ocaml/dune

- ROADMAP.org
- doc/manual.org
* fix a bunch of typos
* s/rule/alias/ in the alias section
* clarify that multiple exe's in the same dir with a different build conf. are
possible
> Fix up manual/roadmap

- .travis.yml
Will work against OCaml 4.0{2,3,4} and Linux, OSX
@diml you will need to enable travis yourself as you need to be an admin in the
org
> Add .travis file

- src/ansi_color.ml
- src/ansi_color.mli
- src/context.ml
- src/future.ml
- src/gen_rules.mli
- vendor/re/src/jbuild
- remove some ocamldoc comment in jbuilder source
- remove warning about color option unconditionally
> Compatibility for 4.02.3

- doc/manual.org
- src/gen_rules.ml
- src/jbuild_types.ml
Useful for running tests for a specific package
will update docs approved
> Specify package for aliases

- doc/quick-start.rst
It was scheme, now it's OCaml.
> Fix language choice for example in docs.

- doc/quick-start.rst
Since the ppx_deriving line isn't entirely obvious, and I haven't seen documented elsewhere.
> Add an example showing how to use ppx_jane

- Makefile
- bin/main.ml
- doc/jbuild
- src/build_system.ml
- src/build_system.mli
- src/path.mli
Added clean subcommand in reference to issue #80
> Add clean subcommand

- src/gen_rules.ml
This is a follow-on suggestion for work in 6a8a440 as part of #119.
@diml - the special case in 6a8a440 does indeed allow jbuild files to be set up to work for MSVC without warning. However, it forces the OCaml syntax because you need files like this:
```
let c_library_flags =
(* This causes LNK4006 and LNK4221 warnings.
* See:
*   - https://github.com/janestreet/jbuilder/issues/119
*   - https://github.com/alainfrisch/flexdll/pull/32
*   - https://github.com/ocaml/ocaml/pull/1189
*)
if List.mem ("ccomp_type", "msvc") J.ocamlc_config then {|
(c_library_flags (:standard gdi32.lib user32.lib shell32.lib advapi32.lib))|}
else {|
(c_library_flags (:standard -lgdi32 -luser32 -lshell32 -ladvapi32))|}
```
This PR extends what you've done slightly to allow `-lgdi32` to be used even on MSVC. …
> Further MSVC C library import hacking

- src/merlin.ml
This check is done in add_rules and dot_merlin. Only of those checks is
necessary. The check in dot_merlin is removed.
Little blemish that I noticed.
> Remove duplicate check for merlin context

- README.md
- bin/main.ml
This is a fairly innocuous pull request which fixes a small typo that I stumbled upon while browsing the documentation.
> Fixed a typo in the documentation.

- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
- src/super_context.ml
Here's a quick hack to support the pattern attempted by @jberdine. It seems like
a legitimate use case, so it would be nice make this work somehow.
> support ${..} in :include

- src/odoc.ml
This commit changes the top-level index of the docs generated by Jbuilder so that the index lists all installed libraries (Findlib library packages generated by Jbuilder), rather than only opam packages. For example, current Markup.ml installs libraries
markup
markup.lwt
markup.lwt.unix
With this change, all these libraries are listed in the index. Before this change, only `markup` was listed, because it happened to coincide with the name of the opam package that contains all three libraries.
Not listing the extra libraries makes them undiscoverable, as they can only be reached by direct URL.
> Docs: list all libraries in top-level index

- doc/usage.rst
> Document utop command

- src/lib_db.ml
Indicate which name is duplicated in which jbuild files
Fix #244
I've elected not to drop the build context from the report jbuild sources because the error might only occur in a particular context since the jbuild file can be generated. Opinions on this decisions are welcome.
> Report duplicate names with a good error message

- src/gen_rules.ml
- src/odoc.ml
- src/odoc.mli
Reverts janestreet/jbuilder#290
> Revert "RFC update odoc rules"

- Makefile
In case new rules are introduced in Makefile.dev
> Set default goal explicitly in Makefile

- .travis.yml
- jbuild-workspace.dev
> 4.06.0 boilerplate

- bootstrap.ml
Fixes https://github.com/janestreet/jbuilder/issues/322
> Quote programs in the bootstrap script

- src/import.ml
- src/meta.ml
Fixes https://github.com/janestreet/jbuilder/issues/331
> Escape double quotes for META field values

- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/ocaml-syntax/jbuild
- test/blackbox-tests/test-cases/ocaml-syntax/run.t
A fairly important feature that isn't tested anywhere.
> Simple test for the ocaml syntax for jbuild files

- .travis-ci.sh
- test/blackbox-tests/cram.mll
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/odoc/jbuild
- test/blackbox-tests/test-cases/odoc/run.t
Test that `$ jbuilder build @doc` and generates an index.
> Odoc tests

- jbuilder.opam
Add test commands and test dependencies. This isn't used for CI, but the plan is to add a CI step that does makes use of these.
> Update opam file for tests

- src/super_context.ml
- test/blackbox-tests/test-cases/reason/jbuild
- test/blackbox-tests/test-cases/reason/pp/jbuild
- test/blackbox-tests/test-cases/reason/pp/reasononlypp.ml
- test/blackbox-tests/test-cases/reason/run.t
Fix the bug found while writing #359
> Reason preprocess fix

- .travis-ci.sh
- jbuilder.opam
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/ppx-rewriter/jbuild
- test/blackbox-tests/test-cases/ppx-rewriter/ppx/fooppx.ml
- test/blackbox-tests/test-cases/ppx-rewriter/ppx/jbuild
- test/blackbox-tests/test-cases/ppx-rewriter/run.t
I wanted to write some ppx rewriter tests because the linting PR was going to touch this stuff a little bit and I've come across this little issue. I'm not sure how to pass custom driver arguments when I use ppx_driver as my driver. See the last failing test.
> Ppx rewriter tests

- .travis-ci.sh
- jbuilder.opam
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/utop/forutop/forutop.ml
- test/blackbox-tests/test-cases/utop/forutop/jbuild
- test/blackbox-tests/test-cases/utop/init_forutop.ml
- test/blackbox-tests/test-cases/utop/run.t
Test the `$ jbuilder utop` command.
> Utop tests

- test/blackbox-tests/test-cases/meta-gen/run.t
- test/blackbox-tests/test-cases/meta-gen/src/jbuild
Makes sure that that directory option is used appropriately in the META
> Add test for sub library in sub dir

- src/import.ml
I've just faced a stack overflow because of this.
> Make split_lines tailrec.

- .travis-ci.sh
- test/blackbox-tests/jbuild
Current version of reason doesn't install on travis. We'll revert this once reason makes a point release.
cc @jordwalke
> Disable reason tests for now

- src/jbuild.ml
- src/jbuild.mli
- src/jbuild_load.ml
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/include-loop/a.inc
- test/blackbox-tests/test-cases/include-loop/b.inc
- test/blackbox-tests/test-cases/include-loop/c.inc
- test/blackbox-tests/test-cases/include-loop/jbuild
- test/blackbox-tests/test-cases/include-loop/run.t
> Detect recursive includes

- test/blackbox-tests/test-cases/odoc/run.t
- test/blackbox-tests/test-cases/odoc/test.mld
cc @diml I just forgot to check in this file.
> Test custom mld usage in odoc tests

- src/lib_db.ml
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/scope-bug/alib/jbuild
- test/blackbox-tests/test-cases/scope-bug/blib/jbuild
- test/blackbox-tests/test-cases/scope-bug/blib/sub/jbuild
- test/blackbox-tests/test-cases/scope-bug/run.t
Here's a test witnessing a scope handling bug when generating META files. I'm pretty sure that this is an issue elsewhere as well, but this is my minimal reproducible example.
> META generation bug in different scopes

- test/blackbox-tests/test-cases/meta-gen/jbuild
- test/blackbox-tests/test-cases/meta-gen/run.t
A library that has been pp'd with a preprocessor that has runtime deps
> Add another test case for meta generation

- README.md
> Mention the jbuilder -> dune rename in readme

- src/gen_rules.ml
Straight forward simplifications.
> replace double fanout with fanout3

- src/odoc.ml
the lib component isn't just a library name. It can contain the scope as well
which we should resolve correctly
> Fix scoping related odoc rules

- src/lib_db.ml
The dirs must be sub directories of the anonymous_scope path. Which is the build
root of the context of the lib db.
> Verify that scope by path lookup uses valid dirs

- bin/main.ml
> Make target_hint not fail when target is Path.root

- Makefile
- bin/main.ml
- doc/jbuild.inc
- src/clflags.ml
- src/clflags.mli
- src/config.ml
- src/config.mli
- src/main.ml
- src/scheduler.ml
> Add `(jobs N)` in the config file

- src/lib_db.ml
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/installable-dup-private-libs/a1/jbuild
- test/blackbox-tests/test-cases/installable-dup-private-libs/a2/jbuild
- test/blackbox-tests/test-cases/installable-dup-private-libs/run.t
Fixes #502. The top closure was also buggy.
> Fix private dup installable

- src/merlin.ml
We know the build directory of exteranl packages, hence we should simply use it.
This is extracted from #498 . It's a big enough change to give it its own commit here. I've tested this myself on a couple of projects and it seems to work the same.
> Change .merlin generation to not use PKG

- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/merlin-tests/exe/jbuild
- test/blackbox-tests/test-cases/merlin-tests/jbuild
- test/blackbox-tests/test-cases/merlin-tests/lib/jbuild
- test/blackbox-tests/test-cases/merlin-tests/ppx/jbuild
- test/blackbox-tests/test-cases/merlin-tests/run.t
- test/blackbox-tests/test-cases/merlin-tests/sanitize-dot-merlin/jbuild
- test/blackbox-tests/test-cases/merlin-tests/sanitize-dot-merlin/sanitize_dot_merlin.ml
These require post-processing all the absolute paths out of the .merlin.
@diml if you have ideas on how to make the post-processing simpler I'd be happy to hear them.
> Add .merlin tests

- src/import.ml
- src/loc.ml
- src/log.ml
- src/process.ml
- src/report_error.ml
- src/scheduler.ml
- src/scheduler.mli
The status line wasn't properly cleared
> Fix printing of errors

- src/context.ml
- src/context.mli
- src/import.ml
- src/jbuild_load.ml
- src/ocamlc_config.ml
- src/ocamlc_config.mli
The context module is getting quite hairy.
> Move reading/reading ocamlc -config to own module

- .travis-ci.sh
We also use the ppx but we should list these dependencies explicitly
> Explicitly depend on the jsoo compiler for tests

- bin/main.ml
- src/action.ml
- src/build_system.ml
- src/context.ml
- src/gen_rules.ml
- src/jbuild.ml
- src/lib.ml
- src/ocamlc_config.ml
- src/ocamldep.ml
- src/ordered_set_lang.ml
- src/path.ml
- src/scope.ml
- src/sexp.ml
- src/sexp.mli
- src/string_with_vars.ml
- src/super_context.ml
- src/usexp/parser_automaton_internal.ml
- src/usexp/sexp_ast.ml
- src/usexp/usexp.ml
- src/usexp/usexp.mli
- src/utils.ml
- src/with_required_by.ml
- src/workspace.ml
This is to discuss of making `Atom.t` private (see also https://github.com/ocaml/dune/pull/459).
> WIP Make Atom.t private (and consequences)

- src/modules_partitioner.ml
- test/blackbox-tests/test-cases/ocamldep-multi-stanzas/run.t
Specify how to fix the error (by writing modules fields)
> Improve error in modules partition

- CHANGES.md
- src/jbuild.ml
> Accept and ignore ppx.driver fields

- doc/tests.rst
- src/inline_tests.ml
> Allow to specify additional libraries for the test runner

- src/lib.ml
- src/lib.mli
- src/odoc.ml
- src/preprocessing.ml
Get the package of a library and also include it in the status of pulbic
libraries.
@diml your commit from the doc PR
> Implement Lib.package

- src/install_rules.ml
- src/super_context.ml
- src/super_context.mli
Will be used for odoc and installation
> Add a map from package names to libraries to super context

- doc/jbuild.rst
- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/build_interpret.mli
- src/build_system.ml
- src/build_system.mli
- src/fiber/fiber.ml
- src/fiber/fiber.mli
- src/gen_rules.ml
- src/install_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/odoc.ml
- src/super_context.ml
- src/super_context.mli
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/package-dep/jbuild
- test/blackbox-tests/test-cases/package-dep/run.t
Implement #621. @diml does this look right? I think I just need to add some better validation of the package name itself.
> Add package dependency

- src/env.ml
> Handle duplicate environment variables

- src/odoc.ml
- test/blackbox-tests/test-cases/odoc/jbuild
- test/blackbox-tests/test-cases/odoc/run.t
Found this bug when expanding the odoc test suite...
> Fix odoc lazy load

- src/gen_rules.ml
- src/odoc.ml
- test/blackbox-tests/test-cases/odoc/run.t
@trefis how about this version of #653? I've added the missing newlines that Anton wanted.
> Cosmetic changes for default package entry point.

- .travis.yml
> Disable OSX tests

- src/super_context.ml
Some simple omissions that were noticed in #746
> Pass some missing loc's when using Path.relative

- src/context.ml
- src/stdune/path.ml
The main change here is the the move to rely on Path.kind over the conditional checks. The delta between this patch and symbolic paths should be quite reasonable.
> Path refactorings.

- doc/faq.rst
These links where broken on [jbuilder.readthedocs.io](http://jbuilder.readthedocs.io/en/latest/faq.html).
> Fix broken link ?

- MIGRATION.md
This PR adds a `MIGRATION.md` file explaining how the transition to Dune will happen with a timeline for the various steps.
> Add a migration file

- bin/main.ml
- src/action.ml
- src/process.ml
- src/process.mli
The elements are unique and the order isn't well defined anyway.
> Change Build_job to be set

- src/build.ml
- src/super_context.ml
> Replace dyn_paths with dyn_path_set

- src/odoc.ml
- test/blackbox-tests/test-cases/odoc/run.t
This in turn lets us try @rizo's extremely cool PR in https://github.com/ocaml/odoc/pull/139 with a wider set of packages :-)
> Fix doc generation with odoc-master branch

- src/findlib.ml
> Remove extra set to list conversion

- src/package.ml
- src/stdune/interned.ml
- src/stdune/interned.mli
- src/sub_system_name.ml
- src/variant.ml
I accidentally removed this in the last PR. I think it should probably be brought back.
> Make Interned generative again

- src/build_system.ml
> Remove an extra conversion in rules_for_files

- src/stdune/interned.ml
- src/stdune/interned.mli
> Add No_interning module for easy experimentation

- src/build_system.ml
This fixes the issue with `make test` in #796
> Fix an issue when a file is part of several packages

- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/super_context.ml
> Change Paths_glob to return a set of paths

- src/merlin.ml
- test/blackbox-tests/test-cases/merlin-tests/run.t
This fixes the regression introduced in #805
> Merlin fix

- src/super_context.ml
The second change I'm not 100% sure about. Was there a reason for the ordering? Otherwise, won't the 2nd commit give us better parallelization?
> Little cleanups

- test/blackbox-tests/test-cases/gen-opam-install-file/ppx-new/dune
- test/blackbox-tests/test-cases/gen-opam-install-file/ppx-old/jbuild
- test/blackbox-tests/test-cases/gen-opam-install-file/run.t
The example should work with dune and jbuild files.
> Add a ppx rewriter example for the generated install file

- src/build_system.ml
- src/stdune/hashable.ml
- src/stdune/hashtbl.ml
- src/stdune/hashtbl.mli
- src/stdune/hashtbl_intf.ml
- src/stdune/path.ml
- src/stdune/path.mli
This should give us the opportunity to experiment with faster hashes and interning
> Add Path.Table

- src/package.ml
- src/stdune/interned.ml
- src/stdune/interned.mli
- src/stdune/path.ml
- src/sub_system_name.ml
- src/variant.ml
@diml the choices that I've made are a bit of arbitrary here but this should give us the control that we want.
> Add an intern option to control ordering

- doc/index.rst
- doc/jbuild.rst
- doc/menhir.rst
> Give menhir its own section in the docs

- src/module.mli
> Remove module name private type

- CHANGES.md
> Add a couple of entries to the change log

- src/jbuild.ml
> Use extension parameter in error message

- src/fiber/fiber.ml
- src/stdune/stdune.ml
- src/stdune/univ_map.ml
- src/stdune/univ_map.mli
So that we can reuse them for Of_sexp
> Move universal maps from Fiber to Stdune

- CHANGES.md
- doc/jbuild.rst
- example/dune
- src/build.ml
- src/build.mli
- src/jbuild.ml
- src/jbuild.mli
- src/super_context.ml
- test/blackbox-tests/dune
- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/misc/dune
- test/unit-tests/dune
To make it clearer it doesn't include generated files.
> Rename files_recursively_in to source_tree

- src/jbuild.ml
> Select lexer based on dune vs jbuild

- src/inline_tests.ml
- src/jbuild.ml
- src/jbuild.mli
- src/preprocessing.ml
- src/stanza.ml
- src/stanza.mli
> Move Jbuild.syntax to Stanza module

- src/dune_project.ml
- src/fiber/fiber.ml
- src/stdune/univ_map.ml
- src/stdune/univ_map.mli
- src/syntax.ml
Very useful for debugging. @diml hopefully adding this debug info isn't too much of a performance penalty.
> Add sexp conversion to univeral maps

- test/bulk-update.sh
I wrote this small script while updating the tests for a feature I'm working on.
> Sscript to help updating all the tests

- bin/main.ml
- src/action.ml
- src/build_system.ml
- src/build_system.mli
- src/super_context.ml
- src/utils.ml
- src/utils.mli
- src/vfile_kind.ml
- src/vfile_kind.mli
Fix #916 
Will add the other files as separate commits
> Use Util.Persistent to reimplemented promoted files store

- doc/migration.rst
> Update table of renamed vars in docs

- doc/quick-start.rst
> Port quick start to dune syntax

- doc/advanced-topics.rst
- doc/configurator.rst
- doc/documentation.rst
- doc/faq.rst
- doc/index.rst
- doc/project-layout-specification.rst
- doc/usage.rst
This migrates the rest of the manual to use dune
> More Manual Updates

- bin/main.ml
- src/build_system.ml
- src/stdune/list.ml
- src/stdune/list.mli
> Add List.find_exn

- .travis-ci.sh
We should be testing the most recent combination we can
> Change ppx_driver dep to ppxlib

- .travis-ci.sh
cc @diml. I'll merge this asap since it's obviously correct. Sorry for this.
> Extra ppxlib was listed instead of reason

- doc/dune-files.rst
> Update documentation for executable stanza format

- src/report_error.ml
You get a quote from Dune if you can make Dune crash. Credit goes to [David Powers](https://blog.janestreet.com/author/dpowers/).
> Exceptions are the little-death that brings total obliteration

- src/stanza.ml
- test/blackbox-tests/test-cases/dune-project-edition/run.t
@diml @emillon I'm merging this because the env stanza is already in and this commit is necessary for it and many others.
> Update latest syntax to 1.1

- doc/quick-start.rst
https://discuss.ocaml.org/t/jbuilder-to-dune-what-is-first-dep/2356/3
> doc: remove %{first-dep} in quick-start.rst

- CHANGES.md
> Update CHANGELOG with optional names entry

- .travis-ci.sh
We can achieve the same effect with OPAMYES="true"
> Remove all --yes from travis

- doc/quick-start.rst
In addition, document the convention for expect tests.
cc @gpetiot
> Quickstart: use short test stanza

- src/lib_rules.ml
> Fix msvc_hack_cclibs using combinators

- src/lib_rules.ml
Since all the library rules are in the same module, we have more flexibility in organizing them. All the changes are basically moving stuff around and the main little thing to note is that we're adding the rule to generate the alias module a little later. Before we were doing it after setting up the compilation rules for normal modules, now we're doing it right before setting up the compilation rule for the alias module. This doesn't seem to make a difference.
> Split library rules into more logical steps

- src/syntax.ml
> Add context and all supported versions when an syntax id is unset

- src/dir_contents.ml
- src/dune_file.ml
- src/dune_project.ml
- src/dune_project.mli
- src/install_rules.ml
- src/jbuild_load.ml
- src/lib.ml
- src/scope.ml
- src/super_context.ml
> Make Dune_project.t abstract

- bin/main.ml
- src/artifacts.ml
- src/context.ml
- src/dsexp/dsexp.ml
- src/dune_file.ml
- src/findlib.ml
- src/install_rules.ml
- src/installed_dune_file.ml
- src/module.ml
- src/ocaml-config/ocaml_config.ml
- src/ocamldep.ml
- src/process.ml
- src/scheduler.ml
- src/scope.ml
- src/stdune/filename.ml
- src/stdune/list.ml
- src/stdune/list.mli
- src/stdune/path.ml
- src/stdune/pp.ml
- src/stdune/string.ml
- src/stdune/string.mli
- src/watermarks.ml
- test/unit-tests/dune
- test/unit-tests/string.mlt
This simplifies quite a lot of code
> Introduce String.{take,drop,split_n}

- src/dir_contents.ml
- src/dir_contents.mli
Make records privates and add internal signature to Library_modules
> Make types in Dir_contents more private

- src/dune_file.ml
- src/dune_file.mli
- src/install_rules.ml
* Install .o files corresponding to .cmx files
* Install .o files for stubs
* Do not install archive files
> Adjust install files for virtual libraries

- src/lib_rules.ml
Building virtual libraries and implementations complicates the build 2 folds:
* Virtual libraries cannot construct archives
* Implementations will also come with external .o files that will need to be linked (from stubs)
Also, I suggest that we disable `build_self_stubs` for virtual libraries as in my comment in the source.
> Disable archives for virtual libraries

- src/inline_tests.ml
- src/preprocessing.ml
- src/sub_system.ml
> Simplify some Result.List.all

- src/dir_contents.ml
- src/dir_contents.mli
- src/dune_file.ml
- src/install_rules.ml
- src/lib_rules.ml
- src/module.ml
- src/module.mli
- test/blackbox-tests/test-cases/intf-only/run.t
- test/blackbox-tests/test-cases/variants/invalid-virtual-lib/dune
- test/blackbox-tests/test-cases/variants/invalid-virtual-lib/dune-project
- test/blackbox-tests/test-cases/variants/module-fields/test.ml
- test/blackbox-tests/test-cases/variants/run.t
Check that it doesn't overlap with other fields and signal appropriate errors.
> Interpret virtual modules field

- src/lib_rules.ml
We could also just move all this logic to `Lib_file_deps`, but I'm not sure if it's worth it to spread the lib rules across multiple modules at this point. This is just the minimum required for doing virtual libraries in a more obvious way.
> Move setting lib file aliases to separate function

- src/dune_file.ml
- src/dune_project.ml
- src/dune_project.mli
- test/blackbox-tests/test-cases/variants/run.t
These extension provide the minimum version by default
> Add support for experimental extensions

- doc/quick-start.rst
> Use Configurator.V1 in the docs as example for cstubs

- doc/usage.rst
> Document --watch flag

- bin/arg.ml
- bin/common.ml
- bin/common.mli
- bin/dune
- bin/main.ml
- bin/target.ml
- bin/target.mli
- bin/util.ml
- bin/util.mli
- src/stdune/env.ml
- src/stdune/env.mli
- src/stdune/proc.ml
- src/stdune/proc.mli
- src/stdune/stdune.ml
Some of the organization/naming choices that were made here aren't optimal, but it should still be an improvement. Subsequent PR's should improve things further.
> Cleanup CLI by splitting it into more modules

- HACKING.md
- README.md
This section is no longer relevant
> Remove jenga from the README

- src/lib.ml
- src/preprocessing.ml
- src/stdune/result.ml
- src/stdune/result.mli
The folding change was rejected before because I accidentally change the order. This time, the order should be the same.
> Trivial simplifications

- src/module_compilation.mli
I hope I would not have made the error of #1310 with this added documentation.
> [Doc] Precise that nodynlink also have an impact on .so.

- HACKING.md
- Makefile
> Describe testing in the hacking doc

- src/arg_spec.ml
- src/arg_spec.mli
- src/build_system.ml
- src/import.ml
- src/stdune/nothing.ml
- src/stdune/nothing.mli
- src/stdune/stdune.ml
- src/stdune/type_eq.ml
- src/stdune/type_eq.mli
- src/stdune/univ_map.ml
- src/vfile_kind.ml
- src/vfile_kind.mli
> Move the eq and nothing types to stdune

- src/context.ml
- src/findlib.ml
- src/findlib.mli
- src/lib_info.ml
- test/unit-tests/tests.mlt
> Findlib.path is oddly named as it corresponds to a list of path

- doc/quick-start.rst
> Expand "dune exec" example

- dune.opam
They only apply for the 2.0 versions of the rules
> Remove the constraints on menhir

- src/install_rules.ml
- src/package.ml
- src/package.mli
passing the path and name separately just makes things a bit more complicated
> Pass package directly to install rules

- README.md
Related to #1412 
- Link to cross-compilation chapter in official Dune documentation
> DOC: Readme cross-compilation link

- editor-integration/emacs/dune.el
Fixes https://github.com/ocaml/dune/issues/1452
Signed-off-by: Christophe Troestler <Christophe.Troestler@umons.ac.be>
> Fix occurrence of an old variable

- doc/faq.rst
See #1465 (cc @XVilka)
Thanks!
> FAQ: How to make warnings non-fatal?

- bin/main.ml
- test/blackbox-tests/test-cases/exec-cmd/run.t
Signed-off-by: Aaron L. Zeng <me@bcc32.com>
> Fix typo in exec error message

- src/build_system.ml
- src/gen_rules.ml
- src/lib.ml
- src/lib_rules.ml
- test/unit-tests/sexp.mlt
- test/unit-tests/tests.mlt
As discussed in #1502, this style of comment will not be preserved by ocamlformat.
> Turn banner comments into plain comments

- src/preprocessing.ml
> Fix preprocessing of jbuild projects

- src/build_system.ml
- src/build_system.mli
- src/format_rules.ml
> Make the fmt alias builtin

- doc/tests.rst
Just a few things I noticed were out of date or incorrect as I was playing around with inline testing
> Minor updates to the testing documentation

- src/format_rules.ml
Wait until we've loaded the directory
> Do not evaluate files in source_dir early

- bin/main.ml
- src/build_system.ml
- src/dir_contents.ml
- src/gen_rules.ml
- src/main.ml
- src/preprocessing.ml
- src/scope.ml
- src/stdune/hashtbl.ml
- src/stdune/hashtbl.mli
- src/stdune/hashtbl_intf.ml
- src/stdune/map.ml
- src/stdune/map_intf.ml
- src/versioned_file.ml
> Simpliify some duplicate code with find_exn

- src/compilation_context.ml
- src/compilation_context.mli
- src/exe.ml
- src/exe_rules.ml
- src/inline_tests.ml
- src/js_of_ocaml_rules.ml
- src/lib_rules.ml
- src/link_time_code_gen.ml
- src/menhir.ml
- src/utop.ml
> Include expander in Compilation_context

- doc/project-layout-specification.rst
- doc/usage.rst
> Document what dune-project (name) does

- src/pform.ml
- src/pform.mli
- src/syntax.ml
- src/syntax.mli
That function is pretty useful when debugging expanders.
> Add Pform.Map.pp_debug

- src/install_rules.ml
> Pass package version to dune package file

- src/action_exec.ml
- src/build_system.ml
- src/deps.ml
- src/deps.mli
- src/dune_lang/atom.ml
- src/dune_lang/atom.mli
- src/preprocessing.ml
- src/report_error.ml
- src/stdune/caml/dune_caml.ml
- src/stdune/digest.ml
- src/stdune/digest.mli
- src/stdune/stdune.ml
- src/utils.ml
Being able to mix this with strings was not very good.
> Make Digest type abstract

- README.md
Signed-off-by: Anil Madhavapeddy <anil@recoil.org>
> README: update to reflect that dune 1.0 is now out

- src/action_dune_lang.ml
- src/action_dune_lang.mli
- src/inline_tests.ml
- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
- src/preprocessing.ml
- src/string_with_vars.ml
- src/string_with_vars.mli
- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
Do this when encoding subsystems
Fix #1631
> Upgrade templates for subsystems

- src/string_with_vars.ml
In particular, this should fix the travis builds
> Upgrade the syntax of variables to %{...}

- test/unit-tests/memoize.mlt
> Do not include signatures in memoize tests

- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/unit-tests/dune
> Disable tests in 4.05 that doesn't work

- CONTRIBUTING.md
> PRs should be made against master

- src/scheduler.mli
- src/stanza.ml
- test/blackbox-tests/test-cases/too-many-parens/run.t
Found one of the error hints a bit jarring, so I fixed it.
> Correct 'less' to 'fewer' in several places

- src/bootstrap.boot.ml
- src/bootstrap.ml
- src/bootstrap.mli
- src/dune_load.ml
- src/dune_load.mli
- src/file_tree.ml
- src/file_tree.mli
- src/main.ml
And replace it by a `Bootstrap` module that has a special implementation during bootstrap.
> Remove extra_ignored_subdirs argument

- src/catapult/catapult.ml
> Fix 4.02 build + do less work when tracing is disabled

- bin/main.ml
- src/build_system.ml
- src/build_system.mli
- src/hooks.ml
- src/hooks.mli
- src/scheduler.ml
- src/scheduler.mli
- src/utils.ml
- src/utils.mli
Make the code of the various components more self-contained.
> Simplify db management

- src/context.ml
- src/context.mli
- src/install_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_modules.ml
- src/lib_rules.ml
- src/module.ml
- src/ocamldep.ml
- src/ocamlobjinfo.mli
- src/ocamlobjinfo.mll
- src/virtual_rules.ml
- src/virtual_rules.mli
- test/blackbox-tests/test-cases/variants/run.t
> Restore dependency graph from ocamlobjinfo

- bench/scheduler_bench.ml
> Fix fiber benchmarks

- bin/install_uninstall.ml
- src/action_unexpanded.ml
- src/bindings.ml
- src/build.ml
- src/build_system.ml
- src/context.ml
- src/dune_file.ml
- src/dune_lang/dune_lang.ml
- src/dune_package.ml
- src/exe.ml
- src/format_rules.ml
- src/gen_rules.ml
- src/js_of_ocaml_rules.ml
- src/lib.ml
- src/lib_modules.ml
- src/lib_rules.ml
- src/memo/memo.ml
- src/odoc.ml
- src/preprocessing.ml
- src/stdune/either.ml
- src/stdune/either.mli
- src/stdune/fn.ml
- src/stdune/fn.mli
- src/stdune/io.ml
- src/stdune/stdune.ml
- src/stdune/string.ml
- src/super_context.ml
and simplify some code using constructor functions and the Fn module.
> Add Fn module to stdune

- src/build_system.ml
- src/deps.ml
- src/deps.mli
> Move parallel iteration to Deps module

- doc/dune-files.rst
> `subdirs` -> `dirs`

- src/dep_path.ml
- src/dep_path.mli
- src/exe_rules.ml
- src/lib.ml
- src/lib.mli
- src/stdune/fmt.ml
- src/stdune/fmt.mli
- src/sub_system.ml
- test/blackbox-tests/test-cases/lib-errors/run.t
- test/blackbox-tests/test-cases/variants/run.t
> Improve error messages for invalid deps for exes

- src/dune_lang/dune_lang.ml
- src/dune_lang/dune_lang.mli
- src/dune_lang/dune_lexer.mll
- src/dune_lang/jbuild_lexer.boot.ml
- src/dune_lang/jbuild_lexer.mll
- src/dune_lang/lexer.ml
- src/dune_lang/lexer.mli
- src/dune_lang/lexer_shared.ml
- src/dune_lang/lexer_shared.mli
- src/installed_dune_file.ml
- test/unit-tests/sexp.mlt
This should help for `dune fmt` /cc @emillon
> Add a version of the parser that preserves comments

- .travis-ci.sh
- .travis.yml
The CI test seems to be broken. This test is also a bit annoying in general.
> Remove CI test checking that CHANGES.md was modified

- src/dune_file.ml
This kind of handling will be useful for the toplevel stanza and the upcoming
c_executables stanza.
> Factor our name/public name handling

- test/blackbox-tests/test-cases/menhir/run.t
This test needs sorting to work on OSX & Travis
> Sort results for mock test

- src/link_time_code_gen.ml
> Fix link time code gen for 4.02

- .gitignore
- .travis-ci.sh
- src/c_sources.ml
- src/c_sources.mli
- src/dir_contents.ml
- src/stdune/string.ml
- src/stdune/string.mli
- test/blackbox-tests/test-cases/duplicate-c-cxx-obj/run.t
- test/blackbox-tests/test-cases/duplicate-c-cxx/run.t
- test/blackbox-tests/test-cases/github734/run.t
Addressing @diml's comments from #1788
> Improve error message & add docs

- editor-integration/emacs/dune-flymake.el
- editor-integration/emacs/dune.el
Fixes to be able to publish it on MELPA.
> Emacs dune mode

- src/configurator/v1.ml
- src/configurator/v1.mli
I took some time to propose another interface to run commands.  Let me know what you think.
> Export commands to run programs and capture their output

- src/memo/memo.ml
- src/memo/memo.mli
> Use Format to pp memoized callstack

- src/preprocessing.ml
The previous code had a bit of duplication between Linting and preprocessing. Also, I removed the `Build.action_dyn` wrapping, @diml was it necessary?
> Factor out common handling of Action for lint/pp

- .travis-ci.sh
I'm not sure why it's there in the first place
> Remove wrong dune version from CI

- editor-integration/emacs/dune.el
Account for:
* virtual_modules, implements
* binaries in env
* toplevel stanza
> Update emacs syntax highlighting

- doc/dune-files.rst
Signed-off-by: Louis Roché <louis@louisroche.net>
> doc: fix typo

- CHANGES.md
- src/catapult/catapult.ml
- src/stdune/stdune.ml
- test/blackbox-tests/test-cases/trace-file/run.t
- test/unit-tests/catapult.mlt
This adds some useful stats to the catapult counters. @emillon was there a reason why most stats were omitted?
> Some GC stats were missing

- src/build_system.ml
> build_system.gen_rules is set only once

- src/gen_rules.ml
- src/install_rules.ml
- src/install_rules.mli
- src/lib_rules.ml
- src/local_package.ml
- src/local_package.mli
- src/package.ml
- src/package.mli
- src/stdune/id.ml
- src/stdune/id.mli
- src/stdune/option.ml
- src/stdune/option.mli
This is the last instance of on_load_dir. @diml should I get rid of this functionality in build_system.ml?
I could also memoize generating the `Path.Map.t` map for better perf.
> Reomve on load dir

- src/build_system.ml
- src/predicate.ml
- src/predicate.mli
- src/stdune/stdune.ml
- src/stdune/tuple.ml
- src/stdune/tuple.mli
> Memoize the evaluation of predicate

- src/gen_rules.ml
> Make sure that all js_targets are in ctx_dir

- src/dir_contents.ml
- src/dir_contents.mli
- src/gen_rules.ml
- src/memo/memo.ml
- src/memo/memo.mli
- test/unit-tests/memoize.mlt
> Create a type Memo.Lazy.t to make it easier to reason about performance.

- src/build_system.ml
This list should include the targets create by running the actions.
Am I missing something? How was this omitted before?
> Fix the full list of tagrets in the alias dir

- .github/CODEOWNERS
Let me know if you wanna add your name to the list.
> [coq] [github] Update codeowners for Coq code.

- src/c.ml
- src/c.mli
- src/c_sources.ml
- src/dir_contents.ml
- src/dune_env.ml
- src/dune_env.mli
- src/dune_file.ml
- src/dune_file.mli
- src/env_node.ml
- src/env_node.mli
- src/expander.ml
- src/expander.mli
- src/lib_rules.ml
- src/mode.ml
- src/mode.mli
- src/ocaml_flags.ml
- src/ocaml_flags.mli
- src/super_context.ml
- src/super_context.mli
This removes a bunch of extraneous conversions and shares decoding code. I will do something similar for the C flags.
> Merge flags field into common record

- src/coq_rules.ml
If the ibrary in the dependency doesn't belong to the same package we
should not install the compatibility rule for the plugin.
For example `Coq-Equations` does:
```
(libraries coq.plugins.extraction equations.plugin)
```
but only the compat link for `equations` should be installed.
> [coq] Don't install compat rule for lib dependencies not in the same package.

- src/build_system.ml
Previously, this was done manually
> Memoize mkdir_p

- src/dune_file.ml
- src/dune_project.ml
- src/dune_project.mli
> Add root discovered by dune to package error message

- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/path_intf.ml
This module signature shares the basic functions that should be present in all
path variants. This is i preparation for the cleanup that we are planning.
> Introduce Path_intf.S

- src/lib_modules.ml
- src/lib_modules.mli
- src/vimpl.mli
Also remove unused Lib_modules.have_artifacts function
> Add documentation to Lib_modules and Vimpl

- src/coq_rules.boot.ml
> Do not compile coq rules for bootstrap

- doc/dune-files.rst
I recently had to use that feature and couldn't remember how to do it so I thought about improving the documentation around it a little!
Let me know what you think!
> Add documentation and example for test stanza action override

- src/env_node.ml
- src/expander.ml
- src/ocaml_flags.ml
- src/super_context.ml
Seem like all of these checks can be done in the expander.
> Simplify has_special_forms checks

- test/blackbox-tests/test-cases/coq/run.t
> fix coq tests that I broke in #2105

- src/dune_file.ml
> fix ppx args parsing in jbuild for backwards compatibility

- src/action.ml
- src/action.mli
- src/artifacts.ml
- src/ocamlobjinfo.mll
Now it must be created via a constructor
> Make Not_found a private type

- src/watermarks.ml
- test/blackbox-tests/test-cases/dune-project-meta/run.t
@rgrinberg, this is what I was thinking about
> Expose the issue between `dune subst` and opam file generation

- test/unit-tests/vcs.mlt
> do not let the git tests escape the build directory

- src/scheme.mli
> Add docs for Scheme

- src/action.ml
- src/action.mli
- src/action_ast.ml
- src/action_intf.ml
- src/diff.ml
- src/diff.mli
- src/test_rules.ml
Now there's no more duplication in the parsing code.
> De-duplicate action code by adding a Diff module

- src/action_exec.ml
- src/promotion.ml
- src/promotion.mli
We are only allowed to promote from the build directory
> Use Path.Build.t in Promotion

- src/file_tree.ml
- src/file_tree.mli
- src/upgrader.ml
This makes the types more precise at the cost of a bit of conversion
boilerplate.
> Change upgrade to use Path.Source.t

- src/dune_load.ml
The generated dune files live in the build dir and the types now reflect that.
This avoids a check for the build dir when we create the parent dir for example.
> Use build paths where appropriate in dune_load

- bin/common.ml
This seems to be a bit safer. It's a bit of a shame that we don't have an option like `-no-always-show-command-line`, but this is something that should be added more consistently anyways.
> Always show full command in release profile

- editor-integration/emacs/dune.el
> Update list of emacs stanzas

- CONTRIBUTING.md
Signed-off-by: Volker Diels-Grabsch <v@njh.eu>
> Add missing link

- src/preprocessing.ml
They should all be created with the same ~dir argument to add_rule
This change only makes a difference to users who have added a local refmt binary to `binaries` or are using some environment variables meant for `refmt`.
> Create pp rules consistently

- src/virtual_rules.ml
The obj dir is already set correctly. It is set correctly whenever we construct
the Lib_modules.t from the dune-package file.
This is a preliminary PR to the simplification that will follow.
> Do not set the object directory for the vlib external graph

- bin/compute.ml
- src/build_system.ml
- src/build_system.mli
- src/dir_contents.ml
- src/dir_status.ml
- src/install_rules.ml
- src/local_package.ml
- src/memo/memo.ml
- src/memo/memo.mli
- src/odoc.ml
- src/packages.ml
- src/stdune/dyn.ml
- src/stdune/dyn.mli
- src/stdune/dyn0.ml
- src/stdune/int.ml
- src/stdune/int.mli
- src/stdune/interned.ml
- src/stdune/interned.mli
- src/stdune/path.ml
- src/stdune/path_intf.ml
- src/stdune/set.ml
- src/stdune/set.mli
- src/stdune/string.ml
- src/stdune/string.mli
- src/stdune/unit.ml
- src/stdune/unit.mli
- src/vcs.ml
- test/unit-tests/memoize.mlt
> switch memo.mli Sexp => Dyn

- src/context.ml
- src/context.mli
- src/exe.ml
- src/install_rules.ml
- src/lib_archives.ml
- src/lib_config.ml
- src/lib_config.mli
- src/lib_rules.ml
- src/module_compilation.ml
- src/pform.ml
- src/virtual_rules.ml
* Use this type more consistently when possible
* Move some more library configuration options to it
* Make it a part of context so we don't have to create it so many times
This PR is mostly a pre-req for other PR's
> Improve Lib_config.t

- bootstrap.ml
Previously, it would ignore interface deps but that is obviously wrong.
It should use botha intf and impl files to discover deps.
This issue is quite annoying and I've finally gotten sick of tweaking .ml/.mli files to make bootstrap work.
> Fix bootstrap to account for mli deps

- src/obj_dir.ml
Replace it with an elimination function that takes care of common cases
for us.
> Simplify pattern match in Obj_dir

- src/lib.ml
Follow the same convention as Build_system. The diff looks bug, it's mostly whitespace changes due to new indentation.
> Rewrite recursive functions with recursive modules

- editor-integration/emacs/dune.el
Support for 2 new features:
* compiling the stdlib
* build-info library
> Add more keywords to emacs mode

- src/action_exec.ml
- src/build_system.ml
- src/cached_digest.ml
- src/preprocessing.ml
- src/rules.ml
- src/stdune/digest.ml
- src/stdune/digest.mli
Marshalling is a bit of an implementation detail at the moment. I'd prefer not to leak it out everywhere.
> Add Digest.generic

- src/build_system.ml
- src/cached_digest.ml
- src/persistent.ml
- src/persistent.mli
- src/promotion.ml
- src/utils.ml
- src/utils.mli
Another step in eliminating the Utils module
> Move Utils.Persistent to own module

- src/memo/memo.ml
- src/memo/memo.mli
- src/stdune/hashtbl.ml
- src/stdune/hashtbl.mli
- src/stdune/table.ml
- src/stdune/table.mli
This improves the exceptions by letting us print the key
> Add dyn converter to Hashtable functor

- src/binary_kind.ml
- src/binary_kind.mli
- src/coq_module.ml
- src/coq_module.mli
- src/coq_rules.ml
- src/dune_file.ml
- src/dune_file.mli
- src/meta.ml
- src/meta.mli
- src/mode.ml
- src/mode.mli
- src/module.ml
- src/module.mli
- src/static_deps.ml
- src/static_deps.mli
- src/stdune/fmt.ml
- src/stdune/fmt.mli
- test/unit-tests/dune_file.mlt
- test/unit-tests/tests.mlt
This should be enough to get rid of the `Fmt` module.
> Change more functions from pp to to_dyn

- doc/index.rst
I just realised that I forgot to add this new page to the index
> Add installation section to the index

- src/env_node.ml
- src/file_binding.ml
- src/file_binding.mli
- src/gen_rules.ml
- src/install_rules.ml
- src/local_package.ml
We cannot expand to any other kind of paths
> Use build paths in File_bindings.Expanded

- src/inline_tests.ml
- src/lib_rules.ml
- src/sub_system_intf.ml
- test/expect-tests/findlib_tests.ml
Make sure to diff the source files rather than the preprocessed ones.
> Fix expectation tests

- src/print_diff.ml
Fixes https://github.com/ocaml/dune/pull/2391/files#r304309250
> Fix git diff invocation when skipping trailing CRs

- editor-integration/emacs/dune.el
> Emacs mode updates

- src/stanza.ml
- test/blackbox-tests/test-cases/allow_approximate_merlin/run.t
- test/blackbox-tests/test-cases/dune-init/run.t
- test/blackbox-tests/test-cases/dune-package/run.t
- test/blackbox-tests/test-cases/dune-project-edition/run.t
- test/blackbox-tests/test-cases/github1529/run.t
- test/blackbox-tests/test-cases/github1549/run.t
- test/blackbox-tests/test-cases/inline_tests/run.t
- test/blackbox-tests/test-cases/variants-external-declaration/run.t
- test/blackbox-tests/test-cases/variants-only-package/run.t
- test/blackbox-tests/test-cases/variants/run.t
- test/blackbox-tests/test-cases/vlib-default-impl/run.t
- test/blackbox-tests/test-cases/vlib/run.t
Because bumping to 2.0 breaks build of camomile.
> bump version to 1.12 for now

- src/stanza.ml
- test/blackbox-tests/test-cases/dune-init/run.t
- test/blackbox-tests/test-cases/dune-jbuild-var-case/run.t
- test/blackbox-tests/test-cases/dune-package/run.t
- test/blackbox-tests/test-cases/dune-ppx-driver-system/run.t
- test/blackbox-tests/test-cases/dune-project-edition/run.t
- test/blackbox-tests/test-cases/dup-fields/run.t
- test/blackbox-tests/test-cases/embed-jbuild/run.t
- test/blackbox-tests/test-cases/findlib-error/run.t
- test/blackbox-tests/test-cases/github1529/run.t
- test/blackbox-tests/test-cases/github1549/run.t
- test/blackbox-tests/test-cases/github992/run.t
- test/blackbox-tests/test-cases/inline_tests/run.t
- test/blackbox-tests/test-cases/ocamldep-multi-stanzas/run.t
- test/blackbox-tests/test-cases/ocamllex-jbuild/run.t
- test/blackbox-tests/test-cases/path-variables/run.t
- test/blackbox-tests/test-cases/upgrader/run.t
- test/blackbox-tests/test-cases/variants-external-declaration/run.t
- test/blackbox-tests/test-cases/variants-only-package/run.t
- test/blackbox-tests/test-cases/variants/run.t
- test/blackbox-tests/test-cases/vlib-default-impl/run.t
- test/blackbox-tests/test-cases/vlib/run.t
Need CI to debug Camomile issues.
> Bump maximum version to 2, 0

- src/installed_dune_file.boot.ml
> Remove installed_dune_file from bootstrap

- bin/install_uninstall.ml
- src/action_unexpanded.ml
- src/configurator/v1.ml
- src/dune_file.ml
- src/dune_init.ml
- src/dune_lang/atom.ml
- src/dune_lang/atom.mli
- src/dune_lang/dune_lang.ml
- src/dune_lang/dune_lang.mli
- src/dune_lang/escape.ml
- src/dune_lang/escape.mli
- src/dune_lang/template.ml
- src/dune_lang/template.mli
- src/dune_project.ml
- src/format_dune_lang.ml
- src/install_rules.ml
- src/modules_field_evaluator.ml
- src/super_context.ml
- src/watermarks.ml
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/path-variables/run.t
- test/expect-tests/dune_lang/sexp_tests.ml
All dune_lang values are now printed in dune style.
> Remove jbuild style output

- src/dune_lang/template.ml
- src/report_error.ml
- src/stdune/code_error.ml
- src/stdune/code_error.mli
- src/stdune/loc.ml
- src/stdune/loc0.ml
- test/expect-tests/dune_lang/sexp_tests.ml
I wanted this location in a couple of places as the error might originate from some file input.
> Code error loc

- src/stdune/hashtbl.ml
Some simple changes to the hashtable module. See individual commits
> Hashtable tweaks

- bootstrap.ml
This allows one to change switches without redoing bootstrap
> Build bootstrap with -custom in dev

- doc/dune-files.rst
This fixes sphinx warnings and fixes some weird-looking markup.
> Various markup fixes in doc

- .travis-ci.sh
- .travis.yml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/private-modules/run.t
- test/blackbox-tests/test-cases/transitive-deps-mode/run.t
- test/blackbox-tests/test-cases/wrapped-transition/run.t
The changes to promotion are looking suspicious. This needs investigation before it is merged.
> port tests to 4.08

- src/format_rules.boot.ml
> Remove format rules from bootstrap

- bin/arg.ml
- bin/common.ml
- bin/common.mli
- bin/import.ml
- src/config.ml
- src/config.mli
- src/context.ml
- src/context.mli
- src/dune_env.ml
- src/dune_env.mli
- src/env_node.ml
- src/env_node.mli
- src/js_of_ocaml_rules.ml
- src/main.ml
- src/main.mli
- src/ocaml_flags.ml
- src/ocaml_flags.mli
- src/pform.ml
- src/profile.ml
- src/profile.mli
- src/super_context.ml
- src/super_context.mli
- src/workspace.ml
- src/workspace.mli
This gives a proper type for user defined vs builtin profiles
> Add Profile module

- src/dune_file.ml
it should say dune rather than jbuild files
> Fix recursive dune files error message

- src/opam_create.ml
- test/blackbox-tests/test-cases/dune-project-meta/run.t
- test/blackbox-tests/test-cases/dune-project-meta/test-fields-with-tmpl/dune-project
Signed-off-by: Anurag Soni <anurag@sonianurag.com>
> use tags from package stanza in dune-file

- doc/advanced-topics.rst
- doc/coq.rst
- doc/documentation.rst
- doc/dune-files.rst
- doc/installation.rst
- doc/jsoo.rst
- doc/menhir.rst
- doc/migration.rst
- doc/opam.rst
- doc/project-layout-specification.rst
- doc/variants.rst
This is from #2521, mostly small rendering and cosmetic fixes.
> Doc refresh - 1

- test/blackbox-tests/test-cases/github2499/run.t
This doesn't seem to work in travis
> Do not use shell expansion for tests

- bootstrap.ml
The bootstrap script changes to allow for subdirs in libraries that allow this.
> [bootstrap] Allow unqualified subdirs

- src/dune/action_exec.ml
Now, arguments in action_exec.ml are divided into two groups:
* The ones present in the exec_context are not changing during the
execution of the action.
* The ones present in the exec_environment are subject to change during
the action execution.
Signed-off-by: Jakub Staron <jstaron@janestreet.com>
> Wraps arguments in the action_exec.ml into struct.

- doc/dune-libs.rst
> build-info doc tweaks

- src/dune/build_system.ml
I've reopened this PR as it looks like it's no longer possible to re-open PR's that have been force pushed to.
> Build system early return fiber

- src/dune/build_system.ml
Use Option.{map,some_if,iter} to simplify some code.
> Simplify pattern matching with combinators

- src/stdune/csexp.ml
- src/stdune/csexp.mli
- test/expect-tests/dune_lang/csexp_tests.ml
Signed-off-by: Jakub Staron <jstaron@janestreet.com>
> Adds of_string function to Csexp.

- src/dune/lib_rules.ml
We'd like to construct the compilation context without setting up the
rules because it will be necessary to share this context for other
purposes. In particular, the odoc rules will need to construct this
value on their own.
Once this is done, we'll gain a bit of performance as we will no longer need to setup odoc rules everytime.
> Move cctx for libraries into own function

- install_ocaml.cmd
> Switch appveyor testing to 4.08

- src/dune/gen_rules.ml
This is an overdue change that is necessary for the odoc refactoring that I'm planning.
> Remove functor from gen_rules

- doc/opam.rst
- doc/usage.rst
Some rearrangement of existing material to make it easier to find.
> Doc tweaks

- src/dune/lib.ml
This error check for conflicts doesn't seem to be possible. If the
library is visited then the comparison [t = t'] will always return true
> Remove conflicts error

- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/dune_package.ml
- src/dune/findlib/findlib.ml
- src/dune/gen_rules.ml
- src/dune/lib.ml
- test/blackbox-tests/test-cases/variants-external-declaration-conflict/run.t
> Add locations to names in external_variant

- src/dune/build_system.ml
- src/dune/scope.ml
- src/stdune/fdecl.ml
- src/stdune/fdecl.mli
- src/stdune/log.ml
- test/expect-tests/memo/memoize_tests.ml
This improves the error message when something is set twice
> Add to_dyn converter to Fdecl

- src/dune/file_tree.ml
- src/stdune/path.ml
Both the build_dir and the File_tree settings can be defined using fdecl
> Replace custom references with Fdecl

- src/dune/file_tree.ml
This is in preparation for the memoziation pr for file_tree
> Move readdir type and function into submodule

- example/sample-projects/hello_world/run.t
- src/dune/lib_rules.ml
- test/blackbox-tests/test-cases/reason/run.t
- test/blackbox-tests/test-cases/scope-ppx-bug/run.t
> Simplify a use of Build.dyn_paths_unit

- CHANGES.md
(I tried to push directly to `master` but couldn't get past the DCO check).
> Update CHANGES.md for #2692

- test/blackbox-tests/test-cases/copy-files-non-sub-dir-error/run.t
- test/blackbox-tests/test-cases/tests-stanza-action-syntax-version/run.t
- test/blackbox-tests/test-cases/vendor/run.t
Signed-off-by: mefyl <mefyl@gruntech.org>
> Fix expected error messages from ce231518.

- test/blackbox-tests/test-cases/github1855/run.t
This bug has already been fixed.
> Add regression test for 1895 (#2710)kkkk

- bin/install_uninstall.ml
The detection of `META` and `dune-package` files was fragile and got recently broken. This PR cleans up the way we detect these files.
> Fix rewriting of META and dune-package files

- src/dune/dune_init.ml
One last extension that evaded my last PR
> Don't hardcode ".opam" in dune_init

- src/memo/memo.ml
This way we don't have to pass the extra function everywhere. I'm probably missing the deeper reason why both parameters are passed, but it gets in the way of adding the `Memo.Cell` feature that is planned.
> Fetch the spec directly form the dep_node

- src/memo/memo.ml
Creating a dep node for the sync and async is almost identical and can be factored into one function. Probably more can be done to share code between sync/async - this is just a low hanging fruit.
> Factor dep_node creation for sync and async

- src/dune/ordered_set_lang.ml
- src/dune/ordered_set_lang.mli
- src/dune/ordered_set_lang_intf.ml
It got annoying to have to change the signature in both the ml and mli.
> Add Ordered_set_lang_intf module

- dune-action-plugin.opam
- dune-project
> Fix list of dependency for dune-action-plugin package

- src/dune/action_ast.ml
- src/dune/action_exec.ml
- src/dune/action_intf.ml
- src/dune/build_system.ml
- src/dune/cinaps.ml
- src/dune/context.ml
- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/main.ml
- src/dune/predicate_lang.ml
- src/dune/predicate_lang.mli
- src/dune/process.ml
- src/dune/process.mli
- src/dune/sub_dirs.ml
- src/dune/sub_dirs.mli
* Move Predicate_lang.Ast to Predicate_lang
* The old Predicate_lang is now Predicate_lang.Glob
> Tweak Predicate_lang interface

- bin/alias.ml
- bin/alias.mli
- bin/arg.ml
- bin/arg.mli
- bin/common.ml
- bin/main.ml
- bin/target.ml
- src/dune/alias.ml
- src/dune/alias.mli
- src/dune/build_system.ml
- src/dune/build_system.mli
- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/odoc.ml
- src/dune/rules.ml
- src/dune/rules.mli
- src/dune/test_rules.ml
This introduces a type for alias names.
I need this PR for adding `alias` to `rule`.
> Introduce Alias.Name

- src/dune/file_tree.ml
Previously, we'd eagerly read every directory and immediately filter out
directories which aren't readable. This commit makes those directories
identical to empty directories.
> [File_tree] Make unreadable directories empty

- src/dune/simple_rules.ml
I've promoted the shorter branches to the top and extracted some helper validation functions.
> Simplify simple_rules

- src/dune/dir_contents.ml
- src/dune/dune_file.mli
- src/dune/env_node.ml
- src/dune/exe_rules.ml
- src/dune/expander.mli
- src/dune/foreign.ml
- src/dune/foreign.mli
- src/dune/foreign_rules.ml
- src/dune/foreign_sources.ml
- src/dune/foreign_sources.mli
- src/dune/inline_tests.ml
- src/dune/lib_archives.ml
- src/dune/lib_file_deps.ml
- src/dune/lib_rules.ml
- src/dune/toplevel.ml
- src/dune/utils.ml
- src/stdune/dune
- test/blackbox-tests/test-cases/duplicate-c-cxx-obj/run.t
- test/blackbox-tests/test-cases/duplicate-c-cxx/run.t
- test/blackbox-tests/test-cases/foreign-library/run.t
- test/blackbox-tests/test-cases/foreign-stubs/run.t
This addresses a couple of CRs by @aalekseyev.
> Ignore unused foreign sources, improve error messages

- test/blackbox-tests/test-cases/foreign-library/run.t
- test/blackbox-tests/test-cases/foreign-stubs/run.t
> Drop `--display short` in foreign library tests

- test/blackbox-tests/test-cases/variables-for-artifacts/dune
- test/blackbox-tests/test-cases/variables-for-artifacts/run.t
> Make the [variables-for-artifacts] test pass in sandbox

- src/dune/lib_rules.ml
We used to pass three arguments `path`, `static_target` and `dynamic_target` to `ocamlmklib` but in fact they all can be computed from an `archive_name`, which hopefully makes the code clearer.
> Reduce code duplication in [ocamlmklib] and address question

- Makefile
Signed-off-by: Olaf Hering <olaf@aepfle.de>
> make reinstall should not depend on itself

- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/module_name.ml
- src/dune/module_name.mli
- src/dune/preprocessing.ml
- src/dune/virtual_rules.ml
This slightly reduces the dependencies of dune_file making it easier to
break up.
> [refactor] Move Per_module to Module_name

- bin/compute.ml
- src/memo/function.ml
- src/memo/function.mli
- src/memo/memo.ml
- src/memo/memo.mli
- src/memo/run.ml
- src/memo/run.mli
The memo module is getting a bit busy. This gives a nicer hierarchy and reduces the weight of memo.
> [memo] Split memoization function to separate module

- src/memo/memo.ml
- src/stdune/type_eq.ml
- src/stdune/type_eq.mli
> [memo] Move Memo.Witness to Type_eq

- test/blackbox-tests/test-cases/ppx-runtime-dependencies/gen_c.ml
- test/blackbox-tests/test-cases/ppx-runtime-dependencies/run.t
We thought of a few tricky cases. Adding tests for those.
> Add more ppx rewriter dependency cycle tests

- bin/import.ml
- bin/install_uninstall.ml
- bin/main.ml
- src/dune/build_system.ml
- src/dune/build_system.mli
- src/dune/scheduler.ml
- src/dune/scheduler.mli
- src/dune_manager/dune_manager.ml
- src/dune_manager/dune_manager.mli
- src/dune_memory/dune
- src/dune_memory/dune_memory.ml
- src/dune_memory/dune_memory.mli
- src/dune_memory/dune_memory_intf.ml
- src/dune_memory/key.ml
- src/dune_memory/key.mli
- src/dune_memory/utils.ml
- src/stdune/path.ml
- src/stdune/path.mli
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/dune-cache-dedup-direct/run.t
- test/blackbox-tests/test-cases/dune-cache-dedup-direct/stat.sh
- test/blackbox-tests/test-cases/dune-cache-promote-direct/run.t
- test/blackbox-tests/test-cases/dune-cache-promote-direct/stat.sh
- test/blackbox-tests/test-cases/dune-cache-symlink-direct/run.t
- test/blackbox-tests/test-cases/dune-cache-symlink-direct/stat.sh
- vendor/boot/dune_manager.ml
- vendor/boot/dune_memory.ml
This is a prerequisite for #2754 .
> Add direct filesystem acces mode to dune cache.

- src/stdune/path.ml
- test/expect-tests/stdune/path_tests.ml
> Fix a bug in `Path.Build.extract_first_component` and share code

- doc/faq.rst
This was asked several times to me, so I suppose that makes it a Frequently Asked Question.
> Add a FAQ entry about disabling buffering

- src/dune_manager/dune_manager.ml
- src/dune_manager/messages.ml
- src/dune_manager/messages.mli
- src/dune_manager/messages_intf.ml
- src/dune_manager/utils.ml
> Extract cache protocol.

- src/dune/context.ml
- src/dune/context.mli
- src/dune/foreign_rules.ml
- src/dune/lib_rules.ml
This avoid the string check for msvc everywhere
> Add type for ctx.ccomp_type

- bin/common.ml
- bin/import.ml
- bin/subst.ml
- src/dune/config.ml
- src/dune/config.mli
- src/dune/main.ml
- test/blackbox-tests/test-cases/dune-cache-dedup-direct/run.t
- test/blackbox-tests/test-cases/dune-cache-dedup/run.t
- test/blackbox-tests/test-cases/dune-cache-promote-direct/run.t
- test/blackbox-tests/test-cases/dune-cache-promote/run.t
- test/blackbox-tests/test-cases/dune-cache-symlink-direct/run.t
- test/blackbox-tests/test-cases/dune-cache-symlink/run.t
- test/blackbox-tests/test-cases/dune-cache-trim/run.t
- test/blackbox-tests/test-cases/dune_memory-and-the-universe/run.t
> Add CLI and config file configuration for the cache.

- src/dune_cache/dune_cache.ml
Dune is already protected against the file disappearing while retrieving it from the cache. Fix #2755.
> Do not lock cache on lookup.

- src/dune/promotion.ml
> Restore user write permissions when promoting a file.

- bin/common.ml
- bin/import.ml
- bin/main.ml
- bin/subst.ml
- src/dune/build_system.ml
- src/dune/build_system.mli
- src/dune/config.ml
- src/dune/config.mli
- src/dune/main.ml
- src/dune_lang/decoder.ml
- src/dune_lang/decoder.mli
- src/stdune/float.ml
- src/stdune/float.mli
Requires https://github.com/ocaml/dune/pull/2844 to be merged first. Fix #2751.
> Randomly check rules reproducibility.

- doc/dune-files.rst
Signed-off-by: Antonio Nuno Monteiro anmonteiro@gmail.com
> Clarify the documentation for `implicit_transitive_deps`

- CHANGES.md
> Update change log

- otherlibs/configurator/src/v1.mli
Fixes #2806
Signed-off-by: Olaf Hering <olaf@aepfle.de>
> Document the Pkg_config.query API

- .github/CODEOWNERS
Some files have moved around, some do not exist anymore.
> Cleanup CODEOWNERS file

- src/stdune/fdecl.ml
- src/stdune/fdecl.mli
- src/stdune/log.ml
It doesn't seem to be needed anymore
> Remove Fdecl.reset

- dune-action-plugin.opam
- dune-project
Use with-test rather than test
> Fix opam file

- src/dune/stanza.ml
- test/blackbox-tests/test-cases/deprecated-library-name/run.t
- test/blackbox-tests/test-cases/dune-init/run.t
- test/blackbox-tests/test-cases/dune-package/run.t
- test/blackbox-tests/test-cases/dune-project-edition/run.t
- test/blackbox-tests/test-cases/exes-with-c/run.t
- test/blackbox-tests/test-cases/foreign-library/run.t
- test/blackbox-tests/test-cases/github1529/run.t
- test/blackbox-tests/test-cases/github1549/run.t
- test/blackbox-tests/test-cases/inline_tests/run.t
- test/blackbox-tests/test-cases/re-exported-deps/run.t
- test/blackbox-tests/test-cases/variables-for-artifacts/run.t
- test/blackbox-tests/test-cases/variants-external-declaration/run.t
- test/blackbox-tests/test-cases/variants-only-package/run.t
- test/blackbox-tests/test-cases/variants/run.t
- test/blackbox-tests/test-cases/vlib-default-impl/run.t
- test/blackbox-tests/test-cases/vlib/run.t
While working on a new feature I needed to bump the Dune language to 2.1. Doing this in a separate commit since a few updates need to be made to the testsuite.
> Bump Dune language to 2.1

- src/dune/dir_contents.ml
- src/dune/dune_load.ml
- src/dune/file_tree.ml
- src/dune/file_tree.mli
- src/memo/memo.ml
- src/memo/memo.mli
This took quite a bit more effort than I expected, which perhaps suggests that I'm doing it wrong.
> Use Memo.Cell in File_tree

- src/dune/dune_project.ml
The current implementation finds the minimum twice, perhaps because `choose` makes no guarantees about what it chooses. We should just call `min_binding` to get the minimum.
> Simplify [Dune_project.default_name]

- test/blackbox-tests/test-cases/dune-project-meta/run.t
> Remove a comment that is obviously stale

- README.md
Changes should be straightforward.
> README: Fix some wording choices

- test/blackbox-tests/test-cases/subst/file.ml.in
- test/blackbox-tests/test-cases/subst/run.t
> Add reproduction case for #2910

- src/dune/context.ml
- src/dune/global.ml
- src/dune/global.mli
- src/dune/main.ml
- src/dune/workspace.ml
- src/memo/memo.ml
- src/memo/memo.mli
Same as Fdecl, but is reset after every run. With this new Fdecl, it should be easier to make sure this doesn't break going forward
Fix #2941
> Introduce Memo.Run.Fdecl

- src/memo/memo.ml
This implementation avoids a hash table look up.
> Implement [Memo.Lazy] using [Memo.Cell]

- dune-private-libs.opam
- dune-project
> Minimum OCaml version in dune-private-libs

- src/memo/memo.ml
We use a combination of `mutable` and `Lazy.t` to initialise `dep_node` with a reference to a `dag_node` that need to refer back to the `dep_node`, in a cyclic manner. It turns out we can achieve this simply by using a recursive let binding.
> Simplify [Dep_node]

- src/memo/memo.ml
This eliminates a couple of `assert false` in impossible branches.
> Make [Memo.State.Running_*] typed

- .github/ISSUE_TEMPLATE/bug_report.md
Closes #2978
It should still be possible for users to open blank issues.
> Add an issue template for bug reports

- doc/quick-start.rst
- doc/usage.rst
Signed-off-by: Danny Willems <contact@danny-willems.be>
> Doc: typos

- src/dune_cache/dune_cache.ml
- src/dune_cache/dune_cache.mli
- src/dune_cache/dune_cache_intf.ml
* The logic to accumulate trimming results is moved to one function
* Simplify building a target path
> [refactor] Dune_cache

- doc/dune-files.rst
More doc clarification re: #3017
> Mention dune 2.0 bc target change

- src/dune/build_system.ml
There's no to copy all the fileds in Pre_rule, we can just include it.
> Simplify Internal_rule.t

- src/dune/build_system.ml
This PR attempts to make things in build_system.ml a clearer by removing the last large piece of mutable state: this `files` field mirrors the information in `targets_here` (which I'm renaming to `rules_here`), so let's just use the latter.
Also rename things a little bit to make them clearer.
> Get rid of remaining mutable state `Build_system.files`

- src/dune/build.ml
- src/memo/memo.ml
- src/memo/memo.mli
- test/expect-tests/memo/memoize_tests.ml
While it turned out that I do not immediately need this feature, it will most certainly become useful soon, e.g. for @rgrinberg's on-going work on `Fiber`-isation of a large part of Dune.
> Add an asynchronous equivalent for [Memo.Poly]

- boot/duneboot.ml
Because it's nicer when we see that something is happening
> Add a status line to duneboot

- src/dune/dune_package.ml
- src/dune/dune_package.mli
- src/dune/findlib/findlib.ml
- src/dune/install_rules.ml
> Convert Dune_package.entries to a map

- bin/installed_libraries.ml
- src/dune/dune_package.ml
- src/dune/dune_package.mli
- src/dune/findlib/findlib.ml
- src/dune/findlib/findlib.mli
- src/dune/findlib/meta.ml
- src/dune/findlib/meta.mli
- src/dune/lib.ml
- src/dune/lib.mli
- src/dune/lib_name.ml
- src/dune/lib_name.mli
- src/dune/link_time_code_gen.ml
- src/dune/super_context.ml
- test/expect-tests/findlib_tests.ml
Could be extended later into a real package database, but it should be sufficient for relocation branch.
> [Findlib] Cache installed package lookup and export it

- doc/dune-files.rst
I don't know though how to check that change is OK for this markup. It's not obvious how to do that when looking at `doc/` contents.
> Doc: Mention how to add libary to project in project files doc.

- .travis.yml
- dune-project
- dune.opam
- dune.opam.template
So that we can have the special dependency on ocaml
> Move the depends field to dune.opam.template

- bin/common.ml
- bin/common.mli
- bin/dune
- bin/import.ml
- bin/target.ml
- boot/libs.ml
- src/dune/dune
- src/dune/import.ml
- src/dune_cache/dune
- src/dune_cache/dune_cache.ml
- src/dune_cache_daemon/dune
- src/dune_cache_daemon/dune_cache_daemon.ml
- src/dune_util/dune
- src/dune_util/log.ml
- src/dune_util/log.mli
- src/stdune/stdune.ml
- test/expect-tests/common/dune
- test/expect-tests/common/dune_tests_common.ml
Only contains the old Stdune.Log for now. Will soon include the dune
specific path modules.
> Introduce Dune_util

- src/dune/compilation_context.ml
- src/dune/compilation_context.mli
- src/dune/link_time_code_gen.ml
This is tune with how we modify the compilation context for other
special schemes.
> Add Compilation_context.for_link_time_code_gen

- src/dune/string_with_vars.ml
- src/dune/string_with_vars.mli
- src/stdune/applicative.ml
- src/stdune/applicative.mli
- src/stdune/applicative_intf.ml
- src/stdune/stdune.ml
Allow the function used to expand in String_with_vars to have an
applicative effect.
> Applicative expansion of string_with_vars

- src/dune/process.ml
- src/stdune/spawn.ml
- src/stdune/spawn.mli
- src/stdune/stdune.ml
This module is general purpose enough to live in stdune
> Move Spawn to stdune

- src/dune/cm_kind.ml
- src/dune/cm_kind.mli
- src/dune/expander.ml
- src/dune/expander.mli
- src/dune/mode.ml
- src/dune/mode.mli
- src/dune/pform.ml
- src/dune/pform.mli
- src/dune/string_with_vars.ml
- src/dune/string_with_vars.mli
- src/dune/super_context.ml
- src/dune/value.ml
- src/dune/value.mli
- Move static expansion into its own function.
- Add a comment explaining the rational behind it.
> [expander] refactor

- src/stdune/stdune.ml
- src/stdune/top_closure.ml
- src/stdune/top_closure.mli
- src/stdune/top_closure_intf.ml
These modules are general purpose enough to be in stdune
> Move top closure to stdune

- bin/compute.ml
- src/memo/function.ml
- src/memo/function.mli
- src/memo/memo.ml
- src/memo/memo.mli
- test/expect-tests/memo/memoize_tests.ml
> Do not intern names and do not name lazy nodes in [memo.ml]

- bin/common.ml
- src/dune/action_exec.ml
- src/dune/build_system.ml
- src/dune/dir_contents.ml
- src/dune/dune_init.ml
- src/dune/file_tree.ml
- src/dune/gen_rules.ml
- src/dune/install_rules.ml
- src/dune/merlin.ml
- src/dune/odoc.ml
- src/dune/sub_dirs.ml
- src/stdune/path.ml
- src/stdune/set.ml
- src/stdune/set_intf.ml
This allows us to deforest a bit of code and make some code shorter.
> Introduce Set.of_list_map

- src/dune/package.mli
- src/dune/sub_system_name.mli
- src/dune/variant.mli
- src/stdune/interned.ml
- src/stdune/interned.mli
- src/stdune/interned_intf.ml
- src/stdune/stdune.ml
Allows us to write the signature only once
> Move interned interface to own module

- src/dune/dir_contents.ml
* Now the local parameter is always collected. Perviously, it was
collected only in the [(include_subdirs qualified)] mode. However, it's
simpler to just always calculate it and have th ecallers discard it in
unqualified mode.
* The function is now extracted into a separate [collect_group]
function.
> [Dir_contents] refactor walk function

- src/dune/coq_rules.ml
- test/blackbox-tests/gen_tests.ml
This refactoring will make it easier to understand that the extraction stanza
will introduce in an upcoming PR.
> Split coqc/coqdep rules into separate functions

- bin/common.ml
- src/dune/clflags.ml
- src/dune/clflags.mli
- src/dune/lib.ml
- src/dune/lib_info.ml
- src/dune/promotion.ml
- src/dune/report_error.ml
- src/stdune/report_error.ml
- src/stdune/report_error.mli
- src/stdune/stdune.ml
This module is not general purpose enough to be in [Stdune]
> Move [Clflags] to [Dune_util]

- .travis-ci.sh
> [coq] [travis] Re-enable Coq's test in CI

- bin/external_lib_deps.ml
- src/dune/clflags.ml
- src/dune/colors.ml
- src/dune/report_error.ml
- src/dune/scheduler.ml
- src/dune_util/report_error.ml
- src/dune_util/report_error.mli
- src/stdune/stdune.ml
It's current state is not general enough to be included in [Stdune]
@mefyll you can still access this module but via [Dune_util]
> Demote report_error to [Dune_util]

- src/dune/cinaps.ml
The version of cinaps in opam should be recent enough
> Suggest cinaps without pinning

- src/memo/memo.ml
@snowleopard, I'm not entirely satisfied with this refactor, but I think it's net slightly positive.
If you like it, we can merge it. If not, feel free to take inspiration (on what not to do).
> Refactor so that dependency edge is added unconditionally

- src/dune/lib.ml
The [Unimplemented.fold] function isn't necessary if we just define the
more specific functions to fetch virtual libraries implemented via
default or variants
> Simplify finding implementations of vlibs

- test/blackbox-tests/test-cases/plugin-mode/run.t
Seems like someone forgot to `dune promote`.
> Fix a test

- src/dune/mdx.ml
- src/stdune/ordering.ml
[source_tree_dep_set] is the same as [Dep.Set.source_tree]
> Remove some duplicate code

- doc/dune-files.rst
> Debug MDX doc

- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/gen_rules.ml
The [files] argument is always File_binding.Unexpanded.t list
> Simplify type of Install_conf

- src/cache/cache.ml
- src/cache/cache.mli
- src/dune/cached_digest.ml
> Don't remove write permissions on non regular targets.

- src/dune/dir_contents.ml
- src/dune/lib_info.ml
- src/dune/package.ml
- src/dune/print_diff.ml
- src/dune/rule.ml
- src/stdune/console.ml
- src/stdune/loc.ml
- src/stdune/loc.mli
* Use pp instead of format
* print locations in a friendlier way in Dyn.t values
> Improve pretty printing of locations

- src/dune/action_unexpanded.ml
- src/dune/action_unexpanded.mli
- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/expander.ml
- src/dune/expander.mli
- src/dune/merlin.ml
- src/dune/preprocessing.ml
- src/dune/simple_rules.ml
- src/dune/super_context.ml
- src/dune/super_context.mli
- src/dune/targets.ml
- src/dune/targets.mli
Move multiplicities and all Targets types to it
> Add targets module

- README.md
To help new opam users install and use dune.
> Mention eval opam config env

- bin/caching.ml
- bin/import.ml
- src/cache/cache.ml
- src/cache/cache.mli
- src/cache/cache_intf.ml
- src/cache/client.ml
- src/cache/client.mli
- src/cache/key.mli
- src/cache/local.ml
- src/cache/local.mli
- src/cache/messages.ml
- src/cache/messages.mli
- src/cache/messages_intf.ml
- src/cache_daemon/cache_daemon.ml
On-going improvements to the documentation, as well as some minor clarifications in the code.
> Document Dune cache 

- src/dune/action.ml
- src/dune/action.mli
- src/dune/action_dune_lang.mli
- src/dune/action_unexpanded.ml
- src/dune/action_unexpanded.mli
- src/dune/coq_rules.ml
- src/dune/super_context.ml
* Make resolved actions private
* Make the target/dep inference private
* Share code between expansion phases
> Refactor action handling

- src/dune/lib.ml
- src/stdune/poly.ml
- src/stdune/poly.mli
@diml this is the part of the cycle detection PR that doesn't change existing behavior.
> Refactor library closure

- doc/faq.rst
Signed-off-by: James R. Wilcox <wilcoxjay@gmail.com>
> typo in FAQ

- src/dune/artifact_substitution.ml
It got messed up when we introduced ocamlformat. Use a doc comment and a verbatim block to preserve manual formatting.
> Restore schema in comment

- test/blackbox-tests/test-cases/subdir-stanza/run.t
> Add a missing EOF

- doc/concepts.rst
Hi,
Fix #3254.
Sorry for the delay...
> add a note about `preprocessing_deps` in preprocessing specification

- src/dune/buildable_rules.ml
- src/dune/buildable_rules.mli
- src/dune/exe_rules.ml
- src/dune/install_rules.ml
- src/dune/lib_rules.ml
- src/dune/simple_rules.ml
- src/dune/super_context.ml
- src/dune/super_context.mli
Our goal is to shrink Super_context as possible
> Move SC.Libs to Buildable_rules

- CHANGES.md
> Add changelog entry for #3092

- bin/util.ml
- src/cache/messages.ml
- src/dune/build_system.ml
- src/dune/context.ml
- src/dune/expander.ml
- src/dune/pform.ml
- src/dune/rules.ml
- src/dune/super_context.ml
Makes the code shorter and faster
> Deforest with Map.of_list_map_exn

- src/dune/install.ml
- src/dune/install_rules.ml
* Move definitions close to their usage
* Do not leak unnecessary names
* Add some comments
> Organize install_rules a little better

- src/cache/cache.ml
- src/cache/cache_intf.ml
- src/cache/client.ml
- src/cache/local.ml
- src/cache/messages.ml
- src/cache_daemon/cache_daemon.ml
- src/dune/build_system.ml
- src/dune/scheduler.ml
- test/blackbox-tests/test-cases/dune-cache/trim/run.t
This implements the proposal #3357.
There is a also a minor refactoring of related code.
> Implement RFC #3357 on Dune cache

- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/cinaps/include-subdirs.t
@NathanReb would you mind having a look at this bug? I'm not as familiar with
the cinaps extension.
> Reproduce include_subdirs + cinaps bug

- doc/dune-files.rst
> Fix small typo in doc

- test/blackbox-tests/test-cases/strict-package-deps/run.t
> strict_package_deps doesn't understand transitive deps

- src/cache/local.ml
- src/dune_lang/decoder.ml
- src/stdune/char.ml
- src/stdune/char.mli
- src/stdune/stdune.ml
Following [the suggestion](https://github.com/ocaml/dune/pull/3413#discussion_r413354991) by @rgrinberg.
> Add Stdune.Char

- doc/dev/README.md
- doc/dev/cache.md
Here is the [rendered version of the document](https://github.com/ocaml/dune/blob/0165b7527780bb7027c5d084076f98981ca07491/doc/dev/cache.md).
> Add notes on cache design and implementation

- src/dune/dune_project.ml
- src/dune_lang/decoder.ml
- src/fiber/fiber.ml
- src/stdune/univ_map.ml
- src/stdune/univ_map.mli
Make add/set/update behave more like the normal map API
> Refactor Univ_map API

- src/dune/process.ml
- src/stdune/stdune.ml
- src/stdune/temp.ml
- src/stdune/temp.mli
This is a first step towards #3432 and is required to move forward with #3392.
> Extract Process.Temp

- test/expect-tests/fiber/fiber_tests.ml
* Test the context restoration of Ivar.read
* Test the behavior Ivar.fill
> Add more fiber tests

- .travis-ci.sh
- .travis.yml
> [WIP] unbreak travis

- src/dune/scheduler.ml
- src/fiber/fiber.ml
- src/stdune/queue.ml
- src/stdune/queue.mli
- src/stdune/stdune.ml
- test/expect-tests/fiber/fiber_tests.ml
This queue module follows the convention of Stdune
> [stdune] Add queue module

- boot/duneboot.ml
Fixes warnings emitted during bootstrap
> Fix ocamldoc in bootstrap

- .ocamlformat
- src/dune/colors.ml
- src/dune/coq_rules.ml
- src/dune/dune_env.ml
- src/dune/env_node.ml
- src/dune/env_node.mli
- src/dune_lang/t.ml
> Upgrade to ocamlformat v0.14.2

- src/dune/scheduler.ml
We already have a type to represent an exception + a backtrace. We might
as well use it.
> Use Exn_with_backtrace in Fiber

- otherlibs/cram/bin/dune
- otherlibs/cram/bin/sanitize.ml
- test/blackbox-tests/test-cases/block-strings.t/run.t
- test/blackbox-tests/test-cases/cross-compilation.t/run.t
- test/blackbox-tests/test-cases/deprecated-library-name.t/run.t
- test/blackbox-tests/test-cases/dune-package.t/run.t
- test/blackbox-tests/test-cases/duplicate-c-cxx-obj.t/run.t
- test/blackbox-tests/test-cases/duplicate-c-cxx.t/run.t
- test/blackbox-tests/test-cases/foreign-library.t/run.t
- test/blackbox-tests/test-cases/foreign-stubs.t/run.t
- test/blackbox-tests/test-cases/gen-opam-install-file.t/run.t
- test/blackbox-tests/test-cases/github1549.t/run.t
- test/blackbox-tests/test-cases/glob-deps.t/run.t
- test/blackbox-tests/test-cases/inline_tests.t/run.t
- test/blackbox-tests/test-cases/install-dry-run.t/run.t
- test/blackbox-tests/test-cases/install-libdir.t/run.t
- test/blackbox-tests/test-cases/lib.t/run.t
- test/blackbox-tests/test-cases/no-installable-mode.t/run.t
- test/blackbox-tests/test-cases/output-obj.t/run.t
- test/blackbox-tests/test-cases/plugin-mode.t/run.t
- test/blackbox-tests/test-cases/re-exported-deps.t/run.t
- test/blackbox-tests/test-cases/reason.t/run.t
- test/blackbox-tests/test-cases/virtual-libraries/dune-package-info/run.t
- test/blackbox-tests/test-cases/virtual-libraries/install-file/run.t
- test/blackbox-tests/test-cases/virtual-libraries/vlib-default-impl/run.t
- test/blackbox-tests/utils/dune
- test/blackbox-tests/utils/dune_cmd.ml
extension sanitation must now be manually ran via dune_cmd sanitize
> Remove automatic sanitation

- .ocamlformat
This makes is possible to install base 0.14.0.
> Upgrade ocamlformat to 0.14.3

- doc/toplevel-integration.rst
> Update toplevel integration doc

- dune-configurator.opam
- dune-project
- otherlibs/configurator/src/import.ml
- otherlibs/configurator/src/v1.ml
> [configurator] restore compatibility with 4.03

- doc/dune-files.rst
I got "bitten" by https://github.com/ocaml/dune/issues/1552 - here's an update to the manual to reflect the current state of parsing.
> Update docs for lang stanza

- dune-action-plugin.opam
- dune-build-info.opam
- dune-configurator.opam
- dune-glob.opam
- dune-private-libs.opam
Dune 2.7 now generates this field
> Add with-doc to dune opam files

- src/fiber/fiber.ml
- test/expect-tests/fiber/fiber_tests.ml
`deref` might be called by `forward_error` from the rhs of the `try...with` block inside `apply`. When we can the `on_release` continuation, we need something to catch exception it might raise.
> Catch exceptions inside deref

- src/fiber/fiber.ml
> Always call defer last as stated in the invariants

- doc/tests.rst
Document the `BUILD_PATH_PREFIX_MAP` mechanism for sanitation
> Document cram sanitation

- dune-private-libs.opam
- dune-project
> Relax constraints on dune-private-libs

- doc/usage.rst
> Document how to build targets in directories that start with `@`

- doc/tests.rst
Explain how to test locally defined binaries since it's so common
> Improve cram docs

- boot/libs.ml
- src/dune_rules/bootstrap_info.ml
- src/dune_rules/lib_info.ml
- src/dune_rules/lib_info.mli
- src/dune_rules/link_time_code_gen.ml
Rather than delaying the conversion until later
> Use Module_name.t for data_module field

- .github/workflows/workflow.yml
- dune-configurator.opam
- dune-project
- otherlibs/configurator/src/import.ml
- otherlibs/configurator/src/v1.ml
Issues discovered when trying to release 2.7.1
cc @kit-ty-kate
> Fix configurator on older versions

- README.md
Signed-off-by: Jordan Danford <jordandanford@gmail.com>
> Update link to cross-compilation docs in `README.md`

- bin/install_uninstall.ml
- bin/print_rules.ml
- src/dune_lang/t.ml
- src/dune_rules/bootstrap_info.ml
- src/dune_rules/coq_rules.ml
- src/dune_rules/install_rules.ml
- src/dune_rules/pform.ml
- src/dune_rules/plugin_rules.ml
- src/dune_rules/toplevel.ml
- src/dune_util/log.ml
- src/memo/memo.ml
- src/stdune/ansi_color.ml
- src/stdune/console.ml
- src/stdune/dyn.ml
- src/stdune/loc.ml
- src/stdune/pp.ml
- src/stdune/pp.mli
- src/stdune/user_error.ml
- src/stdune/user_message.ml
- test/expect-tests/catapult/catapult_tests.ml
- test/expect-tests/common/dune_tests_common.ml
- test/expect-tests/dune_lang/sexp_tests.ml
- test/expect-tests/findlib_tests.ml
- test/expect-tests/stdune/pp_tests.ml
In preparation for unvendoring this library, we make sure it's up to date.
> Update to latest pp

- src/dune_engine/build_system.ml
* Use |> when it removes a bunch of parens
* Use functional update instead of creating a new record
> Style improvements to build_system

- CHANGES.md
> Add missing changes entry for pipe-*

- CHANGES.md
> Change my username in the changelog

- CHANGES.md
I'm not able to push directly to master DCO check needed.
> Update CHANGES for diff with non existent reference and for sites

- doc/formatting.rst
> Clarify formatting in dune

- src/dune_engine/install.ml
- src/dune_engine/section.ml
- src/dune_engine/section.mli
- src/section/dune_section.ml
- src/section/dune_section.mli
Do not copy paste it around in Section/Section_with_site
> Keep section parsing in one place

- src/dune_rules/action_to_sh.ml
- test/blackbox-tests/test-cases/pipe-actions.t/run.t
Strangely locally `make test` was not finding any difference until I ran `make clean`.
> [Pipe] fix tests

- src/dune_engine/config.ml
- src/dune_engine/config.mli
- src/dune_rules/context.ml
Previously, they were present in Config + Context
> Move all lib install path to Config

- src/dune_rules/dune_file.ml
- test/blackbox-tests/test-cases/no-installable-mode.t/run.t
Improve error message as suggested in #3896
Fixes #3896
> Improve error message on js compilation fixes ocaml/dune#3896

- src/dune_engine/build.ml
As discussed on slack, these are a little more efficient than Map2 for most of
our use cases
> [build] add Seq, Both primitives

- src/dune_rules/install_rules.ml
- src/stdune/set.ml
- src/stdune/set_intf.ml
* Some deforestation
* Remove some duplication
* Use pipes where appropriate
> Simplify install_rules

- src/dune_rules/dune_file.ml
- test/blackbox-tests/test-cases/instrumentation.t/run.t
Adds missing version check in #3932
> Add version check for instrumentation parameters

- doc/hacking.rst
- doc/index.rst
- doc/working-on-dune.rst
This is the start of a more "Dune developer orientated manual". It will provide a more extensive documentation about how to work on Dune as well as guidelines in order to keep the project in a good state.
> developer manual

- doc/sites.rst
@bobot after reviewing the docs, I'm suspecting that the `generated_module` stanza is named a little too generally. I'd prefer a name that hints that this module generation is specific to the sites feature.
Let's get another pairs to have a look to see if things are clearer.
Perhaps @nojb?
> Improve `sites` documentation

- src/dune_engine/scheduler.ml
Accessing the hash table's length is just as fast
> [scheduler] Remove running count

- src/dune_rules/link_time_code_gen.ml
do not raise exception when library fails to resolve
> link_time_code_gen - better error handling

- src/dune_rules/lib.ml
Small internal change to clean up vlib handling
> Move Vlib_visit to Vlib.Visit

- otherlibs/site/test/run.t
- src/dune_engine/dpath.ml
- src/dune_engine/dpath.mli
- src/dune_rules/dir_with_dune.mli
- src/dune_rules/dune_package.ml
- src/dune_rules/super_context.ml
There were no test for the site feature for a site of an installed package
> Error for loading dune-package with site information

- test/blackbox-tests/test-cases/merlin/dune
- test/blackbox-tests/test-cases/merlin/suffix.t/alterexe.aml
- test/blackbox-tests/test-cases/merlin/suffix.t/dune
- test/blackbox-tests/test-cases/merlin/suffix.t/dune-project
- test/blackbox-tests/test-cases/merlin/suffix.t/run.t
Also see #3977 
Also add  a handy alis to run all merlin tests: `all-merlin-tests`
> Add test for PR #3977 : dialect SUFFIXes

- otherlibs/site/src/plugins/plugins.ml
- otherlibs/site/test/run.t
The order of readdir can be non-deterministic
> Sort the list of plugins

- bin/external_lib_deps.ml
- src/cache/messages.ml
- src/dune_rules/merlin.ml
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- test/blackbox-tests/test-cases/github1946.t/run.t
- test/blackbox-tests/test-cases/merlin/merlin-tests.t/run.t
Also tweak the pp'ing of merlin configs.
> Remove more uses of formatting strings

- src/dune_rules/ml_sources.ml
Both are caused by the same problem - failing to resolve a library.
> Replace 2 Result.ok_exn with 1

- test/expect-tests/fiber/fiber_tests.ml
Add tests for sequential vs. parallel behavior.
Test that fork raises exceptions from both sides.
> [fiber] add exception handling tests

- src/dune_lang/decoder.ml
Make Fields.t and subtypes private records. Make interface consistent with rest.
> [Dune_lang] Improve fields interface

- otherlibs/site/src/plugins/plugins.ml
- otherlibs/site/test/run.t
Fix a bug with `b.b.b`. The sub-directories where not concatenated, only the last was taken into account.
> Loading sub-sub-library don't work

- src/dune_engine/build_system.ml
- src/dune_engine/dep.ml
- src/fiber/fiber.ml
- src/fiber/fiber.mli
iterate over a set in parallel without allocating an intermediate list.
> [fiber] add set_parallel_iter

- src/dune_engine/build_system.ml
- src/dune_engine/dep.ml
- src/dune_rules/coq_sources.ml
- src/dune_rules/cram_rules.ml
- src/dune_rules/dir_contents.ml
- src/stdune/set.ml
- src/stdune/set_intf.ml
> [stdune] Set.to_list_map_rev

- bin/print_rules.ml
- src/dune_engine/action.ml
- src/dune_engine/action.mli
- src/dune_engine/build.ml
- src/dune_engine/build_system.ml
- src/dune_engine/dep.ml
- src/dune_engine/dep.mli
- src/dune_engine/static_deps.ml
- src/dune_engine/static_deps.mli
This is better than redundantly passing it all the time
> Add Dep.eval_pred forward declaration

- src/dune_engine/scheduler.ml
Previously, build cancellation relied on file change events interrupting
`Fiber.run`. This will not work if we want rpc to stay uninterrupted.
We change cancellation to work by setting the status of the scheduler to
be `Cancelling_build`. Once the status is set, we kill running build
processes and forbid launching new ones to await the termination of the
build. Then, we re-run the build.
> Re-do build cancellation

- otherlibs/site/test/run.t
- src/memo/memo.ml
- test/expect-tests/memo/memoize_tests.ml
> Add a test case showing exponential exception buildup.

- src/dune_engine/build.ml
- src/dune_engine/build.mli
- src/dune_engine/build_system.ml
- src/dune_engine/dep.mli
We can use the same fdecl in Dep
> Remove eval_pred fdecl in build

- src/cache/local.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/temp.ml
- src/stdune/temp.mli
One implementation of temporary files/dirs is enough
> Remove [Path.temp_dir] in favor of [Temp]

- src/dune_engine/dep.ml
Memoize traces of globs. This is a naive attempt, and I'm not sure if it's
correct.
> Attempt to fix #3862
