dune-action-plugin.opam, dune-project, test/unit-tests/artifact_substitution/dune, test/unit-tests/dune, test/unit-tests/ocaml-config/dune
This makes dune runtest -p not fail when exercised by opam.
=> Attach unit tests to packages

src/stdune/nothing.ml
We do not need to support 4.02 anymore, so this part can be simplified.
=> Nothing: implement using a refutation branch

bin/alias.ml, src/dune/alias.ml, src/dune/alias.mli, src/dune/build_system.ml, src/dune/config.ml, src/dune/dpath.ml, src/dune/dpath.mli, src/stdune/path.ml, src/stdune/path.mli
The current code has two problems:
* It hard codes the names of special directories like `_build/.aliases` and
`_build/install`.
* The logic for analyzing target directories and targets is duplicated.
I attempt to address both of these problems. The first problem is solved by
moving the special directories to the `Dpath` module. The second problem is
addressed by reusing some of the code from `Dpath.analyse_target`.
PS: I also got rid of the `assert false` in `Dpath.analyse_target`. I recall it
was discussed that it was desirable, but I must have forgot about this.
=> Tweak dir triaging

src/dune/build_system.ml, src/dune/dune_file.ml, src/dune/dune_file.mli, src/dune/dune_load.ml, src/dune/exe.mli, src/dune/js_of_ocaml_rules.ml, src/dune/js_of_ocaml_rules.mli, src/dune/opam_create.ml, src/dune/rule.ml, src/dune/rule.mli, src/dune/super_context.mli
`Rule` is unusable without these types anyway and it allows us to create
rules without depending on `Dune_file.t`.
=> Move promote settings to `Rule`

src/dune/build.ml, src/dune/context.ml, src/dune/dune_load.ml, src/dune_lang/syntax.ml, src/ocaml-config/ocaml_config.ml, src/stdune/caml/dune_caml.ml, src/stdune/scanf.ml, src/stdune/scanf.mli, src/stdune/stdune.ml
This is a slightly safer version that only catches 2 exceptions that
scanf throws
=> [stdune] add scanf module

src/dune/context.ml, src/dune/context.mli, src/dune/lib.ml, src/dune/lib.mli, src/dune/lib_archives.ml, src/dune/lib_archives.mli, src/dune/lib_config.ml, src/dune/lib_config.mli, src/dune/lib_rules.ml, src/dune/modules.ml, src/dune/modules.mli
This is a re-make of #2693. It depends #2828 to be merged first. At which point
I will implement `Lib_config.empty_native_archive` correctly.
=> Fix native code generation of empty libraries on MSVC

src/dune/context.ml, src/dune/context.mli, src/dune/dune_load.ml, src/dune/exe.ml, src/dune/expander.ml, src/dune/foreign_rules.ml, src/dune/pform.ml, src/dune/super_context.ml, src/stdune/scanf.ml, test/blackbox-tests/gen_tests.ml
Lots of fields in [Context.t] are just copies of the underlying
[Ocaml_config.t]. There's no need to repeat them.
=> Remove duplicated fields in [Context.t]

src/dune/context.ml, src/dune/lib_dep.ml, src/dune/process.ml, src/dune/process.mli, src/stdune/env.ml, src/stdune/env.mli, src/stdune/tuple.ml, src/stdune/tuple.mli
We can use memoization to save the opam version rather than manually
storing it in a reference cell.
=> Memoize Opam Version

otherlibs/build-info/test/run.t
This is what happens when dune subst is called (when pinning) or dune-release runs (when releasing).
=> build-info: test that dune-project sets version

src/dune/dir_contents.ml
In 2.0, select choices can no longer be valid module names. So this
detection isn't necessary anymore.
=> Remove detection of used in select

boot/duneboot.ml
=> Fix bootstrap in OCaml >= 4.10 (-output-complete-obj => output-complete-exe)

src/dune/build.ml, src/stdune/list.ml, src/stdune/list.mli
The current definition of `cons` is non-standard and unused. By flipping the arguments, we make it more useful.
=> Fix the order of arguments of [cons]

src/dune/gen_rules.ml, src/dune/install_rules.ml, src/dune/install_rules.mli
In our internal repo this reduces the Dune's memory consumption from 11GB to 5GB.
=> Memoize generation of rules for dune-package and meta files

CHANGES.md, doc/dune-files.rst, dune-project, src/dune/dune_project.ml
It's now true by default as it was in 1.x
=> Revert implicit transitive default

bin/compute.ml, src/memo/function.ml, src/memo/function.mli, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
Often, we just use dummy values for them anyway. Might as well not
bother in those cases.
=> Make memoization docs optional

.ocamlformat-ignore
Apparently `boot/duneboot.ml` is generated too. A follow up to #2906.
=> Add boot/duneboot.ml to .ocamlformat-ignore

src/dune/command.ml, src/dune/install_rules.ml
=> Drop unnecessary [doc] arguments when using Memo

doc/foreign-code.rst, src/dune/dir_contents.mli, src/dune/dune_file.ml, src/dune/dune_file.mli, src/dune/exe.ml, src/dune/exe_rules.ml, src/dune/foreign.ml, src/dune/foreign.mli, src/dune/foreign_sources.ml, src/dune/foreign_sources.mli, src/dune/lib.ml, src/dune/lib_archives.ml, src/dune/lib_info.mli, src/dune/lib_rules.ml, src/stdune/path.mli, test/blackbox-tests/test-cases/foreign-library/run.t
As reported in #2914, it's currently not possible to have a library with a foreign archive in a subdirectory:
`(library ... (foreign_archive dir/lib) ...)`
To support such "relative" foreign archives in libraries, we need to pass the `-L dir` flag when linking the executables, which depend on such libraries.
This patch does a fair amount of refactoring, to make the logic less error prone due to the confusion between various `string`-like types.
TODO:
=> Add support for relative foreign archives in libraries

README.md
The instruction with `_boot` didn't work for me, but with `_build` it does. So I hope this change is correct.
=> Fix a typo in the installation instruction

bin/cache_daemon.ml, bin/common.ml, bin/common.mli, src/dune/config.ml, src/dune_cache_daemon/dune_cache_daemon.ml
So far the code was just forking and running the daemon, which had the advantage of not requiring an `exec` or looking up the dune executable paths. However this was dangerous as we inherited some global status (e.g. the global build directory) and would now prevent re-opening the logs to a different location.
This branch starts the cache by executing `dune cache start ...`.
=> Start cache daemon through an `exec`.

src/dune/lib.ml, src/dune/lib.mli
This PR adds a function `Lib.link_deps` to compute the list of files that are needed to link a library in an executable. This is needed for the new toplevel support method.
=> Add Lib.link_deps

.travis-ci.sh
`ocaml-secondary-compiler` is now available upstream. Will merge once CI passes.
=> Remove custom opam-repository for testing 4.02.3

doc/jsoo.rst
I had to modify the example to make it work with `dune 2.0.0`.
I believe we need `(modes js)` now because [`explicit-js-mode`](https://dune.readthedocs.io/en/latest/dune-files.html#explicit-js-mode) is the default for dune >= 2.0.0.
=> Update jsoo example for dune 2.0

src/stdune/digest.ml, test/blackbox-tests/test-cases/dialects/run.t, test/blackbox-tests/test-cases/dune-ppx-driver-system/run.t, test/blackbox-tests/test-cases/formatting/run.t, test/blackbox-tests/test-cases/merlin-tests/run.t, test/blackbox-tests/test-cases/multiple-private-libs/run.t, test/blackbox-tests/test-cases/output-obj/run.t, test/blackbox-tests/test-cases/ppx-rewriter/run.t, test/blackbox-tests/test-cases/private-public-overlap/run.t, test/blackbox-tests/test-cases/scope-ppx-bug/run.t, test/blackbox-tests/test-cases/shadow-bindings/run.t, test/blackbox-tests/test-cases/tests-stanza/run.t
We currently use `Marshal.to_string` with sharing enabled when computing digests of values of arbitrary types. It's better to use the `No_sharing` setting to avoid generating different digests for inputs that differ only in how they share internal values. For example, if a command line contains duplicate flags, such as multiple occurrences of the flag `-I`, then `Marshal.to_string` will produce different digests depending on whether the corresponding strings `"-I"` point to the same memory location or to different memory locations.
Note that a few digests in the testsuite changed. Presumably this is because the `No_sharing` setting is reflected in the resulting digest.
=> Make the function [Digest.generic] more robust

doc/quick-start.rst
Update the `quickstart` section to use `foreign_stubs`
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>
=> [DOC] quickstart: dune2 does no longer support c_flags

doc/dune, test/blackbox-tests/dune
There's no need for an intermediate diff step
=> Simplify some dune tests with mode promote

boot/duneboot.ml
on macOS, nproc doesnt exist and so bootstrap currently shows this
at build time:
```
./.duneboot.exe
/bin/sh: nproc: command not found
```
We now capture stderr in the bootstrap command invocation so that
the output is not sent onto the main console, making for a cleaner
build output on macOS.
Signed-off-by: Anil Madhavapeddy <anil@recoil.org>
=> do not show bootstrap command outputs on stderr when probing cpus

doc/dune-files.rst, doc/variants.rst
`modules_without_implementation` are a subset of `modules`
This is a suggestion that resulted from a discussion with @rgrinberg in Discord, when I didn't immediately realize I had to add my `virtual_modules` in `modules` too.
=> docs: clarify that `virtual_modules`, `private_modules` and

src/dune/file_tree.ml, src/memo/memo.ml, src/memo/memo.mli, src/stdune/fdecl.ml, src/stdune/fdecl.mli
It's useful to have a simple guarantee that forward declarations are read at most once via `Fdecl.get`, but currently `Fdecl.peek` gets in the way because it's unchecked. 
It appears that the only place we use `Fdecl.peek` is when implementing an "idempotent set" operation which permits multiple calls to `Fdecl.set` as long as they set the same value. 
This PR removes `Fdecl.peek` and adds `Fdecl.set_idempotent` instead.
=> Drop [Fdecl.peek]

bin/subst.ml
Ran across this when grepping through my `_opam` so I thought I might as well submit the fix.
=> Fix typo in documentation

src/dune/build_system.ml, src/dune/context.ml, src/memo/memo.ml, src/memo/memo.mli
It is possible to call `Memo.exec` on an asynchronous function from a synchronous one and then discard the result. The memoization framework does not support such sync-async dependencies and this PR adds a mechanism to detect and report them.
Surprisingly, with this change one of the tests fails on my machine, which means we do have such dependencies in Dune (or that I somehow messed up the detection). I'd like to see if the CI fails too.
=> Detect sync-async dependencies in the memoization framework

doc/caching.rst
Fixes this warning:
```
/builddir/build/BUILD/dune-2.1.0/doc/caching.rst:20: WARNING: Inline emphasis start-string without end-string.
```
=> Escape asterisk interpreted by sphinx as emphasis start without end.

doc/advanced-topics.rst, doc/concepts.rst, doc/cross-compilation.rst, doc/dune-files.rst, doc/migration.rst, doc/quick-start.rst, doc/tests.rst
Some code samples contain characters that the pygments Scheme lexer doesn't recognize, such as %.  This leads to warnings like this:
```
/builddir/build/BUILD/dune-2.1.0/doc/advanced-topics.rst:218: WARNING: Could not lex literal_block as "scheme". Highlighting skipped.
```
Use the lisp lexer instead for such samples.  The code is really neither Scheme nor Lisp, anyway.
=> Use the lisp lexer for code samples with non-Scheme characters

test/blackbox-tests/dune.inc, test/blackbox-tests/gen_tests.ml
Manually defined tests should always have corresponding .t files in the
test directory. Previously, such tests would be silently ignored.
This check allows us to catch some invalid test definitions.
=> Improve safety of gen_tests.ml

test/blackbox-tests/test-cases/lib/run.t
Followup to #3013
Without this, tests on my local were failing with
```
@@ -135,6 +135,7 @@ TODO: Fix %{libexec} and %{libexec-private} variables and test them.
$ cat >external/dune-project <<EOF
> (lang dune 2.1)
> (name external_library)
+  sh: line 2: warning: here-document at line 0 delimited by end-of-file (wanted `EOF')
$ cat >external/dune <<EOF
> (library
>  (name extlib)
```
=> Add missing EOF to heredoc

src/dune/action.ml, src/dune/action.mli, src/dune/build_system.ml, src/dune_cache/dune_cache.ml, src/stdune/path.ml, src/stdune/path.mli, test/blackbox-tests/test-cases/lib/run.t
Do not waste time looking up the cache and report cache miss for clearly non cachable files. Cachability is similar ton sandboxability, but subtly different. For instance there is no point in sandboxing a copy, but we want to look it up the cache to benefit from deduplication.
=> Skip looking up non cachable files.

.gitignore
- Adding `_opam` under the assumption that we generally develop dune in a sandbox (is this mistaken?)
- Adding `/boot.exe` since it is a build artifact
Signed-off-by: Shon Feder <shon.feder@gmail.com>
=> Add _opam and /boot.exe to git ignore

src/dune_cache/dune_cache.ml, src/stdune/path.ml, src/stdune/path.mli
In OPAM CI's model, multiple process use the cache simultaneously. They need to operate without interlocking lest the cache actually slows down the build. Atomic filesystem operation should guarantee that conflicting concurrent use trigger no hard errors, just cache misses at worst.
=> Do not lock the filesystem when using the cache.

bin/external_lib_deps.ml, src/dune/build.ml, src/dune/build.mli, src/dune/build_system.ml, src/dune/build_system.mli
`Build.t` expressions come with a few subtle invariants. This PR removes one of them, which requires that `Build.static_deps` is called before other type of static analysis so that `if_file_exists` queries are resolved at appropriate time.
(This is follows some initial investigation done in #2993.)
=> Simplify handling of [if_file_exists] build expressions

src/dune/action.ml, src/dune/action.mli, src/dune/build.ml, src/dune/build_system.ml, src/dune/simple_rules.ml
I came across a few occurrences of `Progn []` to denote the empty `Action` and I think such actions deserve a proper name.
=> Add [Action.empty]

src/dune/modules_field_evaluator.ml, test/blackbox-tests/test-cases/intf-only/run.t, test/blackbox-tests/test-cases/virtual-libraries/vlib/run.t
Some error messages contain:
```
This will become an error in the future.
```
even though they are already errors. This dates from the time these were warnings. This PR updates these messages.
=> Remove stale "This will become an error ..." messages

src/dune/dune_file.ml
This was only allowed in jbuild files and we no longer support jbuild files. We only keep the parser in order to provide a better error message.
=> Remove the logic to handle the (fallback) field

src/dune/watermarks.ml
Looks like OCaml 4.07 build was broken by this commit: https://github.com/ocaml/dune/commit/f941609a4852f10fc0e13353ce8141ca92fb0b6c. This PR should fix it.
=> Fix OCaml 4.07 build

src/stdune/list.ml
I'm not sure if this fixes #3048 or not, but it seems best to stick to tail
recursive things by default.
=> Make List.filter_{map,opt} tail recursive.

doc/dune-files.rst
Hi,
I guess this was just a typo. in the doc.
=> remove useless bracket

bin/common.ml, src/dune/action_dune_lang.ml, src/dune/context.ml, src/dune/dir_contents.ml, src/dune/dune_file.ml, src/dune/findlib/findlib.ml, src/dune/gen_meta.ml, src/dune/inline_tests.ml, src/dune/install.ml, src/dune/module_name.ml, src/dune/scheduler.ml, src/dune/upgrader.ml, src/stdune/list.ml, src/stdune/poly.ml, src/stdune/poly.mli, src/stdune/stdune.ml
To discourage the use of polymorphic comparison and make it easier to
detect where it's used.
=> Use Poly.compare instead of Stdune.compare

src/dune/findlib/findlib.ml, src/dune/gen_meta.ml, src/dune/lib_kind.ml, src/dune/lib_kind.mli, test/blackbox-tests/test-cases/meta-gen/run.t
This is a (hacky) solution for the problem reported in https://github.com/ocaml/dune/issues/3057.
With this fix, Dune can build the example from #3057. Not sure it's worth adding a separate test.
=> Extract information about the library kind from generated META files

src/dune/build.ml, src/dune/build.mli, src/dune/build_system.ml
We used to need a way to hide certain `Build.t` subexpressions behind `Lazy_no_targets` constructors. These constructors were not explored when computing the list of build targets (with `Build.targets`) and allowed us to avoid a cyclic dependency between computing the list of targets and resolving `If_file_exists` queries (hidden behind `Lazy_no_targets`).
Thanks to #3052, we no longer need to traverse `Build.t` expressions to compute the list of build targets, and we can therefore remove this bit of complexity.
Note that laziness here is used only to avoid cycles, i.e. it is not a performance optimisation, because we do evaluate everything when computing the list of static dependencies with `Build.static_deps`.
I checked that there is no degradation in performance or memory usage.
=> Remove [Build.Lazy_no_targets]

src/dune/build.ml, src/dune/build.mli, src/dune/build_system.ml
While working on memoizing `Build.static_deps` and `Build.exec` using `Memo`, we realised that `file_exists` and `eval_pred` never change within a single build, so it's better to treat them as top-level bindings instead (which will later turn into proper memoized function to track changes between builds).
Simply referring to `Build_system.file_exists` from within `build.ml` would create a cyclic module dependency, so we set `file_exists` and `eval_pred` via forward declarations.
=> Set [file_exists] and [eval_pred] as forward declarations

src/dune/build.ml, src/memo/memo.ml, src/memo/memo.mli, src/stdune/type_eq.ml, src/stdune/type_eq.mli
This PR removes the ad-hoc memoization used in `Build.exec`, switching to `Memo` instead. 
Since `Build.exec` is a polymorphic function and requires some `Type_eq` tricks to memoize with `Memo`, we also add `Memo.Poly` -- a general mechanism for memoizing polymorphic functions.
I checked that there is no significant degradation of performance or memory usage. We do allocate a little more memory due to using `Memo` hash tables, but the overhead is less than 1% when building Dune with Dune.
=> Memoize [Build.exec] using the memoization framework

src/dune/build.ml, src/dune/build.mli, src/dune/build_system.ml, src/dune/static_deps.ml, src/dune/static_deps.mli
Memoizing `Build.static_deps` not only allows us to avoid repeating work when entering `Build.Memo` nodes but also makes it possible to get rid of the lazy caching of `static_deps` in `Internal_rule`.
The modification of `Build.static_deps` led to some simplification of the `Static_deps` module.
I checked that there is no significant degradation of performance or memory usage.
=> Memoize [Build.static_deps]

test/blackbox-tests/dune.inc, test/blackbox-tests/gen_tests.ml
Still not perfect, but this commit allows me to at least generate the right stanza when adding a new test. 
Incidentally, this fixes the incorrect path separator committed in #3080.
=> Handle Windows paths better in [gen_tests.ml]

src/dag/dag.ml, vendor/incremental-cycles/src/incremental_cycles.ml, vendor/incremental-cycles/src/incremental_cycles.mli, vendor/incremental-cycles/src/incremental_cycles_intf.ml, vendor/update-incremental-cycles.sh
This PR updates the `incremental_cycles` vendored library to its last version.
I want to get this PR in before we start touching `incremental_cycles` as discussed in #2959 . 
This update comes with a minor API change for the [raw_add_edge] function, so I updated dag.ml accordingly. I wanted to make sure that the API change is properly accounted for, as it could be easily overseen.
=> Update the vendored incremental-cycles

bin/print_rules.ml, src/dune/build_system.ml, src/dune/build_system.mli, src/dune/rule.ml, src/dune/rule.mli
This PR merges `Rule.Pre_rule.t` and `Build_system.Internal_rule.t` into `Rule.t` (the difference between these two types had been gradually reduced in the last couple of months), and renames `Build_system.Rule.t` into `Build_system.Evaluated_rule.t`, hopefully making things easier to understand.
=> [WIP] One rule to rule them all

perf.sh
It seems the `perf.sh` script got broken after the bootstrap changes,
this PR fixes it.
=> [perf.sh] Fix after bootstrap changes

bin/common.ml, bin/common.mli, bin/exec.ml, bin/init.ml, bin/main.ml
This partially resolves https://github.com/ocaml/dune/issues/3007 by adding short examples for the `build`, `runtest` and `exec` subcommands (as well as for the main `dune --help` page). For example, `dune exec --help` now contains the following section:
```
EXAMPLES
1.  Run the executable named `my_exec':
dune exec my_exec
2.  Run the executable defined in `foo.ml' with the argument `arg':
dune exec ./foo.exe -- arg
```
The `EXAMPLES` sections are positioned near the bottom of their respective man-pages [by convention](man7.org/linux/man-pages/man7/man-pages.7.html).
=> Add examples to the manpages of major subcommands

bin/common.ml, src/dune/config.mli
We already have an error message when this variable is incorrectly set, but I think it's a slightly better user experience this way.
We could do something similar for the other `DUNE_CACHE_*` variables if you like the idea.
CC. @mefyl
=> Explicitly enumerate accepted DUNE_CACHE env values

bootstrap.ml
Can't remember which version of OCaml fixed it, but warning 40 triggers on 4.02.3
=> Eliminate warnings on 4.02.3 bootstrap

CHANGES.md, bin/main.ml, doc/dune.inc, doc/tests.rst, doc/usage.rst, vendor/cmdliner/src/cmdliner_manpage.ml
Closes #3006
As noted in the comment, this follows the approach opam uses for its command aliases, visible here https://github.com/ocaml/opam/blob/fbbe93c3f67034da62d28c8666ec6b05e0a9b17c/src/client/opamArg.ml#L759-L775
No meaningful tests have occurred to me, and I'd be grateful for any testing suggestions if they occur to someone else. 
The top-level help text looks like this:
```
COMMAND ALIASES
test
An alias for runtest.
```
where the `COMMAND ALIASES` section follows immediately after the `COMMANDS` section.
The `dune test --help` gives:
```
dune-test(1)                      Dune Manual                     dune-test(1)
NAME
dune-test - An alias for runtest.
SYNOPSIS
dune test [OPTION]... [DIR]...
DESCRIPTION
dune test is an alias for dune runtest.
See dune runtest --help for details. …
```
=> Make `dune test` a command alias for `dune runtest`

CONTRIBUTING.md, README.md, bin/cache_daemon.ml, bin/common.ml, bin/help.ml, doc/advanced-topics.rst, doc/concepts.rst, doc/cross-compilation.rst, doc/dune-files.rst, doc/dune-libs.rst, doc/foreign-code.rst, doc/jsoo.rst, doc/make-help.txt, doc/tests.rst, doc/usage.rst, doc/variants.rst
Fixes typos, capitalisation errors (GitHub, Javascript etc.) and some standard Frenchisms ('informations', 'allows to' etc.).
=> Assorted documentation spelling and grammar fixes

test/blackbox-tests/gen_tests.ml
This should fix the bug where blackbox-tests from `_build` directory are added to the generated dune rules.
I unfortunately was unable to reproduce the bug and therefore to test that fix.
=> Fix blackbox test discovery

src/memo/memo.ml, src/memo/memo.mli
This is required for the fibered generation of rules
=> Add Memo.Lazy.Async

dune-action-plugin.opam, dune-build-info.opam, dune-configurator.opam, dune-glob.opam, dune-private-libs.opam, dune-project, otherlibs/configurator/src/dune, otherlibs/configurator/src/v1.ml, otherlibs/configurator/test/blackbox-tests/test-cases/configurator/config/run.ml, otherlibs/configurator/test/blackbox-tests/test-cases/configurator/run.t, src/dune/context.ml, src/dune/gen_rules.ml, src/dune/lib_info.ml, src/dune/lib_info.mli, src/dune/link_time_code_gen.ml
Currently, every time we call a program using `dune-configurator`, it systematically calls `ocamlc -config`. And after the recent changes to cram test, for every shell phrase we call a sanitizer that uses `dune-configurator` (to obtain the various os dependent file extensions).
This is not very efficient.
To avoid this, this PR changes things so that the ocaml configuration is passed from dune to dune-configurator through a file. This file is stored as `_build/<context>/.dune/configurator`. Since we don't have a convenient way to detect that a binary will read this file and we don't want user of configurator to manually add this dependency, we simply create this file eagerly when setting up the context.
The last thing dune needs to pass to `dune-configurator` through an environment …
=> Pass ocaml configuration to configurator through a file

dune, example/dune, otherlibs/action-plugin/test/depend-on-directory-without-targets/dune, otherlibs/action-plugin/test/dependency-rebuilt-but-not-changed/dune, otherlibs/action-plugin/test/depends-on-directory-with-glob/dune, otherlibs/action-plugin/test/depends-on-its-target-by-read-dir/dune, otherlibs/action-plugin/test/depends-on-its-target/dune, otherlibs/action-plugin/test/do-not-rebuild-unneeded-dependency/dune, otherlibs/action-plugin/test/multiple-dynamic-run-within-single-action/dune, otherlibs/action-plugin/test/no-dependencies/dune, otherlibs/action-plugin/test/one-absent-dependency/dune, otherlibs/action-plugin/test/one-dependency-with-chdir/dune, otherlibs/action-plugin/test/one-dependency/dune, otherlibs/action-plugin/test/one-directory-dependency/dune, otherlibs/action-plugin/test/one-target/dune, otherlibs/action-plugin/test/one-undeclared-target/dune, otherlibs/action-plugin/test/ordinary-executable/dune, otherlibs/action-plugin/test/simple-copy/dune, otherlibs/action-plugin/test/target-in-parent-directory/dune, otherlibs/action-plugin/test/two-stages-dependency-choose/dune, otherlibs/build-info/test/dune, otherlibs/configurator/src/v1.ml, otherlibs/configurator/test/blackbox-tests/dune, test/blackbox-tests/cram.mll, test/blackbox-tests/dune, test/blackbox-tests/dune.inc, test/blackbox-tests/gen_tests.ml, test/blackbox-tests/sanitizer.ml
This is in preparation of making cram test available to users.
This PR is for two reasons:
- I plan to merge the cram test tool directly into dune, as `dune cram`. It is very small and that will make distribution easier
- users will be allowed to define their own sanitizer
=> Split out the cram test sanitizer

test/blackbox-tests/test-cases/byte_complete/run.t, test/blackbox-tests/test-cases/cram/run.t
My shell emits a warning, which breaks the tests.
```
+  /tmp/dune-teste7152a.sh: line 6: warning: here-document at line 1 delimited by end-of-file (wanted `EOF')
```
Signed-off-by: mefyl <mefyl@gruntech.org>
=> Add missing EOF terminators to blackbox tests.

src/dune/coq_rules.ml
In Coq, dependencies of a `.vo` file on other `.vo` files are
link-time dependencies given that Coq will load all the dependencies
transitively. For example, imagine the situation where we have a
dependency chain, `Require`-wise:
```
a.v ← b.v ← c.v
```
[that is to say, `c.v` only `Requires Import b.`]
In this case, loading `b` will trigger the loading of `a` too; this
means that the dependencies of `c.v` must be computed transitively.
Unfortunately, in the average case this leads to a quadratic grow of
dependency edges; moreover, would we add these edges naïvely that we
would be wasting quite a bit of effort due to a lack of sharing
among the users of `b`.
However, in order to improve integrity, the current implementation of
Coq does add to module `c` a table with the digest of all …
=> [coq] Disable sandboxing for `.vo` rules

doc/concepts.rst, doc/opam.rst
This aims to address some shortcoming in the documentation around generating opam files, reported in #3070.
=> Improve docs on generating opam files (#3070)

.ocamlformat, otherlibs/configurator/src/v1.mli, src/dune/coq_module.mli, src/stdune/daemonize.mli, src/stdune/path_intf.ml
No option was added or removed between 0.12 and 0.13, there were only consistency fixes, so the upgrade should be painless.
=> Upgrade to ocamlformat 0.13.0

CHANGES.md, boot/duneboot.ml
Bootstrapping dune on a 1 core machine and a bytecode only switch is
broken because -custom is missing.
discovered by @xclerc
=> Fix bootstrap in bytecode mode

src/dune/build_system.ml, src/dune/rule.ml, src/dune/rule.mli
This removes `Rule.shim_of_build_goal` that was used to create fake rules for build requests with no targets, executed at the start of the build system. Note that we previously memoized the evaluation of "build requests" which seems unnecessary since they are evaluated only once. We therefore drop memoization, make this explicit by using the `Non_memoized` constructor.
=> Simplify building of "build requests"

doc/dune-files.rst, doc/opam.rst, doc/test/dune, doc/test/run.t
Dune docs contain some outdated code examples suggesting to use `(lang dune 1.0)` which may be confusing to users. This commit adds a test that reveals all such occurrences, making it easier to keep the docs up-to-date.
Ideally, we also need to parse all examples using the latest Dune... some day!
=> Add a test to find old versions of Dune language in docs

bin/import.ml, bin/install_uninstall.ml, src/dune/dune_load.ml, src/dune/file_tree.ml, src/dune/file_tree.mli, src/dune/gen_rules.ml, src/dune/super_context.ml, src/dune/super_context.mli
There's quite a few functions that just wrap various ways of donig
projections. The API is easier to understand if we get rid of all this
stuff.
=> Remove api bloat in File_tree

bin/install_uninstall.ml, src/dune/context.ml, src/dune/context.mli, src/stdune/env.ml
It turned out we only ever look up two OPAM config variables: `lib` and `prefix`. Both can be turned into lazy values instead.
=> Remove an ad-hoc cache table for Opam config variables

test/blackbox-tests/dune.inc, test/blackbox-tests/test-cases/invalid-module-name/run.t
Reproduces an issue where dune is attempting to build with an invalid
module name.
@diml what do you think is the correct behavior here? Shall we just ignore such
sources or warn/error?
=> Use invalid module name as source

src/dune/context.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
This adds appropriate cutoff for OPAM config variables (#3150).
Once we memoize various file-system accessors, many other occurrences of `Memo.lazy_` will need to be annotated with appropriate equality checks for cutoff.
=> Add a way to specify cutoff in [Memo.Lazy] and [Memo.Async.Lazy]

boot/libs.ml
A left-over from a recent change to the pretty-printer.
=> Regenerate a generated file

src/dune/context.ml, src/dune/context.mli, src/dune/foreign_rules.ml, src/dune/lib_config.ml, src/dune/lib_config.mli, src/dune/lib_rules.ml, src/ocaml-config/dune, src/ocaml-config/ocaml_config.ml, src/ocaml-config/ocaml_config.mli, src/stdune/dyn.ml
This check is useful for other users of Ocaml_config. I also get rid of the
duplication in Lib_config and Context.
=> Move Ccomp_type to Ocaml_config

src/dune/artifacts.ml, src/dune/context.ml, src/dune/context.mli
We also refactor code to make the mechanism of preferring `.opt` executables robust, by explicitly listing all programs for which we prefer the `.opt` versions instead of relying on the order of calls to `which`. We also discover and signpost a bug in the process.
I guess this might deserve a line in the change log, since the old `opt`-preferring behaviour was fragile and we could accidentally resolve some executables incorrectly.
=> Remove the ad-hoc [which_cache]

src/dune/context.ml
We treat such paths incorrectly. Better report an error instead.
=> Disallow relative paths in Findlib configuration

src/dune/context_name.mli, src/dune/lib.ml, src/dune/module_name.mli, src/dune/per_item.ml, src/dune/per_item.mli, src/dune/per_item_intf.ml, src/dune/top_closure.ml, src/dune/top_closure.mli, src/dune/top_closure_intf.ml, src/stdune/io.ml, src/stdune/io.mli, src/stdune/io_intf.ml, src/stdune/monad.ml, src/stdune/monad.mli, src/stdune/monad_intf.ml, src/stdune/stdune.ml
To avoid duplication, we store module signatures in separate modules.
This PR applies this style across the codebase.
=> Make signature handling more consistent

src/dune/coq_rules.ml, src/dune/coq_sources.ml, src/dune/coq_sources.mli, src/dune/dir_contents.ml, src/dune/dir_contents.mli
The error message was incorrect. It mentioned that coq doesn't support
[(include_subdirs unqalified)], but in fact it doesn't support
[qualified].
=> Fix qualification handling in coq

src/dune/dir_contents.ml, src/dune/dir_contents.mli, src/dune/exe_rules.ml, src/dune/foreign_sources.ml, src/dune/install_rules.ml, src/dune/lib_archives.ml, src/dune/lib_rules.ml, src/dune/virtual_rules.ml
The foreign_source_of_* family of functions were just wrappers without
additional abstraction. It's just as easy to do the extra function call
in the callers.
=> Remove unnecessary functions from [Dir_contents]

src/dune/env_node.ml, src/dune/env_node.mli, src/dune/super_context.ml, src/dune/super_context.mli, test/blackbox-tests/dune.inc, test/blackbox-tests/test-cases/env/env-affects-expander-affects-env/dune, test/blackbox-tests/test-cases/env/env-affects-expander-affects-env/run.t
This removes mutation from `Env_node`, switching to `Memo.Lazy`. 
The logic is also slightly simplified by factoring out some common patterns (e.g. `inherited`). The resulting code is still rather convoluted due to the proliferation of lazy computations but hopefully the new state is still an improvement.
When implementing, we noticed that tests were not very good (the first draft was wrong yet passed the testsuite), so we've also added a test to make sure we use the right expanders.
=> Remove ad-hoc memoization in [Env_node]

src/dune/alias.ml, src/dune/build_system.ml, src/dune/cached_digest.ml, src/dune/context.ml, src/dune/dune_project.ml, src/dune/findlib/findlib.ml, src/dune/gen_rules.ml, src/dune/lib.ml, src/dune/opam_file.ml, src/dune/preprocessing.ml, src/dune/response_file.ml, src/dune/scheduler.ml, src/dune/sub_system_info.ml, src/dune_lang/versioned_file.ml, src/memo/memo.ml, src/stdune/interned.ml
Also delete redundant recalculation of `Ocaml_version`.
=> Mark all remaining mutable tables as safe or to-be-removed

src/dune/super_context.ml
Because we are using [with_record_no_ddeps], we aren't allowed to
collect any dynamic dependencies.
=> Add assertion explaining TODO

src/stdune/path.ml, src/stdune/set.ml
The implementation does mkdir_p relative to the appropriate [root] works
in both cases.
=> Remove duplicate mkdir implementation

.travis-ci.sh
```
#=== ERROR while compiling zed.2.0.5 ==========================================#
662# context     2.0.5 | linux/x86_64 | ocaml-system.4.09.0 | https://opam.ocaml.org#20e0fd9d
663# path        ~/.opam/default/.opam-switch/build/zed.2.0.5
664# command     ~/.opam/default/bin/dune build -p zed -j 1
665# exit-code   1
666# env-file    ~/.opam/log/zed-26170-d8a3f7.env
667# output-file ~/.opam/log/zed-26170-d8a3f7.out
668### output ###
669# Error: The implementation src/zed_string.ml
670# [...]
671#          val compare_index :
672#            t ->
673#            ('a, 'b) result ->
674#            ('a, 'b) result ->
675#            ok:('a -> 'a -> int) -> error:('b -> 'b -> int) -> int
676#        is not included in
677#          val compare_index : t -> index -> index -> int
678# …
```
=> Downgrade zed to make CI pass

src/dune/dir_contents.ml, src/dune/dir_status.ml, src/dune/dir_status.mli
Add separate cases for generated directories and source directories
without dune files.
=> Improve Dir_status readability

src/dune/ml_sources.ml
The check should occur only when we need the OCaml modules
This also fixes the problem @ejgallego reported. It's not strictly necessary now that he's made the other fix, but i think we might as well preserve the old behavior to be safe.
=> Ml_sources: Make include_subdirs more lazy

src/dune/coq_module.ml, src/dune/coq_module.mli, src/dune/coq_rules.ml, test/blackbox-tests/test-cases/coq/run.t
- After changes upstream, passing `-coqlib` is not necessary now,
`-boot` will disable hardcoded paths in Coq, the regular `-R` prefix
adds the stdlib in scope.
- Install layout when a library has `(boot)` is a bit different, in
particular we don't install in `user-contrib` but in theories.
=> [coq] Further Coq stdlib bootstrap tweaks

src/dune/gen_rules.ml
Fixes #3206 ; in particular one has to be careful to scan directories
before actual stanzas need it.
=> [gen_rules] Don't load ml_sources eagerly in gen_rules

src/cache/local.ml, test/blackbox-tests/test-cases/dune-cache/trim/run.t
=> Don't crash when trimming while the cache directory does not exist.

src/dune/build_system.ml, src/dune/cached_digest.ml, src/dune/scheduler.ml, src/stdune/hashtbl.ml, src/stdune/hashtbl_intf.ml
Stdune's hash tables do not support multiple bindings.
While I'm at it, should we rename all the names in hashtable that involve `add` into `set`? We don't support multiple bindings so our naming should reflect that.
thanks @giltho!
=> Implement [Hashtbl.set] using [replace]

src/dune_util/report_error.ml, test/blackbox-tests/test-cases/dir-target-dep/run.t
Segfault means a specific thing that is in fact never accompanied by this message.
Let's change the message to not be misleading by saying "crash" instead of "segfault".
=> Change an error message: segfault -> crash

bin/caching.ml, bin/common.ml, bin/subst.ml, src/dune/config.ml, src/dune/config.mli, src/dune/process.ml, src/dune/scheduler.ml, src/dune_util/log.ml, src/dune_util/log.mli, src/stdune/console.ml, src/stdune/console.mli, test/expect-tests/common/dune_tests_common.ml, test/expect-tests/vcs_tests.ml
This is in preparation for #3068. This PR generalises the `Console` module. The console is now seen as an abstract system that can report messages and a status the user.
The module now allows to set the actual backend, compose backends, etc... #3068 will simply provide a new backend for the console.
=> Generalise the Console module

src/dune/lib.ml, src/dune/lib.mli, src/dune/scope.ml
Lib.Hidden is used to represent hidden libraries for both the status of libraries in the database and Resolve_result. This requires us to introduce a type parameter but we can keep it out of the public API by making Resolve_result abstract.
=> Introduce Lib.Hidden

doc/dune-files.rst
It made the documentation at the page https://dune.readthedocs.io/en/stable/dune-files.html sound a little strange.
=> Typo in the documentation

src/memo/memo.ml, src/memo/memo.mli
This patch makes handling of normal values and exceptions more uniform, which simplifies the code, allowing us to get rid of the `Failed` state. We also remove some functionality related to `on_already_reported` which is no longer used.
I run some testing in file-watching mode to make sure errors are reported correctly (and eagerly) and we do not start to leak memory.
=> Treat exceptions as proper values in the memoization framework

src/cache/client.ml, src/cache/local.ml
The client implementation teardown now calls the underlying local implementation teardown, to ensure temporary directory are cleaned up. If you used daemon mode, you might have a lot of leaked `~/.cache/dune/db/v2/promoting*` empty directories worth removing manually.
=> Don't leak temporary directory in cache daemon mode.

bin/init.ml, src/dune/dune_init.ml, src/dune/dune_project.ml, src/dune/format_config.ml, src/dune/process.ml, src/dune/scheduler.ml, src/dune_util/report_error.ml, src/stdune/ansi_color.ml, src/stdune/pp.ml, src/stdune/pp.mli, src/stdune/user_error.ml, src/stdune/user_message.ml, src/stdune/user_warning.ml
Remove the `~tag` label of `Pp.tag`. I always found this label a bit annoying as it is redundant with the function name.
Before:
```ocaml
val tag : 'a t -> tag:'a -> 'a t
```
after:
```ocaml
val tag : 'a -> 'a t -> 'a t
```
=> Remove tag label to Pp.tag

src/stdune/list.ml, src/stdune/list.mli, src/stdune/ordering.ml, src/stdune/ordering.mli
This is necessary for me in ocaml-lsp. I figured that it's better to maintain
this stuff in one place.
=> [stdune] introduce List.min_by

src/dune/string_with_vars.ml, src/dune_lang/lexer.mll, src/dune_lang/template.ml, src/dune_lang/template.mli, src/jbuild_support/string_with_vars.ml, test/blackbox-tests/test-cases/output-obj/run.t, test/blackbox-tests/test-cases/tests-stanza/run.t, test/expect-tests/dune_lang/sexp_tests.ml
The only recognised syntax is `%{...}`, no need to support other older syntaxes. This simplifies a bit the code
=> Remove some vestigial jbuilder code related to variable syntax

src/dune/lib.ml, src/dune/lib.mli, src/dune/scope.ml, src/dune/scope.mli, src/dune/super_context.ml
We make the handling of Coq theories to be independent of `Lib`, which
deals with OCaml libs. This is in preparation for the introduction of
composition with inter-scope public Coq theories.
This is softer alternative to #3280, at the cost of introducing some
uglier code in `Scope`.
=> [coq] Rework Coq_lib.DB handling as not to interfere with `Lib`

test/blackbox-tests/dune.inc, test/blackbox-tests/gen_tests.ml
topfind is provided by ocamlfind
=> [tests] toplevel-integration has external dep

src/dune/build_system.ml, test/blackbox-tests/test-cases/dir-target-dep/run.t
When there's a rule that tries to create a target that is already a
soure directory, this should be reported as an error.
=> Detect rule target & source dir overlap

doc/dune-files.rst
Coq users are so used to doing `Cd` in extraction prelude files to
workaround the Coq output bug that we should warn them against that.
=> [coq] Nit on documentation for extraction.

src/dune/coq_lib.ml, src/dune/coq_lib.mli, src/dune/coq_rules.ml
Otherwise when composing with Coq itself, libraries not using `From Coq` won't compile.
This is until we deprecate the implicit nature of the Coq prefix, which I'm going to try in 8.12 cc: @Zimmi48
=> [coq] Allow implicit composition with the boot theory.

otherlibs/cram/bin/sanitize.ml
Allows to sanitize list of directories that can be found in environment variables
From #3104, used just during debugging but still useful.
=> [Cram sanitization] path separator used to separate directory

src/dune/action_dune_lang.ml, src/dune/bindings.ml, src/dune/blang.ml, src/dune/dep_conf.ml, src/dune/dune_env.ml, src/dune/dune_file.ml, src/dune/foreign.ml, src/dune/format_config.ml, src/dune/inline_tests.ml, src/dune/lib_dep.ml, src/dune/mdx.ml, src/dune/package.ml, src/dune_lang/decoder.ml, src/dune_lang/decoder.mli, test/blackbox-tests/test-cases/cmdliner-dep-conf/run.t, test/blackbox-tests/test-cases/re-exported-deps/run.t
This is part of a larger work to make `Decoder.t` a pure applicative (or selective, will see how it goes). Once we remove `Decoder.(>>=)`, we need a lot more specialised `if_xxx` functions. To avoid their proliferation, this PR proposes to replace them all by a single and general `alt` combinator that tries a list of parsers in sequence and uses the first one that succeeds:
```ocaml
val alt : 'a t list -> 'a t
```
The difficult part is to decide which error to reraise when they all fail. Ideally, we want to reraise the one from the branch that matched the most structural elements. This is difficult to implement right now, so I used a rubbish implementation that will lead to bad error messages in some cases. However, once `Decoder.t` is a pure applicative, it should be easier to change it …
=> Replace all the Decoder.if_* functions by a single Decoder.alt

bin/caching.ml, src/stdune/daemonize.ml, src/stdune/daemonize.mli
This fixes a couple of typos and makes the meaning of `string` in the callback a bit more obvious in the interface of `daemonize`.
=> Minor improvements to docs and [daemonize] interface

.travis-ci.sh
@snowleopard @ejgallego I believe this should unbreak travis. Looking at the log, it seems that it's because an opam command is trying to upgrade coq and doesn't go through the `keep_travis_happy`.
We might need a more general solution moving forward though.
=> Upgrade to Coq 8.11.1 in Travis

bin/caching.ml, src/cache/local.ml, src/cache/local.mli, test/blackbox-tests/test-cases/dune-cache/trim/run.t
This implements the first step of #3357.
=> Decouple versions of file and metadata stores in the cache

dune-project
It looks like the Dune's `dune-project` file has fallen behind, and some useful features (like #3092) are not enabled leading to problems like those discussed in #3376.
Let's bump the version to `2.5`. 
Shall we do any other adjustments to `dune-project` to safely transition to the new version?
=> Bump dune-project to 2.5

src/dune/cinaps.ml, src/dune/compilation_context.ml, src/dune/compilation_context.mli, src/dune/exe_rules.ml, src/dune/inline_tests.ml, src/dune/lib_rules.ml, src/dune/super_context.ml, src/dune/super_context.mli, src/dune/toplevel.ml, src/dune/utop.ml
This setting is specific to OCaml compilation, so it should be in the
compilation context as much as possible.
This allows us to remove yet another function from Super_context
=> Move opaque setting to Compilation_context

src/dune/build.ml, src/dune/build.mli, src/stdune/applicative.ml, src/stdune/applicative_intf.ml
This makes it usable with all applicative consuming functors
=> Add applicative interface to build

src/dune/action_ast.mli
This module was missing an mli for quite a while. The omission must have
been accidental.
=> Write mli for Action_ast

src/dune/build_system.ml, src/dune/build_system.mli, src/dune/install_rules.ml, src/dune/mdx.ml, src/dune/super_context.ml, test/blackbox-tests/test-cases/reporting-of-cycles/run.t
* Properly error on missing packages in (package ..) definitions
* Move <pkg>-files aliases to the package dir. This makes rule loading
lazier.
=> Package dependency handling

src/stdune/fcntl_stubs.c
I'm updating the `dune-windows` package and this header is giving me grief. Apparently, lower or uppercase shouldn't matter on windows so I'm proposing we change it to lowercase, which works for me. See: https://stackoverflow.com/questions/15466613/lowercase-windows-h-and-uppercase-windows-h-difference
=> Lowercase `windows.h`

src/dune/context.ml, src/fiber/fiber.ml, src/fiber/fiber.mli
And re-implement its only use case using simpler concepts.
This reduces the overall amount of code and concepts.
=> Remove fiber.once

bin/describe.ml, test/blackbox-tests/test-cases/describe/run.t
This field contains the list of directories containing all the cmi's of
a library.
=> Add include_dirs field to dune describe

otherlibs/configurator/src/dune, otherlibs/configurator/src/dune_lang.ml, otherlibs/configurator/src/dune_lang.mli, otherlibs/configurator/src/import.ml, otherlibs/configurator/src/ocaml_config.ml, otherlibs/configurator/src/ocaml_config.mli, otherlibs/configurator/src/v1.ml, src/dune/context.ml, src/ocaml-config/ocaml_config.ml, src/ocaml-config/ocaml_config.mli
@diml I'm wondering, perhaps we should just merge ocaml_config and configurator?
=> Remove stdune from configurator and switch to csexp

bin/arg.ml, bin/arg.mli, bin/caching.ml, src/cache/local.ml, src/cache/local.mli, src/cache_daemon/cache_daemon.ml, src/cache_daemon/utils.ml, src/dune/config.ml, src/dune/config.mli, src/dune_lang/decoder.ml, src/dune_lang/decoder.mli, src/stdune/dyn.ml, src/stdune/dyn.mli, src/stdune/sexp.ml, test/blackbox-tests/test-cases/dune-cache/trim/run.t
This PR does a few things:
* As discussed with @mefyl, cache trimming no longer removes unused files that are referenced from broken metadata files because doing so may in turn break more metadata files.
* I simplified `Trimming_result` since two of its fields were unused (and in some cases were not updated correctly).
* We now take into account the size of removed metadata files in `Trimming_result`.
* As discussed with @jeremiedimino, I switched to using `int64` for aggregating file sizes to make this  work on 32-bit platforms. As noted in a comment, we still can't support files larger than 1GB on 32-bit platforms because we pervasively use `int` for representing individual file size. We can improve this in future.
* The latter required to add some support for `int64` to Stdune.
=> Refactor cache trimming

otherlibs/configurator/src/v1.ml, otherlibs/configurator/test/blackbox-tests/test-cases/configurator/config/run.ml, otherlibs/configurator/test/blackbox-tests/test-cases/configurator/run.t, src/dune/context.ml
@jeremiedimino, as discussed, we support both versions of the configurator protocol
=> Generate ./dune/configurator in the old format

bin/target.ml, src/dune/action_unexpanded.ml, src/dune/action_unexpanded.mli, src/dune/artifacts.mli, src/dune/context.ml, src/dune/context.mli, src/dune/dep_conf_eval.ml, src/dune/dep_conf_eval.mli, src/dune/dir_contents.ml, src/dune/dir_contents.mli, src/dune/exe_rules.ml, src/dune/expander.ml, src/dune/expander.mli, src/dune/foreign_rules.ml, src/dune/format_rules.ml, src/dune/gen_rules.ml, src/dune/inline_tests.ml, src/dune/merlin.ml, src/dune/preprocessing.ml, src/dune/preprocessing.mli, src/dune/simple_rules.ml, src/dune/super_context.ml, src/dune/super_context.mli, src/dune/test_rules.ml, test/blackbox-tests/test-cases/deps-conf-vars/run.t, test/blackbox-tests/test-cases/variables-for-artifacts/run.t
* some implementation details of the `expander` are now private
* it's no longer necessary to pass the same `foreign_flags` and `map_exe`
functions
=> Expander refactor

bin/main.ml, src/dune/scheduler.ml, src/fiber/fiber.ml, src/fiber/fiber.mli, test/expect-tests/fiber/fiber_tests.ml, test/expect-tests/memo/memoize_tests.ml, test/unit-tests/artifact_substitution/artifact_substitution.ml
The only call to `Fiber.yield` in the codebase is superfluous, let's get rid of it and simplify `Fiber.run`. This allows to remove the only bit of scheduling logic that was left in the `Fiber` module and keep it entirely in `src/dune/scheduler.ml`, which is nice.
The fiber tests were relying on `Fiber.yield`, so I just added a micro scheduler built on top of `Fiber` in the fiber tests. This micro scheduler is similar to the old implementation but uses only standard features exposed in the `Fiber` API.
=> Simplify Fiber.run

src/dune/scheduler.ml, src/fiber/fiber.ml, src/fiber/fiber.mli, test/expect-tests/fiber/fiber_tests.ml
`Fiber.peek` and `Fiber.ivar` are the only two functions that are not pure in the API of Fiber. This PR makes them pure.
=> Purify fiber

src/dune_util/report_error.ml, test/blackbox-tests/test-cases/dir-target-dep/run.t
- remove the second `Error: ` prefix for `Unix_error`
- drop the backtrace and only print the message for `Sys_error`
=> Improve printing of Sys_error and Unix_error exceptions

test/blackbox-tests/test-cases/dune-cache/trim/run.t, test/blackbox-tests/utils/dune_cmd.ml
Use dune_cmd stat rather than the non portable stat
=> Fix stat test to be cross platform

doc/faq.rst
This adds a FAQ entry about how to generate a mli file for a ml-only module.
=> Document ocaml-print-intf

doc/concepts.rst, doc/documentation.rst, doc/dune-files.rst, doc/dune-libs.rst, doc/faq.rst, doc/goals.rst, doc/tests.rst, doc/variants.rst
Hi,
This fixes markup (some warnings and some text that was in italics rather than in fixed width), and some duplicate words.
=> Fix markup in doc

doc/dune-files.rst, doc/tests.rst
The individual options (`(deps)` etc) are documented on the tests page but there was no pointer.
=> Document (inline_tests) in libraries

doc/dune-files.rst
This causes weird link text (and wrong targets) such as:
> Build contexts can be specified by writing a mdx (since 2.4) file
=> Doc: fix dune-workspace ref

test/expect-tests/fiber/fiber_tests.ml
Print the exact results of tests where possible.
I'd also like to clean up the other tests that use flags. @jeremiedimino what
about just printing the value of the flag and whether Never was raised at the
end of the run?
=> Cleanup output of fiber tests

otherlibs/configurator/src/import.ml
=> [configurator] restore compat with 4.07

src/dune/process.ml, src/stdune/spawn.ml, src/stdune/spawn.mli
There's an Env in stdune
@jeremiedimino I noticed that Spawn.spawn behaves slightly differently on
windows and everywhere else. `Unix.create_process` looks up `prog` in `PATH`,
while `exec` does not.
=> Remove extra Env module in Process

CHANGES.md
- `bisect_ppx` has been reverted in the 2.6.0 branch
- in-process formatting has been done since
=> Fix 2.6.0 changelog

src/stdune/spawn.ml
The function behaves slightly differently between windows and unix. We
should consider changing it. For now, I just noted the difference with a
comment.
=> [stdune] document Spawn.spawn

boot/duneboot.ml, otherlibs/cram/bin/cram_lexer.mli, otherlibs/cram/bin/cram_lexer.mll, otherlibs/cram/bin/run.ml, otherlibs/cram/bin/sanitize.ml, otherlibs/cram/bin/sanitizer.ml, otherlibs/cram/bin/sanitizer.mli, src/dune/action_exec.ml, src/dune/process.ml, src/stdune/env.ml, src/stdune/env.mli, src/stdune/fpath.ml, src/stdune/fpath.mli, src/stdune/path.ml, src/stdune/path.mli, src/stdune/sexp.ml, src/stdune/sexp.mli, src/stdune/temp.ml, src/stdune/temp.mli
=> [cram] file generation

src/fiber/fiber.ml, test/expect-tests/fiber/fiber_tests.ml
Forking, waiting for the thread, and then waiting for the finalizer to
run does not work.
@jeremiedimino this seems like an issue with fork. Seems like wait `deref`
should be called on `Future.wait`.
cc @andreypopp
=> Add test for finalize/fork behavior

doc/dune-files.rst
In `(lang dune 2.0)` it already provides a useful error message, so the documentation is not that useful.
=> Remove (no_keep_locs) doc

otherlibs/configurator/src/v1.ml
When dune-configurator is used with dune 2.5.1, dune will not create the right file. When using opam, this is prevented by the correct metadata, but this triggers an unpleasant error message when dune is picked from the system `$PATH`.
This also cleans up the output so that a pretty "Error: ..." is displayed.
See #3572 (cc @avsm)
=> Improve error for configurator + dune < 2.6

src/dune/context.ml, src/dune/scheduler.ml, src/fiber/fiber.ml, src/fiber/fiber.mli, test/expect-tests/fiber/fiber_tests.ml
As discussed during yesterday's meeting, this PR removes `Fiber.fork` because it is difficult to reason about, especially in the presence of exceptions. `Fiber` instead becomes a [structured concurrency monad](https://en.wikipedia.org/wiki/Structured_concurrency), which is much simpler to reason about.
To remove the `Fiber.fork` in the scheduler, I introduced a `Fiber.run2` function. This function feels a bit ad-hoc and eventually we should replace it by something more idiomatic, but in the meantime it will do. In particular, it is required because of the way we handle polling; as soon as a file changes, we abort the whole computation immediately. Essentially we throw out the entire fiber tree and restart from scratch. This requires terminating as soon as a a certain event is received …
=> Remove Fiber.fork

test/blackbox-tests/test-cases/c-stubs/run.t, test/blackbox-tests/test-cases/contents-depends-on-glob/run.t, test/blackbox-tests/test-cases/copy_files/run.t
We were just looking at tests that need the sanitizer with Rudi, and our finding is that:
- there are not that many tests that need the extension sanitazation
- many of them can be simplified in a way that sanitization is not needed
- for the few remaining ones, we can just do it manually
This will simplify the cram system even more.
This PR just changes a few tests we looked at.
=> Cleanup a few tests

dune
As the comment states, we do not need this anymore now that 4.07 support is dropped.
=> Remove ocaml-syntax-shims from (binaries)

test/blackbox-tests/test-cases/check-alias/run.t
-printf isn't available in macos find
=> Replace -printf with awk

src/fiber/fiber.ml, src/fiber/fiber.mli, test/expect-tests/fiber/dune, test/expect-tests/fiber/fiber_tests.ml
To allow iterating in parallel over infinite lists without leaking memory.
=> Add Fiber.Stream

doc/known-issues.rst
The explanation is taken from @ejgallego's answer under https://coq.zulipchat.com/#narrow/stream/240550-Dune-devs.20.26.20users/topic/dune.20and.20parallel.20builds (unfortunately you must login to read it).
Also, if this is merged, please replace "jbuilder" by "dune" in the issue title, so that people who click the link aren't too confused.
=> Document #236 under "Known issues"

test/blackbox-tests/dune.inc, test/blackbox-tests/gen_tests.ml, test/blackbox-tests/test-cases/github25.t/run.t, test/blackbox-tests/test-cases/jsoo/github3622.t/run.t, test/blackbox-tests/test-cases/jsoo/simple.t/run.t
It's clearer to set the environment from the test itself. Also, it makes
it simpler to port to the cram stanza.
=> Remove setenv from findlib test

src/fiber/fiber.ml, test/expect-tests/fiber/fiber_tests.ml
Raising inside the callback of `Fiber.sequential_iter` does not respect
the current execution context.
This test just causes an abnormal exit so the output can't even be
collected for the exepct tests.
@jeremiedimino is this intentional? In `fork` it sems like we careful to
avoid this.
=> [fiber] test sequential_iter and expcetions

doc/concepts.rst, doc/dune-files.rst
=> Document re_export field

boot/duneboot.ml, otherlibs/action-plugin/src/dune_action_plugin.mli, otherlibs/configurator/src/v1.mli, src/dune/ordered_set_lang.mli
These happen when running `make fmt`.
=> Fix odoc warnings

src/dune/merlin_server.ml, test/blackbox-tests/test-cases/merlin/server.t/run.t
When Merlin will start relying on external readers, dune will not be immediately ready and continue to generate `.merlin` files in the source tree.
This PR thus disable the merlin configuration server and send an error message to Merlin that ask for a build of the project in order to generate the `.merlin` files.
In due time, dune will stop generating these files and send the configuration directly to merlin. (PR #3554)
=> Disable merlin config server until  files stop being generated

src/dune/process.ml
Recently I started getting the following errors when building moderately-sized workspaces:
```
Error: open: /dev/null: Too many open files
Error: open: /tmp/dune528db4.output: Too many open files
Error: open: /tmp/dune93b269.output: Too many open files
Error: open: /tmp/duneb4d3c8.output: Too many open files
Error: open: /tmp/dune472f36.output: Too many open files
Error: open: /tmp/dune62787e.output: Too many open files
Error: open: /tmp/dune0a6e20.output: Too many open files
Error: open: /tmp/dune096c63.output: Too many open files
Error: open: /tmp/dune955bb3.output: Too many open files
Error: open: /tmp/dune2bc4c9.output: Too many open files
Error: open: /tmp/dune5fb45e.output: Too many open files
Error: /tmp/dune887f90.output: Too many open files
Error: /tmp/dune974539.output: Too many …
```
=> Avoid repeatedly opening /dev/null

CHANGES.md, src/dune/dune_file.ml, src/dune/file_tree.ml, src/dune/stanza_common.ml, src/dune/stanza_common.mli, src/dune/sub_dirs.ml, src/dune/sub_dirs.mli, src/dune_lang/decoder.ml, src/dune_lang/decoder.mli, test/blackbox-tests/test-cases/ocaml-syntax.t/run.t, test/blackbox-tests/test-cases/subdir-stanza.t/run.t
Currently, the `(include ...)` stanza is processed after the `(subdir ...)` stanzas have been removed from the input. This makes it impossible to support `(subdir ...)` in a file used via `(include ...)`. The PR adjusts things so that the `(include ...)` stanza is processed simultaneously with `(subdir ...)`, so that this is allowed.
I found the code that handles `(subdir ...)` a bit tricky, so would appreciate a review by someone familiar with it. Thanks!
Fixes #3419
=> Allow (subdir ...) in dune files used via (include ...)

src/dune/scheduler.ml
When running dune build -w without inotify or fswatch, it refers to a non-existent library `fswtach`, presumably a typo.
Signed-off-by: Cameron Wong <cam@camdar.io>
=> fix typo (fswtach -> fswatch)

src/catapult/catapult.ml, src/dune/cram_exec.ml, src/stdune/io.ml, test/blackbox-tests/test-cases/dune
`Stdune.Io.read_all` fails on Windows when reading text files.
The reason is that `in_channel_length` does not actually give a correct estimate of the number of characters that will be read.
This PR makes us stop relying `in_channel_length` being a correct upper bound. Instead, we treat it as a hint, so the function succeeds both when the number is too high (on Windows) and when it's too low (on procfs).
=> Fix read_all on Windows for files open in text mode

test/blackbox-tests/test-cases/variables/var-cc.t/run.t
* -i wasn't used in a portable manner
* ocaml on mac includes some trailing space in compiler flags
=> [test] fix var-cc.t to work on macos

doc/concepts.rst
Using the former in a recent enough version of dune will produce the
following error:
Error: %{path:..} was renamed to '%{dep:..}' in the 2.1 version of the dune
language
=> Docs: replace `%{path:<path>}` with `%{dep:<path>}`

src/dune/expander.ml, src/dune/scope.ml, src/dune/scope.mli, src/dune/super_context.ml
* do not save project name. we can obtain it from the project
* don't save [context] name. it's only used for an error message where it
doesn't even help
* do not pass [lib_config] if there's a [context] available.
[lib_config] can be obtained from context
=> Clean up scope module

bin/printenv.ml, bin/top.ml, src/dune/cinaps.ml, src/dune/compilation_context.ml, src/dune/coq_rules.ml, src/dune/jsoo_rules.ml, src/dune/mdx.ml, src/dune/menhir.ml, src/dune/odoc.ml, src/dune/opam_create.ml, src/dune/preprocessing.ml, src/dune/super_context.ml, src/dune/super_context.mli, src/dune/toplevel.ml, src/dune/utop.ml
* build_dir & profile are all unnecessary and can be obtained from
Context.
* artifacts wasn't used anywhere
=> Remove bloated api functions in Super_context

src/dune/dune_env.ml, src/dune/dune_env.mli, src/dune/env_node.ml, src/dune/env_node.mli, src/dune/expander.ml, src/dune/expander.mli, src/dune/foreign.ml, src/dune/foreign.mli, src/dune/foreign_language.ml, src/dune/foreign_language.mli, src/dune/foreign_rules.ml, src/dune/foreign_sources.ml, src/dune/lib_archives.ml, src/dune/lib_file_deps.ml, src/dune/super_context.ml, src/dune/super_context.mli, src/dune/utils.ml
In the same vein as my other recent PRs.
This started as a refactoring of "definitely backend" modules that used `Lib_name`, but I noticed that `Foreign` was also mostly things that don't need to be in the engine.
I'm generally less satisfied with this one (see my rant in `foreign_langage.mli`), but I think it's a step in the right direction -- `foreign` feels like a front-end module, so we should move towards moving all of that infrastructure into the frontend.
Would appreciate other thoughts.
Signed-off-by: Cameron Wong <cwong@janestreet.com>
=> Refactor [Foreign]

dune-configurator.opam, dune-project, otherlibs/configurator/src/dune
This is the first in the unvendoring of the dune repository. We will
only stick to vendored dependencies for the dune executable.
This should not cause any problems because csexp is stable and versioned.
cc @avsm just to make sure he's aware.
=> Use external csexp in configurator

CHANGES.md, src/dune/coq_module.ml, src/dune/coq_module.mli, src/dune/coq_rules.ml, test/blackbox-tests/test-cases/coq/base-unsound.t/run.t, test/blackbox-tests/test-cases/coq/base.t/run.t, test/blackbox-tests/test-cases/coq/compose-plugin.t/run.t, test/blackbox-tests/test-cases/coq/compose-simple.t/run.t, test/blackbox-tests/test-cases/coq/compose-sub-theory.t/run.t, test/blackbox-tests/test-cases/coq/ml-lib.t/run.t, test/blackbox-tests/test-cases/coq/rec-module.t/run.t
Fix #3437
@gares @ejgallego should `.aux` files be installed as well?
=> [coq] Add .aux & .glob files as targets

Makefile
This breaks out the testing deps install command into its
own script, so that this can be used by both travis and
the dev-deps make target.
This is aimed at resolving the recurring problem of new devs (or devs setting up a new environment) having to manually track down test dependencies. This was discussed with @lubegasimon and @rgrinberg several weeks back.
=> Improve robustness of dev-deps make target

CHANGES.md, src/dune_engine/print_diff.ml, src/stdune/fpath.ml, src/stdune/fpath.mli, src/stdune/path.ml, src/stdune/path.mli
git diff does not like symlink arguments.
Fixes #3740
=> Resolve symlinks before running git diff

CHANGES.md, src/dune_engine/action_exec.ml, src/dune_engine/dtemp.ml, src/dune_engine/dtemp.mli, src/dune_engine/process.ml, src/stdune/env.mli, src/stdune/path.ml, src/stdune/path.mli, src/stdune/temp.ml, src/stdune/temp.mli, test/expect-tests/stdune/temp_tests.ml
Use a temp dir that's inside the build directory. This makes it easier
to debug builds.
=> Implement #3432

test/blackbox-tests/test-cases/lib.t/run.t
The setup is as follows:
* We 2 packages in a single project
* 1 package uses %{lib-private} to refer to the artifacts of the other
package
* This works in development builds
* It fails in production because -p (and --only-packages) hide the
definition of the 1st package
@snowleopard this is the bug I had in mind in slack.
=> Reproduce %{lib-private} bug

test/blackbox-tests/test-cases/overlapping-deps.t
This is an ancient feature introduced in
https://github.com/ocaml/dune/pull/587
But no test cases were added. This PR addresses this.
=> Add test case for overlapping dependencies

src/dune_rules/dune_file.ml, src/dune_rules/expander.ml, src/dune_rules/lib_info.ml, src/dune_rules/lib_info.mli, src/stdune/string.ml, src/stdune/string.mli
Comparing by project name is unnecessary and a little fragile once we
allow duplicate project names in the same workspace.
=> Avoid project name comparison

src/dune_engine/include_stanza.ml, src/dune_engine/include_stanza.mli, src/dune_engine/sub_dirs.ml, src/dune_rules/coq_stanza.ml, src/dune_rules/dune_file.ml, src/dune_rules/stanza_common.ml, src/dune_rules/stanza_common.mli
This allows to move most of the module to dune_rules. Since only the
include stanza is necessary in dune_engine.
=> Split Stanza_common from include stanza

doc/jsoo.rst
Added note that preprocess field is required for js_of_ocaml syntax extensions. This is not obvious when coming directly from js_of_ocaml page.
=> Explicitly mention usage of js_of_ocaml-ppx

src/dune_engine/build_system.mli
This function isn't used outside of Build_system. We can remove it from
the interface.
=> Make Build_system.get_vcs private

src/dune_rules/ordered_set_lang.ml, src/dune_rules/ordered_set_lang.mli, src/dune_rules/ordered_set_lang_intf.ml
Ordered_set_lang can live inside the rules library
=> Move OSL from engine

test/blackbox-tests/test-cases/enabled_if/eif-context_name.t/run.t
Without EOF, Bash yields `sh: warning: here-document at line 1 delimited by end-of-file (wanted 'EOF')`, causing the test to fail.
=> Fix cram tests with bash 5.0.18.

src/dune_engine/build.ml, src/dune_engine/build.mli, src/dune_engine/build_system.ml, src/dune_engine/lib_deps_info.ml, src/dune_engine/lib_deps_info.mli, src/dune_rules/buildable_rules.ml, src/dune_rules/expander.ml, src/dune_rules/preprocessing.ml
Allow library dependencies to be collected via an extensible type and
the `Record` constructor. This inverts the dependency between `Build` and
`Lib_deps_info`.
This isn't enough to get rid of `Lib_name` from the core, but it's a start. The
next step would be to figure out to move it out of `Dep_path` as well.
=> Remove libraries from build core

bin/external_lib_deps.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli
Collecting library dependencies is done just as easily in the caller.
This functionality isn't general purpose so it shouldn't live in the
engine.
=> Move all lib deps from engine

src/dune_rules/lib.ml, src/dune_rules/lib.mli, src/dune_rules/scope.ml
Before this PR constructing a DB from library stanzas was split between
`Scope` and `DB`. This PR just moves it all to one place: `Scope`.  The
end result is that there's a single place to modify the implementation
details of this feature and less interfaces are exported.
=> Move db construction from stanza to scope

src/dune_rules/dune_file.ml, src/dune_rules/dune_file.mli, src/dune_rules/inline_tests.ml, src/dune_rules/install_rules.ml, src/dune_rules/lib_rules.ml, src/dune_rules/odoc.ml, src/dune_rules/scope.ml, src/dune_rules/super_context.ml
Unrelated changes from #3655 that make it easier to review the other PR.
* We change `lib.public` to `visibility`. This is consistent with how we handle
private/public everywhere else.
* `lib_entries_by_package` is moved to own function
=> Cleanups from #3655

src/dune_rules/dune_file.ml, src/dune_rules/dune_file.mli, src/dune_rules/gen_rules.ml, src/dune_rules/scope.ml
Previously, we'd add redirect for private libraries only if the
underlying libraries were filtered out. It's simpler, to just always add
a redirect and rmeove the additional logic for redirects when
constructing a library database.
=> Improve library redirect behavior

src/dune_lang/decoder.ml, src/dune_lang/decoder.mli, src/dune_rules/bindings.ml
* Make `<|>` work on arbitrary parsers.
* Add `either`.  Like the current <|>, but it lets us know which parser
completed. Simplifies an instance where we do the separation ourselves.
=> Add Decoder.either & generalize <|>

src/dune_rules/lib.ml, src/dune_rules/lib.mli, src/dune_rules/utop.ml
Previously, we'd use Lib.DB.find_even_when_hidden and then reverse
engineer whether the library is hidden. Now, we just ask the DB to
distinguish between a library that doesn't exist and a library that is
hidden.
=> Simplify filtering hidden libs in utop rules

src/dune_rules/exe_rules.ml
* Split construction of o_files, linkages, programs into functions
* Move Re-order let bindings closer to where they are used and in a
tighter scope
* ~~Cleanup a strange looking conditional~~ (nojb explained why this is necessary).
=> Simplify Exe_rules

.ocamlformat, Makefile, src/catapult/catapult.ml, src/dune_engine/build_system.ml, src/dune_engine/dune_project.ml, src/dune_rules/coq_sources.ml, src/dune_rules/dep_conf_eval.ml, src/dune_rules/foreign_rules.ml, src/dune_rules/install_rules.ml, src/dune_rules/super_context.ml, src/dune_rules/utop.ml, src/dune_rules/visibility.ml, src/memo/implicit_output.ml, src/stdune/type_eq.ml
Hi, this is what the project would look like after being reformated with the current version (candidate) of ocamlformat 0.15.0.
**Please do not merge until ocamlformat.0.15.0 is available with opam.**
The main changes are due to the improved inconsistency of option `indicate-multiline-delimiters`, a lot of spaces where missing before closing parentheses in the previous versions.
Please let me know if you see any regressions that I may have missed.
=> Upgrade to ocamlformat 0.15.0

Makefile, test/blackbox-tests/test-cases/jsoo/simple.t/bin/dune, test/blackbox-tests/test-cases/jsoo/simple.t/bin/runtime.js, test/blackbox-tests/test-cases/jsoo/simple.t/bin/technologic.ml, test/blackbox-tests/test-cases/jsoo/simple.t/lib/dune, test/blackbox-tests/test-cases/jsoo/simple.t/lib/x.ml, test/blackbox-tests/test-cases/jsoo/simple.t/run.t
This puts an additional constraint on ppxlib and doesn't increase our
testing at all.
=> Remove js_of_ocaml-ppx from tests

doc/dune-files.rst, doc/dune-libs.rst, doc/quick-start.rst
Update the instructions to use dune-configurator (now a separate package).
Signed-off-by: Christophe Troestler <Christophe.Troestler@umons.ac.be>
=> Update the instructions to use dune-configurator

src/dune_rules/compilation_context.ml, src/dune_rules/compilation_context.mli, src/dune_rules/menhir.ml, src/dune_rules/module_compilation.ml
Small optimization and less possibility for confusing for editor tools.
=> [menhir] Disable bin_annot for mock modules

src/dune_rules/dep_rules.ml, src/dune_rules/install_rules.ml, src/dune_rules/lib.ml, src/dune_rules/module_compilation.ml, src/dune_rules/obj_dir.ml, src/dune_rules/obj_dir.mli, src/dune_rules/virtual_rules.ml
The family of unsafe functions would return a file path even if it's not
supposed to exist. It was the responsibility of the caller to make sure
that these functions were called correctly. Instead, these functions now
make sure they are called with correct module/visibility/cm_kind
combinations.
=> Make Obj_dir functions a little safer

CHANGES.md, doc/dune-files.rst, src/dune_engine/lib_name.ml, src/dune_engine/lib_name.mli, src/dune_rules/compilation_context.ml, src/dune_rules/dune_file.ml, src/dune_rules/dune_file.mli, src/dune_rules/dune_package.ml, src/dune_rules/findlib/findlib.ml, src/dune_rules/gen_meta.ml, src/dune_rules/gen_rules.ml, src/dune_rules/install_rules.ml, src/dune_rules/lib.ml, src/dune_rules/lib.mli, src/dune_rules/lib_info.ml, src/dune_rules/lib_info.mli, src/dune_rules/link_time_code_gen.ml, src/dune_rules/obj_dir.ml, src/dune_rules/obj_dir.mli, src/dune_rules/odoc.ml, src/dune_rules/preprocessing.ml, src/dune_rules/scope.ml, src/dune_rules/scope.mli, src/dune_rules/super_context.ml, test/blackbox-tests/test-cases/private-modules.t/run.t, test/blackbox-tests/test-cases/private-package-lib.t/run.t
This PR implements the `(package ..)` field on libraries that lack a public name. For example:
```
(library
(name foo)
(package bar))
```
This makes `foo` available to the public libraries in `bar` but not to public libraries in any other package. `foo` will be installed as `bar.__private__.foo`. The name mangling encourages users to avoid using this library name directly.
I have a some questions about the implementation to @emillon and @jeremiedimino:
Initially, we agreed that the cmi's of such libraries will not be installed. I'm not entirely sure this is workable however. Consider this setup with 2 libraries and an executable in a single project
```
(library
(name foo)
(package bar))
(library
(libraries foo)
(public_name bar))
(executable
(name baz)
(libraries bar)
(package baz))
``` …
=> Private libraries attached to a package

CHANGES.md, src/stdune/bin.ml
Issue detected in https://github.com/aantron/luv/pull/72
The `gmake` binary does not exist on Cygwin and caused issues in `luv` when trying to use `%{make}` to fix the BSD support.
This PR fixes the issue by simply looking for `gmake` on unix systems only. This is also closer to what opam does: https://github.com/ocaml/opam/blob/a96a576a1be44b07128cef4554108d7319d0728f/src/state/opamStateConfig.ml#L44
=> Fix %{make} on Windows

doc/concepts.rst, src/dune_engine/action_exec.ml, src/dune_engine/dtemp.mli, src/dune_engine/process.mli, src/dune_rules/action_to_sh.ml, test/blackbox-tests/test-cases/pipe-actions.t/append_to_line.ml, test/blackbox-tests/test-cases/pipe-actions.t/echo_outputs.ml, test/blackbox-tests/test-cases/pipe-actions.t/run.t
The execution of the outputs of the first command was not duplicated so it could fail in some cases. The first commit shows such error but one for `pipe-stderr` can be also produced if both outputs are sent to one file. The second commits fixes the problem, but when we need to duplicate a `Process.Io` is not clear to me.
However the semantic of `pipe-stderr` and in some way `pipe-outputs` seems  strange. Usually piping is used for filtering from `stdin` to `stdout` (`grep`, `sed`, ... work on those not `stderr`). `stderr` is used for errors in the pipe, but are not also filtered by the others. For doing `pipe-outputs` in shell, usually one write `cmd |& cmd1 | cmd2 | cmd3` not `cmd |& cmd1 |& cmd2 |& cmd3`. If `pipe-stderr` filter only `stderr` not `stdout`, I believe the result of the …
=> Fix pipe action

src/dune_rules/lib.ml
Whenever we know the library is defined in the context, we can look up
its project directly. There's no need to reverse engineer it from the
packages, as this would be incorrect for vendored packages in the same
workspace. For example:
```
vendor/
foo/
foo.opam
foo.opam
```
The current code would wrongly determine that libraries in either foo
packages are different in the same project.
=> Fix project lookup for libraries

CHANGES.md, bin/subst.ml
In particular I wanted this as to have `dune subst` interpret
`--debug-backtraces` in the context of #3219
I'm not sure if that's the way to go, so please consider this PR as a RFC
=> [dune subst] Interpret common command line flags.

bin/import.ml, bin/install_uninstall.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/dune_project.ml, src/dune_engine/package.ml, src/dune_engine/package.mli, src/dune_rules/coq_rules.ml, src/dune_rules/dune_file.ml, src/dune_rules/gen_meta.ml, src/dune_rules/gen_rules.ml, src/dune_rules/generate_module_rules.ml, src/dune_rules/install_rules.ml, src/dune_rules/install_rules.mli, src/dune_rules/lib.ml, src/dune_rules/lib_info.ml, src/dune_rules/link_time_code_gen.ml, src/dune_rules/main.ml, src/dune_rules/odoc.ml, src/dune_rules/opam_create.ml, src/dune_rules/packages.ml, src/dune_rules/stanza_common.ml, src/dune_rules/super_context.ml
We'd like to lift the restriction on packages with the same name
co-existing in the same workspace. The first step is to avoid this
reliance in `Build_system`. In `Build_system`, we rely on the user
creating a path to package map when generating the rules. This PR makes
it so that we don't use on package names in this map.
We use a set of packages where uniqueness is determined by the package
name + the package path. This is guaranteed to be unique.
=> do not rely on package names in Build_system

doc/dune-files.rst
=> doc/dune-files.rst: typo

src/dune_engine/scheduler.ml
select had no arguments, so it's the same as a sleep.
=> Replace Unix.select with Unix.sleepf

src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rules/gen_rules.ml, src/dune_rules/main.ml, src/dune_rules/super_context.ml, src/dune_rules/super_context.mli
If a function has an optional argument, it should also have a positional one.
Somehow pre 4.12, these cases were not detected.
=> Fix optional argument warnings for 4.12

CHANGES.md, doc/dune-files.rst, src/dune_rules/coq_rules.ml
Fixes #3924 , and a bug where `:standard` was not properly set in
theory flags, as they should be inherited from the ones set in the
profile; thanks Rudi Gringerb.
=> [coq] Add "-q" to default flags.

CHANGES.md, Makefile, doc/dune-files.rst, src/dune_rules/coq_lib.ml, src/dune_rules/coq_lib_name.mli, src/dune_rules/coq_mode.ml, src/dune_rules/coq_mode.mli, src/dune_rules/coq_module.ml, src/dune_rules/coq_module.mli, src/dune_rules/coq_rules.ml, src/dune_rules/coq_rules.mli, src/dune_rules/coq_sources.ml, src/dune_rules/coq_sources.mli, src/dune_rules/coq_stanza.ml, src/dune_rules/coq_stanza.mli, src/dune_rules/profile.mli, test/blackbox-tests/test-cases/coq/github3624.t/run.t, test/blackbox-tests/test-cases/coq/native-compose.t/bar/bar.v, test/blackbox-tests/test-cases/coq/native-compose.t/bar/dune, test/blackbox-tests/test-cases/coq/native-compose.t/dune, test/blackbox-tests/test-cases/coq/native-compose.t/dune-project, test/blackbox-tests/test-cases/coq/native-compose.t/foo/dune, test/blackbox-tests/test-cases/coq/native-compose.t/foo/foo.v, test/blackbox-tests/test-cases/coq/native-compose.t/run.t, test/blackbox-tests/test-cases/coq/native-single.t/bar.v, test/blackbox-tests/test-cases/coq/native-single.t/dune, test/blackbox-tests/test-cases/coq/native-single.t/dune-project, test/blackbox-tests/test-cases/coq/native-single.t/foo.v, test/blackbox-tests/test-cases/coq/native-single.t/run.t
We add a `(mode ...)` field to the `(coq.theory ...)` stanza that when
set to `native` will have the Coq compiler to generate and install
"native" objects, that is to say, `.cmxs` libraries containing an
ML-level version of the corresponding Coq module.
As of today, Coq itself does call the `ocamlfind ocaml` to compile the
object files, this restriction may be lifted in the future however it
is not easy as tactics do have access to "Just-In-Time" native
compilation too.
The patch itself should have been straightforward except for a big
problem due to the way Coq outputs native targets and the limitations
of Dune.
By default, `coqc -native-compute on` will generate the OCaml-level
objects files under `.coq-native/`, and the regular `.vo` object in
the build dir. This scheme doesn't work …
=> [coq] Add support for native-mode compilation.

bin/arg.ml, bin/arg.mli, bin/describe.ml, bin/format_dune_file.ml, bin/printenv.ml, src/dune_engine/action_ast.ml, src/dune_engine/action_exec.ml, src/dune_engine/action_intf.ml, src/dune_engine/action_mapper.ml, src/dune_engine/format_dune_lang.ml, src/dune_engine/format_dune_lang.mli, src/dune_rules/action_to_sh.ml, src/dune_rules/action_unexpanded.ml, src/dune_rules/dune_init.ml, src/dune_rules/format_rules.ml, src/dune_rules/format_rules.mli, src/dune_rules/gen_rules.ml, src/dune_rules/upgrader.ml
See https://github.com/ocaml/dune/pull/3928#issuecomment-727015097
This PR adds versioning for the auto-formatting style for the `dune` language.
- The `format-dune-file` subcommand now carries an optional flag `--dune-version` to specify the version wanted (note that this command is not used by `dune` itself, since the formatting is done in-core since #3536)
- `dune describe`, `dune printenv` and `dune init` use the latest version, since it seemed frivolous to add a flag to set the style version.
=> Add versioning for dune auto-formatting style

test/blackbox-tests/test-cases/coq/dune
This prevent macos devs to run the coq-native tests.
These tests should be enabled again when Coq will support native mode in macos.
I also added an alias to easily run all tests in the coq folder `./dune.exe build @all-coq-tests`
=> Disable coq-native tests (and add alias for all coq tests)

src/dune_engine/scheduler.ml
This reverts commit 179d2d1383322416d87cc2812a8d7dadbff8314f and should fix the tests (and thus the CI) for macos.
This rollback or a  more cleaver mitigation should be merged before releasing 2.8.0.
=> Fix OSX issue by reverting "[scheduler] Remove running count"

src/dune_rules/context.ml, src/dune_rules/gen_rules.ml
For normal contexts we were using a map, while for super contexts, a
hash table. This makes super contexts use a map as well.
=> Make context generation uniform

CHANGES.md, dune-project, dune.opam
Dune 2.8.0 will stop writing `.merlin` files.
To ensure the smoothest transition possible we need to conflict with versions of Merlin and OCaml-LSP that do not support the new "external configuration readers", that is: `merlin < 3.4.0` and `ocaml-lsp-server < 1.3.0`.
=> Add conflict with OCamlLSP < 2.3.0

Makefile
Upstream opam has split Coq's native support to a config-only package.
This unfortunately means that people need to run `opam update`.
=> [ci] [coq] [opam] Track opam upstream changes in Coq packaging.

src/memo/memo.ml
Only the exec and exec_dep_node functions are public in this module
=> Add module signatures to Exec_{sync,async}

src/dune_rules/merlin_ident.ml, test/blackbox-tests/test-cases/merlin/merlin-tests.t/exes/dune, test/blackbox-tests/test-cases/merlin/merlin-tests.t/run.t
Per stanza Merlin files were named by concatenating executables names. This can cause issues with large `executables` stanzas.
Now the filename shows the name of the first executable and a hash of the rest.
@nojb would be great if you could test that PR on your codebase.
=> Fix long merlin idents

src/dune_rules/lib.ml, src/dune_rules/lib.mli
Delay errors in loading subsystem until we actually need to write its
information.
=> Sub_system error handling

test/blackbox-tests/test-cases/dir-target-dep.t/run.t
file was overlapping with another directory, rather than a file
----
#
=> Fix directory target test

src/fiber/fiber.ml, src/fiber/fiber.mli, src/memo/memo.ml, test/expect-tests/fiber/fiber_tests.ml
Re-raise all exceptions to the current handler. This function can be
more efficient in the future.
=> [fiber] add reraise_all

src/dune_engine/build.ml, src/dune_engine/build.mli, src/dune_engine/build_system.ml, src/dune_rules/merlin.ml
This MR merge additions to `Build.t` from #3900 @bobot and #3131 by @rgrinberg . The name, as proposed by  @jeremiedimino during a meeting, make sure that we ponder each uses.
```
val do_not_use_stage_fiber: 'a Fiber.t -> 'a t
val do_not_use_stage_dyn_fiber: 'a Fiber.t t -> 'a t
val do_not_use_stage_build: 'a t t -> 'a t
```
The goal is to make them available and to discuss only when we are going to use them if their use is justified.
=> Add non applicative case in `Build.t` for staging

bin/caching.ml, doc/dev/cache.md, src/cache/local.ml, src/cache/local.mli, src/dune_engine/build_system.ml, src/dune_engine/cached_digest.ml, src/dune_engine/dune_project.ml, src/dune_engine/scheduler.ml, src/dune_rules/findlib/findlib.ml, src/dune_rules/lib.ml, src/memo/memo.ml, src/stdune/digest.ml, test/blackbox-tests/test-cases/deprecated-fields/d-allow-approx-merlin.t, test/blackbox-tests/test-cases/dune-cache/missing-data.t/run.t, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
This PR does a few changes to the Dune build cache: 
* It brings Dune in sync with Jenga by computing file digests in the same way.
* It implements a unified trimming for old (`v3`) and new (`v4`) cache entries, so that the cache is trimmed correctly even if the user switches between different versions of Dune (thus fixing #3542).
* Finally, we switch to prioritising the trimming of entries by *the last change time* `ctime` instead of the *last modification time* `mtime`, also for consistency with Jenga.
TODO:
=> Switch to cache v4

src/dune_rules/expander.ml
All of these are already checks are already done in
[expand_receord_generic], which is called in catch all clause.
=> Remove pointless [assert false] in [Expander]

src/dune_engine/build_system.ml
This allows for the locks to be cleaned up when the build system is re-created.
=> Move locks to build_system

src/dune_engine/build_system.ml
If we know the rule digest is different, then there's no reason to
calculate the target digest.
(Apologies if I'm missing something obvious here)
=> Skip calculating target digests when possible

otherlibs/build-info/test/run.t, test/blackbox-tests/test-cases/dune-project-meta/main.t/run.t, test/blackbox-tests/test-cases/meta-template-version-bug.t, test/blackbox-tests/test-cases/subst.t/run.t, test/expect-tests/vcs_tests.ml
Newer versions of git complain that the default branch name is subject
to change and we shouldn't rely on it. This PR sets it explicitly for
all of our tests.
=> Future proof git init in tests

bin/common.ml
The current inline documentations don't tell the user what values can be supplied to `--terminal-persistence`, requiring them to go digging in other docs (or the source). I though we could smooth that out. :)
=> Add inline docs for --terminal-persistence modes

bin/common.ml, bin/common.mli, bin/subst.ml
We explicitly read --debug-backtraces instead of relying on
`Common.term`. `Common.term` ended up bringing an entire kitchen sink of
stuff we don't want. For instance, root directory discovery.
=> Fix dune subst not to initialize root

src/dune_engine/build_system.ml
`load_dir_fold` is a bit ugly, but it's used to optimize the code paths that seem to allocate the most in clean builds. So it seems to be worth it.
I've also discovered that our use of set operations in `build.ml` can also be quite slow if the sets grow large. Perhaps it's worth switching the accumulation to lists, and only then converting to sets.
=> Deforest eval_pred and file_exists

CHANGES.md, src/dune_engine/dune_project.ml, src/dune_engine/dune_project.mli, src/dune_rules/watermarks.ml, test/blackbox-tests/test-cases/subst/from-project-file.t, test/blackbox-tests/test-cases/subst/project-name-restriction.t, test/blackbox-tests/test-cases/subst/unicode.t, test/blackbox-tests/test-cases/subst/with-opam-file.t
This PR re-organizes the `dune subst` tests, and adds a test case for what I
think is strange behavior. Why should `dune subst` impose additional
restrictions that dune itself doesn't check for?
=> [dune subst] Improve dune-project (name ..) behavior

src/dune_engine/dune_project.ml, src/dune_engine/dune_project.mli, src/dune_rules/cxx_flags.ml, src/dune_rules/cxx_flags.mli, src/dune_rules/cxx_rules.ml, src/dune_rules/cxx_rules.mli, src/dune_rules/env_node.ml, src/dune_rules/env_node.mli, src/dune_rules/foreign_rules.ml, src/dune_rules/gen_rules.ml, src/dune_rules/super_context.ml, test/blackbox-tests/test-cases/cxx-flags.t/baz.cpp, test/blackbox-tests/test-cases/cxx-flags.t/dune, test/blackbox-tests/test-cases/cxx-flags.t/main.ml, test/blackbox-tests/test-cases/cxx-flags.t/quad.ml, test/blackbox-tests/test-cases/cxx-flags.t/run.t
This PR is an attempt to answer #3528.
It adds a new module with a small "database" of C++ flags that are necessary to the use of some of the most common C compiler to build C++ code.
Given the actual context and whether C or C++ code is being built, this module provide the set of necessary flags that should be added to the compiler command line : from the database mentioned above for C++ and from the config `ocamlc_cflags` and `ocamlc_cppflags` for C. For convenience it also add the FDO flags tot he list and also returns the output args that should be used for the specified compiler.
The main issue is that, because these C++ flags where not added by Dune before, users probably added them themselves and they will be duplicated in the command line. I am not sure whether this would break …
=> Add necessary C++ flags for most common compilers

src/dune_engine/hooks.ml, src/dune_engine/hooks.mli
When one hook fails, it prevents running all other hooks. This is wrong
because other hooks are still required to write various database files.
This PR makes sure that we try running all hooks even if one fails.
=> Run all hooks - even on failure

src/memo/memo.ml, src/stdune/exn_with_backtrace.ml, src/stdune/exn_with_backtrace.mli, test/blackbox-tests/test-cases/all-promotions.t/run.t, test/blackbox-tests/test-cases/formatting.t/run.t, test/expect-tests/memo/memoize_tests.ml
This tries to implement @snowleopard's idea of saving the exceptions in a set
=> Attempt to fix #4097

bin/common.ml, bin/common.mli, src/dune_engine/clflags.ml, src/dune_engine/clflags.mli, src/dune_rules/cram_rules.ml, src/dune_rules/cram_stanza.ml, src/dune_rules/cram_stanza.mli, src/dune_rules/dune_file.ml, src/dune_rules/stanza_common.ml, src/dune_rules/stanza_common.mli, test/blackbox-tests/test-cases/cram/package.t
the [package] field will attach the tests of this cram stanza to the
specified package
Fixes #3792
=> Allow [package] on cram stanza

src/dune_rules/lib.ml, src/dune_rules/lib.mli, src/dune_rules/merlin.ml
Should give us another nice speed-up. Even faster would be not to iterate
through the modules and just return all the dirs considered in Dir_contents.
=> Generate src dirs once per library

test/blackbox-tests/test-cases/c-flags.t/run.t
+  warning: here-document at line 1 delimited by end-of-file (wanted `EOF')
Signed-off-by: Antonin Décimo <antonin@tarides.com>
=> Fix warning of missing EOF in c-flags.t

test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
This test seems to be broken since a recent change on the github side. Let's disable them until we have a fix for them.
=> Comment out broken trim tests

test/blackbox-tests/test-cases/merlin/allow_approximate_merlin_warn.t/run.t
=> Fix non-portable use of 'echo' in the cram tests

bin/import.ml, src/dune_engine/config.ml, src/dune_engine/config.mli, src/dune_engine/process.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_rules/main.ml, src/dune_rules/main.mli
This simplifies a bit the code as we don't need to call `Main.set_concurrency` anymore.
The old code was using `Process.run`, which we can't use in `scheduler.ml` without creating a dependency cycle between `Process` and `Scheduler`. I hesitated between adding a forward declaration and using `Unix.create_process` directly. Since the old detection was already done sequentially and the code is simple overall, I opted for the latter.
=> Move CPU counting to scheduler.ml

bin/install_uninstall.ml, src/dune_rules/context.ml, src/dune_rules/context.mli
It is only used once in the install command, no need to store it in the context.
/cc @bobot
=> Remove field install_prefix from Context.t

doc/concepts.rst, otherlibs/site/test/run.t, src/dune_rules/expander.ml
I'm not sure how to add this feature to the blackbox-tests but it works with:
```
$ cat dune
(rule
(target test.target)
(action (with-stdout-to %{target} (run echo "%{version:ppxlib}"))))
$ dune build
$ cat _build/default/test.target
0.20.0
```
=> Add support for %{version:installed-pkg}

bin/build_cmd.ml, bin/exec.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli
Not sure how we omitted this, but we do this after `dune runtest` or `dune exec`
=> Run end of build hook after doing `$ dune build`

CHANGES.md, Makefile, doc/concepts.rst
See https://github.com/ocaml/dune/issues/1506 for context: this feature is currently completely undocumented.
Note: the Variables documentation is a bit of a pain to read, in particular because variables are not listed in alphabetic order so it is difficult to tell if a variable is documented without grepping. (It could also be split between "simple" variables `%{var}` and the parametrized `%{var:arg}` form, or some other forms of categorization.)
=> Document `%{env:<var>=<default>}`

test/blackbox-tests/test-cases/merlin/merlin-tests.t/run.t
`grep -q` closes the input once it finds a match which causes `dune ocaml-merlin` to fail with an error if it isn't quick enough to write the output completely. The fix removes `-q` and simply redirects `grep`'s output to `/dev/null`.
=> Fix reproducibility of a merlin test

src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
This test seems to reveal a bug in the Memo's cutoff logic.
=> Add a Memo test with a non-uniformly cut diamond

CHANGES.md, doc/dune-files.rst, src/dune_rules/coq_mode.ml, src/dune_rules/coq_mode.mli, src/dune_rules/coq_module.ml, src/dune_rules/coq_rules.ml, src/dune_rules/coq_stanza.ml
Fixes #4142.
Changes introduced in #3210 meant that Dune became incompatible with
Coq < 8.10 ; this was not intentional and it turns out we had Coq Dune
users in Coq 8.9 / 8.8.
Indeed `(using coq 0.3)` does require Coq >= 8.10, but when `(using
coq 0.2)` is set, we should remain compatible with Coq 8.7-8.9.
=> [coq] Restore compatibility with Coq < 8.10 for coq-lang < 0.3

CHANGES.md, src/dune_rules/findlib/meta.ml
As per https://github.com/ocaml/ocamlfind/pull/10
Signed-off-by: Louis Gesbert <louis.gesbert@ocamlpro.com>
=> Add META rule for 'compiler-libs.native-toplevel' (ocamltoplevel.cmxa)

test/blackbox-tests/test-cases/merlin/github4125.t/dune-workspace, test/blackbox-tests/test-cases/merlin/github4125.t/run.t
CI is broken due to a test using a switch named `default` to test cross-compilation settings.
I used `opam switch show` to trick the test in always using an existing switch: the current one.
=> Fix the CI

CHANGES.md, src/dune_engine/cached_digest.ml, src/stdune/path.ml, src/stdune/path.mli
Fix https://github.com/ocaml/dune/issues/4195
In sandbox, symlink requires rw permissions on the directory of the sources to create a symlink. Copy does not require.
To test, you can build this branch, and try to install `bls12-381-unix` or `bls12-381-js`.
In addition to the comments in #4195, this issue has not been detected by the CI of bls12-381 (installing via opam is verified here: https://gitlab.com/dannywillems/ocaml-bls12-381/-/blob/master/.gitlab-ci.yml#L136) or by the CI of the public opam-repository (see https://github.com/ocaml/opam-repository/pull/18112) because I think sandbox is not used.
=> Virtual_rules: use copy instead of symlink when copying signatures

CHANGES.md, src/dune_rules/exe_rules.ml, src/dune_rules/lib_rules.ml, src/dune_rules/merlin.ml, src/dune_rules/merlin.mli, test/blackbox-tests/test-cases/github1946.t/run.t, test/blackbox-tests/test-cases/github759.t/run.t, test/blackbox-tests/test-cases/merlin/github4125.t/run.t, test/blackbox-tests/test-cases/merlin/merlin-from-subdir.t/run.t, test/blackbox-tests/test-cases/merlin/merlin-tests.t/run.t, test/blackbox-tests/test-cases/merlin/per-module-pp.t/run.t, test/blackbox-tests/test-cases/merlin/server.t/run.t, test/blackbox-tests/test-cases/merlin/src-dirs-of-deps.t/run.t, test/blackbox-tests/test-cases/merlin/symlinks.t/run.t, test/blackbox-tests/test-cases/merlin/unit-names-merlin-gh1233.t/run.t
Make it so that `dune` communicates the standard library directory to `merlin`. This makes it possible to use `merlin` with an OCaml compiler other than the one it was compiled with.
Fixes #4188
=> merlin: communicate STDLIB directive

bin/dune_init.ml, src/dune_engine/mode.ml, src/dune_engine/mode.mli, src/dune_rules/check_rules.ml, src/dune_rules/context.ml, src/dune_rules/cram_exec.ml, src/dune_rules/exe.ml, src/dune_rules/exe.mli, src/dune_rules/exe_rules.ml, src/dune_rules/findlib/meta.ml, src/dune_rules/lib.ml, src/dune_rules/link_mode.ml, src/dune_rules/link_mode.mli, src/dune_rules/menhir.ml, src/dune_rules/module_name.ml, src/dune_rules/module_name.mli, src/dune_rules/workspace.ml, src/dune_rules/workspace.mli, src/stdune/list.ml, src/stdune/list.mli
Get rid of implicit polymorphic equality in List.mem and align the type with Base.
In Ocaml stdlib and in dune before this PR, the type is
```
val mem : 'a -> set:'a list -> bool 
```
In base and in dune after this PR, the type is:
```
val mem : 'a list -> 'a -> equal:('a -> 'a -> bool) -> bool
```
One could imagine a middle-ground where the `set` argument is still named, but I didn't want to introduce a third version.
=> Get rid of implicit polymorphic equality in List.mem

CHANGES.md, doc/instrumentation.rst, src/dune_rules/cinaps.ml, src/dune_rules/dune_file.ml, src/dune_rules/exe_rules.ml, src/dune_rules/lib_rules.ml, src/dune_rules/preprocess.ml, src/dune_rules/preprocess.mli, src/dune_rules/preprocessing.ml, src/dune_rules/preprocessing.mli, src/dune_rules/toplevel.ml, src/dune_rules/utop.ml, test/blackbox-tests/test-cases/instrumentation.t/ppx/hello_ppx.ml, test/blackbox-tests/test-cases/instrumentation.t/run.t
Fixes #3983 
@aantron if you could give this one a spin that would be great. The syntax is as discussed in #3983.
=> Allow to declare (instrumentation) dependencies

CHANGES.md, src/stdune/path.ml
Progresses #4167 prior to OCaml 4.13.
The guard must test for the file's presence, as you can't differentiate `EACCES` and `ENOENT` without ocaml/ocaml#10220.
=> Workaround OCaml PR#8857 in Path.touch

src/memo/memo.ml, test/expect-tests/memo/memoize_tests.ml
This fixes the bug revealed in #4240.
Here is how the bug is happening.
Consider the following chain of dependencies: `A -> B -> C ..... -> Y -> Z -> C`.
* When we enter the node `C` for the second time via the edge `Z -> C`, we create a cycle, which causes `add_dep_from_caller` to raise the `Cycle_error` exception, which propagates to the caller.
* At this point, the caller `Z` was in the `dep_changed` function. The exception is uncaught and is propagated to the `do_validate` function, where it's also uncaught, which in particular means that the corresponding `ivar` will never be filled. Note that `do_validate` is called after registering the edge `Y -> Z`, so `Y`'s dependencies are updated correctly.
* The uncaught exception propagates further to the caller of `Z`, which is `Y`. Here …
=> Fix a cycle detection bug and update documentation

src/memo/memo.ml
It used to be possible for a computation to finish with a cycle error and remain in the `Considering` state forever, becoming a "zombie" computation. To distinguish between "current" and "zombie" computations, we stored the `run` in which the computation had started. In this way, before subscribing to an `Ivar.t` from the `completion`, we could check if it corresponded to the current run, and if not, start a new computation.
With better error-handling introduced in #4015, we believe such zombie computations are no longer possible. In this PR, we make the function `currently_considering` throw a `Code_error` if it encounters a zombie.
Once we have convinced ourselves that there are no zombies out there, we can remove the `run` from the `Considering` state.
=> Assert the non-existence of zombies

src/fiber/fiber.ml, test/blackbox-tests/test-cases/rpc.t
Allow output streams to be closed more than once. Rpc relies on this
somewhere, and it seems harmless to allow.
=> Fiber.Stream.Out.t double close

bin/common.ml, bin/common.mli, bin/init.ml, bin/main.ml, test/blackbox-tests/test-cases/dune-init.t/run.t, test/blackbox-tests/test-cases/github3046.t/run.t
Closes #3602
Provides more detailed and better structured information in the manpage for `dune init`.
=> Improve the CLI help for the init subcommand

doc/usage.rst, src/dune_rules/merlin.ml, test/blackbox-tests/test-cases/merlin/server.t/dune, test/blackbox-tests/test-cases/merlin/server.t/not-a-module-name.ml, test/blackbox-tests/test-cases/merlin/server.t/run.t
This is part of #4217
Fixes ocaml/merlin#1262
It implements the [proposed solution n°  2](https://github.com/ocaml/dune/issues/4217#issuecomment-781468553) to handle more gracefully source files with uncommon names.
For example it is somehow regular to have a file `my_module.ccpo.ml` that will be be preprocessed by a rule with target `my_module.ml`.
However the user-edited file is `my_module.ccpo.ml` and we want Merlin to work as expected even if the configuration has been generated by Dune for `my_module.ml`. 
This PR implement the simplest solution to that issue: by convention, the first component of a filename whose parts are separated by dots is used to match with the generated configurations.
=> [merlin] Handle filenames with dot-separated sections

otherlibs/dune-rpc/private/dune_rpc_private.ml
After we fill a request, we can remove it from the table of pending
requests.
=> [dunerpc] Cleanup requests table

test/expect-tests/dag/dag_tests.ml
This is a minimal test that reveals a problem with our cycle detection library: adding an edge that creates a cycle is not an idempotent operation: first, it fails with an error (as it's supposed to) but after another attempt, it accepts the edge, creating a cycle (as it's not supposed to).
=> Add a test demonstrating that cycles can be created

otherlibs/dune-rpc/private/types.ml, src/dune_engine/stanza.ml
@jeremiedimino I tried moving this to a shared file and using a copy rule like
we discussed, but then we need to complicate bootstrap. It doesn't seem worth it
to go through all that when we can just write it in the rpc.
=> [rpc] Use dune's latest version in versioning rpc

src/memo/memo.ml, test/expect-tests/memo/memoize_tests.ml
Calling `Memo.exec` and then not running the resulting `Fiber.t` brings the memoization framework into an inconsistent internal state. The first commit demonstrates the problem, to be fixed in subsequent commits.
=> Fix eager side effects in Memo.exec

test/expect-tests/memo/memoize_tests.ml
This is a follow up for #4275, showing that it is possible to create a dependency cycle at the level of the Memo API. This leads to deadlocks and zombie computations, so ideally we should find a way to work around the limitation of the cycle detection library.
=> Reveal deadlocks and zombies when repeatedly creating a cycle

bench/dune_bench/scheduler_bench.ml, bin/common.ml, bin/common.mli, bin/import.ml, bin/ocaml_merlin.ml, bin/subst.ml, src/dune_engine/import.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/stdune/fpath.ml, src/stdune/fpath.mli, test/blackbox-tests/test-cases/dialects.t/run.t, test/blackbox-tests/test-cases/dune-init.t/run.t, test/blackbox-tests/test-cases/enabled_if-exec.t/run.t, test/blackbox-tests/test-cases/env/env-variables.t/run.t, test/blackbox-tests/test-cases/foreign-library.t/run.t, test/blackbox-tests/test-cases/link-includes.t/run.t, test/blackbox-tests/test-cases/meta-template-version-bug.t, test/blackbox-tests/test-cases/multi-dir.t/run.t, test/blackbox-tests/test-cases/private-package-lib.t/run.t, test/blackbox-tests/test-cases/private-public-overlap.t/run.t, test/blackbox-tests/test-cases/re-exported-deps.t/run.t, test/blackbox-tests/test-cases/toplevel-stanza.t/run.t, test/blackbox-tests/test-cases/utop/utop-default.t/run.t, test/blackbox-tests/test-cases/workspaces.t/run.t, test/expect-tests/vcs_tests.ml
This is an attempt to make the Scheduler more agnostic of the console UI. The
basic idea is that the scheduler should just fire events that a UI should
handle, and not know anything about the console backend. This is needed to make
it easier to incorporate dune's upcoming tui, which will be handling these
events differently.
@aalekseyev perhaps you could take a look?
=> Move UI code from Scheduler

CHANGES.md, src/dune_rules/preprocessing.ml
Fixes: #3698, which is a regression from #2286. Should we add a test for it?
=> Add back correct host for ppx.exe

test/expect-tests/memo/memoize_tests.ml
This test highlights a known quadratic behaviour in Memo that will be fixed in an upcoming PR.
=> Add a test showing unnecessary recomputation of nested nodes with cutoff

test/expect-tests/memo/memoize_tests.ml
When we recompute a node, the old nodes that it had previously created are registered as dependencies of the result. Not sure this can lead to incorrect behaviour under the assumption of deterministic computations, but it's at least a performance problem.
The current test is a bit of a hack: it triggers the problem thanks to non-determinism. It would be nice to find a way to demonstrate the problem without non-determinism. @aalekseyev Any ideas?
=> Add a test demonstrating phantom dependencies

bin/import.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli
The caching logic can be outside of the scheduler, if we allow to run
"tasks" from the scheduler thread.
=> Kick out caching out of scheduler

src/catapult/catapult.ml, src/catapult/catapult.mli, src/dune_engine/stats.ml, test/blackbox-tests/test-cases/trace-file.t/run.t, test/expect-tests/catapult/catapult_tests.ml
This allows us to record more than one time series at once.  Use this for the GC
stats.
=> Allow record valued counters

src/memo/memo.ml, test/expect-tests/memo/memoize_tests.ml
Now if a node has no cutoff and we find out that it is out of date, we do not recompute it immediately but postpone recomputation until we know for sure that this node actually contributes to the final result.
=> Do not recompute nodes with cutoff unnecessarily

otherlibs/stdune-unstable/fdecl.ml, otherlibs/stdune-unstable/fdecl.mli, src/memo/memo.ml, src/memo/memo.mli
As a follow up to #4305, we are making it easier to create nodes with no cutoff, since they can be treated more efficiently.
=> Make it easier to create lazy nodes with no cutoff

src/dune_engine/process.ml
When ok_codes `n = false`, it's not possible for `t` to be `Ok`
@jeremiedimino perhaps I'm missing something obvious here, but this piece of
code doesn't seem useful.
=> Remove dead code in Process

bench/dune_bench/scheduler_bench.ml, bin/common.ml, bin/import.ml, src/dune_config/dune_config.ml, src/dune_config/dune_config.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, test/expect-tests/vcs_tests.ml
It's no longer required now that we manage screen clearing outside of
scheduler.
=> Move terminal persistence out of scheduler

src/dune_engine/build_system.ml
This is already taken care of by the `Build_system.reset` in `Dune_engine.Main.init_build_system`.
=> Do not clear errors in Build_system.run

.ocamlformat
I've had this diff sitting around unstaged for some time, and finally decided to PR it. In short:
> The `conventional` profile is default for fresh installations of OCamlFormat, but is override-able via a global config file inside `$XDG_CONFIG_HOME. To ensure that formatting is reproducible on a per-project basis, it's necessary to override any settings in this global file.
I've had some issues with new contributors to projects accidentally reformatting the project due to this behaviour, so at some point decided to defend against it; perhaps this will avoid some grief here too :-)
A potential change to the semantics of global config files is tracked by [this issue](https://github.com/ocaml-ppx/ocamlformat/issues/1459).
=> Specify conventional profile in .ocamlformat config

src/dune_rules/cram_exec.ml
Record disambiguation behaviour changed when using `|>` in https://github.com/ocaml/ocaml/pull/10081
cc @alainfrisch
=> Add support for OCaml 4.13

src/dune_engine/action_builder.ml, src/dune_engine/action_builder.mli, src/dune_rules/buildable_rules.ml, src/dune_rules/merlin.ml, src/dune_rules/merlin_ident.ml, src/dune_rules/merlin_ident.mli
This makes it possible to get rid of `merlin-exists` files and is also useful for the Jenga -> Dune transition.
=> Add [goal] constructor to [Action_builder.t]

doc/quick-start.rst
For "Setting the OCaml compilation flags globally",
```
(env
(dev
(flags (:standard -w +42)))
(release
(flags (:standard -O3))))
```
`(flags (:standard -O3))` will only cause an error (I don't know the reason but because of ocamlc still used I think). So instead, use `ocamlopt_flags` instead of `flags` and it will not error.
```
/usr/bin/ocamlc.opt: unknown option '-O3'.
```
Here is the error using `flags` instead of `ocamlopt_flags`.
```
Signed-off-by: Jack Murrow <jack.murrow122005@gmail.com>
```
=> Fixed OCaml compilation flag error

src/cache/local.ml
* Use Temp to delete temp dir. This will prevent another deletion from being
attempted on at_exit
* Switch to using `Path` over `Unix` functions. This reduces the conversions
visible in the code.
=> [cache] path related cleanups

bin/build_cmd.ml, otherlibs/dune-rpc/dune_rpc.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_rpc_impl/server.ml, src/dune_rpc_impl/server.mli
This fixes the shutdown notification to work when the code is waiting for file
changes. Previously, a pending shutdown would wait until a file notification was
sent.
=> [RPC] Fix shutdown

otherlibs/stdune-unstable/caller_id.mli, otherlibs/stdune-unstable/io.ml, otherlibs/stdune-unstable/io_intf.ml, src/dune_engine/action.ml, src/dune_engine/action.mli, src/dune_engine/action_ast.ml, src/dune_engine/action_builder.ml, src/dune_engine/action_builder.mli, src/dune_engine/action_dune_lang.ml, src/dune_engine/action_exec.ml, src/dune_engine/action_intf.ml, src/dune_engine/action_mapper.ml, src/dune_engine/build_system.ml, src/dune_engine/process.ml, src/dune_engine/process.mli, src/dune_rules/action_to_sh.ml, src/dune_rules/action_unexpanded.ml, src/dune_rules/cinaps.ml, src/dune_rules/test_rules.ml, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
This is useful for creating helper scripts, which is something we do inside Jane Street and we need it for the transition to Dune.
This PR only adds the internal support for now, it doesn't expose it through the syntax.
=> Allow to create executable files in the action language

src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_rules/main.ml, src/fiber/fiber.ml, test/expect-tests/fiber/fiber_tests.ml, test/expect-tests/test_scheduler/test_scheduler.ml, test/expect-tests/test_scheduler/test_scheduler.mli
Instead of the execution of the last fiber that happened to run. The first commit adds a test that demonstrate the issue, and the second commit fixes it.
=> Make iter callback of Fiber.run iter run in same execution context

src/fiber/fiber.ml, test/blackbox-tests/test-cases/all-alias.t/run.t, test/blackbox-tests/test-cases/coq/compose-cycle.t/run.t, test/blackbox-tests/test-cases/coq/compose-two-scopes.t/run.t, test/blackbox-tests/test-cases/coq/public-dep-on-private.t/run.t, test/blackbox-tests/test-cases/odoc/odoc-unique-mlds.t/run.t, test/blackbox-tests/test-cases/plugin-mode.t/run.t, test/expect-tests/dune_rpc/dune_rpc_tests.ml, test/expect-tests/fiber/fiber_tests.ml, test/expect-tests/test_scheduler/test_scheduler.ml
At the moment, when we call `Ivar.fill` we immediately execute the fibers waiting on this ivar. This means that they might be executed on a stack that is quite deep. I've observed stack overflows because of this while trying Dune inside Jane Street.
This PR changes the implem so that when we call `Ivar.fill`, we only queue the execution of the fibers and actually execute from the toplevel, in `FIber.run`. We create one job queue per call to `Fiber.run` and store it in the execution context.
The code is actually a bit simpler as a result as we don't need to think about context switches anymore in various functions such as `Ivar.fill`, which is nice.
The tests are failing at the moment.
=> Reduce stack usage in fiber

bin/common.ml, src/dune_engine/cached_digest.ml, src/dune_engine/clflags.ml, src/dune_engine/clflags.mli, test/blackbox-tests/test-cases/debug/digests.t
This PR add an option `--debug-digests` that makes Dune explain why it decides to re-digest some files:
```
$ dune build x --debug-digests
Re-digested file x because its stats changed:
{ old_digest = digest "b83631c134a9649ec383d0eb9c356803"
; new_digest = digest "705e0d7e5030b1831b18211b1e398faf"
; old_stats = { mtime = 1617030769.38; size = 0; perm = 436 }
; new_stats = { mtime = 1617030769.41; size = 2; perm = 436 }
}
```
I've sometimes wondered why Dune was re-digesting some files. This should help understand why.
=> Add an option to debug Dune's metabolism

src/dune_engine/build_system.ml, src/dune_engine/dep.ml, src/dune_engine/dep.mli
To avoid re-computing them over and over. This should speed up things.
=> Cache digests of aliases and globs

otherlibs/stdune-unstable/temp.ml, otherlibs/stdune-unstable/temp.mli
The current implementation tries the same candidate 1000 times instead of trying 1000 different candidates. This PR fixes this bug and also does a minor refactoring.
=> Fix generation of temp paths

otherlibs/stdune-unstable/path.ml
This change makes it so that the `basename` function does not use `Fdecl.get Build.build_dir` and therefore its semantics is stable even if the build directory path changes.
Pragmatically this was motivated by work on the internal janestreet fork of dune where we construct paths at toplevel, so we run into this `Fdecl.get` failing.
=> Make `Stdune.Path.basename` fail when used on the root of build dir

otherlibs/stdune-unstable/path.ml
We are calling `Sys.getcwd` at the toplevel of both Fpath and Path. Let's share this value.
=> Avoid one initial call to Sys.getcwd

otherlibs/stdune-unstable/path.ml, otherlibs/stdune-unstable/path.mli, src/cache/local.ml, src/dune_engine/cached_digest.ml
I'm factoring out a few smaller patches out of my upcoming PR on rewriting the shared cache.
This patch removes some code duplication and makes `Path.Build.chmod` more flexible.
=> Make Path.Build.chmod more flexible

src/dune_engine/dpath.ml
Make analyse_target slightly more robust. 
In one case when working on a forked dune we saw this call to `Path.Source.basename` raise.
We don't know why this happened, but it seems better not to raise in that case.
=> Small robustness fix in analyse_target

src/dune_engine/action.ml, src/dune_engine/action.mli, src/dune_engine/build_system.ml, src/dune_engine/dep.ml, src/dune_engine/dep.mli, src/dune_engine/dune_project.ml, src/dune_engine/dune_project.mli, src/dune_engine/execution_parameters.ml, src/dune_engine/execution_parameters.mli, src/dune_engine/source_tree.ml, src/dune_engine/source_tree.mli, test/blackbox-tests/test-cases/depend-on/dep-on-alias.t/run.t
Which capture all the information that might influence rule execution. Right now, this is only the dune language version, but I plan to add `swallow_stdout_on_success` in there as well after. The new module `Execution_parameters` also collect the various behaviour that depend on the dune version, such as:
```
val should_remove_write_permissions_on_generated_files : t -> bool
```
This PR also adds a function `Source_tree.execution_parameters_of_dir` which has a cutoff. The rationale is to make `execute_rule` depend only on this value rather than on the whole `Dune_project.t`, which is bigger and might change more often.
The second commit introduce `should_expand_aliases_when_sandboxing : t -> bool` so that the expansion of aliases when sandboxing only takes effect when using lang dune >= …
=> Introduce execution parameters

src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rules/dune_load.ml, src/dune_rules/dune_load.mli, src/dune_rules/gen_rules.ml
Stop keeping track of VCS commit in `build_system.ml`.
We found that in the cloud setting, restoring artifacts rule by rule is fast enough, so we no longer plan to support the bulk download mode where we fetch all artifacts corresponding to a git commit. This was the only reason to keep VCS information.
(This is extracted from #4443.)
=> Remove VCS support from Dune cache

bin/common.ml, bin/common.mli, bin/import.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/clflags.ml, src/dune_engine/clflags.mli, src/dune_rules/cram_rules.ml, src/dune_rules/dune_load.ml, src/dune_rules/dune_load.mli, src/dune_rules/dune_rules.ml, src/dune_rules/gen_rules.ml, src/dune_rules/gen_rules.mli, src/dune_rules/install_rules.ml, src/dune_rules/install_rules.mli, src/dune_rules/main.ml, src/dune_rules/main.mli, src/dune_rules/only_packages.ml, src/dune_rules/only_packages.mli, src/dune_rules/super_context.ml, src/dune_rules/super_context.mli, src/memo/memo.ml, src/memo/memo.mli, test/blackbox-tests/test-cases/vendor/dash-p-and-vendored-packages.t/run.t
This PR is part of an effort to make the initialisation code more "pull-based". i.e., in polling mode, instead of doing some toplevel (big) side effecting computations in a loop, I'd like to have a single call to `Memo.Build.run` which pulls the various bits it needs via memo.
This particular PR removes `Build_system.set_packages`. To do that, I had to add a memo for getting the list of all super contexts, which required making `Dune_load.load` and `only_packages` be pulled based as well. In the end:
- the first commit introduces a `Dune_rules.Only_packages` module with a `Clflags` sub-module similar to the one on the `Workspace` module;  we set it once at the beginning of the process and then we have a memo for the evaluation of the command line settings. I moved there all the logic …
=> Remove Build_system.set_packages

CHANGES.md, doc/tests.rst, src/dune_rules/cram_rules.ml, src/dune_rules/cram_stanza.ml, src/dune_rules/cram_stanza.mli, test/blackbox-tests/test-cases/tests-locks.t/dune-project, test/blackbox-tests/test-cases/tests-locks.t/run.t, test/blackbox-tests/test-cases/tests-locks.t/tests-no-locks/b.t, test/blackbox-tests/test-cases/tests-locks.t/tests-no-locks/dune, test/blackbox-tests/test-cases/tests-locks.t/tests-no-locks/sub/d.t, test/blackbox-tests/test-cases/tests-locks.t/tests/a.t, test/blackbox-tests/test-cases/tests-locks.t/tests/dune, test/blackbox-tests/test-cases/tests-locks.t/tests/sub/b.t
This PR adds locks to the Cram stanza. This is necessary to run some mutually exclusive tests.
For example we have some tests of the Merlin server that fail randomly when executed concurrently.
Of course the hard part is testing these changes:
- I had to turn off `INSIDE_DUNE` but I believe this should not be too dangerous if I then always specify the `--root` of the workspace on the command line ?
- I make the assumption that two identical tests that run concurrently should finish at the same second. This is wrong (but luckily pleased the CI), and I guess we should loop and compute a mean.
=> [cram] Add locks to the Cram stanza

bin/build_cmd.ml, bin/common.ml, bin/compute.ml, bin/describe.ml, bin/exec.ml, bin/import.ml, bin/print_rules.ml, bin/printenv.ml, bin/top.ml, bin/utop.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rules/context.ml, src/dune_rules/context.mli, src/dune_rules/cxx_flags.ml, src/dune_rules/gen_rules.ml, src/dune_rules/gen_rules.mli, src/dune_rules/main.ml, src/dune_rules/main.mli, src/dune_rules/odoc.ml, src/dune_rules/odoc.mli, src/memo/memo.ml, test/blackbox-tests/test-cases/cxx-flags.t/run.t
This PR changes things so that `Build_system.init` is now only used once at the beginning of the process to tie the knot between `Dune_engine` and `Dune_rules`, and is no longer called on every build in polling mode.
The various values required by `Gen_rules.gen_rules` are now pulled entirely via memo.
We still have a `Import.Main.setup` in `bin/import.ml`, however it is now much simpler and it's only job is to setup the status line.
=> Make the toplevel build pull-based

CHANGES.md, doc/dune-files.rst, src/dune_engine/dune_project.ml, src/dune_engine/dune_project.mli, src/dune_engine/source_tree.ml, src/dune_engine/source_tree.mli, test/blackbox-tests/test-cases/alternative-dune-fname.t/run.t
As discussed in #4386 we decided to allow an alternative name for dune files. As a first step, the present PR allows `dune-file` as an alternative to `dune` (with `dune-file` taking precedence over `dune`). A couple of questions:
- do we version this change?
- what about the documentation? do we publicize `dune-file` as the "official" name from now on?
Fixes #4386
=> Accept dune-file as dune file name

src/dune_engine/build_system.ml
I initially thought it was better to not include them as I thought about them as implementation details of the `Action.t Action_builder.t`. But thinking about it again it seems better to include them, especially since tests that are executed via anonymous actions.
=> Include anonymous actions in rule count

bench/dune
There is a conflict between `vendor/spawn` and the `spawn` dependency of `core_bench`. Let's disable the build of the bench program until this is sorted.
=> Disable the build of the bench program

otherlibs/stdune-unstable/fpath.ml, otherlibs/stdune-unstable/fpath.mli, otherlibs/stdune-unstable/path.ml, otherlibs/stdune-unstable/temp.ml, src/dune_cache_storage/layout.ml, src/dune_cache_storage/layout.mli, src/dune_engine/build_system.ml
This PR fixes a few issues with `temp.ml`:
=> Fix a few issues with [temp.ml]

src/dune_engine/format_dune_lang.ml, src/dune_lang/atom.ml, src/dune_lang/atom.mli, src/dune_lang/cst.ml, src/dune_lang/cst.mli, src/dune_lang/encoder.ml, src/dune_lang/lexer.mli, src/dune_lang/lexer.mll, src/dune_lang/parser.ml, src/dune_lang/parser.mli, src/dune_lang/t.ml, src/dune_lang/t.mli, src/dune_rules/action_unexpanded.ml, src/dune_rules/binary_kind.ml, src/dune_rules/dep_conf.ml, src/dune_rules/dune_file.ml, src/dune_rules/modules_field_evaluator.ml, src/dune_rules/ordered_set_lang.ml, src/upgrader/dune_upgrader.ml, test/expect-tests/dune_lang/sexp_tests.ml
A bit more cleanup following dropping support for jbuilder:
- we no longer need to support "sexp comments" or "block comments" in the parser
- not all strings are valid `Atom.t` values. We didn't make the type strict in the past because it made the jbuilder support complicated, but now we can
=> More cleanup following dropping jbuilder support

src/dune_engine/build_system.ml
Self-explanatory, random typos in progress reporting.
=> fix minor error in rpc progress reporting

bin/cache.ml, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
Otherwise some existing scripts might fail with an unhelpful error.
=> Add an error message for removed cache start/stop commands

doc/caching.rst, doc/dev/cache.md, src/dune_cache_storage/mode.mli
Now that the cache daemon is removed, we need to purge its mentions from the docs.
=> Update Dune cache documentation

src/dune_cache/trimmer.ml
This is a follow up to @aalekseyev's change of the `Path.stat` interface.
While doing that, I documented a couple of races and a problem with our trimming heuristic.
=> Handle [Path.stat_exn] errors in the trimmer

CHANGES.md, bin/common.ml, doc/caching.rst, otherlibs/stdune-unstable/option.ml, otherlibs/stdune-unstable/option.mli, src/dune_cache/config.ml, src/dune_cache/config.mli, src/dune_cache_storage/mode.ml, src/dune_cache_storage/mode.mli, src/dune_config/dune_config.ml, src/dune_config/dune_config.mli, src/dune_engine/build_system.ml, test/blackbox-tests/test-cases/dune-cache/config.t/run.t, test/blackbox-tests/test-cases/dune-cache/promote-copy.t/run.t, test/blackbox-tests/test-cases/dune-cache/promote-direct-copy.t/run.t, test/blackbox-tests/test-cases/dune-cache/promote-direct.t/run.t, test/blackbox-tests/test-cases/dune-cache/promote.t/run.t, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t, test/blackbox-tests/utils/dune_cmd.ml, test/expect-tests/dune_config/dune_config_test.ml
Also improve new cache configuration and associated help messages.
I added a test to make sure the changes of the configuration file are appropriately versioned, and that environment variables and command flags can override them, as advertised.
I added `dune_cmd exists` for convenient and portable checking of file/directory existence.
This completes the rewrite of Dune cache. The next step is implementing the cloud cache on top of the new foundation.
=> Delete old cache configuration settings in 3.0

doc/sites.rst
I found this out when trying sites in my project. `generate_sites_module` should take `(module module_name)` and not `(name ...)`
=> docs: `name` -> `module` in `(generate_sites_module ...)`

bin/common.ml, src/dune_engine/build_system.ml, src/dune_engine/execution_parameters.ml, src/dune_engine/execution_parameters.mli, src/dune_engine/source_tree.ml, src/dune_engine/source_tree.mli
We don't do that in Dune at the moment, but it is used by the Jenga rules inside Jane Street. Without this PR we get a loop between:
- find-dir-raw "." (the listing in source_tree of the root source dir)
- the filtering of files (in an upcoming PR) that goes through interpreting the .hgignore with the jenga rules
- calling `hg debugignore` via an anonymous action
- calling `Source_tree.execution_parameters_of_dir (Path.Build.drop_optional_build_context dir)` where `dir` is `_build/.actions`
- find-dir-raw "."
=> Allow anonymous actions attached to a directory outside a build context

test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
It turned out to be flaky and broke `main`, so I'm replacing it with a `TODO` for now.
=> Drop the trimming test for the [copy] mode for now

src/dune_engine/build_system.ml, src/dune_engine/fs_notify_memo.ml, src/dune_engine/fs_notify_memo.mli, src/dune_engine/scheduler.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
Currently any `Files_changed` event triggers the restart of the build, even if the modified file is ignored by the build system. This PR changes the behaviour to only trigger restarts when the file change events correspond to files that are tracked by the build system, i.e. for which we called `Fs_notify_memo.depend`.
=> Don't restart the build when untracked files change

src/dune_engine/scheduler.ml, src/memo/memo.ml, src/memo/memo.mli
As pointed out by @aalekseyev, we should enable the optimisation introduced in #4512 if the user enabled the incremental mode via the environment variable `DUNE_WATCHING_MODE_INCREMENTAL`.
=> Skip untracked file changes in incremental mode

otherlibs/dune-rpc/dune_rpc.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/conv.ml, otherlibs/dune-rpc/private/conv.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_rpc_impl/server.ml
This change is API-only.
This PR introduces two changes to the public-facing API.
- Make the `targets` field of `Diagnostic.t` less stringly-typed. This way, clients can have descriptive error messages independent of dune's rendering
- Add the `directory` field to diagnostics. In a lot of cases I expect this to be redundant with `targets`, but if an action decides to `cd` on its own or something, this can be useful. More selfishly, Jenga currently passes this field in its RPC, so a lot of our internal consumers would prefer to have this field directly (rather than try to infer it out of `targets`).
=> [RPC] Richer diagnostic reporting

otherlibs/stdune-unstable/temp.ml, otherlibs/stdune-unstable/temp.mli, src/dune_rpc_impl/run.ml
@rgrinberg This PR essentially reverts this commit: https://github.com/ocaml/dune/commit/653462ad1213119597d2a9f157f70892765f23e3.
We recently changed the behaviour of `temp_path` because the behaviour that the above commit restores is unsafe: if you call `temp_path` concurrently, you may end up getting the same path as a result, because you don't "reserve" the path in any way. As a result, multiple processes may interfere by using the same temporary file. Since it's impossible to use such API safely, it seems better to not provide it at all.
I expanded the comment to make it clearer why the temporary files must be created and what to do if the call site doesn't want them to exist -- create a temporary directory and use any path inside, which is safe.
Note that `client_address` that was …
=> Make [Temp.temp_path] safe again and document why

Makefile
Current-bench expects only json as output from the `make bench` target as of now, so any extraneous output will cause it to fail. Suppressing the stderr output for now to make it pass.
=> Suppress stderr output for current-bench

otherlibs/stdune-unstable/temp.ml, otherlibs/stdune-unstable/temp.mli, src/dune_cache/local.ml, src/dune_cache_storage/dune_cache_storage.ml, src/dune_cache_storage/dune_cache_storage.mli, src/dune_cache_storage/layout.ml, src/dune_cache_storage/layout.mli, src/dune_cache_storage/util.ml, src/dune_cache_storage/util.mli, src/dune_rpc_impl/run.ml
Renaming `Temp.temp_path` and adjusting a few similar names, as suggested in #4519.
=> Make names containing "path" less ambiguous

Makefile
Currently, continous benchmarking fails with the error `make: Nothing to be done for target 'bench'`, adding a .PHONY target forces it to make bench everytime.
=> Make `bench` a .PHONY target

bin/rpc.ml
These were used to make some tests more reproducible. Those tests were
removed.
=> [RPC] remove reconnection retries

bench/bench.ml, otherlibs/stdune-unstable/dune, otherlibs/stdune-unstable/proc.ml, otherlibs/stdune-unstable/proc.mli, otherlibs/stdune-unstable/wait3_stubs.c, src/dune_engine/process.ml, src/dune_engine/process.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, test/blackbox-tests/test-cases/trace-file.t/run.t
We fallback to the old method on win32.
=> Use wait3 to accurately time spawned processes

src/dune_engine/build_system.ml, src/dune_engine/fs_memo.ml, src/dune_engine/source_tree.ml, src/dune_engine/vcs.ml, src/dune_rules/command.ml, src/dune_rules/context.ml, src/dune_rules/dir_contents.ml, src/dune_rules/dir_status.ml, src/dune_rules/fdo.ml, src/dune_rules/install_rules.ml, src/dune_rules/super_context.ml, src/dune_rules/workspace.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
I noticed that #4540 left `create_hidden` whose name is now out of date.
I initially wanted to rename it to `create_simple` but after discussing with @aalekseyev, we thought that it would be better to rename `Output.Simple` to `Output.Cutoff` and `create_hidden` to `create_no_cutoff` for greater clarity at call sites.
While doing the renaming, I noticed that in a few places we can simplify the code by using `create_no_cutoff` instead of `create`, which doesn't require to pass the `Output` module, which was often created on the spot.
=> Drop remaining references to visibility in Memo

bin/dune_init.ml, src/dune_engine/action_exec.ml, src/dune_engine/build_system.ml, src/dune_engine/diff.ml, src/dune_engine/fs_memo.ml, src/dune_engine/import.ml, src/dune_engine/include_stanza.ml, src/dune_engine/promotion.ml, src/dune_engine/source_tree.ml, src/dune_rules/cram_exec.ml, src/dune_rules/dune_load.ml, src/dune_rules/findlib/findlib.ml, src/dune_rules/findlib/findlib.mli, src/dune_rules/findlib/meta.ml, src/dune_rules/merlin_server.ml, src/dune_rules/simple_rules.ml, src/upgrader/dune_upgrader.ml
Hide `Path.exists` and `Path.readdir_unsorted_with_kinds` in Dune build engine, encouraging to use their tracked versions from `Fs_memo` instead. The untracked versions are still available from `Path.Untracked`.
This PR doesn't change any behaviour and switches to using `Path.Untracked` but leaves a couple of pointers for next steps.
=> Encourage accessing the file system via [Fs_memo]

src/dune_engine/build_system.ml, src/dune_engine/fs_memo.ml, src/dune_engine/fs_memo.mli, src/dune_rules/workspace.ml
A follow up to #4543.
Also rename `Fs_memo.file_exists` to `Fs_memo.path_exists` since we use it not only for files but for directories too.
=> Replace some [Path.Untracked.exists] calls with [Fs_memo.path_exists]

src/dune_engine/source_tree.ml, src/dune_engine/source_tree.mli
Another follow up to #4543.
All remaining occurrences of `Path.Untracked.readdir_unsorted_with_kinds` are called on a build directory.
=> Switch to using [Fs_memo.dir_contents] in [Source_tree]

src/dune_engine/cached_digest.ml, src/dune_engine/fs_memo.ml, src/dune_engine/fs_memo.mli, src/dune_engine/import.ml, src/dune_engine/source_tree.ml
Start tracking `Path.stat` calls in `Source_tree`. Also take care of a previously unhandled error.
=> Add [Fs_memo.path] and use it in [Source_tree]

doc/dune-files.rst
I recently opened #4486 to discover that it was in fact not an issue but a lack of comprehension from my part. This PR attempts to help by:
- documenting the `using` stanza in its own subsection of the `Stanza reference > dune-project` file, and
- adding a note in `Stanza reference > dune-project > package`.
The goal is to make the documentation a bit clearer so that me-from-the-past (or anyone else in the same situation) realises that the version in `(using menhir <version>)` has nothing to do with the version of Menhir and everything to do with the version of the DSL under the `(menhir ...)` stanza. As a consequence, having `(using menhir <version>)` in one's `dune-project` file does not make Menhir a dependency of the project.
I added a section about the `using` stanza right after the …
=> Document "using" and warn that it does not imply a software dependency

src/dune_engine/vcs.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
This PR fixes a couple of tests so that running `DUNE_WATCHING_MODE_INCREMENTAL=true dune runtest -w` doesn't fall over on the very first build. 
There were two problematic tests:
* `vcs_tests.ml` was using functions like `Vcs.describe` that call out to `git` or `hg`. Despite using `of_reproducible_fiber`, the corresponding fibers are actually not reproducible, since the result depends on the current state of the file system. I fixed this by adding `Memo.Build.of_non_reproducible_fiber` that adds a dependency on the current run, and changed `Vcs` to use it instead. This means that we will rerun `Vcs`'s fibers in every build run. We might find a way to optimise this in future.
* `memoize_tests.ml` was calling `Memo.reset` relying on it to clear the memoization caches, but `Memo.reset` …
=> Fix testsuite in incremental file-watching mode

src/dune_engine/build_system.ml, src/dune_engine/execution_parameters.ml, src/dune_engine/fs_memo.ml, src/dune_engine/source_tree.ml, src/dune_engine/vcs.ml, src/dune_rules/command.ml, src/dune_rules/context.ml, src/dune_rules/dir_contents.ml, src/dune_rules/dir_status.ml, src/dune_rules/fdo.ml, src/dune_rules/install_rules.ml, src/dune_rules/odoc.ml, src/dune_rules/packages.ml, src/dune_rules/super_context.ml, src/dune_rules/workspace.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
As discussed in #4542, we are removing the requirement to provide `to_dyn` for outputs of memoized functions. This helps us to simplify the API and get rid of some internal complexity.
=> Remove [to_dyn] of memoized function outputs

src/dune_engine/dep_path.ml, test/blackbox-tests/test-cases/executables-implicit-empty-intf.t/run.t, test/blackbox-tests/test-cases/private-modules.t/run.t, test/blackbox-tests/test-cases/wrapped-transition.t/run.t
Since a change in the git repo several weeks ago, Dune prints a location pointing to the dune file even if the output already contains a location. This is especially annoying for compiler errors.
This PR fixes that by not augmenting user messages with a location taken from the stack when the message starts with "File " (we already do a similar analysis in `process.ml`).
The difference can be observed in the tests that were updated.
=> Fix multiple location printing

src/memo/memo.mli
The callback should return `Build.t` rather than `Fiber.t`. We didn't notice it before because this function is unused at the moment.
I also moved it after `create` since `create_with_store` is a more expert version of `create`.
=> Fix type of Build.create_with_store

bin/common.ml, bin/common.mli, bin/import.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
To assist performance tuning of Memo, I'd like to add some performance counters.
For now, they include:
* `nodes_in_current_run`: number of nodes visited in the current run.
* `edges_in_current_run`: number of dependency edges of the nodes visited in the current run.
* `nodes_computed_in_current_run`: number of nodes that were (re)computed in the current run. This number cannot not exceed `nodes_in_current_run`. 
* `edges_traversed_in_current_run`: number of edges that were traversed in the current run. Some edges may be traversed twice, so this number can exceed `edges_in_current_run`.
I added the counters to some Memo tests, so that we can catch possible regressions (e.g. changes in cutoff behaviour).
It's also possible to run Dune with `-w --watch-metrics` to display the counters after …
=> Add performance counters and --watch-metrics flag

src/dune_engine/scheduler.ml, src/dune_file_watcher/dune_file_watcher.ml, src/dune_file_watcher/dune_file_watcher.mli, test/expect-tests/dune_file_watcher/dune_file_watcher_tests.ml
In my previous PR I introduced a bug where dune fails with this message whenever the inotify watcher is killed:
```
Thread 3 killed on uncaught exception Failure("end of file reading inotify pipe")
```
That includes when the watcher is killed by dune itself, for example on exit (e.g. when you terminate it with a signal).
This PR fixes that bug by propagating the failure to the main thread and handling it explicitly.
=> Fix the error "end of file reading inotify pipe" .

src/dune_engine/scheduler.ml, src/dune_file_watcher/dune_file_watcher.ml, src/dune_file_watcher/dune_file_watcher.mli, test/expect-tests/dune_file_watcher/dune_file_watcher_tests.ml
Fix the issue described [here](https://github.com/ocaml/dune/pull/4571#issuecomment-833354432). 
More precisely, fix the last reason why we are sometimes seeing the following when doing Ctrl+C:
```
Thread 3 killed on uncaught exception Failure("end of file reading inotify pipe")
```
The fix is to pass the `Thread.create` function defined in `scheduler.ml` to `Dune_file_watcher` and use it instead of the regular `Thread.create`. I used an API that is similar to the one used in `Csexp_rpc`. I'm thinking that it might be worth adding a `Thread` module in `Stdune` that would do this overriding once and for all. We might want to generalise this trick, for instance so that it can work with any signals the application might be interested in, so I'm leaving that for future work for now.
=> Fix handling of signals

src/dune_engine/scheduler.ml
With the current change, the build no longer deadlocks but we memoize `got signal KILL` as result of cancelled computations and so build can't proceed anyway. So, we need a way to mark these computations as "cancelled" and not memoize them. I'm going to do this right in this PR.
=> Delay calling Memo.reset until the build is cancelled

bench/bench.ml, bench/dune
Looking it up from PATH is fragile and could mean that the wrong dune is used.
=> [bench] always use dune from source

src/dune_engine/process.ml, src/dune_util/config.ml, test/expect-tests/process_tests.ml
Test demonstrates that Process.Io.null cannot be used as input or
output.
This is an old issue that I encountered when changing the VCS code. I'm not sure
if this is intentional, but it does make Process.Io.null hard to use correctly.
=> Add Dune_engine.Process unit test

CHANGES.md, src/dune_rules/gen_rules.ml, src/dune_rules/mdx.ml, src/dune_rules/mdx.mli, test/blackbox-tests/test-cases/mdx-stanza.t/enabled-if-old-lang-dune/dune, test/blackbox-tests/test-cases/mdx-stanza.t/enabled-if-old-lang-dune/dune-project, test/blackbox-tests/test-cases/mdx-stanza.t/enabled-if/dune, test/blackbox-tests/test-cases/mdx-stanza.t/enabled-if/dune-project, test/blackbox-tests/test-cases/mdx-stanza.t/enabled-if/iffalse.md, test/blackbox-tests/test-cases/mdx-stanza.t/enabled-if/iftrue.md, test/blackbox-tests/test-cases/mdx-stanza.t/run.t
This brings useful workflows such as disabling failing mdx test depending on the OS.
This is an ad-hoc solution until #4080 is implemented but looks safer for 2.x.
=> Add (enabled_if) support to the mdx stanza

CHANGES.md
This was added in unreleased instead of 2.9.0 as described in
<https://github.com/ocaml/dune/wiki/Release-Plan-for-Dune-2.9>
Signed-off-by: Etienne Millon <me@emillon.org>
=> Fix changelog section for #4434

src/dune_engine/action_builder.ml, src/dune_engine/action_builder.mli, src/dune_rules/action_unexpanded.ml
Now that `external-lib-deps` and `Action_builder`'s labels are gone, we can simplify the API of `Action_builder.static_eval` to just:
```ocaml
val static_eval : 'a t -> ('a * Dep.Set.t) option
```
rather than:
```ocaml
val static_eval : 'a t -> ('a * unit t) option
```
I need this for some change I was looking at.
=> Simplify the signature of Action_builder.static_eval

bin/build_cmd.ml
With this PR, our metrics change to
```
38341/38366 computed/total nodes, 136891/136870 traversed/total edges
(2.28 sec, 18864128 heap words)
```
=> Add heap words to build metrics

bin/build_cmd.ml, test/blackbox-tests/test-cases/dune
I missed the build failure case when testing #4592. With this PR, we print metrics both on successes and on failures.
=> Print metrics even if the build fails

bench/bench.ml, test/blackbox-tests/test-cases/dune
Use the new "swallow on success" setting for the stdout/stderr of commands executed by bench.ml
=> Don't swallow errors in bench.ml

src/dune_engine/build_system.ml, test/blackbox-tests/test-cases/dune-cache/repro-check.t/run.t, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
Context names are represented with ints internally, so marshalling them is a bug.
This PR fixes that bug by marshalling the corresponding string, instead.
=> Do not hash context name as int

src/dune_rules/coq_rules.ml, src/dune_rules/merlin.ml, src/dune_rules/merlin_server.ml
We developed an automated script to export patches from Janestreet internal repo instead of doing it manually.
The script ends up round-tripping via a different configuration of camlformat, and that roundtrip is not a no-op.
This PR accepts those changes (dropping some empty lines), so that the code roundtrips better.
=> Roundtrip formatting through Janestreet style.

otherlibs/stdune-unstable/stdune.ml, otherlibs/stdune-unstable/unix_error.ml, otherlibs/stdune-unstable/unix_error.mli, src/dune_engine/source_tree.ml
I noticed that no-op rebuilds lead to re-executing `execute_rule_impl` about a thousand times when building Iron, which was caused by the lack of cutoff on `Source_tree.Readdir.of_source_path`. After adding the cutoff, the no-op rebuilds got 3x faster for me.
=> Memoize [Source_tree.Readdir.of_source_path] with cutoff

src/dune_engine/scheduler.ml
Previously, it would not terminate current build processes when shutdown was
requested. This new implementation is exactly the same as sending a signal.
=> Fix rpc shutdown

otherlibs/stdune-unstable/console.ml, otherlibs/stdune-unstable/console.mli, src/dune_engine/build_system.ml, src/dune_engine/cached_digest.ml
This feature makes dune change its status line when it saves caches to disk.
This is very useful to see why dune is suddenly stuck for 5 seconds.
Testing
-------
Ran without -verbose, saw the status line show these messages as expected.
=> Show db save progress in status line

otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.mli, test/expect-tests/dune_rpc/dune, test/expect-tests/dune_rpc/dune_rpc_tests.ml
we ned to be careful with exporting types from Stdune, so we should be
explicit about modules coming from Stdune
=> [RPC] do not open stdune in signature

bench/bench.ml, otherlibs/stdune-unstable/temp.ml, otherlibs/stdune-unstable/temp.mli, src/dune_cache/local.ml, src/dune_cache_storage/util.ml, src/dune_engine/action_exec.ml, src/dune_engine/dtemp.ml, src/dune_engine/process.ml, src/dune_rpc_impl/run.ml, src/dune_rules/cram_exec.ml, src/dune_stats/dune_stats.ml, test/expect-tests/csexp_rpc/csexp_rpc_tests.ml, test/expect-tests/stdune/temp_tests.ml
As discussed in #4610.
I used underscores because:
* using `.` can lead to confusion with file extensions
* using `-` can be inconvenient if prefix is omitted, since the leading `-` might be confused with a command line flag -- for example, try `touch -test-`.
=> Add systematic separators for temp prefix and suffix

src/dune_engine/build_system.ml, src/fiber/fiber.mli, src/memo/memo.mli
Parallelism has a cost of combining dependencies of both computations. It's worth clarifying that in the docs. As discussed, I also reduced parallelism in `execute_rule_impl`, to avoid accumulating too much dependencies if we fail to compute action execution parameters.
=> Reduce parallelism in [execute_rule], add some docs

src/dune_util/report_error.ml, src/dune_util/report_error.mli
We've been deduplicating errors in Memo for a while, so there is no need for this special mechanism any more. In fact, since it uses a mutable set of already-reported errors, which is never cleared, it's not compatible with the incremental file-watching mode.
=> Drop already reported error code

src/dune_engine/build_system.ml
With the change to `Dep_path`, any information attached to `User_error.E` exceptions currently get swallowed before reaching the RPC, producing an empty diagnostic with the message `"Memo.Error.E(_)"`. This fixes that.
Signed-off-by: Cameron Wong <cwong@janestreet.com>
=> Fix RPC reporting of [Memo.Error.E] values

src/memo/memo.ml, src/memo/memo.mli, test/blackbox-tests/test-cases/formatting.t/run.t
Change `Memo.Build.run` to catch, deduplicate and reraise all exceptions to fix the bug I introduced in #4623.
=> Deduplicate errors in [Memo.Build.run]

src/dune_engine/action_exec.ml, src/dune_engine/print_diff.ml, src/dune_engine/process.ml, src/dune_engine/process.mli, test/blackbox-tests/test-cases/cinaps/include-subdirs.t/run.t, test/blackbox-tests/test-cases/cinaps/simple.t/run.t, test/blackbox-tests/test-cases/github3490.t/run.t
Since some time, we have been adding locations to diffs printed by dune that were not really useful. This PR improves this.
It adds a location pointing to the first diffed file to errors produced by `Print_diff`. This is what was happening before with `patdiff` as we were passing `--location-style omake`. We now do it no matter what diff program is being used. This also remove a race condition when using `diff` or `git diff` as we used to print the location using `Console.print` and then raise an exception, thus allowing other stuff to be printed in between.
=> Improve locations of diffs

src/dune_rules/profile.ml
I think this is a typo, right?
```
dra@thor:~/dune$ dune printenv --verbose 2>&1 | fgrep 'profile =' -A2 -B2
{ name = "default"
; kind = "default"
; profile = Dyn
; merlin = true
; for_host = None
```
=> Correct printed name of Dev profile

src/memo/memo.ml, test/expect-tests/memo/memoize_tests.ml
This makes sure that any Memo exceptions that escape are still printed
properly.
I saw @cwong-ocaml runnning into some `Memo.E (_)` exceptions. This should
improve messages like that.
=> Register memo exceptions for printing

otherlibs/stdune-unstable/console.ml, src/dune_engine/build_system.ml, src/dune_engine/cached_digest.ml
Saving Dune's databases can be slow if they are big. This PR changes Dune to save the databases only at exit.
This PR does a very simple but relatively dumb thing (just using `at_exit` instead of `Hooks.End_of_build`). As mentioned in the `CR-someday`, we might need to revisit the current implementation.
I tested that this interacts well with Ctrl-C handling: the first Ctrl-C starts the shutdown (including saving the database), the second Ctrl-C prints a message, the third Ctrl-C kills Dune (and discards the database).
=> Don't save Dune databases on every build run

Makefile
The bench command was changed to add a src so that there's no confusion about which dune is running the benchmarks. The benchmarks should now run, but will fail on the parse step (which I will fix in the current-bench pipeline).
Signed-off-by: Gargi Sharma <gs051095@gmail.com>
=> Add missing src for bench target

src/dune_engine/fs_memo.ml, src/memo/memo.ml, src/memo/memo.mli
Upstream some memo.ml tweaks made in Janestreet to reduce the diff.
Justifications for not reverting them in Janestreet fork, instead: 
- Memo.incremental_mode_enabled: we use it to enable incremental mode based on dune-workspace. We should probably upstream that change too and clean it up (stop using env var entirely), but it's a bit too tied up to upstream for now.
- The default size of memo table is 2: I'm generally thinking the smaller this number, the better. This change was made in a commit labelled "performance tweaks", so maybe it makes things slightly smaller, but I wouldn't hold my breath. (any effect is surely eclipsed by a ridiculous overhead of Table.create)
- `val lazy_cell` is exposed because, well, it's useful.
=> Upstream memo.ml tweaks

bin/build_cmd.ml, bin/common.ml, otherlibs/stdune-unstable/digest.ml, otherlibs/stdune-unstable/digest.mli, otherlibs/stdune-unstable/metrics.ml, otherlibs/stdune-unstable/metrics.mli, otherlibs/stdune-unstable/monoid.ml, otherlibs/stdune-unstable/monoid.mli, otherlibs/stdune-unstable/stdune.ml, src/memo/memo.ml, src/memo/memo.mli
This PR adds two time metrics: 
* Cycle detection (time spent in `Memo.add_dep_from_caller` function)
* Generic digest computation (time spent in `Digest.generic`)
For the zero build of Dune, I get:
```
69650/69650 computed/total nodes, 181578/181578 traversed/total edges
(2.19s total, 0.24s cycle detection, 0.06s digests, 24.7M heap words)
```
=> Add some more metrics

otherlibs/stdune-unstable/id.ml, otherlibs/stdune-unstable/id.mli, src/memo/memo.ml
In my experiments, this significantly reduces the time and memory taken by Memo's cycle detection (saw reductions from 20% to 50% for both).
=> Switch to hash tables in Deps_so_far

bin/rpc.ml, otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml, otherlibs/dune-rpc/dune_rpc.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/csexp_rpc/csexp_rpc.ml, src/csexp_rpc/csexp_rpc.mli, src/dune_rpc_server/dune_rpc_server.ml, src/dune_rpc_server/dune_rpc_server.mli, test/expect-tests/csexp_rpc/csexp_rpc_tests.ml, test/expect-tests/dune_rpc/dune_rpc_tests.ml
RPC is currently flushing after request and notification. While that's usually
good enough, it's a poor way of doing IO when one is sending many requests.
This PR introduces an API to batch requests & notifications and submit them at
once.
Two limitations of this API are:
* The server is unable to batch notifications to the client. This can be easily fixed.
* It's not possible to batch requests/notifictions along with the initialization request. So it's not possible to initialize, send requests & notifications in a single round trip.
=> [RPC] Batching API

src/csexp_rpc/csexp_rpc.ml
Print s-expressions in the traditional rather than the canonical form.
This makes it easier to debug.
=> [RPC] use readable sexp format for debugging

src/dune_engine/build_system.ml
This hook got lost when I was factoring out PR #4649 from out internal fork.
=> Add the lost Metrics.reset hook

editor-integration/emacs/dune
dune-watch is in the tree, but not made installed by opam. This is intended to fix that.
=> added dune-watch.el to install targets

src/dune_rules/context.ml, test/blackbox-tests/test-cases/install-libdir.t/run.t
I recently updated to a beta version of Opam 2.1 and the following error shows when using `opam config var prefix`:
```
opam: var was removed in version 2.1 of the opam CLI, but version 2.1 has been requested. Use opam var instead or set OPAMCLI environment variable to 2.0.
```
Two mitigations are possible:
1. Exporting `OPAMCLI=2.0`
2. Using `opam var prefix` instead
This PR implements option 2. However if I am not mistaken this will only work with `opam >= 2.0` ~~and I don't know if that is a satisfying constraint for Dune ?~~ Edit: the opam file does state `opam-version: "2.0"` so I guess this is not an issue.
=> Workaround `opam config var` being removed in Opam 2.1

bin/build_cmd.ml, bin/import.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli
This should fix some of the noise at shutdown that we've been seeing.
I tested this manually by calling [dune shutdown] while watching dune was building and not seeing any error.
=> Suppress build system early error reporting if we're shutting down

src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/memo/memo.ml, src/memo/memo.mli
To get better latency for RPC requests, file changes, signals, etc...
It works as follow:
- whenever we submit an event from a thread, we set the flag `got_event` to `true`
- in a strategic place in `memo.ml`, we call `Scheduler.yield_if_there_are_pending_events`, which checks if this flag is set and yield if yes, causing the execution to go through the scheduler
- we reset this flag just before the blocking `Condition.wait` in `Event.Queue.next`
I refactored a bit the code in `Event.Queue.next` to simplify the invariant around `available`. Now we only call `Condition.wait` after we have checked the various fields of the event queue and found no event to report.
I removed the deadlock check as it was now failing as soon as dune would yield and as discussed in the past, it is not really …
=> Insert yield points in memo

src/dune_engine/clflags.ml, src/memo/memo.ml, src/memo/memo.mli, src/memo/run.ml, src/memo/run.mli, test/expect-tests/memo/memoize_tests.ml
I've finally got around to finishing off this optimisation that we discussed a couple of times: with this PR, we no longer store a corresponding value (or its identifier) alongside every dependency in Memo. This saves some memory but also simplifies the implementation since we no longer need the `Value_id` module.
=> Stop storing value ids in Memo's lists of dependencies

bin/rpc.ml, otherlibs/dune-rpc-lwt/test/dune_rpc_lwt_tests.ml, src/csexp_rpc/csexp_rpc.ml, src/csexp_rpc/csexp_rpc.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_rpc_impl/run.ml, src/dune_rpc_impl/run.mli, test/expect-tests/csexp_rpc/csexp_rpc_tests.ml
The previous code would wait for all waiting to initialize before
serving a single session. This would cause unnecessary delays if clients
would stall.
@cwong-ocaml I think this should fix the "delays" you've been
encountering
@jeremiedimino some advice on how to write this code cleanly would be
appreciated.
=> [RPC] improve connection handling

src/memo/memo.ml
`Cached_value.deps` stores a list of dependencies `deps`. We construct this list when creating a cached value but traverse it on every rebuild (i.e. more often), so it makes sense to make this traversal faster by switching to an array and thus avoiding pointer chasing. This also saves some memory (roughly two words per node dependency).
My benchmarks show a noticeable improvement (of the order of 10%), given that this is a hot path for incremental rebuilds.
=> Use arrays for storing Memo node dependencies

bin/alias.ml, bin/alias.mli, bin/build_cmd.ml, bin/build_cmd.mli, bin/exec.ml, bin/print_rules.ml, bin/target.ml, bin/target.mli, bin/top.ml, bin/utop.ml, test/blackbox-tests/test-cases/overlapping-deps.t
The goal of this PR is to remove the call to `eval_build_request` in `bin/target.ml` so that functions in `Build_system.For_command_line` are only called for `dune rules`. This will allow to simplify the implementation of `Action_builder`, and hopefully make it more efficient.
To do that, this PR refactors the code interpreting targets.
The first three commits are preparatory work to simplify the API of `Target`:
- the first commit removes `Target.resolve_target` and adapt the code in utop.ml which was the only user of this function
- the second commit removes `Target.resolve_target_mixed` and adapt the code in exec.ml which was the only user of this function
- the third commit merges `Target.resolve_targets_exn` and `Target.request` into a single `Target.interpret_targets` function, …
=> Refactor target interpretation to remove call to `eval_build_request`

bin/alias.ml, src/dune_engine/action_builder.ml, src/dune_engine/action_builder.mli, src/dune_engine/alias.ml, src/dune_engine/alias.mli, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rules/dep_conf_eval.ml, src/dune_rules/install_rules.ml, src/dune_rules/main.ml, src/dune_rules/super_context.mli
This module contained:
- functions to interpet `(alias* ...)` in dune file, these were moved to `Dune_rules.Dep_conv_eval`
- functions to interpret `@...` on the command line, these were moved to the `bin/` directory
- some code to setup a default alias when it isn't defined. This doesn't need to belong to the core so I made it configurable and moved the current definition to Dune_rules
This PR should make it easier to "reverse" the dependency between `Action_builder` and `Build_system`, and then simplify the implementation of `Action_builder`. Additionally, it also makes the `Build_system` module a bit smaller.
=> Split-off Build_system.Alias

bin/print_rules.ml, src/dune_engine/alias.ml, src/dune_engine/alias.mli, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli
This was the only place it was used. This is again preparatory work to simplify `Action_builder` and this also makes `Build_system` smaller.
To do that I had to expose a few more functions from `Build_system`. It felt special to expose the most basic functionnality of the build system:`Build_system.build_file`.
=> Move Build_system.For_command_line to bin/print_rules.ml

otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/conv.ml, otherlibs/dune-rpc/private/conv.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_rpc_impl/server.ml
LSP supports multiple messages/locations for a single diagnostic. It
would be great if dune would send multiple locations in this format for
some errors. For example in:
* mli/ml mismatch errors
* duplicate {library,module,executable} errors
Related to #4670 which will extract such related error from ocaml compilation
commands
=> [RPC] support related messages in diagnostics

doc/concepts.rst, doc/usage.rst
=> Reference Merlin naming convention in copy rule documentation

bin/build_cmd.ml, src/memo/memo.ml, src/memo/memo.mli
The cycle detection timer has a big performance impact (~10% for incremental zero builds) and even when it's disabled it might have negative effect on the hot path in Memo, so it seems best to remove it and use `perf` for benchmarking & optimisation.
=> Remove the cycle detection timer

src/memo/memo.ml
We have two checks in `start_considering` and it makes sense to reorder them to make this function a bit faster on average:
* The `get_cached_value_in_current_cycle` is likely to succeed more often (because nodes often have multiple readers), in which case we can return `Finished cv` without looking at `dep_node.state`.
* In incremental (near) zero builds, there is little or no concurrency, so the `Considering` path should be happening pretty rarely, which justifies making it a bit slower (before this change, it required a single check, and now it will require two).
=> Reorder checks in Memo.start_considering

doc/concepts.rst
I hope I am not mistaken and this is indeed an error. I did have to change that in my `dune` files to make them do what I wanted.
=> fix typo in documentation: %{ocamlc-config} → %{ocaml-config}

src/dune_cache/local.ml, test/blackbox-tests/test-cases/dune-cache/basic-copy.t/run.t, test/blackbox-tests/test-cases/dune-cache/basic-hardlink.t/run.t
When fixing the issues due to partial restoration of artifacts from the cache in #4665, we accidentally reversed the list of targets, which led to storing incorrect entries to Dune database and subsequent workspace-local cache failures.
The first commit adds a test to catch such regressions in future and the second commit fixes the bug. To demonstrate this bug, the existing test case had to be extended from one to two targets (reversing a singleton list is a no-op).
=> Fix regression in zero builds

otherlibs/dune-rpc/private/dune_rpc_private.ml
The client wasn't registering the progress reporting handler callback
=> [RPC] Fix progress reporting

src/dune_engine/build_system.ml, src/memo/memo.ml, src/memo/memo.mli, src/memo/store.ml, src/memo/store.mli, src/memo/store_intf.ml, test/expect-tests/memo/memoize_tests.ml
We'd like to implement an RPC that makes it possible to "nudge" Dune to restart the build assuming that all files accesses need to be redone and all errors recomputed. Specifically, this PR adds:
* `Memo.Invalidation.clear_cache` to make it possible to invalidate a whole memoization table, such as `Fs_memo.memo`.
* `Build_system.error_cell` which is a dependency of all actions that raised errors: by invalidating this cell, we'll force Dune to rerun these actions.
There may be a slight performance cost because I moved the `Loc.is_none loc` check inside `Fiber.with_error_handler` to avoid wrapping the resulting fiber into another `Fiber.with_error_handler`. This seems acceptable.
=> Add functionality for [dune nudge] RPC

CHANGES.md, doc/dune-files.rst, src/dune_rules/coq_rules.ml
`mode native` seems broken with Coq master as it looks for `coq.kernel` whereas only `coq-core.kernel` is listed by ocamlfind.
=> Library coq.kernel replaced by coq-core.kernel in Coq >= 8.14

bin/build_cmd.ml, bin/exec.ml, bin/import.ml, bin/print_rules.ml, bin/printenv.ml, bin/top.ml, bin/utop.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/process.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli
This PR does the following:
- commit 1:
- To detect (and ignore) errors caused by cancellation, we pattern-match on the exception instead of inspecting the scheduler state. This means that it is now possible to keep seeing errors during cancellations, but those errors are "real" errors so are not problematic.
- Since we have that information in the exception, we don't need all these `report_error` callbacks whose purpose was to check if we're being cancelled.
- commit 2: 
- Use that information to suppress such errors from being reported over RPC
- commit 3:
- Move all error handling from `Scheduler.poll` to `Build_system.run` so that we don't have to keep synchronizing the two modules on how they handle errors.
- As a result, the non-polling build errors are now reported by …
=> Unify and simplify the error handling

otherlibs/dune-rpc/private/dune_rpc_private.ml
Client handlers should understand the build_event callback.
I changed the pattern matching on the handler to be exhaustive to
hopefully avoid issues like this in the future.
=> [RPC] client handler and build events

src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rpc_impl/server.ml
When a build is interrupted by cancellation or an error, report that
status to RPC
@aalekseyev I tried doing it via the scheduler handler, but it's not so easy
because the scheduler's handler doesn't allow for fiber operations. To
workaround this, I imagine that I'd need some sort of a queue with non blocking
`push`. It's a bit too complicated for this simple thing, so I just went back to
the hack. We can always revisit later.
=> Report interrupt/fail events to RPC

src/fiber/fiber.ml, src/fiber/fiber.mli, test/expect-tests/fiber/fiber_tests.ml
Like all all_concurrently, but doesn't allocate any lists.
I'm using this in lsp, but I imagine it would be useful in dune as well.
If it's accepted, I can add some tests for this.
=> [Fiber] add Fiber.parallel_all_unit

bin/rpc.ml
Prevent `dune rpc init --wait` from leaking threads by only calling `Scheduler.Worker.create ()` if there isn't currently a sleeping poll thread.
Signed-off-by: Cameron Wong <cwong@janestreet.com>
=> fix thread leak in --wait mode

src/dune_engine/build_system.ml, test/blackbox-tests/test-cases/aliases.t/dune, test/blackbox-tests/test-cases/aliases.t/run.t
I noticed that Dune can produce error messages like "Error: No rule found for alias alias foo" (with duplicated word "alias"). This PR fixes the duplication and adds some tests.
=> Fix error message for unknown aliases, add tests

src/dune_engine/scheduler.ml, src/memo/memo.ml, src/memo/memo.mli, src/upgrader/dune_upgrader.ml, test/expect-tests/memo/memoize_tests.ml
Building on `Store.iter` introduced in #4719, we use a more principled approach when clearing Memo caches: before dropping all of their contents, we traverse each table and invalidate the contained nodes. This makes sure that nodes that we hold on to via `lazy_` or `cell` references are invalidated too.
=> Fix a bug in [Memo.clear_caches]

src/dune_engine/scheduler.ml
This PR does two things:
- Refactor `Scheduler.Event.Queue.next` so we have a tangible list of event sources instead of a large function where the level of indentation roughly determines the priority.
I think this way it's clearer what's going on. I'm not too worried about allocation of these closures because scheduler events are not supposed to be very numerous.
- Then swap the order of `worker_tasks_completed` and `jobs_completed` in this list.
This is simply to make the priority order make more sense, not really fixing any issue I observed.
The reason I'm looking into this is that I wanted to use the `worker_tasks_completed` mechanism for inotify watcher and there we clearly want the same-ish priority as `invalidation`.
=> Rpc higher priority than build jobs

CHANGES.md, otherlibs/stdune-unstable/path.ml
Currently, `Path.Local_gen.parse_string_exn` has a fast path for when the argument is already "canonical", see
https://github.com/ocaml/dune/blob/26f5e57d1aef71f476a6dc40990b9d6a517f7849/otherlibs/stdune-unstable/path.ml#L341-L347
The function `is_canonicalized` checks a number of conditions such as whether there are two slashes in a row, etc. However, I think on Windows it should also check for the presence of backslashes since these are not canonical (a value of type `Path.Local.t` is represented with forward slashes only).
This PR should fix #4717 which is blocking the use of `merlin` on Windows when using `(include_subdirs unqualified)`. It would be fantastic if we could get this in 2.9.
Fixes #4717
=> Path.Local: backslashes are not canonical on Windows

CHANGES.md, src/stdune/path.ml
=> [2.9-backport] Path.Local: backslashes are not canonical on Windows (#4745)

test/blackbox-tests/test-cases/public_name-exe.t/example.ml, test/blackbox-tests/test-cases/public_name-exe.t/run.t
bsd sed (on macos) doesn't allow -i to work with symlinks
=> Fix tests with bsd sed

CHANGES.md, src/dune_rules/coq_module.ml, src/dune_rules/coq_rules.ml, test/blackbox-tests/test-cases/coq/native-compose.t/bar/dune, test/blackbox-tests/test-cases/coq/native-compose.t/foo/a/a.v, test/blackbox-tests/test-cases/coq/native-compose.t/foo/dune, test/blackbox-tests/test-cases/coq/native-compose.t/run.t
=> [coq] Fix silly bug in native install rules when non-trivial wrappers are used

CHANGES.md, bin/install_uninstall.ml, configure.ml, doc/usage.rst, src/dune_engine/install.ml, src/dune_engine/install.mli, src/dune_rules/artifact_substitution.ml, src/dune_rules/artifact_substitution.mli, src/dune_rules/setup.defaults.ml, src/dune_rules/setup.mli, test/blackbox-tests/test-cases/install-docdir.t/run.t, test/blackbox-tests/test-cases/install-etcdir.t/run.t
Fixes #4723
This is an important fix for those using Dune to build, for example,
Debian packages, as docdir is there `prefix/share/doc/package`,
similarly for `etc`.
Thus, I request for approval to ship this in 2.9.
I have written the patch very conservatively, as to allow easy
backporting, but once we release 2.9 it would be convenient to
refactor this code so overridable directories are placed into a
record.
=> [install] Allow users to specify docdir and etcdir

CHANGES.md, src/dune_rules/coq_rules.ml, src/dune_rules/env_node.ml, src/dune_rules/env_node.mli, src/dune_rules/super_context.mli, test/blackbox-tests/test-cases/coq/env.t
This is very subtle and I am not sure I do understand all the
subtleties here, but moving the expansion to the inheritance function
seems like the right thing to do.
Added almost exhaustive test cases.
Closes #4566
=> [coq] Fix computation of profile flags.

test/blackbox-tests/test-cases/coq/flags.t
This wasn't done in the past as to avoid the ugly grep, but the flag
logic is delicate so we must start testing it properly.
=> [coq] Add test cases for flags

CHANGES.md, doc/dune-files.rst, src/dune_rules/coq_rules.ml
backport of #4713
Signed-off-by: Pierre Roux <pierre.roux@onera.fr>
=> [2.9] [coq] Library coq.kernel replaced by coq-core.kernel in Coq >= 8.14

CHANGES.md, src/dune_rules/coq_rules.ml, src/dune_rules/env_node.ml, src/dune_rules/env_node.mli, src/dune_rules/super_context.mli, test/blackbox-tests/test-cases/coq/env.t, test/blackbox-tests/test-cases/coq/flags.t
=> [2.9] [coq] Fix computation of profile flags

CHANGES.md, src/dune_rules/coq_module.ml, src/dune_rules/coq_rules.ml, test/blackbox-tests/test-cases/coq/native-compose.t/bar/dune, test/blackbox-tests/test-cases/coq/native-compose.t/foo/a/a.v, test/blackbox-tests/test-cases/coq/native-compose.t/foo/dune, test/blackbox-tests/test-cases/coq/native-compose.t/run.t
Cherry-picked from #4750 ; submitting separately as this has been included already in 2.9.
=> [coq] Fix silly bug in native install rules when non-trivial theory wrappers are used

CHANGES.md, src/dune_rules/coq_rules.ml, test/blackbox-tests/test-cases/coq/flags.t
This is due to the rework of the Coq "native" compilation system in
8.14.
Note that as in `(lang coq 0.3)` and upwards, this requires Coq >=
8.10.
Targeting 2.9 due to low risk and high annoyance for users of Coq 8.14 + `(coq lang 0.3)`
=> [coq] Adjust warnings on Coq 8.14 and `(lang coq (>= 0.3))`

src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
While we are actively working on Memo, it's useful to keep track of the size of the cycle detection graph. In future, we might turn this metric off, or only print it in machine-readable format when requested, but for now it seems OK to print it with other metrics printed by the `--print-metrics` flag.
This PR also fixes a slight inaccuracy when counting considered nodes: previously, we didn't count "stale" computation nodes, i.e. nodes that we tried to restore from cache, which failed, but never tried to compute because they became unreachable. Now we count such stales nodes too.
=> Add counters for Memo's cycle detection graph

CHANGES.md
A few PRs were backported later so we need to move the changelog in
`main` to the 2.9 slot.
Note that `CHANGES` previous to 2.9 don't seem to be consistent with
`main`, likely due to the same phenomenon.
=> [changes] Sync with 2.9 branch

otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli
This requires adding a `finalize` function in the `Client` functor
=> [RPC] always close channel after client callback

CHANGES.md, src/dune_rules/super_context.ml, test/blackbox-tests/test-cases/workspaces.t/run.t
=> [coq] Display coq env flags in `dune printenv`

CHANGES.md, src/dune_rules/preprocess.ml, src/dune_rules/preprocess.mli, test/blackbox-tests/test-cases/instrumentation.t/run.t, test/blackbox-tests/test-cases/instrumentation.t/trivial_ppx/dune, test/blackbox-tests/test-cases/instrumentation.t/trivial_ppx/dune-project, test/blackbox-tests/test-cases/instrumentation.t/trivial_ppx/trivial_ppx.ml
Should fix https://github.com/ocaml/dune/pull/3932#discussion_r657127990
=> Bugfix: only add instrumentation flags if instrumentation enabled

otherlibs/site/test/bug_4219.t
It was missing EOF end markers
=> Fix test bug_4219.t

bin/diagnostics.ml, bin/rpc.ml, bin/shutdown.ml, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_rpc_impl/run.ml, src/dune_rpc_impl/run.mli, test/expect-tests/dune_rpc/dune_rpc_tests.ml
It's not longer necessary as we have a proper way to handler incoming
notifications from the server.
=> [RPC] Remove Client.connect_raw

otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml, src/dune_rpc_impl/where.ml
It is possible that a file could be created after Sys.file_exists but
before Unix.stat. In which case, an incorrect result will be returned.
This PR changes analyze_path to only rely on Unix.stat
@aalekseyev It's not the race you've encountered, but it's good to fix anyway.
=> [RPC] fix another race in analyze_path

boot/libs.ml, src/dune_engine/compound_user_error.ml, src/dune_engine/compound_user_error.mli, src/dune_engine/dune, src/dune_engine/process.ml, src/ocamlc_loc/dune, src/ocamlc_loc/ocamlc_loc.ml, src/ocamlc_loc/ocamlc_loc.mli, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml, test/expect-tests/ocamlc_loc/dune, test/expect-tests/ocamlc_loc/ocamlc_loc_tests.ml
Starting to address #4668.
Some issues right off the bat:
- Do we try to parse the structured nature of OCaml errors? See the 2nd test for
an example where sub-errors are present. Currently, I treat these as separate
errors. In LSP, there's no way to reflect the nesting of errors anyway.
- It's a bit of a hassle to parse errors with `--no-buffer`. It would require us
to redirect stdout/stderr manually as we'll need to feed this into the parser
as well. Perhaps we can just skip error parsing when `--no-buffer` is on?
=> Introduce library to parse ocamlc errors

bin/rpc.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, test/expect-tests/dune, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml, test/expect-tests/timer_tests.ml
Allow waiting for a duration to elapse before resuming a fiber
=> [Scheduler] add timer mechanism

src/dag/dag.ml, src/dag/dag.mli, src/dag/dag_intf.ml, src/memo/memo.ml, src/memo/once.ml, src/memo/once.mli, test/expect-tests/dag/dag_tests.ml, test/expect-tests/memo/memoize_tests.ml
The main idea behind the optimisation is as follows. Cycles can only appear when we subscribe to a `Once.t` computation that is currently running, because that's where multiple threads of computation might deadlock waiting for each other to complete. To prevent such deadlocks, it is sufficient to only add the edges that lead to such "subscribing" edges to the cycle detection graph. All other edges can be skipped. This can reduce the number of edges in the cycle detection graph significantly. In particular, we no longer add the edges that force `Once.t` computations for the first time. This means that when doing an incremental zero rebuild, we are not going to add any edges to the cycle detection graph at all, because there is no build parallelism and we are never going to subscribe to a …
=> Reimplement Memo cycle detection

src/dune_rules/dune_file.ml, test/blackbox-tests/test-cases/instrumentation.t/run.t, vendor/ocaml-inotify/src/inotify_stubs.c
- `unistd.h` does not exist on Windows (in `inotify_stubs.c`)
- fix version check for a feature that was backported to 2.9
=> A couple of tiny tweaks

src/dune_rules/lib.ml, test/blackbox-tests/test-cases/dune-ppx-driver-system.t/run.t
Unique id's are getting in the way of memoizing the Lib module
=> Remove unique_id from libraries

src/memo/memo.ml
The `build` type alias is unimportant anyway, so moving it to the end of the file seems appropriate.
=> Help Merlin to show better types in [memo.ml]

bin/common.ml, test/blackbox-tests/test-cases/watching/test-1.t/run.t, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml, vendor/cmdliner/src/cmdliner_cline.ml
... to avoid delving into deep corners of cmdliner.
Also, revert our cmdliner patch.
=> Rename [--watch=passive] into [--passive-watch-mode]

src/memo/memo.ml, src/memo/memo.mli, src/memo/once.ml, src/memo/once.mli, test/expect-tests/memo/memoize_tests.ml
As agreed in #4756, this PR stops reusing DAG nodes for different phases.
=> Stop reusing DAG nodes for restore and compute

test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
Treat `Sys_error` as EOF when reading from fd.
Should be harmless to ignore this.
=> [RPC] improve end to end tests

otherlibs/dune-rpc/private/dune_rpc_private.ml, src/dune_rpc_impl/run.ml, test/blackbox-tests/utils/dune_cmd.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
We are creating the symlink before the actual socket. Which means that it is possible for the client to observe a dead link. This PR changes the code to create the socket first.
=> Rpc symlink creation race

editor-integration/emacs/dune.el
Fix for https://github.com/ocaml/dune/pull/4222 the regex is not correct.
```lisp
;; Original regex
;; NOTE 0 is true and nil is false (roughtly speaking)
(string-match "\\(?:\\`\\|/\\)dune\\(?:\\.inc\|-project\\)?\\'" "dune")
0
(string-match "\\(?:\\`\\|/\\)dune\\(?:\\.inc\|-project\\)?\\'" "dune.inc")
nil
(string-match "\\(?:\\`\\|/\\)dune\\(?:\\.inc\|-project\\)?\\'" "dune-project")
nil
;; New regex
(string-match "\\(?:\\`\\|/\\)dune\\(?:\\.inc\\|\\-project\\)?\\'" "dune")
0
(string-match "\\(?:\\`\\|/\\)dune\\(?:\\.inc\\|\\-project\\)?\\'" "dune.inc")
0
(string-match "\\(?:\\`\\|/\\)dune\\(?:\\.inc\\|\\-project\\)?\\'" "dune-project")
0
(string-match "\\(?:\\`\\|/\\)dune\\(?:\\.inc\\|\\-project\\)?\\'" "dune-project.inc")
nil
(string-match …
```
=> Fixup autoload regex for Emacs.

CHANGES.md, src/dune_rules/findlib/meta.ml
=> Meta: add support for ocamldoc pseudo-package

CHANGES.md, otherlibs/site/test/run.t, src/dune_rules/opam_create.ml
Introduced in Dune 2.9, Opam files are now generated with this line:
```
build: [
["dune" "subst" "--root" "."] {dev}
```
This was added in commit 88d8b0e199f7a9d6a805bba5c98022fd37e19a7e in PR #4730. 
The author probably forgot that Dune doesn't have the `subst --root .` option. Amusingly, an earlier issue refers to this problem:
> Oh no, sorry, I should have been clearer. It was really that in the futur we generate with the `--root .`, (I forgot dune was generating that). It is a regression that must be fixed.
> 
> And thank you for pointing that `dune subst` doesn't have contrary to the other command a `--root` option.
_Originally posted by @bobot in https://github.com/ocaml/dune/issues/4043#issuecomment-746465438_
As I see it, using Opam files generated by **Dune 2.9 only** is now …
=> [2.9] Opam file generation is broken: don't use `subst --root` in Opam files

src/dune_engine/package.ml, src/dune_engine/package.mli, src/dune_lang/encoder.mli
Adds an `encode` function for package data, as a prerequisite of adding an `encode` function for `Dune_project.t`,
- Towards #4702 
- Prerequisite of #4367
I'm starting with a small chunk of the encoding, so I can get feedback in case I'm going about this wrong.
I could particularly use advise on where/whether I should test this: It will ultimately get tested via black box tests, but seems the `encode` function itself could use some testing. But I haven't found clear precedent for testing `encode` functions in the current tests.
=> Add encode function for Package.t

src/memo/memo.ml, test/expect-tests/memo/memoize_tests.ml
We increment `edges_traversed` twice: in `Deps.changed_or_not` and also in the function `f` that we pass to it. This PR fixes it.
=> Stop double-counting traversed edges in Memo metrics

src/memo/memo.ml
This makes creating `Computation`s a bit cheaper: instead of creating a lazy node with a closure holding a `dep_node`, we provide the `dep_node` when forcing our ad-hoc `Lazy_dag_node`.
Microbenchmarks show slightly better allocations across all scenarios (and also slightly better performance).
I also made a couple of tweaks to `State`-handling. These tweaks didn't have an effect on the microbenchmarks.
```
┌────────────────────────────────────┬──────────────┬─────────────┬───────────┬───────────┬────────────┐
│ Before                             │     Time/Run │     mWd/Run │  mjWd/Run │  Prom/Run │ Percentage │
├────────────────────────────────────┼──────────────┼─────────────┼───────────┼───────────┼────────────┤
│ 1-bind (create and compute)        │     497.86ns │     608.00w │ …
```
=> Switch to ad-hoc lazy DAG nodes

src/dune_file_watcher/dune, src/dune_file_watcher/dune_file_watcher.ml, src/dune_rules/mdx.ml
Since the proper solution to not-retriggering-on-hgignored-file-changes
continues to elude us, we can start with a hacky one:
bring back the event filtering that we used in the
external backends.
This PR does that.
Testing
-------
Manual testing: ran dune in watching mode while editing files, saw
that dune only retriggers when you save the files, not when you
start editing them.
=> Dune file watcher: use exclude patterns

otherlibs/stdune-unstable/dune_filesystem_stubs/readdir.c
Looks like in readdir we're not handling the errors as man page says we should.
Fix that. It should not matter much in theory because the only possible error described in the man page is EBADF, which is a bug in the user code rather than the filesystem condition. However, we've seen some evidence that suggests this function may be returning errors in practice, so let's report those correctly.
By the way, this issue is also present in the OCaml unix library.
=> fix error handling in readdir C binding

CHANGES.md, src/dune_rules/gen_meta.ml, test/blackbox-tests/test-cases/private-package-lib.t/run.t
=> Fix META generation for private libs.

src/dune_engine/build_system.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/run_with_error_handler.ml
This shouldn't change any existing behavior as far as I know since I don't know any examples of `f` that raise exceptions, but as a general code cleanup it's much less surprising if the exceptions raised by f are treated the same as the exceptions raised inside the Memo.Build.t
=> Build_system.run: catch the exceptions raised by f

doc/tests.rst
Explain why dune doesn't support output matching
=> [doc] Add a comment about re/glob matching

.github/workflows/workflow.yml
> And of course, if you are still referencing avsm/setup-ocaml in your
> own workflow definition, this is a good time to change it to
> ocaml/setup-ocaml.
https://discuss.ocaml.org/t/github-actions-for-ocaml-now-stable-and-on-the-ocaml-org/7889
=> setup-ocaml new home is under ocaml/

doc/concepts.rst
Noticed this grammatical error while reading documentation, thought I would make a pull request!
This is my first pull request, so please let me know if I missed something
This is the offending documentation page:
=> grammar change, there -> their

src/csexp_rpc/csexp_rpc.ml
The RPC server accepts on a non blocking socket, which yields us non
blocking clients. Sessions expect a blocking fd however, and so this
made dune rpc spin on reads from the rpc client fd. To fix the issue, we
clear the blocking flag on newly accepted connections.
@voodoos should fix the cpu pinning
=> [RPC] fix cpu spinning

otherlibs/site/test/run.t, src/dune_rules/opam_create.ml, test/blackbox-tests/test-cases/dune-project-meta/main.t/run.t
replace "--promote-install-files false" by "--promote-install-files=false" since it is more likely it will work in the futur
=> [Cmdline] create more futur proof opam file

CHANGES.md, src/dune_engine/pform.ml, src/dune_engine/pform.mli, src/dune_rules/expander.ml
@toots is erroring out when the toolchain isn't defined ok for you?
=> Add %{toolchain} variable

src/dune_engine/scheduler.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/dune_rpc_e2e/dune, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
For some reason this breaks error reporting with RPC (it now reports stale errors). Investigating as to what the cause is.
=> Turn on incremental memo by default

otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml, otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.mli, otherlibs/dune-rpc/dune_rpc.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/conv.ml, otherlibs/dune-rpc/private/conv.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, otherlibs/dune-rpc/private/types.ml, otherlibs/dune-rpc/private/types.mli, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_rpc_impl/client.ml, src/dune_rpc_impl/diagnostics.ml, src/dune_rpc_impl/long_poll.ml, src/dune_rpc_impl/long_poll.mli, src/dune_rpc_impl/poll_spec.ml, src/dune_rpc_impl/server.ml, src/dune_rpc_server/dune_rpc_server.ml, src/dune_rpc_server/dune_rpc_server.mli, src/dune_util/log.ml, src/dune_util/log.mli, test/expect-tests/dune_rpc/dune, test/expect-tests/dune_rpc/dune_rpc_tests.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.mli, test/expect-tests/fiber/fiber_tests.ml
This PR introduces a new subscription mechanism with the following advantages:
* Consistent API to subscribe and unsubscribe
* A way to terminate a subscription from the server side
* Multiple subscriptions of the same type per connection (not useful yet)
* Formalizes the pattern of returning the initial value along with the subscription.
* Server API to define new types of things to subscribe for.
I've yet to use the new API for our current subscriptions. I'd like to get a round of review for the API first.
=> RPC - New subscription mechanism

test/blackbox-tests/test-cases/mdx-stanza/enabled-if.t/iffalse.md, test/blackbox-tests/test-cases/mdx-stanza/enabled-if.t/iftrue.md, test/blackbox-tests/test-cases/mdx-stanza/linked-libraries.t/README.md, test/blackbox-tests/test-cases/mdx-stanza/local-package.t/README.md, test/blackbox-tests/test-cases/mdx-stanza/new-deps-field.t/README.md, test/blackbox-tests/test-cases/mdx-stanza/preludes.t/README.md
Starting from mdx.1.11.0, toplevel phrases without termintating `;;` are deprecated in toplevel blocks.
Some of MDX stanza tests were lacking the semi-colons, triggering a warning from MDX. It's not a breaking change for regular users but it shows up in `dune runtest` output and therefore breaks the cram tests for the MDX stanza.
=> Add trailing `;;` in MDX code blocks for forward compat with mdx >= 1.11.0

otherlibs/stdune-unstable/temp.ml
omit empty suffixes or prefixes
=> [stdune] prettier temp paths

CHANGES.md, plugin/jbuild_plugin.ml, src/dune_rules/assets.ml
=> Use Toploop.add_directive

otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml, otherlibs/dune-rpc-lwt/test/dune, otherlibs/dune-rpc-lwt/test/dune_rpc_lwt_tests.ml, otherlibs/dune-rpc-lwt/test/realpath_stubs.c, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/where.ml, otherlibs/dune-rpc/private/where.mli, src/csexp_rpc/csexp_rpc.ml, src/csexp_rpc/dune, src/csexp_rpc/pthread_chdir_stubs.c, src/dune_rpc_impl/run.ml, src/dune_rpc_impl/where.ml
As discussed, use bindat/connectat on *nix and __pthread_chdir on macos.
EDIT: looks like bindat/connectat is BSD only. Fortunately, it appears that we don't need the hack at all on Linux as the temp paths in the tests are short enough.
=> Remove all the symlink hackery

otherlibs/dune-rpc/private/dune_rpc_private.ml
I should have caught this earlier. It doesn't actually change any observable behavior, but is probably a good change to make for hygiene's sake anyway.
Signed-off-by: Cameron Wong <cwong@janestreet.com>
=> [RPC] fix handling of post-versioning aborts

otherlibs/dune-rpc/private/where.ml
Rename From rpc to .rpc. So it makes it possible to have a context named
"rpc"
=> [RPC] rename socket dir

otherlibs/stdune-unstable/list.ml, src/memo/memo.ml
This is a follow-up to #4926.
As discussed, we are now going to print a message when the reason for restarting Dune is unknown, encouraging the user to report this as a bug.
I also fixed a bug in `List.truncate` which marked the result as "truncated" when `max_length` was equal to the length of the original list.
=> Print a message when the reason for restarting is unknown

CHANGES.md, src/dune_rules/inline_tests.ml, src/dune_rules/inline_tests_info.ml, src/dune_rules/inline_tests_info.mli, test/blackbox-tests/test-cases/inline_tests/enabled-if.t
This is an improvement over enabled_if on the library itself as it still
allows to compile the library.
=> Add enabled_if to running inline_tests

otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/conv.ml, otherlibs/dune-rpc/private/conv.mli, otherlibs/dune-rpc/private/dbus_address.mll, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/where.ml, test/expect-tests/dune_rpc/dune_rpc_tests.ml
Allow converters to signal errors by returning result
Fix #4915
=> Remove failwith from dunerpc

src/dune_engine/scheduler.ml, src/memo/memo.ml, src/memo/memo.mli
After adding proper diagnostics for restarts, we no longer need some debugging code guarded by `if false`, so I'm deleting it to simplify things a bit. 
Also fixed a silly typo (`Test` vs `Unknown`) to bring code and comments in sync.
=> Minor clean up of [Memo.Invalidation]

bin/build_cmd.ml, otherlibs/stdune-unstable/digest.ml, otherlibs/stdune-unstable/digest.mli, otherlibs/stdune-unstable/metrics.ml, otherlibs/stdune-unstable/metrics.mli, src/fiber/fiber.ml, src/fiber/fiber.mli
Changes metrics module to take in a string tag when recording metrics. Measurements are aggregated in a persistent map which is printed out at the end of a build. This makes it easier to add new timers as you don't need to expose the timer object to the build command.
Sample output:
```
Memo graph: 2/280162 restored/computed nodes, 663573 traversed edges
Memo cycle detection graph: 52313/86840/73878 nodes/edges/paths
(52.23s total, 68.0M heap words)
Timers:
generic_digest - time spent = 0.19s, count = 34536
```
=> More flexible metrics collection

src/ocamlc_loc/ocamlc_loc.ml, src/ocamlc_loc/ocamlc_loc.mli, test/expect-tests/ocamlc_loc/ocamlc_loc_tests.ml
Warning payloads are entirely optional.
Should fix the issue. Let me know if this is broken on any other version of the compiler.
=> Fix ocamlc loc parsing in 4.11

src/dune_rpc_impl/import.ml, src/dune_rpc_impl/long_poll.ml, src/dune_rpc_impl/poll_spec.ml, src/dune_rpc_impl/server.ml
This fixes the issues with end-of-build progress reporting over the RPC.
First, the final `Success` event is often dropped. This is due to that event being sent in quick succession to the last progress event (in which `remaining` is 0) being sent -- any active long poll requests will receive the `In_progress` event, then there's a very narrow window for a new request to arrive before the `Success`. In most cases I could try, even with tight scheduling control, the `Success` was always being sent to zero waiting clients, and any subsequent polls hit the next issue.
Secondly, progress updates are edge-triggered, meaning that they are only sent out when the value is changed. This means that if a request arrives during a time where the build status is the same for a long time (i.e., when the …
=> [RPC] Fix end-of-build reporting via [Progress]

src/dune_rpc_impl/run.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_registry_test.ml
Always print socket paths as absolute
=> [rpc] Fix registry paths

src/dune_engine/build_system.ml, src/dune_engine/target_promotion.ml, src/dune_engine/target_promotion.mli, test/blackbox-tests/test-cases/promote/old-tests.t/run.t
This PR does a few things without changing existing behaviour:
* Instead of recomputing target digests, we reuse the digests that are already available after executing a rule. This is useful for an upcoming PR that implements promotion for directory targets (we won't need to recursively traverse the directories again).
* Add a few comments documenting ideas for further improvement.
* Add a test to ensure that promoted targets are restored when deleted or modified by the user. Also clarify the behaviour of another existing test.
* Move around some code to make the main target promotion logic more visible.
=> Refactor target promotion and add more docs/tests 

test/blackbox-tests/test-cases/display.t
As can be seen, we are often still displaying the line that comes from `--display short`, which feels somewhat wrong.
=> Add a test documenting various display modes of Dune

test/blackbox-tests/test-cases/promote/dep-on-promoted-target.t/run.t, test/blackbox-tests/test-cases/promote/old-tests.t/run.t, test/blackbox-tests/test-cases/watching/target-promotion.t
I'm making some changes around the target promotion logic, so I'd like to add some more tests.
Note that this reveals a bug in the file-watching mode.
=> Add more tests for the current behaviour of target promotion

src/dune_rules/lib.ml, test/blackbox-tests/test-cases/default-implementation/package-mismatch1.t/run.t, test/blackbox-tests/test-cases/deprecated-library-name/features.t, test/blackbox-tests/test-cases/enabled_if/eif-context_name.t/run.t, test/blackbox-tests/test-cases/enabled_if/eif-ocaml_version.t/run.t, test/blackbox-tests/test-cases/enabled_if/eif-simple.t/run.t, test/blackbox-tests/test-cases/exec-missing.t/run.t, test/blackbox-tests/test-cases/forbidden_libraries.t/run.t, test/blackbox-tests/test-cases/foreign-library.t/run.t, test/blackbox-tests/test-cases/github1541.t/run.t, test/blackbox-tests/test-cases/lib.t/run.t, test/blackbox-tests/test-cases/libexec.t/run.t, test/blackbox-tests/test-cases/optional-executable.t/run.t, test/blackbox-tests/test-cases/optional.t/run.t, test/blackbox-tests/test-cases/ppx-runtime-dependencies.t/run.t, test/blackbox-tests/test-cases/virtual-libraries/impl-not-virtual.t/run.t
Thanks to #5075 and #5047, we can now easily provide more information for some library resolution errors. I think it's pretty helpful to tell the user why the problematic library was required. In fact, in one of the tests, this was suggested as a future improvement.
We could only do this for a subset of errors in this module, but after studying the new error messages, I think all of them got better.
=> Attach stack traces to library resolution errors

CHANGES.md, src/dune_engine/fs_memo.ml, src/dune_file_watcher/dune_file_watcher.ml, src/dune_file_watcher/dune_file_watcher.mli, src/fsevents/bin/dune_fsevents.ml, src/fsevents/dune, src/fsevents/fsevents.ml, src/fsevents/fsevents.mli, src/fsevents/fsevents_stubs.c, test/expect-tests/dune_file_watcher/dune_file_watcher_tests_linux.ml, test/expect-tests/fsevents/fsevents_tests.ml
Allow to create multiple fsevents watchers and receive all the events in one thread. This is a pre-req for watching external directories.
=> FSEvents: multiple watchers

test/blackbox-tests/test-cases/watching/copy-rules.t
Another test for file-watching mode, and another subtle bug: copy rules don't seem to interact well with `promote-into`.
I suspect the plain `promote` logic is broken too but it's masked by the fact that Dune sees the promoted files in the build directory. With the `into` option, the corresponding file is in a different directory and there is nothing to mask the bug.
=> Add a test for copy rules in file-watching mode

src/dune_engine/build_system.ml, src/dune_engine/fs_memo.ml, test/blackbox-tests/test-cases/dune-cache/mode-copy.t/run.t, test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t/run.t, test/blackbox-tests/test-cases/watching/test-1.t/run.t
This just makes it easier to debug.
=> Print --debug-cache messages without --verbose

CHANGES.md, src/dune_lang/syntax.ml, test/blackbox-tests/test-cases/lang-dune-warning.t
Syntax versions (the string after `lang dune` for example) are parsed with `Scanf.sscanf`. This only parses the longest matching prefix and ignored the rest of the string. So `lang dune 2.3.0` is silently interpreted as `2.3` and so is `lang dune 2.4suffix`.
This PR adds a warning when there is a suffix. An error could break existing projects.
The implementation adds a `%s` to match the suffix. This specifier stops on whitespace characters, but these can not appear in valid atoms.
=> Warn when lang versions have an ignored suffix

src/dune_engine/action.ml, src/dune_engine/action.mli, src/dune_engine/action_builder.ml, src/dune_engine/build_system.ml, src/dune_engine/rule.ml, src/dune_engine/rule.mli, src/dune_engine/rules.ml, src/dune_engine/rules.mli, src/dune_rules/context.ml, src/dune_rules/dune_file.ml, src/dune_rules/dune_file.mli, src/dune_rules/simple_rules.ml, src/dune_rules/simple_rules.mli, src/dune_rules/super_context.ml, src/dune_rules/super_context.mli, src/dune_rules/test_rules.ml, test/blackbox-tests/test-cases/dune-cache/mode-copy.t/run.t, test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t/run.t, test/blackbox-tests/test-cases/dune-cache/repro-check.t/run.t, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t, test/blackbox-tests/test-cases/patch-back-source-tree.t
Morally, this is a property of the action rather than the rule.
=> Move patch_back_source_tree an action property rather than a rule one

CHANGES.md, doc/dune-files.rst, src/dune_rules/dune_file.ml, test/blackbox-tests/test-cases/promote/promote-foo-deleted.t
We planned to delete the `promote-foo` syntax in Dune 2 but forgot. Let's do this now.
=> Delete [promote-foo] syntax in favour of [promote foo]

src/dune_rules/cram_exec.ml, test/blackbox-tests/test-cases/github3857.t, test/blackbox-tests/test-cases/menhir/promote.t/run.t, test/blackbox-tests/test-cases/meta-template-version-bug.t
tests shouldn't be able to observe the test files
Fix #4776
=> fix(cram): remove cram file after it is read

test/blackbox-tests/test-cases/watching/watching-dot-files.t
Which is a problem when a rule depend on a dot files.
And for the facepalm effect: dot files are watched iff they are at the root.
=> Add a test demonstrating that Dune doesn't watch dot files

src/dune_file_watcher/dune_file_watcher.ml, test/blackbox-tests/test-cases/watching/watching-dot-files.t
Less ambitious version of #5094. We still want #5094, but we'll have to change a few more things before we can go ahead with this. This PR will do in the meantime.
-----
Only ignore events about .#... files.
Also remove a stale comment about inotifywait that we don't use
anymore.
=> Don't ignore all events about dot files

src/dune_engine/build_system.ml, test/blackbox-tests/test-cases/reporting-of-cycles.t/run.t
The test added in #5039 bothered me due to inconsistent capitalisation, so I fixed it.
=> Fix capitalisation in "evaluating predicate..." message

bench.Dockerfile, bench/bench.ml
- The PR is primarily an update to the benchmarking JSON schema to v2 to allow specifying units for the metrics.
- There's a second PR which removes an unnecessary duplicated `make bench` run from the `bench.Dockerfile`.
=> Upgrade bench json version

doc/dune-files.rst
it is introduced in 3.0 rather than 2.9
cc @hhugo
=> doc: fix minimum version for empty intf generation

test/blackbox-tests/test-cases/watching/retriggering.t
I was super confused by seeing `Failure` from the RPC when the build was in fact merely re-triggering. It costed me quite a bit of time to figure out what's going on. So, I'm adding a test to demonstrate the current behaviour along with a CR-somday to fix it if everyone agrees.
=> Test Dune RPC behaviour in the case of re-triggering

test/blackbox-tests/test-cases/subdir-stanza/basic.t, test/blackbox-tests/test-cases/watching/basic.t
I also moved the basic tests out of the separate subdirectory.
With the new name, building `@basic` runs both `subdir-stanza/basic.t` and `watching/basic.t`. I wonder: is it possible to tell Dune to build just one of them? I tried `@watching/basic` and (unsurprisingly) this didn't work. I don't think there is much point in trying to avoid name collisions, since in the long run it's hardly possible.
=> Reuse helpers.sh in basic file-watching tests

bin/rpc.ml, src/dune_engine/build_system.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_rpc_impl/decl.ml, src/dune_rpc_impl/decl.mli, test/blackbox-tests/test-cases/watching/retriggering.t
Following up on #5103, I'm adding a new `Build_outcome_for_rpc` called `Restart`. I think this makes the behaviour less surprising.
I guess the clients will need to be changed to accept the new outcome. Do we need to bump some RPC version?
=> Add a new RPC outcome [Restart]

test/blackbox-tests/test-cases/watching/quick-cancel.t
Another hotfix for the file-watching testsuite following #5108.
=> Fix a non-deterministic file-watching test

CHANGES.md, doc/tests.rst, src/dune_rules/inline_tests.ml, src/dune_rules/inline_tests_info.ml, src/dune_rules/inline_tests_info.mli
This adds the field and updates the documentation. I wasn't sure if/how I should add tests.
I tested this on a project by using the flag and inspecting dune's logs to verify that the link flags made it to the `ocamlopt` command for the test runner (also tested the `(:include <file>)` syntax).
=> add link_flags field to inline_tests

bin/common.ml, src/dune_config/dune_config.ml, src/dune_engine/action.ml, src/dune_engine/action.mli, src/dune_engine/build_system.ml, src/dune_engine/sandbox.ml, src/dune_engine/sandbox.mli, src/dune_engine/sandbox_mode.ml, src/dune_engine/sandbox_mode.mli, src/dune_rules/simple_rules.ml, test/blackbox-tests/test-cases/dune-cache/mode-copy.t/run.t, test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t/run.t, test/blackbox-tests/test-cases/dune-cache/repro-check.t/run.t, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
Since this is really what it is. The code seems more natural this way as well.
I ended up removing the invariant on `Action.Full.t` and convinced myself it is Ok. Instead, in `execute_rule` we force `can_go_in_shared_cache = false` if the selected sandboxing mode is `Some Patch_back_source_tree`.
In the end, it seems to me that not having the invariant on `Action.Full.t` simply means that we might end up creating more cache entries than necessary if we change the (ignored) `can_go_in_shared_cache` field of an action that has `sandbox = Sandbox_mode.singleton (Some Patch_back_source_tree)`, which doesn't seem terrible.
=> Make patch_back_source_tree a sandboxing mode.

test/blackbox-tests/test-cases/patch-back-source-tree.t
It seems that the internal action stamp file is created inside the sandbox and then copied to the source tree.
=> Expose a bug related to patch-back-source-tree and the action stamp file

bin/common.ml, src/dune_config/dune_config.ml, src/dune_engine/sandbox_mode.ml, src/dune_engine/sandbox_mode.mli
That were used to parse the config file. This is so that we don't accidentally add new values without versioning them in the future.
=> Replace a few of_string functions by decode functions

src/dune_engine/build_system.ml, src/dune_engine/sandbox.ml, src/dune_engine/sandbox.mli, src/dune_engine/targets.ml, src/dune_engine/targets.mli
Since it might create an empty `Targets.t`
=> Remove Targets.remove_file

Makefile, doc/dune-files.rst
fixes doc indentation issue reported here https://github.com/ocaml/dune/pull/3905#discussion_r739044538
updates sphinx-autobuild command-line arguments (-p and -r were removed in later versions)
=> Fix "Linking Modes" so that it's not a top-level section

test/blackbox-tests/test-cases/watching/retriggering.t
I noticed that this test failed for me a couple of times with the `build` returning `Success` instead of `Restart`. The only explanation that I have is that Dune wasn't fast enough to react to the creation of the new file and reported successful completion of the build instead of restarting. I'm adding a short delay after touching the file to hopefully make such races much less likely. I wonder if @jeremiedimino's upcoming PR will make this `sleep` unnecessary (as discussed [here](https://github.com/ocaml/dune/pull/5108#issuecomment-963740138)).
=> Add a short delay to ensure Dune notices the new file

src/dune_file_watcher/dune_file_watcher.ml
It's unnecessary following #5129 given that the patterns now match paths without `/` as well.
=> Remove some unnecessary path absolution

src/dune_engine/scheduler.ml
Before this PR, `Sync` events from the file watcher we reported along side other build input changes. This meant that we at the point we interpret build input changes event we had to scan the list for `Sync` events.
This PR makes `Sync` its own separate event, which makes the code clearer IMO.
One difference with before is that if the file watcher reports a list of events that is `[ev1; ev2; Sync; ev3; ev4]` where `evX` are not Sync events, the old code would wakeup the ivar waiting for the Sync event with `[ev1; ev2; ev3; ev4]` while the new code will only wakeup the ivar with `[ev1; ev2]` and will leave in `[ev3; ev4]` in the event queue. It would be easy enough to get the old behaviour back by making the event queue report `[ev1; ...; ev4]`  before the Sync event, but the new behaviour …
=> Make FS Sync its own event

bin/print_rules.ml, src/dune_engine/action_exec.ml, src/dune_engine/action_exec.mli, src/dune_engine/build_system.ml, src/dune_engine/process.ml, src/dune_engine/process.mli, src/dune_engine/reflection.ml, src/dune_engine/reflection.mli, src/dune_engine/rule.ml, src/dune_engine/rule.mli, src/dune_engine/rules.ml, src/dune_engine/targets.ml, src/dune_engine/targets.mli, src/dune_rules/dir_contents.ml, src/dune_rules/simple_rules.ml, src/dune_rules/simple_rules.mli, src/dune_rules/super_context.mli, src/dune_rules/test_rules.ml
As discussed, this PR introduces `Targets.Validated.t` that is guaranteed to satisfy a few properties. This allows us to make the code a bit more type-safe (getting rid of `head_exn`). Also, I decided to expose the underlying record `{files; dirs}` because it makes the code more natural in many places.
There is no change in behaviour.
=> Add [Targets.Validated.t]

src/dune_engine/scheduler.ml, src/dune_file_watcher/dune_file_watcher.ml, src/dune_file_watcher/dune_file_watcher.mli, test/expect-tests/dune_file_watcher/dune_file_watcher_tests_linux.ml, test/expect-tests/dune_file_watcher/dune_file_watcher_tests_macos.ml
To differentiate multiple FS syncs.
This is not immediately useful, but will be in the next PR I'm writing.
=> Add FS sync ids

src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli
And instead replace it by a `flush_file_watcher : unit -> unit Fiber.t` function. This makes the scheduler code simpler: we have one less global state to reason about.
=> Remove the Wait_for_inotify_sync scheduler state

src/fsevents/fsevents.ml, src/fsevents/fsevents_stubs.c
so that we don't have to remember to free manually
@nojb extracted this from #5127 as it's the only commit relevant to the C api.
=> refactor: switch runloop to custom

src/dune_engine/scheduler.ml
Rather than pass around a `~flush` argument. I find that it makes the logic slightly less scattered.
=> Small improvement: put the two `flush_file_watcher` next to each other in `poll_passive`

otherlibs/stdune-unstable/stdune.ml, src/dune_engine/cached_digest.ml, src/dune_engine/cached_digest.mli, src/dune_engine/fs_cache.ml, src/dune_engine/fs_cache.mli, src/dune_engine/fs_memo.ml, src/dune_engine/fs_memo.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_engine/target_promotion.ml, src/dune_file_watcher/dune_file_watcher.ml, src/dune_file_watcher/dune_file_watcher.mli, test/blackbox-tests/test-cases/watching/copy-rules.t, test/blackbox-tests/test-cases/watching/target-promotion.t
Fixes #5087.
By getting rid of the `Scheduler.ignore_for_watch` hack, we fix two file-watching tests. These tests were previously broken due to ignoring the next event for the promoted path but that is just wrong because there are other functions that depend on that path's content and existence.
I also removed `Path.Source.unlink_no_err dst` for two reasons:
* First, it's unnecessary since `promote_source` uses `rename` under the hood which succeeds if the destination exists.
* Second, this operation may trigger the build restart too early, before we have finished copying the file. It's better to avoid non-atomic modifications of the source directory if possible.
I also added a CR-someday pointing out a problem with file promotion logic: when we promote a file, we can change its content …
=> Remove [Scheduler.ignore_for_watch]

src/dune_engine/action_exec.ml, src/dune_engine/action_exec.mli, src/dune_engine/build_system.ml, src/dune_engine/process.ml, src/dune_engine/process.mli
The current API is awkward to use in situations where there are no targets.
=> Relax the API of [Action_exec.exec] for internal JS actions

test/blackbox-tests/test-cases/watching/what-dune-watches.t
We can see that currently Dune is watching both files and directories. Which is not necessary, it could just watch directories.
=> Add a test showing what Dune watches via inotify

src/dune_file_watcher/dune_file_watcher.ml, src/dune_file_watcher/dune_file_watcher.mli, test/blackbox-tests/test-cases/watching/target-promotion.t
The first commit exposes a couple of problems with file-system event processing that happen during target promotion:
* We still receive events for temporary `.#promoted.dune-temp` files.
* We restart the build when `mtimes` of a directory changes, even if its contents is the same from Dune's point of view.
The second commit fixes the first problem. I'm going to look at the second problem in a separate PR.
The third commit removes some code, which I believe is no longer useful.
By the way, I believe this PR also fixes another bug: the way the code was written, I think we always ignored `Queue_overflow` because it contained no paths! Now we are no longer ignoring it.
=> Tests file-system events for promotion and fix an event filtering bug

src/dune_engine/build_system.ml, src/dune_engine/target_promotion.ml, src/dune_engine/target_promotion.mli, test/blackbox-tests/test-cases/promote/old-tests.t/run.t, test/blackbox-tests/test-cases/watching/target-promotion.t
This is a small refactoring to make the upcoming target promotion PR easier to review. 
* Instead of checking that the parent directory exists for every destination, we only check it once and only in the case of using the `into` feature. There is no point in checking this for other cases since the parent directory is guaranteed to exist (it should contain the corresponding `dune` file). Note how this improves one of the tests: a call to `path_exists` disappeared.
* We no longer need target digests, so I'm dropping them from the API.
* Use `Fiber.sequential_iter` since we don't really benefit from parallelism here.
=> Refactor target promotion

src/dune_engine/build_system.ml, test/blackbox-tests/test-cases/directory-targets/main.t
While working on target promotion I realised that the workspace-local cache is currently broken for directory targets. Adding a test to demonstrate this.
=> Add a test for workspace-local cache and directory targets

src/fiber/fiber.mli, src/fiber_util/fiber_util.ml, src/fiber_util/fiber_util.mli, test/expect-tests/fiber/dune, test/expect-tests/fiber/fiber_tests.ml
Inside JS, we need to be able to run background actions. This is currently broken because of the check inside `with_job_slot`. To workaround this, I'd to implement more fine-grained fiber cancellation so that we can cancel just the build and not all possible running fibers.
This PR add support for Fiber cancellation.
=> Add support for Fiber cancellation

src/dune_engine/scheduler.ml, src/fiber/fiber.ml, src/fiber/fiber.mli, src/fiber_util/fiber_util.ml, src/fiber_util/fiber_util.mli, test/expect-tests/test_scheduler/test_scheduler.ml
This is useful to be able to fire a cancellation from the scheduler core. I initially wondered about just making the `iter` callback return a general `unit Fiber.t`, but then it's a bit awkward if this fiber yields. We could detect it and raise, but I opted for a slightly heavier style and a compile time guarantee rather than more flexibility and a runtime check.
=> Allow to fill more than one ivar at a time

src/dune_engine/dune, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/fiber_util/fiber_util.ml, src/fiber_util/fiber_util.mli, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/fiber/fiber_tests.ml, test/expect-tests/scheduler_tests.ml
At the moment, when we restart a build we cancel all fibers, independently of whether they are part of the current build or not. For instance, this means that processes ran by other systems such as the RPC get cancelled as well, which is odd. This is problematic inside Jane Street as we need to run background hg commands.
This PR adds a test exposing this behaviour and then fixes it locally setting a new `Fiber_util.Cancellation.t` in each build.
=> When restarting a build, don't cancel fibers unrelated to the build

bin/common.ml
We recently had an issue inside Jane Street where Dune was running with the shared cache enabled by default inside cram tests. This was causing failures in the CI.
This PR logs the shared cache status so that we can check that the cache is disabled. Plus, it seems generally useful to know in reports whether the shared cache was in use or not.
=> Log whether the shared cache is enabled or not

otherlibs/stdune-unstable/interned.ml, otherlibs/stdune-unstable/interned_intf.ml, otherlibs/stdune-unstable/path.ml, otherlibs/stdune-unstable/path_intf.ml, otherlibs/stdune-unstable/string.mli, src/dune_engine/build_system.ml, src/dune_engine/sandbox.ml, src/dune_engine/sandbox.mli, src/dune_engine/target_promotion.ml, src/dune_engine/target_promotion.mli, src/dune_engine/targets.ml, src/dune_engine/targets.mli
A refactoring that makes the code working with directory targets more uniform.
This also fixes a few `Set` modules by exposing a missing type equality.
=> Add [Targets.Produced]

src/memo/memo.ml
Move the call to `check_point` in memo.ml inside `report_and_collect_errors` so that exceptions are caught. Otherwise we were leaving memo in a bad state in case of cancellation.
=> Fix hanging introduced by f171cca9b439072817dd6834914ad0b1b482149b

otherlibs/action-plugin/src/protocol.ml, otherlibs/dune-rpc/private/registry.ml, otherlibs/ordering/ordering.ml, otherlibs/ordering/ordering.mli, src/dune_engine/action_exec.ml, src/dune_engine/alias.ml, src/dune_engine/cached_digest.ml, src/dune_engine/dep.ml, src/dune_engine/file_selector.ml, src/dune_engine/install.ml, src/dune_engine/mode.ml, src/dune_engine/package.ml, src/dune_engine/pform.ml, src/dune_engine/sandbox_mode.ml, src/dune_engine/scheduler.ml, src/dune_engine/source_tree.ml, src/dune_engine/string_with_vars.ml, src/dune_graph/graph.ml, src/dune_lang/decoder.ml, src/dune_lang/syntax.ml, src/dune_lang/template.ml, src/dune_rules/binary_kind.ml, src/dune_rules/binary_kind.mli, src/dune_rules/dune_file.ml, src/dune_rules/inline_tests_info.ml, src/dune_rules/lib.ml, src/dune_rules/preprocess.ml, src/dune_util/ml_kind.ml
Continuing the conversation started in #5166, this PR adds `let=` to chain comparisons, so one can write:
```ocaml
let compare { x; y; z } t =
let open Ordering.O in
let= () = compare_x x t.x in
let= () = compare_y y t.y in
compare_z z t.z
```
or, a bit less compactly but more symmetrically:
```ocaml
let compare { x; y; z } t =
let open Ordering.O in
let= () = compare_x x t.x in
let= () = compare_y y t.y in
let= () = compare_z z t.z in
Eq
```
The resulting code is pleasant to read but I'm not entirely sure it has no overhead compared to manual `match`ing.
@jeremiedimino Btw, I couldn't use `let?` because `?` isn't an allowed operator character.
P.S.: I converted only a couple of comparison functions but if we decide that going this way is a good idea, I'm happy to adapt the rest of the …
=> Add [Ordering.O.let=]

perf.sh
I'm switching to `https://github.com/ocaml-dune/dune-bench` as this is a better benchmark. 
I've also tweaked the script a bit so that it doesn't choke on build warnings and adds the repository name to the summary:
```
Summary for building https://github.com/ocaml-dune/dune-bench:
Current branch  Main branch 
============== =============
| real 54.138s   real 54.234s
Full build | user 168.245s  user 169.472s
| sys  38.503s   sys  38.577s
| real 2.198s    real 2.197s
Zero build | user 2.046s    user 2.034s
| sys  0.153s    sys  0.162s
```
=> Change [perf.sh] to use [dune-bench] repo by default

otherlibs/site/test/plugin_require_thread.t/app.ml, otherlibs/site/test/plugin_require_thread.t/run.t
Instead of using default toplevel exception printing of OCaml catch the exception.
@snowleopard You can merge directly if you are satisfied.
=> Fix dune site tests when backtrace printing activated

src/dune_engine/fs_cache.ml, src/dune_engine/fs_cache.mli, src/dune_engine/target_promotion.ml, test/blackbox-tests/test-cases/watching/target-promotion.t
The `Fs_cache.Reduced_stats` record is too large and some of its fields are currently unused. They cause unnecessary restarts for Dune, so I am removing them. The `mtime` field is particularly problematic because it changes for a directory when we create temporary files inside it, which I believe is the cause for #5170.
I originally included these fields into `Fs_cache.Reduced_stats` because they appeared important for the `Cached_digest` module. However, `Cached_digest` obtains them via untracked file-system access and we are not planning to change that for now. This means, there is no reason to keep them in `Fs_cache.Reduced_stats`.
This fixes a problem in an existing file-watching test and also improves builds in my manual testing.
=> Stop caching unused fields in [Fs_cache.Reduced_stats]

test/blackbox-tests/test-cases/actions/dune
Temporary
@rgrinberg Just to have an all green CI before a proper fix.
=> [Test] Deactivate stray process test for macos

src/dune_engine/build_system.ml, src/dune_engine/fs_cache.ml, src/dune_engine/fs_cache.mli, src/dune_engine/fs_memo.ml, src/dune_engine/sandbox.ml, test/blackbox-tests/test-cases/watching/target-promotion.t
This is a follow-up to #5203. As explained in the added comment, the reasons for doing this are:
* Semantically, this is equivalent because `Path.exists` is also implemented by checking that the `stat` call succeeds (see `caml_sys_file_exists`).
* `Fs_cache.path_stat` doesn't change too often because the resulting record `Reduced_stats` doesn't include frequently changing fields like `mtime`. Technically, it can still change while `path_exists` remains constant `true`, for example, if the `st_kind` field changes, in which case Dune will restart unnecessarily, but such changes are rare, so we don't care.
* Reusing `Fs_cache.path_stat` helps us to reduce the number of `stat` calls, i.e. we can do just one call to answer both `path_stat` and `path_exists`.
* Having a smaller number of …
=> Implement [Fs_memo.path_exists] via [Fs_cache.path_stat]

src/dune_engine/build_system.ml, src/dune_engine/fs_memo.ml, src/dune_engine/fs_memo.mli, src/dune_engine/sandbox.ml, src/dune_engine/target_promotion.ml, src/dune_rules/artifacts.ml, src/dune_rules/context.ml, src/dune_rules/findlib/findlib.ml, src/dune_rules/workspace.ml, test/blackbox-tests/test-cases/sandboxing.t/run.t
As discussed in #5205, all call sites of `Fs_memo.path_stat` can be rewritten to use more precise functions.
=> Replace [Fs_memo.path_stat] with more precise functions

otherlibs/stdune-unstable/set_intf.ml, src/dune_engine/build_system.ml, src/dune_engine/sandbox.ml, src/dune_engine/sandbox.mli
As discussed in #5209. 
We could also change `Action.chdirs` to return `Path.Build.Set.t` but that seems more invasive.
=> Assert that actions only [chdir] inside the build directory
