ocaml/dune

src/dune_engine/build.ml, src/dune_engine/static_deps.ml, src/dune_engine/static_deps.mli
Both/Seq/Map2 can all be done concurrently
=> Make Build.exec more concurrent

src/dune_engine/scheduler.ml
Allows us to reuse this scheduler for expect tests
=> Move all scheduler state to one record

test/blackbox-tests/test-cases/subst/from-project-file.t, test/blackbox-tests/test-cases/subst/unicode.t, test/blackbox-tests/test-cases/subst/with-opam-file.t
=> Remove a few more --initial-branch

Makefile, doc/hacking.rst
* Run dune-release tag
* Make sure that dune-release uses the in source dune
=> Improve release invocation

bin/build_cmd.ml, bin/build_cmd.mli, bin/clean.ml, bin/clean.mli, bin/import.ml, bin/main.ml, bin/promote.ml, bin/promote.mli
Consistent with how organize all other commands
=> Split promote/clean/build cmds into modules

CHANGES.md
https://github.com/ocaml/dune/issues/3756 remains unfixed :-)
=> Fix small typo in CHANGES

src/dune_rules/context.ml, src/dune_rules/gen_rules.ml
SO that we don't need to expose Ivar in the memo monad.
=> Remove last uses of Fiber.Ivar in rule generation code

doc/dune-files.rst, doc/hacking.rst, doc/instrumentation.rst, doc/opam.rst, doc/sites.rst, doc/tests.rst, src/dune_engine/stanza.ml, test/blackbox-tests/test-cases/dune-ppx-driver-system.t/run.t, test/blackbox-tests/test-cases/jsoo/explicit-js-mode-anon.t/run.t, test/blackbox-tests/test-cases/meta-template-version-bug.t
And also update a few tests to not mention the latest language version, so that we don't have to update them again in the future.
=> Bump latest language version to 2.9

src/cache_daemon/cache_daemon.ml, src/cache_daemon/dune, src/cache_daemon/utils.ml, src/stdune/daemonize.ml, src/stdune/daemonize.mli, src/xdg/xdg.ml, src/xdg/xdg.mli
=> Dune cache - minor tweaks

src/dune_rules/dune_rules.ml, test/expect-tests/findlib_tests.ml
This will hopefully make us more mindful of what we use inside cli.
=> Add lib interface for dune_rules

doc/dune-files.rst, doc/hacking.rst, doc/instrumentation.rst, doc/opam.rst, doc/sites.rst, doc/tests.rst, src/dune_engine/stanza.ml, test/blackbox-tests/test-cases/dune-init.t/run.t
We are now officially preparing 3.0 \o/
=> Bump language version to 3.0

src/memo/memo.ml
Just drop unnecessary `inp` argument in a couple of places.
=> Simplify Memo a bit

src/dune_engine/build_system.ml
It's needed to save the build errors from the last run in case dune rpc needs to
report them.
=> Save build system errors

src/dune_rules/dune_file.ml
=> Fix typo on visibility error message

bin/install_uninstall.ml, src/dune_engine/dir_set.ml, src/dune_engine/process.ml, src/dune_engine/rules.ml, src/dune_lang/syntax.ml, src/dune_rules/dune_package.ml, src/dune_rules/foreign_rules.ml, src/dune_rules/gen_meta.ml, src/stdune/map.ml, src/stdune/map_intf.ml
Introduce to_list_map. Symmetrical to of_list_map.  This already exists in Set,
might as well add it to Map.
=> Deforest Map.to_list |> List.map

src/csexp_rpc/csexp_rpc.ml, src/csexp_rpc/csexp_rpc.mli, src/csexp_rpc/dune, src/csexp_rpc/worker.ml, src/csexp_rpc/worker.mli, src/fiber/fiber.ml, src/fiber/fiber.mli, src/stdune/fpath.ml, src/stdune/fpath.mli, src/stdune/path.ml, src/stdune/stdune.ml, test/expect-tests/csexp_rpc/csexp_rpc_tests.ml, test/expect-tests/csexp_rpc/dune
As requested by @jeremiedimino
=> Split csexp_rpc from rpc

bin/describe.ml
=> Better 'dune describe' docstring

otherlibs/dune-rpc/private/dbus_address.mli, otherlibs/dune-rpc/private/dbus_address.mll, otherlibs/dune-rpc/private/dune_rpc_private.ml
@jeremiedimino your original parser pased a list of addresses, but this
is probably not useful for us.
=> [dune rpc] parse only 1 address

src/dune_engine/scheduler.ml
This should fix the issue @voodoos reported
=> Cleanup rpc sockets on exit

src/dune_config/dune_config.ml
=> Use Int.of_string in dune_config

CHANGES.md
Signed-off-by: Ulysse Gérard <thevoodoos@gmail.com>
=> Update CHANGES for #4261 (clean merlin files)

src/memo/memo.ml
I'm extracting this refactoring from my ongoing work on Memo v2. It seems generally useful to distinguish computations that failed due to exceptions (e.g. division by zero in a user-supplied functions) from those that failed due to a dependency cycle.
One of the next steps could be to cancel all computations as soon as we hit any cycle, to work around the limitation of our incremental cycle detection library discovered in #4275.
It should be possible to build on the this PR to add support for a more general notion of cancellations, where computations can be cancelled not only because of dependency cycles, but because we decided to cancel everything in the current run.
=> Distinguish computation errors from cancellations

doc/index.rst, doc/rpc.rst, otherlibs/dune-rpc/dune_rpc.mli
Add some simple preliminary docs
=> [rpc] add documentation

otherlibs/dune-rpc/dune_rpc.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, otherlibs/dune-rpc/private/types.ml, otherlibs/dune-rpc/private/types.mli, src/dune_rpc_server/dune, src/dune_rpc_server/dune_rpc_server.ml, src/stdune/exn.ml, src/stdune/exn.mli, src/stdune/exn_with_backtrace.ml, src/stdune/exn_with_backtrace.mli
report errors that aren't request specific using the log notification
Perhaps this notification should be switched to "error"?
=> [dunerpc] use log notification for errors

bin/dune, boot/libs.ml, dune-action-plugin.opam, dune-build-info.opam, dune-configurator.opam, dune-glob.opam, dune-private-libs.opam, dune-private-libs.opam.template, dune-project, dune-rpc.opam, dune-site.opam, otherlibs/action-plugin/src/dune, otherlibs/dune-rpc/dune, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune, src/cache/dune, src/cache_daemon/dune, src/csexp_rpc/dune, src/dune_rules/dune, src/stdune/csexp.ml, src/stdune/dune, src/stdune/sexp.ml, src/stdune/sexp.mli, src/stdune/stdune.ml, test/expect-tests/csexp_rpc/dune, vendor/csexp/src/csexp.ml, vendor/csexp/src/csexp.mli, vendor/csexp/src/dune, vendor/update-csexp.sh
With the goal of using the new canonical csexp type in dune rpc
=> Update to new csexp

bin/rpc.ml
Correctly close client after session is done.
=> Fix dune rpc init close

src/memo/memo.ml, test/expect-tests/memo/memoize_tests.ml
This fixes the issue demonstrated in #4311.
=> Fix the bug with phantom dependencies in Memo

Makefile
=> Lift version restriction on mdx

src/dune_rules/gen_meta.ml, src/dune_rules/lib.ml, src/dune_rules/lib.mli
This seems like more of a concern of Gen_meta than Lib. And Lib is already huge.
=> Remove meta handling from lib to gen_meta

.github/workflows/workflow.yml, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t, test/blackbox-tests/test-cases/merlin/github4125.t/dune-workspace, test/blackbox-tests/test-cases/merlin/github4125.t/run.t, test/blackbox-tests/test-cases/merlin/symlinks.t/realroot/dune-project, test/blackbox-tests/utils/dune_cmd.ml
https://github.com/ocaml/dune/pull/4327 + #4232 + tweak to a Merlin test
=> Restore 2.8 branch CI

otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_rpc_impl/server.ml, src/dune_rpc_impl/server.mli
Not the most useful request, but there's no harm in making it public. It's at
least useful for tests.
=> [RPC] make ping public

otherlibs/stdune-unstable/monoid.ml, otherlibs/stdune-unstable/monoid.mli, src/dune_engine/action_builder.ml, src/dune_engine/scheduler.ml, src/fiber/fiber.ml, src/fiber/fiber.mli, src/memo/memo.mli, test/expect-tests/fiber/fiber_tests.ml
As discussed, this is necessary background tasks in the RPC server
=> Fiber.Pool

src/fiber/fiber.ml
It is used only once. If we inline it, it become simpler.
=> Inline and simplify deref_finalize

otherlibs/dune-rpc/private/dune_rpc_private.mli, otherlibs/dune-rpc/private/types.ml, otherlibs/dune-rpc/private/types.mli, src/dune_engine/scheduler.ml, src/dune_rpc_server/dune, src/dune_rpc_server/dune_rpc_server.ml, src/dune_rpc_server/dune_rpc_server.mli, test/expect-tests/dune_rpc/dune_rpc_tests.ml
=> Add stats to dune's rpc server

bin/internal.ml, bin/internal_dump.ml, bin/main.ml, src/dune_engine/build_system.ml, src/dune_engine/cached_digest.ml, src/dune_engine/promotion.ml, src/dune_rules/merlin.ml, src/dune_util/persistent.ml, src/dune_util/persistent.mli, test/blackbox-tests/test-cases/internal/dump.t
To inspect persistent database files such as the digest database, the promote database, the rule database for incremental compilation, ...
=> Add [dune internal dump] command

bin/build_cmd.ml, bin/import.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rpc_impl/server.ml, src/dune_rpc_impl/server.mli, src/dune_rules/main.ml, src/dune_rules/main.mli
To simplify the code. Always using a mutex doesn't seem harmful to me.
Comes after #4448
=> Alwayas use a build mutex

otherlibs/stdune-unstable/temp.ml
Following a discussion in #4443.
=> Improve exception handling in [Temp.try_paths]

src/dune_engine/action.ml, src/dune_engine/action.mli, src/dune_engine/action_builder.ml, src/dune_engine/action_builder.mli, src/dune_engine/build_system.ml, src/dune_engine/rule.ml, src/dune_engine/rule.mli, src/dune_engine/rules.ml, src/dune_engine/rules.mli, src/dune_rules/context.ml, src/dune_rules/super_context.ml
They don't need to be known statically and the extra power is useful for using dune with the jenga rules.
=> Move env and locks to dynamic part of action

src/dune_engine/action.ml, src/dune_engine/action.mli, src/dune_engine/build_system.ml, src/dune_rules/context.ml, src/dune_rules/super_context.ml, test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
We have that in jenga and need it for running the jenga rules with dune. Comes after #4462
=> Add can_go_in_shared_cache

src/dune_engine/action_exec.ml, src/dune_engine/action_exec.mli, src/dune_engine/build_system.ml, src/dune_rules/cram_exec.ml, test/blackbox-tests/test-cases/path-rewriting.t, test/blackbox-tests/utils/dune, test/blackbox-tests/utils/dune_cmd.ml
=> Extend BUILD_PATH_PREFIX_MAP with the workspace root

bin/common.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rpc_impl/server.ml, src/dune_rpc_impl/server.mli, src/dune_rules/main.ml, src/dune_rules/main.mli
* Add severity to error notifications. Should these be renamed to
diagnostics perhaps?
=> [RPC] Improve error/promotion handling

src/dune_engine/sub_dirs.ml, src/dune_rules/dune_load.ml, src/dune_rules/preprocessing.ml, src/dune_rules/scheme.ml
Found a few places where we could reuse `Option.merge`.
=> Make use of [Option.merge]

doc/opam.rst
See also https://github.com/ocaml/dune/pull/3647
=> opam.rst: dune subst should be called with dev

otherlibs/stdune-unstable/fdecl.ml, otherlibs/stdune-unstable/fdecl.mli
=> Remove unused Fdecl.set_idempotent

src/dune_engine/source_tree.ml, src/dune_engine/source_tree.mli
To make Jane Street fork of Dune a bit easier to rebase.
=> Add a hook for filtering out temporary files

CHANGES.md, src/dune_rules/cinaps.ml, test/blackbox-tests/test-cases/cinaps/multiple-cinaps.t, test/blackbox-tests/test-cases/generated-source-dir-overlap.t/run.t
Multiple cinaps stanzas are currently forbidden. There's no reason to
restrict this.
=> Allow multiple cinaps stanzas in a dir

otherlibs/stdune-unstable/path.mli, src/dune_engine/build_system.ml, src/dune_engine/cached_digest.ml, src/dune_engine/cached_digest.mli, src/dune_engine/fs_notify_memo.ml, src/dune_engine/fs_notify_memo.mli, src/dune_engine/scheduler.ml, src/dune_rules/workspace.ml
Replace the lower-level `depend` with higher-level `file_exists` and `file_digest` and add some comments.
=> Refactor Fs_notify_memo

otherlibs/dune-rpc-lwt/test/dune_rpc_lwt_tests.ml
Log rpc client and the build server events separately
=> [RPC] make lwt tests more reproducible

otherlibs/stdune-unstable/fpath.ml
As spotted by @aalekseyev, my fix in #4529 was incomplete: there is still one race left. Fixing it here.
=> Fix another possible race

src/dune_rpc_impl/run.ml
`dune build -w` is broken since #4437. Looking at the diff, it seems that a call to `Fiber.Pool.run` was accidentally removed. This PR restores it. I checked and this PR does fix `dune build -w`.
=> Restore a Fiber.Pool.run that seems to have been removed by accident

bin/rpc.ml, bin/shutdown.ml, src/dune_rpc_impl/run.ml, src/dune_rpc_impl/run.mli
* Use socket symlinking trick for client established servers.
* Encapsulate more low level stuff in Dune_rpc_impl.Run.
=> [RPC] Connection Handling Improvements

src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli
After @snowleopard's refactoring, this thing isn't used anymore.
=> Remove sync tasks

src/dune_engine/build_system.ml
As explained in the comments, there is no need to use the memoized version here. In fact, using it breaks incremental file-watching builds because these `mkdir_p` calls are still untracked and so right now we delete but never recreate these sandbox directories.
=> Don't memoize [mkdir_p] for sandbox directories

src/dune_engine/build_system.ml
This fdecl is no longer necessary.
=> Remove alias_exists_fdecl

src/dune_engine/cram_test.ml, src/dune_engine/cram_test.mli, src/dune_engine/source_tree.ml, src/dune_rules/cram_exec.ml
Makes it easier to debug cram tests and see what is running.
=> Improve temp names in cram

src/dune_stats/dune_stats.ml, test/blackbox-tests/test-cases/trace-file.t/run.t
=> Remove trailing zero's when writing json

src/dune_cache/local.ml, src/dune_cache_storage/util.ml, src/dune_engine/process.ml
=> temp names: "." to separate prefix/suffix

src/csexp_rpc/csexp_rpc.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli
=> [Scheduler] capture backtrace in [Worker]

src/dune_engine/build_system.ml, src/dune_engine/opam_file.ml, src/dune_engine/source_tree.ml, src/dune_rules/super_context.ml, src/memo/memo.ml, src/memo/memo.mli, test/expect-tests/memo/memoize_tests.ml
There are no behaviour changes.
=> Update some docs, move a couple of functions around

bin/rpc.ml
Report errors immediately as they come, rather than waiting for all the
fibers.
@cwong-ocaml this PR might be helpful to debug the issue your encountering
=> [RPC] print errors in rpc init

otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_rpc_impl/client.ml, test/expect-tests/dune_rpc/dune_rpc_tests.ml
Take Chan/Fiber as separate arguments. I have no idea why I packed
everything into one module in the first place.
=> [RPC] simplify client functor

bin/rpc.ml, src/csexp_rpc/csexp_rpc.ml
@cwong-ocaml hopefully this is enough to fix your issues with reconnecting. I
went over the code and made sure that error handling is tight everywhere.
=> [RPC] Improve error recovery

test/expect-tests/memo/memoize_tests.ml
While taking another look at the cycle detection logic, I realised that adding old dependency edges (during the restore from cache phase) is unnecessary and can also lead to spurious cycle errors. This test demonstrates the problem. I don't think it's possible to trigger this problem with deterministic tasks. Still, adding such a test seems useful.
I'm planning to fix it in a subsequent PR.
@jeremiedimino So, it appears that you were right during our morning discussion, and I was wrong :) We don't need to add old dependency edges when detecting cycles. In fact, doing this is not only unnecessary but is subtly incorrect.
=> Add a test that reveals spurious cycles in Memo

src/dune_rpc_server/dune_rpc_server.ml
Currently, it waits until the client disconnected before reporting errors
@jeremiedimino I'm not sure how to report such errors correctly. They are not
really the fault of the developer or the user, but more like errors caused by
invalid clients. It's useful to see them on the server side however.
=> [RPC] server should report client errors promptly

test/blackbox-tests/test-cases/merlin/merlin-tests.t/run.t, test/blackbox-tests/test-cases/subst/from-project-file.t, test/blackbox-tests/test-cases/subst/unicode.t, test/blackbox-tests/test-cases/subst/with-opam-file.t
@voodoos commit originally from @jeremiedimino, it breaks tests without an up to date git. More problematically it modifies my dune repository (it continues the git command even if the init fails).
=> Cherry-pick removing of some last --initial-branch

Makefile
This ensures that current-bench can import the JSON data.
=> Let `make bench` emit just JSON

src/dune_engine/build_system.ml
and remove module Alias = Alias0
Looks like a leftover from previous a refactoring.
=> Rename Alias0 to Alias in build_system.ml

src/dune_engine/action_exec.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/print_diff.ml, src/dune_engine/print_diff.mli, src/dune_engine/promotion.ml, src/dune_engine/promotion.mli, src/dune_rpc_impl/server.ml
Allows clients to understand which errors correspond to promotions
=> [RPC] add promotion annotations to errors

bin/rpc.ml
do not try to connect outside the polling loop
=> [RPC] fix --wait

bin/rpc.ml, src/csexp_rpc/csexp_rpc.ml, src/csexp_rpc/csexp_rpc.mli, src/dune_rpc_impl/server.ml
This should hopefully fix status for you.
=> [RPC] Fix status issues

otherlibs/dune-rpc/private/dune_rpc_private.ml
Add offending data to the error payloads
=> [RPC] improve fatal errors

src/memo/memo.ml
This change allows us to avoid traversing two pointers `without_state.spec.allow_cutoff` when checking if a dependency edge is up to date, thus avoiding potential memory stalls in incremental (near) zero rebuilds.
In my experiments, this reduces the time attributed to the `go` function and its descendants by `perf` by 5%. More specifically, here are two figures for incremental rebuilds of a large internal target:
* Before this change: 16.67% (in `go`) and 40.18% (in and below `go`)
* After this change: 9.24% (in `go`) and 35.07% (in and below `go`)
=> Cache the cutoff flag in Memo's Dep_node

otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_rpc_impl/server.ml
These events are currently received when the client subscribes to build
progress.
=> [RPC] report build events to clients

src/dune_engine/build_system.ml
This PR reverts the incorrect implementation of `Build_system.error_cell`. Not only it didn't work but it also introduced a performance regression :facepalm:
=> Revert the bug introduced in #4719

src/dune_engine/scheduler.ml, src/memo/memo.ml, src/memo/memo.mli
=> Defunctionalize Memo.Invalidation.t for debugging

src/memo/memo.ml
Remove some code duplication I introduced when doing a merge of the previous two PRs.
=> Fix silly merge

test/blackbox-tests/test-cases/dune, test/blackbox-tests/test-cases/merlin/dune, test/expect-tests/dune
Depend on various binaries such as git, node, ocamlfind where
appropriate
=> Improve test dependencies

.github/workflows/workflow.yml, src/dune_file_watcher/dune_file_watcher.ml, test/blackbox-tests/test-cases/dune, test/blackbox-tests/test-cases/watching/test-1.t/run.t
install fsevents using homebrew
=> Enable watch mode tests on MacOS

src/dune_engine/scheduler.ml
When standing by, the normal shut down mechanism deadlocks. This is easily
reproduced by running in passive mode and shutting down without building
anything.
To fix, we force the shutdown by sending a signal.
In addition, we make sure the Waiting_for_inotify_sync state also
terminates properly.
This fix feels a bit dirty. I don't quite like how I am pretending we received a
signal. Should we introduce a new event?
=> [Scheduler] Shutdown when standing by

CHANGES.md, bin/install_uninstall.ml, configure.ml, doc/usage.rst, src/dune_engine/install.ml, src/dune_engine/install.mli, src/dune_rules/artifact_substitution.ml, src/dune_rules/artifact_substitution.mli, src/dune_rules/setup.defaults.ml, src/dune_rules/setup.mli, test/blackbox-tests/test-cases/install-docdir.t/run.t, test/blackbox-tests/test-cases/install-etcdir.t/run.t
=> [2.9] [install] Allow users to specify docdir and etcdir

CHANGES.md, src/dune_rules/coq_rules.ml, test/blackbox-tests/test-cases/coq/flags.t
=> [2.9] [coq] Adjust warnings on Coq 8.14 and `(lang coq (>= 0.3))`

CHANGES.md
Due to wrong solving of merge conflict.
=> [2.9] [changes] Fix double entry

src/dune_engine/mode.ml, src/dune_rules/cram_rules.ml, src/dune_rules/gen_rules.ml, src/dune_rules/jsoo_rules.ml, src/dune_rules/lib_rules.ml, src/dune_rules/mdx.ml, src/dune_rules/merlin.ml, src/dune_rules/module_compilation.ml, src/dune_rules/opam_create.ml, src/dune_rules/preprocessing.ml, src/dune_rules/virtual_rules.ml, src/memo/memo.ml, src/memo/memo.mli
As discussed [here](https://github.com/ocaml/dune/pull/3956#discussion_r655439361).
=> Rename Memo.Build.if_ to Memo.Build.when_

src/dune_engine/process.ml
To differentiate colored and uncolored output
=> Introduce output type for process output

CHANGES.md, src/dune_rules/preprocess.ml, src/dune_rules/preprocess.mli, test/blackbox-tests/test-cases/instrumentation.t/run.t, test/blackbox-tests/test-cases/instrumentation.t/trivial_ppx/dune, test/blackbox-tests/test-cases/instrumentation.t/trivial_ppx/dune-project, test/blackbox-tests/test-cases/instrumentation.t/trivial_ppx/trivial_ppx.ml
=> [2.9] Bugfix: only add instrumentation flags if instrumentation enabled

src/dune_engine/process.ml
Only detect embedded locations on the color stripped output.
I also refactored things to make it harder to make this mistake in the future
=> Fix detection of embedded locations

CHANGES.md
=> CHANGES for sites fixes in 2.9

bin/rpc.ml, otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_rpc_impl/decl.ml, src/dune_rpc_impl/decl.mli, src/dune_rpc_impl/server.mli, src/dune_rpc_impl/where.ml, src/dune_rpc_impl/where.mli, test/expect-tests/dune_rpc_e2e/dune, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
Given the upcoming changes to this stuff, it's better to make sure we
have some tests to verify nothing breaks. I did not write this in cram
because I expect to test other client functionality that will not be
available via just cli commands.
=> [RPC] test diagnostics handling

src/dune_rpc_impl/server.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
This should reduce ambiguity for clients.
In general, it seems like the less "interpretation" clients need to do, the
better. Not to mention that the logic is kept in one place, and dune retains
control over everything with this approach.
=> [RPC] use absolute paths in diagnostics

bin/rpc.ml, src/csexp_rpc/csexp_rpc.ml, src/csexp_rpc/dune
Should be easier to debug than dumping to stderr
=> Csexp_rpc - Log to _build/log

vendor/cmdliner/src/cmdliner.ml, vendor/cmdliner/src/cmdliner.mli, vendor/cmdliner/src/cmdliner_arg.ml, vendor/cmdliner/src/cmdliner_arg.mli, vendor/cmdliner/src/cmdliner_base.ml, vendor/cmdliner/src/cmdliner_base.mli, vendor/cmdliner/src/cmdliner_cline.ml, vendor/cmdliner/src/cmdliner_cline.mli, vendor/cmdliner/src/cmdliner_docgen.ml, vendor/cmdliner/src/cmdliner_docgen.mli, vendor/cmdliner/src/cmdliner_info.ml, vendor/cmdliner/src/cmdliner_info.mli, vendor/cmdliner/src/cmdliner_manpage.ml, vendor/cmdliner/src/cmdliner_manpage.mli, vendor/cmdliner/src/cmdliner_msg.ml, vendor/cmdliner/src/cmdliner_msg.mli, vendor/cmdliner/src/cmdliner_suggest.ml, vendor/cmdliner/src/cmdliner_suggest.mli, vendor/cmdliner/src/cmdliner_term.ml, vendor/cmdliner/src/cmdliner_term.mli, vendor/cmdliner/src/cmdliner_trie.ml, vendor/cmdliner/src/cmdliner_trie.mli, vendor/update-cmdliner.sh
Re-point the script to the upstream version that we actually use and then re-run the script.
=> update the cmdliner code using update-cmdliner.sh

src/memo/memo.ml
Just deleting/revising some stale comments in Memo.
=> Update stale comments

bin/build_cmd.ml, bin/describe.ml, bin/exec.ml, bin/import.ml, bin/print_rules.ml, bin/printenv.ml, bin/top.ml, bin/utop.ml, src/memo/memo.mli, test/blackbox-tests/test-cases/watching/quick-cancel.t
This PR fixes a bug happening in watching mode, where if a file is modified quickly after a build is restarted, dune prints an exception like below, and then gets stuck.
```
Error: exception Dune_engine__Scheduler.Build_cancelled
Raised at Dune_engine__Scheduler.with_job_slot.raise_if_cancelled in file
"src/dune_engine/scheduler.ml", line 812, characters 6-51
Called from Dune_engine__Scheduler.with_job_slot.(fun) in file
"src/dune_engine/scheduler.ml", line 822, characters 6-27
Called from Fiber.Execution_context.run_jobs in file "src/fiber/fiber.ml",
line 204, characters 8-13
Re-raised at Stdune__Exn.raise_with_backtrace in file
"otherlibs/stdune-unstable/exn.ml", line 36, characters 27-56
Called from Fiber.Execution_context.run_jobs in file "src/fiber/fiber.ml",
line 204, characters …
```
=> Fix "Build_cancelled" error in watching mode

src/memo/memo.ml
We currently branch on `dep.has_cutoff` for every `dep`, even if that `dep` can be successfully restored from the cache and doesn't need to be recomputed. Such branches are costly because they are hard to predict, so it's best to make them only when necessary. This PR pushes the branch into the computation phase.
With this change, I think we can also get rid of the `has_cutoff` optimisation, since we'll only need to follow `spec.allow_cutoff` when starting the computation and computation needs to look at `spec` anyway. I could do this change in this PR but it seems a bit orthogonal to the branch change -- perhaps, it's best to make it in a separate PR.
Microbenchmarks look good but not spectacular. Anyway, the restore from cache scenarios are improved, which is what we mostly care about …
=> Push the [has_cutoff] branch into the compute phase

src/async_inotify_for_dune/async_inotify.ml
Saw this `select` crash with EINTR in jenga.
I'm not sure this crash is possible with dune and I don't even know how to reproduce it, but handling EINTR can't hurt.
=> handle EINTR coming from [select] in inotify

CHANGES.md
=> [changes] Add changes entry for Haiku fix

CHANGES.md, src/dune_rules/install_rules.ml, test/blackbox-tests/test-cases/github4821.t/run.t
=> Fix enabled_if for public libraries

CHANGES.md, src/dune_rules/install_rules.ml, test/blackbox-tests/test-cases/github4821.t/run.t
This is the 3.0 version of #4824
fixes #4821
=> Fix enabled_if for public libraries [main]

CHANGES.md
=> [changes] Sync with 2.9.1 changelog

otherlibs/dune-rpc/dune_rpc.ml, otherlibs/dune-rpc/dune_rpc.mli, otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/dune_rpc_private.mli, src/dune_engine/format_dune_lang.ml, src/dune_engine/format_dune_lang.mli, src/dune_rpc_impl/dune, src/dune_rpc_impl/server.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
Needed for lsp to support formatting of dune files
=> [rpc] request for formatting dune files

src/dune_rules/install_rules.ml
We make `stanza_to_entries` a top-level function, which will prove
convenient later on in some ongoing PRs.
=> [refactor] Small refactoring in install_rules

src/dune_rules/lib.ml
This avoid having to justify why it is safe.
=> Repalce one mutable field in lib.ml by let rec + lazy

test/blackbox-tests/test-cases/dune, test/blackbox-tests/test-cases/watching/github4923.t, test/blackbox-tests/test-cases/watching/helpers.sh, test/blackbox-tests/test-cases/watching/quick-cancel.t
And factorise the tests of watch mode
=> Add a reproduction case for #4923

src/dune_engine/build_system.ml, src/dune_engine/source_tree.ml, src/dune_rules/context.ml, src/dune_rules/gen_rules.ml, src/dune_rules/install_rules.ml, src/dune_rules/scheme.ml
=> refactor: name some lazy cells

test/blackbox-tests/test-cases/watching/github5064.t
I keep coming across #5064 so I tried to add a test reproducing it. I didn't quite manage, but I believe I managed to reproduce a related problem.
=> Add a test case for #5064

src/dune_rules/simple_rules.ml
We were evaluating the dependencies of aliases twice (it's already done inside `Action_unexpanded.expand`).
=> Remove some duplicated work

src/dune_engine/build_system.ml, src/dune_rules/dir_contents.ml, src/dune_rules/install_rules.ml, test/blackbox-tests/test-cases/reporting-of-cycles.t/run.t
@jeremiedimino looks like this is still a problem.
=> test: reproduce crash in #4345

test/blackbox-tests/test-cases/watching/quick-cancel.t
(Merging without review to fix the main branch.)
=> Fix a test broken in #5108

src/dune_engine/build_system.ml, src/dune_engine/targets.ml, src/dune_engine/targets.mli, test/blackbox-tests/test-cases/patch-back-source-tree.t
Create the stamp file for anonymous actions outside the sandbox.
=> Fix bug exposed in #5121

otherlibs/stdune-unstable/top_closure.ml, test/blackbox-tests/test-cases/watching/github5064.t
Should fix the ocamldep issue.
=> fix: do not rely on mutation in top closure

.github/CODEOWNERS
@christinerose with this you should get a notification every time someones creates a PR that changes the doc/ directory.
=> Add @christinerose as code owner of doc/

src/dune_engine/scheduler.ml, test/blackbox-tests/test-cases/actions/stray-process.t, test/blackbox-tests/test-cases/watching/basic.t, test/blackbox-tests/test-cases/watching/copy-rules.t, test/blackbox-tests/test-cases/watching/github4923.t, test/blackbox-tests/test-cases/watching/github5064.t, test/blackbox-tests/test-cases/watching/quick-cancel.t, test/blackbox-tests/test-cases/watching/retriggering.t, test/blackbox-tests/test-cases/watching/target-promotion.t, test/blackbox-tests/test-cases/watching/watching-dot-files.t, test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml
=> Remove "wait for inotify sync" messages

test/expect-tests/inotify_tests/dune, test/expect-tests/inotify_tests/inotify_tests.ml
Which is an assumption we are making for the inotify sync mechanism.
=> Add a test showing that inotify reports events in chronoligical order

bin/import.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli
=> Replace the Wait_for_file_change state by a function

test/expect-tests/dune_file_watcher/dune_file_watcher_tests_macos.ml
=> test(fsevents): reproducible test

src/dune_engine/scheduler.ml
=> Don't reorder fs events

test/expect-tests/inotify_tests/inotify_tests.ml
=> Inotify tests involving an external process

src/dune_engine/target_promotion.ml, src/dune_rules/artifact_substitution.ml
Promotion can change the content of promoted files (due to artifact substitution), so we need to compare correct digests for the optimisation to actually work.
=> Fix optimisation in target promotion

src/dune_engine/action_exec.mli, src/dune_engine/target_promotion.ml
I accidentally merged #5155 before pushing last-minute tweaks to comments, so doing this here.
=> Fix comments

dune-project, dune-rpc.opam, otherlibs/dune-rpc/dune, otherlibs/dune-rpc/private/dune, otherlibs/dune-rpc/private/exported_types.ml, otherlibs/dune-rpc/private/import.ml
ordering and pp should be included
=> chore: update dune rpc deps

src/dune_engine/build_system.ml
Whenever I'm working on `execute_rule_impl`, I drown in complexity of this function. This PR moves a few pieces of functionality into separate functions, plus makes a few other minor changes. 
There are no changes in behaviour.
=> Refactor [execute_rule_impl]

src/dune_engine/build_system.ml
We currently unnecessarily use the `pending_targets` mechanism for sandboxed actions, so this PR fixes this.
=> Skip pending_targets clean up for sandboxed actions

otherlibs/stdune-unstable/dune_filesystem_stubs/dune_filesystem_stubs.ml, otherlibs/stdune-unstable/dune_filesystem_stubs/dune_filesystem_stubs.mli, otherlibs/stdune-unstable/map.ml, otherlibs/stdune-unstable/map_intf.ml, otherlibs/stdune-unstable/seq.ml, otherlibs/stdune-unstable/seq.mli, src/dune_engine/build_system.ml, src/dune_engine/target_promotion.ml, src/dune_engine/targets.ml, src/dune_engine/targets.mli, src/fiber/fiber.ml, src/fiber/fiber.mli, test/blackbox-tests/test-cases/directory-targets/main.t
This is a basic version. Some TODOs:
=> Implement promotion for directory targets

CHANGES.md, bin/install_uninstall.ml, otherlibs/site/test/github4389.t/dune, otherlibs/site/test/github4389.t/dune-project, otherlibs/site/test/github4389.t/main.ml, otherlibs/site/test/github4389.t/run.t, otherlibs/site/test/github4389_without_build_info.t/dune, otherlibs/site/test/github4389_without_build_info.t/dune-project, otherlibs/site/test/github4389_without_build_info.t/main.ml, otherlibs/site/test/github4389_without_build_info.t/run.t, otherlibs/site/test/run.t, test/blackbox-tests/test-cases/deprecated-library-name/features.t
=> dune-site should replace paths in "sections", not "sites"

bench/micro/fiber_bench.ml
And remove duplicated ivar benchmark
=> Add Fiber.Var benchmarks

src/fiber/fiber.ml, test/expect-tests/fiber/fiber_scheduler.ml
@jeremiedimino feel free to push the fix here.
=> test(fiber): simple test for Fiber.Scheduler

src/dune_rules/odoc.ml
Remove some useless code in odoc.ml. I removed it and observed no difference in behaviour. Looking at it, it doesn't seem useful: it's trying to produce rules for `_doc/_odoc/lib/...` by loading the rules for the corresponding library directory. I checked and this definitely doesn't produce rules in the `_doc` directory, which means that produced set of rules will simply be for nothing. It's probably some old stuff, from when we used to generate the `.odoc` files in the `_doc` folder.
=> Remove some useless code in odoc

dune, xdg.opam
=> fix(xdg): opam file

doc/instrumentation.rst
Signed-off-by: Christine Rose <professor.rose@gmail.com>
=> doc: instrumentation.rst

bench/micro/dune, bench/micro/memo_bench/benchmarks.ml, bench/micro/memo_bench/dune, bench/micro/memo_bench/memo_intf.ml, bench/micro/memo_bench/memo_tests_env.ml, bench/micro/memo_bench_main.ml, bench/micro/runner.sh
Add micro benchmarks for `Memo`. These were written by Arseniy inside Jane Street, I just copied and adapted them.
=> Add memo benchmarks

bench/bench.ml
So that the page gets easier to navigate after we add more benchmarks.
=> Reorganise benchmarks

CHANGES.md
(To avoid GitHub spamming during release.)
=> Use name in changelog for consistency

test/expect-tests/memo/memoize_tests.ml
While working on a fix for cutoffs with non-reproducible errors (see #5314), I noticed a strange behaviour in Memo: it appears that it some situations the early cutoff can be ineffective. This PR adds a test to demonstrate the problem.
=> Demonstrate a recomputation bug in Memo

src/dune_engine/source_tree.ml
Avoid an unnecessary call to `find_dir` by converting the `sub_dir` value at hand to a `Dir.t`.
=> Simplify implementation of nearest_dir

CHANGES.md, dune-project, dune.opam
@jonludlam @lubegasimon does the minimum version of odoc need to change?
=> chore: odoc CHANGES

src/fiber/fiber.ml, src/fiber/fiber.mli, test/expect-tests/fiber/fiber_tests.ml
Will complete the PR once I get an initial approval.
=> feature: Svar

doc/overview.rst
I encountered two small problems while reading through the first chapters of the Dune manual. Here are fixes in case they're wanted.
=> Small documentation fixes

test/expect-tests/fiber/fiber_tests.ml
Make the allocation tests more robusts. Instead of testing that we
allocated nothing, we should check that extra overhead is constant wrt
the number of elements.
@snowleopard do you have time to review this? It is extracted from #5230
=> test(fiber): allocation tests for parallel_iter

src/fiber/fiber.ml, src/fiber/fiber.mli, test/blackbox-tests/test-cases/coq/compose-cycle.t/run.t, test/blackbox-tests/test-cases/coq/compose-two-scopes.t/run.t, test/blackbox-tests/test-cases/coq/public-dep-on-private.t/run.t, test/blackbox-tests/test-cases/default-implementation/package-mismatch1.t/run.t, test/blackbox-tests/test-cases/deprecated-library-name/features.t, test/blackbox-tests/test-cases/enabled_if/eif-context_name.t/run.t, test/blackbox-tests/test-cases/enabled_if/eif-ocaml_version.t/run.t, test/blackbox-tests/test-cases/forbidden_libraries.t/run.t, test/blackbox-tests/test-cases/invalid-dune-package.t/run.t, test/blackbox-tests/test-cases/lib-errors.t/run.t, test/blackbox-tests/test-cases/lib.t/run.t, test/blackbox-tests/test-cases/libexec.t/run.t, test/blackbox-tests/test-cases/ocamldep-error-check.t, test/blackbox-tests/test-cases/optional-executable.t/run.t, test/blackbox-tests/test-cases/overlapping-deps.t, test/blackbox-tests/test-cases/ppx-runtime-dependencies.t/run.t, test/blackbox-tests/test-cases/virtual-libraries/github2896.t/run.t, test/blackbox-tests/test-cases/virtual-libraries/vlib-wrong-default-impl.t/run.t, test/expect-tests/fiber/fiber_tests.ml
=> New fiber implementation

test/expect-tests/dune_file_watcher/dune
I need to think about how to make them more reliable
=> chore(ci): disable flaky tests

CHANGES.md
=> [changes] Update CHANGES for 2.9.2 backports

test/blackbox-tests/test-cases/jsoo/no-check-prim.t/run.t, test/blackbox-tests/test-cases/jsoo/simple.t/run.t
the new jsoo compiler is outputting another command
=> test: promote for new jsoo

CHANGES.md, src/dune_rules/findlib/meta.ml, src/dune_rules/ocaml_version.ml, src/dune_rules/ocaml_version.mli
=> Meta: do not define bigarray library on OCaml >= 5

src/dune_rules/ocaml_version.mli
=> chore: fix odoc syntax

CHANGES.md
@jonludlam collaborated with @lubegasimon regarding https://github.com/ocaml/dune/pull/5045.
=> @jonludlam collaborated with @lubegasimon

src/dune_engine/build_system.ml
Just fixing a typo introduced in #5439.
=> Fix typo in comment

src/dune_rules/compilation_context.ml, src/dune_rules/compilation_context.mli, src/dune_rules/exe.ml, src/dune_rules/exe_rules.ml, src/dune_rules/inline_tests.ml, src/dune_rules/js_of_ocaml.ml, src/dune_rules/js_of_ocaml.mli, src/dune_rules/jsoo_rules.ml, src/dune_rules/jsoo_rules.mli, src/dune_rules/lib_rules.ml, src/dune_rules/module_compilation.ml
=> Refactoring: Introduce Js_of_ocaml.In_context

test/blackbox-tests/test-cases/pp-cwd.t/pp/dune, test/blackbox-tests/test-cases/pp-cwd.t/pp/pp.mll, test/blackbox-tests/test-cases/pp-cwd.t/run.t
make sure that we test where ppx's are executed (in the build context root)
=> test: add preprocessing + cwd test

src/fiber/fiber.ml
effect will be a keyword in that fork. Our effect is an internal type, so we can pick another name for it.
cc @kit-ty-kate @snowleopard
=> fix: restore compat with base-effect

dune-action-plugin.opam, dune-configurator.opam, dune-private-libs.opam, dune-project, dune-rpc-lwt.opam, dyn.opam, fiber.opam, stdune.opam
=> chore: update opam constraints

doc/concepts.rst
Signed-off-by: Eduardo Costa <m4c0@users.noreply.github.com>
Screenshot of the issue:
=> [Doc] Fix formatting of `Dependency Specification`

bin/rpc.ml
This is a remnant from old versions of rpc that relied on this
subcommand being used to initiate a session. This should no longer be
used anywhere.
=> fix: remove dune rpc init

dune.opam, dune.opam.template
=> chore: remove opam <2 special cases

otherlibs/stdune/fpath.ml, otherlibs/stdune/fpath.mli, otherlibs/stdune/monad.ml, otherlibs/stdune/monad.mli, otherlibs/stdune/monad_intf.ml, src/dune_rules/action_unexpanded.ml, src/memo/memo.ml, src/memo/memo.mli, test/blackbox-tests/test-cases/watching/fs-memo.t
No behaviour changes. Just a little clean up in a few places I spotted when doing the recent renaming. Plus updating a stale comment in a test whose output changed in #5556.
=> A minor clean up: fix typos, stale comments, move some code

CHANGES.md, vendor/spawn/src/spawn.ml, vendor/spawn/src/spawn_stubs.c, vendor/update-spawn.sh
=> fix: update spawn

doc/dune-files.rst, doc/foreign-code.rst, doc/hacking.rst, doc/instrumentation.rst, doc/opam.rst, doc/sites.rst, otherlibs/dune-rpc/private/types.ml, test/blackbox-tests/test-cases/dune-init.t/run.t, test/blackbox-tests/test-cases/github4821.t
=> Create dune lang 3.2

test/blackbox-tests/test-cases/github5555.t
This is the initial failing test, split from #5560.
=> Add failing test for #5555

src/dune_rules/dune_file.ml, src/dune_rules/module_name.ml, src/dune_rules/module_name.mli
=> fix: improve error message for bad lib name

CHANGES.md, doc/concepts.rst, src/dune_rules/blang.ml, src/dune_rules/blang.mli, test/blackbox-tests/test-cases/enabled_if-exec.t/run.t
=> feature: add [not] to blang

src/chrome_trace/chrome_trace.mli
Necessary for use in ocamllsp.
=> Introduce chrome-trace package

src/dune_stats/dune_stats.ml
Four optimizations:
* Use command line flags that make `lsof` faster.
* Stop checking for proc fs over and over.
* Stop leaking fd's
* Stop using temp files
=> Fix up slow fd counts on MacOS

src/dune_engine/install.mli
There isn't anything engine specific in them.
=> Move install rules  to dune rules

otherlibs/stdune/bool.ml, otherlibs/stdune/digest.ml, otherlibs/stdune/env.ml, otherlibs/stdune/hashtbl.ml, otherlibs/stdune/hashtbl.mli, otherlibs/stdune/path.ml, otherlibs/stdune/string.ml, otherlibs/stdune/tuple.ml, src/dune_config/dune_config.ml, src/dune_engine/dune_project.ml, src/dune_engine/execution_parameters.ml, src/dune_engine/process.ml, src/dune_lang/syntax.ml, src/dune_rules/context.ml, src/dune_rules/dune_env.ml, src/dune_rules/odoc.ml, src/dune_rules/super_context.ml, src/dune_rules/workspace.ml
consistent with the rest of the code base
=> refactor: replace Hashtbl.hash with Poly.hash

src/dune_engine/source_tree.ml
The stanza `(include ..)` accesses the file system and hence should live under `Memo.t` and use watch mode aware file access primitives.
=> Track `include` file access in dune files

src/dune_rules/action_unexpanded.ml, src/dune_rules/expander.ml, src/dune_util/value.mli
=> fix: make fmt

test/blackbox-tests/test-cases/mdx-stanza/paths.t
This includes repro cases for #5596.
=> mdx stanza: add test cases for paths

src/dune_rules/findlib/meta.ml
Fixes #5715 (corrects a bad refactor in #5691)
=> Fix regression from #5691

src/dune_engine/alias.ml, src/dune_engine/alias.mli, src/dune_rules/dep_conf_eval.ml, src/dune_rules/dep_conf_eval.mli, src/dune_rules/install_rules.ml
it's an implementation detail of the install rules
=> refactor(engine): move package install alias

src/dune_rules/exe.ml, src/dune_rules/jsoo_rules.ml, src/dune_rules/jsoo_rules.mli
add locations to all jsoo compilation commands
=> fix(jsoo): better locations

src/dune_engine/build_system.ml, src/dune_engine/dep.ml, test/blackbox-tests/test-cases/dune-cache/mode-copy.t, test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t, test/blackbox-tests/test-cases/dune-cache/repro-check.t, test/blackbox-tests/test-cases/dune-cache/trim.t
get rid of one seemingly unnecessary concatenation
=> refactor: make digest slightly more efficient

src/dune_rules/inline_tests_info.ml, src/dune_rules/lib.ml, src/dune_rules/preprocessing.ml, src/dune_rules/sub_system_info.ml, src/dune_rules/sub_system_name.ml, src/dune_rules/sub_system_name.mli
all sub system names must also be proper library names
=> refactor: add sub system name validation

CHANGES.md, boot/duneboot.ml, bootstrap.ml, src/dune_rules/findlib/meta.ml, src/ocaml-config/ocaml_config.ml, src/ocaml/version.ml, src/ocaml/version.mli
Updates Dune for compatibility with the changes proposed in ocaml/ocaml#11198.
=> Support new locations of unix, str and dynlink

src/dune_engine/load_rules.ml
@snowleopard perhaps we can pick a better name for `source_file_digest`?
=> Small cleanups

src/dune_engine/rule_cache.ml
I'm open to improvements in the wording of the error.
Also, do you think it is possible to cram test this?
=> better error when attempting link cache accross file system

otherlibs/stdune/predicate.ml, otherlibs/stdune/predicate.mli, otherlibs/stdune/stdune.ml, src/dune_engine/action_exec.ml, src/dune_engine/dep.ml, src/dune_engine/file_selector.ml, src/dune_engine/file_selector.mli, src/dune_engine/import.ml, src/dune_engine/vcs.ml, src/dune_lang/dune_lang.ml, src/dune_lang/glob.ml, src/dune_lang/glob.mli, src/dune_lang/predicate_lang.ml, src/dune_lang/predicate_lang.mli, src/dune_lang/predicate_with_id.ml, src/dune_lang/predicate_with_id.mli, src/dune_rules/check_rules.ml, src/dune_rules/coq_rules.ml, src/dune_rules/dep_conf_eval.ml, src/dune_rules/dune_file.ml, src/dune_rules/foreign_rules.ml, src/dune_rules/gen_rules.ml, src/dune_rules/import.ml, src/dune_rules/lib_file_deps.ml, src/dune_rules/simple_rules.ml
Split [Predicate] into [Predicate] and Predicate_with_id.
Sometimes we don't need the [id]. We can just ask for a simple predicate
in those cases.
=> refactor: split [Predicate]

src/dune_engine/build_system.ml, test/blackbox-tests/test-cases/watching/sandbox-mkdir.t
=> Remove mkdir memoization

src/dune_rules/dep_rules.ml, src/dune_rules/ocamlobjinfo.mli, src/dune_rules/ocamlobjinfo.mll
This shouldn't affect much, but it should give us a little extra safety
with the cache.
=> fix(rules): sandbox ocamlobjinfo

src/dune_rules/dep_conf_eval.ml, src/dune_rules/expander.ml, src/dune_rules/expander.mli, src/dune_rules/install_rules.ml, src/dune_rules/plugin_rules.ml, src/dune_rules/plugin_rules.mli, src/dune_rules/sites.ml, src/dune_rules/sites.mli, src/dune_rules/super_context.ml, src/dune_rules/super_context.mli
=> refactor(rules): move sites rules to [Sites]

otherlibs/dune-rpc/private/dune_rpc_private.ml, test/expect-tests/dune_rpc/dune_rpc_tests.ml
Fixes #5479 
Replaces #5480
cc @cwong-ocaml
=> Client side cancellation of long polling

src/dune_rules/artifacts.ml, src/dune_rules/context.ml, src/dune_rules/context.mli
* do not throw them away with the super context
* share lookups between contexts in the same directories
=> refactor(rules): speed up the which look ups

doc/papers/ocaml-2021/header.tex, doc/papers/ocaml-2021/memo.md, doc/papers/ocaml-2021/refs.csl
Jeremie suggested a few improvements and asked to move him to the Acknowledgements sections.
Merging without review.
=> Address Jeremie's feedback on Memo abstract

src/dune_rules/coq_lib.ml, src/dune_rules/coq_lib.mli, src/dune_rules/coq_rules.ml, src/dune_rules/coq_sources.ml, src/dune_rules/coq_stanza.ml, src/dune_rules/coq_stanza.mli, test/blackbox-tests/test-cases/coq/coqdoc-dir-target-clash.t/run.t
the location of the theory name and the location of the stanza aren't
the same.
I think overly brief code review comment was misinterpreted :)
=> fix(coq): revert location regression

CHANGES.md
=> [coq] Add changes for #5867

CHANGES.md, dune-project, ocamlc-loc.opam, otherlibs/ocamlc_loc/src/dune, otherlibs/ocamlc_loc/src/lexer.mll, otherlibs/ocamlc_loc/src/ocamlc_loc.ml, otherlibs/ocamlc_loc/src/ocamlc_loc.mli, otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml, src/dune_engine/compound_user_error.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml
Handle more formats, alerts, and format messages better.
=> Improve location parsing

src/dune_rules/only_packages.ml
filtering stanzas should only be done once per run.
=> fix(rules): address performance regression

src/dune_rules/context.ml, src/dune_rules/workspace.ml
These should be completely equivalent
=> refactor: unit table to lazy

CHANGES.md
=> Fix typo in changelog

otherlibs/action-plugin/src/dune_action_plugin.ml, otherlibs/action-plugin/src/import.ml, otherlibs/action-plugin/src/protocol.ml, otherlibs/action-plugin/src/protocol.mli
We don't qualify [Stdune] in our code base
=> chore(dap): do not qualify [Stdune]

CHANGES.md, bin/coqtop.ml, test/blackbox-tests/test-cases/coq/coqtop-nested.t/dune-project, test/blackbox-tests/test-cases/coq/coqtop-nested.t/run.t, test/blackbox-tests/test-cases/coq/coqtop-nested.t/theories/a/a.v, test/blackbox-tests/test-cases/coq/coqtop-nested.t/theories/b/b.v, test/blackbox-tests/test-cases/coq/coqtop-nested.t/theories/c.v, test/blackbox-tests/test-cases/coq/coqtop-nested.t/theories/d.v, test/blackbox-tests/test-cases/coq/coqtop-nested.t/theories/dune, test/blackbox-tests/test-cases/coq/coqtop-root.t/dune-project, test/blackbox-tests/test-cases/coq/coqtop-root.t/run.t, test/blackbox-tests/test-cases/coq/coqtop-root.t/theories/dune, test/blackbox-tests/test-cases/coq/coqtop-root.t/theories/foo.v
Subsumes #5868
Close #5868
Fix #5552
=> [coqtop] fix directory for subdirectory targets.

doc/coq.rst
This is the doc for #5695 <s>and relies on #5755 so draft for now.</s>
=> Add doc for coqdoc support

src/dune_rules/coq_rules.ml
We use Args.S instead of passing around lists
=> refactor(coq): tweak to argument handling

bench/bench.ml, bench/micro/dune_bench/scheduler_bench.ml, bin/build_cmd.ml, bin/common.ml, bin/common.mli, bin/diagnostics.ml, bin/import.ml, bin/rpc.ml, bin/rpc.mli, bin/subst.ml, src/dune_config/dune_config.ml, src/dune_config/dune_config.mli, src/dune_engine/process.ml, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_rpc_impl/server.ml, src/dune_rpc_impl/server.mli, test/expect-tests/csexp_rpc/csexp_rpc_tests.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_registry_test.ml, test/expect-tests/process_tests.ml, test/expect-tests/scheduler_tests.ml, test/expect-tests/timer_tests.ml, test/expect-tests/vcs_tests.ml
remove unnecessary params; simplify types
=> refactor(rpc): simplify running rpc

otherlibs/dune-rpc/dune_rpc.mli
useful information for clients to provide editors in some cases
ps-id: 56891a59-1371-4f27-b2cf-f0d8e45a6012
=> feature(rpc): allow accessing pid from client

src/dune_engine/build_system.ml
ps-id: 51b3ef1e-d9a7-4ae7-98d0-dc905605f46a
=> refactor(engine): add cutoff for anon actions

bin/ocaml_merlin.ml
ps-id: 5d7ce35e-299a-4186-80bf-4553e7cf4779
=> fix(merlin): allow scheduler to terminate

src/dune_rules/action_unexpanded.ml, src/dune_rules/dep_conf_eval.ml, src/dune_rules/link_flags.ml, src/dune_rules/ocaml_flags.ml, src/dune_rules/preprocessing.ml, src/dune_rules/super_context.ml, src/dune_util/value.ml, src/dune_util/value.mli
Add cutoffs to [Action_builder.memoize]
ps-id: e10c1e88-77e4-4c29-9b33-49566b4deb61
=> refactor(rules): add cutoffs

doc/concepts.rst
=> Doc: remove self-reference in Alternative Deps

src/dune_rules/coq_module.ml
ps-id: c1e47a8c-7b06-49df-b029-29240dd210cc
=> refactor(coq): do not hardcode ocaml extensions

test/blackbox-tests/test-cases/dune, test/blackbox-tests/test-cases/watching/dune
ps-id: 64532423-785e-4531-a312-8a3dd8e88d26
=> test: move watch mode settings to own test dir

src/dune_rules/compilation_context.ml, src/dune_rules/compilation_context.mli, src/dune_rules/exe_rules.ml, src/dune_rules/module_compilation.ml, test/blackbox-tests/test-cases/generate-sources.t
This seems like an artificial limitation at first glance.
=> test: generate executable sources in subdir

test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
ps-id: beb37073-d9b3-4e28-9ac2-91193ca208fd
=> test: do not pollute XDG_RUNTIME_DIR

bin/ocaml_merlin.ml, test/blackbox-tests/test-cases/merlin/merlin-from-subdir.t/run.t, test/blackbox-tests/test-cases/merlin/server.t/run.t
* Print error on bad inputs
* Handle Eof correctly
* Fix tests to actually interpolate the bash variables.
=> Various merlin fixes

src/dune_rules/preprocess.ml
ps-id: 3343d503-a617-4b2c-9353-4da1cf9c4ed9
=> style: remove unneeded module qualifications

test/expect-tests/fiber/fiber_tests.ml
ps-id: 06d7dedd-ce31-40f0-bcea-ad81fddc9173
=> test(fiber): improve test descriptions

test/blackbox-tests/test-cases/ppx-runtime-dependencies.t/run.t, test/blackbox-tests/test-cases/toplevel-stanza.t/preprocessors/dune
ps-id: efe0d4a0-671b-44d4-ba11-11673e449ce4
=> chore: test formatting

doc/dune-files.rst
=> Document how to generate { = version }

doc/dune-files.rst
=> Doc: files install mode only depends on section

doc/usage.rst
=> Doc: dune subst with no VCS does nothing

CHANGES.md, src/dune_rules/dune_file.ml, test/blackbox-tests/test-cases/github4401.t
=> Keep rules marked promote until-clean with -p

src/dune_engine/rule.mli
=> Fix position of some doc comments

otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml
ps-id: 7dac91cb-1c45-4b56-aed9-10a2d367e9d5
=> test(ocamlc-loc): more ocaml errors

otherlibs/chrome-trace/src/chrome_trace.ml, otherlibs/chrome-trace/src/chrome_trace.mli, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_engine/sandbox.ml, src/dune_engine/sandbox.mli, src/dune_engine/scheduler.ml, src/dune_engine/scheduler.mli, src/dune_stats/dune_stats.ml, src/dune_stats/dune_stats.mli
ps-id: 50198f48-67bb-4f8b-8e2c-daedd81973a6
=> feature: trace sandbox creation

src/dune_rules/module_compilation.ml
ps-id: 7dc158d5-3d5f-4846-9330-5104b9120d28
=> refactor: remove some module qualifiers

bin/subst.ml
ps-id: 63541b20-0f65-4721-88fb-043d4fdd6653
=> chore: make fmt

bench/micro/fiber_bench.ml
ps-id: 098d5c15-a008-4bf0-86b3-c09be506523e
=> bench(fiber): single ivar benchmark

src/dune_engine/sandbox.ml, test/blackbox-tests/test-cases/directory-targets/create-dir-with-symlink.t
ps-id: 9756e311-9e14-4fb4-9ee4-55576311f3ea
=> fix(dir-target): allow producing symlinks

CHANGES.md, src/dune_rules/menhir_rules.ml
ps-id: ba679cfd-9795-4bfb-902d-24ab89eaaf39
=> feature: sandbox menhir actions

test/blackbox-tests/test-cases/dune-init.t/run.t, test/blackbox-tests/test-cases/generate-sources.t, test/blackbox-tests/test-cases/jsoo/simple.t/run.t
ps-id: 0effa91b-3e55-46dd-8a2b-c8f95bba4307
=> test: remove useless test output

test/blackbox-tests/test-cases/several-packages.t/executable/dune, test/blackbox-tests/test-cases/several-packages.t/install/dune, test/blackbox-tests/test-cases/several-packages.t/run.t
ps-id: 22aecbc4-ce23-4f96-8c40-d992097e1b9f
=> test: better output

bin/coqtop.ml, bin/describe.ml, bin/exec.ml, bin/top.ml, bin/utop.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rules/context.ml
it's always ignored
ps-id: a27fc6ce-c70c-4dbe-be17-df4e8713d615
=> refactor: [build_file] do not return digest

src/dune_file_watcher/dune_file_watcher.ml
Paths excluded using the fsevents mechanism of `~exclusion_paths` only skip the children under these paths. This PR makes sure that we skip events that directly apply to paths in `~exclusion_paths` as well
=> fix(fsevents): remove build dir notifications

CHANGES.md, doc/concepts.rst, src/dune_rules/dune_file.ml, src/dune_rules/dune_file.mli, src/dune_rules/exe_rules.ml, src/dune_rules/foreign.ml, src/dune_rules/foreign.mli, src/dune_rules/lib_rules.ml, test/blackbox-tests/test-cases/foreign-objects/foreign-objects-compile-with-rule.t, test/blackbox-tests/test-cases/foreign-objects/foreign-objects-error-on-duplicate.t, test/blackbox-tests/test-cases/foreign-objects/foreign-objects-exe.t, test/blackbox-tests/test-cases/foreign-objects/foreign-objects-lib.t
Addresses https://github.com/ocaml/dune/issues/4129
Still need to update documentation, but want to get some feedback on the design first.
=> Support (foreign_objects ...) field

otherlibs/stdune/path.ml, otherlibs/stdune/path.mli, src/dune_engine/dune_project.ml, src/dune_engine/fs_memo.ml, src/dune_engine/fs_memo.mli, src/dune_engine/include_stanza.ml, src/dune_engine/load_rules.ml, src/dune_engine/package.ml, src/dune_engine/source_tree.ml, src/dune_engine/target_promotion.ml, src/dune_rules/artifacts.ml, src/dune_rules/context.ml, src/dune_rules/dune_load.ml, src/dune_rules/dune_package.ml, src/dune_rules/findlib/findlib.ml, src/dune_rules/findlib/meta.ml, src/dune_rules/findlib/meta.mli, src/dune_rules/foreign_rules.ml, src/dune_rules/simple_rules.ml, src/dune_rules/workspace.ml
ps-id: 0b6059b1-b94a-4e8a-9e1c-68f9e86ea427
=> refactor: use [Outside_build_dir.t]

src/dune_engine/rule_cache.ml
ps-id: 68dde42e-21ac-42f3-8041-5d06e0cd8256
=> chore: only allocate error message on error

src/dune_cache/local.ml
ps-id: af3ea039-4112-4bcf-b621-047ab460e9e3
=> refactor: remove duplicate function

otherlibs/ocamlc_loc/src/lexer.mli
ps-id: 65439b6f-a4a5-4f38-bab3-58d2e59e65e2
=> chore: add lexer.mli

src/dune_rules/ctypes_rules.ml, src/dune_rules/mdx.ml, src/dune_rules/toplevel.ml
ps-id: 4611267b-3f9f-4277-9528-1d295c5fcf67
=> refactor: a little deforestation of Path.Set

.github/workflows/workflow.yml
This allows the workflow to be run manually from a UI in github.
=> Add workflow_dispatch workflow trigger

test/blackbox-tests/test-cases/install-dir/install-libdir.t/dune
ps-id: d2122131-76f0-439d-963f-a991fa24e318
=> chore: fix indentation in tests

Makefile, test/blackbox-tests/test-cases/coq/compose-plugin.t/src_a/gram.mlg, test/blackbox-tests/test-cases/coq/compose-plugin.t/thy1/a.v, test/blackbox-tests/test-cases/coq/compose-plugin.t/thy2/a.v, test/blackbox-tests/test-cases/coq/ml-lib.t/src_a/gram.mlg, test/blackbox-tests/test-cases/coq/ml-lib.t/theories/a.v
Coq 8.16 has now been released.
=> [CI] start testing 8.16 version of Coq

test/blackbox-tests/test-cases/include-qualified/basic.t/dune, test/blackbox-tests/test-cases/include-qualified/basic.t/dune-project, test/blackbox-tests/test-cases/include-qualified/nested-lib-interface.t/dune, test/blackbox-tests/test-cases/include-qualified/nested-lib-interface.t/dune-project, test/blackbox-tests/test-cases/include-qualified/nested-virtual.t/dune-project, test/blackbox-tests/test-cases/include-qualified/pp.t/dune-project
they were using some old stuff that's no longer supported
ps-id: 301add05-a87a-49f8-bccb-6b31cd2d1332
=> test: fix qualified include tests

flake.nix
use "*" instead of null as we're told by opam-nix
ps-id: 7514f9bf-9624-496b-b357-9435a7b30f64
=> chore(nix): fix warnings

src/dune_rules/install_rules.ml
ps-id: 1979636a-13b5-452b-83c0-e2822b94ad63
=> refactor: remove module qualifiers

src/dune_cache/dune_cache.ml
ps-id: 0cf6fb53-c8c5-4b85-ad6a-e08657180a85
=> refactor: interface file for dune cache

CHANGES.md, src/dune_rules/cinaps.ml
ps-id: 1ab4ad8e-b4aa-4f3e-829b-d87c213c82f8
=> feature(cinaps): sandbox running cinaps actions

flake.lock, flake.nix
ps-id: 6fcb3422-1764-42dc-88bc-142380c4baa9
=> chore(nix): do not inherit nixpkgs from opam-nix

flake.lock, flake.nix
unbreaks running the expect tests in nix
ps-id: 007bea34-d120-4964-a6b3-5b7cb085c938
=> chore(nix): update to latest ocamllsp

src/dune_rules/exe_rules.ml, test/blackbox-tests/test-cases/github5787.t
=> Improve error if name of an exe is not in modules

src/dune_rules/coq_rules.ml
ps-id: 82c51d60-647a-44bd-aec8-1ff7495d4290
=> refactor(coq): minor tweaks

doc/coq.rst
This needs some testing.
Depends on #5755
cc @ejgallego
=> Doc for Coq plugins

CHANGES.md, doc/dune-files.rst, src/dune_rules/dune_file.ml, src/dune_rules/dune_file.mli, src/dune_rules/simple_rules.ml, src/dune_rules/test_rules.ml, test/blackbox-tests/test-cases/alias-multiple.t
We add support for multiple aliases for rules.
=> feature: multiple alias support in rules

CHANGES.md, doc/concepts.rst, src/dune_rules/dune_file.ml, src/dune_rules/dune_file.mli, src/dune_rules/exe_rules.ml, src/dune_rules/lib_rules.ml, test/blackbox-tests/test-cases/extra-objects/extra-objects-compile-with-rule.t, test/blackbox-tests/test-cases/extra-objects/extra-objects-error-on-duplicate.t, test/blackbox-tests/test-cases/extra-objects/extra-objects-exe.t, test/blackbox-tests/test-cases/extra-objects/extra-objects-lib.t
=> Rename foreign_objects to extra_objects

.dockerignore
ps-id: 8884110c-8356-45bc-9b06-2780fea3082f
=> chore: add dockerignore file

Makefile, dev.Dockerfile
ps-id: a84f5801-0c44-412e-af23-69561bb805d5
=> chore: add a docker dev file for development

flake.nix
ps-id: 6659be2d-72e9-4f5d-83f9-9b72699a576f
=> chore(nix): add ccls to dev tools

bin/import.ml, src/dune_engine/build_system.ml, src/dune_engine/build_system.mli, src/dune_rpc_impl/server.ml
Removed unnecessary API.
I wonder if it is worth somehow testing the output as a trailing log?
=> cleanup: Refactor build progress measures

src/dune_rpc_impl/server.ml
ps-id: 6c2ad0e1-5224-4193-a0fd-62993cac1c6e
=> refactor(rpc): trim some massive indentation

src/dune_rpc_impl/server.ml
ps-id: 0f42eb7a-b158-4864-82ee-b7f10085e89a
=> refactor(rpc): organize imports

bin/import.ml, bin/main.ml
ps-id: 9e170a9d-347c-4051-a3c2-0433e8a0878c
=> refactor: organize bin/import.ml

bin/build_cmd.ml
ps-id: 7d86954e-5caf-4772-aff0-5f99b6c04a4e
=> refactor: remove unnecessary qualification

test/expect-tests/digest/digest_tests.ml, test/expect-tests/digest/dune
@snowleopard looks like the tests were accidentally disabled. I enabled them and they were failing. The tests are now fixed.
=> test: enable digest tests

dev.Dockerfile
strace is needed for some watcher tests
ps-id: 78bda085-2e0a-4ab1-9c94-c4f3e29e176c
=> chore(docker): add strace

flake.lock
ps-id: 94eb8bee-43de-4c1b-beb3-42c6aaa08254
=> chore(nix): update flakes

flake.nix
=> Fix some errors in flake.nix

boot/duneboot.ml
Instead of deleting _boot, we clear it. This is a bit more friendly to
users of docker bind mounts.
ps-id: 5e0d4966-d5c5-4e40-a2d0-ca5679b74eec
=> refactor(bootstrap): improve clean

Makefile
it installs far too slow
ps-id: a9f58d67-052a-4d36-9018-61ac9bd81e59
=> test: remove coq from dependencies

Makefile, test/blackbox-tests/test-cases/coq/dune
ps-id: 4edd1734-0f46-4291-9c96-9eb31c5c9bfe
=> test(coq): guard behind env var

CHANGES.md, src/dune_rules/ctypes_rules.ml, src/dune_rules/ctypes_rules.mli, src/dune_rules/ctypes_stanza.ml, src/dune_rules/ctypes_stanza.mli, src/dune_rules/ctypes_stubs.ml, src/dune_rules/ctypes_stubs.mli, src/dune_rules/dune_file.ml, src/dune_rules/exe_rules.ml, src/dune_rules/foreign.ml, src/dune_rules/foreign.mli, src/dune_rules/foreign_rules.ml, src/dune_rules/foreign_sources.ml, src/dune_rules/lib_rules.ml, src/dune_rules/ordered_set_lang.ml, src/dune_rules/ordered_set_lang.mli, src/dune_rules/pkg_config.ml, src/dune_rules/pkg_config.mli, src/dune_rules/super_context.ml, src/dune_rules/super_context.mli, test/blackbox-tests/test-cases/ctypes/lib-return-errno.t/dune
Use the rules api directly to simplify the generation of rules
ps-id: 916c0c89-c6fc-416a-a3a9-032047f9aa37
=> refactor(ctypes): simplify rules further

doc/quick-start.rst, example/hello_world.t/README.org, example/with-configure-step.t/README.org
Addressed some concerns from [feedback](https://github.com/ocaml/dune/issues/5915), but there are still more to go. There are still some unanswered questions for which I'm awaiting answers. I will keep updating this file as I go, but I wanted to start a PR in case what I've done so far isn't accurate or needs more clarification. 
Signed-off-by: Christine Rose <professor.rose@gmail.com>
=> initial edits for quickstart, and slight edits in examples ReadMes

test/blackbox-tests/test-cases/inline_tests-byte.t
new test to reproduce #5515
Signed-off-by: Darius Foo <darius.foo.tw@gmail.com>
ps-id: 85f0f691-1c9b-4654-8394-3769f33992ed
=> test: running inline tests in bytecode mode

CHANGES.md, src/dune_rules/exe.ml, src/dune_rules/exe.mli, src/dune_rules/inline_tests.ml, test/blackbox-tests/test-cases/inline_tests-byte.t
Signed-off-by: Darius Foo <darius.foo.tw@gmail.com>
ps-id: 41266b17-d31e-491f-83b0-a3b818be4c80
=> fix: inline tests in bytecode mode

test/blackbox-tests/test-cases/rule/digest.t/pwd.ml, test/blackbox-tests/test-cases/rule/digest.t/run.t
ps-id: 2f20bba2-0d4b-4214-a4c1-ba87696409c6
=> test: digest tests should be reproducible

.gitignore
ps-id: dc9ec485-7899-4730-88a8-77f1243ef1ed
=> chore: ignore nix profiles

src/dune_rules/gen_rules.ml
ps-id: 6ee7c87a-f2d9-4e97-88f2-69e3f2abdd63
=> refactor: better scope

test/blackbox-tests/test-cases/dune-cache/mode-copy.t, test/blackbox-tests/test-cases/watching/dir-target-promotion.t, test/blackbox-tests/test-cases/watching/fs-memo.t, test/blackbox-tests/test-cases/watching/target-promotion.t
ps-id: 2896aaff-af43-41ec-80a5-82ec0c7024b8
=> chore: indentation fixes in tests

dev.Dockerfile, flake.nix, test/blackbox-tests/test-cases/dune
and update nix/docker dependencies
ps-id: e18306c8-c1ea-4694-94e1-655385e48258
=> test: add missing file deps

bench/perf.sh
ps-id: 6616532e-28ba-40be-aee7-0fabddd717ce
=> refactor: move perf.sh to bench

flake.nix
ps-id: d8570ac8-3fe1-4d1d-b7af-ba24527c98b1
=> chore(nix): ocamlformat version from .ocamlformat

flake.lock
ps-id: 80d0bb5d-e066-4bb0-be16-4674dce5b9cd
=> chore(nix): update

flake.lock, flake.nix
ps-id: 91e0b8c1-8800-4488-9234-6fff0e99231e
=> chore(nix): add melange to dependencies

.github/workflows/workflow.yml
=> chore: add Nix jobs to CI

flake.nix
needed for vcs_tests
ps-id: 528292c5-b407-4f95-84ba-20265db9c8f8
=> chore(nix): add mercurial test dep

chrome-trace.opam, dune-action-plugin.opam, dune-build-info.opam, dune-configurator.opam, dune-glob.opam, dune-private-libs.opam, dune-project, dune-rpc-lwt.opam, dune-rpc.opam, dune-site.opam, dyn.opam, fiber.opam, ocamlc-loc.opam, ordering.opam, stdune.opam, xdg.opam
ps-id: f4998a29-1b35-4cf8-8601-240247ecf039
=> chore: update dune-project to 3.5

doc/hacking.rst, doc/test/run.t
I have:
- Made sure line wrapping is consistent.
- Added a table of contents.
- Added information about Nix environments for devs.
=> refactor(doc): improvements to hacking.rst

.github/workflows/workflow.yml, flake.nix
This one should be much faster.
=> ci: rewrite fmt job

bin/build_cmd.mli
ps-id: d7e12ef8-aec7-41b0-ac3f-d0aa354bf2d9
=> refactor: remove private function from mli

src/dune_engine/sub_dirs.mli
ps-id: 5c4aa785-3263-4e1c-85ae-5ccf761f90c9
=> refactor: subdir_stanzas is now abstract

doc/index.rst
I've put the most important entries at the top and ordered the rest in alphabetical order.
=> doc: reorder index

doc/overview.rst
cc @christinerose could you take a look. I've reformatted the text to fit in the 80 char col and improved a few details here and there. This subsumes your PR in #5972.
=> doc: reformat and improve overview.rst

src/dune_engine/targets.ml
ps-id: 47677923-c4d9-42d3-a9a0-cf33894c8b83
=> refactor: deforest targets

src/dune_rules/exe.ml
=> refactor: improve error message

test/blackbox-tests/test-cases/ctypes/github-5561-name-mangle.t
ps-id: 16fe5009-f02b-438a-bc52-df7a623ee50b
=> test(ctypes): reproduce #5561

test/blackbox-tests/test-cases/watching/basic.t, test/blackbox-tests/test-cases/watching/copy-rules.t, test/blackbox-tests/test-cases/watching/dir-target-promotion.t, test/blackbox-tests/test-cases/watching/fs-memo.t, test/blackbox-tests/test-cases/watching/retriggering.t, test/blackbox-tests/test-cases/watching/sandbox-mkdir.t, test/blackbox-tests/test-cases/watching/target-promotion.t
ps-id: a2a4f641-08e1-4cda-9265-86e58f7ce7ac
=> refactor: replace bash with sh

CHANGES.md
ps-id: 605f2a89-ac8f-4efe-8fff-248426451801
=> chore: fix typo in CHANGES

src/dune_rules/ctypes_rules.ml
they aren't general enough to be useful
=> refactor(ctypes): inline some functions

CHANGES.md
ps-id: 535b635b-4376-4528-805a-ea63a3c188ce
=> chore: remove melange from CHANGES

bin/coqtop.ml
These were factored in #6192 but this was useless so we undo it.
=> refactor(coq): inline functions in coqtop

src/dune_engine/action.ml, src/dune_engine/action_exec.ml, src/dune_engine/action_intf.ml, src/dune_engine/action_mapper.ml, src/dune_rules/action_unexpanded.ml, src/dune_rules/coq_rules.ml, src/dune_rules/odoc.ml
The argument should be [target] instead of [path]
ps-id: 427b1e3d-afff-498a-810b-1c3d60f43eae
=> refactor: improve type of [Action.mkdir]

CHANGES.md, src/dune_rules/lib.ml, test/blackbox-tests/test-cases/private-package-lib/private-public-overlap.t
private libraries with (package ..) cannot depend on private libraries
without
ps-id: 91412a1c-5bfe-43e5-a0e9-41710af35c51
=> fix: incorrect private/public overlap check

src/dune_rules/gen_rules.ml
ps-id: b7a22b6e-02cd-4f82-8784-adf57513ed22
=> refactor: type annotated ignored argument

bin/clean.ml, src/dune_engine/target_promotion.ml, src/dune_engine/target_promotion.mli, test/blackbox-tests/test-cases/internal/dump.t
promotion targets are sources and they should be represented using this
type
=> refactor: promotion targets are sources

CHANGES.md
mention that concurrent dunes are forbidden
ps-id: a85a9358-bb68-4181-ae0f-0988ba433392
=> chore: update CHANGES

test/blackbox-tests/test-cases/dune
ps-id: 1164c0b2-b7c0-4048-9f57-6dd06da65afd
=> test: more accurate deps on dune_cmd

src/dune_rules/lib_flags.ml
ps-id: 8ddb7982-5094-48e8-ad0f-ecd86f157032
=> refactor(melange): share visible_cmi branch

.github/workflows/workflow.yml, .gitignore, Makefile, bench/bench.ml, bin/dune, boot/duneboot.ml, doc/hacking.rst, dune, dune.exe, dune.opam, dune.opam.template
* removes yet another generated file from the source repo
* we leave dune.exe as a shell script for user convenience
ps-id: 66b16903-5cf0-4b64-b1b5-e46e26df555a
=> refactor: move dune.exe binary to _boot

test/blackbox-tests/test-cases/melange/empty-entries.t, test/blackbox-tests/test-cases/melange/include_subdirs.t/inside/dune, test/blackbox-tests/test-cases/melange/intfonly.t/dune, test/blackbox-tests/test-cases/melange/mli.t/dune, test/blackbox-tests/test-cases/melange/multilib.t/dune, test/blackbox-tests/test-cases/melange/outside.t/inside/dune, test/blackbox-tests/test-cases/melange/private-module.t/dune, test/blackbox-tests/test-cases/melange/private.t/inside/dune, test/blackbox-tests/test-cases/melange/simple.t/lib/dune, test/blackbox-tests/test-cases/melange/target-validation.t
ps-id: ff8ea692-6c63-4412-a16f-655290a05eb0
=> test(melange): format stanzas properly

test/blackbox-tests/test-cases/include-qualified/basic.t/exe/dune
ps-id: 959d4c0e-cfa8-4597-9020-a4879fffb385
=> test: include-qualified tests misses dep

src/dune_rules/coq_stanza.ml, test/blackbox-tests/test-cases/coq/coqpp.t/dune-project, test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/dune-project, test/blackbox-tests/test-cases/coq/coqtop/coqtop-root.t/run.t, test/blackbox-tests/test-cases/coq/github3624.t
=> chore(coq): remove coq lang 0.7

src/dune_rules/exe_rules.ml, src/dune_rules/lib_rules.ml, src/dune_rules/melange_rules.ml, src/dune_rules/merlin.ml, src/dune_rules/merlin.mli
ps-id: dd7b4934-6201-4e65-bd10-ac7570d79c72
=> refactor: remove optional args in [Merlin.make]

src/dune_rules/ml_sources.ml, src/dune_rules/modules.ml, src/dune_rules/modules.mli
ps-id: eb5ed45c-d122-4f75-95ea-32f8026e6770
=> refactor: remove copied code in [Modules]

doc/hacking.rst
=> chore: tweak `hacking.rst` following `dune.exe` move to _boot

src/dune_rules/ctypes_rules.ml
ps-id: dfc69ea1-fb65-4e77-a74a-2a1e9d9163f8
=> refactor(ctypes): remove pesky aliases

src/dune_rules/module_compilation.ml, src/dune_rules/module_compilation.mli
ps-id: c154a84f-97bd-49ca-9b41-db7ea59d89ac
=> refactor: remove unused [flags] parameter

src/dune_rules/dir_status.ml
ps-id: 465b9475-5450-4f2a-96fa-ef772e0a0af5
=> refactor: status db style tweaks

doc/hacking.rst
ps-id: 9f127e90-1f3e-4489-81fe-844f7d2f86a9
=> doc: formatting tweak

flake.nix
ps-id: bf9c773a-d381-4f13-8118-fbcc4494605d
=> chore(nix): add patdiff

src/dune_rules/melange_rules.ml, src/dune_rules/melange_stanzas.ml, src/dune_rules/melange_stanzas.mli, test/blackbox-tests/test-cases/melange/promote-with-lib.t, test/blackbox-tests/test-cases/melange/promote.t
=> feat(melange): implement promotion for melange.emit

Makefile
remove redundant clean argument
ps-id: a1eb596f-7991-4a02-a804-5d67b83bc0d3
=> chore: makefile tweak

CHANGES.md
ps-id: eb079512-5f07-451b-8fa8-81636917613a
=> chre(CHANGES): allow dump-dot-merlin in watch mode

src/dune_rules/merlin.ml
the buffer is newly created
ps-id: bbe56f84-4776-4d41-aad4-9e902c7c1588
=> refactor: remove pointless Buffer.clear

otherlibs/site/test/run_2_9.t, test/blackbox-tests/test-cases/depend-on/installed-packages.t, test/blackbox-tests/test-cases/github1946.t/run.t, test/blackbox-tests/test-cases/github2206.t/run.t, test/blackbox-tests/test-cases/github759.t/run.t, test/blackbox-tests/test-cases/melange/merlin.t, test/blackbox-tests/test-cases/merlin/default-based-context.t/run.t, test/blackbox-tests/test-cases/merlin/github4125.t/run.t, test/blackbox-tests/test-cases/merlin/merlin-from-subdir.t/run.t, test/blackbox-tests/test-cases/merlin/merlin-tests.t/run.t, test/blackbox-tests/test-cases/merlin/per-module-pp.t/run.t, test/blackbox-tests/test-cases/merlin/src-dirs-of-deps.t, test/blackbox-tests/test-cases/merlin/symlinks.t/run.t, test/blackbox-tests/test-cases/merlin/unit-names-merlin-gh1233.t/run.t, test/blackbox-tests/test-cases/rule/dependency-external.t
shaves a process call
ps-id: c725c500-7da0-4432-9203-c9b21631ecb3
=> test: switch $(pwd) to $PWD

flake.lock, flake.nix
- In https://github.com/melange-re/melange/pull/440, I made melange incorporate the melange-compiler-libs flake, as they're tightly coupled
=> chore(nix): simplify obtaining melange

src/dune_rules/dune_file.ml, src/dune_rules/melange_stanzas.ml, src/dune_rules/preprocess.mli
ps-id: 34ed96cf-624e-42b4-9b5e-821ec9bcb928
=> refactor: random style fixes

src/dune_rules/buildable_rules.ml, src/dune_rules/cinaps.ml, src/dune_rules/pp_spec.ml, src/dune_rules/pp_spec.mli, src/dune_rules/preprocessing.mli, src/dune_rules/toplevel.ml, src/dune_rules/utop.ml
ps-id: 5ffeb6aa-76d2-49b9-b57b-c9f06b01ab3f
=> refactor: remove pointless [Memo.return]

bin/describe.ml, src/dune_rules/dune_rules.ml, src/dune_rules/preprocessing.ml, src/dune_rules/preprocessing.mli, src/dune_rules/virtual_rules.ml
ps-id: ecd04720-d468-407b-be96-65660cad7e72
=> refactor: share preprocessing code

src/dune_rules/link_time_code_gen.ml
ps-id: 74b4703c-079c-4810-8899-cb6b2d4024ff
=> refactor: reduce scopes

src/dune_rules/preprocessing.ml
helps get rid of a lot of nesting
ps-id: ca26f816-1d65-4875-831b-7a944bdb5951
=> refactor: introduce preprocessing helper

src/dune_engine/dialect.ml, src/dune_rules/preprocessing.ml
ps-id: adde099a-a1a8-4791-b2c5-56fe673ca371
=> refactor: simplify Dialect with Ml_kind.Dict.get

src/dune_rules/cinaps.ml, src/dune_rules/inline_tests.ml, src/dune_rules/link_time_code_gen.ml, src/dune_rules/mdx.ml, src/dune_rules/module.ml, src/dune_rules/module.mli, src/dune_rules/modules.ml, src/dune_rules/modules_field_evaluator.ml, src/dune_rules/preprocessing.ml, src/dune_rules/toplevel.ml
ps-id: 29e122e4-444b-4fba-b133-f1b526827d7b
=> refactor: remove Module.generated_{alias,root}

boot/dune
to make sure it works and get editor support
ps-id: 36fcb3f6-d9e2-4953-b979-6d332d8edbd8
=> chore: compile configure script

flake.lock
ps-id: 05371d73-3075-4b14-b56b-51077df3b0f4
=> chore: update nix

CHANGES.md
Signed-off-by: Etienne Millon <me@emillon.org>
=> Prepare 3.6.1

test/blackbox-tests/test-cases/formatting/format-alternative.t
currently broken
ps-id: f7334048-6ef7-4e17-84a7-8c5daeed7443
=> test: formatting of alternative dune files

Makefile, flake.lock, flake.nix, src/dune_rules/module_compilation.ml
@rgrinberg I tried to push to your branch in https://github.com/ocaml/dune/pull/6561 but I didn't have permission. Feel free to cherry-pick my commits to your branch.
- https://github.com/ocaml/dune/pull/6571/commits/edb7edef12b5566433d24af095a94bf74f36a593 updates the lockfile to get new melange after https://github.com/melange-re/melange/pull/458
- https://github.com/ocaml/dune/pull/6571/commits/e60e4e1021f2d942215a29ced1b995f1250ef419 updates the Makefile to pin the new required test deps
=> refactor(melange): remove bs specific flag 

test/blackbox-tests/test-cases/subdir-stanza/gh4907.t
ps-id: b7f92720-6f38-4525-be5b-73320f72467f
=> test: document test gh4907

otherlibs/configurator/test/blackbox-tests/dune
ps-id: 03d36cbe-0214-4bc1-8fc1-96c1309740ae
=> test: add pkg-config dependency

src/dune_rules/module_compilation.ml
ps-id: 9f434f4a-2f16-4061-8230-a3e49ff25162
=> refactor: simplify by passing alias module

src/dune_rules/modules.ml
ps-id: d96b047d-fb74-45bf-bada-9dc70551cec3
=> refactor: wrap modules in a single place

Makefile
ps-id: 3479b6bb-7894-4c86-80ff-e43a412c10bd
=> chore: remove result type dependency

Makefile
tested by running the command locally
=> fix: `make docker-build-image`

src/dune_rules/melange_binary.ml, src/dune_rules/melange_binary.mli, src/dune_rules/melange_rules.ml, src/dune_rules/merlin.ml, src/dune_rules/module_compilation.ml
=> fix(melange): add loc to `Melange_binary.{melc,where}`

src/dune_rules/gen_rules.ml
ps-id: 18e9e336-3026-43bf-87f0-62f1e25bfb76
=> refactor: gen_rules pattern matching

README.md
This makes it easier for people reading the source to use it as a README.
=> doc(README): rewrap paragraphs and cleanup links

README.md
appveyor was not working AFAIK.
=> doc: cleanup status badges in README.md

otherlibs/stdune/appendable_list.ml, otherlibs/stdune/appendable_list.mli, src/dune_rules/utop.ml
ps-id: b9901d95-dc30-4bff-a0a7-0776e32a8b38
=> refactor(stdune): Add Appendable_list.cons

test/blackbox-tests/test-cases/dune, test/blackbox-tests/test-cases/utop/dune
ps-id: f043a7ef-1f7e-413a-99e0-5f20b2932a0f
=> test: depend on utop

bin/top.ml, src/dune_rules/utop.ml
ps-id: c97579d0-5a78-41f1-b4b3-33be236aefcb
=> refactor: improve style of utop rules

test/blackbox-tests/test-cases/utop/lib-under-subdir.t
ps-id: 32e12c2e-a5ce-459c-8317-7dba44e4b17c
=> test: dune utop for (subdir ..)

test/blackbox-tests/test-cases/dune-cache/cache-man.t, test/blackbox-tests/test-cases/dune-cache/trim.t
=> test(cache): test output of man pages

test/blackbox-tests/test-cases/melange/dune
ps-id: 1665d7d8-9c8f-49fd-81e7-5fad009ae161
=> test(melange): add rescript_syntax dependency

test/blackbox-tests/test-cases/jsoo/dune
ps-id: 5ec5ccd7-559c-4ce0-959a-c01a0fbdb63a
=> test: add jsoo dependencies

doc/hacking.rst
=> doc: Add note about ignored let bindings to hacking.rst

otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/fiber_intf.ml
ps-id: 5497782f-88aa-453b-a241-8f6ece3ef766
=> refactor(rpc): remove some signature duplication

src/dune_rpc_server/dune_rpc_server.ml
delay the side effect until the fiber
ps-id: 69be80e0-52c4-4cc4-8cd4-936d64193719
=> refactor(rpc): purify notification sending

otherlibs/dune-rpc/private/versioned.ml, src/dune_rpc_server/dune_rpc_server.ml
move functor independent code outside of functor
ps-id: 22b8d898-9ad4-4a8b-9a8c-a6ce37639782
=> refactor(rpc): clean up versioning

otherlibs/dune-rpc/private/dune_rpc_private.ml, src/dune_rpc_server/dune_rpc_server.ml
ps-id: 16c08147-df8b-4266-b698-5baa9c1aea6c
=> refactor(rpc): improve scopes

otherlibs/dune-rpc/private/dune_rpc_private.mli
ps-id: 18d33a5b-197d-466a-8c52-b11c49dc63d7
=> refactor(rpc): remove pointless aliases

otherlibs/dune-rpc/private/menu.ml, otherlibs/dune-rpc/private/menu.mli, otherlibs/dune-rpc/private/versioned.ml
ps-id: 6f3f4c8b-9d1b-4545-b4fa-39ddea6b2c53
=> refactor(rpc): make menus abstract

otherlibs/dune-rpc/private/types.ml, otherlibs/dune-rpc/private/versioned.ml
ps-id: c56cb240-b972-40f5-a8fb-9327f110ec10
=> refactor(rpc): use Fun.id

otherlibs/dune-rpc/private/dune_rpc_private.ml, otherlibs/dune-rpc/private/types.ml, otherlibs/dune-rpc/private/types.mli
instead of resorting to raw strings or integers
ps-id: d27f7f00-0da3-4055-8305-1c4bc244fb57
=> refactor: use method/version functions

otherlibs/dune-rpc/private/dune_rpc_private.ml
if version initialization fails, terminate the connection cleanly
ps-id: b3645c0b-4c65-455c-b2ba-73da5f845993
=> fix(rpc): clean termination on server error

otherlibs/dune-rpc/private/dune_rpc_private.mli
ps-id: 31c786d3-0aea-4eb6-bda4-186b1f4ec14e
=> refactor: use Method.{Name,Version}.t aliases

otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml
ps-id: 2fd3a993-23ef-49bd-b4eb-c456aadbfbfa
=> test: demonstrate alerts failing to parse

otherlibs/stdune/ansi_color.ml, otherlibs/stdune/ansi_color.mli, otherlibs/stdune/user_message.ml, otherlibs/stdune/user_message.mli
We also add italic to ansi_color.
=> feature: italicise "Hint" in User_message

src/dune_rpc_impl/dune, src/dune_rpc_impl/import.ml, src/dune_rpc_impl/server.ml
This will break Tui
ps-id: 64b51901-28f8-4142-98d9-aadf7bcd66be
=> refactor(rpc): do not write errors to stderr direct

otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml
ps-id: 0cacb591-00d9-42b8-ab32-d98b186e1800
=> test(ocamlc_loc): multiple errors

otherlibs/ocamlc_loc/src/lexer.mll, otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml
ps-id: f078c9e0-a681-47f2-b223-9f57f9d1922b
=> fix(ocamlc_loc): remove leading space from alert

otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml
ps-id: fd6a7295-b6bb-42ae-8dab-d98396ca467a
=> test(ocamlc_loc): fatal alerts

bench/micro/dune_bench/scheduler_bench.ml, otherlibs/stdune/env.ml, otherlibs/stdune/env.mli, otherlibs/stdune/env_path.ml, otherlibs/stdune/env_path.mli, otherlibs/stdune/stdune.ml, src/dune_config/dune_config.ml, src/dune_engine/action_exec.ml, src/dune_engine/print_diff.ml, src/dune_engine/utils.ml, src/dune_engine/vcs.ml, src/dune_file_watcher/dune_file_watcher.ml, src/dune_rules/context.ml, src/dune_rules/cram_exec.ml, src/dune_rules/env_node.ml, src/dune_stats/dune_stats.ml, test/blackbox-tests/test-cases/github3766.t/test.ml, test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml, test/expect-tests/process_tests.ml, test/expect-tests/scheduler_tests.ml
To avoid the [Env] depending on [Path]
ps-id: ebe0f05f-9cff-4c9b-a617-508242f44830
=> refactor(stdune): introduce [Env_path]

src/dune_rules/lib.mli, src/dune_rules/melange_rules.ml, test/blackbox-tests/test-cases/melange/virtual_lib.t/run.t
ps-id: 67fdf1a3-a324-4bf6-a2d0-79e4f862576f
=> fix(melange): virtual library support

src/dune_engine/scheduler.ml
ps-id: 7e2ce692-752f-4d11-9500-6c024d221bc7
=> refactor: remove pointless alias

src/dune_rules/melange_rules.ml
ps-id: ff23868b-1a7d-4f00-af04-c759e94df926
=> refactor(melange): do not open Super_context

otherlibs/stdune/path.ml, otherlibs/stdune/path.mli
ps-id: 5ad17922-b880-4a49-9953-1da9514d838f
=> refactor(stdune): remove dead alias

otherlibs/dune-rpc/dune_rpc.ml, otherlibs/dune-rpc/dune_rpc.mli
use aliases instead
ps-id: 36ed2715-0a1b-448d-b893-db2db594024b
=> refactor(rpc): less destructive substitution

otherlibs/dune-rpc/private/dune_rpc_private.mli
ps-id: b01f7de7-630b-450a-bcda-29f68f48fa85
=> refactor(rpc): reorder [Client] and [Versioned]

src/dune_rules/context.ml
ps-id: 9d2b5917-051e-409d-87f3-44207adc1148
=> refactor: add name to configuration node

src/dune_rules/melange_rules.ml
ps-id: 3888fdf5-4b35-4cd1-a46c-f31fd42ac332
=> refactor(melange): tighter bindings

test/blackbox-tests/test-cases/version-corruption.t
ps-id: 988b2f1a-4481-4fd6-9d27-a1cd8747e095
=> test: update version-corruption test

test/blackbox-tests/test-cases/github6644.t
regression test for #6644
ps-id: 6c20e308-105c-4692-8417-2429de55c202
=> test: staged_pps and sandboxing

src/dune_rpc_server/dune_rpc_server.ml, src/dune_rpc_server/dune_rpc_server.mli
* add a finalizer that makes sure sessions are closed
* add Session.closed to determine when sessions are closed
ps-id: 32b83e8c-226e-45c3-806a-7fb413e34a0f
=> refactor(dune_rpc): simplify closing

src/dune_rules/melange_rules.ml
ps-id: 8aa48135-0f0e-49d0-a6e2-8d964b06b2f5
=> refactor(melange): clean up build_js calls

otherlibs/stdune/list.ml, otherlibs/stdune/list.mli
=> chore(stdune): remove rev_map_append

src/dune_rules/gen_rules.ml, src/dune_rules/melange_rules.ml, src/dune_rules/melange_rules.mli
.cmj and .js rules should be separated
ps-id: 6362ec95-ee71-4c56-97ac-8144b24a28e5
=> refactor(melange): separate rule loading

otherlibs/dune-rpc/private/dune_rpc_private.mli, otherlibs/dune-rpc/private/versioned.ml, otherlibs/dune-rpc/private/versioned.mli
ps-id: abb84e6b-e10c-4239-a2ba-96daf736bec1
=> refactor(rpc): add [Call.to_dyn]

src/dune_rpc_server/dune_rpc_server.ml
* Add printers to all session errors
* Use a custom type that includes only useful for information
ps-id: 3e878d0e-0b83-4d14-9491-e70555d7caac
=> refactor(rpc): invalid session errors

otherlibs/dune-rpc/private/dune_rpc_private.mli
=> refactor(rpc): make [Call.to_dyn] public

CHANGES.md, bin/top.ml
=> fix: correctly validate argument to top-module

otherlibs/stdune/id.ml, otherlibs/stdune/id.mli
We have mutable id fields in a couple of places.
=> refactor(stdune): make [Id.t] immediate

src/dune_rpc_server/dune_rpc_server.mli
ps-id: 593a35c8-93f4-4f5d-9678-808f4600dce1
=> refactor(rpc): remove unused Stage1 functions

bench/micro/fiber_bench.ml
Benchmark the Fiber.Pool implementation
=> chore(fiber): add pool benchmarks

test/expect-tests/fiber/fiber_tests.ml
Demonstrates that we incorrectly allow pools to run more than once
=> test(fiber): Pool tests

CHANGES.md, bin/cache.ml, test/blackbox-tests/test-cases/dune-cache/cache-man.t, test/blackbox-tests/test-cases/dune-cache/size.t/run.t, test/blackbox-tests/test-cases/dune-cache/trim.t
=> feature(cache): add `dune cache size` command

CHANGES.md, src/dune_rules/exe.ml
following/fix #6832 
A typo was introduced while refactoring #6832, this PR fixes it.
=> Fix jsoo linkall detection

src/dune_engine/format_config.ml, test/blackbox-tests/test-cases/formatting/empty-field.t
Very simple fix to issue #7016
Also adds a test.
=> Formatting stanza works with no arguments again (Fix #7016)

CHANGES.md, editor-integration/emacs/dune.el
Signed-off-by: Idir Lankri <ilankri@protonmail.com>
=> feature(emacs): auto-detect `dune-workspace` files as `dune` files

CHANGES.md, src/dune_console/dune_console.ml
=> fix(console): clean up console on exit

otherlibs/stdune/src/copyfile_stubs.c, otherlibs/stdune/src/io.ml, otherlibs/stdune/src/io.mli, src/dune_config/config.ml, src/dune_config/config.mli, src/dune_config_file/dune_config_file.ml
Use sendfile to copy files on Linux.
=> feature: optimize file copying on linux

src/dune_rules/ml_sources.ml, test/blackbox-tests/test-cases/github7600.t
fix https://github.com/ocaml/dune/issues/7600
=> fix: directory module name checking

CHANGES.md, src/dune_rules/local_install_path.ml
it was set to bin/ accidentally
=> fix: man dir for contexts

CHANGES.md
Signed-off-by: Etienne Millon <me@emillon.org>
=> Prepare 3.8.2

CHANGES.md, bin/describe/describe.ml
=> show: add Installed_libraries to show

bench/bench.ml, boot/libs.ml, doc/changes/8531.md, src/dune_engine/action_exec.ml, src/dune_engine/dune, src/dune_engine/execution_parameters.ml, src/dune_engine/execution_parameters.mli, src/dune_engine/process.ml, src/dune_engine/process.mli, src/dune_output_truncation/dune, src/dune_output_truncation/dune_output_truncation.ml, src/dune_output_truncation/dune_output_truncation.mli, src/dune_rules/artifact_substitution.ml, test/blackbox-tests/test-cases/github3490.t
=> feature: output truncation

src/dune_rules/expander.ml, test/blackbox-tests/test-cases/github7962.t
=> fix: forbid escaping the context root

doc/changes/copy-sandbox-dirs.md, src/dune_engine/sandbox.ml, test/blackbox-tests/test-cases/directory-targets/copy-sandboxing.t
Fixes #7724
Signed-off-by: Etienne Millon <me@emillon.org>
=> Add directory target support to copy sandbox

doc/changes/8948.md, src/dune_rules/package_db.ml, src/dune_rules/package_db.mli, src/dune_rules/super_context.ml, test/blackbox-tests/test-cases/eager-package-lookup.t
=> fix: load rules even if some packages aren't found

doc/changes/9914.md, doc/reference/foreign.rst, src/dune_rules/foreign.ml, src/dune_rules/foreign.mli, src/dune_rules/gen_rules.ml, test/blackbox-tests/test-cases/foreign-library.t
=> (foreign_library): support (enabled_if)

test/blackbox-tests/test-cases/pkg/hash-algos.t
Fixes https://github.com/ocaml/dune/issues/10134
=> pkg: add test for different hashing algos

src/dune_pkg/fetch.ml, src/dune_pkg/opamUrl0.ml, src/dune_pkg/opamUrl0.mli, src/dune_pkg/opam_repo.ml, src/dune_rules/fetch_rules.ml, test/blackbox-tests/test-cases/pkg/default-git-branch.t, test/expect-tests/dune_pkg/rev_store_tests.ml
=> fix(pkg): correctly rebuild packages when default branch changes

doc/coq.rst, doc/foreign-code.rst, doc/hacking.rst, doc/instrumentation.rst, doc/melange.rst, doc/sites.rst, otherlibs/dune-rpc/private/types.ml, test/blackbox-tests/test-cases/directory-targets/installed-dependency.t, test/blackbox-tests/test-cases/dune-init.t/run.t, test/blackbox-tests/test-cases/install/install-stublibs.t/run.t, test/blackbox-tests/test-cases/melange/basic-install.t, test/blackbox-tests/test-cases/pkg/implicit-dune-constraint.t, test/blackbox-tests/test-cases/pkg/pin-stanza/unknown-dune-version.t
=> feature: bump dune version to 3.15

src/dune_rules/exe_rules.ml, src/dune_rules/inline_tests.ml, src/dune_rules/jsoo/jsoo_rules.mli, test/blackbox-tests/test-cases/default-targets/bins.t/run.t, test/blackbox-tests/test-cases/jsoo/explicit-js-mode-specified.t/run.t, test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
=> Add rule for bc-for-jsoo target only when performing whole program compilation

CHANGES.md, doc/changes/10892.md, doc/changes/10953.md, doc/changes/11166.md, doc/changes/11172.md, doc/changes/11173.md, doc/changes/11234.md, doc/changes/11274.md, doc/changes/11307.md, doc/changes/11308.md, doc/changes/11402.md, doc/changes/11404.md, doc/changes/11437.md, doc/changes/11503.md, doc/changes/11504.md, doc/changes/11541.md
This PR is just the changelog for the alpha0 release of Dune before opening the main PR on opam.
=> [3.18] changelog for 3.18.0~alpha0
