src/dune_engine/build_system.ml
src/dune_engine/build_system.mli
src/dune_engine/target_promotion.ml
src/dune_engine/target_promotion.mli
src/dune_rules/artifact_substitution.ml
src/dune_rules/artifact_substitution.mli
src/dune_rules/main.ml
test/blackbox-tests/test-cases/directory-targets/main.t
test/blackbox-tests/test-cases/watching/dir-target-promotion.t

As discussed in #5202.
I also investigated the spurious errors in file-watching promotion test and clarified the reason by expanding the CR-someday.

Clean up promoted directory targets more aggressively

---

src/dune_engine/build_system.ml
test/blackbox-tests/test-cases/dir-target-dep.t/run.t
test/blackbox-tests/test-cases/directory-targets/main.t

Fixing a couple of outstanding CR-somedays for directory targets.
I tweaked the existing error message: we were printing the conflicting directory with the context bit (e.g. `default/dir`) for some reason.

Handle conflicts for directory targets

---

bin/workspace_root.ml
doc/usage.rst

As discussed in the last dev meeting this PR restore the old root detection behavior: Dune will keep looking for an outermost `dune-workspace` file instead of stopping on the first one.
This is necessary to have `dune ocaml-merlin` provide configuration for nested vendored project with their own workspace file.
Fixes #5187 
(partial revert of https://github.com/ocaml/dune/pull/4921)

Revert workspace detection

---

src/dune_rules/cxx_flags.ml
src/dune_rules/cxx_flags.mli
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/exe_rules.ml
src/dune_rules/foreign.ml
src/dune_rules/foreign.mli
src/dune_rules/lib_rules.ml
src/dune_rules/super_context.ml
test/blackbox-tests/test-cases/cxx-flags.t/baz.cpp
test/blackbox-tests/test-cases/cxx-flags.t/bazexe.cpp
test/blackbox-tests/test-cases/cxx-flags.t/dune
test/blackbox-tests/test-cases/cxx-flags.t/main.ml
test/blackbox-tests/test-cases/cxx-flags.t/quad.ml
test/blackbox-tests/test-cases/cxx-flags.t/run.t

In Dune 3.0 the option `use_standard_c_and_cxx_flags` will be enabled by default.
However an issue exist with the current implementations: all the default flags were provided at compile time and none during the link. Discussion about that issue can be found in PR #4846.
This PR fixes that by adding link time flags like `-lstdc++` or `-shared-libgcc` (depending on the detected compiler) to 
`ocamlmklib` and `ocamlc/opt` invocations when one or more stubs is in C++.
CC @recoules

Add default cxx link flags to `ocamlmklib` and  `ocamlc` calls

---

bin/target.ml
src/dune_engine/build_system.ml
test/blackbox-tests/test-cases/watching/dir-target-promotion.t

@jeremiedimino OK, I found a nice way to fix the CLI resolution problem for directory targets without any deep changes. Basically, I just flip the order of checks in `resolve_path`: first, check if `path` is a target, and only later check if there is a matching source dir. In this way, we don't turn directory targets into aliases.
I also added a CR-someday for `Pred.eval_impl` following our today's chat.

Fix CLI resolution of directory targets

---

otherlibs/stdune-unstable/path.ml
otherlibs/stdune-unstable/path.mli
src/dune_engine/build_system.ml
src/dune_engine/rule_cache.ml
src/dune_engine/rule_cache.mli

Move ~500 lines for dealing with the rule caches out of `build_system.ml`.
No change in behaviour apart from no longer sorting missing targets in errors.

Factor out rule cache logic into a separate module

---

bin/import.ml

Instead of:
```
Done: <done>/<total> (jobs: <jobs>)
```
print:
```
Done: <percent-done>% (<done>/<total>, <left> left) (jobs: <jobs>)
```
For instance:
```
Done: 10% (10/100, 90 left) (jobs: 20)
```
This is the style we use in Emacs inside Jane Street, and I like it a bit better than the one we currently have. In particular it's nice to see the percentage and the number of rules left.

Tweak the progress display

---

otherlibs/fiber-lwt/dune
otherlibs/fiber-lwt/fiber_lwt.ml
otherlibs/fiber-lwt/fiber_lwt.mli
src/fiber/fiber.ml
src/fiber/fiber.mli

@rgrinberg as promised, this adds a `Fiber.Scheduler` module for caller controlled execution. This PR comes with a `Fiber_lwt` module as bonus.

Add Fiber.Scheduler + Fiber_lwt

---

bin/exec.ml
bin/import.ml
bin/print_rules.ml
bin/target.ml
bin/utop.ml
src/dune_engine/action_builder.ml
src/dune_engine/build_system.ml
src/dune_engine/build_system.mli
src/dune_engine/dune_engine.ml
src/dune_engine/load_rules.ml
src/dune_engine/load_rules.mli
src/dune_engine/reflection.ml
src/dune_rules/gen_rules.ml
src/dune_rules/odoc.ml

The next step in breaking up `build_system.ml` into smaller pieces. Now adding `Load_rules`.
The only non-trivial bit of the split is that `build_system.ml` needs to call `Load_rules.set_current_rule_loc` to set the callback for resolving rule locations, for error messages.
After this PR, `build_system.ml` is down to "just" ~1000 lines.

Move load rules to separate module

---

otherlibs/stdune/digest.ml
otherlibs/stdune/digest.mli
src/dune_engine/build_system.ml
src/dune_engine/cached_digest.ml
src/dune_engine/cached_digest.mli
src/dune_engine/fs_cache.ml
src/dune_engine/fs_cache.mli
src/dune_engine/fs_memo.ml
src/dune_engine/fs_memo.mli
src/dune_engine/load_rules.ml
src/dune_engine/rule_cache.ml
src/dune_engine/target_promotion.ml
test/blackbox-tests/test-cases/watching/dir-target-promotion.t
test/blackbox-tests/test-cases/watching/fs-memo.t
test/blackbox-tests/test-cases/watching/target-promotion.t

While working on optimising watching as in #5233, I noticed that `Fs_memo.path_digest` is only called for files (not directories), so I'm changing the API to reflect that. This means it's sufficient to watch such queries only via the parent directory, so it simplifies the upcoming optimisation.
The first commit updates comments in `Fs_memo` and strengthens an assertion: `Fs_memo.init` is now only allowed to be called multiple times if `dune_file_watcher = None`.
The second commit does the actual change.

Do not allow to compute digests of directories via [Fs_memo]

---

otherlibs/configurator/dune
otherlibs/configurator/src/dune

Remove -alert=-unstable globally, not just for the library.

Fix build of configurator with 4.02.3

---

dune
otherlibs/configurator/dune

As discussed on Slack, it seems that Merlin behaves differently from the compiler when interpreting `alert` flags. As suggested by @voodoos, I'm tweaking the flags to help Merlin a bit. This solves the issue for me locally.

Fix alert flags so that Merlin understands them

---

src/dune_engine/rules.ml
src/dune_engine/rules.mli
src/dune_rules/dir_contents.ml

These don't seem useful. Instead, optimise `Rules.produce` when given an empty set of rules.

Remove Rules.produce_opt/collect_opt

---

src/dune_engine/dune_engine.ml
src/dune_engine/process.ml
src/dune_engine/process.mli

We need this for our internal Dune rules because we sometimes need to set `TMPDIR` to other locations.

Add a hook to [process.ml] for not overriding TMPDIR

---

Makefile
test/blackbox-tests/test-cases/odoc/warnings.t/run.t

Our CI jobs started failing with errors [like this](https://github.com/ocaml/dune/runs/4374419587?check_suite_focus=true).
This PR should fix things by switching to newer `odoc`.

Bump odoc lower bound to 2.0.1

---

src/dune_engine/fs_memo.ml
test/blackbox-tests/test-cases/watching/dir-target-promotion.t
test/blackbox-tests/test-cases/watching/fs-memo.t
test/blackbox-tests/test-cases/watching/what-dune-watches.t

This continues the work started in #5233: we now watch files by watching their parent directories.
The first commit moves the code around to prepare the change, the second commit makes the change, the third one does some clean up and simplification.

Watch files via parent

---

otherlibs/stdune/map.ml
otherlibs/stdune/map_intf.ml
src/dune_engine/build_system.ml
src/dune_engine/rule_cache.ml
src/dune_engine/targets.ml
src/dune_engine/targets.mli
test/blackbox-tests/test-cases/directory-targets/main.t

This fixes handling of directory targets when looking them up in the workspace-local cache. Alas, as the error message in the test indicates, we are still getting cache misses because we actually clean up directory targets in `Load_rules.load_dir`.

Fix workspace-local cache for directory targets

---

src/dune_rules/cinaps.ml
src/dune_rules/compilation_context.ml
src/dune_rules/compilation_context.mli
src/dune_rules/ctypes_rules.ml
src/dune_rules/ctypes_rules.mli
src/dune_rules/dep_rules.ml
src/dune_rules/dep_rules.mli
src/dune_rules/exe.ml
src/dune_rules/exe.mli
src/dune_rules/exe_rules.ml
src/dune_rules/inline_tests.ml
src/dune_rules/lib_rules.ml
src/dune_rules/link_time_code_gen.ml
src/dune_rules/mdx.ml
src/dune_rules/menhir.ml
src/dune_rules/module_compilation.ml
src/dune_rules/module_compilation.mli
src/dune_rules/modules.ml
src/dune_rules/modules.mli
src/dune_rules/ocamldep.ml
src/dune_rules/ocamldep.mli
src/dune_rules/odoc.ml
src/dune_rules/odoc.mli
src/dune_rules/preprocessing.ml
src/dune_rules/toplevel.ml
src/dune_rules/utop.ml

`Compilation_context` represents all the compilation information for a set of modules, so it seems natural to put the dependency graphs there. This simplify the code as it removes a lot of passing along of the dep graphs manually and will help with another PR I'm working on.

Add module dependency graphs to Compilation_context.t

---

bin/install_uninstall.ml
otherlibs/action-plugin/src/dune_action_plugin.ml
otherlibs/stdune/dune_filesystem_stubs/dune_filesystem_stubs.ml
otherlibs/stdune/dune_filesystem_stubs/dune_filesystem_stubs.mli
otherlibs/stdune/stdune.ml
src/dune_cache_storage/layout.ml
src/dune_engine/load_rules.ml
src/dune_engine/rule_cache.ml
src/dune_engine/source_tree.ml
src/dune_engine/target_promotion.ml
src/dune_util/report_error.ml
test/blackbox-tests/test-cases/directory-targets/main.t
test/blackbox-tests/test-cases/unreadable-src.t/run.t
test/blackbox-tests/test-cases/watching/fs-memo.t
test/expect-tests/dune_action_plugin/dune_action_test.ml

As suggested by @jeremiedimino, I'm making the way we print Unix errors more uniform.
This also addresses a few CR-somedays in the code.

Print Unix errors uniformly

---

src/dune_engine/build_system.ml
src/dune_engine/build_system.mli
src/dune_engine/install.ml
src/dune_engine/install.mli
src/dune_engine/rules.ml
src/dune_engine/rules.mli
src/dune_engine/subdir_set.ml
src/dune_engine/subdir_set.mli
src/dune_rules/gen_rules.ml
src/dune_rules/install_rules.ml
src/dune_rules/install_rules.mli
src/dune_rules/opam_create.ml
src/dune_rules/opam_create.mli
test/blackbox-tests/test-cases/reporting-of-cycles.t/run.t

We were generating the following rules for every single directory, which is a waste of CPU:
- all the rules for generation the opam files for all packages in the worksapce
- all the rules for generating the `META` and `dune-package` files for all packages in the workspace
Now, we generate them only once at the root of each project, and only for the packages of the project.
I also refactored a bit `install_rules` to split the generation of files inside `_build/default` and `_build/install`, and also to avoid unnecessary bouncing between `Rules.produce` and `Rules.collect`.
After this, we could split `install_rules.ml` between:
- the computation of the install entries
- the symlink rules
- the generation of the <package>.install files
- the generation of the META and dune-package files

Stop generation the same rules over and over

---

bin/help.ml

Autodetection was implemented in 53202d0a09 for #530, but this piece of doc was
not updated.
Signed-off-by: Paolo G. Giarrusso <p.giarrusso@gmail.com>

dune-config docs for jobs: document autodetection

---

src/dune_engine/build_system.ml
src/dune_engine/sandbox_mode.ml

The only way to select sandboxing with hardlinks is via the command line. If people do that, we can assume they know what they are doing.

Remove error about sandboxing with hardlinks not working on Windows

---

src/dune_engine/build_config.ml
src/dune_engine/build_system.ml
src/dune_engine/sandbox_config.ml
src/dune_engine/sandbox_config.mli
src/dune_engine/sandbox_mode.ml
src/dune_engine/sandbox_mode.mli
src/dune_rules/dune_file.ml
src/dune_rules/simple_rules.ml
test/blackbox-tests/test-cases/patch-back-source-tree.t

As discussed [here](https://github.com/ocaml/dune/pull/5271#discussion_r762006776), listing `patch_back_source_tree` in default sandboxing preferences is odd because Dune might pick it up as a sensible sandboxing mode. It should only be allowed via an explicit opt-in by writing `(mode patch-back-source-tree)`.

Remove [patch_back_source_tree] from default sandboxing preferences

---

src/dune_engine/build_config.ml
src/dune_engine/build_config.mli
src/dune_engine/load_rules.ml
src/dune_engine/load_rules.mli
src/dune_rules/dir_contents.ml
src/dune_rules/dir_contents.mli
src/dune_rules/format_rules.ml
src/dune_rules/format_rules.mli
src/dune_rules/gen_rules.ml
src/dune_rules/install_rules.ml
src/dune_rules/odoc.ml
src/dune_rules/odoc.mli
src/dune_rules/only_packages.ml
src/dune_rules/only_packages.mli
src/dune_rules/packages.ml
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli
src/dune_rules/toplevel.ml
src/dune_rules/utop.ml
src/dune_rules/utop.mli
test/blackbox-tests/test-cases/lib-errors.t/run.t
test/blackbox-tests/test-cases/ppx-runtime-dependencies.t/run.t

Up to know, there were complex and mostly unknown and unchecked invariants for producing the build rules. This PR replaces them by saner and checked invariants:
- `gen_rules ~dir` is only allowed to produce rules for descendant of `dir`. This is now checked
- a directory can declare that its parent will generate its rules by having `gen_rules` return `Redirect_to_parent`
There is still an opportunity for messing things up: if `gen_rules ~dir` produces rules for a descendant `dir'` and `gen_rules ~dir:dir'` doesn't return `Redirect_to_parent`, then these rules will simply be lost. In the future, I would like to change things so that the rules for a directory are the union of all the rules generated in this directory by all the calls to `gen_rules` on the ancestor of the directory. This …

Tighten the rule generation API

---

src/dune_engine/fs_memo.ml
test/blackbox-tests/test-cases/symlink-targets.t/run.t
test/blackbox-tests/test-cases/watching/fs-memo.t
test/blackbox-tests/utils/dune_cmd.ml

Demonstrate that Dune currently has a couple of issues with symbolic links:
* Promoting a symbolic link turns it into a regular file.
* Dune sometimes doesn't rebuild when a watched symbolic link changes.

Demonstrate a few issues with handling symbolic links

---

doc/dev/directory-targets.md

I'd like to have a canonical doc describing directory targets, so I can link to it, and it's weird to keep linking to the RFC #3316 since it will eventually get out of date. It's best to keep the doc next to the code, so they can evolve together.
Here is the [rendered version](https://github.com/ocaml/dune/blob/df979371599db03e01603b70f54157755107a2a4/doc/dev/directory-targets.md).

Add a doc on directory targets

---

src/dune_cache/local.ml

We've been occasionally getting some shared cache errors mentioning `EEXIST` and `link` when running large builds internally. I've finally managed to debug this: apparently the code path that handles the "too many links" error in the shared cache had a silly error which rendered this code path useless. This PR fixes the error and adds some comments.
You might wonder: how can 65000 links be not enough for the shared cache? It turns out we build a lot of empty files which all link to the same entry in the shared cache. These are mostly empty lists of dependencies stored in `.d` files.
I tested this manually. I can't come up with a reliable and not super slow test to add to CI.

Fix handling of "too many links" error in the shared cache

---

dune.opam
dune.opam.template

there's no reason to filter out other pacakges with -p as dune depends
on them
Fix #5190

fix: release build of dune

---

otherlibs/stdune/path.ml
otherlibs/stdune/path.mli
src/dune_cache/local.ml
src/dune_engine/cached_digest.ml
src/dune_engine/diff_promotion.ml
src/dune_engine/sandbox.ml
src/dune_engine/target_promotion.ml

I realised that my previous PR #5300 actually changed behaviour (we started setting write permissions for all users!), so to avoid such mistakes in future, I'm making the type abstract and the comments, hopefully, clearer.

Make permissions abstract

---

otherlibs/stdune/digest.ml
otherlibs/stdune/path.ml
otherlibs/stdune/path.mli
src/dune_cache/local.ml

Clean up bit fiddling with the execute permission bit.
The CI failure is unrelated.

Use [Path.Permissions] for execute permissions too

---

src/dune_engine/scheduler.ml

While debugging a large performance regression that we were seeing in our internal incremental builds, I found that #5181 made our incremental builds very slow in the case where Dune receives multiple file-system events in quick succession (which does often happen in practice, e.g. when creating new files).
The idea of calling `check_cancelled t` was to save some work by raising the `Build_cancelled` exception during Memo node recomputation. This does save the work but also destroys early cutoffs (we throw away earlier successes and replace them with `Build_cancelled` exceptions), which means the next build is going to be very slow.
The change in this commit fixes the regression, but of course we want to find a way to keep the `check_cancelled t` optimisation: we just need to preserve …

Fix Dune performance regression in incremental builds

---

src/memo/memo.ml
src/memo/memo.mli
test/expect-tests/memo/memoize_tests.ml

This fixes the issue reported in #5320. It turned out to be not so mysterious after all: before this PR, we forgot the old value when invalidating a Memo node. There was a CR-someday to change this, which is what this PR does.
(I left some debugging infrastructure I used to debug this issue on purpose.)

Preserve the old value when invalidating Memo nodes

---

doc/test/run.t

Looks like #5045 broke some tests on CI? This PR tries to fix them by `dune promote`.

Update doc tests

---

doc/foreign-code.rst
src/dune_rules/ctypes_rules.ml
src/dune_rules/ctypes_stanza.ml
src/dune_rules/ctypes_stanza.mli
test/blackbox-tests/test-cases/ctypes/exe-vendored-preamble.t/dune
test/blackbox-tests/test-cases/ctypes/exe-vendored.t/dune

Allows ` (headers (preamble "#include %{read:preamble.sexp}"))` and `(headers (include (:include includes.sexp)))` and add documentation for `headers`

Allow variables in ctypes headers

---

src/dune_engine/sub_dirs.ml
test/blackbox-tests/test-cases/vendor/main.t/run.t

Make it more generic against the list of statuses. This is to prepare for an upcoming feature adding a new directory status (for generated directories).
There is no change in behaviour except for the ordering of statuses in error messages. I didn't try to preserve it since any order works fine.

Refactor Sub_dirs.eval

---

test/blackbox-tests/test-cases/directory-targets/copy-files.t

This tests is aimed at exposing an issue with directory targets. Fixing the issue makes the test fail with a dependency cycle that is very difficult to remove without deep changes in Dune.
This commit adds another test that doesn't have this problem.

Extend the directory-targets/copy-files.t test

---

src/fsevents/fsevents_stubs.c

make sure runloop pointer is always registered

fix(fsevents): invalid gc usage

---

bin/describe.ml

Made explicit the type definitions that represent the information that
is dumped about the workspace. Translation to the Dyn.t type happens
as a second stage.
The goal of this commit is hopefully to make users' life easier in
decoding the S-expressions into meaningful contents, and to make it
easier to extend the features of ``dune describe`` in the future.
Signed-off-by: Benoît Montagu <benoit.montagu@inria.fr>

Minor code cleanup for ``dune describe``

---

Makefile

The command "[[ ... ]]" is supported by bash, but not by sh or dash
(these shell are used by default in Ubuntu, for example).
Signed-off-by: Benoît Montagu <benoit.montagu@inria.fr>

Fixed Makefile so that the dev-switch rule works with a shell different than bash

---

CHANGES.md
src/dune_lang/t.ml
src/dune_rules/colors.ml

This PR consists in 2 cherry-picked commits about compatibility with current trunk, related to the format API.

[2.9] Compatibility with OCaml 5.0

---

test/blackbox-tests/test-cases/directory-targets/copy-files.t

ls output is not portable across gnu and bsd userland

test: fix mac compat for copy-files

---

CHANGES.md
plugin/jbuild_plugin.ml
src/dune_rules/assets.ml

I did some brief testing on my side, but would appreciate confirmation from some other dev (especially if this is not being tested in the CI).

Restore compatibility with 4.02

---

dune-configurator.opam
dune-project
otherlibs/configurator/src/dune

we don't support 4.03 anyway, so compatibility isn't needed.

chore: remove result from configurator

---

Makefile

This option has been removed from current dune-release and I
understand it should not be needed. Review from an expert would be
much appreciated.

[release] Remove deprecated -n option in the dune-release make target

---

CHANGES.md
bin/common.ml

https://github.com/ocaml/dune/issues/5369
If `--diff-command` is used, use this.  
Otherwise, if `DUNE_DIFF_COMMAND` is set, use this.  
Otherwise use the same default as before.

support `DUNE_DIFF_COMMAND` environment variable

---

CHANGES.md
bootstrap.ml

The `bootstrap.ml` script tries to remove generated files when it exits. It does so by calling `Sys.remove`. Unfortunately, `Sys.remove` cannot remove directories, and on Macos the C compiler and linker generate a directory (in this case, `.duneboot.exe.dSYM`) to hold debugging information. This breaks `make release`.
To reproduce, just run this on Macos:
```
OCAMLPARAM=_,cclib=-g make release
```
To solve this problem, the best solution is to just ignore errors when removing the generated files.

bootstrap.ml: ignore errors when trying to remove generated files

---

.github/workflows/ci.ml

String.concat requires a label

chore: fix warning ci.ml

---

doc/tests.rst

This is a simple adjustment, the `test.output` should really be `tests.output`, as defined in the previous code snippet here:
```
(rule (with-stdout-to tests.output (run ./tests.exe)))
(rule
(alias runtest)
(action (diff tests.expected test.output)))
```

Fix a typo in the documentation's diff test section

---

otherlibs/stdune/user_message.ml

do not raise when error doesn't have an "Error: " prefix. This isn't a
bug (at least with our current errors), but it's fragile because this
function is sometimes used for debugging

refactor: User_message.to_string

---

CHANGES.md
src/dune_rules/findlib/meta.ml
src/dune_rules/ocaml_version.ml
src/dune_rules/ocaml_version.mli

They all have their own opam package and were never defined in neither the compiler on ocamlfind.
`result` was removed from dune 3.0 for the same reason, I think uchar and seq should probably go too.

Remove uchar and seq dummy modules

---

CHANGES.md
Makefile
src/dune_rules/mdx.ml
test/blackbox-tests/test-cases/mdx-stanza/env-variables.t

Since realworldocaml/mdx#366, the executable output by `ocaml-mdx dune-gen` supports `MDX_RUN_NON_DETERMINISTIC` like `ocaml-mdx test` itself. Dune needs to know about that to rerun the tests if the variable has been set in the meantime.

mdx stanza: record env var dependency

---

doc/dev/rpc-versioning.md

fix some minor typos in `doc/dev/rpc-versioning.md`

fix typos in documentation

---

test/blackbox-tests/test-cases/watching/what-dune-watches.t

I guess the order and repeated entries don't matter, so let's dedup and sort.

Make what-dune-watches tests more reproducible

---

src/dune_engine/action_exec.ml
src/dune_engine/build_system.ml
src/dune_engine/execution_parameters.ml
src/dune_engine/execution_parameters.mli
test/blackbox-tests/test-cases/dune-cache/mode-copy.t/run.t
test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t/run.t
test/blackbox-tests/test-cases/dune-cache/repro-check.t/run.t
test/blackbox-tests/test-cases/dune-cache/trim.t/run.t

This breaks existing ppx rewriters which rely on real paths existing in
build artifacts.

fix: disable build path prefix map pre 3.0

---

test/blackbox-tests/test-cases/deps-conf-vars/dynamic.t

as discussed, we enabled dyn deps in some places but forgot to do it everywhere applicable.

test: demonstrate limited dyn deps

---

doc/dune-files.rst

It is a bug that asking again to build a directory targets with unchanged dependencies rerun the action, right?

Document the limitation of directory targets

---

CHANGES.md
src/dune_rules/ocaml_flags.ml

In particular, warning 70 is very annoying
cc @c-cube

fix warnings

---

doc/tests.rst

In the `Testing an OCaml Program` section about cram tests, there was a `tab`
being used instead of spaces. It might seem fine when edited with a tab-stop
setting of `4` but the markup parser translates it to 8 spaces. To avoid this
kind of issues (and because consistency feels nice) I changed it to spaces.
Signed-off-by: Eduardo Costa <m4c0@users.noreply.github.com>
Screenshot of the issue:

[doc] Minor formatting issue

---

doc/concepts.rst

introduced after https://github.com/ocaml/dune/commit/23cff6ebebabd6a894955611f86a39299d5f5ad5#diff-9718f66e50394e604b467ec4a30f1dfd922b22cb141da906961faacf359b8e61R613-R615
cc @rgrinberg

fix(docs): Move `(include <file>)` documentation after sandbox doc

---

doc/dune-files.rst

To show that names by themselves can be dependencies, e.g.
```
(depends
abc
def...
```

Update dependency syntax spec

---

otherlibs/xdg/xdg.ml

From the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
> If `$XDG_DATA_HOME` is either not set or empty, a default equal to
> `$HOME/.local/share` should be used.
and this is also true for the other env vars.

xdg: default value if env var is either not set or empty

---

otherlibs/xdg/xdg.ml

From the [XDG Base Directory Specification][1]:
> All paths set in these environment variables must be absolute. If an
> implementation encounters a relative path in any of these variables
> it should consider the path invalid and ignore it.
If the env var is empty, `Filename.is_relative` returns `true`, so this is
a more general case that I missed in #5510.
cc @nojb 
[1]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

xdg: default value if env var is not absolute

---

CHANGES.md
otherlibs/stdune/fpath.ml
otherlibs/stdune/fpath.mli
otherlibs/stdune/path.ml

esy uses `DUNE_BUILD_DIR` pointing to an absolute directory, but since https://github.com/ocaml/dune/commit/0f31294fe7eb361f7bfe1b9c4bc8cb54e8ad7f41 dune rejects removing any absolute directory, as a new checking was added.
Leading to `dune clean` to fail, and also basic functionality such as `dune build -w`.
This PR removes the checking, as the patch was likely a mistaken and not all absolute directories are external.

fix `dune clean` on esy

---

doc/concepts.rst
doc/dune-files.rst
doc/hacking.rst
doc/migration.rst
doc/quick-start.rst
doc/tests.rst

This fixes missing refs, bad markup, etc. This makes `make doc` clean.

Various markup fixes

---

doc/tests.rst

I had difficulty to figure out how to run a single Cram test (my codebase has a lot of tests and if I add e.g. a debug print all kinds of tests fail, thus filling my terminal with a lot of noise) so I thought it would be good to add this info for future users and future me to know.
I assumed the process would be like it is, but instead of `dune build @alias` I mistakenly used `dune runtest @alias` which did not do what I thought.

Add documentation on how to run a single cram test

---

test/blackbox-tests/test-cases/expand-make.t

The logic we're testing is that `make` is picked if `gmake` is not in `PATH`. This is hard to to test if `gmake` is already in `/usr/bin` or the like. So a more precise setup is used.

expand-make.t: handle case where gmake is in PATH

---

CHANGES.md
otherlibs/stdune/proc.ml
test/blackbox-tests/test-cases/exec-cmd.t/run.t

The `.db` of the wrong `_build` was modified when using `--root` with `dune exec`.

Fix dune exec dump in wrong directory

---

CHANGES.md
src/dune_rules/coq_rules.ml
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/a/a.v
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/a/dune
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/dune-project
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/run.t

This should help reduce the coqdep calls drastically.
Improves #5100 .
In particular, while a build from scratch has still one coqdep call per file overhead, incremental builds don't anymore. This makes one coqdep call per theory (or `-modules`) much less critical.

[coq] Ignore contents in coqdep rule

---

src/dune_engine/action_builder0.ml
src/dune_engine/build_system.ml
src/dune_rules/dir_status.ml
src/memo/memo.ml
src/memo/memo.mli

As discussed with @rgrinberg, we're renaming `Memo.t` to `Memo.Table.t` and `Memo.Build.t` to `Memo.t` to make many type signatures in Dune shorter (and also not to bake in the notion of "builds" into the generic Memo library).
This is Step 1 of this renaming.

Rename [Memo.t] to [Memo.Table.t]

---

src/dune_engine/build_config.ml
src/dune_engine/build_config.mli
src/dune_engine/build_system.ml
src/dune_engine/load_rules.ml
src/dune_engine/load_rules.mli
src/dune_rules/dir_contents.ml
src/dune_rules/dir_contents.mli
src/dune_rules/gen_rules.ml
src/dune_rules/odoc.ml
src/dune_rules/simple_rules.ml
test/blackbox-tests/test-cases/directory-targets/copy-files.t
test/blackbox-tests/test-cases/watching/fs-memo.t

So that we can answer whether a path is under a directory target with
loading the rules, thus avoiding computation cycles in some cases.
Rebased version of #5354

fix: report directory targets before rules

---

dune-project
ocamlc-loc.opam

dune-private-libs is needed for our vendored re

fix: add missing depends to ocamlc-loc

---

src/memo/memo.ml
src/memo/memo.mli

Right now, Merlin infers the type `Memo.memo` everywhere. This PR fixes the problem by getting rid of this alias.

Delete [Memo.memo] type alias to improve inferred types

---

src/dune_engine/action_exec.ml
src/dune_engine/utils.ml
src/dune_engine/utils.mli

it's the only place where it's used and it removes one function from the
ugly Utils module

refactor: move bash_exn to caller

---

src/dune_engine/load_rules.ml
test/blackbox-tests/test-cases/directory-targets/main.t

Do not delete all directory when loading rules. Stale artifact deletion
should take directory targets into account

fix: directory targest and artifact cleanup

---

CHANGES.md
otherlibs/site/src/plugins/plugins.ml

- Used in the wild before findlib documented `plugin(native|byte)`
- Still used in many packages

[Plugin] add support for archive(native|byte, plugin)

---

otherlibs/stdune/fpath.ml

This PR fixes the race that occurs when:
1. we want to `$ mkdir -p x/y`
2. `x` does not exist
3. we successfully create `x`
4. we try creating `y`
5. but someone else already created `y` for us
Maybe this fixes #5461?

fix: better handling of mkdir races

---

test/expect-tests/dune

so that the rest of the tests do not depend on the findlib fixtures

test: split findlib tests into separate stanza

---

CHANGES.md
otherlibs/stdune/path.ml
otherlibs/stdune/path.mli
src/dune_engine/build_system.ml
src/dune_engine/load_rules.ml
src/dune_engine/load_rules.mli
test/blackbox-tests/test-cases/glob-deps.t/run.t

As mentioned in the test, globs should only match against files.
Fix #5540

Fix global evaluation in external dirs

---

CHANGES.md
src/dune_engine/action_exec.ml
src/dune_engine/print_diff.ml
src/dune_engine/process.ml
src/dune_engine/process.mli
src/dune_rules/cram_exec.ml

Instead of labelling everything as `sh`, add the names of cram tests to metrics. I also added some unrelated cleanups along the way (in separate commits)

better cram test metrics

---

CHANGES.md
src/dune_engine/load_rules.ml

this is needed to use globs on external dirs in watch mode

fix: track external directory IO

---

test/blackbox-tests/test-cases/directory-targets/create-target-chdir.t

add a test that tries to create a directory target using chdir +
without-stdout-to

test: directory targets and chdir

---

bin/install_uninstall.ml
boot/duneboot.ml
otherlibs/configurator/src/import.ml
otherlibs/configurator/src/v1.ml
otherlibs/stdune/dune_filesystem_stubs/dune_filesystem_stubs.ml
otherlibs/stdune/io.ml
otherlibs/stdune/sys.ml
src/dune_cache/local.ml
src/dune_config/dune_config.ml
src/dune_stats/dune_stats.ml

Stop catching Invalid_argument, Code_error and other exceptions that we rarely intend to swallow

refactor: catch specific exceptions only

---

CHANGES.md
otherlibs/stdune/console.ml

[--terminal-persistence=clear-on-rebuild] will no longer destroy scrollback on some faulty terminals

fix: terminal persistence and scrollback

---

CHANGES.md
src/dune_engine/process.ml
src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli
test/expect-tests/scheduler_tests.ml

* do not print output of cancelled jobs
* `Process.run` will not return with a value signalling success if the job was cancelled after the process terminated.
Should help out with #5482.

fix: better cancelled jobs handling

---

CHANGES.md
src/dune_engine/fs_memo.ml
src/dune_engine/fs_memo.mli
src/dune_rules/dune_load.ml

Convert more untracked file system to the memoized code path.

fix: memo fs access for ocaml syntax dune files

---

otherlibs/stdune/digest.ml
otherlibs/stdune/digest.mli
test/blackbox-tests/test-cases/directory-targets/main.t
test/expect-tests/stdune/digest_tests.ml

@rgrinberg Not sure how I missed this when reviewing your PR for digesting directories, but we clearly don't need to include `mtime` and friends anymore. We did that before only because we didn't have a proper digest. Now that we do, `mtime` stands in the way of early cutoff for directory targets, so this PR fixes that.

Fix early cutoff for directory targets

---

src/dune_engine/build_system.ml
src/dune_engine/build_system.mli
src/dune_rules/install_rules.ml

Ideally, build_system should know as little as possible about the
details of pacakges.

refactor: move package_deps to rules

---

src/dune_engine/utils.ml
src/dune_engine/utils.mli

Utils.library_not_found isn't used anywhere

refactor: remove dead code

---

bin/dune_init.ml
bin/dune_init.mli
bin/workspace_root.ml
configure.ml
src/dune_rpc_impl/server.ml
src/dune_rules/bootstrap_info.mli
src/dune_rules/setup.defaults.ml
src/upgrader/dune_upgrader.ml
src/upgrader/dune_upgrader.mli

Use explicit imports to demonstrate that we depend on things from
[Dune_engine] that shouldn't be there.
EDIT: Needs #5671 merged first.

refactor: limit Build_engine use where possible

---

test/blackbox-tests/test-cases/coq/dune

instead of the guard, we depend on the appropriate binaries.
cc @Alizter

test(coq): stop guarding rules with enabled_if

---

test/blackbox-tests/test-cases/vendor/main.t/run.t

The test has been moved to its own folder.

Remove leftover test in vendor/main.t

---

CHANGES.md
doc/dune-files.rst
src/dune_rules/mdx.ml
test/blackbox-tests/test-cases/mdx-stanza/locks.t

This adds a (locks) field to the mdx stanza. This field is versioned against the extension.

Add (locks) to (mdx) stanza

---

src/dune_rules/cram_rules.ml
src/dune_rules/cram_stanza.ml
src/dune_rules/cram_stanza.mli
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/expander.ml
src/dune_rules/expander.mli
src/dune_rules/locks.ml
src/dune_rules/locks.mli
src/dune_rules/mdx.ml
src/dune_rules/simple_rules.ml

It contains a field parser and a type to be consumed by the new `Expander.expand_locks` function.

Refactor: add a Locks module

---

src/dune_rules/mdx.ml
test/blackbox-tests/test-cases/mdx-stanza/paths.t

This fixes part of #5596 by providing error messages instead of crashes. The locs are not great but this is the best we can do without modifying mdx.

mdx stanza: improve error messages for path errors

---

CHANGES.md
src/dune_rules/mdx.ml
test/blackbox-tests/test-cases/mdx-stanza/paths.t

This supports paths that go up a directory while staying in the workspace (only in stanza 0.3).

mdx stanza: support paths that point outside directory

---

src/dune_rules/coq_rules.ml
src/dune_rules/coq_rules.mli
src/dune_rules/gen_rules.ml

Instead of returning them, we add them directly with Super_context. This
is our standard practice in every other rules module and is also required for generating directory targets.

refactor(coq): add rules directly

---

CHANGES.md
src/dune_engine/fs_memo.ml
src/dune_engine/fs_memo.mli
src/dune_rules/foreign_rules.ml
test/blackbox-tests/test-cases/foreign-library.t

the check for include directories should use tracked io to work in watch
mode

fix: track io in foreign rules

---

test/blackbox-tests/test-cases/include-subdirs/stop-at-project-root.t

Demonstrates that #1477 is not a bug

test: show that include_subdirs stops at projects

---

src/dune_engine/dune_engine.ml

it's no longer part of the public API

refactor(engine): hide Action_intf

---

src/dune_rules/lib.ml

The `resolve_complex_deps` function contains a fold that manipulates a triplet to build a value of type `resolved_deps`. This extracts a module to extract that accumulator so that the logic of adding to it is separated from how to manipulate it.

refactor: Resolve_names : extract a builder module

---

src/dune_engine/action.ml
src/dune_engine/action.mli
src/dune_engine/action_ast.ml
src/dune_engine/action_ast.mli
src/dune_engine/action_intf.ml
src/dune_engine/action_types.ml
src/dune_engine/action_types.mli

These types aren't related to the Ast and this will simplify subsequent PR's that add custom actions and split the frontend the backend better.

refactor(engine): move types to action_types

---

CHANGES.md
boot/duneboot.ml
bootstrap.ml
src/dune_rules/findlib/meta.ml
src/dune_rules/ocaml_version.ml
src/dune_rules/ocaml_version.mli
src/ocaml-config/ocaml_config.ml

Updates Dune for compatibility with the changes proposed in ocaml/ocaml#11198 (2.9 version of #5581)

[2.9.x] Support new locations of unix, str and dynlink

---

CHANGES.md
bin/main.ml
src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli
test/blackbox-tests/test-cases/signal-exit-code.t
test/expect-tests/dune_rpc_e2e/dune_rpc_registry_test.ml
test/expect-tests/scheduler_tests.ml

set the exit code to 130 when dune is terminated with a signal

fix: set exit code on signal

---

dune-action-plugin.opam
dune-configurator.opam
dune-project
dune-rpc-lwt.opam
otherlibs/action-plugin/src/dune
otherlibs/dune-rpc-lwt/src/dune
src/csexp_rpc/dune
src/dune_cache/dune
src/dune_cache_storage/dune
src/dune_rpc_server/dune
src/dune_rules/dune
src/dune_stats/dune
src/dune_util/dune
src/memo/dune
stdune.opam

Hot on the heels of https://github.com/ocaml/ocaml/pull/11198, Dune has quite a few missing dependencies on Unix!
I added `(re_export unix)` in the cases where `Unix` is used in a signature.

Add explicit dependencies on Unix

---

CHANGES.md
src/dune_engine/dep.ml
src/dune_engine/dep.mli
src/dune_engine/sandbox.ml

* calculate the directories that must be created in one go
* do not store unnecessary directories in the field

refactor(sandboxing): optimize dir creation

---

src/dune_engine/action_builder0.ml
src/dune_engine/action_builder0.mli

Add a way to cutoff on [Action_builder.memoize] node. 
This is needed to implement some internal Jane Street build rules.

Add support for cutoff on [Action_builder.memoize] node

---

src/dune_rules/lib.ml
src/dune_rules/lib.mli
src/dune_rules/scope.ml
src/dune_rules/scope.mli
src/dune_rules/super_context.ml

move into the library database as it's the only place where it's being
used. Also remove more stuff from the junk yard that is Super_context

refactor(rules): simplify project/package map

---

otherlibs/chrome-trace/src/chrome_trace.ml
otherlibs/chrome-trace/src/chrome_trace.mli

Object output allows us to add metadata to traces

feature(chrome-trace): add object output

---

README.md

I noticed the status badge in the README.md was of the old travis CI. We remove it and replace it with the GitHub actions status badge.
We also cleanup other mentions of travis.

Replace travis status badge with GitHub one

---

test/blackbox-tests/test-cases/dune
test/blackbox-tests/test-cases/patch-back-source-tree.t

test: disable exit-code on ci + mac

---

src/dune_rules/cram_rules.ml
src/dune_rules/mdx.ml
src/dune_rules/only_packages.ml
src/dune_rules/only_packages.mli
src/dune_rules/super_context.ml

In continuation of the quest of making Super_context less of a junk yard, we move stanza filtering into [Only_packages].

refactor(engine): move stanza filtering

---

doc/papers/ocaml-2021/memo.md
src/memo/dune

Just freshening up the abstract, plus a drive-by change to the Memo's description in `dune` file. It's far more than just a "function memoizer" these days.

Tweaks to Memo docs

---

src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli

[Dune_file.Stanza.syntax] isn't used anywhere

refactor(rules): remove unused type

---

src/dune_engine/build_system.ml
test/blackbox-tests/test-cases/directory-targets/main.t

Fix #5830
ocamlformat sometimes makes some weird decisions...

Add hint to unsandboxed directory target error message.

---

bin/describe.ml
bin/installed_libraries.ml
src/dune_rules/context.ml
src/dune_rules/context.mli
src/dune_rules/findlib/findlib.ml
src/dune_rules/jsoo_rules.ml
src/dune_rules/lib.ml
src/dune_rules/lib.mli
src/dune_rules/lib_config.ml
src/dune_rules/lib_config.mli
src/dune_rules/link_time_code_gen.ml
src/dune_rules/scope.ml
src/dune_rules/scope.mli
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli

Callers can now create it without referring to the super context. One less thing stuffed into the super context is always a good thing. Additionally, we don't need to flush the findlib DB on every build iteration now.

refactor(rules): move findlib from super_context

---

test/blackbox-tests/test-cases/directory-targets/dir-contents.t

It's an issue we need to fix before allowing coq to use directory targets for extraction. For now, this is just a test demonstrating the issue.

test: directory targets cannot generate sources

---

boot/duneboot.ml

They were disabled for the compilation command, but apparently the
linker can spit them out too.
```
cd _boot && /home/opam/.opam/4.14/bin/ocamlopt.opt -o ../dune.exe -g -I +threads unix.cmxa threads.cmxa -no-alias-deps -w -49-6 readdir.c wait3_stubs.c spawn_stubs.c fsevents_stubs.c inotify_stubs.c pthread_chdir_stubs.c -args mods_list
File "src/dune_engine/compound_user_error.ml", line 41, characters 20-35:
Alert unstable: module Ocamlc_loc
```

fix(bootstrap): disable unstable alerts

---

bin/top.ml
src/dune_rules/compilation_context.ml
src/dune_rules/dir_contents.ml
src/dune_rules/dir_contents.mli
src/dune_rules/exe.ml
src/dune_rules/lib.ml
src/dune_rules/lib.mli
src/dune_rules/lib_flags.ml
src/dune_rules/lib_flags.mli
src/dune_rules/merlin.ml
src/dune_rules/scope.ml
src/dune_rules/scope.mli
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli

Gets rid of a bunch of ugly forward declarations. Although it requires us to pass more Sctx in some places, it's better than sneakily passing it through forward declarations. I have upcoming pr's to get rid of much of this anyway.

refactor: remove Lib.modules and its friends

---

CHANGES.md
src/dune_rules/ocaml_flags.ml

Enable flags that are of the "unused X" form. This is consistent with
our other flags
This was discussed and approved at the dune meeting at some point, but I forgot to submit the PR.

fix: tweak flags for 3.3

---

src/dune_rules/dune_load.ml

Dune files written in OCaml syntax must be evaluated once per run. While
this was maintained by keeping all the stanzas in one data structure in
the super context, now any memoizing function can get the list of
stanzas. This change makes sure that we don't memoize the evaluated
stanzas incorrectly.

refactor: dune file evaluation

---

CHANGES.md
src/dune_rules/lib.ml

For Dune 2.9.4, a back-port of https://github.com/ocaml/dune/pull/5526.

Fix bigarray support for OCaml 5.x [2.9]

---

src/dune_engine/action_exec.ml

Using [Temp.destroy] is preferable to direct deletion as it will prevent
dune trying to delete the file again on shutdown

refactor(dap): cleanup response file better

---

src/dune_rpc_impl/client.ml
src/dune_rpc_impl/client.mli
src/dune_rpc_impl/private.ml
test/expect-tests/dune_rpc/dune_rpc_tests.ml

Get rid of the useless `Run` module as very little is shared between client and server.

Refactor RPC

---

src/dune_rules/coq_lib.ml
src/dune_rules/coq_rules.ml

Instead of doing an special case in Coq_lib, we handle the boot
library directly in the flags.
This allows us to handle coqdoc-specific flags related to `-boot`, and
is more in line with what we expect the future theory model will be.
Downside is that `-boot` is now not included in the closure dep, but
that seems fine, actually we should forbid `(boot)` libraries from
declaring `(theories ...)` deps, but as we are getting rid of it
eventually maybe it is not worth the effort.

[coq_rules] Refactor boot flag handling.

---

src/dune_rules/coq_rules.ml

It just hinders readability IMO

cleanup(coq): remove SC module alias for Super_context

---

.gitignore

This should let us have our own hooks. Ignoring them for now.
I don't know we should be sharing them. I made a small hook for checking `@fmt`, `@check` and `@runtest` which will get run when `gps` isolates a commit.

Added .git-ps to .gitignore

---

src/dune_rules/buildable_rules.ml
src/dune_rules/buildable_rules.mli
src/dune_rules/exe_rules.ml
src/dune_rules/lib_rules.ml

Instrumentation, preprocessing, and empty interfaces are all shared
concerns of executables and libraries.
ps-id: ee416e7c-1cf1-496b-9642-c9e59af50921

refactor(rules): module building code

---

Makefile

`.PHONY` can be put anywhere, but putting it next to the rule makes it easier to
remove or rename it when needed (for example `default` has been renamed to `help` but the `.PHONY` instruction had not been renamed).

Makefile: move PHONY instructions next to their use

---

bin/rpc.ml
otherlibs/dune-rpc/dune_rpc.mli
otherlibs/dune-rpc/private/dune_rpc_private.ml
otherlibs/dune-rpc/private/dune_rpc_private.mli
otherlibs/dune-rpc/private/types.ml
otherlibs/dune-rpc/private/types.mli

* Long polling should quietly terminate the stream when a connection dies
* Dedicated error kind for connection errors. These are very common so clients should ignore them.

RPC(client): better connection handling

---

doc/dune-files.rst

Not just `with-test`, `build` and `dev`.
Closes #3770

Doc: all opam variables can be used as filter

---

CHANGES.md
src/dune_rules/context.ml
src/dune_rules/findlib/meta.ml
src/ocaml/version.ml
src/ocaml/version.mli

This is an update of #5824, compatible with the latest version pushed to ocaml/ocaml#11007. The current proposal is that from OCaml 5.0.0~alpha1, the compiler installs its own `META` files in directories under the Standard Library directory.
The previous version was not able to guarantee the operation of Dune or opam's `ocaml-system` because there wasn't a mechanism for reliably determining the location of the compiler's `META` files. The latest revision proposes that the compiler's `META` are therefore _always_ installed in the same place, with Dune and ocamlfind using that fact to change their default search paths for packages accordingly.
This PR, therefore:
- Disables the automatic generation of the compiler's `META` files used for OCaml 4.x.
- Adds the Standard Library directory to …

Turn off shimmed META files for OCaml 5.0+

---

doc/dune-files.rst

- this is an optional field (with a pointer to inferred rules)
- move directory targets to their own section
Closes #4526

Doc: restructure section about (target) in (rule)

---

bin/init.ml

Doc: dune init: fix typo in examples

---

test/blackbox-tests/test-cases/watching/fs-memo.t

-d is only avilable on GNU
ps-id: 8f485986-bcb7-4df5-8eea-c29b0e9622e6

test: fix non portable use of xargs

---

src/dune_stats/dune
src/dune_stats/dune_stats.ml
src/dune_stats/dune_stats.mli
src/dune_stats/dune_stats_stubs.c
test/expect-tests/dune_stats/dune
test/expect-tests/dune_stats/dune_stats_tests.ml

using lsof is bad for two reasons:
* it's buggy b/c we swallow sigchld's in the signal watching thread
* it's quite slow
We replace lsof with a native api for getting the number of open fd's for a process.

do not use lsof on macos

---

src/dune_rules/coq_rules.ml

It's not needed and can easily be added in when hand debugging as
necessary.

cleanup(coq): remove debug code

---

CHANGES.md
bench/bench.ml
bench/micro/dune_bench/scheduler_bench.ml
bin/common.ml
bin/common.mli
bin/import.ml
bin/subst.ml
src/dune_config/dune_config.ml
src/dune_config/dune_config.mli
src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli
test/expect-tests/csexp_rpc/csexp_rpc_tests.ml
test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
test/expect-tests/dune_rpc_e2e/dune_rpc_registry_test.ml
test/expect-tests/process_tests.ml
test/expect-tests/scheduler_tests.ml
test/expect-tests/timer_tests.ml
test/expect-tests/vcs_tests.ml

But leave an option to restore the old behavior for benchmarking.

Ignore insignificant file system changes by default

---

CHANGES.md
otherlibs/ocamlc_loc/src/lexer.mll
otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml

excerpts may start with blank characters

ocamlc-loc: correctly skip excerpts

---

CHANGES.md
bin/describe.ml
src/dune_rules/lib.ml
src/dune_rules/lib.mli
test/blackbox-tests/test-cases/describe.t

Fixes issue #5747
Here is what happened before this fix: if your project was using a
virtual library and at least two implementations for that virtual
library, then dune describe would not produce any information for the
libraries of your project (it would only show information about the
executables, if there were any). The issue was in the computation of
the transitive closure of libraires, that raised an error by default
in the presence of overlapping implementations of virtual libraries.
In such a case, the error was treated by discarding all information
about the libraries.
The fix consists in computing the transitive closure of libraries
without performing any overlap checks between implementations of a
virtual library. We have defined the `descriptive_closure` function
for this very …

Make `dune describe` correctly handle overlapping implementations for virtual libraries

---

CHANGES.md
src/dune_rules/dune_env.ml
test/blackbox-tests/test-cases/env/env-unused.t

Since matching is sequential, anything after `_` cannot be reached.
Closes #5886

Env stanza: warn if some rules are ignored

---

bench/bench.ml
bench/micro/dune_bench/scheduler_bench.ml
bin/import.ml
bin/subst.ml
src/dune_config/dune_config.ml
src/dune_config/dune_config.mli
src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli
test/expect-tests/csexp_rpc/csexp_rpc_tests.ml
test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
test/expect-tests/dune_rpc_e2e/dune_rpc_registry_test.ml
test/expect-tests/process_tests.ml
test/expect-tests/scheduler_tests.ml
test/expect-tests/timer_tests.ml
test/expect-tests/vcs_tests.ml

These subcommands do not build anything and hence should be
interruptible with C-c
ps-id: d4aae9a9-9625-42c4-82df-3f30213ab0b0

fix: disable signal handling for subst/merlin

---

.gitattributes
CHANGES.md
boot/libs.ml
otherlibs/xdg/dune
otherlibs/xdg/gen_flags/dune
otherlibs/xdg/gen_flags/gen_flags.ml
otherlibs/xdg/xdg.ml
otherlibs/xdg/xdg_stubs.c
src/dune_rules/bootstrap_info.ml

This sets the following XDG defaults on Windows:
```
XDG_CONFIG_HOME --> %LOCALAPPDATA%
XDG_DATA_HOME --> %LOCALAPPDATA%
XDG_CACHE_HOME --> FOLDERID_InternetCache
```
A C call is needed to get the right path for `FOLDERID_InternetCache`. This is included in the PR, but perhaps it is considered to be too much trouble? Opinions welcome.
cc @dra27 @jonahbeckford
Fixes #5808

Better XDG defaults for Windows

---

doc/dune-files.rst

They are supported in addition to `(uri)` and `(github)`.

doc: mention (bitbucket), (gitlab), (sourcehut)

---

doc/dune-files.rst

Recently had to disable the cram test project-wide and got the following error after I followed the doc:
```
$ dune runtest
File "dune-project", line 43, characters 6-14:
43 | (cram disabled)
^^^^^^^^
Error: must be 'disable' or 'enable'
```

Fix dune-project cram stanza documentation

---

src/fiber/core.ml
src/fiber/fiber.mli

This function is quite specialized to our metrics module and is just
easily implemented externally.
The motivation for this is to move `Stdune.Metrics` into its own private library as its quite specialized.

refactor: remove [Fiber.record_metrics]

---

src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli

[Scheduler.flush_file_watcher] isn't used anywhere
ps-id: 7305f061-b5cc-4ab9-b79a-8010940e715c

refactor(scheduler): remove dead code

---

src/fiber/scheduler.ml

Remove pattern match and function call when filling empty ivars
ps-id: a9642d29-4f12-401b-88f4-5ef7f7e2078d

refactor(fiber): optimize ivar

---

test/blackbox-tests/test-cases/github1645.t

Add repro case for #1645

---

test/blackbox-tests/test-cases/target-outside-dir.t

Looks like we can get around the limitation of producing only in our own directory in a sneaky way in user rules.
@snowleopard i assume this is unintentional

test: generating in subdirs

---

src/dune_engine/build_system.ml
src/dune_engine/source_tree.ml
src/dune_engine/source_tree.mli

Move it into [Build_system] as this is only place where this is used.
ps-id: a12ab53c-2569-45ba-973b-cb18ae92715d

refactor(engine): move execution_parameters_of_dir

---

src/dune_rules/exe.ml
src/dune_rules/inline_tests.ml
src/dune_rules/jsoo_rules.ml
src/dune_rules/link_time_code_gen.ml
src/dune_rules/menhir_rules.ml
src/dune_rules/module_compilation.ml
src/dune_rules/ocamldep.ml
src/dune_rules/odoc.ml
src/dune_rules/preprocessing.ml
src/dune_rules/simple_rules.ml

it's used too infrequently to be useful
ps-id: e83f3210-69e4-42cf-95e3-fc64d556ba80

refactor: remove Super_context alias

---

editor-integration/emacs/dune-watch.el

The header printed by dune watch contains variable information (file that changed).
As the dune-watch mode search for the header to erase from the buffer the previous compilation output, we should just search for the prefix of the header. If not, the header is never found and thus the successive compilation results are not erased but stacked in the buffer.

[emacs] adapt dune-watch-minor-mode to change of header

---

bench/bench.ml
bench/micro/dune_bench/scheduler_bench.ml
bin/common.ml
bin/subst.ml
otherlibs/stdune/path.ml
otherlibs/stdune/path.mli
test/expect-tests/common/dune_tests_common.ml
test/expect-tests/dune_file_watcher/dune_file_watcher_tests_lib.ml
test/unit-tests/artifact_substitution/artifact_substitution.ml

This is clearer than [Path.Build.Kind] and is useful in other contexts
as well
ps-id: 18030879-bae6-43eb-8283-1cac3f5340ea

refactor: introduce [Path.Outside_build_dir.t]

---

src/dune_rules/ctypes_rules.ml
src/dune_rules/pkg_config.ml
src/dune_rules/pkg_config.mli

Run pkg-config as a normal rule. This is both more correct and more efficient.

refactor(ctypes): remove configurator

---

bin/print_rules.ml
test/blackbox-tests/test-cases/directory-targets/main.t

We can at least print directory targets in sexp mode.
ps-id: 85d4838a-8f74-459b-a245-dd32ab82ad11

fix: dune print-rules should print dir targets

---

bin/common.ml
src/dune_engine/clflags.ml
src/dune_engine/clflags.mli
src/dune_engine/load_rules.ml
test/blackbox-tests/test-cases/directory-targets/loading-inside-directory-target.t

Load a subdir inside a directory target and make sure that stale
artifact clean up works correctly.
https://github.com/ocaml/dune/pull/5599#issuecomment-1105819683
Needs #6055 for loading rules by printing the rules in a directory.

test: loading inside directory target

---

test/blackbox-tests/test-cases/directory-targets/create-dir-with-symlink.t

add a test that demonstrates creating a directory target by symlinking
another directory.
ps-id: 242b2743-2c72-44dc-97e4-532f04e162df

test: directory target and symlink

---

CHANGES.md
src/dune_engine/rule.ml
src/dune_rules/action_unexpanded.ml
src/dune_rules/simple_rules.ml
test/blackbox-tests/test-cases/directory-targets/create-target-chdir.t
test/blackbox-tests/test-cases/generate-sources.t
test/blackbox-tests/test-cases/target-outside-dir.t

we intended to forbid this all along, but failed to do so for inferred
targets.
ps-id: 140db227-78c6-4782-90b3-535c3ac8eb90

fix: disallow targets in subdirs

---

src/dune_engine/cached_digest.ml

When we [stat] the target and determine to be a file, the digest function should
no longer permit it to be a directory.

refactor(digest): restrict [allow_dirs]

---

bin/common.ml
bin/dune
bin/import.ml
bin/internal_dump.ml
boot/libs.ml
otherlibs/stdune/stdune.ml
src/dune_config/dune
src/dune_config/dune_config.ml
src/dune_console/dune
src/dune_console/dune_console.ml
src/dune_console/dune_console.mli
src/dune_engine/dune
src/dune_engine/import.ml
src/dune_file_watcher/dune
src/dune_file_watcher/dune_file_watcher.ml
src/dune_rules/dune
src/dune_rules/import.ml
src/dune_util/dune
src/dune_util/import.ml
src/dune_util/log.ml
src/dune_util/report_error.ml
src/memo/dune
src/memo/memo.ml
src/upgrader/dune
src/upgrader/dune_upgrader.ml
test/expect-tests/common/dune
test/expect-tests/common/dune_tests_common.ml

[Console] isn't general purpose enough to live in [Stdune]
ps-id: ebd1cb41-98fd-4acc-b2a8-0a33ce911772

refactor(stdune): move [Console] to own library

---

CHANGES.md
bin/import.ml
src/dune_config/dune_config.ml
src/dune_config/dune_config.mli
src/dune_console/dune_console.ml
src/dune_console/dune_console.mli

[clear-on-rebuild-and-flush-history] is added for situations where in
fact we do prefer to flush the terminal history. Note that some
emulators will maintain the history regardless.
ps-id: 2ecb488c-d1ae-4ef8-947a-649091419b2f

feature: new terminal persistence mode

---

src/fiber/scheduler.ml

we know that case [Empty_with_readers] has at least one job to enqueue,
so we enqueue it manually ourselves before enqueuing the rest.
ps-id: de9dbcec-fc09-426c-a9e2-811f5f38f430

refactor(fiber): optimize reader enqueue

---

otherlibs/chrome-trace/src/chrome_trace.ml
otherlibs/chrome-trace/src/chrome_trace.mli
otherlibs/chrome-trace/test/chrome_trace_tests.ml
src/dune_engine/process.ml
src/dune_rpc_server/dune_rpc_server.ml

There's already a functional Id type in this library. The stack frame id
was introduced by accident.
ps-id: 03190f5c-cc17-42e2-b990-510eb356f76e

refactor(chrome-trace): use a single [Id] type

---

CHANGES.md
src/dune_rules/cinaps.ml

ps-id: b87ebe4c-10dc-4357-a41a-942fc04ccce7

feature: sandbox cinaps actions

---

doc/faq.rst

This fixes a tiny typo in `faq.rst`
Signed-off-by: Jay Lee <jaeho.lee@snu.ac.kr>

Fix a typo in faq.rst

---

src/dune_console/dune
src/dune_console/dune_console.ml
src/dune_console/dune_console.mli
src/dune_engine/scheduler.ml

We no longer block on updating the terminal
ps-id: 230cf5db-0841-4d20-af31-5f2cf27a8432

fix: run console in separate thread

---

src/dune_engine/sandbox.ml
test/blackbox-tests/test-cases/directory-targets/create-dir-with-symlink.t

Instead of manually traversing the directory and moving things file by
file, we rely on one call of [Unix.rename].
The advantage is that we move the direcory atomically. Previously, an
error could interrupt the recursive rename and leave _build/ with some
partially copied directory.
ps-id: 39a65638-5953-4ed5-bcae-bbb13c63e46f

fix: atomically copy dir targets from sandbox

---

CHANGES.md
src/dune_engine/build_system.ml
src/dune_engine/rule_cache.ml
src/dune_engine/targets.ml
src/dune_engine/targets.mli
test/blackbox-tests/test-cases/directory-targets/main.t
test/blackbox-tests/test-cases/directory-targets/no-sandboxing.t

allow non sandboxed rules to produce directory targets
ps-id: 49c39ffb-67c2-4ea1-9b33-ea5be360f5bb

feature: relax directory target rules

---

CHANGES.md
otherlibs/stdune/dune_filesystem_stubs/dune_filesystem_stubs.ml
otherlibs/stdune/dune_filesystem_stubs/dune_filesystem_stubs.mli
src/dune_engine/action_builder.ml
src/dune_engine/action_builder.mli
src/dune_rules/coq_rules.ml
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/gen_rules.ml
src/dune_rules/install.ml
src/dune_rules/install.mli
src/dune_rules/install_rules.ml
src/dune_rules/plugin_rules.ml
test/blackbox-tests/test-cases/directory-targets/install-dir-target.t

This PR allows installing all the artifacts in a directory using the following syntax:
```
(install
(dir foo/bar)
(package pkg)
(section baz))
```
This will build `foo/bar` and add its recursive listing to `pkg.install`.
This feature is particularly useful for installing things such as documentation, where there's a lot of overhead in listing the contents individually.

feature: install dir

---

src/dune_console/dune_console.ml

improve escape sequence that flushes terminal history
Seems to work fine in tmux.

fix: flush terminal history

---

test/blackbox-tests/test-cases/dune
test/blackbox-tests/test-cases/env/dune
test/blackbox-tests/test-cases/merlin/dune

all of these tests rely on switches so they should depend on opam
ps-id: e5d76705-36ee-4452-a630-8452bbcc879b

test: add opam dependencies

---

CHANGES.md
otherlibs/build-info/test/run.t
src/dune_rules/link_time_code_gen.ml

With flambda, Sys.opaque_identity is needed around the placeholder
string or else flambda is able to compile it away. This prevents the
rewriting done by e.g. `dune install` from working.
fix: https://github.com/ocaml/dune/issues/6075

fix(duild-info): reapply flambda fix from #3599 removed in #5049

---

CHANGES.md
doc/concepts.rst
src/dune_rules/foreign.ml
src/dune_rules/foreign.mli
src/dune_rules/foreign_rules.ml
test/blackbox-tests/test-cases/include-dirs-include/include-dir-chain.t
test/blackbox-tests/test-cases/include-dirs-include/include-dir-include-lib.t
test/blackbox-tests/test-cases/include-dirs-include/include-dir-include-loop.t
test/blackbox-tests/test-cases/include-dirs-include/multiple-include-dirs.t
test/blackbox-tests/test-cases/include-dirs-include/single-include-dir.t

Addresses https://github.com/ocaml/dune/issues/3993
Still need to add a version number check but opening this now to get preliminary feedback while I work out the best way to do that.

Add `(:include <file>)` terms to include_dir field

---

test/blackbox-tests/test-cases/directory-targets/remove-write-permissions.t

dune does not make directory targets read only at the moment
ps-id: 6cf69909-983b-4440-9286-e33146f183d8

test: permissions on directory targets

---

CHANGES.md
otherlibs/xdg/xdg_stubs.c

XDG stubs: require Vista functions

---

src/dune_rules/dir_status.ml

this function may raise, and it's not useful here
ps-id: c76ce6b5-cbbf-4f0c-bd65-bd9318662fc9

refactor: remove [Path.Build.drop_build_context_exn]

---

CHANGES.md
bin/describe.ml
test/blackbox-tests/test-cases/describe.t

The provided directories restrict the worskpace description to those
directories. Note that the transitive dependencies of the discovered
executables and libraries are always printed.
If no argument is provided, then the behavior is unchanged.
If `.` is provided as argument, then only the part of the workspace
that is reachable from the current directory is printed (which makes
a difference if the command is run from a subdirectory).
This fixes issue #3893.

allow `dune describe workspace` to accept directories as arguments

---

CHANGES.md
src/dune_rules/odoc.ml
test/blackbox-tests/test-cases/odoc/github1117.t

This controls the syntax of the output.
Closes #1117

Record the fact that odoc reads ODOC_SYNTAX

---

bin/main.ml
src/dune_console/dune_console.ml
src/dune_console/dune_console.mli

wait until all output is flushed before terminating dune
ps-id: 4a999aa6-1018-4ec0-a3b2-8f54426e4885

fix: wait until output if flushed

---

CHANGES.md
src/dune_rules/coq_module.ml
test/blackbox-tests/test-cases/coq/base-unsound.t/run.t
test/blackbox-tests/test-cases/coq/base.t/run.t
test/blackbox-tests/test-cases/coq/compose-cycle.t/run.t
test/blackbox-tests/test-cases/coq/compose-installed.t/run.t
test/blackbox-tests/test-cases/coq/compose-plugin.t/run.t
test/blackbox-tests/test-cases/coq/compose-projects-cycle.t/run.t
test/blackbox-tests/test-cases/coq/compose-projects-missing.t/run.t
test/blackbox-tests/test-cases/coq/compose-self.t/run.t
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/run.t
test/blackbox-tests/test-cases/coq/coqtop-recomp.t
test/blackbox-tests/test-cases/coq/ml-lib.t/run.t
test/blackbox-tests/test-cases/coq/native-compose.t/run.t
test/blackbox-tests/test-cases/coq/native-single.t/run.t
test/blackbox-tests/test-cases/coq/rec-module.t/run.t

We stop declaring .aux files as targets in the coqc rules. .aux files are simply a "cache" recording a runtime estimation for the STM (the thing that let's Coq process proofs asynchronously) to schedule proofs. It definitely should not be cached (or really known) by Dune.
Fixes #6004

remove .aux targets from coqc rule

---

src/dune_rules/dune_package.ml
src/dune_rules/modules.ml
src/dune_rules/modules.mli

It was never really needed because dune-package is not stable, but was added as a convenience to use dune 2.0 without rebuilding everything. This hack is not needed anymore.

refactor: remove old format for modules

---

otherlibs/ocamlc_loc/src/lexer.mli
otherlibs/ocamlc_loc/src/lexer.mll
otherlibs/ocamlc_loc/src/ocamlc_loc.ml
otherlibs/ocamlc_loc/src/ocamlc_loc.mli
otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml

This is needed for ocamllsp to reuse the library to parse the error messages produced by merlin.

feature(ocamlc_loc): messages without location

---

otherlibs/stdune/applicative.ml
otherlibs/stdune/monad.ml
otherlibs/stdune/monoid.ml
otherlibs/stdune/top_closure.ml
src/fiber/core.ml

This fixes several places where `[@@inlined]` was written but `[@@inline]` was intended.  Per [the manual](https://v2.ocaml.org/manual/attributes.html#ss:builtin-attributes), the former goes on specific application sites, while the latter goes on function definitions.  The attributes are currently having no effect - the compiler just ignores them.
Of course, inlining something doesn't always affect performance in the direction one expects.  I don't know if there are dune benchmarks somewhere that could be used to test this change.  An alternative is to just delete these attributes, preserving the current performance behavior.

Fix misplaced "inlined" attributes

---

CHANGES.md
bin/install_uninstall.ml

This refactors `copy_file` in `Install_uninstall` so that it uses `Artifact_substitution.copy_file`. This ensures that these copies are atomic at least for non-special files. It also allows hooks to trigger on install (#6137).

Refactor: use copy_file in install/uninstall

---

CHANGES.md
test/blackbox-tests/test-cases/coq/compose-plugin.t/src_a/gram.mlg
test/blackbox-tests/test-cases/coq/ml-lib.t/src_a/gram.mlg

Coq 8.16 has changed the syntax for plugins as they are now loaded
using `findlib`, Dune's test-suite needs to be updated slightly.

[coq] Preliminary test-suite update for 8.16

---

src/dune_rules/ordered_set_lang_intf.ml

[Ordered_set_lang_intf.Key] doesn't need the vast majority of map
functions so we shouldn't require them
ps-id: 24b6276a-10e3-465e-a40f-c1dc70928031

refactor: remove functions from signature

---

doc/rpc.rst

RPC docs: do not mention `dune rpc init`

---

CHANGES.md
src/dune_rules/cinaps.ml
test/blackbox-tests/test-cases/cinaps/runtime-deps.t

Add a `runtime_deps` field to cinaps stanzas to specify dependencies required for the action executing the cinaps binary.

feature(cinaps): runtime dependencies

---

flake.nix

because opam-nix is overriding opam to be a dummy package
ps-id: 7a3c55dc-7552-4b10-88e2-398bead48c2d

fix(nix): move opam to nativeBuildInputs

---

CHANGES.md
bin/install_uninstall.ml
src/dune_rules/artifact_substitution.ml
src/dune_rules/artifact_substitution.mli

Closes #5650
For future reference:
- [Technical Note TN2206 - macOS Code Signing In Depth](https://developer.apple.com/library/archive/technotes/tn2206/_index.html)
- [documentation of `adhoc`](https://developer.apple.com/documentation/security/seccodesignatureflags/1397793-adhoc)
- [open source implementation of codesign](https://github.com/indygreg/PyOxidizer/tree/main/apple-codesign) - in particular see [this part about ad-hoc mode](https://github.com/indygreg/PyOxidizer/blob/5fb59d1c269ad1097713bc358a5b62abf5814663/apple-codesign/src/signing_settings.rs#L300-L305)

Call codesign after artifact substitution on macos

---

test/blackbox-tests/test-cases/root-module-duplicate.t

Add failing root_module test that produces duplicate modules.
Signed-off-by: mefyl <mefyl@gruntech.org>
ps-id: 3853660f-435d-4853-8c81-6471892cac96

test: failling root_module test

---

src/dune_rules/lib.ml

It's incorrect to compare libraries by [Lib.Id.t] for memoization. We
switch to physical equality which is safe given our current
implementation which forbids modifying or creating [Lib.t] obtained from
the database.
We also fix the hash along the way. It doesn't affect correctness, but
it makes sure that our memoization functions don't suffer from bad
hashing when libraries are used from different build iteration
ps-id: f10f7ced-9861-4c61-9c17-fa481d09bc34

fix(rules): correct equality/hash for [Lib.t]

---

bin/coqtop.ml
src/dune_rules/coq_rules.ml

The implementation of coqtop had a lot of copy and pasted parts. We share these so that it makes future refactoring easier and shares work for dune.

cleanup(coq): factor coqtop through existing functions

---

CHANGES.md
bin/describe.ml
test/blackbox-tests/test-cases/describe.t

For ROTOR we would like to have access to the original source files, not their locations within the build directory. To get this, we need the build context and the workspace root. 
This is an updated PR of https://github.com/ocaml/dune/pull/3834 and https://github.com/ocaml/dune/pull/6092, the latter of which I closed by mistake (sorry).
In this PR the build prefix and the path to the workspace root are added the the beginning of the output of dune describe.
@esope, would you be able to review this updated version? Thanks in advance.

Add root and build context to dune describe output

---

doc/conf.py
doc/index.rst

@christinerose I noticed that these mentions of Dune were not capitalized correct in the manual.
Looks like this now:
https://dune--6200.org.readthedocs.build/en/6200/

doc: fixed capitalization of Dune in manual

---

bin/describe.ml

Failed rebase of the recent dune describe PR. We should serialize these paths as strings and not use their internal representation

fix: serialization of root/build_context

---

otherlibs/dune-rpc/dune_rpc.mli

the directory is absolute and not relative to the workspace
ps-id: 5206c9a2-3118-4df3-962e-5e615ad32c13

doc(dune-rpc): fix directory path

---

doc/coq.rst

In particular the advice about directory split was bogus.

[coq] [doc] Some fixes to documentation.

---

.github/workflows/workflow.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

CHANGES.md
otherlibs/stdune/ansi_color.ml
test/blackbox-tests/test-cases/github5528.t

CSI n K is used to clear the current line. It was not properly parsed by `Ansi_color.parse`. It is now ignored.
Closes #5528

Ansi_color.parse: handle CSI n K

---

CHANGES.md
src/fsevents/fsevents_stubs.c

mainly useful for nixos on macos which is stuck on the old sdk
ps-id: 32403256-aef1-41bb-b674-272998e51c3c

fix(fsevents): allow on older mac sdk's

---

src/fsevents/fsevents_stubs.c

`__builtin_popcount` is supported on GCC and clang. It's not on MSVC but that part of the stubs is only built on macos.

fsevents: use __builtin_popcount

---

CHANGES.md
bin/install_uninstall.ml
src/dune_rules/artifact_substitution.ml
src/dune_rules/artifact_substitution.mli
test/unit-tests/artifact_substitution/artifact_substitution.ml

This ensures that we're not running `codesign` in cases we don't strictly need it. This in turn prevents a regression in macos+nix, where the codesign binary is not in PATH.
Closes #6226

Only run codesign if there have been substitutions

---

test/blackbox-tests/test-cases/watching/dune

strace is needed for what-dune-watches.t
ps-id: e08fc460-bb95-4c20-a324-64459828dc4a

test: add missing deps

---

src/dune_digest/dune_digest.ml
test/blackbox-tests/test-cases/directory-targets/github6168/github6168.t
test/expect-tests/digest/digest_tests.ml

compute digests for symlinks present inside directory targets
ps-id: a0b24bf1-b7da-413f-a2d6-08f977cc8973

fix: symlinks in directory targets

---

Makefile
flake.nix

It's not being used in any of the tests
ps-id: 7f572c8f-607d-4d89-a4f4-9fca29675b31

chore(ci): remove merlin from test deps

---

doc/dune-files.rst
doc/index.rst
doc/jsoo.rst
doc/melange.rst

Companion PR for #6238, including:
- new section "JavaScript Compilation With Melange"
- updates to `modes` field in `library` stanza

[docs] Melange mode in library

---

doc/melange.rst

should be 3.6 instead of 3.5
ps-id: 40e630f4-d251-4b33-87d6-4b902af5c1f9

doc: melange dune version

---

.github/workflows/workflow.yml
test/blackbox-tests/test-cases/coq/dune
test/blackbox-tests/test-cases/dune

Coq gets its own job that takes around 12min to run all the tests. We could definitely cut this time down further by making use of the cache or dropping the dep on the Coq stdlib.
This at least let's us ignore Coq tests during main CI runs.
@rgrinberg I've subsumed #6270 since it needed an extra modification.

refactor(ci): put Coq in its own job

---

CHANGES.md

* Mention that melange support has been introduced
* Add missing contributor to ctypes changes
ps-id: c52da800-103c-481d-b834-7cc58146bffa

chore: fix CHANGES

---

CHANGES.md
bin/describe.ml
test/blackbox-tests/test-cases/external-lib-deps.t
test/blackbox-tests/test-cases/external-lib-deps/simple-pps.t/dune
test/blackbox-tests/test-cases/external-lib-deps/simple-pps.t/dune-project
test/blackbox-tests/test-cases/external-lib-deps/simple-pps.t/run.t
test/blackbox-tests/test-cases/external-lib-deps/simple.t/run.t

This PR is motivate by [dune-opam-lint](https://github.com/ocurrent/opam-dune-lint). The command `dune external-lib-deps` is used by it and this command is removed in dune #4298. Getting the command back is not realistic, I think. Instead of getting all information by doing a static analysis of the build graph. We extract all the information we need during the build, so `dynamically`.
* The first approach is to categorize the Data Base dependencies like `Project_libs` db, `Public_libs` db, `Installed_libs` db. Then, during the resolution catch all libs that searched in `Installed_libs`, potentially there are external libs. Easy to add but you have to propagate the `build_dir` in order to get the dependencies by `build_dir`.
* The second approach, after resolving the lib we could get the …

Add an option to replace external-lib-deps command

---

.github/workflows/workflow.yml

These CI jobs only make sure that OCaml is built which is pretty much
guaranteed by building 4.08.
ps-id: 0aee90aa-b568-4314-9347-721330c40093

chore(ci): remove building 4.09-4.12

---

test/blackbox-tests/test-cases/rule-digest.t

We should fix this to improve build incrementality.

Expose a bug where rule digest depends on irrelevant details of dune file

---

Makefile

Gets rid of the opam warnings for missing fields:
```
error 23: Missing field 'maintainer'
warning 25: Missing field 'authors'
warning 35: Missing field 'homepage'
warning 36: Missing field 'bug-reports'
warning 56: It is discouraged for non-compiler packages to use 'setenv:'
error 57: Synopsis and description must not be both empty
```
Signed-off-by: Javier Chavarri <javier.chavarri@gmail.com>

update melange pin

---

Makefile

we now use opam-nix instead of opam2nix
ps-id: f735414d-6f43-43bd-a458-c18b19afa557

chore: remove unused nix stuff from makefile

---

flake.lock
flake.nix

* do not reuse inputs from ocamllsp
* do not use opam-repository from opam-nix
* add devShells to allow more than one shell to be defined
ps-id: 727091c3-bd27-4253-b868-ad6753f515c2

chore(nix): more flake fixes

---

test/blackbox-tests/test-cases/directory-targets/install-dir-target.t

I thought I saw a bug in dune related to nesting directories, but the output looks right.

test: add a test exercising nesting in directory targets

---

boot/bootstrap.ml
boot/dune

* This lets us catch compilation errors and warnings
* Gives us correct merlin/lsp support
ps-id: a6c43325-fce3-4030-921c-c3340111203c

refactor: compile bootstrap script

---

Makefile

* use $(BIN) var when possible
* do not make clean rebuild the binary
ps-id: f00da1e3-aba7-4792-bbf2-4e4bd713c56e

chore: makefile cleanups

---

src/dune_engine/action.ml
src/dune_engine/action_exec.ml
src/dune_engine/action_intf.ml
src/dune_engine/action_mapper.ml
src/dune_engine/action_to_sh.ml

This "action" is only used by the dune language to turn off dep/target
inference. It does nothing useful inside the engine

refactor: remove no-infer from engine actions

---

Makefile
flake.lock

The new commit sha introduces fewer dependencies, as `melange` and `mel` (which depends on luv -- slower to compile) are now different packages. We just need to depend on `melange`.

chore(melange): update Melange pin

---

.github/workflows/workflow.yml

This concurrency expression allows us to cancel runnings actions when we (force) push new commits.

ci: auto-cancel previous jobs

---

CHANGES.md
bin/import.ml
src/dune_engine/build_system.ml
src/dune_engine/build_system.mli

Looks like this if there are failures:
```sh
Done: 83% (3217/3849, 632 left, 1 failed) (jobs: 0)
```
and looks like this if there are none:
```sh
Done: 83% (3217/3849, 632 left) (jobs: 0)
```

feature: Show number of failed jobs during build

---

otherlibs/stdune/path.ml

I was searching for the ordering of the keys in a `Path.Set` and thought the pattern matching could be easier to read by refining some of the wildcards `_`.
I also added a docstring explaining how paths are compared. I wonder if it would be useful to add this information to `Path.Set`'s description and to he ones of other collections over paths.

refactor: clarify matching for path comparison and add a docstring

---

flake.nix

- Add a lighter version of the default shell that can bootstrap an environment with `nix develop .#slim`
- This is a little more cache-friendly with upstream, and avoids resolving all of opam-repository
- Useful for a quick env bootstrap to test something out

chore(nix): add `devShells.slim`

---

otherlibs/stdune/string.ml
test/expect-tests/stdune/string_tests.ml

Previously if the suffix was the entire string, drop_suffix would return the original string. This changes its behaviour to return the empty string instead in this case.

Fix bug in drop_suffix

---

.github/workflows/workflow.yml
Makefile
doc/concepts.rst
doc/conf.py

We also make `make doc` more strict with respect to Sphinx warnings and fix a few warnings.

ci: Add documentation job

---

.github/workflows/workflow.yml

- `Main Workflow` was a long and non-descriptive name. Has been replaced with `CI`.
- `build` job is now named `Build` for consistency with other jobs.
- `skip_test` does not need to be set to false when not included.

refactor(ci): misc cleanup

---

Makefile

Some users (me) have permission issues with their hostname.

makefile: bind on 0.0.0.0 for livedoc

---

CHANGES.md
doc/concepts.rst
doc/dune-files.rst
src/dune_rules/dep_conf_eval.ml
src/dune_rules/dune_file.ml
test/blackbox-tests/test-cases/glob_files_rec.t
test/blackbox-tests/test-cases/install-absolute-path-error.t

These cases now result in a user error being raised instead of crashing dune.

Prevent crash on absolute path in install stanza and glob_files_rec

---

test/blackbox-tests/test-cases/glob-deps-outside-directory.t

This adds a test that exercises our ability to handle globs that begin with ".." in preparation for a change that generalizes our implementation of globs

test: glob deps referring to outside the directory

---

CHANGES.md
bin/build_cmd.ml
bin/common.ml
bin/common.mli
bin/help.ml
bin/main.ml
otherlibs/stdune/ansi_color.ml

The patch follows the spec at <https://bixense.com/clicolors/> that has been implemented by multiple build systems and compilers already.
When Dune is not run in a tty (such as a CI system or a script), it will strip ANSI colors from the output of targets (such a tests runs). This is often undesirable.
Dune will now recognize the following environment variables and act according to the spec:
- `CLICOLOR != 0`
ANSI colors are supported and should be used when the program isn’t piped.
- `CLICOLOR == 0`
Don’t output ANSI color escape codes.
- `CLICOLOR_FORCE != 0`
ANSI colors should be enabled no matter what.
The behaviour regarding `TERM=dumb` is also retained.
This allows toggling from the global state the output of colors.
Fixes #6323.

Support `CLICOLOR` and `CLICOLOR_FORCE` to manage ANSI colors

---

otherlibs/stdune/ansi_color.ml
test/expect-tests/stdune/ansi_color_tests.ml

`Ansi_color.strip` removes ANSI escape sequences of colors[¹].
They start with the ASCII ESC (escape) character and end with the m character. The function used to copy valid characters character by character, but that is inefficient as we can copy to the destination buffer the whole valid substring at once.
Switching to unsafe string access in the inner loop yields another improvement.
The two combined show an improvement of 50% in a micro-benchmark realistic test case:
String of 562895 bytes with 1740 ANSI escape sequences. 
```
╭─────────────────────────┬───────────────────────────╮
│name                     │  monotonic-clock          │
├─────────────────────────┼───────────────────────────┤
│  strip strip_char       │        3090329.2703 ns/run│
│  strip strip_substring  │ …
```

refactor: optimize `Ansi_color.strip` perf by copying substrings

---

CHANGES.md
doc/dune-files.rst
src/dune_rules/artifacts_db.ml
src/dune_rules/dep_conf.ml
src/dune_rules/dep_conf.mli
src/dune_rules/dep_conf_eval.ml
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/file_binding.ml
src/dune_rules/file_binding.mli
src/dune_rules/glob_files.ml
src/dune_rules/glob_files.mli
test/blackbox-tests/test-cases/install-glob/install-glob-absolute-path.t
test/blackbox-tests/test-cases/install-glob/install-glob-files-only.t
test/blackbox-tests/test-cases/install-glob/install-glob-recursive.t
test/blackbox-tests/test-cases/install-glob/install-glob-sub-dir.t
test/blackbox-tests/test-cases/install-glob/install-glob-web-example.t/dune
test/blackbox-tests/test-cases/install-glob/install-glob-web-example.t/dune-project
test/blackbox-tests/test-cases/install-glob/install-glob-web-example.t/run.t
test/blackbox-tests/test-cases/install-glob/install-glob.t
test/blackbox-tests/test-cases/install-include/install-include-glob-files.t

Closes https://github.com/ocaml/dune/issues/6018

Add `(glob_files <glob>)` and `(glob_files_rec <glob>)` to the `files` field of the `install` stanza

---

src/dune_rules/exe_rules.ml
src/dune_rules/lib_rules.ml
src/dune_rules/merlin.ml
src/dune_rules/merlin.mli
test/blackbox-tests/test-cases/melange/merlin.t

If a library is defined only for melange, we tell merlin to use the
melange object dir to lookup cmi's

fix(melange): merlin support for melange only libs

---

bin/cache.ml

Looks like:
```
EXAMPLES
Trimming the Dune cache to 1 GB.
$ dune cache trim --trimmed-size=1GB
Trimming 500 MB from the Dune cache.
$ dune cache trim --size=500MB
```

doc: Improve documentation for dune cache

---

src/dune_rules/module_compilation.ml

As @anmonteiro mentioned, we want to use double hyphens for melange args. Support for single hyphens in long args are only there for backwards compatibility.

melange: use double hyphen for bs-read-cmi

---

test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/Test.v
test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/dune
test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/dune-project
test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/run.t

Test demonstrating #6366.
The issue is that `Context.coq_flags` is missing from the coqtop flags in coq_rules. This is not so easy to add however due to that being an `Action_builder`. I've tried refactoring the coqtop stuff to allow for this but it will require more work.

test(coq): add test demonstrating missing flags to dune coq top

---

otherlibs/stdune/path.ml
test/blackbox-tests/test-cases/dune-ppx-driver-system.t/run.t

this function should match [Path.to_string_maybe_quoted (Path.build p)]
ps-id: 361a98e9-00b4-4e35-afcd-8cf9902dcc0c

fix: [Path.Build.to_string_maybe_quoted]

---

CHANGES.md
src/dune_rules/ctypes_stanza.ml
test/blackbox-tests/test-cases/ctypes/github-5561-name-mangle.t

Causes an issue when external_library_name has mixed cases

fix(ctypes): remove unnecessary case changes

---

Makefile
dev.Dockerfile
docker/dev.Dockerfile
docker/dev.yml

Use it to setup some named volumes to make it easy to share _build and
_boot between containers.
ps-id: 3cdb09fc-2d1f-4e2c-8f70-452a6c3370c9

chore: add docker-compose

---

test/blackbox-tests/test-cases/private-package-lib/private-public-overlap.t

Add a test that demonstrates that a private library that's part of a
package can't depend on a library on that doesn't belong to any
packages.
ps-id: 833856c5-1297-44ea-b5f5-23da4b440ec3

test: incorrect private/public check

---

bin/install_uninstall.ml
otherlibs/stdune/fpath.ml
otherlibs/stdune/fpath.mli
otherlibs/stdune/path.ml
otherlibs/stdune/temp.ml
src/dune_file_watcher/dune_file_watcher.ml
test/expect-tests/stdune/fpath_tests.ml

We check that if a directory already exists that it is in fact a directory and not a file.

stdune: check if existing dir is actually a dir

---

src/dune_rules/melange_stanzas.ml
src/dune_rules/melange_stanzas.mli
src/dune_rules/ml_sources.ml
test/blackbox-tests/test-cases/melange/root-module.t

Adds support for `root_module` field, analog to `executable` stanza one.

feature(melange): support root_module

---

test/blackbox-tests/test-cases/promote/non-existent-subdir.t

Try to promote into a source directory that doesn't exist by setting up
the rule with `subdir`.
ps-id: 0cdd5220-e880-4ed1-a586-dd4133b17900

test: promote and subdir

---

Makefile

Now that 0.3.0 is out (thanks @anmonteiro!), dune doesn't need to pin melange any longer.

chore(melange): replace pin with opam version

---

doc/dune-files.rst

The `(mdx 0.3)` syntax was added in Dune 3.2 by <https://github.com/ocaml/dune/commit/9783f3ff17680f383c9cb7c4897a95a62b5e2a55>, but this wasn't documented. This commit updates the default version in the manual and points out that the `lock` stanza requires mdx stanza 0.3.

Document that `(mdx (locks …))` require mdx 0.3 stanza

---

CHANGES.md
src/dune_rules/artifact_substitution.ml
test/blackbox-tests/test-cases/promote/non-existent-subdir.t

If a subdir stanza defines a rule that promotes into a non-existent
source dir, it would fail. Now we just create the directory in the
source.
ps-id: e7b4b471-0c58-480a-a433-2f8aaa207153

fix: allow promoting with subdir

---

.github/workflows/workflow.yml

instead of @all which pull in a lot of other stuff
ps-id: 62e27328-da02-4bae-a278-5164627aa917

fix(ci): build @install to build dune

---

src/dune_rules/melange_rules.ml
src/dune_rules/melange_stanzas.ml
src/dune_rules/melange_stanzas.mli
test/blackbox-tests/test-cases/melange/aliases.t

Adds field `alias` to `melange.emit` so the stanza can be written as follows:
```
(melange.emit
(target output)
(alias app)
(module_system commonjs))
```
The alias rule has only the `melange.emit` `entries` as deps, not the modules resulting from depending on other libraries.

feature(melange): alias field for `melange.emit`

---

src/dune_rules/melange_binary.ml
src/dune_rules/melange_binary.mli
src/dune_rules/melange_rules.ml
src/dune_rules/merlin.ml
src/dune_rules/module_compilation.ml
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli

ps-id: cce82426-de1a-4473-a3af-1a91ab987de5

feature(melange): add correct stdlib dir

---

src/dune_rules/melange.ml
src/dune_rules/melange.mli
src/dune_rules/melange_rules.ml

it's only used in [Melange_rules] so it should be defined there
ps-id: a096ab9f-c424-49d7-9735-9dac97f007d8

refactor(melange): move [lib_output_dir]

---

src/dune_rules/dir_contents.ml

Something small I noticed when reading the code.

refactor(dir_contents): reuse "ocaml" for forcing t.ml

---

src/dune_rules/melange_rules.ml
test/blackbox-tests/test-cases/melange/include_subdirs.t/run.t
test/blackbox-tests/test-cases/melange/outside.t/dune-project
test/blackbox-tests/test-cases/melange/outside.t/inside/c.ml
test/blackbox-tests/test-cases/melange/outside.t/inside/dune
test/blackbox-tests/test-cases/melange/outside.t/lib/b.ml
test/blackbox-tests/test-cases/melange/outside.t/lib/b.mli
test/blackbox-tests/test-cases/melange/outside.t/lib/dune
test/blackbox-tests/test-cases/melange/outside.t/run.t
test/blackbox-tests/test-cases/melange/private.t/run.t
test/blackbox-tests/test-cases/melange/public.t/run.t
test/blackbox-tests/test-cases/melange/simple.t/run.t

Introduce a new layout that allows any library from the workspace to be
used in emit. The new layout now follows these rules:
* $emit_stanza/$target defines the root
* any library in $path will now be in $emit_stanza/$target/$path
* entry module $x will now be in $emit_stanza/$target/$emit_stanza/$x
The scheme is quite ugly but it lifts the annoying limitation of
re-arranging the project.
ps-id: a4c025e6-eedb-4b1e-8d55-ec5b6a1eeeae

feature(melange): more flexible layout for emit

---

test/blackbox-tests/test-cases/cram/custom-build-dir.t

Which means that running dune inside a cram test when DUNE_BUILD_DIR is
set doesn't work
ps-id: cd8c01a3-63d3-470e-be02-445c1bfdfa3e

test: DUNE_BUILD_DIR leaks to cram tests

---

src/dune_rules/artifacts_db.ml
src/dune_rules/cinaps.ml
src/dune_rules/exe_rules.ml
src/dune_rules/install_rules.ml
src/dune_rules/lib.ml
src/dune_rules/lib.mli
src/dune_rules/mdx.ml
src/dune_rules/melange_rules.ml
src/dune_rules/merlin_ident.ml
src/dune_rules/merlin_ident.mli
src/dune_rules/toplevel.ml
src/dune_rules/utop.ml
test/blackbox-tests/test-cases/melange/merlin.t

Makes sure that a merlin conf is generated for `melange.emit` stanzas.
Added some additional test, and tested on a demo project, seems to work fine.

feature(melange): fix merlin for emit stanza

---

docker/dev.Dockerfile

kate's workaround to set the image to use 2.1
ps-id: 2169cac7-ee84-4c22-8186-9f1e0f5a1535

chore: use opam 2.1 in docker images

---

test/blackbox-tests/test-cases/cram/custom-build-dir.t

The error message printed the pid, which affected the message's wrapping
depending on the pid's number of digits.
ps-id: ab179e80-5975-4dc5-acd4-97a79ac285ba

test: custom-build-dir should be reproducible

---

src/dune_rules/dir_status.ml

forbid [(melange.emit ..)] from appearing under [(include_subdirs
unqualified)]
ps-id: 5e380e59-4bf5-4847-9344-07db138b8f60

fix(melange): handle include_subdirs unqualified

---

src/dune_engine/diff_promotion.ml

Using List.sort is just as good and [FileMap] violated our casing
convention
ps-id: b09c7aa4-8014-4e9e-8d1d-18fb2b1e24d6

refactor: remove temporary map used for sorting

---

.readthedocs.yaml
Makefile
doc/conf.py
doc/requirements.txt
flake.nix

This is imo a nice usability improvement ;-)
Using sphinx-copybutton <https://sphinx-copybutton.readthedocs.io/en/latest/>.
Hope I've setup nix flakes correctly. Building works locally but I haven't tested nix stuff.

doc: add button to copy code blocks in Dune manual

---

src/dune_rules/module_compilation.ml

* reduce scope of bindings
* add a helper for melange args
ps-id: e4059d8b-6f96-4b2a-9fad-a787c0aa73f8

refactor: clean up module compilation

---

CHANGES.md
doc/coq.rst
src/dune_rules/coq_mode.ml
src/dune_rules/coq_mode.mli
src/dune_rules/coq_rules.ml
src/dune_rules/coq_stanza.ml
src/dune_rules/coq_stanza.mli
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/dune-project
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/run.t
test/blackbox-tests/test-cases/coq/coqtop/coqtop-flags.t/run.t

We omit the need for native to be specified in the coq.theory stanza and instead allow for Dune to automatically detect whether to enable native compilation via the output of `coqc -config` which was exposed in #6049. This continues and finishes an earlier attempt to do someting similar in #4722.
cc @proux01 @ejgallego

feature(coq): automatic detection of native

---

src/dune_rules/dir_status.ml

When we tell the user a stanza is forbidden under [(include_subdirs
$type)] we should write the correct $type rather than guess it's
[unqualified]
Adding Ali as a reviewer as this only affects error messages for coq

fix: improve error message for status db

---

flake.lock
flake.nix

- [nix-overlays](https://github.com/nix-ocaml/nix-overlays) enables flambda by default
- depending on the melange flake forces dune developers to build an extra flambda compiler to work on Dune
- this change uses the upstream OCaml from nixpkgs which should always be cached in cache.nixos.org

chore(nix): make it faster to get melange

---

bin/common.ml
bin/common.mli
bin/import.ml

This mostly applies to merlin and some rpc based commands.
ps-id: 55faf889-a62e-458a-aed0-efac084a64c1

fix: respond to signals when not building

---

otherlibs/stdune/path.ml
otherlibs/stdune/path.mli
src/dune_rules/context.ml
src/dune_rules/findlib/findlib.ml
src/dune_rules/findlib/findlib.mli
test/expect-tests/findlib_tests.ml

use Path.Outside_build_dir.t for findlib config paths
ps-id: 2467264d-4ef8-45e3-9a48-dfdf9a62119f

refactor: path type safety

---

test/blackbox-tests/test-cases/melange/empty-entries-target-dir-exists.t

This tests demonstrates an unintuitive error message when the `melange.emit` target directory exists. 
I'm not sure what can be done about this, perhaps @rgrinberg has ideas.

test(melange): demonstrate build failure when target dir exists

---

CHANGES.md
bin/common.ml
otherlibs/stdune/ansi_color.ml
otherlibs/stdune/ansi_color.mli

We want to enable the status line if and only if stderr is a tty. ANSI color usage was tweaked in 3.6.0 with #6340 to allow users to force colors. As status line activation actually depended on whether ANSI colors were enabled or not, this change had the side effect to always enable the status line even when ANSI colors were requested for something that's not a tty.
Fix this by exposing a simple lazy wrapper of `Unix.isatty` to use instead of `Ansi_color.stderr_supports_color`.

Fix status line enabled when ANSI colors are forced

---

src/dune_rules/virtual_rules.ml

ps-id: d6db4e0f-752c-4f01-a20e-c0078752e40f

refactor: small style tweaks

---

CHANGES.md
src/dune_util/dune_flock.c
src/dune_util/flock.ml
src/dune_util/global_lock.ml

Implement file locking (for the global lock) using `LockFileEx` to avoid having two OCaml implementations of the global lock.
Incidentally, while testing this PR I came across an issue which is also present in `main` (it is independent of the present PR): currently `dune clean` fails on Windows due to the `.lock` file being open inside the `_build` directory. A possible solution would be to keep this file outside the `_build` directory. Opinions? cc @dra27
See https://github.com/ocaml/dune/pull/6360#discussion_r1027136625 for context.

Implement flock on Windows with LockFileEx + 'dune clean' fix on Windows

---

CHANGES.md
doc/dune-files.rst

Fixes #5493
Moreover, the "man" page for `dune-config(5)` is terribly out-of-date and does not seem very pratical to have the information in two places (the manual and the man page). Since we don't document any other Dune file format in man page format, shall we get rid of the `dune-config(5)` man page?

Add doc for config file

---

src/dune_engine/action_builder.mli
src/dune_engine/dialect.mli
src/dune_engine/scheduler.ml
src/dune_engine/source_tree.ml
src/dune_engine/sub_dirs.mli
src/dune_lang/pform.mli
src/dune_rules/foreign_language.mli
src/dune_rules/lib.mli
src/dune_rules/module.mli
src/dune_rules/module_name.mli
src/dune_rules/ordered_set_lang.mli
src/dune_rules/resolve.mli
src/dune_rules/visibility.mli
src/ocaml/cm_kind.mli
src/ocaml/ml_kind.mli
src/ocaml/mode.mli

instead of destructive substitution
ps-id: 3ab6fc21-70d4-4f62-aad6-16c320c7f863

refactor: use type aliases in type signatures

---

CHANGES.md
bin/common.ml
bin/common.mli
bin/ocaml_merlin.ml
bin/rpc.ml
otherlibs/site/test/run.t
test/blackbox-tests/test-cases/depend-on/installed-packages.t
test/blackbox-tests/test-cases/dune-package.t/run.t
test/blackbox-tests/test-cases/write-permissions.t

these two setting should always be set together
coincidentally, this also correctly removes the `Entering Directory` messages for install commands. This is expected as those commands do not build or print errors.

refactor: unify print dir and forbid_builds

---

CHANGES.md
otherlibs/configurator/src/v1.ml

When using MSVC, the output flag should be `-Fe<exe name>` and `-Fo<obj name>` instead of `-o <exe name>` and `-o <obj name>`.
Also removed some MSVC-specific logic that doesn't seem to be needed.
cc @jonahbeckford
Fixes #6537

Fix configurator MSVC invocations

---

src/dune_rules/lib_rules.ml

symlink instead of copying object files that live along the .cma
ps-id: 95606075-fe44-4866-91da-1612d28ecd31

refactor: speed up stdlib build

---

bin/common.ml

I somehow corrupted the digest database and hit the following exception on Dune startup:
```
Description:
("Fdecl.get: not set", {})
Raised at Stdune__Code_error.raise in file "code_error.ml", line 10,
characters 30-62
Called from Stdune__Fdecl.get in file "fdecl.ml" (inlined), line 23,
characters 13-53
Called from Dune_util__Log.t in file "log.ml" (inlined), line 41, characters
11-22
Called from Dune_util__Log.info_user_message in file "log.ml", line 44,
characters 8-12
Called from Dune_util__Persistent.Make.load.(fun) in file "persistent.ml",
line 72, characters 14-345
Called from Stdune__Exn.protectx in file "exn.ml" (inlined), line 10,
characters 8-11
Called from Stdune__Io.Make.with_file_in in file "io.ml" (inlined), line 102,
characters 35-89
Called from …
```

Call [Dune_util.Log.init] as soon as possible

---

src/dune_rules/exe_rules.ml
src/dune_rules/lib_rules.ml
src/dune_rules/melange_rules.ml
src/dune_rules/merlin.ml
src/dune_rules/merlin.mli

Merlin rules shouldn't resolve the preprocessor spec as this breaks lazy
loading.
In particular, if a ppx preprocessor isn't resolved, then all the rules
in that dune file will fail to load.
ps-id: 3caf59c2-23c5-42cf-8652-8df41dc80bc3

fix: merlin rules with pp's

---

CHANGES.md
src/dune_rules/module_compilation.ml

ths environment should be obtained from the directory of the module and
not the root.
ps-id: b1a39f83-6e31-4229-af7c-b428df4f5aa6

fix: module compilation rule env

---

flake.lock
flake.nix

I noticed a few problems with the regular shell:
- every time the source tree changes, opam2nix does full resolution again and rebuilds everything
- somehow, using the `nixpkgs` input doesn't give me editor completion on the slim shell, but using `nix-overlays` as the input fixes it for me
Steps to reproduce:
```shell
$ nix develop .#slim -c zsh
$ make clean && make dev
$ nix develop .#slim -c nvim
```

chore(nix): use nix-overlays for the slim devShell

---

bin/ocaml_merlin.ml
test/blackbox-tests/test-cases/merlin/server.t/run.t
test/blackbox-tests/test-cases/merlin/symlinks.t/run.t

ps-id: 9629267c-bc9b-45d0-b88b-4d1008c0229d

refactor: simplify merlin

---

src/dune_rules/dir_contents.ml
src/dune_rules/ml_sources.ml
src/dune_rules/ml_sources.mli
test/blackbox-tests/test-cases/virtual-libraries/same-directory.t

This is a follow-up to https://github.com/ocaml/dune/pull/6550

fix: raise when virtual library / implementations are in the same directory

---

test/blackbox-tests/test-cases/melange/ocaml-flags.t

It is useful to have a test that covers the way `ocamlc_flags` and `ocamlopt_flags` fields interact with Melange builds. This PR adds it, in addition to the existing `flags.t` test.

melange: add test for ocaml flags

---

CHANGES.md
bin/common.ml
otherlibs/stdune/ansi_color.ml
otherlibs/stdune/ansi_color.mli

We want to enable the status line if and only if stderr is a tty. ANSI
color usage was tweaked in 3.6.0 with #6340 to allow users to force
colors. As status line activation actually depended on whether ANSI
colors were enabled or not, this change had the side effect to always
enable the status line even when ANSI colors were requested for
something that's not a tty.
Fix this by exposing a simple lazy wrapper of Unix.isatty to use
instead of Ansi_color.stderr_supports_color.
Signed-off-by: Antonin Décimo <antonin@tarides.com>

[3.6] backport #6503 (status line fix)

---

src/fsevents/fsevents_stubs.c

by disabling watch mode on such versions
ps-id: dc8e96cc-61a9-4497-baac-0934b82efe6f

fix: re-enable dune on older macos sdk's

---

src/dune_rules/module.ml

define all kinds in a list to avoid copy pasting in converters
ps-id: 1cdfe380-b448-4983-b355-922ae509fd3e

refactor: module kinds

---

src/dune_rules/modules.ml
src/dune_rules/modules.mli

ps-id: abe40fa8-2e33-43c3-a4a3-98a29aa27ae6

refactor: remove Modules.is_empty

---

CHANGES.md
src/dune_rules/format_rules.ml
test/blackbox-tests/test-cases/formatting/format-alternative.t

alternative file names such as dune-file should be accepted
ps-id: cd846c27-e187-4513-8f51-ec53bcca332e

fix: format alternative file names

---

src/dune_engine/source_tree.ml
src/dune_engine/source_tree.mli
src/dune_engine/sub_dirs.ml
src/dune_engine/sub_dirs.mli
src/dune_rules/dir_contents.ml
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/dune_load.ml
src/dune_rules/format_rules.ml

The dune file path returned by Source_tree.Dune_file is always present.
This is wrong because some dune files are generated using subdir. This
commit tweaks the API to reflect this fact and updates the rest of the
code to handle such virtual dune files.
ps-id: b2dfc4df-ea48-491c-987e-b9b3d193e597

fix: dune files from source tree

---

src/dune_rules/artifacts.ml
src/dune_rules/artifacts.mli
src/dune_rules/gen_rules.ml

ps-id: aa7062b3-986e-478e-b1e0-e157d9f0382d

refactor: define the .bin magic path once

---

otherlibs/dune-rpc-lwt/src/dune_rpc_lwt.ml

- Lwt is introducing a breaking change in `Lwt_result` in the next release (cf. https://github.com/ocsigen/lwt/pull/965).
- This change allows `dune-rpc-lwt` to be forward compatible with that change

refactor(dune-rpc-lwt): forward compatiblity with upcoming Lwt_result

---

src/dune_rules/module_compilation.ml
src/dune_rules/modules.ml

the library interface for modules shouuld always be present
ps-id: a0bd5d9c-5212-4e05-b78a-a047f988cc09

refactor: wrapped modules refactor

---

src/dune_rules/modules.ml
src/dune_rules/modules.mli

it's unused
ps-id: e275dcc8-736d-4ffc-9205-127642f742b7

refactor: remove Modules.map

---

bin/arg.ml
bin/install_uninstall.ml

`Cmdliner.Arg.conv` happens to be a pair of `parser` and `printer` but is marked as to be made abstract. Actually the work on completion requires making it abstract and modify it. So this PR switches to using just the public API.

refactor: assume Cmdliner.Arg.conv is abstract

---

CHANGES.md
src/dune_rules/cxx_rules.ml
test/blackbox-tests/test-cases/cxx-flags.t/run.t

This ensures that c++ compiler can be detected even with an explicit `--sandbox`.
Fixes #6415

fix: declare deps for ccomp detection

---

dune-file

Since #6340 we're considering `CLICOLOR_FORCE` to determine whether stderr supports color. However this changes behavior observable from the test suite, so `CLICOLOR_FORCE=1 make test` fails (this is tracked as #6607).
The issue is that ocaml/setup-ocaml#631, this variable is set in the CI environment. So we disable it until the situation is fixed (and this variable does not have observable changes anymore).

Set CLICOLOR_FORCE=0

---

src/dune_rules/dir_contents.ml
src/dune_rules/dune_file.ml
src/dune_rules/dune_package.ml
src/dune_rules/dune_package.mli
src/dune_rules/findlib/findlib.ml
src/dune_rules/lib.ml
src/dune_rules/lib_info.ml
src/dune_rules/lib_info.mli

refactor: move `modules: Modules.t` from `Dune_package.Lib` to `Lib_info`

---

src/dune_rules/link_time_code_gen.ml
src/dune_rules/module.ml
src/dune_rules/module.mli

do not "guess" object names when generating link time modules.
Actually look up the generated module and find the object name
ps-id: 8cd946aa-9f0d-4895-8f98-9bc1320a82a1

fix: link time code gen

---

src/dune_rules/coq_config.ml
src/dune_rules/coq_config.mli
src/dune_rules/coq_rules.ml

Before we were failing if for some reason `coqc --config` failed when selecting the native mode. This makes it so that if for whatever reason `coqc --config` doesn't succeed then we default to vo mode.

coq: more resilient config query

---

doc/hacking.rst

I explained these patterns to newcomers recently so I think they make sense to be included in our guide.

doc: how we write `to_dyn` and `equal`

---

bin/cache.ml
test/blackbox-tests/test-cases/dune-cache/cache-man.t
test/blackbox-tests/test-cases/dune-cache/trim.t

We also do some cleanup of the documentation. This will make adding more subcommands easier in the future.
The (deprecated and removed) commands start and stop have also been completely removed.
closes #4471

refactor(cache): use cmdliner groups in dune cache commands

---

CHANGES.md
src/dune_rules/utop.ml
test/blackbox-tests/test-cases/utop/lib-under-subdir.t

data_only_dirs can also define libraries using (subdir ..)
ps-id: 5af7aeb4-f29b-4338-aa14-fe2d568245be

fix: load rules under subdir

---

test/blackbox-tests/test-cases/dune
test/blackbox-tests/test-cases/link-time-transitive-deps.t

reproduce the issue in PR #6633
link time code generation doesn't use the correct compilation closure
for the build info module. It uses the compile closure but we should use
the link closure
ps-id: 17ab080e-5060-4f3e-9f0c-20d74b58f6ce

test: transitive deps and link time code gen

---

CHANGES.md
src/dune_rules/compilation_context.ml
test/blackbox-tests/test-cases/link-time-transitive-deps.t

correctly set the includes when computing the compilation context for
link time modules
ps-id: 80738955-dbfe-4717-b014-1d4544b2d4bc

fix: link time code gen + implicit transtive deps

---

CHANGES.md
src/dune_rules/inline_tests.ml
test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t

The first commit update an existing test to demonstrate the bug.

Fix inline_tests with jsoo and whole_program compilation mode

---

src/dune_rules/merlin.ml
test/blackbox-tests/test-cases/melange/merlin.t

This PR changes the ordering in which melange flag directive and user preprocessing directive are applied.
By inverting this order, Merlin will apply Melange ppx first, so it does not fail when encountering "melange-isms" like pipe first operator.
Tested on a couple of projects with a couple dozen files with different ppxs applied, seems Merlin integration works smoothly, modulo hovering over Melange stdlib values as reported on #6467.

melange: change flag directives ordering for merlin

---

otherlibs/dune-rpc/private/dune_rpc_private.ml

If version negotiation fails due to an unexpected response from the
server, we cleanly terminate the connection.
ps-id: 3c00ded6-eec7-4cce-a841-40705ac99aad

fix(rpc): improve error handling

---

test/blackbox-tests/test-cases/melange/flags.t

Fixes #6572. The PR just adds a test to demonstrate the functionality, but the implementation was added in #6569 inadvertently, as `Dune_env` and `Dune_file` both decode using the same function in `Ocaml_flags`:
https://github.com/ocaml/dune/blob/1798cc6a4d8fa65d6f2fddc59f848f07f0c5d2b3/src/dune_rules/dune_env.ml#L191
https://github.com/ocaml/dune/blob/1798cc6a4d8fa65d6f2fddc59f848f07f0c5d2b3/src/dune_rules/dune_file.ml#L172
Unless I'm missing something.

melange: add test to show flags passed from env

---

otherlibs/dune-rpc/private/conv.ml
otherlibs/dune-rpc/private/conv.mli
otherlibs/dune-rpc/private/dune_rpc_private.ml
otherlibs/dune-rpc/private/dune_rpc_private.mli
otherlibs/dune-rpc/private/types.ml
otherlibs/dune-rpc/private/types.mli
src/dune_rpc_server/dune_rpc_server.ml

This adds the ability to for RPC servers to send requests to the server. In other words, it makes the RPC protocol bidirectional. This is needed for dune to distribute actions among forkers. To send an action to a forker, dune will now make a request to the appropriate forker client.
This PR only adds the machinery at the level of RPC packets being sent. To finish this, I'll add version negotiation for server -> client requests in a subsequent PR.

feature(dune-rpc): bidirectional communication

---

test/blackbox-tests/test-cases/actions/dune

it's flaky everywhere, not just on macos
ps-id: ac670f7d-7914-4eb1-be0a-e800a542142a

test: re-enable stray-proces test on macos

---

boot/libs.ml
src/csexp_rpc/csexp_rpc.ml
src/csexp_rpc/csexp_rpc.mli
src/csexp_rpc/dune
src/dune_engine/dune
src/dune_engine/scheduler.ml

Use an ugly forward declaration to break the dependency cycle. We need
to do this because we want to use RPC inside the engine, and this is
currently impossible because [Csexp_rpc] cannot be included.
ps-id: 3700019c-b2be-4913-8f28-b85e0a6eb594

refactor(csexp_rpc): remove dune_engine dep

---

src/dune_engine/build_config.ml
src/dune_engine/build_config.mli
src/dune_engine/load_rules.ml
src/dune_rules/gen_rules.ml
src/dune_rules/odoc.ml

now it allows generating rules in addition to redirecting
ps-id: c63babc4-cd24-4d16-8c49-b1e4de16660e

feature: Redirect_to_parent improved

---

CHANGES.md
otherlibs/ocamlc_loc/src/lexer.mli
otherlibs/ocamlc_loc/src/lexer.mll
otherlibs/ocamlc_loc/src/ocamlc_loc.ml
otherlibs/ocamlc_loc/src/ocamlc_loc.mli
otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml

correctly parse alerts and add a new severity kind
ps-id: 4ec7db6f-4026-4936-991c-fcfc4d535ba2

fix(ocamlc_loc): parse alerts

---

src/dune_rules/melange_rules.ml

Use [Dir_contents.modules_of_lib]. This function will work once external
libraries are also supported.
ps-id: ae9c4956-1a2c-4f5d-be06-87411b6903be

refactor(melange): simplify module handling

---

doc/overview.rst

Small typo I realized when reading the docs, which triggered an ugly 80 column reformatting.

Fix missing parenthesis in docs

---

otherlibs/stdune/user_message.ml

This is so that it is formatted correctly if it appears in a Pp.vbox.

fix(User_message): put a box around the location Pp.t

---

doc/overview.rst

It moved from @samoht to @ocamllabs to @tarides now.

Update URL to dune-release

---

otherlibs/stdune/ansi_color.ml
otherlibs/stdune/ansi_color.mli
otherlibs/stdune/user_message.ml
src/dune_engine/process.ml
test/expect-tests/stdune/ansi_color_tests.ml

We need to ability to match on Ansi_color.t in #6654.

refactor(ansi_color): Make Ansi_color.t into a variant

---

bin/common.ml
bin/common.mli
src/dune_config/dune_config.ml
src/dune_config/dune_config.mli
src/dune_engine/display.ml
src/dune_engine/display.mli
src/dune_engine/dune_engine.ml
src/dune_engine/process.ml
src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli

Now it lives in its own module. Later to be decoupled from [Scheduler]
ps-id: 6ed60e23-799a-4f75-a101-8b408a60b2e7

refactor(dune_engine): move [Display]

---

otherlibs/stdune/ansi_color.ml
otherlibs/stdune/env.ml

Save some syscalls when detecting the functionality of the tty
ps-id: e70564a3-cf06-4c6b-bae1-db0839095046

refactor(stdune): high performance tty detection

---

dune-project
ocamlc-loc.opam
otherlibs/ocamlc_loc/src/lexer.mli
otherlibs/ocamlc_loc/src/lexer.mll
otherlibs/ocamlc_loc/src/ocamlc_loc.ml
otherlibs/ocamlc_loc/src/ocamlc_loc.mli

ps-id: e8d8a78e-24a1-4674-8270-d3276c9976ad

refactor(ocamlc_loc): uniform handling of codes

---

src/dune_rules/artifacts_db.ml
src/dune_rules/cinaps.ml
src/dune_rules/install_rules.ml
src/dune_rules/lib.ml
src/dune_rules/lib.mli
src/dune_rules/mdx.ml
src/dune_rules/melange_rules.ml
src/dune_rules/toplevel.ml

[allow_overlaps] and [forbidden_libraries] must always be provided
ps-id: fbc63255-6f69-4d6b-8a4d-862ee22bdd23

refactor: remove optional arguments from lib

---

CHANGES.md
bin/dune_init.ml
test/blackbox-tests/test-cases/init-error-if-dune-is-directory.t

When running `dune init (exe|lib|test)` in a directory which contains a directory named "dune", prior to this change, the error would be: Error: Is a directory
Following this change, the error is now:
Error: "/path/to/dune" already exists and is a directory

Error on "dune init" if dir exists named "dune"

---

src/dune_rules/melange_rules.ml
src/dune_rules/melange_stanzas.ml
src/dune_rules/melange_stanzas.mli

Overlapping dependencies allow for the same dependency to be pulled both
from the workspace and installed libraries, as long as they aren't used
in the same closure.
This feature isn't particularly useful, but I've added it because for parity executable and because it's very easy to do so.

feature(melange): allow overlapping dependencies

---

test/blackbox-tests/test-cases/build-percent-form-bin.t

The command $ dune build %{bin:..} doesn't work correctly
ps-id: dc34b284-e534-4b73-a300-63a91fe8ff85

test: demonstrate dune build bug

---

CHANGES.md
src/dune_sexp/lexer.mll
test/expect-tests/dune_lang/sexp_tests.ml

This PR adds two tests that the sexp lexer for strings errors out on digit escape sequences such as "\0000" and "\x000" and fixes the issue.
I stumbled upon that issue by trying to install a locally-pinned opam package into a switch named “5β2”, which generated a `dune-package` containing `5\206\1782` which did not parse correctly.

Fix sexp lexer for escaped sequences such `\000` followed by another digit

---

CHANGES.md

CHANGES.md is for user facing changes rather than developer facing
changes
ps-id: bc1b1111-6687-4a5a-a41e-9843f7c2ccbd

chore(CHANGES): remove CI item

---

otherlibs/dune-rpc/private/dune_rpc_private.mli
otherlibs/dune-rpc/private/versioned.ml
otherlibs/dune-rpc/private/versioned.mli

We write an explicit interaface for Versioned.Make so that callers can
include it in their signatures.
ps-id: 1591cce2-128a-4d6e-9d4d-ccc2a6a66d03

refactor(rpc): explicit Versioned.Make interface

---

doc/cross-compilation.rst

Existing examples cause the following error:
```
File "dune-workspace", line 6, characters 3-27:
6 |    (native windows android))))
^^^^^^^^^^^^^^^^^^^^^^^^
Error: Atom or quoted string expected
```

docs: fix parse error in example

---

CHANGES.md
src/csexp_rpc/csexp_rpc.ml

We use the pipe trick to interrupt the accept loop. This needs the pipe
to be non blocking, but non blocking pipes are emulated on windows so we
shouldn't try to set them to non blocking.
ps-id: 2dac6f72-88da-4456-97ac-0c55e080a10a

fix(rpc): windows

---

src/dune_rpc_server/dune

do not rely on stdune exporting them
ps-id: 31ba6b1c-69f7-4cf6-90fe-575616a3b1b3

refactor: add missing dyn & ordering dependencies

---

src/dune_rules/melange_rules.ml
src/dune_rules/melange_stanzas.ml
src/dune_rules/melange_stanzas.mli
src/dune_rules/ml_sources.ml
test/blackbox-tests/test-cases/melange/intfonly-entries.t

When intf only modules are included in melange.emit, we shouldn't
generate js rules for them
ps-id: ef68aca1-e36b-42b9-8bf9-00564ee968d3

fix(melange): intf only modules

---

CHANGES.md
src/dune_rules/artifact_substitution.ml
test/blackbox-tests/test-cases/dune
test/blackbox-tests/test-cases/version-corruption.t

For [issue 6668 ](https://github.com/ocaml/dune/issues/6668), expected to fail and segfault until the bug is fixed

Add version corruption testcase and fix binary corruption

---

src/dune_rules/bootstrap_info.ml

We shouldn't emit `In_source_tree`, but rather raw relative paths as
strings
ps-id: 5807da91-5c6e-43f7-a1b0-c3d33472eaa7

fix: boostrap generation

---

src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli

yield_if_there_are_pending_events is unused
ps-id: 631072bf-8a7f-48e7-a093-fd20c5554e0e

refactor(scheduler): remove unused function

---

src/dune_engine/scheduler.ml

Worker_task, Yield, Timer are all synonyms for Fiber.fill. There's no
sense in duplicating them.
ps-id: e7076281-f806-4c71-aaf6-6f9511bbd893

refactor(scheduler): remove redundant events

---

src/memo/memo.ml

Do not allocate a tuple that gets thrown away immediately
ps-id: 50a3bfe1-ea76-43a8-a4e4-ccaff30c88d9

refactor(memo): optimize Memo.Lazy.create

---

otherlibs/stdune/signal.ml
otherlibs/stdune/signal.mli
src/dune_engine/process.ml
src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli
src/dune_util/log.ml

The `Signal` module is general purpose enough to live in `Stdune`. I've also expanded it to cover all known signals.

refactor(scheduler): move [Signal] to [Stdune]

---

src/dune_rules/melange_rules.ml
test/blackbox-tests/test-cases/melange/dune-js-file-unmangling.t/dune
test/blackbox-tests/test-cases/melange/dune-js-file-unmangling.t/run.t
test/blackbox-tests/test-cases/melange/empty-entries.t
test/blackbox-tests/test-cases/melange/flags.t
test/blackbox-tests/test-cases/melange/include_subdirs.t/inside/dune
test/blackbox-tests/test-cases/melange/include_subdirs.t/run.t
test/blackbox-tests/test-cases/melange/intfonly.t/dune
test/blackbox-tests/test-cases/melange/intfonly.t/run.t
test/blackbox-tests/test-cases/melange/javascript-extension.t
test/blackbox-tests/test-cases/melange/missing-melc.t
test/blackbox-tests/test-cases/melange/mli.t/dune
test/blackbox-tests/test-cases/melange/mli.t/run.t
test/blackbox-tests/test-cases/melange/multilib.t/dune
test/blackbox-tests/test-cases/melange/multilib.t/run.t
test/blackbox-tests/test-cases/melange/ocaml-flags.t
test/blackbox-tests/test-cases/melange/preprocess.t
test/blackbox-tests/test-cases/melange/private.t/inside/dune
test/blackbox-tests/test-cases/melange/private.t/run.t
test/blackbox-tests/test-cases/melange/public.t/my_project/dune
test/blackbox-tests/test-cases/melange/public.t/run.t
test/blackbox-tests/test-cases/melange/root-module.t
test/blackbox-tests/test-cases/melange/simple.t/lib/dune
test/blackbox-tests/test-cases/melange/simple.t/run.t
test/blackbox-tests/test-cases/melange/unmangling.t
test/blackbox-tests/test-cases/melange/virtual_lib.t/dune
test/blackbox-tests/test-cases/melange/virtual_lib.t/run.t

* Build all js artifacts concurrently
* Use glob dependencies to represent dep graph more efficiently
Now we are pretty much required to introduce an alias to make the melange.emit usable, as we no longer require runtime dependencies to build dependencies as well.

refactor(melange): improve build plan

---

src/dune_rules/coq_sources.ml
test/blackbox-tests/test-cases/coq/theory-stanza-duplicate-module.t/run.t

I encountered this when writing a Dune file for a project with an explicit modules field. This should give a nicer message.

fix(coq): add error message for duplicate module decleration

---

CHANGES.md
bin/common.ml
bin/common.mli
bin/dune_init.ml
bin/init.ml
test/blackbox-tests/test-cases/config/config-in-workspace-file.t
test/blackbox-tests/test-cases/dune-init-proj-no-spurious-build-dir.t
test/blackbox-tests/test-cases/dune-init.t/run.t

Fixes https://github.com/ocaml/dune/issues/5429

Prevent spurious _build directory from being created when running `dune init proj ...`

---

otherlibs/stdune/ansi_color.ml

when this variable is absent, we should not force colors
ps-id: a96f4cc6-068c-4b53-946d-8a9986ca986c

fix: handle missing CLICOLOR_FORCE correctly

---

src/dune_engine/dune_project.ml
src/dune_engine/dune_project.mli
src/dune_rules/dir_status.ml
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/gen_rules.ml
src/dune_rules/melange_stanzas.ml
src/dune_rules/melange_stanzas.mli
src/dune_rules/ml_sources.ml
src/dune_rules/ocaml_flags.ml

It should exist in [Melange_stanzas]
ps-id: bee92f9b-6ded-4f47-b13a-25052ac6ff48

refactor(melange): move stanza definition

---

CHANGES.md
src/dune_rules/compilation_context.ml

ocamlc and ocamlopt don't play well with sandboxing, but ocamldep is
fine
ps-id: cd518774-0ed7-4f52-9169-a709ac1ab7a7

fix: do not impose no_sandboxing on ocamldep

---

src/dune_engine/scheduler.ml

In some buggy tests, this error leaks. It's useful to print what it is
in such cases.
ps-id: 403a00cb-7113-470d-b6dd-a0ed14ddb8e2

refactor: print shutdown exception

---

doc/toplevel-integration.rst

Signed-off-by: Armaël Guéneau <Armael@users.noreply.github.com>
According to the changelog, `dune ocaml top-module` was in fact introduced in dune 3.6.0 (and indeed the command doesn't seem to exist in dune 3.4.0).

doc: fix version indication for "dune ocaml top-module"

---

src/dune_rules/melange_rules.ml

they just add indirection and the globs are never re-used
Note that this also improves the correctness of the rules somewhat. As we don't pull .js rules that might accidentally be inside the emit target dir.

refactor(melange): remove js globs

---

src/dune_rules/check_rules.ml
src/dune_rules/check_rules.mli
src/dune_rules/exe_rules.ml
src/dune_rules/lib_rules.ml
src/dune_rules/melange_rules.ml

We need to add the correct set of .cmi files to the check alias depending on which mode we're working with.

fix(melange): check rules

---

src/dune_rules/dir_contents.ml
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/generate_sites_module_rules.ml
src/dune_rules/generate_sites_module_rules.mli
src/dune_rules/generate_sites_module_stanza.ml
src/dune_rules/generate_sites_module_stanza.mli

This stanza is guarded behind an extension

refactor: move generate_sites_module to own module

---

src/dune_rules/cram_rules.ml
src/dune_rules/cram_stanza.ml
src/dune_rules/cram_stanza.mli
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli

From Dune_file.Cram to Cram_stanza.T

refactor: move cram stanza definition

---

src/dune_engine/scheduler.ml

[Shutdown.Reason.t] and [Shutdown_reason.t] are the same modulo
constructor names.
ps-id: d75c7609-cd02-4fe2-9c30-d08cd71ea60f

refactor(scheduler): remove duplicate types

---

src/dune_rules/check_rules.ml
src/dune_rules/check_rules.mli
src/dune_rules/exe_rules.ml
src/dune_rules/lib_mode.ml
src/dune_rules/lib_mode.mli
src/dune_rules/lib_rules.ml
src/dune_rules/merlin.ml

We select the merlin mode for melange/ocaml in one place and use it on
both merlin and check_rules

refactor(melange): share mode handling

---

src/dune_rpc_impl/server.ml
src/dune_rpc_server/dune_rpc_server.ml
src/dune_rpc_server/dune_rpc_server.mli

instead of taking this upgrade callback is a mutable argument, we treat
it as every callback and let it be provided in the [Handler].
@snowleopard if you're using this internally, let me know if there are issues porting. I expect this to be straightforward.

refactor(rpc): remove mutable callback

---

test/blackbox-tests/test-cases/melange/include_subdirs.t/run.t

test should include .js paths to show that they're currently wrong

test(melange): include_subdirs

---

src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli
test/expect-tests/scheduler_tests.ml

When the scheduler shuts down due to a timeout (during testing), we
clarify this in the error message.

refactor(rpc): distinguish Timeout from Shutdown

---

src/dune_rules/ctypes/ctypes_stanza.ml
test/blackbox-tests/test-cases/ctypes/function-description-collision.t

When several `(function_description)` fields are found with the same (functor, instance) pair, we used to crash with an error when setting up the rules.

Ctypes: detect duplicate function descriptions

---

CHANGES.md
bin/dune
bin/exec.ml
test/blackbox-tests/test-cases/exec-watch/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/dune-project
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/run.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/touch.ml
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/dune-project
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/foo.ml
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/run.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-no-passive.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/dune-project
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/run.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/touch.ml
test/blackbox-tests/test-cases/exec-watch/wait-for-file.sh

Fixes https://github.com/ocaml/dune/issues/2934

Eager watch mode for exec

---

CHANGES.md
src/dune_rules/preprocessing.ml
test/blackbox-tests/test-cases/github6644.t

Setting sandboxing by default would break staged_pps because it would
transitively make various compilation commands to be sandboxed as well
which is not supported.
We restore the old (no sandboxing) default to staged_pps
ps-id: 592a0185-83e3-4572-aac0-9fbc11d999f9

fix: staged_pps should work

---

CHANGES.md
src/dune_rules/command.mli
src/dune_rules/dune_rules.ml
src/dune_rules/exe.ml
src/dune_rules/jsoo/jsoo_rules.ml
src/dune_rules/jsoo/jsoo_rules.mli
src/dune_rules/link_time_code_gen.ml
src/dune_rules/link_time_code_gen.mli
src/dune_rules/link_time_code_gen_type.ml
src/dune_rules/link_time_code_gen_type.mli
test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
test/blackbox-tests/test-cases/jsoo/jsoo-config.t/run.t
test/blackbox-tests/test-cases/jsoo/no-check-prim.t/run.t
test/blackbox-tests/test-cases/jsoo/public-libs.t/run.t
test/expect-tests/jsoo_tests.ml

I'm currently working on https://github.com/ocsigen/js_of_ocaml/pull/1378 which make `js_of_ocaml link` only link required compilation units (similar to what ocamlc/ocamlopt do).
The goal is reduce the size of the generated js files and fix a semantic difference between whole program and separate compilation (Side effects in a library are always performed with separate compilation).
with https://github.com/ocsigen/js_of_ocaml/pull/1378, `js_of_ocaml link` accept a new flag `--linkall`. This PR tries to propagate that information where it's currently ignored.
The first commit is mostly a cleanup.
- it replaces `Action_builder.map/bind` with the `Action_builder.O` let syntax
- it extract the type `Link_time_code_gen.t` to its own module to avoid circular deps.
- make it clear where we …

Propagate linkall to js_of_ocaml for separate compilation

---

CHANGES.md
src/dune_rules/jsoo/jsoo_rules.ml

This should help to build jsoo toplevels using separate compilation.
See https://github.com/ocsigen/js_of_ocaml/pull/1380
Sadly, this multiply the number of jsoo targets by ~2.

Jsoo: recognize toplevel variant

---

CHANGES.md
src/dune_rules/context.ml
test/blackbox-tests/test-cases/custom-cross-compilation/github6843.t

It's possible for a context with targets to be a cross compilation
context for other contexts. Previously, we'd assume that wasn't the
case.
fixes #6843

fix(rules): cross compilation bug

---

bin/common.ml

We now enumerate all the values in --display in dune --help.
Fixes #526

fix: add display options in --help

---

CHANGES.md
src/dune_rules/mdx.ml

With @maiste and @art-w we had a long debugging session with mdx. I think it'd be nice to have #6416 (arbitrary flags for mdx) but in the meantime enabling colors in mdx and having more logs when Dune runs in verbose mode is, imo, a good start.

mdx: enable colors for debugging

---

CHANGES.md
src/dune_rules/artifacts.ml
src/dune_rules/artifacts.mli
src/dune_rules/artifacts_db.ml
src/dune_rules/main.ml
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli
test/blackbox-tests/test-cases/install-bin-glob.t
test/blackbox-tests/test-cases/install-bin-include.t

This fixes a memo dependency cycle between evaluating globs in install stanzas and populating the artifacts database. Populating the artifacts database involves enumerating all files installed in the "bin" section which involves expanding globs as these files can be specified as globs rather than literal files. Expanding globs in the install stanza requires loading the rules for the directory containing the glob, and doing so depends on the artifacts database.
Fixes #6708

Defer computation of local_bin

---

CHANGES.md
bin/common.ml
bin/subst.ml
src/dune_config/dune_config.ml
src/dune_config/dune_config.mli

When running with fancy terminals in watch mode, we pre-emptively clear
the screen. This is to prevent subsequent clears in watch mode making
the user's screen jump.
Fixes #6884

fix: pre-emptively clear screen

---

CHANGES.md
otherlibs/ocamlc_loc/src/lexer.mli
otherlibs/ocamlc_loc/src/lexer.mll
otherlibs/ocamlc_loc/src/ocamlc_loc.ml
otherlibs/ocamlc_loc/test/ocamlc_loc_tests.ml

[ocamlc_loc] would fail to parse exercepts that would contains dots in
them

fix(ocamlc_loc): extended excerpts

---

CHANGES.md
src/dune_rules/cinaps.ml
test/blackbox-tests/test-cases/cinaps/custom-alias.t

Allow setting the alias used to run cinaps actions.
This is done to override the behavior of attaching the cinaps action to
both the `cinaps` and `runtest` aliases.

feature(rules): custom alias for cinaps

---

src/dune_engine/build_system.ml
src/dune_engine/build_system.mli
src/dune_engine/compound_user_error.ml
src/dune_engine/compound_user_error.mli
src/dune_engine/dune_project.ml
src/dune_engine/process.ml
src/dune_engine/sub_dirs.ml
src/dune_rpc_impl/diagnostics.ml
src/dune_rules/foreign.ml
src/dune_rules/foreign_sources.ml
src/dune_rules/ml_sources.ml
src/dune_rules/scope.ml
test/expect-tests/dune_rpc_e2e/dune_rpc_diagnostics.ml

Some compilation commands emit more than one diagnostic. For example,
ocamlc can emit more than one deprecation or unused error warning.
The previous behavior would be to just take the first error and drop the
others. This PR fixes the behavior to include all errors extracted out
of a command.
cc @ddickstein

fix: include all diagnostics

---

CHANGES.md
src/dune_rules/ctypes/ctypes_field.ml
src/dune_rules/ctypes/ctypes_field.mli
src/dune_rules/ctypes/ctypes_rules.ml
src/dune_rules/ctypes/ctypes_rules.mli
src/dune_rules/exe_rules.ml
src/dune_rules/lib_rules.ml
test/blackbox-tests/test-cases/ctypes/directories.t

This creates version 0.3 of the ctypes field.
When used, commands are run in the directory where the corresponding stanza is defined. This makes it possible to use relative directories.
Fixes #5325

ctypes 0.3: run commands in stanza directory

---

src/dune_rules/ml_sources.ml
src/dune_rules/module.ml
src/dune_rules/module.mli
src/dune_rules/modules_field_evaluator.ml
src/dune_rules/modules_field_evaluator.mli
test/blackbox-tests/test-cases/gh5267.t

Do not use [Modules.t] to detect if a module is present in more than one
stanza.
This is a source based check so we should just use the sources directly

fix: module stanza mapping

---

CHANGES.md
bin/coq/coqtop.ml
src/dune_rules/coq/coq_rules.ml
src/dune_rules/coq/coq_rules.mli
test/blackbox-tests/test-cases/coq/base-unsound.t/run.t
test/blackbox-tests/test-cases/coq/base.t/run.t
test/blackbox-tests/test-cases/coq/compose-cycle.t/run.t
test/blackbox-tests/test-cases/coq/compose-installed.t/run.t
test/blackbox-tests/test-cases/coq/compose-plugin.t/run.t
test/blackbox-tests/test-cases/coq/compose-projects-cycle.t/run.t
test/blackbox-tests/test-cases/coq/compose-projects-missing.t/run.t
test/blackbox-tests/test-cases/coq/compose-self.t/run.t
test/blackbox-tests/test-cases/coq/coqdep-on-rebuild.t/run.t
test/blackbox-tests/test-cases/coq/coqdoc-multi-theory.t/run.t
test/blackbox-tests/test-cases/coq/coqdoc-with-boot.t/run.t
test/blackbox-tests/test-cases/coq/coqdoc.t/run.t
test/blackbox-tests/test-cases/coq/coqtop/coqtop-recomp.t
test/blackbox-tests/test-cases/coq/extract.t
test/blackbox-tests/test-cases/coq/ml-lib.t/run.t
test/blackbox-tests/test-cases/coq/native-compose.t/run.t
test/blackbox-tests/test-cases/coq/native-single.t/run.t
test/blackbox-tests/test-cases/coq/no-stdlib.t/run.t
test/blackbox-tests/test-cases/coq/plugin-meta.t/run.t
test/blackbox-tests/test-cases/coq/public-dep-on-private.t/run.t
test/blackbox-tests/test-cases/coq/rec-module.t/run.t

We now call coqdep once per theory. Each theory produces a `mytheory.theory.d` file which is then further interpreted into an internal dependency map.
This is joint work with @ejgallego.
TODO:
+ https://github.com/ejgallego/coq-universe/pull/32 
+ It appears in total ~5min of coqdep calls are saved.

feature(coq): call coqdep once per theory

---

CHANGES.md
boot/libs.ml
src/dune_file_watcher/dune
src/dune_file_watcher/dune_file_watcher.ml
src/fswatch_win/bin/dune
src/fswatch_win/bin/dune_fswatch_win.ml
src/fswatch_win/dune
src/fswatch_win/fswatch_win.ml
src/fswatch_win/fswatch_win.mli
src/fswatch_win/fswatch_win_stubs.c
test/unit-tests/fswatch_win/dune
test/unit-tests/fswatch_win/fswatch_win_tests.ml

This PR builds on #6087, simplifying the implementation, adding a small test driver, tests, some documentation, etc.
I recommend reading the comments in `fswatch_win.mli` to get a sense of the API and the comment at the top of `fswatch_win_stubs.c` to get a sense of the implementation.
I would appreciate a review of the changes to `dune_file_watcher.ml`. In particular I am not sure if the stuff involving `Fsevents.is_special_file_fsevents` and the `sync_table` is correct (I mostly copied this from `fsevents` and am not sure what role the `sync_table` plays).
There is a small test driver in `src/fswatch_win/bin/dune_fswatch_bin.exe`. Some tests were added to `test/unit-tests/fswatch_win`.

Add native polling mode support on Windows

---

bin/dune
bin/exec.ml
test/blackbox-tests/test-cases/exec-watch/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/dune-project
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/run.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-basic.t/touch.ml
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/dune-project
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/foo.ml
test/blackbox-tests/test-cases/exec-watch/exec-watch-ignore-sigterm.t/run.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-no-passive.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/dune
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/dune-project
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/run.t
test/blackbox-tests/test-cases/exec-watch/exec-watch-server.t/touch.ml
test/blackbox-tests/test-cases/exec-watch/wait-for-file.sh

This is the second attempt at adding this feature. The problem with the first attempt was that replacing the call to `Scheduler.go` with `Scheduler.go_with_rpc_server_and_console_status_reporting` caused occasional non-deterministic seg faults on macos. There's some info about the problem on the PR which reverts the previous attempt at adding this feature: https://github.com/ocaml/dune/pull/6867. At the time of writing we don't know the cause of this problem.
The difference this time around is that we maintain the call to `Scheduler.go` when running `dune exec` not in watch mode, and only invoke `Scheduler.go_with_rpc_server_and_console_status_reporting` when running in watch mode. There is some additional refactoring done to make this split more ergonomic. We may see seg faults on macos …

Add support for eager watch mode for `dune exec`

---

src/dune_rules/dep_graph.ml
test/blackbox-tests/test-cases/virtual-libraries/incorrect-archive-7027.t

Fix an incorrectly computed module closure for virtual libraries with
more than one module.

fix: multiple modules per virtual lib

---

src/dune_rules/melange/melange_rules.ml
test/blackbox-tests/test-cases/melange/emit-installed.t

Preserve .js paths of melange artifacts upto the source directory of the
library

fix(melange): installed libraries path

---

CHANGES.md
doc/stanzas/env.rst
src/dune_rules/compilation_context.ml
src/dune_rules/dune_env.ml
src/dune_rules/dune_env.mli
src/dune_rules/env_node.ml
src/dune_rules/env_node.mli
src/dune_rules/install_rules.ml
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli
test/blackbox-tests/test-cases/env/env-bin-annot.t/run.t

This PR proposes to add a new field `(bin_annot <bool>)` to the `(env)` stanza. When the `<bool>` is `false`, no `.cmt*` files are generated in the corresponding subtree (even for public libraries).
One use-case is in the CI, where the generation of these files takes up time and space but are not used at all. Some rough timings show a 5% speedup in our codebase.
What do you think?

(env): add (bin_annot <bool>) field to specify whether to generate `.cmt*` files

---

CHANGES.md
bin/common.ml
src/dune_console/dune_console.ml
src/dune_console/dune_console.mli
test/blackbox-tests/test-cases/error_messages_separated.t

This is an attempt to fix issue #6158
Remark: If a command (say, `ocamlopt`) returns several messages (such as warnings), a single line is put at the end, since this is considered as a single message.

Add a new line at the end of error reports (#6823

---

CHANGES.md
src/dune_rules/dune_file.ml
test/blackbox-tests/test-cases/melange/promote-with-lib.t

Allows writing `(modes :standard melange)` which will be useful when converting libraries in existing repositories.

feature: make `modes` field an Ordered_set_lang instance

---

CHANGES.md
bench/bench.ml
bench/micro/dune_bench/scheduler_bench.ml
src/dune_engine/print_diff.ml
src/dune_engine/vcs.ml
src/dune_rules/artifact_substitution.ml
src/dune_rules/context.ml
src/dune_rules/coq/coq_config.ml
src/dune_rules/cram/cram_exec.ml
src/dune_rules/dune_load.ml
src/dune_rules/jsoo/jsoo_rules.ml
src/dune_rules/melange/melange_binary.ml
test/blackbox-tests/test-cases/cram/git-diff-fail.t
test/expect-tests/process_tests.ml
test/expect-tests/vcs_tests.ml

We change the display of various `Process.run` calls in Dune to be `Quiet` and non-overridable.
This fixes issues such as those observed in #4066.

feature: Silence display in non-user processes

---

CHANGES.md
src/dune_rules/dune_package.ml
test/blackbox-tests/test-cases/install-stublibs.t/run.t

Currently, libraries installed by Dune (ie carrying a `dune-package` file) do not record the information about the library's stublibs (`dllXXX_stubs.$ext_dll`), which make it impossible to depend on these libraries to build bytecode or JS executables in the workspace.
This PR fills records the necessary information in a new field `foreign_dll_files` of the `dune-package` file (using a path relative to the package root to maintain relocatibility).

Enable use of stublibs of _installed_ libraries

---

CHANGES.md
src/dune_rules/compilation_context.ml
src/dune_rules/modules.ml
test/blackbox-tests/test-cases/stdlib-compilation-depend-on-library.t

- the stdlib alias module is different from dune's because it contains code
- this change allows that code to depend on modules in `(libraries ..)`
- this allows the melange stdlib (which depends on another, bootstrapping lib) to be compiled using `(stdlib ...)`
- fix decoding  stdlib in dune-package, which expected an extra sexp

stdlib: include dependencies for stdlib alias, decode correctly

---

CHANGES.md
src/dune_rules/preprocessing.ml
test/blackbox-tests/test-cases/preprocessor-directory.t/run.t

Running the preprocessor from cwd breaks the error messages outputted by
the preprocessor.

fix: Revert "fix: Invoke preprocessor commands from local dir"

---

CHANGES.md
src/dune_threaded_console/dune_threaded_console.ml
src/dune_threaded_console/dune_threaded_console_intf.ml

Previously, dune would re-render on every frame even when it wasn't
necessary.
Now, dune will make sure we have at least one modification before
re-rendering

fix: do not re-render unless needed

---

CHANGES.md
otherlibs/stdune/src/ansi_color.ml
otherlibs/stdune/src/ansi_color.mli
otherlibs/stdune/src/int.ml
otherlibs/stdune/src/int.mli
otherlibs/stdune/test/ansi_color_tests.ml
src/dune_tui/dune_tui.ml

We add support for 8 and 24 bit color codes.
- fixes #7181

feature(ansi_color): add support for 8 and 24 bit color codes

---

dev/bench/data.js

Just a small cosmetic change **against `gh-pages` branch**, where the Melange and synthetic benchmarks data is stored.
The reason is that in #7198 we changed the labels of the cold runs, so now there is data for this runs with these two labels:
- `synthetic build time (Linux)` (before #7198)
- `synthetic build time (cold, Linux)` (after #7198)
Which leads to 2 tables being shown for cold runs, but the data is for the same benchmark.
This PR updates the old data so that the labels coincide with the newest ones and they get rendered in the same table.

bench: update gh pages data to consolidate cold builds

---

bench/micro/copyfile.ml
bench/micro/dune
otherlibs/stdune/src/copyfile_stubs.c
otherlibs/stdune/src/dune
otherlibs/stdune/src/io.ml

Use mac's [clonefile] instead of manually copying. [clonefile] is like
hardlink but it will copy-on-write when edited.
The attached benchmark before the optimization:
```
real    0m3.593s
user    0m0.249s
sys     0m2.849s
```
And after:
```
real    0m2.044s
user    0m0.083s
sys     0m1.954s
```
So about a 45% reduction. Not bad. The benchmark also includes how long it took to delete the temp directory at the end (Around 10k additional unlinks), so 45% is likely pessimistic.

feature: use clonefile on macos

---

CHANGES.md
doc/sites.rst
otherlibs/site/src/plugins/dune
otherlibs/site/src/plugins/linker/dune
otherlibs/site/src/plugins/linker/dynlink/dune
otherlibs/site/src/plugins/linker/dynlink/linker.ml
otherlibs/site/src/plugins/linker/linker.mli
otherlibs/site/src/plugins/linker/toplevel/dune
otherlibs/site/src/plugins/linker/toplevel/linker.ml
otherlibs/site/src/plugins/plugins.ml
test/blackbox-tests/test-cases/sites-plugin.t
test/blackbox-tests/test-cases/toplevel-plugin-fail.t
test/blackbox-tests/test-cases/toplevel-plugin-fail2.t
test/blackbox-tests/test-cases/toplevel-plugin.t

To load a file in toplevel we should use `Topdirs.dir_load` (or `Toploop.load_file`) instead of `Dynlink` as the latter is not allowed in the toplevel environment. The problem, however, is that `Topdirs` is only available in the bytecode mode so we can't just do `if !Sys.interactive then ...`. The trick that we are using in the BAP plugin systems is to have a hidden reference to the `load` function that is overridden with `Topdirs`'s one when we are loading from a toplevel.
The proposed solution is different and relies on virtual libraries with the default library using `Dynlink` as the loader. To be able to use plugins from the toplevel, we need to add `dune-site.toplevel` to the `libraries` stanza.
Do you think this is user-friendly enough? Ideally, I would like to have magic, so that …

adds support for loading plugins in toplevels

---

CHANGES.md
boot/duneboot.ml

We were passing an empty enviornment to Unix.open_process_full_cmd before. We now pass the full available Unix.environment since we are only querying the concurrency by calling nproc or getconf.
On NixOS this was causing the bootstrap to default to a single processor since nproc wasn't available in the empty environment.

fix(boot): fix env vars when finding out concurrency

---

CHANGES.md
boot/duneboot.ml

Previously, we'd run the shell to discover the number of processes by
using `Unix.open_process_full`. The shell isn't being used for anything,
so we switch to executing the process directly.

feature(boot): remove reliance on shell

---

CHANGES.md
src/csexp_rpc/csexp_rpc.ml
src/csexp_rpc/pthread_chdir_stubs.c

RPC clients that suddenly disconnect will no longer raise sigpipe and
make dune terminate.

fix(rpc): ignore sigpipe on macos clients

---

CHANGES.md
src/dune_rules/compilation_context.ml
test/blackbox-tests/test-cases/stdlib/stdlib-flags.t

Reported by @gretay-js.
This ensures that when building `stdlib.ml` (the main module of a library with `(stdlib)`), flags set in the corresponding stanza `(library)` are correctly passed.

fix(stdlib): pass flags when building stdlib.ml

---

CHANGES.md
src/csexp_rpc/csexp_rpc.ml
src/csexp_rpc/csexp_rpc.mli
src/csexp_rpc/csexp_rpc_stubs.c
src/csexp_rpc/dune
src/csexp_rpc/io_buffer.ml
src/csexp_rpc/io_buffer.mli
test/expect-tests/csexp_rpc/io_buffer_tests.ml

We ignore sigpipe by sending messages with `sendmsg` with the appropriate flag.
All of this requires us to get rid of the `Out_channel`, but this desirable anyway, since we'll need it gone for evented IO.

fix(rpc): ignore sigpipe on linux

---

CHANGES.md
src/fsevents/fsevents_stubs.c

Fixes https://github.com/ocaml/dune/issues/6151
This just a copy of https://github.com/ocaml/dune/pull/6215 rebased onto main. I've tested this on both an M1 and x86 mac and it fixes the problem.

fsevents: move free to finalizer

---

CHANGES.md
bench/bench.ml
bench/micro/dune_bench/scheduler_bench.ml
bin/common.ml
bin/common.mli
bin/import.ml
bin/subst.ml
src/dune_config_file/dune_config_file.ml
src/dune_config_file/dune_config_file.mli
src/dune_engine/scheduler.ml
src/dune_engine/scheduler.mli
src/dune_file_watcher/dune_file_watcher.ml
src/dune_file_watcher/dune_file_watcher.mli
test/blackbox-tests/test-cases/watching/what-dune-watches.t
test/expect-tests/csexp_rpc/csexp_rpc_tests.ml
test/expect-tests/dune_action_runner/dune_action_runner.ml
test/expect-tests/dune_file_watcher/dune
test/expect-tests/dune_file_watcher/dune_file_watcher_tests_linux.ml
test/expect-tests/dune_file_watcher/dune_file_watcher_tests_macos.ml
test/expect-tests/dune_file_watcher/dune_file_watcher_tests_patterns.ml
test/expect-tests/dune_rpc_e2e/dune_rpc_e2e.ml
test/expect-tests/dune_rpc_e2e/dune_rpc_registry_test.ml
test/expect-tests/process_tests.ml
test/expect-tests/scheduler_tests.ml
test/expect-tests/timer_tests.ml
test/expect-tests/vcs_tests.ml

This PR allows the command line option `--exclude-from-watch` to exclude directories from dune build --watch. ~~It should exclude more directories if those are listed in dune-workspace: (context (default (watch_exclusions node_modules doc)))~~
~~However I got lost in the Dune code base and can't figure out a way to get the Dune workspace information into the Dune file watcher. Need help with that!~~
(This is a continuation of https://github.com/ocaml/dune/pull/7086 by @nojb that was reviewed by @rgrinberg )

User-configured watch exclusions

---

CHANGES.md
src/dune_config/config.ml
src/dune_config/config.mli
src/dune_engine/build_system.ml
src/dune_engine/dune

Make it possible to enable it with the "speculative_cutoff" internal
config option

fix: disable cutoff where it hurts concurrency

---

CHANGES.md
src/dune_rules/compilation_context.ml
test/blackbox-tests/test-cases/stdlib-flags.t

Reported by @gretay-js.
This ensures that when building `stdlib.ml` (the main module of a
library with `(stdlib)`), flags set in the corresponding stanza
`(library)` are correctly passed.

[3.7] Backport #7241 (pass flags when building stdlib.ml)

---

src/dune_rules/dune_project.ml
src/dune_rules/dune_project.mli
src/dune_rules/gen_rules.ml
src/dune_rules/install_rules.ml
src/dune_rules/opam_create.ml
src/dune_rules/opam_create.mli
src/dune_rules/package.ml
src/dune_rules/package.mli
test/blackbox-tests/test-cases/opam-directory/generate-opam-file.t

When we set (opam_file_location inside_opam_directory), we are allowed
to put all the opam file in the opam/ directory relative to the project.

feature: allow opam files in opam/

---

CHANGES.md
src/dune_rules/lib.ml
test/blackbox-tests/test-cases/custom-cross-compilation/ppx-cross.t
test/blackbox-tests/test-cases/custom-cross-compilation/ppx-runtime-libraries.t
test/blackbox-tests/test-cases/ppx-runtime-dependencies.t/run.t

- There's a lingering issue after #7415 where a library's runtime dependencies get resolved at the time of its instantiation
- In a cross-compilation scenario, we only know the context when we're resolving the library that depends on the ppx with runtime_deps, so they can't be resolved eagerly when the ppx library is being instantiated.
- This patch proposes deferring their evaluation until they're needed by the rules post-preprocessing.

test(x-compilation): demonstrate overlap check failure with ppx_runtime_libraries

---

src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/install_rules.ml
test/blackbox-tests/test-cases/foreign-stubs/installed-headers.t

Use exact locations for [installed_c_headers] entry rules

fix: improve locations for [installed_c_headers]

---

src/dune_rules/dune_file.ml
test/blackbox-tests/test-cases/package-rule.t/run.t

Closes #7471, as discussed in #7461 to only allow the #7445 feature on dune-lang 3.8.
This fixes the issue that #7445 by itself fixes a language quirk that is only fixed in 3.8, but without actually requiring dune-lang 3.8. It revises the previous test that uses an older dune-lang to fail.

Only enable `package` in short-form rules on dune lang 3.8+

---

CHANGES.md
src/dune_rules/dune_project.ml
src/dune_rules/install_rules.ml
src/dune_rules/package.ml
src/dune_rules/package.mli
test/blackbox-tests/test-cases/dune-project-meta/fresh-build.t
test/blackbox-tests/test-cases/toplevel-plugin/toplevel-plugin-fail.t
test/blackbox-tests/test-cases/toplevel-plugin/toplevel-plugin-fail2.t
test/blackbox-tests/test-cases/toplevel-plugin/toplevel-plugin.t

Previously, the contents of the .install file would depend on whether
the .opam install file would be present in the source.
This check is wrong whenever we generate the .opam file ourselves. This
commit checks if we are generating the .opam file.

fix: correctly generate .install files

---

CHANGES.md
src/dune_rules/link_time_code_gen.ml
test/blackbox-tests/test-cases/builtin-support-override.t

- demonstrates a crash in link-time codegen when there's a library called `findlib.dynload`
- this is extracted from a real case (`caqti-dynload`) when consumed within an opam monorepo, which uses https://github.com/dune-universe/lib-findlib

test: demonstrate crash in link-time codegen

---

CHANGES.md
src/dune_engine/build_system.ml
src/dune_engine/targets.ml
src/dune_engine/targets.mli

For unsandboxed rules, directory targets weren't being cleared when
running rules were interrupted. This PR treats files and directories in
the same way.

fix: delete stale directory targets

---

otherlibs/stdune/src/io.ml

A regression in #7257 meant that the "portable" file copying routine was using text mode channels, corrupting binary files when copying them (under Windows). This explains the current Windows failures in the CI.
cc @rgrinberg

copy_file_portable: use binary mode to avoid corruption

---

CHANGES.md
bin/ocaml/ocaml_merlin.ml
otherlibs/stdune/src/string.ml
otherlibs/stdune/src/string.mli
test/blackbox-tests/test-cases/merlin/github7577.t/run.t

Recently we upgraded from Dune 3.5 to 3.7 at LexiFi and noticed a bug under Windows that causes the Merlin configuration for files that contain uppercase letters not to be found.
The issue seems to be that under Windows, we lowercase the full file path in order to match the workspace root in a case-insensitive fashion. However, as a side effect, we "lose" the uppercase characters in the basename itself.
As a solution, this PR proposes to only do the prefix matching in case-insensitive mode, but not to touch the actual filename.
cc @voodoos @rgrinberg

merlin: avoid touching case of filename

---

CHANGES.md
doc/stanzas/mdx.rst
src/dune_rules/mdx.ml
test/blackbox-tests/test-cases/mdx-stanza/mld-files.t

MDX 2.3.0 added support for MLD files, the mdx 0.4 stanza adds `*.mld` to the default globs.
Probably it would make sense to add a version check for this and it would be good to land #7569 beforehand.

feature: mdx 0.4 stanza with support for `mld` files out of the box

---

src/dune_rules/cinaps.ml

We forgot to record the source files as part of the action which was causing them to not be added to the sandbox. This fix adds them and the example in the original report becomes resolved. I was unable to reproduce this issue in a cram test so it was tested manually.
fix #7376

fix: files recorded by sandboxed cinaps action in action builder

---

CHANGES.md
src/dune_rules/context.ml

fix: allow overriding "ocaml" with findlib

---

doc/coq.rst

doc(coq): Add documentation for composition with installed theories

---

CHANGES.md
doc/stanzas/executable.rst
src/dune_rules/dune_file.ml
test/blackbox-tests/test-cases/public-name-empty.t

Fixes #5852
This brings consistency with `(public_names)` in `(executables)`: a plural stanza with only `-` in `(public_names)` installs nothing.

Make (public_name -) equivalent to no public name

---

CHANGES.md
otherlibs/dune-rpc/private/where.ml

`0.0.0.0` is a dummy address that is interpreted in different ways by the various APIs. We should use the `loopback` (= `127.0.0.1`) address which always denotes the local host.
This is needed to use the RPC protocol on Windows.

dune-rpc: use loopback address on Windows

---

CHANGES.md
src/dune_rules/odoc.ml
test/blackbox-tests/test-cases/odoc/multiple-private-libs.t/run.t
test/blackbox-tests/test-cases/odoc/odoc-simple.t/run.t
test/blackbox-tests/test-cases/odoc/odoc-unique-mlds/diff-scope.t/run.t
test/blackbox-tests/test-cases/odoc/odoc-unique-mlds/same-scope.t/run.t

Fixes #7364
If the directory is named `_odoc_support` with a leading underscore, it is omitted when deploying to github pages. This is because this system also support the jekyll site generator, which uses this convention for data files.
We can not use any directory name here since we want to avoid conflicts with OCaml identifiers and names of `*.mld` files. Starting with a dot seems to fit the requirements.

odoc: put odoc support files in odoc.support

---

CHANGES.md
doc/coq.rst
src/dune_rules/coq/coq_rules.ml
src/dune_rules/coq/coq_stanza.ml
src/dune_rules/coq/coq_stanza.mli

This allows users to further configure the flags sent to coqdoc. It is an ordered set lang with :standard being just `--toc` as is currently passed today.
Fix #7594

feature(coq): add coqdoc_flags field to coq.theory

---

doc/dune-files.rst

Change the documentation for `(map_workspace_root)` so that it matches the existing situation.
See #7743 which had been incorrectly merged.

doc: correct doc for (map_workspace_root)

---

src/dune_rules/coq/coq_rules.ml
src/dune_rules/scope.ml
src/dune_rules/scope.mli
test/blackbox-tests/test-cases/coq/compose-installed-compat.t/run.t
test/blackbox-tests/test-cases/coq/compose-installed-rebuild.t/run.t
test/blackbox-tests/test-cases/coq/compose-installed-sub.t/global/algebra/dune
test/blackbox-tests/test-cases/coq/compose-installed-sub.t/global/dune
test/blackbox-tests/test-cases/coq/compose-installed-sub.t/global/field/dune
test/blackbox-tests/test-cases/coq/compose-installed-sub.t/run.t
test/blackbox-tests/test-cases/coq/compose-installed-sub.t/user/dune
test/blackbox-tests/test-cases/coq/compose-installed.t/run.t
test/blackbox-tests/test-cases/coq/compose-plugin.t/run.t
test/blackbox-tests/test-cases/coq/compose-projects-boot.t/run.t
test/blackbox-tests/test-cases/coq/lazy-lib.t
test/blackbox-tests/test-cases/coq/ml-lib.t/run.t
test/blackbox-tests/test-cases/coq/rec-module.t/run.t

We make the loading of theories even lazier in scope.ml. This required refactoring the coq db into a Memo.Lazy.t. I'm open to a better way of doing this but this at least fixes the bug observed in #7747 and #7748.
I added a test case for #7747 and showed that this patch fixes it also.
This PR fixes the following issues, however they will be closed on a new run of the opam ci:
- #7747 
- #7748

fix(coq): make loading of theories in scope lazier 

---

CHANGES.md
src/dune_stats/dune_stats.ml

We want to include more things in the trace file and we should always produce valid JSON here.

Improve JSON string quoting in Dune tracing

---

CHANGES.md
bin/common.ml
otherlibs/chrome-trace/test/chrome_trace_tests.ml
src/dune_engine/process.ml
src/dune_stats/dune_stats.ml
src/dune_stats/dune_stats.mli

This allows Dune to generate trace files which contain the same information as .jenga/debug files about processes that Dune runs. This can be quite a bit of information (including stdout and stderr) so this is controlled by the `--trace-extended` flag.

Trace more data

---

CHANGES.md
doc/coq.rst
src/dune_rules/coq/coq_config.ml
src/dune_rules/coq/coq_config.mli
src/dune_rules/coq/coq_path.ml

Coq versions < 8.13 do not have COQ_NATIVE_COMPILER_DEFAULT and were causing dune to crash when searching for this var. We make it so that if dune does not find it, it defaults to "no". The docs should also be updated accordingly.
fix #7846

fix(coq): fix crash when COQ_NATIVE_COMPILER_DEFAULT missing 

---

CHANGES.md
doc/coq.rst
src/dune_rules/coq/coq_config.ml
src/dune_rules/coq/coq_config.mli
src/dune_rules/coq/coq_path.ml

- fix(coq): better config var not found message
- fix(coq): fix crash when COQ_NATIVE_COMPILER_DEFAULT missing
- doc(coq): update documentation about native compilation wrt old coq ver
- coq: encapsulate value type in coq_config

[3.8] backport #7847

---

CHANGES.md
src/dune_rules/coq/coq_lib.ml
test/blackbox-tests/test-cases/coq/compose-installed-prefix-dupe.t/B/a.v
test/blackbox-tests/test-cases/coq/compose-installed-prefix-dupe.t/B/dune
test/blackbox-tests/test-cases/coq/compose-installed-prefix-dupe.t/B/dune-project
test/blackbox-tests/test-cases/coq/compose-installed-prefix-dupe.t/C/a.v
test/blackbox-tests/test-cases/coq/compose-installed-prefix-dupe.t/C/dune
test/blackbox-tests/test-cases/coq/compose-installed-prefix-dupe.t/C/dune-project
test/blackbox-tests/test-cases/coq/compose-installed-prefix-dupe.t/run.t
test/blackbox-tests/test-cases/coq/compose-installed-sub.t/run.t
test/blackbox-tests/test-cases/coq/compose-installed.t/run.t

- test(coq): duplicate theory prefix in COQPATH bug
- fix(coq): first theory in COQPATH takes precedence always
- coq: add missing changelog entry

[3.8] backport #7790 and #7862

---

CHANGES.md
src/dune_rules/cinaps.ml
test/blackbox-tests/test-cases/cinaps/concurrent-promotions.t

Instead of failing on the first promotion, offer all of them.

fix(cinaps): offer all promotions

---

CHANGES.md
src/dune_rules/melange/melange_rules.ml
src/dune_rules/resolve.ml
src/dune_rules/resolve.mli
test/blackbox-tests/test-cases/melange/melange-emit-package.t

- test(melange): demonstrate melange.emit doesn't respect `-p`
- fix(melange): resolve libraries lazily for melange.emit
- chore: add changelog entry for #7849 (#7925)

[3.8] backport #7849, #7925

---

CHANGES.md
src/dune_rules/melange/melange_rules.ml
test/blackbox-tests/test-cases/melange/aliases.t
test/blackbox-tests/test-cases/melange/dune-rules.t

It is confusing that `dune build` does not build targets specified by a `melange.emit` stanza by default.
This PR intends to address this by adding `melange.emit` targets to `@all` alias as well as (the current default) `@melange` alias by default.
This stems from the discussion of https://github.com/ocaml/dune/pull/7924.
more specifically, this PR implements the suggestion in https://github.com/ocaml/dune/pull/7924#issuecomment-1583215590
- related: https://github.com/ocaml/dune/pull/7924
- implementing (1) in https://github.com/ocaml/dune/pull/7924#issuecomment-1583215590
- ~[ ] fix existing test cases if necessary~ (update: does not seem to break any existing test)

melange - add `melange.emit` targets to `@all` alias as well by default

---

CHANGES.md
otherlibs/stdune/src/loc.ml
otherlibs/stdune/test/loc_tests.ml

The previous code would pretend that a multi-line excerpt was
single-line whenever the stop character was outside the line.
Fixes #7905

fix: correctly print multi-line excerpts

---

CHANGES.md
otherlibs/stdune/src/loc.ml
otherlibs/stdune/test/loc_tests.ml

- test: reproduce #7905 (#7949)
- fix: correctly print multi-line excerpts (#7950)

[3.8] backport #7949 and #7950

---

CHANGES.md
bin/describe/describe.ml
bin/describe/describe.mli
bin/main.ml

We ad a command group `dune show` which is an alias of `dune describe`. Motivation is that it is more convenient and easier to remember.

create dune show command group

---

CHANGES.md
bin/common.ml
boot/libs.ml
src/dune_stats/dune_stats.ml
src/dune_util/dune
src/dune_util/persistent.ml
test/blackbox-tests/test-cases/trace-file.t/run.t

Loading/Marshalling can be slow if the files being loaded are huge. We
record the overhead when --trace-file is enabled.

feature: trace loading/marshalling files

---

CHANGES.md
doc/stanzas/test.rst
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/enabled_if.ml
src/dune_rules/enabled_if.mli
src/dune_rules/gen_rules.ml
test/blackbox-tests/test-cases/test-build-if/feature.t
test/blackbox-tests/test-cases/test-build-if/package.t
test/blackbox-tests/test-cases/test-build-if/version.t

Fixes #6938
The semantics of `(enabled_if)` in `(test)` can be confusing: `(test)` can be seen as the combination of `(executable)` and a `(rule (alias runtest))`; but `(enabled_if)` actually only controls the "running" part, not the "building" one.
This adds a new `(build_if)` field in `(test)`. When it evaluates to false, the test stanza is bypassed (no build is attempted).

add: build_if in test stanza

---

CHANGES.md
src/dune_rules/package.ml
test/blackbox-tests/test-cases/opam-constraints.t

`add_group` appends parenthesis to the result of `opam_constraint` in order to handle precedence of `opamBaseParser.mly` in `opam-file-format` (https://github.com/ocaml/opam-file-format).
Fixes [#3431](https://github.com/ocaml/dune/issues/3431)

`opam_constraint t` result should respect precedence

---

src/dune_rules/melange/melange_rules.ml
src/dune_rules/resolve.ml
src/dune_rules/resolve.mli
src/dune_util/report_error.mli
test/blackbox-tests/test-cases/melange/transitive-ppx.t

- This is a regression introduced in #7849

test(melange): show crash when `melange.emit` depends on transitive PPX

---

CHANGES.md
otherlibs/stdune/src/io.ml
test/blackbox-tests/test-cases/github8041.t

Fixes #8041.
When using `sendfile` to copy files on Linux, fall back to the portable version if it fails at runtime for some reason (NFS, etc).

fix: sendfile: fall back to portable copy

---

CHANGES.md
bin/describe/describe.ml

Not sure if we want to mention `dune show rules` in help for `dune rules`.

show: print_rules now part of show command

---

CHANGES.md
src/dune_rules/preprocessing.ml
test/blackbox-tests/test-cases/dune
test/blackbox-tests/test-cases/reason-expect.t/run.t
test/blackbox-tests/test-cases/reason.t/refmt/dune
test/blackbox-tests/test-cases/reason.t/run.t
test/blackbox-tests/utils/dune
test/blackbox-tests/utils/refmt.ml

Fix #7930
ppx needs the original source of a file even if it is a dialect. This was missing causing the sandboxed version to error. We add the original source file as a hidden dependency in the ppx action.
I also found that inline_tests was not using the correct dialect source, which can be seen in my commits as I tried to remove my original reason dependency. I therefore have also submitted a fix for that.

fix: ppx and reason bug

---

CHANGES.md
bin/describe/describe_external_lib_deps.ml
test/blackbox-tests/test-cases/external-lib-deps/exclude-internal-deps.t/run.t
test/blackbox-tests/test-cases/external-lib-deps/simple-pps.t/run.t
test/blackbox-tests/test-cases/external-lib-deps/simple.t/run.t

Instead of having only external dependencies, we could also add the internal dependencies for more information.
This is related to https://github.com/ocurrent/opam-dune-lint/pull/46.

Improve "dune describe external-lib-deps" : printing out more information 

---

CHANGES.md
src/dune_rules/gen_meta.ml
test/blackbox-tests/test-cases/meta-gen.t/run.t

Using `jsoo_runtime` (instead of `linkopts(javascript`) to retrieve jsoo runtime files has been advertised in the documentation since jsoo 4.1.0 (see https://ocsigen.org/js_of_ocaml/4.1.0/manual/runtime-files).
How to proceed with such cleanup wrt backward compatibility ?

remove linkopts(javascript) from META

---

doc/changes/8023.md
src/dune_rules/enabled_if.ml
test/blackbox-tests/test-cases/enabled_if/eif-arch_sixtyfour.t/dune
test/blackbox-tests/test-cases/enabled_if/eif-arch_sixtyfour.t/hello.ml
test/blackbox-tests/test-cases/enabled_if/eif-arch_sixtyfour.t/run.t
test/blackbox-tests/test-cases/enabled_if/eif-exec-forbidden_var.t/run.t
test/blackbox-tests/test-cases/enabled_if/eif-install-forbidden_var.t/run.t

We allow the `arch_sixtyfour` variable in `enabled_if`.
- fix #7997

feature: allow arch_sixtyfour in enabled_if

---

CHANGES.md
doc/changes/7674.md
src/dune_rules/melange/melange_stanzas.ml
src/dune_rules/melange/melange_stanzas.mli
src/dune_rules/ml_sources.ml
src/dune_rules/modules_field_evaluator.ml
src/dune_rules/modules_field_evaluator.mli
test/blackbox-tests/test-cases/intf-only/excluded-by-modules-field.t
test/blackbox-tests/test-cases/private-modules/private-module-excluded-by-modules-field.t
test/blackbox-tests/test-cases/virtual-libraries/virtual-modules-excluded-by-modules-field.t

Carrying on from #7608, we make the undeclared modules check an error.

chore: make undeclared modules check an error

---

doc/changes/8090.md
src/dune_config/config.ml
vendor/spawn/src/spawn_stubs.c
vendor/update-spawn.sh

feature: use posix_spawn on macos

---

bin/install_uninstall.ml
doc/changes/8361.md
src/dune_rules/artifact_substitution.ml
src/dune_rules/artifact_substitution.mli

- It looks like macOS's `codesign` tool is a lot more lenient than Nix's `sigtool`, and skips signing files altogether if they're not binaries.
- This PR fixes the Nix part by only signing binaries and not regular files (e.g. sites modules produced by `dune-site`)
fixes https://github.com/ocaml/dune/issues/8360

fix: only sign executables

---

doc/changes/8349.md
doc/stanzas/install.rst
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/install_entry_with_site.mli
src/dune_rules/install_rules.ml
src/install/entry.ml
src/install/entry.mli
test/blackbox-tests/test-cases/install/install-source-tree.t

This PR allows us to install source trees with the following field in the install stanza:
```
(install
(section doc)
(source_tree dir))
```

feature: allow installing source trees

---

bin/dune
bin/main.ml
bin/monitor.ml
bin/monitor.mli
boot/libs.ml
doc/changes/8152.md
doc/dune.inc
src/fiber_event_bus/dune
src/fiber_event_bus/fiber_event_bus.ml
src/fiber_event_bus/fiber_event_bus.mli
test/expect-tests/fiber_event_bus/dune
test/expect-tests/fiber_event_bus/fiber_event_bus_tests.ml

This PR adds the `dune monitor` command which allows the user to connect to an already running `dune build` in watch mode and view the build progress and status. It does so by connecting to a running RPC server in a workspace and listening for progress changes.
- fixes https://github.com/ocaml/dune/issues/7308
This work is still experimental and may be subject to further changes.
In the future, all `dune build` commands may have behaviour similar to `dune monitor` allowing for multiple builds in the same workspace, all sharing the same build server. We also hope to further improve the TUI allowing for a seamless experience for users.

feature: dune monitor

---

doc/changes/8350.md
doc/stanzas/install.rst
src/dune_rules/dune_file.ml
src/dune_rules/file_binding.ml
src/dune_rules/file_binding.mli
src/dune_rules/gen_rules.ml
src/dune_rules/install_entry.ml
src/dune_rules/install_entry.mli
src/dune_rules/install_rules.ml
test/blackbox-tests/test-cases/install/install-glob/install-glob-relative.t
test/blackbox-tests/test-cases/install/install-source-tree.t
test/blackbox-tests/test-cases/start-install-dst-with-parent-error.t

This disallows install dst paths from begining with ".." to prevent them referencing a directory outside the install directories of the package.
This new constraint would prevent globs from being able to refer to files outside the current directory and its descendants, so this also adds a new keyword which changes the prefix of paths matched by a glob in the install stanza. It's similar to the `(files (foo as bar))` syntax in that it allows installed files to be placed in a location other than the one implied by their position in the source tree. It's now possible to write:
`(files (glob_files (some/path/* with_prefix new/path)))` ...which takes all the paths matched by the glob and replaces the `some/path` component with `new/path`.
I haven't yet updated the docs or changelog or written …

fix: Prevent relative install destinations leaking outside package install dir

---

doc/changes/8518.md
otherlibs/dune-site/test/run.t
otherlibs/dune-site/test/run_2_9.t
src/dune_rules/dune_file.ml
src/dune_rules/rule_mode_decoder.ml
src/dune_rules/rule_mode_decoder.mli
src/dune_rules/simple_rules.ml
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli
test/blackbox-tests/test-cases/ignore-promoted-internal-rules.t

Internal promotion rules such as generating opam files weren't being
ignored under --ignored-promoted-rules.

fix: --ignore-promoted-rules should work on internal rules

---

doc/changes/8448.md
doc/dune-files.rst
otherlibs/stdune/src/user_warning.ml
otherlibs/stdune/src/user_warning.mli
src/dune_rules/dune_file.ml
src/dune_rules/dune_project.ml
src/dune_rules/dune_project.mli
src/dune_rules/file_binding.ml
src/dune_rules/file_binding.mli
src/dune_rules/gen_rules.ml
src/dune_rules/install_entry.ml
src/dune_rules/warning.ml
src/dune_rules/warning.mli
src/dune_rules/warning_emit.ml
src/dune_rules/warning_emit.mli
test/blackbox-tests/test-cases/disable-warning.t
test/blackbox-tests/test-cases/install/install-glob/install-glob-relative.t
test/blackbox-tests/test-cases/start-install-dst-with-parent-error.t
test/blackbox-tests/test-cases/syntax-versioning.t

Add a [Warning] module to handle warnings in a consistent way in dune.
We'd like dune warnings to have the following two properties:
* Muted while in the vendored directory
* Possible to disable
This PR adds a warning mechanism that makes it easy to handle these two concerns.
I've converted a couple of trivial warnings we currently have to this mechanism. More can be done, but this is a start.

refactor: warning system

---

doc/changes/8887.md
doc/tests.rst
src/dune_rules/cram/cram_rules.ml
src/dune_rules/cram/cram_stanza.ml
src/dune_rules/cram/cram_stanza.mli
test/blackbox-tests/test-cases/cram/runtest_alias.t

Introduce a [(default_aliases ..)] that allows to set the default alias
for a cram test.
Unlike, the existing [alias] field, we're only allowed to set the
default once. If the default isn't set, it's just [runtest].

feature(cram): allow overriding default alias

---

doc/changes/8920.md
src/dune_engine/sandbox.ml
test/blackbox-tests/test-cases/directory-targets/copy-sandboxing.t
test/blackbox-tests/test-cases/sandboxing-stale-directory-target.t

Currently, the `copy` sandbox just uses whatever permissions are set in the workspace local cache.
With this PR, it will now make all files and directories writeable.

fix: make copying sandbox files writeable

---

doc/changes/8949.md
src/dune_rules/gen_rules.ml
src/dune_rules/ml_sources.ml
src/dune_rules/ml_sources.mli
src/dune_rules/top_module.ml
test/blackbox-tests/test-cases/menhir/menhir-include-subdirs.t/run.t

menhir stanzas wouldn't know how to attach themselves to executables or
libraries with (include_subdirs qualified) because the module path
wouldn't be computed. Now we compute the module path and it works.

fix(menhir): include_subdirs qualified

---

doc/changes/8990.md
src/dune_engine/build_system.ml
test/blackbox-tests/test-cases/depend-on/expand-aliases-rerun.t
test/blackbox-tests/test-cases/dune-cache/mode-copy.t
test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t
test/blackbox-tests/test-cases/dune-cache/repro-check.t
test/blackbox-tests/test-cases/dune-cache/trim.t

Action digests should depend on whether the aliases have been expanded in the sandbox.
Technically, this value should only matter if the action is sandboxed and there are alias dependencies, but it's likely not worth the effort to make the digest this precise.
cc @jchavarri who discovered this issue

fix: include expand aliases in digest

---

doc/changes/9041.md
src/dune_engine/action.ml
src/dune_engine/action.mli
src/dune_engine/build_system.ml
test/blackbox-tests/test-cases/corrections.t
test/blackbox-tests/test-cases/sandboxing.t

Internal actions that that don't need to be sandboxed would prevent the
entire rule from being sandboxed. Now we just sandbox them even if it's
not necessary.

fix: allow internal dune actions to be sandboxed

---

doc/changes/9052.md
src/dune_engine/build_system.ml
test/blackbox-tests/test-cases/dune-cache/mode-copy.t
test/blackbox-tests/test-cases/dune-cache/mode-hardlink.t
test/blackbox-tests/test-cases/dune-cache/repro-check.t
test/blackbox-tests/test-cases/dune-cache/trim.t
test/blackbox-tests/test-cases/patch-back-source-tree.t
test/blackbox-tests/test-cases/rule/digest.t/run.t
test/blackbox-tests/test-cases/rule/dune

The location of rules is only used for error messages. Therefore, we don't need to include it when computing digests.

fix: remove [loc] from rule digest

---

doc/changes/9076.md
src/dune_rules/lib.ml

fix: properly ignore bigarray if it shouldn't exist

---

src/fsevents/fsevents_stubs.c

Previously, the code waiting on `dq->dq_finished` would get notified in `dune_fsevents_dispatch_queue_wait_until_stopped` that the dispatch queue had completed running. This would lead to the dispatch queue being marked as `Stopped` on the OCaml side, even though the dispatch queue could be passed into `Fsevents.start` again.
This change now tracks the number of fsevents streams in a `fsevents_streams` counter so that `Dispatch_queue.wait_until_stopped` will only return when an exception is raised or if all streams have been stopped, restoring the original behavior in the code that used a runloop.
Fixes #9004. Fixes #8910.

fix: allow reuse of dispatch queues between fsevents in macOS

---

doc/changes/9282.md
src/dune_engine/sandbox.ml
test/blackbox-tests/test-cases/directory-targets/copy-sandboxing.t

Add support for copying sandboxes with symlinks. We do this just by copying whatever the symlink is pointing to. We also copy broken symlinks.

fix: copy sandboxes should copy symlinks as well

---

doc/changes/9309.md
src/dune_rules/dune_env.ml
src/dune_rules/dune_env.mli
src/dune_rules/env_node.ml
src/dune_rules/workspace.ml
test/blackbox-tests/test-cases/github5555.t

fix: correctly check if (binaries) is set in workspace file

---

doc/changes/8447.md
src/dune_rules/compilation_context.ml
src/dune_rules/env_node.ml
src/dune_rules/env_node.mli
src/dune_rules/env_stanza_db.ml
src/dune_rules/env_stanza_db.mli
src/dune_rules/format_rules.ml
src/dune_rules/format_rules.mli
src/dune_rules/gen_rules.ml
src/dune_rules/install_rules.ml
src/dune_rules/odoc.ml
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli
test/blackbox-tests/test-cases/formatting/disable-dune-file.t

This is an experiment to replace the `Env_tree`. The goal is to reduce the possibility of cycles, remove unnecessary memoization, and make it easy to introduce new values that depend on the `env` stanza without shoving everything in one module.

refactor: introduce simpler env stanza db

---

doc/changes/9449.md
src/dune_rules/context.ml

fix(pkg): allow OCAMLFIND_TOOLCHAIN to be set per context

---

doc/changes/9535.md
src/dune_cache/local.ml
src/dune_cache_storage/dune_cache_storage.ml
src/dune_cache_storage/dune_cache_storage.mli
src/dune_engine/build_system.ml
src/dune_shared_cache/dune_shared_cache.ml
src/dune_targets/dune_targets.ml
src/dune_targets/dune_targets.mli
test/blackbox-tests/test-cases/directory-targets/cache-file-and-dir.t
test/blackbox-tests/test-cases/directory-targets/cache-shared-subdir.t
test/blackbox-tests/test-cases/directory-targets/cache.t

This adds support for caching directory targets.

Cache directory targets

---

bin/printenv.ml
src/dune_rules/buildable_rules.ml
src/dune_rules/coq/coq_rules.ml
src/dune_rules/coq/coq_rules.mli
src/dune_rules/dune_rules.ml
src/dune_rules/env_node.ml
src/dune_rules/env_node.mli
src/dune_rules/env_stanza_db.ml
src/dune_rules/env_stanza_db.mli
src/dune_rules/expander.ml
src/dune_rules/expander.mli
src/dune_rules/foreign_rules.ml
src/dune_rules/foreign_rules.mli
src/dune_rules/inline_tests.ml
src/dune_rules/jsoo/jsoo_rules.ml
src/dune_rules/jsoo/jsoo_rules.mli
src/dune_rules/menhir/menhir_rules.ml
src/dune_rules/menhir/menhir_rules.mli
src/dune_rules/ocaml_flags_db.ml
src/dune_rules/ocaml_flags_db.mli
src/dune_rules/super_context.ml
src/dune_rules/test_rules.ml
test/blackbox-tests/test-cases/github7034.t/run.t
test/expect-tests/jsoo_tests.ml

This allows us to define the constituents of `Env_node` separately. The goals are as follows:
1. Make it possible for rules to define their own handling of their `env` fields individually. This allows for better isolation of subsystem specific parts to their own part of the rules. E.g. the coq stuff now lives separate from everything else.
2. Remove the manual shuffling of scope/artifacts that's required when creating the env node. Getting rid of this also fixes a bug with the vendored flags as we can see from the test. Also this PR doesn't completely get rid of this.
3. Improve the performance of incremental compilation. Now, we don't recompute all the effective values derived from `env` when a single one changes. The recomputation is reserved to only what needs to be recomputed. …

refactor: introduce inherited fields in stanza db

---

bin/init.ml
doc/changes/9447_fix_dune_init_proj_with_path.md
doc/usage.rst
test/blackbox-tests/test-cases/dune-init-proj-no-spurious-build-dir.t
test/blackbox-tests/test-cases/dune-init.t/run.t
test/blackbox-tests/test-cases/github7806.t

Fixes #9209
The logic around the `PATH` argument for the `dune init project` subcommand was incorrect. This was creating an unnecessary limitation on the behavior of the sub command, leading to #9209, and inconsistent behavior, diagnosed in https://github.com/ocaml/dune/issues/9209#issuecomment-1817510486.
This was the error: when the `PATH` argument was give to `dune init project`, the `NAME` argument was being appended as the final part of the path. As a result, instead of initializing the project in the specified directory, we were initializing it in a subdirectory of the given directory, bearing `NAME`. As an illustrative example, this led to the confusing behavior that both `dune init proj foo` and `dune init proj foo .` initialized projects in a newly created directory `./foo/`. …

fix(init): correct behavior of PATH argument for `dune init project`

---

bin/cache.ml
doc/changes/8975.md
src/dune_cache_storage/dune_cache_storage.ml
src/dune_cache_storage/dune_cache_storage.mli
test/blackbox-tests/test-cases/dune-cache/cache-man.t
test/blackbox-tests/test-cases/dune-cache/clear.t

Fixes #8971
Of course, if someone does `DUNE_CACHE_ROOT=/ dune cache clear` or similar they will zap their whole system...

Add `dune cache clear` command

---

doc/changes/9643.md
src/dune_file_watcher/dune_file_watcher.ml
test/expect-tests/dune_file_watcher/dune_file_watcher_tests_patterns.ml

Closes: https://github.com/ocaml/dune/issues/9517

fix: use standard_watch_exclusions with fsevents

---

doc/changes/9659.md
src/dune_rules/merlin/merlin.ml
test/blackbox-tests/test-cases/merlin/include-subdirs-qualified.t

Use the same -open flags that are used for compilation
Fixes #8297

fix: correctly output -open flags in merlin

---

doc/changes/9568.md
src/dune_rules/ocaml_flags.ml
test/blackbox-tests/test-cases/default-ocaml-flags-3-13.t

Warning 30 (same constructor/label name used in two mutually-recursive declarations) is an annoying warning that makes no sense since we introduced type-based disambiguation of fields and constructors. It was disabled by default in OCaml 4.10
https://github.com/ocaml/ocaml/pull/9046
and there is no reason to keep it in Dune.
Note: I wasn't sure how warning changes are supposed to be versioned (or not). 3eff8102d299bc6f408736ad641b0392957a4ac1 implements versioning for the new warnings 67, 69, but then c967d8a4880732f2f7cba39d4f283154c5ef914e earlier removed a bunch of warning without any specific versioning code. I went with the simplest approach of the two, but happy to take feedback. (This could benefit from a comment in the source besides `(* New warnings should be introduced here *)`.

Remove warning 30 from the standard set.

---

doc/changes/9578.md
doc/stanzas/library.rst
src/dune_lang/ordered_set_lang.ml
src/dune_lang/ordered_set_lang.mli
src/dune_lang/ordered_set_lang_intf.ml
src/dune_rules/artifacts.ml
src/dune_rules/artifacts.mli
src/dune_rules/dir_contents.ml
src/dune_rules/dir_contents.mli
src/dune_rules/dune_file.ml
src/dune_rules/dune_file.mli
src/dune_rules/exe_rules.ml
src/dune_rules/expander.ml
src/dune_rules/expander.mli
src/dune_rules/ml_sources.ml
src/dune_rules/ml_sources.mli
src/dune_rules/modules_field_evaluator.ml
src/dune_rules/modules_field_evaluator.mli
src/dune_rules/stanza_common.ml
src/dune_rules/stanza_common.mli
test/blackbox-tests/test-cases/modules-expansion.t

Currently `(modules)` has to be an "ordered set" consisting of literal string elements. This PR proposes to allow expansion to take place in this field, allowing in particular the use of `(:include)` and `%{read-lines:}` to specify lists of modules that depend on other artifacts built by Dune. Apart from representing a real improvement on the expresiveness of the build language, I have a feeling this change would also cover a considerable portion of use-cases of the OCaml syntax.
I suggest to start by looking at the test to understand what is being done in the PR.
The first commit is preparatory: it moves a submodule to avoid a dependency cycle in the second commit. The second commit contains the meat of the change:
- Replace `Ordered_set_lang.t` by `Ordered_set_lang.Unexpanded.t` for all …

Allow expansion in `(modules)` field

---

doc/changes/9496.md
otherlibs/stdune/src/map.ml
otherlibs/stdune/src/map_intf.ml
src/dune_rules/artifacts.ml
src/dune_rules/artifacts.mli
src/dune_rules/artifacts_db.ml
src/dune_rules/cinaps.ml
src/dune_rules/coq/coq_config.ml
src/dune_rules/coq/coq_rules.ml
src/dune_rules/expander.ml
src/dune_rules/fdo.ml
src/dune_rules/inline_tests.ml
src/dune_rules/jsoo/jsoo_rules.ml
src/dune_rules/mdx.ml
src/dune_rules/melange/melange_binary.ml
src/dune_rules/menhir/menhir_rules.ml
src/dune_rules/odoc.ml
src/dune_rules/super_context.ml
src/dune_rules/super_context.mli

Previously, we'd always binaries from the install context
(_build/install/$context/bin). This would unnecessarily load the install
rules.
Now, we add an argument that allows us to resolve to the original paths.
Reducing the amount of rules that need to be loaded.
We use this argument in a few cases where we don't need to build the
path in _build/install
Ideally, we'd use this everywhere as it's basically strictly superior. The only issue is that it doesn't preserve backward compat in cases like:
```
(rule
(dep %{bin:foo})
(action (run which foo)))
```
Resolving it in _build/install/default will make the `which` above succeed because we add the bin path in the install directory to the PATH when executing actions. There's a way to get around that of course, but it's not trivial.

fix: resolve installed binaries to local paths

---

doc/changes/9707.md
src/dune_rules/artifacts.ml
src/dune_rules/artifacts.mli
src/dune_rules/artifacts_db.ml
src/dune_rules/file_binding.ml
src/dune_rules/file_binding.mli
test/blackbox-tests/test-cases/bin-available.t
test/blackbox-tests/test-cases/more-than-one-optional.t

We wait until the binaries are resolved to determine if they are optional or not. This allows things to be a little more lazy as we avoid evaluating whether a binary is available until it's used.
Moreover, the handling of `enabled_if` on install sections is no longer ignored when generating the artifacts map

fix: optional binaries handling

---

bin/describe/describe_pp.ml
doc/changes/9769.md
src/dune_rules/dune_load.ml
src/dune_rules/dune_load.mli
src/dune_rules/only_packages.ml

Get rid of the slow dune file comparison in #9738

fix: performance regression from #8447

---

src/dune_rules/action_unexpanded.ml

Starting from 3.13, we resolve [foo] in [(run foo ..)] to where the
binary is defined rather than in the _build/install/default directory.

fix: use original paths in (run ..)

---

bin/ocaml/top.ml
doc/changes/8249.md
test/blackbox-tests/test-cases/top-module/load-from-lib.t

fix: correctly handle absolute paths in dune ocaml top-module

---

bin/subst.ml
doc/changes/9810.md
test/blackbox-tests/test-cases/subst/broken-symlink.t

fix(subst): ignore broken symlinks

---

doc/changes/9897.md
src/dune_rules/gen_rules.ml
test/blackbox-tests/test-cases/odoc/eif-lib-unavailable-doc-private.t

As discussed in https://github.com/ocaml/dune/pull/9839#issuecomment-1917934343.
The previous code was causing trouble when introducing conditionally builds of libraries using `enabled_if` (what's being done in #9839), because Dune would try to add the alias rules for a library that didn't exist.
The test uses the guidelines shared by @rgrinberg in https://github.com/ocaml/dune/pull/9875#issuecomment-1920223246.
Can check the [first commit](https://github.com/ocaml/dune/commit/6d7cab9999e4624a70415278794d3812840787de) in the PR to see current behavior in `main`.

fix: don't add odoc private rules in unavailable libs

---

bin/promotion.ml
doc/changes/9705.md
src/dune_engine/diff_promotion.ml
src/dune_engine/diff_promotion.mli
test/blackbox-tests/test-cases/promote/promotion-list.t

It is a starting point of `dune promotion list`. One of the concern would be the print format.
An example of Dyn format printed directly.
```
{ src = In_build_dir "default/bin/.formatted/main.ml"
; staging = None
; dst = In_source_tree "bin/main.ml"
}
{ src = In_build_dir "default/src/dune_patch/.formatted/dune_patch.ml"
; staging = None
; dst = In_source_tree "src/dune_patch/dune_patch.ml"
}
```

Add `dune promotion list` to display the current changes files.

---

bin/subst.ml
doc/changes/9895-subst-opam.md
src/dune_vcs/vcs.ml
src/dune_vcs/vcs.mli
test/blackbox-tests/test-cases/subst/opam-files/in-opam-subdir.t

fix(subst): subst for opam files in opam/ subdir

---

src/dune_rules/odoc.ml
src/dune_rules/odoc_new.ml
src/dune_rules/sherlodoc.ml
src/dune_rules/sherlodoc.mli
test/blackbox-tests/test-cases/odoc/new/odoc-unique-mlds/diff-scope.t/run.t
test/blackbox-tests/test-cases/odoc/new/warnings.t/run.t
test/blackbox-tests/test-cases/odoc/odoc-new-sherlodoc.t/run.t
test/blackbox-tests/test-cases/odoc/odoc-sherlodoc.t/run.t
test/blackbox-tests/utils/sherlodoc.ml

When calling sherlodoc on with @doc-new, all the .odocl are indexed by sherlodoc. It makes sense to index the dependencies, but the entries from the dependencies should be given less priority as search results. 
This PR passes a `--favoured` flag to sherlodoc, this flag identifies the .odocls that are not external. In turn, sherlodoc ranks these entries higher.

favour odocls that are not dependencies

---

bin/common.ml
bin/common.mli
bin/import.ml
doc/changes/10083.md

it was only useful for testing/benchmarking, but now it's not even used
for that.

fix: remove the --react-to-insignificant-changes option

---

bin/pkg/pkg_common.ml
src/dune_pkg/fetch.ml
src/dune_pkg/fetch.mli
src/dune_pkg/mount.ml
src/dune_pkg/opamUrl0.ml
src/dune_pkg/opamUrl0.mli
src/dune_pkg/opam_repo.ml
src/dune_pkg/opam_repo.mli
src/dune_pkg/rev_store.ml
src/dune_pkg/rev_store.mli
test/blackbox-tests/test-cases/pkg/commit-hash-references.t
test/blackbox-tests/test-cases/pkg/unavailable-package-source.t
test/expect-tests/dune_pkg/fetch_tests.ml
test/expect-tests/dune_pkg/rev_store_tests.ml

This is a set of improvements to the rev store that aims at simplifying
the implementation and interface. The following changes are notable:
* We no longer record any remote names in the git repo. There's no need
as we can just fetch individual objects and url's.
* We cache and reuse all remotes. This makes it more efficient to use
the same remotes more than once.
* We read branches/tags/default branches every time without saving it.
This is the correct thing to do as it has to be updated every single
we run dune as it can change.
* We cache the existence checks of git objects
* We now use the remote store to fetch sources when building packages

fix(pkg): rev store improvements

---

src/dune_pkg/source.ml

This one is a bit hard to test because it requires setting up a git repo over HTTP

fix(pkg): do not try to compute checksums of vcs pins

---

doc/changes/10160.md
src/dune_rules/artifacts.ml
src/dune_rules/artifacts.mli
src/dune_rules/artifacts_db.ml
src/dune_rules/artifacts_db.mli
src/dune_rules/expander.ml
src/dune_rules/expander.mli
src/dune_rules/super_context.ml
test/blackbox-tests/test-cases/dynamic-include-stanza/cycle.t
test/blackbox-tests/test-cases/install-with-var.t/run.t

Previously, we'd limit the variables that we could expand in the install
stanzas. This limitation was needed before we had memo and cycle
detection. Now that we have those, we can just rely on those mechanisms
and let users expand whatever they want.

fix: remove expansion limitation

---

doc/changes/10191.md
src/dune_rules/expander.ml
src/dune_rules/super_context.ml

do not require setting this binding manually everywhere. It's more code and an artificial limitation on where it can be used.

fix: allow inline test expansion everywhere

---

doc/changes/10185.md
src/dune_rules/cram/cram_rules.ml
src/dune_rules/cram/cram_rules.mli
src/dune_rules/expander.ml
src/dune_rules/expander.mli
src/dune_rules/gen_rules.ml
src/dune_rules/mdx.ml
src/dune_rules/simple_rules.ml
test/blackbox-tests/test-cases/cram/enabled_if-expansion.t

We should use the expander where the stanza is defined, rather than the
expander of the test.

fix: correct expander for cram stanzas

---

doc/changes/10011.md
src/dune_rules/lib.ml
test/blackbox-tests/test-cases/bigarray.t/d/d.bigarray.ml
test/blackbox-tests/test-cases/bigarray.t/d/d.dummy.ml
test/blackbox-tests/test-cases/bigarray.t/d/d.nobigarray.ml
test/blackbox-tests/test-cases/bigarray.t/d/dune
test/blackbox-tests/test-cases/bigarray.t/run.t

This is related to #9981.
It turns out the fact that `bigarray` is ignored is not known to `select`.

fix: `select` with `bigarray` in OCaml 5

---

bin/exec.ml
doc/changes/10262.md
test/blackbox-tests/test-cases/exec-watch/exec-pwd.t/run.t

Fixes a bug where commands run from `dune exec -w` would have the cwd of the project root rather than the directory where the command was run.
Fixes https://github.com/ocaml/dune/issues/10236
I haven't added any tests as a good test is added in https://github.com/ocaml/dune/pull/10241.

Exec watch mode spawns processes with initial cwd

---

doc/changes/8784.md
src/dune_rules/lib_rules.ml
test/blackbox-tests/test-cases/ctypes/bytecode-stubs-external-lib.t/dune
test/blackbox-tests/test-cases/ctypes/bytecode-stubs-external-lib.t/dune-project
test/blackbox-tests/test-cases/ctypes/bytecode-stubs-external-lib.t/example.ml
test/blackbox-tests/test-cases/ctypes/bytecode-stubs-external-lib.t/run.t
test/blackbox-tests/test-cases/ctypes/bytecode-stubs-external-lib.t/stubgen/dune
test/blackbox-tests/test-cases/ctypes/bytecode-stubs-external-lib.t/stubgen/function_description.ml
test/blackbox-tests/test-cases/ctypes/bytecode-stubs-external-lib.t/stubgen/type_description.ml
test/blackbox-tests/test-cases/ctypes/dune

Add link flags for external dependencies when using ctypes.
Required when the external lib is not statically linked, in which case
linker needs to be aware at runtime what libs to call. This is the case
for
- dune exec <file>.bc
- dune utop
- mdx tests
That is add to ocamlmklib, link flags such as -l<libname> -L<libdir>
from ctypes if info is available.
If dependent library are not installed in expected locations, env
variable such as LD_LIBRARY_PATH must be extended when required program
is run, depending on os. This may be fixed by adding relocatable paths to
link flags.

Add link flags ocamlmklib when using ctypes stubs.

---

doc/changes/10269.md
src/dune_rules/module.ml
src/dune_rules/module.mli
src/dune_rules/modules.ml
test/expect-tests/module_tests.ml

Fixes #10264
This fixes the round-trip (encoding/decoding) of `Modules.t` and `Module.Kind.t`.
The visible effect was a crash when `(include_subdir qualified)` was set for an installed library.
This area is difficult to test because we don't have an easy way to load dune-package files.
One part is tested via an expect test, but the other isn't (`Modules.t` is difficult to construct); however it has been tested on the repo mentioned in the original bug report.

fix: decoding dune-package crashes with (include_subdirs qualified)

---

doc/changes/10250.md
src/dune_rules/artifacts_obj.ml
src/dune_rules/artifacts_obj.mli
src/dune_rules/enabled_if.ml
src/dune_rules/expander.ml
src/dune_rules/expander.mli
src/dune_rules/expander0.ml
src/dune_rules/expander0.mli
src/dune_rules/install_rules.ml
src/dune_rules/lib_rules.ml
src/dune_rules/ml_sources.ml
src/dune_rules/scope.ml
src/dune_rules/stanzas/library.ml
src/dune_rules/stanzas/library.mli
src/dune_rules/super_context.ml
test/blackbox-tests/test-cases/enabled_if/eif-exec-forbidden_var.t/run.t
test/blackbox-tests/test-cases/enabled_if/eif-forbidden_var.t/run.t
test/blackbox-tests/test-cases/enabled_if/eif-install-forbidden_var.t/run.t
test/blackbox-tests/test-cases/enabled_if/enabled-if-lib-other-vars.t

Previously, the `enabled_if` field on libraries had a bunch of limitations. Basically, only variables that could be computed from the context could be used. E.g. `profile`, `context_name`, etc. This PR removes this limitation and now every variable is allowed provided that it doesn't introduce a memoization cycle.
Normally, such a feature would be trivial, but here we some module dependency cycles that prevent the natural solution from working. If it was possible, we would just call `Super_context.expander ~dir sctx |> Expander.eval_blang` everywhere and be done with it. Unfortunately, we have to solve two problems:
1. Expander depends on scope, and we need `enabled_if` to compute the scope
2. Super_context depends on scope, and therefore on various `enabled_if` through 1.
So we break …

feature: remove limitations on [enabled_if] on libraries

---

doc/changes/10319.md
src/dune_rules/odoc_new.ml

In fact this is likely not an empty library, but a package that either doesn't contain libraries or only contains sublibraries. In either case, it's not at all useful to say a library exists and has no modules!
Fixes #10056

doc-new: Omit docs for 'empty libraries'

---

doc/changes/10575.md
src/dune_util/global_lock.ml

Truncate it after successful locks and before an unlock.
This makes sure that we aren't left with garbage from previous runs.

fix: truncate lock file

---

src/dune_rules/lib.ml
test/blackbox-tests/test-cases/virtual-libraries/github10460.t

When compiling an implementation of a virtual library, there's a check that makes sure we don't the virtual library doesn't exist in the closure of the implementation.
This check tried to compute the linking closure of the library to do so. However, the linking closure might not be complete if the implementation contains other virtual library.
To fix the issue, we use a "partial" linking closure that tries to compute the closure as much as possible, but doesn't fail on missing implementation.
Fix #10460

fix: virtual libraries bug

---

bin/coq/coqtop.ml
doc/changes/10547.md

This fixes #7671 where `dune coq top` tries to take the global build lock even if `--no-build` is enabled.
The problem was that `Common.Builder.term` had `allow_builds` set to `true` by default and didn't get updated when `--no-build` was specified. This led to the creation of an RPC server at initialization, which triggers the lock.
The fix was to update `allow_builds` to `false` with `Common.Builder.forbid_builds`.

fix: don't take build lock for `coq top --no-build`

---

doc/changes/10766.md
doc/reference/dune-project/generate_opam_files.rst
src/dune_lang/package_info.ml
src/dune_lang/source_kind.ml
src/dune_lang/source_kind.mli
test/blackbox-tests/test-cases/source-stanza.t

Adds support to the `source` stanza for Gitlab style organization repositories. This PR is in reference to and would close #6723 if merged.
Putting this out there as a draft for feedback. Right now its implemented so that a 'link' of the type `organization/project/repo` can be prefixed with any of the supported platforms *(github, bitbucket, sourcehut, or gitlab)* in the source stanza despite the fact that I think only Gitlab uses this convention. It would be possible to present an error in the case that this format is used with a platform which does not support it but I was unsure if I should add this.

Organization In Source Stanza

---

doc/changes/10890.md
otherlibs/stdune/src/user_message.ml

Some of the text colors used by dune tend not to be readable on default light-themes terminals. Of course it will always be possible to configure your terminal so that some colors are too light/dark to read, but some of the preset themes on macos are unable to display some colors commonly used by dune.
The three types of text in question are `Ok` seen below as the green program names in the output of `dune build --display=short`, `Details` seen below as the dim text on the right side of the output of `dune build --display=short`, and `Hint` seen below as the inverted colors or italic text displaying the word "Hint" in the output of `dune pkg validate`.
The light theme is MacOS Terminal's "Novel" theme, the dark theme is MacOS Terminal's "Basic" theme, and the purple themes are "Catpuccin …

Change colors to be more readable in light themes

---

bin/common.ml
test/blackbox-tests/test-cases/pkg/ignore-lock-package-build.t

Fixes https://github.com/ocaml/dune/issues/11375
@rgrinberg do you remember why "--ignore-lock-dir" was added to the arguments passed by "--release"? Is it now safe to remove?

pkg: allow pkg for release builds
