ocaml/dune

- src/build.ml
- src/build.mli
- src/gen_rules.ml
- src/jbuild_types.ml
- src/string_with_vars.ml
- src/string_with_vars.mli
I didn't attempt at tackle any of the usability questions. Because my current
implementation is looking very shake.
Looking forward to a lot of feedback.
> Attempt at implementing aliases

- .gitignore
- CHANGES.org
- Makefile
- doc/manual.org
- doc/quick-start.org
- src/alias.ml
- src/config.ml
- src/context.ml
- src/context.mli
- src/file_tree.ml
- src/jbuild_load.ml
- src/main.ml
- src/path.ml
_build is already quite overloaded.
This was a search and replace job. Would probably be better if this was just a
constant somewhere
> Rename _build to _jbuild

- doc/quick-start.org
When running "jbuilder runtest" with "(name (runtest)))" in my jbuild, I got "Error: Atom expected". It seems that removing the extra parenthesis fixes this and is in line with the manual.
> Fix the runtest alias example.

- README.org
- bin/main.ml
- doc/manual.org
Here are some cosmetic improvements to jbuilder, namely fixes for the error message displayed when jbuilder is invoked with an invalid alias name, as well as for various typos and grammatical oddities I found in the documentation. Regarding the latter, English is not my native language but I've tried to use my best judgment and only include non-controversial changes.
> Cosmetic changes

- bin/main.ml
Most of my jbuilder invocations are to build `@install`, so I think that should be what `jbuilder build` does (it currently gives an error).
> Make "build" build @install by default

- doc/manual.org
- src/jbuild_types.ml
- test/jbuild
- test/workspaces/menhir/jbuild
- test/workspaces/menhir/lexer1.mll
- test/workspaces/menhir/lexer2.mll
- test/workspaces/menhir/parser.mly
- test/workspaces/menhir/test.ml
- test/workspaces/menhir/test_menhir1.mly
- test/workspaces/menhir/tokens.mly
Here's something basic that seems to work in most of the simple menhir
projects I've encountered.
Some things to note:
* I'm not sure if it's a good idea to support simple menhir and `--base` in the
same stanza. For example omake supports a separate `MenhirMulti` function
and ocamlbuild has mlypack just for modular menhir
* I'm pretty sure my flags handling is wrong. But there has to be something
in place to pass extra flags to menhir
* All the ocamlc/ocamldep stuff is avoided for now. This PR seems to be
sufficient for most (simple) uses of menhir out there. So perhaps this can
be marked as experimental an improved eventually.
* I don't whether I should add stuff to vjs, as I'm guessing you want to have
tight control over that at JST.
> Menhir support - first pass

- CHANGES.org
- doc/manual.org
- src/gen_meta.ml
- src/gen_rules.ml
- src/jbuild_types.ml
This PR adds `(no_dynlink)` field to libraries which disable the build of:
- the `.cmxs`
- the `.so` for the C stubs
It also passes the `-nodynlink` flag to `ocamlopt`, since there is no point in producing dynlinkable code.
/cc @LaurentMazare
> Allow to disable support for dynlink

- bin/main.ml
- doc/manual.org
- src/main.ml
- src/ml_kind.ml
- src/ml_kind.mli
The jbuilder command line in opam files is too long:
```
build: [
["jbuilder" "build" "@install" "--root" "." "--only" "utop" "-j" jobs]
]
```
And it might get longer if we add support for configuration files in the future:
```
build: [
["jbuilder" "build" "@install" "--root" "." "--only" "utop" "--no-config" "-j" jobs]
]
```
This PR adds a `--release pkg` option which is a shorthand for `--root . --only-package pkg`, and later might also include `--no-config`. With this and #47, we can simplify the invocation to:
```
build: [
["jbuilder" "build" "--release" "utop" "-j" jobs]
]
```
I'm not sure about the name of the option though. Suggestions welcome. Another possibility is to add a separate command, however we need the same thing for tests, so an option seems better.
> [RFC] simplify the jbuilder invocation in opam files

- src/gen_rules.ml
- src/import.ml
- src/module.ml
- src/module.mli
- src/utils.ml
- src/utils.mli
Attempt at #53 
@diml I've left the renaming commit separate at the end so you can judge if you want it or not.
@jordwalke @IwanKaramazow some testing would be appreciated.
> Reason support

- src/file_tree.ml
This makes jbuilder usable for building projects that use a local switch
> Ignore local switch directory

- doc/quick-start.rst
Great to see actual docs for Jane Street projects, so I thought I might try my luck contributing.
I was also a bit confused by the `.exe` thing on Unix, maybe I'll make another PR to clear that up.
> Fix small typo in quickstart

- bin/main.ml
- doc/api-doc.rst
- doc/index.rst
- doc/terminology.rst
- src/action.ml
- src/action.mli
- src/alias.ml
- src/alias.mli
- src/build.ml
- src/build.mli
- src/build_system.ml
- src/config.ml
- src/config.mli
- src/gen_rules.ml
- src/module.ml
- src/module.mli
- src/odoc.ml
- src/odoc.mli
- src/super_context.ml
- src/super_context.mli
This adds the `@doc` alias to build documentation of public libraries. The doc is stored in `_build/doc/<context-name>`.
> [WIP] odoc rules

- src/context.ml
- src/context.mli
- src/gen_rules.ml
The Microsoft C compiler doesn't recognise `-g`. For now, easier just not to compile with any debugging information on MSVC.
> Remove spurious C compiler warning on MSVC

- doc/jbuild.rst
Looks like the right syntax is `(select foo from (x -> y) ( -> y))`
from the example use in js_of_ocaml/compiler
> docs: remove an extra set of brackets from the `select ... from`

- doc/jbuild.rst
- src/action.ml
- src/artifacts.ml
- src/artifacts.mli
- src/bin.mli
- src/gen_rules.ml
- src/install.ml
- src/install.mli
- src/js_of_ocaml_rules.ml
- src/main.ml
- src/super_context.ml
When the user installs an executable, if the source file ends with `.bc` or `.exe`, jbuilder makes sure that the destination ends with `.exe`. This way executables that are installed in any section are correctly installed with the `.exe` suffix.
Additionally, Jbuilder now resolves `${libexec:<foo>:<file>}` to `<foo dir>/<file>.exe` if it exists, and `<foo dir>/<file>` otherwise.
@dra27, can you test this branch?
> Automatically install executable with extension `.exe` on Windows

- src/action.ml
- src/bin.mli
- src/context.ml
- src/future.ml
- src/import.ml
Addresses @fdopen's patch referred to in #146. Three changes accepted:
1. Sys.remove replaced with Sys.force_remove which will attempt to remove the "read-only" attribute on Windows files
2. ocaml variable now includes the .exe extension on Windows
3. Context.Temp.destroy silently fails if it can't delete the file (as the at_exit routine does)
I have not merged the change to bash escaping for two reasons: firstly, this is better solved in the long-term using the `cygvoke` mechanism I've written for opam (but this needs to be spun into a library) and until a full solution is there, I think it better to keep discouraging the use of bash in actions anyway.
@diml - please could you give this a quick once-over?
> Various Windows tweaks

- src/super_context.mli
- src/utils.mli
Warning 50: unattached documentation comment (ignored)
But I don't understand why travis does not catch that.
> Fix some warning 50 for 4.02.3

- .travis-ci.sh
- .travis.yml
- src/context.ml
- src/odoc.ml
A few changes to the Travis CI set-up:
- Include OCaml 4.05 in the test matrix
- Stop using opam, as it's not necessary, and build the compiler directly
- As a result of that simplification, build using `--dev`, and as a result a commit of @bobot's from #179 which fixes a few deprecation warnings
@rgrinberg - please could you cast an eye over this? Then we can be testing 4.05 meaningfully before @diml gets back from vacation!
> CI changes

- src/merlin.ml
This is useful, for example, if one needs to pass specific  flags
by hand (due to the need to use old libraries for example).  Fixes
https://github.com/janestreet/jbuilder/issues/198
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> Preserve quotes on certain flags that contain spaces

- CHANGES.md
- src/arg_spec.ml
- src/arg_spec.mli
- src/findlib.ml
- src/findlib.mli
- src/jbuild_load.ml
- src/js_of_ocaml_rules.ml
- src/lib.ml
Instead of passing `-I <path> file.cma` to the compiler, pass `-I <path> <path>/file.cma`.
Fixes #118 and #177.
Using the full path should also be slightly faster as the compiler won't have to do the lookup through all include paths. The only drawback is that it makes linking command line slightly longer, maybe that's a problem for Windows (cc @dra27).
> Use the full path of archives when linking

- src/jbuild.ml
Also include the malformed module name in the error message so it's more clear what it's complaining about.
> Allow digits and apostrophes in library/module names

- CHANGES.md
- src/merlin.ml
This should make .merlin files generated by jbuilder compatible with merlin < 3.0.0 and >= 3.0.0
Fixes #196 and #199
> Use absolute paths for ppx drivers in .merlin files

- doc/jbuild.rst
- src/build.ml
- src/build.mli
- src/gen_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/js_of_ocaml_rules.ml
- src/js_of_ocaml_rules.mli
- src/merlin.ml
- src/merlin.mli
- src/module_compilation.ml
- src/module_compilation.mli
- src/ocaml_flags.ml
- src/ocaml_flags.mli
- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
- src/super_context.ml
- src/super_context.mli
As per the title - with thanks and due credit to @diml for patient pointers through the internals of jbuilder!
Longer term the aim is to also extend `${read ...}` forms from the action DSL, but this is a necessary first step, and possibly the `${read ...}` change should be for 1.1 anyway?
It would be very good to have this in 1.0 - I shall be experimenting with it later to convert some of my OCaml Syntax jbuild files back to s-expression only.
> Extend `(:include )` to anything that looks like a flag

- bin/main.ml
- src/build_system.ml
- src/build_system.mli
- src/gen_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/main.ml
- src/main.mli
- src/merlin.ml
- src/merlin.mli
- src/utop.ml
- src/utop.mli
Accepts a library name as input and builds and runs utop which loads the given
library.
Here's an attempt at #114. Some comments and questions:
* How would I use .utop.ml as you recommended? It's not a valid module name.
* ~~For now, I've used `uutop.ml` as a workaround, which is not satisfying. In particular, I'm kind of worried that this will interfere with current builds by adding this uutop.ml file which might be included in globs in later builds. Would it make sense to add a separate directory for these utop binaries to solve
these issues? Right now, I'm relying on the fact that I'm defining the utop rules after defining all other rules which seems to work but seems hacky.~~
EDIT: The uutop.ml now exists in its own directory, so this isn't an issue.
* Currently, I'm creating a single …
> utop subcommand

- src/utop.ml
This allows jbuilder to create toplevels with conflicting module names. Such as
ExtLib's and Camomiles' UChar for example.
cc @jvillard
> Disable warning 31 for utop

- .gitignore
- Makefile
- bootstrap.ml
As it happens, bootstrap.ml doesn't trigger warning 40, but putting it as an attribute has the benefit of allowing bootstrap.ml to be compiled before being run.
> Allow bootstrap.ml to be compiled

- CHANGES.md
- src/gen_meta.ml
This PR simplifies the `META` files generated by jbuilder for ppx rewriters by dropping the `deprecated-ppx-method` sub-package. The fields it contains are inlined in the parent package.
We use to generate something like this:
```
requires(-ppx_driver) = "ppx_sexp_conv.deprecated-ppx-method"
package "deprecated-ppx-method" (
version = "v0.9.0"
description = "glue package for the deprecated method of using ppx"
requires = "bigarray sexplib sexplib.0 unix"
requires(-ppx_driver,-custom_ppx) += "ppx_deriving"
ppxopt(-ppx_driver,-custom_ppx) = "ppx_deriving,package:ppx_sexp_conv"
)
```
now we generate:
```
requires(-ppx_driver) = "bigarray sexplib sexplib.0 unix"
requires(-ppx_driver,-custom_ppx) += "ppx_deriving"
ppxopt(-ppx_driver,-custom_ppx) = "ppx_deriving,package:ppx_sexp_conv"
```
I …
> Get rid of the deprecated-ppx-method sub-package

- CHANGES.md
- doc/jbuild.rst
- src/action.ml
- src/action_intf.ml
- src/alias.ml
- src/build.ml
- src/build.mli
- src/build_system.ml
- src/gen_rules.ml
- src/merlin.ml
- src/odoc.ml
- src/sexp.ml
- src/sexp.mli
- src/utils.ml
- src/utils.mli
- src/utop.ml
As discussed in #158.
The implementation is rather simple and simply use `Digest.file`. The table `Path.t -> Digest.t` database is cached to disk and we use timestamps to avoid recomputing digests.
I tried this to build 99 Jane Street packages at once. Without caching the database to disk, null builds go from ~1.9s to ~10s. We'll typically get the same overhead for builds from scratch whether or not we cache the database . Building the 99 packages from scratch with `-j16`takes ~1.30s with master. So I guess it's not too bad.
After caching the database to disk, null builds take ~2.5s. We could improve this a bit by doing something clever for symlinks. We could also improve this by digesting files in a separate thread, but this will make the scheduler a lot more complicated.
This still …
> [WIP] use digest of file contents to detect changes

- src/ordered_set_lang.ml
The form `(:include $(SCOPE_ROOT)\foo)` requires quoting, but the error message was cryptic ("Error: undefined symbol include").
Related to #232 - see comment in https://github.com/janestreet/jbuilder/pull/153#issuecomment-324286383
> Improve error handling for (:include )

- src/gen_rules.ml
- src/odoc.ml
- src/odoc.mli
See http://mirage.github.io/ocaml-git/index.html for an example of what is generated. It's really minimal at the moment but that's better than nothing.
> Add a toplevel html index to the docs

- bin/main.ml
While investigating the Travis failure in #239, I discovered a bug in https://github.com/janestreet/jbuilder/commit/3fb191503385ebb12c4c37a710d84753fa1a7b5e. The new `Path.to_absolute` function asserts that Clflags.workspace_root is absolute, but this isn't true *especially* if `jbuilder build` was called with `-p` (which implies `--root=.`). The simple fix is to set `workspace_root` to the cwd immediately after chdir call.
This can be seen by pinning jbuilder and trying to install cppo 1.6.0 in Opam (it won't be seen with cppo master because it no longer uses OCaml syntax)
> Ensure Clflags.workspace_root is always absolute

- .travis-ci.sh
- .travis.yml
This PR also includes a couple of cosmetic changes to the Travis scripts.
The main change is to add a second build stage which runs the latest OCaml and opam in order to allow the testsuite to be run. So the testsuite is run only if the main OS/OCaml matrix passes.
Somebody with more patience than me with useless formats like YAML may be able to compress the build matrix; I got bored with uploading samples and wasn't sufficiently interested to download the Travis ruby scripts locally to try testing it...
> Run tests in CI

- src/string_with_vars.ml
When the current character is '$' we peek at the next character. But we first
need to make sure that there is a next character.
> Fix out of bounds access when tokenising String_with_vars

- src/odoc.ml
When the docs are viewed locally, the URL `..` causes the browser to display a listing of the parent directory, instead of `../index.html`. The `../index.html` interpretation is only provided by web servers.
> Fix "Up" links to top-level index

- CHANGES.md
- bin/main.ml
- doc/jbuild.rst
- doc/terminology.rst
- doc/usage.rst
- src/alias.ml
- src/alias.mli
- src/build_system.ml
- src/build_system.mli
- src/file_tree.ml
- src/file_tree.mli
- src/gen_rules.ml
- src/import.ml
- src/jbuild.ml
- src/jbuild.mli
- src/jbuild_load.ml
- src/jbuild_load.mli
- src/main.ml
- src/main.mli
- src/path.ml
- src/path.mli
- src/super_context.ml
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/aliases/jbuild
- test/blackbox-tests/test-cases/aliases/run.t
- test/blackbox-tests/test-cases/aliases/src/foo/bar/jbuild
- test/blackbox-tests/test-cases/aliases/src/foo/baz/jbuild
- test/blackbox-tests/test-cases/aliases/src/jbuild
- test/blackbox-tests/test-cases/js_of_ocaml/run.t
Fixes #253.
ThisPR  removes the special _recursive aliases_ `runtest`, `install` and `doc`. Now all aliases are non-recursive. However, the interpretation of aliases on the command line is changed so that when the user types:
```sh
$ jbuilder build @src/x
```
this is interpreted as alias `x` in all descendant of `src` where it is defined. This way the interpretation of `@runtest`, `@install` and `@doc` is unchanged and users can define their own global aliases such as `examples`, `runtest-js`, ...
Inside jbuild files, one can use `(deps (... (alias_rec XXX) ...))` to get the same behavior.
In any case, when the alias is defined in none of the descendant of the specified directory, jbuilder reports an error. Except for `runtest`, `install` and `doc` as this could break existing invocations …
> Sort out recursive/non-recursive aliases

- src/gen_rules.ml
- src/odoc.ml
- src/odoc.mli
odoc was updated recently to support arbitrary `.mld` files (cf. ocaml-doc/odoc#61 ), as a result the `--index-for` flag of the `html` command was removed.
This PR updates the rules to follow the new odoc conventions and seems to work on my test cases (it handles arbitrary `.mld` files), it's probably not as clean as it could be, but I'm hoping you guys can help with that :)
This probably shouldn't be merged (or at least, shouldn't be released on opam) before a new release of odoc is made (which should happen "soon"™).
> RFC update odoc rules

- doc/quick-start.rst
.exe for executables is usually a windows-only convention; this threw me
for a moment and it seems worth calling out that this isn't platform
dependent.
> Clarify use of the .exe extension

- src/context.ml
The contents of `m.h` and `s.h` (in `$PREFIX/lib/ocaml/caml`)
used to be inlined in `config.h` (before 4.06), but they are now
copied and `config.h` just `#include` them.
Jbuilder basically greps `config.h`, looking for `#define ARCH_SIXTYFOUR`
to determine whether the underlying architecture is 64-bit.
As a result, the `ARCH_SIXTYFOUR` variable of jbuilder is
always set to false.
(The problem was diagnosed when trying to build the `re2`
package with 4.06)
> Fix detection of 64-bit architectures for 4.06

- src/context.ml
During architecture detection, check whether a file exists before trying to read from it...
> Fix regression introduced by PR303.

- src/odoc.ml
Currently, Jbuilder doesn't build documentation for non-public libraries. It would be nice if this was possible. This PR makes it the default, which may not be a good long-term decision. I'm happy to make any changes to improve the ergonomics and not break existing use cases.
> Build documentation for non-public libraries

- bin/main.ml
- src/import.ml
When the path passed contianed to exec contains a '/', it will be interpreted
relative to the path of a build context (default context when absent)
Fix #152
> Improve jbuilder exec

- src/action.ml
- src/action.mli
- src/artifacts.ml
- src/artifacts.mli
- src/build.ml
- src/build.mli
- src/gen_rules.ml
- src/module_compilation.ml
- src/ocamldep.ml
- src/super_context.ml
- src/super_context.mli
- src/utils.ml
- src/utils.mli
It would be nice to do this without modifying Prog_spec.
Fix #170
> Fix jbuilder rule in case of missing binaries

- src/gen_rules.ml
Previously, "S. " wasn't added at all. This commit improves the behavior to add
this source whenever we can find at least one module whose original source isn't
from copied_files.
This isn't completely correct whenever some modules are from the jbuild dir, and
some are copied. Fixing this for real will wait until better support from merlin
itself.
> Add "S ." to .merlin when necessary

- src/import.ml
This is from the jbuilder exec branch. Which surprisingly wasn't broken by this.
> Fix off by 1 error in String.drop_prefix

- bin/main.ml
- src/import.ml
There's no need for runcwd as initial_cwd is already defined somewhere. Add
Filename.analyze_program_name function to make the clearer.
This is a patch emailed to me by diml. Though I offered the commit message.
> Refactor jbuilder exec path handling

- src/build_system.ml
I think this was omitted accidentally. Anyways, it will be useful for verifying that actions are selected correctly for target contexts.
> Pass context when executing actions

- .travis-ci.sh
- .travis.yml
Minor correction to the macOS test matrix (test building on 4.06; use 4.05 for opam test).
We can't run the tests on 4.06 at the moment in this setup because opam doesn't build out of the box with 4.06.0 (safe-string). When that dust settles, the obvious thing will be to migrate to opam 2.0.
The problem was two-fold before - there seems to have been a stale jbuilder pin which got into the cache somehow, which I've fixed by deleting it when it's detected. The other issue is that opam was never updating unless forced - it will now do an opam check once per day and refresh the opam installation if necessary.
> [WIP] Sort out CI testing problem

- bin/main.ml
- src/alias.ml
- src/alias.mli
- src/gen_rules.ml
- src/gen_rules.mli
- src/import.ml
- src/main.ml
- src/main.mli
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/force-test/f.ml
- test/blackbox-tests/test-cases/force-test/jbuild
- test/blackbox-tests/test-cases/force-test/run.t
By deleting all of its alias files from the store. I think this turned out to be quite simple unlike what diml predicted in #84. Therefore, I think we should prefer this implementation because it doesn't change the execution of build rules at all.
cc @rdavison
> Add option to force running tests

- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/meta-gen/jbuild
- test/blackbox-tests/test-cases/meta-gen/run.t
Try to test as many aspects as possible: dependencies, synopsis, ppx, etc.
I noticed that this was easy to add without relying on cat if we have `--force`
> Add tests for meta generation

- bin/main.ml
- src/utop.ml
Fix #326 
The first patch is verbatim from diml. I did not want to apply it initially because it broke `jbuilder utop`, but I just had a second look and it's easily fixed by just using absolute dirs. I don't think there are any advantages to using absolute paths here.
> Fix jbuilder exec from sub dirs & utop

- src/super_context.ml
Same fix as 6a3c51c35899fe346804d34497dee594690c0ef6 but also for ppx's
I  just elected to do a similar fix to what @dra27 , but I think cleaner is to simply change the definition of `Lib.archive_files` to include the .a files.
> Fix incremental compilation with ppx's

- bin/main.ml
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/exec-cmd/bar.ml
- test/blackbox-tests/test-cases/exec-cmd/foo.ml
- test/blackbox-tests/test-cases/exec-cmd/jbuild
- test/blackbox-tests/test-cases/exec-cmd/run.t
This option turns out to be quite handy in practice. Been using it for the last day without major issues. I've elected to just make its own option for now because `--dev` seems like it would leave the user guessing. Maybe it's best to support both flags?
Fix #317
cc @copy
> Jbuilder exec rebuilt if possible option

- src/findlib.ml
- src/meta.ml
- src/meta.mli
(originally reported by @trefis)
When trying to link with `nums` in OCaml 4.06, the user gets
an unexpected error message if `ocamlfind` is not present,
because `jbuilder` hardcodes (in `src/meta.ml`) the set of
package that ship with the OCaml distribution.
This PR conditionally includes `nums` in the set, by testing
if the related archive file is present.
> Availability of "num" depends on the OCaml version

- src/odoc.ml
This page generation code really should be moved to odoc, however.
> odoc: don't generate raw HTML and level 1 headings

- test/blackbox-tests/test-cases/reason/jbuild
- test/blackbox-tests/test-cases/reason/ppx/jbuild
- test/blackbox-tests/test-cases/reason/ppx/reasonppx.ml
- test/blackbox-tests/test-cases/reason/run.t
Here's another example of a driver issue I don't understand - this time in conjunction with reason. I can't figure out how to pass driver flags to even the omp driver when used in conjunction with reason sources.
> Add some reason tests wrt to ppx preprocessing

- src/path.ml
- test/unit-tests/jbuild
- test/unit-tests/path.mlt
It doesn't work when the paths are equal or have the same length.
@toots can you try the x branch with this patch applied? Also, it would be nice to understand which paths causing the crash on windows. It seems strange that this a windows only issue. So if you have the bandwidth to add some printf'ing here and find the offending paths that would be wonderful.
> Fix Path.descendent

- CHANGES.md
- src/action.ml
- src/path.ml
- src/path.mli
- test/blackbox-tests/test-cases/copy_files/bar.c
- test/blackbox-tests/test-cases/copy_files/include/bar.h
- test/blackbox-tests/test-cases/copy_files/jbuild
- test/blackbox-tests/test-cases/copy_files/run.t
Microsoft CL doesn't support `#n` and requires the more strictly correct directive `#line`. I've done this by changing the behaviour of `copy#` depending on the file extension.
> Fix copy# for Microsoft C compiler

- test/blackbox-tests/test-cases/copy_files/jbuild
- test/blackbox-tests/test-cases/copy_files/run.t
@dra27 this seems than just skipping the test. If we want to test the case of no modules we can simply add that as a different test case to skipped for 4.02.3.
> Add dummy module to make copy_files test pass on 4.02.3

- src/context.ml
c_compiler can still contain arguments that need to be parsed. Unfortunately,
they must be discarded because it's possible they're already present in
{ocamlc,ocamlopt}_flags
@yminsky if you can, see if this fixes the issue for you (and you see the warning)
> Fix c_compiler parsing for OCaml >= 4.06.0

- CHANGES.md
- Makefile
- bin/main.ml
- doc/jbuild
- doc/jbuild.inc
- doc/jbuild.rst
- doc/update-jbuild.sh
- doc/usage.rst
- src/action.ml
- src/action.mli
- src/action_intf.ml
- src/clflags.ml
- src/clflags.mli
- src/diff.ml
- src/diff.mli
- src/jbuild.ml
- src/jbuild.mli
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/promote/jbuild
- test/blackbox-tests/test-cases/promote/run.t
This PR implements something similar to what was discussed in #371 except for toplevel `(promote ...)` stanza which will be part of another PR.
This PR makes it easier to have generated files that are committed in the source code repository. This method has a few use cases:
- to handle bootstrapping issues
- for single use code generators, when it's easier to review the generated code than the code generator itself
In particular, it provides a nice way to have a jbuild files that are generated and committed in the source tree. This is used in jbuilder itself, in `doc/jbuild`.
Additionally, this PR provide the necessary support for tools that generate *corrected* files, such as expectation tests, some ppx rewriters, etc...
This PR adds two new forms in actions:
- `(promote (<a> as <b>) …
> Add promote actions and include stanzas

- CHANGES.md
- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/super_context.ml
- test/blackbox-tests/test-cases/misc/jbuild
- test/blackbox-tests/test-cases/misc/run.t
> Report better errors for globs pointing to non-existing directories

- doc/jbuild.rst
- src/action.ml
- src/action_intf.ml
- src/super_context.ml
This PR makes `[@@deriving_inline ...]` works with jbuilder. It requires: https://github.com/janestreet/ppx_driver/pull/17
> Accept correction files produced by ppx_driver

- src/action.ml
- src/action.mli
- src/build_interpret.ml
- src/gen_rules.ml
- src/super_context.ml
- src/super_context.mli
The build of cppo is broken with master: it define an alias that produce targets. As a result, we end up with an action that has targets in several directories: the user targets + the alias stamp file.
This PR change the code to ignore such targets and report a warning. I also factorized a bit the code in `Action.Infer`.
BTW, the warning could now be avoided in cppo by using `(ignore-stdout ..)` instead of redirecting it to a file.
> Better behavior when aliases have targets

- CHANGES.md
- src/action.ml
- src/path.ml
The legacy DOS readonly attribute is a tedious difference on Windows, because a user may have permission to delete a file, but unlink fails because the attribute is set.
> Remove readonly attribute on Windows before unlink

- CHANGES.md
- src/arg_spec.ml
- src/arg_spec.mli
- src/gen_rules.ml
The `-o` option in the Microsoft C Compiler is deprecated (and has been for a very long time). The warning is tedious, so use /Fo instead. The only problem with this is that `-o foo.obj` must become `/Fofoo.obj` with no space, which requires a little support in `Arg_spec`.
This appears principally when compiling C++ sources, as these aren't compiled by OCaml (which already handles these differences).
Still to do is suppressing the tedious display of the source file being compiled (see https://github.com/ocaml/ocaml/pull/407) but that hasn't (yet) been annoying me as much as the deprecation warning!
> Use /Fo instead of -o when invoking CL

- src/gen_rules.ml
- src/module.ml
- src/module.mli
- src/odoc.ml
- src/odoc.mli
- src/super_context.ml
- src/super_context.mli
- test/blackbox-tests/test-cases/multiple-private-libs/run.t
- test/blackbox-tests/test-cases/odoc/run.t
This is a minimal version of #304. It only contains fixes to the rules to follow odoc's latest conventions. It doesn't include any of the installation stuff and the documentation stanza.
I'd prefer not to rush with adding a new stanza, especially since there's some wrinkles to the proposed design. Let's just review and merge this PR so that we unblock releasing jbuilder. We'll have plenty of time to design the documentation stanza after the release.
I'll make a separate PR for that work once this one is merged.
> New odoc rules (minimal)

- CHANGES.md
- src/file_tree.ml
- src/import.ml
This is technically a regression introduced in beta15 by #268, but I think that the new behaviour is probably what was wanted originally (it's consistent with how the manual describes jbuild-ignore files too). Prior to #268, you could specify subdirectories in jbuild-ignore files (like, say, .gitignore).
This patch displays a warning for any item in jbuild-ignore which refers to a subdirectory (i.e. `foo` is permitted but `foo/bar` is not).
The alternative would be to restore the pre-beta15 behaviour but in many ways forcing jbuild-ignore to be spread over the tree feels better in terms of composability.
> Display a warning for bad jbuild-ignore lines

- src/gen_meta.ml
- src/gen_meta.mli
- src/gen_rules.ml
- src/lib_db.ml
- src/lib_db.mli
- src/super_context.ml
- src/super_context.mli
- test/blackbox-tests/test-cases/meta-gen/jbuild
- test/blackbox-tests/test-cases/meta-gen/run.t
- test/blackbox-tests/test-cases/odoc/run.t
This PR does the following:
- it generates a `ppx_runtime_deps` variable even for normal libraries (i.e. not with `(kind ppx_rewriter)` or `(kind ppx_deriver)`)
-  it uses the transitive closure for `requires(-ppx_driver)`, since `ocamlfind` won't scan the dependencies of the ppx rewriter itself
I added a test and successfully built `bin_prot`, which is otherwise failing with master
Fix #440
> Fix meta generation for ppx runtime deps

- src/gen_meta.ml
- src/gen_meta.mli
- src/gen_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/lib_db.ml
- src/lib_db.mli
- src/super_context.ml
- src/super_context.mli
- test/blackbox-tests/test-cases/meta-gen/run.t
This fixes the test added in #449.
I realized that the the function that compute the runtime deps of the transitive closure was trying to be too clever and add scoping issues... I rewrote it
> Add the runtime dependencies of the transitive closure of used ppx rewriters

- src/findlib.ml
- src/findlib.mli
- src/lib_db.ml
- src/main.ml
But to avoid making the catch statements verbose, move all findlib exceptions to
a variant.
> Avoid catching wildcard exceptions when calling Findlib.find

- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/build_interpret.mli
- src/build_system.ml
- src/super_context.ml
it can always be inferred from when we can construct the rule. But to do that,
we have to pass it along to internal_rule.
> Remove the path argument from Record_lib_deps

- test/blackbox-tests/test-cases/gen-opam-install-file/jbuild
- test/blackbox-tests/test-cases/gen-opam-install-file/run.t
- test/blackbox-tests/test-cases/meta-gen/jbuild
- test/blackbox-tests/test-cases/meta-gen/run.t
Make sure that adding js runtime files reflects correctly in the META and
.install files
> Add tests of js_of_ocaml flag

- CHANGES.md
- bin/main.ml
- src/action.ml
- src/action.mli
- src/build_system.ml
- src/utils.ml
- test/blackbox-tests/test-cases/promote/run.t
Previously we were only using mtime but it's not precise enough on OSX.
> Fix bad interaction between promotion and incremental builds on OSX

- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/loop/jbuild
- test/blackbox-tests/test-cases/loop/run.t
I just realized that the way loop detection is implemented is not very robust. I'm fixing this in the continue-on-error-branch
> Add a test for dependency cycles

- CHANGES.md
- src/gen_rules.ml
- src/lib.ml
- src/lib.mli
- src/module_compilation.ml
- src/odoc.ml
- src/super_context.ml
- src/utop.ml
Make sure we don't pass `-I <stdlib-dir>` to the compiler. This path is always implicitly added and passing it doesn't play nice with #472
> Do not pass -I <stdlib-dir>

- bin/main.ml
- src/action.ml
- src/action.mli
- src/artifacts.ml
- src/findlib.ml
- src/findlib.mli
- src/jbuild_load.ml
- src/js_of_ocaml_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_db.ml
- src/lib_db.mli
- src/merlin.ml
- src/super_context.ml
- test/unit-tests/tests.mlt
This PR only makes the `Findlib.package` abstract.
Making this type abstract will make refactoring library manage easier. The next step is to make `Lib.t` abstract as well.
> Make `Findlib.package` abstract

- jbuilder.opam
The test deps themselves depend on jbuilder to build. This is not possible with
opam
cc @diml @dra27
> Remove all {test} deps in jbuilder

- src/gen_rules.ml
- src/lib.ml
- src/lib.mli
- src/super_context.ml
- test/blackbox-tests/test-cases/js_of_ocaml/run.t
I realized that the addition of dependencies on `<lib>.a` files when linking an executable was replicated in a few places instead of being in `Lib.archive_files`. This patch changes that. I also updated a bit the code adding dependencies on `<module>.o` files to use the list of modules directly rather that `Path.change_extension`.
> Move the addition of <lib>.a dependencies to Lib.archive_files

- bin/main.ml
- src/action.ml
- src/action.mli
Before:
```
$ jbuilder rules doc/jbuilder.1
((deps (_build/install/default/bin/jbuilder))
(targets (_build/default/doc/jbuilder.1))
(context default)
(action
(chdir
_build/default/doc
(with-stdout-to
_build/default/doc/jbuilder.1
(run _build/install/default/bin/jbuilder --help=groff)))))
```
after (only the last line differs):
```
$ ./_build/install/default/bin/jbuilder rules doc/jbuilder.1
((deps (_build/install/default/bin/jbuilder))
(targets (_build/default/doc/jbuilder.1))
(context default)
(action
(chdir
_build/default/doc
(with-stdout-to
jbuilder.1
(run ../../install/default/bin/jbuilder --help=groff)))))
```
The latter looks more intuitive to me
> Use relative paths in the output of `jbuilder rules`

- src/super_context.ml
`closure'` isn't the prettiest function, but we do get rid of a fair bit of duplication here.
> Deduplicate closure and closed_ppx_runtime_deps_of

- src/gen_rules.ml
- src/lib_db.ml
- src/lib_db.mli
- src/super_context.ml
Two versions aren't really necessary as mostly the primed version was used.
> Remove primed Lib_db.find_scope

- src/import.ml
- src/js_of_ocaml_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_db.ml
- src/merlin.ml
- src/odoc.ml
- src/super_context.ml
Making it private as a first step. There's a few cases where I'm not really sure how to make the distinction go away without pattern matching:
`S` and `B` for internal and `PKG` for external packages. I guess we could get rid of `PKG` directives entirely if we just have `val lib_obj_dir : t -> Path.t` and `val src_dir : t -> Path.t option`. Not sure if this desirable though.
Jsoo's incremental compilation special cases external libraries. Perhaps we could keep the internal lib js artifacts in the global js dir?
For external libs we just take globs for things like header files, while for internal libs we are careful to only use the files listed in the library definition
There's special casing for deep traversal here which only makes sense for external packages. I suppose we can have a …
> Make Lib.t abstract

- bin/main.ml
- src/artifacts.ml
- src/findlib.ml
- src/findlib.mli
- src/js_of_ocaml_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_db.ml
- src/main.ml
- src/report_error.ml
- src/utils.ml
- src/with_required_by.ml
- test/blackbox-tests/test-cases/findlib/run.t
- test/blackbox-tests/test-cases/github25/root/run.t
- test/unit-tests/tests.mlt
This PR changes the findlib module to compute the transitive closure of a findlib package lazily. This simplify the code and prepare for further changes:
- we need something like this for variants, since the transitive closure depends on the selected variants
- it will make it easier to factorize the code between findlib packages and internal libraries
> Compute the transitive closure of findlib packages lazily

- src/findlib.ml
- src/interned.ml
- src/interned.mli
- src/mode.ml
- src/mode.mli
- src/variant.ml
- src/variant.mli
- intern predicate names. We will use this more in the future when we support library variants
- add a Variant module, in preparation for library variants
> Rewrite the findlib predicate stuff

- bin/main.ml
- src/config.ml
- src/config.mli
- src/main.ml
If using progress mode, the output is not a tty and we are not running inside emacs, then switch to quiet mode
> Fix display when output is not a tty

- CHANGES.md
- src/build_system.ml
- src/build_system.mli
- src/odoc.ml
- test/blackbox-tests/test-cases/multiple-private-libs/run.t
Private docs can still be built using the new @doc-private alias
cc @trefis
> Change @doc to only build public docs

- src/import.ml
- src/jbuild.ml
- src/jbuild.mli
- src/per_item.ml
- src/per_item.mli
- src/super_context.ml
Currently, if we have something like `(preprocess (pps (a b c)))` and 20 modules, we are going to call `get_ppx_driver ... ["a"; "b"; "c"]` once for every .ml and .mli files, so 40 times in total.
After this patch, we only call it once.
> Share more results when preprocessing modules

- src/exe.ml
- src/exe.mli
- src/gen_rules.ml
- src/ocaml_flags.ml
- src/ocaml_flags.mli
- src/super_context.ml
- src/super_context.mli
- src/utils.mli
I extracted this from the ppx-runner branch. We need to use that in utop.ml so that we don't have to generate a file called "utop.ml", which causes a warning with #532.
> Add an Exe module to build and link executables

- src/gen_rules.ml
- src/super_context.ml
The `ppx_base` package will come with its own runner,
needing support from dune.
> Add support for upcoming ppx_base

- src/utop.ml
- test/blackbox-tests/test-cases/utop/run.t
This isn't as simple as I thought (as the failing test shows).
> Use .utop.ml to avoid creating a separate dir for utop rules

- CHANGES.md
- src/gen_rules.ml
- test/unit-tests/jbuild
I found this while working on #548. The `Lib__` module needs to have an implementation with OCaml 4.02. This bug is present since #490.
> Fix generation of the alias module with 4.02

- test/blackbox-tests/test-cases/exec-cmd/jbuild
- test/blackbox-tests/test-cases/exec-cmd/run.t
Use dunetestbar rather than bar as a binary name. The former name is too common
and hence can make the test fail if a bar binary exists elsewhere.
> Use a more unique binary name

- src/gen_rules.ml
- src/install_rules.ml
- src/install_rules.mli
Gen_rules is too much of a dumping ground for stuff. Move the stuff related to installation (META files/.install files) to a new install_rules module.
Some notes:
* We don't really Archives to be a functor and can simply make it a set of functions. Didn't want to refactor too many things at once here.
* Do we need an `init` function in `Install_rules.Gen`? It could just be a module side-effect.
> Move installation and META rules to install_rules module

- src/odoc.ml
- src/super_context.ml
- src/super_context.mli
It longer has a reason to exist in super context. Since it doesn't access anything private to a super context anymore.
> Move SC.Doc to Odoc module

- src/build.ml
- src/build.mli
- src/gen_rules.ml
- src/install_rules.ml
- src/merlin.ml
- src/preprocessing.ml
- src/preprocessing.mli
- src/super_context.ml
- src/super_context.mli
It no longer needs to be inside Super_context.
Here is the diff between the old SC.PP module and the new preprocessing.ml file: https://gist.github.com/diml/eaf62f3fa4ae92231c841d193d67823f
> Extract SC.PP as Preprocessing

- src/inline_tests.ml
- src/lib.ml
- src/lib.mli
- src/odoc.ml
- src/scope.ml
- src/sub_system.ml
- src/sub_system_intf.ml
This PR does some refactoring that I need to allow to be generic over ppx drivers.
The first commit changes things in Lib so that hidden libraries are still instantiated as `Lib.t` values. This makes everything else much simpler.
The second commit allow sub-systems to access the `Lib.t` value they are attached to.
> Small lib improvements

- src/configurator/configurator.ml
- src/configurator/configurator.mli
- src/configurator/jbuild
- src/io.ml
- src/io.mli
- src/ocamlc_config.ml
- src/ocamlc_config.mli
- src/stdune/string.ml
- src/stdune/string.mli
- test/unit-tests/configurator/jbuild
- test/unit-tests/configurator/test_configurator.ml
Importing configurator into jbuilder (as discussed).
To consider:
* Should I bring back the various sexp functions? These didn't seem so useful and I should probably use the jbuilder combinator API to rewrite them.
> Import configurator

- src/install_rules.ml
- src/lib.ml
- src/lib.mli
DB.all will return duplicate libraries in cases when it has 2 names for the same
library. This fix changes all to return a set of values. This is to indicate and
guarantee the uniqueness.
> Fix DB.all returning duplicate libs

- CHANGES.md
- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/build_system.ml
- src/gen_rules.ml
- src/merlin.ml
- src/merlin.mli
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/github25/root/run.t
- test/blackbox-tests/test-cases/github568/jbuild
- test/blackbox-tests/test-cases/github568/lib1.opam
- test/blackbox-tests/test-cases/github568/lib2.opam
- test/blackbox-tests/test-cases/github568/run.t
Ignore errors raised during the generation of the .merlin
> Fix #51 & #568

- bin/main.ml
- src/gen_rules.ml
- src/gen_rules.mli
- src/install.ml
- src/install.mli
- src/install_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/jbuild_load.ml
- src/jbuild_load.mli
- src/main.ml
- src/main.mli
- src/package.ml
- src/package.mli
- src/super_context.ml
- src/super_context.mli
- src/utils.ml
- src/utils.mli
First step at privatizing some types. This would have been pretty useful for my work on odoc.
The pr does add some boilerplate, but I think it's justified because the types do clear up a lot. The biggest annoyance is having to switch all the module names everywhere. As I've mentioned in slack, having base style comparators would be really nice.
> Introduce package name private type

- test/blackbox-tests/test-cases/meta-gen/jbuild
- test/blackbox-tests/test-cases/meta-gen/run.t
This is incorrect as those aren't installed.
@diml this is a pretty serious bug that was discovered in https://github.com/mirage/ocaml-git/pull/280#issuecomment-370039966
I suppose the fix is to exclude these private names and include the .cm files in the libraries that depend on the private stuff.
I'm not really sure when this regression was introduced either. I recall this case working fine before. I wonder when this regression was introduced.
> META file includes private libraries

- CHANGES.md
- src/findlib.ml
For packages that are builtin, we check that least one of the archives is present.
> Add a simple workaround for #563

- CHANGES.md
- src/scheduler.ml
- test/blackbox-tests/test-cases/byte-code-only/run.t
- test/blackbox-tests/test-cases/c-stubs/run.t
- test/blackbox-tests/test-cases/copy_files/run.t
- test/blackbox-tests/test-cases/cross-compilation/run.t
- test/blackbox-tests/test-cases/gen-opam-install-file/run.t
- test/blackbox-tests/test-cases/github25/root/run.t
- test/blackbox-tests/test-cases/installable-dup-private-libs/run.t
- test/blackbox-tests/test-cases/intf-only/run.t
- test/blackbox-tests/test-cases/js_of_ocaml/run.t
- test/blackbox-tests/test-cases/menhir/run.t
- test/blackbox-tests/test-cases/multiple-private-libs/run.t
- test/blackbox-tests/test-cases/odoc-unique-mlds/run.t
- test/blackbox-tests/test-cases/odoc/run.t
- test/blackbox-tests/test-cases/redirections/run.t
- test/blackbox-tests/test-cases/scope-bug/run.t
- test/blackbox-tests/test-cases/scope-ppx-bug/run.t
- test/blackbox-tests/test-cases/select/run.t
> Reduce interleaving in the scheduler

- src/exe.ml
- src/exe.mli
- src/gen_rules.ml
- src/import.ml
- src/inline_tests.ml
- src/jbuild.ml
- src/jbuild.mli
- src/module.ml
- src/module.mli
- src/module_compilation.ml
- src/module_compilation.mli
- src/modules_partitioner.ml
- src/modules_partitioner.mli
- src/ocamldep.ml
- src/ocamldep.mli
- src/odoc.ml
- src/odoc.mli
- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
- src/preprocessing.ml
- src/preprocessing.mli
- src/stdune/ordering.ml
- src/stdune/ordering.mli
- src/sub_system_intf.ml
- src/super_context.ml
- src/utop.ml
Again, the coercions don't work so cleanly in 4.02.3. Should we also intern the module names?
> Introduce private type for module name

- CHANGES.md
- doc/jbuild.rst
- src/gen_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/lib.ml
- src/lib.mli
Let's consider the following case:
- library `a` is part of the workspace
- `a` depends on `b` which is only installed
- `b` depends on `c` which is both installed and present in the workspace
before beta18, this was an error. In beta18 it isn't an error anymore, this allows in particular to lint Base without having to create a big workspace. However the new behavior is confusing for users, so we restore the pre-beta18 behavior by default and add an option `allow_soft_conflicts` to get the beta18 behavior.
> Restore stronger check for overlapping libraries

- src/action.ml
- src/context.ml
- src/context.mli
- src/env.ml
- src/env.mli
- src/jbuild_load.ml
- src/process.ml
- src/process.mli
Extracted from my bisect PR. The environment handling is moved to its own module to hide the complexity of handling both forms of an env map. I'm not sure if the laziness is even necessary btw, seems like having a `type t = string array` should be good enough for most cases.
> Move env var handling outside of Context.t

- test/blackbox-tests/cram.mll
- test/blackbox-tests/jbuild
Since compiler support is a bit broken before 4.06
> Skip object tests for OCaml < 4.06

- CHANGES.md
- src/usexp/parser_automaton_internal.ml
- test/blackbox-tests/test-cases/exclude-missing-module/run.t
- test/blackbox-tests/test-cases/findlib/run.t
- test/blackbox-tests/test-cases/intf-only/run.t
- test/blackbox-tests/test-cases/misc/run.t
The start position of atoms wasn't saved by the parser.
> Fix locations reported by the parser

- src/lib.ml
- src/lib.mli
- test/blackbox-tests/test-cases/meta-gen/jbuild
- test/blackbox-tests/test-cases/meta-gen/run.t
- test/blackbox-tests/test-cases/private-public-overlap/run.t
ok @diml, the flag approach works well here. The only issue is that I don't know how to retrieve the name of the public dependency that's requiring the private dependency in the error message.
> Disallow public/private overlap

- src/configurator/configurator.ml
- src/configurator/jbuild
- src/stdune/io.ml
- src/stdune/io.mli
- src/stdune/jbuild
- src/stdune/stdune.ml
This allows configurator to drop the dependency on jbuilder itself. Unless the goal is to make stdune without IO, I don't see downsides.
> Move Io to stdune

- test/blackbox-tests/test-cases/private-public-overlap/optional/jbuild
- test/blackbox-tests/test-cases/private-public-overlap/run.t
Currently, a library marked (optional) will not build if it's public and has a
private dependency.
@diml I alluded to this case in slack. This behavior is wrong, but I think it should be allowed in cases where where we allow database overlaps. In which case we could indeed have a missing public library `foo` and a private library named `foo`.
> private/public tests with (optional)

- CHANGES.md
- doc/jbuild.rst
- src/build_system.ml
- src/build_system.mli
- src/jbuild.ml
- src/jbuild.mli
- src/super_context.ml
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/depend-on-the-universe/jbuild
- test/blackbox-tests/test-cases/depend-on-the-universe/run.t
This adds the `(universe)` dependency specification. This is used to specify that an action depend on everything in the universe. As a result, Jbuilder cannot cache the result of such an action and will instead re-run it every time.
The implementation uses a `_build/.universe-state` file that contains a counter that is incremented on each run.
> Allow to depend on the universe

- src/gen_rules.ml
- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
- src/scope.mli
- src/super_context.ml
Little fixes from my odoc PR. If the duplication of signatures in Ordered_set_lang is long in the tooth, we can always create an `_intf` module.
> Doc related fixes

- src/preprocessing.ml
- src/super_context.ml
- src/super_context.mli
This encoding will also be used by odoc so it's best to share it
> Move they '@' scope encoding to common module

- bin/main.ml
- src/action.ml
- src/action.mli
- src/build_interpret.ml
- src/build_interpret.mli
- src/build_system.ml
- src/build_system.mli
- src/context.ml
- src/context.mli
- src/env.ml
- src/env.mli
- src/super_context.ml
This is work extracted from my branch that allows users to run actions in the installed environment.
The first commit gets rid of passing the context optionally. I find that it's hard to debug why the context is missing when we aren't passing it explicitly. Now, it's much easier to grep for `~context:` and see what's happening to the flow.
The last commit makes the context available for all alias actions. This will be useful because we must know which context are we in to run in something in the installed env of that context.
> Tweaks to Actions

- src/usexp/usexp.ml
- src/usexp/usexp.mli
- test/blackbox-tests/test-cases/inline_tests/dune-file/jbuild
- test/blackbox-tests/test-cases/inline_tests/run.t
- test/unit-tests/jbuild
- test/unit-tests/sexp_tests.ml
The test in this PR shows that while the backends ends up being read and correctly interpreted, the generated .dune file incorrectly escapes the action field.
This problem seems to be present when serializing anything that might incorrectly interpreted as an Atom. A fix seems to be using a more robust check for valid atoms and restricting them to include comment characters, spaces, etc.
Here's one such valid function https://github.com/janestreet/sexplib0/blob/e4b0084877eb79e84c90afd14c07aff34ef619a4/sexp.ml#L60
cc @trefis @xclerc
> Extend backend tests to track the dune.sexp file generated

- src/gen_rules.ml
- src/install_rules.ml
- src/install_rules.mli
- src/jbuild.ml
- src/jbuild.mli
- src/lib.ml
- src/lib.mli
- src/odoc.boot.ml
- src/odoc.ml
- src/odoc.mli
- src/super_context.ml
- test/blackbox-tests/test-cases/gen-opam-install-file/jbuild
- test/blackbox-tests/test-cases/gen-opam-install-file/run.t
- test/blackbox-tests/test-cases/multiple-private-libs/run.t
- test/blackbox-tests/test-cases/odoc-unique-mlds/run.t
- test/blackbox-tests/test-cases/odoc/jbuild
- test/blackbox-tests/test-cases/odoc/run.t
This is yet another attempt at the documentation stanza. The code is still in a bit of a rough state, but it seems to be working.
Some notes about the implementation:
* The mld -> odoc, and cmti -> odoc pipelines are handled completely separately. See the `setup_*_library_odoc_rules`.
* The html pipeline for is done per package and all of its sub libraries.
* The uniqueness of mld's per packages is properly handled without the copying rule. Since we must gather this list statically before generating the package odoc rules anyway.
Some questions that I still have:
* The entry module stuff is still unclear to me. Since it's an .mld file, it will be generated (if missing), and installed for the entire package package. But this still leaves the issue of having an entry level doc for the sub …
> Documentation Stanza

- src/inline_tests.ml
- src/sexp.ml
- src/sexp.mli
- test/blackbox-tests/test-cases/inline_tests/run.t
Encode optional fields as records where optional keys that are None will be
omitted in the resultant sexp. This will match reading the keys back with field_o
> Fix encoding of inline_tests

- src/inline_tests.ml
- src/sexp.ml
- src/sexp.mli
- src/sub_system.ml
- src/sub_system_intf.ml
Split the select_backends between two functions:
- one for backends that support extensions
- one for backends that support replacement
it might be possible to support both at once, but for now this is enough and it's simpler.
> Rework the sub system select

- src/ocaml-config/ocaml_config.ml
We should account for this in ocaml_config.
Fix #637
> assembler might be missing

- src/stdune/map.ml
We should show the key that came earlier in the list first. The error in #638 confused me initially.
> Tweak order in Map.of_list error

- src/findlib.ml
- src/import.ml
- src/meta.ml
- src/meta.mli
- test/unit-tests/tests.mlt
It's always simplified anyway. If we're simplifying some things a late too eagerly, we could also make the simplification itself as lazy.
> Change Meta.load to return the simplified meta

- src/context.ml
- src/env.ml
- src/env.mli
Fix #625 
I'm not sure if my approach or the much simpler one where we simply we t.env is the right one. It feels a bit yicky to just throw away the old PATH so I did the slightly more complicated thing.
> Set the target's PATH when cross compiling

- CHANGES.md
- src/gen_rules.ml
- src/odoc.boot.ml
- src/odoc.ml
- src/odoc.mli
We should pass directories where we store .odoc files instead.
cc @trefis
> Don't pass library include flags to odoc

- src/process.ml
Minor tweak - I was viewing a log using Vim's AnsiEsc plugin which was (erroneously) colouring the whitespace.
> Don't color the whitespace in --display=short

- jbuild-workspace.dev
We should use the latest point release for a particular release
> Use 4.06.1 in jbuild-workspace.dev

- src/configurator/configurator.ml
- src/stdune/exn.ml
- src/stdune/exn.mli
Otherwise uncaught by configurator are hard to debug. I know there's `raise_with_backtrace` now, but it's a bit too new for us.
Review from anyone here suffices.
> Print backtrace in case of uncaught exception

- src/gen_rules.ml
- src/super_context.ml
- src/super_context.mli
it was introduced to avoid generaitng a needless .merlin file for utop levels.
But now that we have a better mechanism for that, it serves no purpose.
Fix #684 . On second glance, this argument definitely doesn't seem useful anymore.
> Remove ~has_dot_merlin flag

- src/configurator/jbuild
- src/ocaml-config/jbuild
- src/ocaml-config/ocaml_config.mli
- src/stdune/caml/caml.ml
- src/stdune/caml/jbuild
- src/stdune/jbuild
- src/usexp/jbuild
- src/usexp/usexp.mli
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/configurator/c_test/jbuild
- test/blackbox-tests/test-cases/configurator/c_test/run.ml
- test/blackbox-tests/test-cases/configurator/config/jbuild
- test/blackbox-tests/test-cases/configurator/config/run.ml
- test/blackbox-tests/test-cases/configurator/import-define/jbuild
- test/blackbox-tests/test-cases/configurator/import-define/run.ml
- test/blackbox-tests/test-cases/configurator/run.t
This is now possible after the recent improvements to the black box tests.
One slightly undesirable thing is that it also forces us to declare all the sub libraries as public as well. But I think that this is basically unavoidable and will come eventually. I don't think that the other libraries should delay the release of configurator.
@dra27 is there a convenient string valued defined we can use in the tests (for completeness).
> Add a blackbox test suite for configurator

- CHANGES.md
- bin/main.ml
Otherwise the tests end up running with `-j something` if you have `(jobs ...)` in the configuration file.
> Do not load the user configuration file when INSIDE_DUNE is set

- src/configurator/v1.ml
- src/context.ml
- test/blackbox-tests/test-cases/configurator/config/run.ml
- test/blackbox-tests/test-cases/configurator/run.t
The simplest way of obsoleting the `-ocamlc` flag. Some notes:
* We are likely to still want to keep `-ocamlc` for debugging, but ideally, warn the user that this isn't necessary. Should we use the `INSIDE_DUNE` variable in configurator to issue a warning when this flag is passed?
* Ideally, `DUNE_CONFIGURATOR` would be an s-expression containing all the config info dune wants to pass to configurator. But there's a couple of issues with this. The first one is that it's tough to write an sexp parser in configurator since the `Sexp` module is in dune itself. And the second issue is that we'd prefer to share the configuration record, but that would require a dependency between dune and configurator. To solve this, I guess we could make `Sexp` part of usexp (or a separate, internal lib) and …
> Pass ocamlc explicitly to configurator using DUNE_CONFIGURATOR

- src/configurator/v1.ml
- src/configurator/v1.mli
- test/blackbox-tests/test-cases/configurator/import-define/run.ml
- test/blackbox-tests/test-cases/configurator/run.t
A user can now define their own macros to use with extracting compile time info.
We need this ability for proper tests in the #678 to make sure that extracting string constants works the same way. `__func__` doesn't work like a proper macro because it isn't expanded by the preprocessor.
> Add ?macros argument when import constants

- src/action.ml
- src/string_with_vars.ml
- src/string_with_vars.mli
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/null-dep/jbuild
- test/blackbox-tests/test-cases/null-dep/run.t
Jbuilder incorrectly infers ${null} to be a target
> Add test to show that jbuilder mishandles ${null}

- CHANGES.md
- src/action.ml
- src/action_intf.ml
- src/build.ml
- src/build.mli
- src/ocamldep.ml
- test/blackbox-tests/jbuild
- test/blackbox-tests/test-cases/github660/explicit-interfaces/jbuild
- test/blackbox-tests/test-cases/github660/explicit-interfaces/lib.ml
- test/blackbox-tests/test-cases/github660/explicit-interfaces/lib.mli
- test/blackbox-tests/test-cases/github660/explicit-interfaces/lib_sub.ml
- test/blackbox-tests/test-cases/github660/explicit-interfaces/lib_sub.mli
- test/blackbox-tests/test-cases/github660/explicit-interfaces/main.ml
- test/blackbox-tests/test-cases/github660/no-interfaces/jbuild
- test/blackbox-tests/test-cases/github660/no-interfaces/lib.ml
- test/blackbox-tests/test-cases/github660/no-interfaces/lib_sub.ml
- test/blackbox-tests/test-cases/github660/no-interfaces/main.ml
- test/blackbox-tests/test-cases/github660/run.t
- test/blackbox-tests/test-cases/menhir/run.t
This work in progress PR is an attempt to fix #660.
@diml let me know how we should do that. From what I understood, the plan is to compute transitive dependencies of modules, so in the linked bug, add a dependency from `Main` to `Lib_sub`?
> Compute transitive modules depencies

- src/configurator/configurator.ml
- src/configurator/extract_obj.mli
- src/configurator/extract_obj.mll
- src/configurator/jbuild
- src/configurator/v1.ml
- src/configurator/v1.mli
Do not run compiled programs to extract #define's
Running a program to extract a #define value doesn't work in a cross compilation
environment. Nevertheless, we can extract #define constants by invoking the
preprocessor directly using the -E flag and doing some parsing to extract
values.
As a consequence, we now ignore the link_flags argument. As we're not going to
be linking any executables. We aren't removing the argument altogether since
it's technically a breaking change. The user will instead see a deprecation
warning when ~link_flags is provided.
@dra27 would be good to hear your opinion about this and how well would this hack work on Windows.
cc @Chris00 because I know he was interested in implementing this in the original configurator
cc @avsm b/c it's a general cross compilation …
> Use Whitequark's Code to extract #define's and other compile time info from object files

- src/arg_spec.ml
- src/arg_spec.mli
- src/build.ml
- src/build.mli
- src/gen_rules.ml
- src/menhir.ml
- src/module_compilation.ml
- src/odoc.ml
This PR replaces the `?extra_targets` argument of `Build.run` by `Arg_spec.Hidden_targets`. The latter allows to specify targets that do not appear on the command line through `Arg_spec`, similarly to `Hidden_deps`. I find it a bit more homogeneous this way.
> ?extra_targets --> Arg_spec.Hidden_targets

- test/blackbox-tests/cram.mll
- test/blackbox-tests/jbuild
The ocamlc config is passed courtesy of configurator anyway
> Remove -ocamlv arg from cram tests

- test/blackbox-tests/cram.mll
- test/blackbox-tests/test-cases/configurator/config/run.ml
This one slip because we don't test against all compilers in CI
> Configurator test fix

- CHANGES.md
- src/build_system.ml
This fixes a bug reported by @samoht on slack
> Make sure all_lib_deps_by_context doesn't report invalid contexts

- test/blackbox-tests/test-cases/output-obj/jbuild
I found this while debugging `-output-complete-obj` on FreeBSD
> Fix flags in output-obj test

- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/jbuild.inc
- test/jbuild
Mark more tests with external deps and extend the no-deps test target.
> Test tweaks

- src/context.ml
- src/env.ml
- src/env.mli
- src/findlib.ml
- src/findlib.mli
- src/import.ml
- src/interned.ml
- src/interned.mli
- test/unit-tests/jbuild
- test/unit-tests/tests.mlt
- test/unit-tests/toolchain.d/tlc.conf
This is useful for configuring PKG CONFIG for cross compilation.
@diml not sure if this is the entirely correct approach so I haven't done a full implementation yet (tests are still missing)
> Allow setting ENV vars in findlib.conf per toolchain

- CHANGES.md
- src/file_tree.ml
- src/file_tree.mli
This way ignored sub-directories are only traversed if the user explicitly references them in a jbuild file or on the command line.
Fix #228
Fix #718
> Scan the file-system lazily

- src/dep_path.ml
- src/dep_path.mli
- src/gen_rules.ml
- src/inline_tests.ml
- src/jbuild.ml
- src/jbuild.mli
- src/js_of_ocaml_rules.ml
- src/modules_partitioner.ml
- src/modules_partitioner.mli
- src/preprocessing.ml
- src/super_context.ml
- src/super_context.mli
- src/utils.ml
- src/utils.mli
And use more precise locations instead. This is in preparation of supporting `dune` files; since we will accept both `dune` and `jbuild` files, this function will become problematic.
> Get rid of jbuild_file_in

- CONTRIBUTING.md
- LICENSE.md
- dune.opam
This PR changes the license of Dune to MIT and add a CONTRIBUTING files explaining that contributors must certify that the [DCO](http://developercertificate.org/) apply to their work. Previously the license was Apache and we were asking contributors to sign the Jane Street CLA.
At the moment we are just waiting for the CLA from a couple of past contributions and then we will be ready to do the switch.
> Switch from Apache+CLA to MIT+DCO

- bin/main.ml
- src/action.ml
- src/build_system.ml
- src/config.ml
- src/context.ml
- src/jbuild_load.ml
- src/log.ml
- src/main.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/utils.ml
Always route these cases through Path.build_dir.
I also got rid of Path.relative_to_buil_dir as I don't think it buys as much anymore.
> Remove all hard coded uses of "_build"

- test/unit-tests/path.mlt
It's worth adding tests for these as the behavior might change. Some things that I'd like to consider:
* `Path.(append build_dir (relative build_dir "bar"))` should return `Path.relative build_dir "bar"`
* `Path.append source_dir build_dir` should result in an error (there are better ways to go from `_build/foo/bar` to `foo/bar`).
* Mixing external paths and build paths should also perhaps result in an error
> Unit tests for current Path.append behavior

- src/build_system.ml
- src/build_system.mli
- src/super_context.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/bad-alias-error/absolute-path/jbuild
- test/blackbox-tests/test-cases/bad-alias-error/outside-workspace/jbuild
- test/blackbox-tests/test-cases/bad-alias-error/run.t
This is useful to catch bugs in implementing #744 
The 2nd commit feels a bit heavy handed but it's nice to have the extra safety of this. Another approach to help maintain this invariant would be to have some phantom types for paths to distinguish build vs. otherwise.
> Alias0.dir is always in build_dir

- src/build_system.ml
- src/file_tree.ml
- src/file_tree.mli
- src/jbuild_load.ml
This factorizes a bit the code and will make adding support for `.dune-fs` files simpler, since the user will be allowed to make a `dune` file be raw data
> Add File_tree.Dir.dune_file

- src/stdune/path.ml
- test/unit-tests/path.mlt
Just a little safety with what we're deleting. Relevant given the recent camlp5 issue.
I also had some close calls with this in development myself from all the path tweaking.
> Rm -rf safety

- test/unit-tests/path.mlt
This function returns false on Path.build_dir which is somewhat surprising.
@diml, originally I thought this was just a bug, but it seems like we're relying on this to make sure that `_build/.universe-state` is built without any explicit rule for doing so. E.g:
```ocaml
let universe = Path.relative Path.build_dir ".universe-state"
assert (not (Path.is_in_build_dir (Path.parent universe)))
```
This seems a bit odd to me, but in case we should document this in a test if we indeed rely on this.
> Path.is_in_build_dir test

- src/menhir.ml
This is purely for the sake of readability;
there should be no change in functionality.
Code is now shared between the case where [--base]
is used and the case where it isn't.
> Cleanup of [src/menhir.ml].

- src/dune_project.ml
- src/dune_project.mli
- src/file_tree.ml
- src/file_tree.mli
- src/jbuild.ml
- src/jbuild.mli
- src/jbuild_load.ml
(resurrection of #763)
This PR does two things:
- it slightly change `Dune_project.t` to allow it to encode jbuilder project as well
- it construct `Dune_project.t` values in `File_tree` and associate a project to each `File_tree.Dir.t` node
This will make it easier to handle versioning of Dune files since we can quickly find out what project a directory is part of. This also simplifies the code in Jbuild_load.
> Collect projects in the file tree

- src/dune_project.ml
- src/dune_project.mli
- src/install_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/lib.ml
- src/scope.ml
- src/scope.mli
- src/stdune/string.ml
- src/stdune/string.mli
- src/super_context.ml
- src/super_context.mli
- test/blackbox-tests/test-cases/merlin-tests/run.t
- test/blackbox-tests/test-cases/ppx-rewriter/run.t
This PR refactors a bit the representation of projects/scopes names. With Dune, we can have several anonymous projects, so we encode that in the type. After this PR, I will do another one to get rid of `Jbuild.Scope_info`, since we can now replace it by just `Dune_project`.
Moving forward, maybe we should also change a bit the terminology in the manual to only talk about projects, since that maps a bit better to the real world.
> Refactor Jbuild.Scope_info.Name and Dune_project.name

- src/file_tree.ml
- src/stdune/path.ml
- src/stdune/path.mli
- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/github764/run.t
- test/blackbox-tests/test-cases/github764/sample-exe/dune
- test/blackbox-tests/test-cases/github764/sample-exe/foo.ml
Fix #764
@diml any way to add tests for this? I tried adding Louis' example but dune errors out too early when it sees the symlink before actually running any tests.
> Detect circular sym links

- CHANGES.md
- src/stdune/sexp.ml
- test/unit-tests/dune
- test/unit-tests/sexp.mlt
When a field is present multiple times in a record, dune ignores the first occurrences. This PR exposes and fix this bug.
> Fix sexp record bug

- src/action.ml
- src/process.ml
- src/stdune/path.ml
- src/stdune/path.mli
- test/blackbox-tests/test-cases/inline_tests/run.t
- test/unit-tests/path.mlt
@diml why is it necessary to add the `./` prefix?
Also, what do you think of getting rid of this function and simply having `Process.run` add the `./` if necessary after the `to_string` conversion. I belive that's the only place where we use this function anyway.
> Add tests for reach_for_running

- src/stdune/sexp.ml
- src/stdune/sexp.mli
- test/unit-tests/sexp.mlt
This PR adds the necessary support in `Sexp.Of_sexp` for fields that might appear multiple times. This is to support `(using <plugin> <version>)` in `dune-project` since they might appear multiple times. This PR is based on #779.
> Allow to define that can appear multiple times

- CONTRIBUTING.md
- LICENSE.md
- dune.opam
> This PR changes the license of Dune to MIT and add a CONTRIBUTING files explaining that contributors must certify that the DCO apply to their work. Previously the license was Apache and we were asking contributors to sign the Jane Street CLA.
> At the moment we are just waiting for the CLA from a couple of past contributions and then we will be ready to do the switch.
#737
> Mit+DCO [WIP]

- src/action.ml
- src/arg_spec.ml
- src/build.ml
- src/build_interpret.ml
- src/build_system.ml
- src/super_context.ml
- src/utils.ml
They save very little in terms of typing but grepping harder than it should be
> Remove aliases of Path.{Set,Map}

- src/merlin.ml
- test/blackbox-tests/test-cases/github759/run.t
- test/blackbox-tests/test-cases/merlin-tests/run.t
Generate the string all at once and reuse buffer. I'm not sure how much this helps performance since the old approach wasn't slow. But this piece of code does run on 0 rebuilds so it's worth tweaking. Also, this cleanup makes it easier to fix the order of paths following the symbolic path fix.
> Speed up merlin generation

- src/stdune/path.ml
The former functions are optimized away while the latter isn't.
> Use Sys.{win32,cygwin} rather than Sys.os_type

- .travis-ci.sh
- bin/dune
- doc/dune
- doc/dune.inc
- doc/update-jbuild.sh
- dune.opam
- jbuilder.descr
- jbuilder.opam
- vendor/boot/opamBaseParser.ml
This should help with #792. Now when running `opam pin add jbuilder --dev`, the installation fails if dune is not installed with the following message:
```
=-=- jbuilder.transition troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> Jbuilder has been renamed and the jbuilder package is now a transition package.
=> Use the dune package instead.
=> 
=> If you want to try the development version of Dune before the 1.0.0 is released, run the following command:
=> 
=> $ opam pin add dune https://github.com/ocaml/dune.git
```
> Add a jbuilder transition package

- doc/usage.rst
Hi!
This clarifies the use case. This replaces the emacs flag with something more likely to be used in a shell session: implicit bindings.
Thanks!
> Add an example for jbuilder utop

- src/build_system.ml
- src/utils.ml
- src/utils.mli
It's much faster. On my machine, null builds of the Jane Street workspace go from ~2.7s to ~1.9s.
> Use Marshal for the incremental and digest databases

- src/file_tree.ml
Hi!
When a symlink loop is detected, the following message is printed:
> Path X has already been scanned. Cannot scan it again through symlink Y
However, the actual symlink that is displayed depends on the order in with `readdir` outputs the contents (which depends on FS internals).
This sorts the directory list so that the message is deterministic.
It can be tested by adding for example a `List.rev` call after `Path.readdir`: the affected version will return a different version in the `github764` test.
Thanks!
> Make "path already scanned" message deterministic

- src/action.ml
- src/build_system.ml
- src/file_tree.ml
- src/stdune/path.ml
- src/stdune/path.mli
As `Sys.readdir`, it returns entries in an nondeterministic order. This can cause problems if caller relies on the list being sorted.
See #820.
Thanks!
> Rename Path.readdir to Path.readdir_unsorted

- src/action.ml
- src/action.mli
- src/installed_dune_file.ml
- src/ordered_set_lang.mli
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- src/syntax.ml
- src/syntax.mli
@diml we can change `val t` to `t_of_sexp` everywhere if you'd like. I also prefer the symmetric convention.
> Move sexpable signature to Stdune.Sexp

- CHANGES.md
- doc/project-layout-specification.rst
- src/file_tree.ml
- src/usexp/lexer.mli
- src/usexp/lexer.mll
- src/usexp/usexp.ml
- src/usexp/usexp.mli
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/block-strings/dune
- test/blackbox-tests/test-cases/block-strings/run.t
- test/unit-tests/sexp.mlt
This PR proposes two changes in the syntax of dune files. The syntax of jbuild files is untouched.
These were pretty much never used and they make the lexical conventions of the language more complicated. I think end of line comments are enough.
It is currently painful to write blocks of text in dune files as there is no syntax for raw strings where things don't need to be escaped. I find the usual syntax used in programming languages for raw strings quite painful as it's impossible to indent blocks of text properly. This PR proposes a syntax for *block* or *end of line* strings which solves this problem.
The syntax is as follow: everything that appears after a `"\|` on a line is a string. If the next line starts with spaces and `"\|` again, it is the continuation of the string. For …
> Block strings + remove block/sexp comments

- src/gen_rules.ml
- src/inline_tests.ml
- src/module.ml
- src/module.mli
- src/preprocessing.ml
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- src/utop.ml
This PR makes `Module.t` private and adds `Module.make`. The code is a bit nicer overall and  we can enforce that at least one of `impl` or `intf` is set.
One difference is that now `Module.make` always computes `obj_name`, even if it's sometimes never used. However I think the API is better this way.
/cc @fpottier
> Make Module.t private and add Module.make

- src/preprocessing.ml
For the jbuild method, we need to keep the last element last. I found this while benching master with the janestreet workspace.
> Fix generation of the ppx key for jbuild directories

- CHANGES.md
- src/odoc.ml
- test/blackbox-tests/test-cases/multiple-private-libs/run.t
- test/blackbox-tests/test-cases/odoc/run.t
private-doc needed to collect the html alias of each library rather than the odoc alias. The rest are just small refactorings.
@diml I think I addressed the comment that you've left for me in the source. Failing when the transitive closure is absent indeed makes sense. Even if we can still technically continue and generate suboptimal docs.
There are still many inefficiencies abound in the doc generation, but I'm thinking that this isn't an issue for people in practice. As long as the rules minimize the weight they add on normal builds.
> Refactor odoc generation and fix the private doc alias

- src/binary_kind.ml
- src/binary_kind.mli
- src/jbuild.ml
- src/jbuild.mli
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/no-installable-mode/private/jbuild
- test/blackbox-tests/test-cases/no-installable-mode/public/jbuild
- test/blackbox-tests/test-cases/no-installable-mode/run.t
- test/unit-tests/dune
- test/unit-tests/jbuild.mlt
There is a bad interaction between `shared-object` and `package`: it makes it somehow forgets about `public_name`.
I'm not too sure what's going on here - it seems like this is caused somewhere in `common_v1` in `jbuild.ml` but help to fix this would be appreciated.
> Improve error message when attempting to install a shared object

- test/blackbox-tests/test-cases/quoting/filename-space/dune
- test/blackbox-tests/test-cases/quoting/filename-space/foo bar.txt
- test/blackbox-tests/test-cases/quoting/run.t
(echo "${read:foo bar}") vs. (echo ${read:foo bar}) handles the argument
differently
> Add test for behavior of templates and arguments with spaces

- dune-project
- src/dune_project.ml
- test/blackbox-tests/test-cases/dune-ppx-driver-system/dune-project
It seems better to start with `1.0`.
> Set dune language version to 1.0

- src/usexp/lexer.mll
- test/unit-tests/sexp.mlt
Things like `\a` are no longer allowed. Before they would be interpreted as a literal `\a`. This will allow to introduce new escape sequences in the future if needed.
> Strengthen the lexing of escape sequences

- src/action.ml
- src/dune_project.ml
- src/dune_project.mli
- src/file_tree.ml
- src/inline_tests.ml
- src/installed_dune_file.ml
- src/jbuild.ml
- src/preprocessing.ml
- src/stanza.ml
- src/stanza.mli
- src/stdune/path.ml
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- src/workspace.ml
This PR changes the Sexp.Of_sexp API to use the same `list_parser` monad to parse both records and constructors. I find the new API simpler as there are less functions and operators. Additionally, the parsing code is a bit nicer as well since the variable to which the result is bound is closer to the delcaration of the argument.
i.e. instead of:
```ocaml
sum 
[ cstr name (arg1 @> arg2 @> arg3 @> nil) (fun x y z -> ...) ]
```
we now have:
```ocaml
sum
[ name,
(arg1 >>= fun x ->
arg2 >>= fun y ->
arg3 >>= fun z ->
return (...))
]
```
> Refactor a bit the Of_sexp API

- src/action.ml
- src/build_system.ml
- src/config.ml
- src/context.ml
- src/dune_project.ml
- src/dune_project.mli
- src/file_tree.ml
- src/installed_dune_file.ml
- src/jbuild.ml
- src/jbuild.mli
- src/ordered_set_lang.ml
- src/preprocessing.ml
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- src/vfile_kind.ml
- src/workspace.ml
- test/unit-tests/jbuild.mlt
- test/unit-tests/sexp.mlt
This PRs adds a user context that is passed around to S-expression parsers. It also changes the code so that the `Dune_project.t` value is passed through this context. In particular, this allows to make the `stanza_parser` field immutable.
> User context in S-expression parsers

- src/action.ml
- src/build_system.ml
- src/config.ml
- src/context.ml
- src/dune_project.ml
- src/dune_project.mli
- src/file_tree.ml
- src/inline_tests.ml
- src/installed_dune_file.ml
- src/jbuild.ml
- src/jbuild.mli
- src/ordered_set_lang.ml
- src/preprocessing.ml
- src/stdune/map.ml
- src/stdune/map_intf.ml
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- src/stdune/univ_map.ml
- src/stdune/univ_map.mli
- src/syntax.ml
- src/syntax.mli
- src/vfile_kind.ml
- src/workspace.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/syntax-versioning/run.t
- test/unit-tests/jbuild.mlt
- test/unit-tests/sexp.mlt
This PRs refactors the way syntax versionning is handled. For every syntax (language, extension, sub-system) we must create a `Syntax.t` value that holds:
- the name and description of the syntax
- the supported versions
This `Syntax.t` value is attached:
- to languages registered via `Dune_project.Lang.register`
- to extensions registered via `Dune_project.Extension.register`
- to sub-systems
If the version of two components is managed by the same syntax, we can simply reuse the same `Syntax.t` value. For instance the versionning of `ppx.driver` or `inline_tests` fields is controlled by the version of the dune language, so they simply reuse the same syntax.
When parsing dune files, the version of each syntax in use is passed via the user context of S-expressions parser. The `Syntax` …
> Complete handling of syntax versioning

- src/dune_project.ml
- src/loc.ml
- src/stdune/sexp.ml
- src/usexp/atom.ml
- src/usexp/atom.mli
- src/usexp/lexer.mli
- src/usexp/lexer.mll
- src/usexp/usexp.ml
- src/usexp/usexp.mli
- test/unit-tests/sexp.mlt
- test/unit-tests/sexp_tests.ml
Atoms can now be constructed and pretty printed with a syntax = Jbuild | Dune.
The syntax controls validation that will be used to make sure we are printing
something/reading valid
An issue here is that I'm hard coding the dune syntax in a couple of places where we should probably be flexible - like the sub systems file. But it seems to work.
> Dune & Jbuild validation for atoms

- CHANGES.md
- doc/jbuild.rst
- src/jbuild.ml
- test/blackbox-tests/test-cases/dune-ppx-driver-system/dune
- test/blackbox-tests/test-cases/dune-ppx-driver-system/run.t
- test/blackbox-tests/test-cases/js_of_ocaml/bin/dune
- test/blackbox-tests/test-cases/js_of_ocaml/lib/dune
- test/blackbox-tests/test-cases/merlin-tests/lib/dune
- test/blackbox-tests/test-cases/meta-gen/dune
I never really liked the current syntax. This PR improves the syntax of `(pps ...)` as follow:
- old syntax: `(pps (ppx1 -arg1 ppx2 (-foo x)))`
- new syntax: `(pps ppx1 -arg ppx2 -- -foo x)`
> Improve the syntax of ppx rewriters and flags

- doc/jbuild.rst
- src/compilation_context.ml
- src/compilation_context.mli
- src/gen_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/module_compilation.ml
- src/which_program/dune
- src/which_program/dune-impl/dune
- src/which_program/gen-no-keep-locs
- src/which_program/jbuilder-impl/dune
The build on OCaml 4.02 is broken since #920. The issue is that `-no-keep-locs` is not supported in 4.02. To fix the issue this PR adds a field `(no_keep_locs)` to library stanzas which emulates the behavior of `-no-keep-locs` in 4.02.
> Fix the build on 4.02 by emulating -no-keep-locs

- CHANGES.md
- bin/main.ml
- doc/jbuild.rst
- doc/terminology.rst
- doc/usage.rst
- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/build_system.ml
- src/build_system.mli
- test/blackbox-tests/test-cases/aliases/run.t
This PR adds a special `default` alias which become the new default target.
When the `default` alias is not explictely defined in a directory, it is implicitely defined as follow:
```scheme
(alias
(name default)
(deps (alias_rec install)))
```
Otherwise the user definition is used.
The default target is changed from building recursively the alias `install` to building the `default` only in the current directory. This allows to redefine what `dune build` in different directories.
In order to represent that, a new syntax is added to the command line: `@@x` means building alias `x` in the current directory. In the end `dune build` is equivalent to `dune build @@default`.
`dune build -p x` still means `dune build -p x @install`. This is done by adding a command line option `--default-target` …
> Add a default alias

- test/blackbox-tests/test-cases/gen-opam-install-file/run.t
--display short isn't useful for many tests.
> Make install tests less verbose

- CHANGES.md
- plugin/jbuild_plugin.mli
- src/jbuild_load.ml
`#require` was restricted to `#require "unix"` a while ago as allowing files in OCaml syntax to load anything didn't seem right. We initially kept `"unix"` as some projects were using it, but we can now forbid `#require` entirely in `dune` files.
Forbidding `unix` improves portability.
> Forbid #require in dune files in OCaml syntax

- CHANGES.md
- bin/main.ml
- src/action.ml
- src/build_system.ml
- src/install.ml
- src/install.mli
- src/install_rules.ml
- src/stdune/io.ml
- src/stdune/io.mli
- src/stdune/path.ml
- vendor/boot/opamParserTypes.ml
opam is currently not mandatory to use dune, however one still needs the external `opam-installer` binary in order to run `dune install` or `dune uninstall`. This is annoying, especially since this tool is quite simple.
In order to make dune more self-contained, this PR reimplements `dune install` and `dune uninstall` without calling out to `opam-installer`.
> Do not use opam-installer to copy files

- CHANGES.md
- doc/dune-files.rst
- src/install.ml
- src/install.mli
> Add the lib_root and libexec_root install sections

- src/install_rules.ml
- src/installed_dune_file.ml
- src/installed_dune_file.mli
- src/jbuild.ml
- src/jbuild.mli
- src/lib.ml
- src/lib.mli
- src/stanza.ml
- src/stanza.mli
- src/usexp/loc.ml
- src/usexp/loc.mli
- src/usexp/usexp.ml
- src/usexp/usexp.mli
- test/blackbox-tests/test-cases/inline_tests/run.t
Fix #909 
This is still WIP because I should really be saving the syntax version rather than the Jbuild vs. Dune version in the Info files. But this PR is still useful for initial review.
One thing that I'm wondering about is we should still generate the per subsystem versions in syntax `(1, 0)`. Seems like jbuilder will not be able to load .dune files generated by dune anyway because of that initial 2.0 language.
> Subsystem versioned

- doc/migration.rst
- src/install_rules.ml
Technically, we still support JBUILDER_GEN. Should we be a bit more thorough in the deprecation here? The issue is that I'm not sure how to get the dune_project from the package.
> Rename JBUILDER_GEN to DUNE_GEN

- CHANGES.md
- bin/main.ml
- doc/usage.rst
- src/dune_project.ml
- src/dune_project.mli
- src/main.ml
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- src/watermarks.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/output-obj/run.t
- test/blackbox-tests/test-cases/subst/dune-project
- test/blackbox-tests/test-cases/subst/file.ml
- test/blackbox-tests/test-cases/subst/file.ml.in
- test/blackbox-tests/test-cases/subst/foo.opam
- test/blackbox-tests/test-cases/subst/run.t
Projects are better defined with dune, so we don't need the automatic project name detection jbuilder was doing and can simply read the dune-project file. Additionally, since `dune subst` is only meant to be called from opam files, this PR simplify this command a bit so that it doesn't looks up the root of the workspace. This fix #954 which was due to users often forgetting to pass `"-p" name` to the `dune subst` invocation.
> Adapt the behavior of dune subst for dune projects

- src/inline_tests.ml
- src/pform.ml
- src/pform.mli
- src/string_with_vars.ml
- src/string_with_vars.mli
- src/super_context.ml
- test/blackbox-tests/test-cases/dep-vars/dune
- test/blackbox-tests/test-cases/dep-vars/jbuild/jbuild
- test/blackbox-tests/test-cases/dep-vars/run.t
- test/blackbox-tests/test-cases/shadow-bindings/dune
- test/blackbox-tests/test-cases/shadow-bindings/run.t
I went a bit too far with merging the maps for variables and macros and as a result expansion doesn't work well when the user define a variable with the same name as a macro. This PR fixes this by splitting the maps for variables and macros inside `Pform.Map.t`. It does a couple of other simplification/cleanups as well.
> Pforms fixes

- doc/dune-files.rst
The `.h` extension should not be present in `install_c_headers`.
> Fix the doc for `install_c_headers`

- CHANGES.md
- doc/dune-files.rst
- doc/migration.rst
- src/jbuild.ml
- src/menhir.ml
- src/pform.ml
- src/preprocessing.ml
- test/blackbox-tests/test-cases/aliases/src/dune
- test/blackbox-tests/test-cases/aliases/src/foo/bar/dune
- test/blackbox-tests/test-cases/aliases/src/foo/baz/dune
- test/blackbox-tests/test-cases/inline_tests/dune-file/dune
- test/blackbox-tests/test-cases/inline_tests/run.t
- test/blackbox-tests/test-cases/shadow-bindings/dune
There are two notions of root in dune:
- the root of a project, which is the first parent directory to contain a `dune-project` file (or at least one `<package>.opam` for compatibility with jbuilder)
- the root of the workspace
The latter is often equal to the former, expect when a package is vendored. Looking at the dune-universe, many projects are currently using `${ROOT}` when they should really be using `${SCOPE_ROOT}`. `${SCOPE_ROOT}` was renamed `%{project_root}` in dune. To make things even more explicit, this PR renames `%{root}` to `%{workspace_root}`.
> Rename %{root} to %{workspace_root}

- CHANGES.md
- src/gen_rules.ml
- src/inline_tests.ml
- src/install_rules.ml
- src/module.ml
- src/module.mli
- src/module_compilation.ml
- src/ocamldep.ml
- src/preprocessing.ml
- src/preprocessing.mli
- src/stdune/path.ml
- src/super_context.ml
- src/super_context.mli
- src/utop.ml
- test/blackbox-tests/test-cases/dune-ppx-driver-system/run.t
- test/blackbox-tests/test-cases/js_of_ocaml/run.t
- test/blackbox-tests/test-cases/ppx-rewriter/run.t
- test/blackbox-tests/test-cases/private-public-overlap/run.t
- test/blackbox-tests/test-cases/reason/run.t
- test/blackbox-tests/test-cases/scope-ppx-bug/run.t
This PR moves all pre-processed files to the object directory. This is the last blocker to offer first class support for multi-directory libraries.
It changes the code as follow:
- systematically pass `-intf-suffix <extension-of-the-implementation-file>` when compiling implementation files. This forces the compiler to read the cmi file rather than create it. Normally the compiler checks that the .mli file is present, however now the implementation and interface files might no longer be in the same directory
- simplify the extension of ast files (ppx or reason). This is allowed by the previous point
- make the `name : string` field of `Module.File` be `path : Path.t` instead. This simplifies the code quite a bit
- put all the generated ast files in the object directory
I added a changelog …
> Move pp files to obj dir

- src/action.mli
- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
- src/pform.ml
- src/pform.mli
- src/string_with_vars.ml
- src/string_with_vars.mli
- src/super_context.ml
This is a preparatory PR for making OSL allow forms such as `%{read:..}` work. There's no functional difference, but it does allow expanding values into OSL in a more consistent way.
> Refactor var expansion

- src/build_system.ml
We don't need to take the union with the file tree given that the targets are already a superset of the files in the source tree.
> Simplify Build_system.eval_glob

- src/dune
- src/jbuild.ml
- src/let-syntax/lexer.mll
- src/stdune/sexp.ml
- src/stdune/sexp.mli
This PR switches jbuild.ml to the let%map syntax and start using more applicative constructs rather than monadic ones. The result is that the parsing is often more clearly separated from the processing code.
> Use let%map in jbuild.ml

- CHANGES.md
- src/gen_rules.ml
- src/preprocessing.ml
- src/preprocessing.mli
- src/stdune/path.ml
- src/stdune/path.mli
- test/blackbox-tests/test-cases/dune-ppx-driver-system/run.t
- test/blackbox-tests/test-cases/js_of_ocaml/run.t
- test/blackbox-tests/test-cases/ppx-rewriter/run.t
- test/blackbox-tests/test-cases/private-public-overlap/run.t
- test/blackbox-tests/test-cases/reason/run.t
- test/blackbox-tests/test-cases/scope-ppx-bug/run.t
I have been getting weird errors from the compiler because of this change and it turns out it is not necessary to support multi-directory libraries.
> Move back .pp files to the source directory

- src/pform.ml
Error.deleted_in would use the current version rather than the deleted version
for the error message
> Use correct version for error message

- src/dir_contents.ml
- src/module.ml
- src/module.mli
- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
This an initial simplification of the module evaluation logic. For virtual libraries we'll be adding a `virtual_modules` field. This will require us to add similar error checking such as the modules in this field are disjoin from `modules_without_implementation` and `modules`, all the modules exist, and all are intf only. With this new code, extending it to support these things should be simpler.
@diml Another approach to simplify the loc book keeping is to simply add a loc field to `Module.t`. I went for the more conservative approach of making things easier by making the OSL do the book keeping. This is likely to be useful elsewhere such as adding variable expansion support, so I figured this will be useful anyway.
> Simplify module evaluator logic

- doc/dune-files.rst
Noticed this issue while finding another issue in #1056.
Also I assume the exact same is true for the `ocamlyacc` stanza, I'll happily also patch this in this PR if desired. Let me know.
> ocamllex does not need the list of modules to be in a list

- test/blackbox-tests/test-cases/dune-project-edition/run.t
The error messages of `cat` can change a bit, for example if a different locale is set. This uses a shell test instead.
> Do not rely on cat output in tests

- doc/dune-files.rst
- doc/index.rst
- doc/jsoo.rst
- doc/usage.rst
Jsoo is about as independent as other features which have their own section. Also, I've already seen users struggle to find content relevant to jsoo in the manual already. Hopefully this organization will make it easier for users to find what they're looking for.
cc @hhugo as well
> Move Jsoo content to its own page

- src/compilation_context.ml
- src/compilation_context.mli
- src/exe.ml
- src/gen_rules.ml
- src/js_of_ocaml_rules.boot.ml
- src/js_of_ocaml_rules.ml
- src/js_of_ocaml_rules.mli
- src/module_compilation.ml
This is how things are done in the menhir plugin for example. The jsoo rules are a bit older so haven't yet been refactored to use this type.
cc @hhugo 
PS: Should we consider making the jsoo rules a proper plugin eventually?
> Refactor jsoo rules to use Compilation_context.t

- src/action.ml
- src/config.ml
- src/dune_project.ml
- src/inline_tests.ml
- src/installed_dune_file.ml
- src/jbuild.ml
- src/ordered_set_lang.ml
- src/preprocessing.ml
- src/promotion.ml
- src/workspace.ml
This converts easy instances of applicative code. The rewrite rule is generally speaking:
```ocaml
e1 >>= pat1 ->
e2 >>= pat2 ->
e3 >>| pat3 ->
r
```
to:
```ocaml
let%map pat1 = e1
and pat2 = e2
and pat3 = e3
in
r
```
Most of the other instances of `>>=` to parse s-expressions fall into two categories:
- setting a default for a field depending on an other field (I think we'll have to store an option instead and evaluate the default later). Example: https://github.com/ocaml/dune/blob/ad0b376aeb950c24a1fe650dd0aa769e0f771b51/src/workspace.ml#L80-L92
- call a different parser depending on the shape of the s-expression. I don't know an obvious situation for this case. Example: https://github.com/ocaml/dune/blob/ad0b376aeb950c24a1fe650dd0aa769e0f771b51/src/jbuild.ml#L196-L201
> Use let%map for applicative code

- CHANGES.md
- doc/dune-files.rst
- src/blang.ml
- src/blang.mli
- src/gen_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/simple_rules.ml
- src/stdune/bool.ml
- src/stdune/bool.mli
- src/stdune/sexp.ml
- src/stdune/stdune.ml
- src/super_context.mli
- src/value.ml
- src/value.mli
The problem this PR is trying to solve is a bit specific to dune, but it's likely that it will be encountered by other projects as well. Currently, dune has a complicated script for generating test definitions that make sure tests run only in environments which support them. For example, some tests may not run on win32. A mechanism to enable tests conditionally would fix these problems.
Add an `enabled_if` field to aliases to toggle the execution of the alias. This field will be valued by a little EDSL for expressing boolean expressions. Here's an example of the kind of conditions we'd express with it:
```
(alias
((name runtest)
(deps (foo.exe))
(action (run ${<}))
(enabled_if (and (<> ${os} win32) (>= ${ocaml_version} 4.0.5)))))
```
This stalled a bit since I'm not sure how to do handle …
> enabled_if

- doc/usage.rst
They should include dune subst when pinning as well
cc @Drup
> Fix opam build instructions in usage.rst

- bin/main.ml
- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/build_interpret.mli
- src/build_system.ml
- src/build_system.mli
- src/gen_rules.ml
- src/jbuild.ml
- src/jbuild.mli
- src/lib_deps_info.ml
- src/lib_deps_info.mli
- src/main.mli
- src/preprocessing.ml
- src/preprocessing.mli
- src/super_context.ml
- src/super_context.mli
This is just some refactoring in preparation for another PR. The `Build.lib_deps` type and its associated functions are moved to their own module.
> Add module Lib_deps_info

- bin/main.ml
- src/gen_rules.ml
- src/gen_rules.mli
- src/import.ml
- src/main.ml
- src/main.mli
- src/meta.ml
- src/stdune/string.ml
- src/stdune/string.mli
- test/unit-tests/tests.mlt
> Remove String_map module

- src/action.ml
- src/inline_tests.ml
- src/jbuild.ml
- src/stanza.ml
- src/stanza.mli
- src/stdune/path.ml
- src/stdune/sexp.mli
- src/string_with_vars.ml
- src/workspace.ml
Followup to #1067. This adds a combinator to switch on file kind, uses existing combinators in more places, and stores an option in `Workspace.Context.Opam.t` as discussed before.
> More applicative syntax

- .travis-ci.sh
These --yes might have been intended for opam list, but opam list doesn't ask
for confirmation so we can just remove it.
> Remove duplicate --yes from opam calls

- src/dir_contents.ml
I found this while trying to use `(include_subdirs unqualified)` in camomile
> Fix bug in Dir_contents

- src/dir_contents.ml
This is the last PR before the virtual modules. The last refactor wasn't enough, as it was still too hard to custom errors. This PR should make it fairly easy to the necessary checks/errors for virtual modules. Dealing with the locs as they are right now is still a tiny bit of a pain, but is manageable.
> Refactor error detection for modules

- HACKING.md
Finally having time to dig in for #159, I began looking through the contributing and hacking texts today. It occurred to me that making some trivial updates to `HACKING.md` might be a good proving ground for my PR and commit etiquette.
Hopefully updating the naming on this document isn't premature. Note the two remaining instances of `jbuild` on lines 60 and 62, reflecting the current source files.
> Update HACKING.md to refer to Dune instead of JBuilder

- src/context.ml
- src/context.mli
- src/gen_rules.ml
- src/module_compilation.ml
- src/ocaml_version.ml
- src/ocaml_version.mli
Instead of comparing on the version numbers, add some predicates in `Context` that describe the compiler behavior.
(as discussed in #1079)
> Extract predicates for compiler versions

- src/inline_tests.ml
- src/lib.ml
- src/preprocessing.ml
- src/stdune/result.ml
- src/stdune/result.mli
- src/sub_system.ml
I realize that some of the old code was written with performance in mind, but `Result.List.map` should be efficient. I can revert the bits that look slow however.
> Simplify Result code with Combinators

- src/install.ml
- src/stdune/option.ml
- src/stdune/option.mli
- test/blackbox-tests/test-cases/cross-compilation/run.t
- test/blackbox-tests/test-cases/gen-opam-install-file/run.t
- test/blackbox-tests/test-cases/reason/run.t
An upcoming diff ends up accidentally changing the order of artifacts. It would be better if this order was deterministic and independent of how we generate the list of entries.
> Generate sorted .install files

- .github/CODEOWNERS
This PR adds a `.github/CODEOWNERS` file so that we get automatically added as reviewers for new pull requests.
> Setup code owners

- src/configurator/dune
- src/dune
So that dune itself can be vendored. Also remove useless `preprocess` field in `src/configurator/dune`.
/cc @avsm
> Fix preprocessing action in src/dune

- src/lib.ml
- src/lib.mli
It's not used outside the Lib module anyway
> Make Lib.Info.t abstract

- src/errors.ml
- test/blackbox-tests/test-cases/intf-only/run.t
- test/blackbox-tests/test-cases/missing-loc-run/run.t
- test/blackbox-tests/test-cases/no-installable-mode/run.t
- test/blackbox-tests/test-cases/several-packages/run.t
- test/blackbox-tests/test-cases/too-many-parens/run.t
- test/blackbox-tests/test-cases/variants/run.t
Signed-off-by: Anurag Soni <anuragsoni.13@gmail.com>
> Truncated view for blocks longer than 10 lines

- src/dune_file.ml
This is useful to enforce because it lets us check for the wrapped property without having to look up virtual libraries of implementations.
As discussed in chat, the main argument against this is that we might not want to make libraries migrate to wrapped/variants all at once, and the renaming hack isn't great. My counter arguments are as follows:
* We now have a transition mode that should make it painless to move to `(wrapped true)`.
* The renaming hack is an implementation detail that will be addressed for all libraries in bulk once we have proper compiler support.
if the main consumers of variants (@samoht, @avsm) object then I won't pursue this restriction, but for an initial version, I think it's a useful simplification. Are there any examples of libraries that would like to make …
> Enforce wrapped true for virtual libs/implementations

- src/dir_contents.ml
- src/dune_file.ml
- src/dune_file.mli
- src/lib.ml
- src/lib.mli
- src/lib_info.ml
- src/lib_info.mli
- src/lib_name.ml
- src/lib_name.mli
- src/lib_rules.ml
- src/module.ml
- src/module.mli
- src/virtual_rules.ml
- src/virtual_rules.mli
For the first stage, I'll only support virtual libraries and implementations that are defined locally. This is because full support will require refactoring dune-project.
I'm not sure if the way I'm handling requires and ppx rd's for implementations is the best way. Another approach is to take the implementation's info and combine those. But then, we don't really want to resolve the virtual lib's selects again.
* `libraries`
* `ppx_runtime_dependencies`
* `wrapped` (always `true`)
> Add virtual implementation info to lib info

- README.md
- bin/main.ml
- doc/usage.rst
Reflect the fact that dune install doesn't need opam-installer anymore.
Signed-off-by: Hongchang Wu <wuhc85@gmail.com>
> Update doc and README

- src/stdune/path.ml
It doesn't seem right to have this restriction in `Path.mkdir_p`.
> Allow Path.mkdir_p on source paths

- src/virtual_rules.ml
- test/blackbox-tests/test-cases/variants/impl-private-modules/dune-project
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/bar.ml
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/baz.ml
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/dune
- test/blackbox-tests/test-cases/variants/impl-private-modules/vlib/bar.mli
- test/blackbox-tests/test-cases/variants/impl-private-modules/vlib/dune
- test/blackbox-tests/test-cases/variants/impl-public-modules/dune-project
- test/blackbox-tests/test-cases/variants/impl-public-modules/impl/bar.ml
- test/blackbox-tests/test-cases/variants/impl-public-modules/impl/baz.ml
- test/blackbox-tests/test-cases/variants/impl-public-modules/impl/dune
- test/blackbox-tests/test-cases/variants/impl-public-modules/vlib/bar.mli
- test/blackbox-tests/test-cases/variants/impl-public-modules/vlib/dune
- test/blackbox-tests/test-cases/variants/run.t
As discussed, the implementations shouldn't introduce anything that might change the existing alias module.
> Do not allow new public modules in implementations

- Makefile
This makes it easier to package dune with an external system (such as debian) using the Makefile targets.
> Respect $LIBDIR in `make install/uninstall`

- src/build_system.ml
We don't need to look at all targets given that they are all in the same directory.
> Simplify mkdir before rule execution

- editor-integration/emacs/dune.el
- Improve highlighting of variables
- Use the following style:
```
(libraries   unix
stdune
```
where the "arguments" are aligned with the first.
> Emacs dune mode

- src/exe.ml
- src/inline_tests.ml
- src/lib_rules.ml
- src/simple_rules.ml
This should avoid the interal location in a few more error messages when
duplicate rules are created.
> Add more locations to rule creation

- doc/advanced-topics.rst
- doc/dune-files.rst
Pretty easy to miss, but all the code examples were missing in the dynload section.
> Markup fixes

- src/lib.ml
- src/lib.mli
- src/lib_info.ml
- src/lib_info.mli
Use Lib_info.t everywhere instead of t or Lib_name.t + Lib_info.t. In particular, this avoids the need to duplicate the types and to split the module in two.
> Refactor Lib.Error

- src/build.ml
- src/build.mli
- src/exe.ml
- src/js_of_ocaml_rules.ml
- src/lib_rules.ml
- src/menhir.ml
- src/module_compilation.ml
- src/ocamldep.ml
- src/odoc.ml
- src/preprocessing.ml
Explained why this is necessary in slack
> Break the dependency between build and context

- src/dune_file.ml
- src/dune_file.mli
- src/lib.ml
- src/lib.mli
- src/lib_info.ml
- src/lib_info.mli
- src/merlin.ml
- src/preprocessing.ml
- src/preprocessing.mli
- src/stdune/exn.mli
It's redundant now that we have Lib_name.t
> Remove Pp module

- src/dune_file.ml
- src/dune_project.ml
- src/dune_project.mli
The full syntax is `(using name version args)`. In addition of enabling new stanzas, this allows extensions to inspect what arguments were passed as arguments in the `dune-project` file.
A shortcut for the "simple" case where there is no associated data is provided for convenience.
> Dune_project: allow extensions to parse arguments

- doc/conf.py
This displays an "Edit on github" link even locally.
It probably fixes the online docs as well (#1350).
> Add github info for generated docs

- src/clflags.ml
- src/clflags.mli
- src/context.ml
- src/lib_rules.ml
- src/ocaml_flags.ml
- src/utils.ml
- src/utils.mli
This flag is never set. This inlines the fact that it is always true.
It doesn't seem to have ever been used. Is there another reason to have this flag?
> Remove unused Clflags.g

- src/clflags.ml
- src/clflags.mli
- src/ocaml_flags.ml
- src/report_error.ml
- src/report_error.mli
Some public references are exposed but never set. They can be removed and their value inlined.
> Remove some dead refs

- src/exe_rules.ml
- src/exe_rules.mli
- src/gen_rules.ml
- src/test_rules.ml
- src/test_rules.mli
`Gen_rules` is a bit difficult to navigate. My plan is to extract the different parts into different files and ultimately replace then `Gen` functor by plain functions. Does that sound like a good plan to you?
> Split executable & test rules out of Gen_rules

- src/dune_lexer.mll
Currently it was ignored, causing error messages to be incorrectly
located.
> Fix the parsing of the newline in the (lang ...) line

- CHANGES.md
- doc/usage.rst
- src/gen_rules.ml
- src/utop.ml
- src/utop.mli
- test/blackbox-tests/test-cases/utop-default/run.t
The current PR seems to work but there a few issues:
* ~~Somehow this makes the current utop tests get stuck. Infinite loop somewhere?~~ actually, one of the new tests simply forgot exit utop after launching it.
* The experience with multiple opam packages is not very good. If we pick a directory above an opam file for `$ dune utop <dir>` all the private libs will be invisible. I don't think this can be helped, but I think that it will confuse users.
* The code is quite inefficient, but is only run when doing `$ dune utop` so it's probably ok.
> Setup utop rules recursively for every directory

- test/blackbox-tests/test-cases/variants/install-file/dune
- test/blackbox-tests/test-cases/variants/install-file/dune-project
- test/blackbox-tests/test-cases/variants/install-file/impl/dune
- test/blackbox-tests/test-cases/variants/install-file/impl/foo.ml
- test/blackbox-tests/test-cases/variants/install-file/vlib/dune
- test/blackbox-tests/test-cases/variants/install-file/vlib/foo.mli
- test/blackbox-tests/test-cases/variants/run.t
This test demonstrates the bug as the installation expects ml-gen and cmt, cmti
files
> Add test for .install files of implementations

- test/blackbox-tests/test-cases/github1395/run.t
This output contains some platform specific stuff (CC in this case)
Having an analogous fix for output-obj would be nice.
> Fix 1395 by not including build output

- src/build_system.ml
Previously, it would be required to replicate the alias name in the creation and
the checking. Now all the standard alias names are stored in a global hash
table.
> Create standard aliases without boilerplate

- test/blackbox-tests/test-cases/force-test/run.t
There's no need to clean in the beginning or rely on --display short to check if
something is rebuilt
@ejgallego could you check if this fixes the `force-test` test for you? You can run it individually with `$ dune build @force-test` btw.
> Simplify the --force tests

- test/blackbox-tests/test-cases/output-obj/run.t
The relevant part of that test is the output of the runtest part.
How exactly it is built is not important and causes build failures on Travis sometimes.
> Make output-obj test more reproducible

- test/unit-tests/action.mlt
- test/unit-tests/expect_test.mll
This is used to ignore some output generated by the toplevel. Useful when the
output isn't useful for the tests and not deterministic.
@ejgallego this should fix another failure for you
> Add [%%ignore] to expect tests

- src/lib_modules.ml
- src/lib_rules.ml
- src/ml_kind.ml
- src/ml_kind.mli
- src/module.ml
- src/module.mli
- src/ocamldep.ml
- src/virtual_rules.ml
- src/virtual_rules.mli
- test/blackbox-tests/test-cases/variants/impl-private-modules/dune
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/bar.ml
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/baz.ml
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/dune
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/priv.ml
- test/blackbox-tests/test-cases/variants/impl-private-modules/impl/priv.mli
- test/blackbox-tests/test-cases/variants/impl-private-modules/test.ml
- test/blackbox-tests/test-cases/variants/run.t
Implementations of virtual libraries need an alias module that includes modules from the implementation and virtual library. On the way, I also fix two unrelated issues:
* The dependency graph was wrong in the presence of private module mli's
* The .install file wasn't being generated as some incorrect copy rules were setup.
> Virtual library implementation fixes related to private modules

- bin/main.ml
- test/blackbox-tests/test-cases/install-libdir/bin/dune
- test/blackbox-tests/test-cases/install-libdir/run.t
The logic is a bit complicated because there are two levels of default values between prefix and libdir. This adds tests for the 4 cases.
> Fix interaction between prefix and libdir defaults

- test/blackbox-tests/test-cases/env-var-expansion/correct/dune
- test/blackbox-tests/test-cases/env-var-expansion/run.t
The second run of alias echo2 should not be printing true twice for example
@trefis does this look intentional?
> Add test to show that the env macro handle scoping of setenv

- src/format_rules.ml
- test/blackbox-tests/test-cases/formatting/run.t
More precisely, when invoked in a directory, it depends on all files named `.ocamlformat` in parent directories.
This change has two benefits:
- it makes ocamlformat dependency tracking correct (all dependencies are there);
- it makes refmt dependency tracking more precise (changing .ocamlformat used to trigger recompilations of reason source files).
> Ocamlformat depends on all .ocamlformat files

- src/env_node.ml
- src/env_node.mli
- src/expander.ml
- src/expander.mli
- src/lib.ml
- src/lib.mli
- src/lib_deps_info.ml
- src/lib_deps_info.mli
- src/super_context.ml
This is reviving @emillon's earlier attempt to split this module. Now that we have an expander module, there's no need to pass awkward types.
> Env node module

- CHANGES.md
- doc/index.rst
- doc/variants.rst
This picks the documentation part from #1430 and adds a disclaimer. That way we can refer to this documentation, but it's not completely public either.
> Document virtual libraries (from #1430)

- CHANGES.md
- src/scheduler.ml
Similarly to how dune ignores `_opam` dir this commit makes it ignore `_esy` dir. This is related to #1578.
> Ignore _esy in file watcher

- doc/dune-files.rst
- doc/faq.rst
- doc/foreign-code.rst
- Add missing labels for `library` and `install`
- Add missing `_` for `dune-subdirs` label
- Extend underline for one of the headers
- Add required duplication of link target when the label isn't a
section header
- Fix list markers to consistently use `-` and have the right amount
of whitespace surrounding them
Signed-off-by: Brendan Long <self@brendanlong.com>
> Fix documentation rst errors

- src/dir_contents.ml
- src/lib.ml
- src/lib.mli
- test/blackbox-tests/test-cases/variants/impl-not-virtual-external/dune
- test/blackbox-tests/test-cases/variants/impl-not-virtual-external/dune-project
- test/blackbox-tests/test-cases/variants/impl-not-virtual/dune
- test/blackbox-tests/test-cases/variants/impl-not-virtual/dune-project
- test/blackbox-tests/test-cases/variants/impl-not-virtual/impl/dune
- test/blackbox-tests/test-cases/variants/impl-not-virtual/lib/dune
- test/blackbox-tests/test-cases/variants/implements-external/impl/dune
- test/blackbox-tests/test-cases/variants/implements-external/impl/dune-project
- test/blackbox-tests/test-cases/variants/implements-external/impl/impl-lib/dune
- test/blackbox-tests/test-cases/variants/implements-external/impl/impl-lib/foo.ml
- test/blackbox-tests/test-cases/variants/implements-external/impl/test.ml
- test/blackbox-tests/test-cases/variants/implements-external/vlib/bar.ml
- test/blackbox-tests/test-cases/variants/implements-external/vlib/dune
- test/blackbox-tests/test-cases/variants/implements-external/vlib/dune-project
- test/blackbox-tests/test-cases/variants/implements-external/vlib/foo.mli
- test/blackbox-tests/test-cases/variants/no-vlib-present/dune
- test/blackbox-tests/test-cases/variants/no-vlib-present/dune-project
- test/blackbox-tests/test-cases/variants/run.t
This set of test cases exercise our error checking when implementing non virtual libraries and implementing external libraries. I've managed to uncover a bug in the process. Fix will come shortly.
> More test cases for variants

- src/dune_lang/dune_lang.ml
- test/blackbox-tests/test-cases/github1560/run.t
Mainly a re-organization by giving the various types their own values. We should be able to move some of their helper functions to these modules.
> Parser cleanups

- src/compilation_context.ml
- src/compilation_context.mli
- src/dep_graph.ml
- src/dep_graph.mli
- src/exe.ml
- src/lib_rules.ml
- src/link_time_code_gen.ml
- src/module_compilation.ml
- src/module_compilation.mli
- src/ocamldep.ml
- src/ocamldep.mli
- src/odoc.ml
- src/odoc.mli
- src/vimpl.ml
- src/vimpl.mli
- src/virtual_rules.ml
- src/virtual_rules.mli
In the old code, the fact that our virtual lib is local is assumed in too many places. I attempt to make this problem easier to address by introducing a `Vimpl` module that should encapsulate all that is necessary for transparently generating implementation rules; regardless of where/how the virtual lib lives.
Note that I had to split the ocamldep module to avoid cycles.
> Introduce vlib implementation module

- src/dir_contents.ml
- src/dir_status.ml
- src/dir_status.mli
- src/super_context.ml
- src/super_context.mli
Now we store the dir_status database per super context. Similarly, we could remove the global cache in Dir_contents as well if I manage to make #1566 work.
> Remove global variable from dir_status

- test/blackbox-tests/test-cases/variants/implements-external/vlib/dune
I just noticed that this library should have been public because this test fails on the dune-package branch.
Findlib is aggressive here in interpreting an empty META file as a library being present. dune-package is more conservative and will treat this library as simply being absent.
> Test for implementing external library should use public lib

- bench/file_tree_cache.ml
- bench/scheduler_bench.ml
- src/stdune/path.mli
To run this benchmark, the scheduler benchmark must be commented. Should we include this in a separate benchmark executable perhaps?
> Add bench for file_tree cache

- src/dune
- src/fiber/fiber.ml
- src/fiber/fiber.mli
- src/ml_kind.ml
- src/ml_kind.mli
- src/module.ml
- src/module.mli
- src/ocamlobjinfo.mli
- src/ocamlobjinfo.mll
- src/stdune/string.ml
- src/stdune/string.mli
- test/unit-tests/dune
- test/unit-tests/expect_test.mll
- test/unit-tests/ocamlobjinfo.mlt
This will be useful to avoid installing all-deps files, but I expect that it will have other uses in the future as well. For example, to discover unused library dependencies.
I'll push some tests in this PR as well.
> Add ocamlobjinfo parser

- test/blackbox-tests/test-cases/external-lib-deps/dune
- test/blackbox-tests/test-cases/external-lib-deps/run.t
This is a case that we rely on for the Jane Street public release.
> Extend the test for external-lib-deps

- src/dune_package.ml
- src/dune_package.mli
- src/findlib.ml
- src/install_rules.ml
- src/local_package.ml
- src/local_package.mli
- src/stdune/set.ml
- src/stdune/set_intf.ml
When a template exists with a virtual library, we error out. As that combination
is not possible.
When a meta template is present, we emit a special dune package file that
ignores it.
> Fix compatibility between meta templates and dune-package

- src/catapult/catapult.ml
- test/blackbox-tests/test-cases/trace-file/run.t
- test/unit-tests/catapult.mlt
Instead of computing the duration and emitting a single event, this outputs one event when the process starts and one when the process ends. They are linked by an auto-incremented id.
Bonus parts:
- we can get rid of the color generation code
- it looks nicer
Before:
After:
> Catapult: use async events

- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
@bobot i've tested this on 4.06 and it seems to work.
> wrapped-transition tests work on 4.06

- doc/tests.rst
I was looking at the manual and wondered whether those are variables of the same class as those using the %{} syntax.
> use var syntax

- src/build_system.ml
- src/context.ml
- src/dir_contents.ml
- src/dune_lang/dune_lang.ml
- src/dune_project.ml
- src/findlib.ml
- src/install_rules.ml
- src/preprocessing.ml
- src/print_diff.ml
- src/stdune/exn.ml
- src/stdune/exn.mli
- src/stdune/loc.ml
- src/stdune/loc.mli
- src/stdune/loc0.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/utop.ml
To unbreak recursion, we introduce a Loc0, internal module.
> Make Loc.in_* functions take Path.t directly

- bootstrap.ml
Helps debug exceptions that only occur when bootstrapping
> Enable backtraces for failures in bootstrap

- src/dir_contents.ml
- src/inline_tests.ml
- src/lib_modules.ml
- src/lib_modules.mli
- src/link_time_code_gen.ml
- src/menhir.ml
- src/module.ml
- src/module.mli
- src/modules_field_evaluator.ml
- src/modules_field_evaluator.mli
- src/utop.ml
- test/blackbox-tests/test-cases/variants/run.t
- remove encoding, decoding duplication
- remove threading of `virtual_modules` information
- simplifies moving `obj_dir` to module
> Add virtual kind in module

- src/dune_lang/dune_lang.ml
- src/stdune/dyn.ml
- src/stdune/dyn.mli
- src/stdune/pp.ml
- src/stdune/pp.mli
- src/stdune/sexp.ml
- src/stdune/sexp_intf.ml
- src/stdune/stdune.ml
As discussed in the retreat, this should save us from some copy paste between the sexp conversion and the pretty printing.
> Dyn module

- src/configurator/v1.ml
- src/stdune/bool.ml
- src/stdune/bool.mli
- src/stdune/int.ml
- src/stdune/int.mli
- src/stdune/option.ml
- src/stdune/option.mli
> Add proper parsing errors when failing to extract values

- Makefile
Since the bootstrap build is now storing artifacts in `_build_bootstrap`, `make install/uninstall` need to copy the files from this same location.
> Fix make install/uninstall

- doc/dune-files.rst
Use the same formatting everywhere: one space indentation and closing parenthese at the end of the previous line.
> Make examples consistent

- src/stdune/path.ml
- test/unit-tests/path.mlt
Allow it to work on build directory paths when the build directory is set to an absolute external path.
This should fix #1735.
> Fix Path.descendant

- bin/exec.ml
- bin/external_lib_deps.ml
- bin/import.ml
- bin/install_uninstall.ml
- bin/main.ml
- bin/printenv.ml
- bin/target.ml
- bin/target.mli
- bin/utop.ml
- src/main.ml
- src/main.mli
While working on #1757, I realised that for some commands such as `dune install` we load all the dune files, even though this is not necessary. This PR refactors a bit the `Main` module in `src` to avoid this.
Now instead of `Main.setup`, cli commands should use `Main.scan_workspace` if they don't need to access the build system or contents of dune files.
> Do not load dune files when not necessary

- bin/upgrade.ml
- src/dune_project.ml
- src/dune_project.mli
- src/file_tree.ml
- src/file_tree.mli
- src/opam_file.ml
- src/opam_file.mli
- src/upgrader.boot.ml
- src/upgrader.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/upgrader/foo.opam
- test/blackbox-tests/test-cases/upgrader/jbuild
- test/blackbox-tests/test-cases/upgrader/run.t
`dune upgrade` now upgrades the opam files:
- it replaces `"jbuilder" ...` by `"dune" ...`
- it changes the contraints to `{build & >= "1.17"}` (or whatever the current version of dune is)
This PR contains a test.
> Make `dune upgrade` upgrade the opam files as well

- test/blackbox-tests/cram.mll
- test/blackbox-tests/test-cases/misc/run.t
This should make some tests more readable. The syntax is:
```
$ cat <<EOF
> Multiline
> Text
> EOF
Multiline
Text
```
> Add support for multiline commands in cram tests

- src/expander.ml
- src/expander.mli
- src/merlin.ml
- src/stdune/option.ml
- src/stdune/option.mli
Previously, it would fail if some vars failed to expand.
I could have used partial expansion to implement this, but we really don't care about the partial results.
Also, this bug really shows that we need support for arbitrary actions. As it's a shame that omp won't have merlin support for example.
> Fix generating .merlin with -pp

- src/ocaml_version.ml
- src/ocaml_version.mli
- src/ocamlobjinfo.mll
However, it can safely be omitted
> -no-approx is not supported in 4.02

- src/ocaml_version.ml
- src/ocaml_version.mli
- src/ocamlobjinfo.mll
This option was introduced in 4.04 so we shouldn't be using it prematurely
> Don't use -no-code pre 4.04

- src/build_system.ml
- src/stdune/id.ml
- src/stdune/id.mli
Check the map for rules that we've iterated before already. Fix #1825 
I'm not sure where the cycle is coming from, but this PR fixes it.
> Fix infinite rule when printing loop

- src/ocamldep.ml
The old function was already doing many things at once. This simplifies things at least a little bit.
> Split parsing of module names and reading them

- doc/foreign-code.rst
re2 is using dune instead of jbuilder
> doc: fix link to re2 foreign build sandboxing

- src/dag/dag.ml
- test/unit-tests/dag.mlt
`Dag` sometimes reports cycles incorrectly.
This PR adds a test demonstrating incorrect behavior and attempts a fix. 
The correctness of the fix is not supported by understanding of the code, but it's supported by the following evidence.
In the test the correct and the incorrect cycle are like this (note that the first 4 elements of the list are reversed):
correct:   [23; 22; 21; 20; 14; 13; 12; 11; 23]
incorrect: [20; 21; 22; 23; 14; 13; 12; 11; 23]
Given the test case, I'm just guessing the `List.rev` of the left side of the list was missing. Indeed, adding that `List.rev` fixes the broken case without breaking anything else.
> DAG cycle reporting bug

- src/file_tree.ml
- src/file_tree.mli
- src/stdune/dyn.ml
- src/stdune/dyn.mli
- src/stdune/dyn0.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/string.ml
- src/stdune/string.mli
- test/unit-tests/memoize.mlt
This is just a start, as it's probably almost never correct to depend on the entire file tree. But it's just a start for other functions to start depending on this.
> Work towards memoization of File_tree.load

- doc/quick-start.rst
As pointed out by @samoht and @emillon, the quickstart was still using the old configurator
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>
> quickstart.rst: old configurator -> dune.configurator

- src/build_system.ml
- src/dune_file.ml
- src/dune_file.mli
It wasn't immediately obvious to me as a tuple.
> Make new promote argument into a record

- src/findlib.ml
- src/stdune/dune
- src/stdune/option.ml
- src/stdune/option.mli
* Add a private Meta_source sub module that abstracts details such as META
naming schemes. This makes a few helper functions private.
* Remove names specific to findlib. Some of these functions read dune-package
files as well.
> Cleanup findlib handling

- src/fiber/fiber.ml
- src/fiber/fiber.mli
- src/memo/memo.ml
Make it possible to set the value of a fiber-local variable locally in a synchronous function.
This generalizes a trick payed in `Memo.Call_stack`, so we can simplify that.
Some of the motivation comes from wanting to introduce another such local variable, for tracking allowed effects.
Separately, this PR also adds `Fiber.of_thunk : (unit -> 'a t) -> 'a t`, which I wanted.
> Add Fiber.Var.set_sync and use it in Memo

- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/build_system.ml
- src/build_system.mli
- src/dep.ml
- src/dep.mli
- src/static_deps.ml
- src/static_deps.mli
- src/super_context.ml
Fix #1931
One thing that is now possible is to omit calculating the entire digest when the `Universe` dependency pops up. Unfortunately, we still need the digest for the sandbox dir. So we'd need an alternative mechanism for generating it.
> Introduce explicit universe dependency

- src/lib.ml
- src/lib.mli
- src/lib_name.ml
- src/lib_name.mli
- src/odoc.ml
- src/stdune/comparable.ml
- src/stdune/comparable.mli
- src/stdune/interned.ml
- src/stdune/interned.mli
- src/stdune/list.ml
- src/stdune/list.mli
I've memoized a couple of functions in odoc that were previously memoized "manually" using a hash table.
I've refrained removing the on_load_dir yet, because I'm a little concerned with the use of a functor in this module. Should we be removing this functor as it's bloating the scope accessible to the memoized functions.
> Odoc Memoization

- test/unit-tests/expect_test.mll
Currently `[@@ignore]` blocks in `.mlt` files suppress raised exceptions just as well as they suppress the values themselves.
I think suppressing exceptions is probably unintentional: it's easy to end up with a block not doing any of its intended function with no error message whatsoever, which is confusing.
This PR makes us print the exceptions (and some of the other error messages), but not the values and types.
> Expect test framework: print exceptions raised by [@@ignore]d blocks

- src/dir_status.ml
- src/memo/memo.ml
- src/stdune/interned.ml
- test/unit-tests/memoize.mlt
Raise when the same memoized function name is used twice.
> Raise when the same memoized function name is used twice

- src/dune_lang/dune_lang.mli
- src/dune_lang/template.ml
- src/install.ml
- src/memo/memo.ml
- src/stdune/caml/dune_caml.ml
- src/stdune/exn.ml
- src/stdune/fdecl.ml
- src/stdune/list.ml
- src/stdune/map.ml
- src/stdune/option.ml
- src/stdune/string.ml
- src/stdune/string_split.ml
- test/unit-tests/sexp.mlt
Exn.code_error should be used everywhere
> Remove all invalid_arg from codebase

- src/context.ml
- src/context.mli
- src/dune_lang/dune_lang.mli
- src/dune_lang/syntax.ml
- src/dune_lang/syntax.mli
- src/dune_project.ml
- src/dune_project.mli
- src/gen_rules.ml
- src/lib_rules.ml
- src/lib_rules.mli
- src/local_package.ml
- src/odoc.boot.ml
- src/odoc.ml
- src/odoc.mli
- src/packages.ml
- src/packages.mli
- src/stdune/exn.ml
- src/stdune/exn.mli
- src/stdune/or_exn.ml
- src/stdune/or_exn.mli
- src/stdune/result.ml
- src/stdune/result.mli
- src/super_context.ml
- src/super_context.mli
- src/syntax.ml
- src/syntax.mli
So far, I've mechanically removed the functor. The memoized functions now include & ignore a `Super_context.t` argument. This works for now but later we'll need to fix this properly.
> Odoc memoization part #2

- bootstrap.ml
- src/dag/dag.ml
- src/dag/dag_intf.ml
- src/dag/dune
- src/dune
- test/blackbox-tests/test-cases/loop/run.t
- test/unit-tests/dag.mlt
- test/unit-tests/memoize.mlt
- vendor/incremental-cycles/LICENSE
- vendor/incremental-cycles/src/dune
- vendor/incremental-cycles/src/incremental_cycles.ml
- vendor/incremental-cycles/src/incremental_cycles.mli
- vendor/incremental-cycles/src/incremental_cycles_intf.ml
- vendor/update-incremental-cycles.sh
This PR proposes to replace the current implementation of the incremental cycle detection algorithm implemented in dune (described in https://dl.acm.org/citation.cfm?doid=2846106.2756553).
This is joint work with @jhjourdan, @charguer and @fpottier.
Our new OCaml implementation has been formally verified using Coq, including both its *functional correctness* and *asymptotic complexity*. It is described in the following [blog-post](http://gallium.inria.fr/blog/incremental-cycle-detection/) (shortly) and [article](http://gallium.inria.fr/~fpottier/publis/gueneau-jourdan-chargueraud-pottier-2019.pdf) (in greater details).
The verified OCaml code and Coq proofs are [available online](https://gitlab.inria.fr/agueneau/incremental-cycles), this PR is simply vendoring the code into dune and …
> Use a formally verified incremental cycle detection algorithm

- src/super_context.ml
I'm not sure why we ended up using `Context.equal`, but there are many fields in `Super_context` and it's unclear that none of them may change from run to run without the `Context` changing.
It's much easier to think about if we use physical equality instead.
> use physical equality for Super_context

- src/build_system.ml
- src/build_system.mli
- src/format_rules.ml
- src/format_rules.mli
- src/gen_rules.ml
Just split the rule generation into two functions. The code isn't very clean yet, I just wanted to show this as a POC. I did not add any memoization because I don't really see what needs to be memoized. Fetching the format config per directory perhaps?
I can clean this code up if the reviewers are happy with this direction.
> Remove on_load_dir in Format_rules and in general

- src/build.ml
- src/build.mli
- src/build_interpret.ml
- src/build_system.ml
- src/dep.ml
- src/dep.mli
- src/static_deps.ml
- src/static_deps.mli
- src/super_context.ml
This allows us to introduce dependency primitives without having to change
[Build.t]. Note that Globs are not included since they require a different index
in the GADT.
> Add Deps constructor to Build.t

- src/context.ml
- src/context.mli
- src/file_tree.ml
- src/ocaml-config/ocaml_config.ml
- src/ocaml-config/ocaml_config.mli
- src/stdune/dyn.ml
- src/stdune/dyn.mli
- src/stdune/dyn0.ml
- src/stdune/env.ml
- src/stdune/env.mli
- src/stdune/hashtbl.ml
- src/stdune/hashtbl.mli
- src/stdune/map.ml
- src/stdune/map.mli
- src/stdune/pp.ml
- src/stdune/pp.mli
- src/stdune/sexp.ml
- src/stdune/sexp.mli
- src/stdune/sexp0.ml
- src/stdune/sexp1.ml
- src/stdune/string.ml
- src/stdune/string0.ml
- src/super_context.ml
- src/super_context.mli
- Add a few conversion to `Dyn.t`
- Add a constructor `Dyn.Sexp` for cases where obtaining a `Dyn.t` is otherwise not easy.
- Introduce `Dyn.Encoder` module similar to `Sexp.Encoder`, both because it's useful and to make it even easier to migrate from Sexp to Dyn.
> More conversions to dyn

- src/build_system.ml
- src/build_system.mli
- src/fiber/fiber.ml
- src/fiber/fiber.mli
- src/gen_rules.ml
- src/install_rules.ml
- src/memo/implicit_output.ml
- src/memo/implicit_output.mli
- src/memo/memo.ml
- src/memo/memo.mli
- src/odoc.ml
- src/packages.ml
- src/stdune/appendable_list.ml
- src/stdune/appendable_list.mli
- src/stdune/exn_with_backtrace.ml
- src/stdune/exn_with_backtrace.mli
- src/stdune/stdune.ml
This PR introduces the concept of "implicit outputs".
This is a compatibility layer between the purely functional world of memoization and the side-effectful world of the rest of Dune. 
With implicit outputs, the rule generator can still be written in imperative style and call `add_rule`, while memoization will correctly treat this as a part of the output of the function.
> Implicit outputs

- src/format_rules.ml
- test/blackbox-tests/test-cases/formatting/run.t
This was causing some files that needed to be re-formatted not to show up as
such. [This comment](https://github.com/ocaml/dune/pull/1942#discussion_r267467311) explains why the current behavior isn't optimal.
Now I'm still not sure why exactly this line makes the difference. 
perhaps @diml knows?
> Remove empty dep to @.formatted/fmt

- src/alias.ml
- src/alias.mli
- src/build.ml
- src/build.mli
- src/build_system.ml
- src/build_system.mli
- src/check_rules.ml
- src/dep.ml
- src/dep.mli
- src/format_rules.ml
- src/gen_rules.ml
- src/inline_tests.ml
- src/install_rules.ml
- src/lib_file_deps.ml
- src/merlin.ml
- src/odoc.ml
- src/preprocessing.ml
- src/simple_rules.ml
- src/super_context.ml
- test/blackbox-tests/test-cases/odoc/run.t
This is the first step to treat aliases a bit more abstractly. There are still uses of `Alias.stamp_file`. To replace those, we will need to simplify the mechanism to add deps to aliases.
> Add Dep.alias dependency

- src/dir_contents.ml
- src/dir_status.ml
- src/dir_status.mli
- src/dune_file.ml
- src/dune_file.mli
This is a cherry-pick of the directory traversal parts from the Dune
PR (#1968) plus a modification to enable the `qualified` mode inside `(include_subdirs ...)`
I was uncomfortable with the misnaming done there, so this PR enables
the `(include_subdirs qualified)` syntax and provides a `local` part
to the traversal so clients [such as the Coq mode] can use it.
Note that this does introduce a bit of overhead in the tree traversal,
especially in deep trees, it should be possible to optimize if we deem
it necessary.
> [dir_contents] Allow qualified traversal of directories.

- .travis-ci.sh
- CHANGES.md
- Makefile
- doc/coq.rst
- doc/index.rst
- src/coq_module.ml
- src/coq_module.mli
- src/coq_rules.ml
- src/coq_rules.mli
- src/dir_contents.ml
- src/dir_contents.mli
- src/dune_file.ml
- src/dune_file.mli
- src/gen_rules.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/coq/base/bar.v
- test/blackbox-tests/test-cases/coq/base/dune
- test/blackbox-tests/test-cases/coq/base/dune-project
- test/blackbox-tests/test-cases/coq/base/foo.v
- test/blackbox-tests/test-cases/coq/rec_module/a/bar.v
- test/blackbox-tests/test-cases/coq/rec_module/b/foo.v
- test/blackbox-tests/test-cases/coq/rec_module/c/d/bar.v
- test/blackbox-tests/test-cases/coq/rec_module/c/ooo.v
- test/blackbox-tests/test-cases/coq/rec_module/dune
- test/blackbox-tests/test-cases/coq/rec_module/dune-project
- test/blackbox-tests/test-cases/coq/run.t
Dear Dune devs, this is a reworked partial version of #1555 , which only includes the very basic handling of Coq modules and rules.
We piggyback on the `local` support for dir traversal when `(include_subdirs qualified)` is enabled to build qualified Coq modules.
I have tested this on a few developments that use recursive modules and so far it works well :)
Below is the commit message:
------
This commit adds experimental Coq support to Dune. See Dune issue 1446
for more details.
The patch adds a new stanza `(coqlib ...)` enabled by adding
`(using coq 0.1)` to `dune-project`. The stanza looks like:
```lisp
(coqlib
(name Ltac2)               ; Determines the `-R` flag
(synopsis "Ltac 2 Plugin") ;
(modules core Lib.mod)
(flags -warn -no-cbv))     ; Flags for `coqc`
```
The functionality of …
> [lang] Preliminary Coq support, core part with recursively qualified modules.

- doc/dune-files.rst
The "Linking modes" section of the Dune files chapter in the docs contained what I assume is an old reference to JBuild
> Jbuild -> Dune

- doc/coq.rst
- src/coq_rules.ml
Using non-"packed" plugins is deprecated in Coq upstream, however
there are still too many of them using declaring an `.mllib` and it is
not reasonable to ask them to migrate for old Coq versions such as
8.8, which we support.
We thus add support for detecting an `.mllib` file if around.
> [coq] Support depending on non-packed legacy plugins.

- src/dune_lang/dune_lexer.mll
- src/dune_lang/jbuild_lexer.mll
- src/dune_lang/lexer_shared.ml
- src/dune_lang/lexer_shared.mli
be a little less pessimistic that our parser is wrong. It's probably an invalid
file.
> Tweak error message when failing to parse dune/jbuild files

- doc/coq.rst
- src/coq_rules.ml
This is needed for compatibility with Coq < 8.11 otherwise Coq doesn't
know how to set correct OCaml `-I` path.
We will remove this kludge in the "2.0" version of the plugin.
We also perform some refactoring and cleanup of the rules code.
> [coq] Install plugin `.cmxs` files under the coq library root.

- .github/CODEOWNERS
trefis doesn't want to own it because it generates a lot of notifications
> change ownership of src/merlin.*

- src/dune_file.ml
- src/dune_file.mli
- src/dune_init.ml
- test/blackbox-tests/test-cases/dune-init/run.t
Fulfills @rgrinberg's request at https://github.com/ocaml/dune/pull/1448#issuecomment-472710046.
The new auxiliary function and light refactor in e24ef68 follows lines discussed with @diml in  #1972
> Refactor Dune_file.Stanzas.parser and clean up Dune_init stanza conflict detection

- src/context.ml
- src/context.mli
- src/lib.ml
- src/lib.mli
- src/lib_config.ml
- src/lib_info.ml
- src/lib_info.mli
- src/scope.ml
- src/scope.mli
- src/super_context.ml
The creation is basically done in 2 parts, so I split it into 2 functions. I also get rid of the mutability which is more clearly handled with a forward declaration. Lib_config.t is introduced to stop passing the same parameters everywhere.
> Clean up Scope DB creation

- src/stdune/in_expect_test.ml
- src/stdune/in_expect_test.mli
- src/stdune/stdune.ml
- test/unit-tests/dune
- test/unit-tests/expect_test.mll
After this PR if you use `Stdune.In_expect_test.printf "hello world\n"` in an expect test, that output will become a part of the expectation. (ideally we'd capture the normal printf, but that's trickier)
> printf in expect tests

- src/dep.ml
- src/dep.mli
This value is only used for marshaling, so there's no need to allow callers to
peek into it.
> Make trace abstract

- src/file_binding.ml
- src/file_binding.mli
- src/install_rules.ml
- src/stdune/path.mli
The dst is a local path, so it should be reflected as such
> Make File_bindings.Expanded.t type more precise

- src/scope.ml
- src/stdune/map.ml
- src/stdune/map_intf.ml
This is similar to the case of the caching that was present in `File_tree.t`. I've benchmarked this change on the ocaml platform, and if it has an impact, it's infact negative as this PR seems to offer a small but measurable speed up. And in fact, the map lookup introduced here could be even faster if we had some sort of a trie based map of paths.
I'm aware that there's some duplication introduced between this PR and #2043. I will address it once both PR's are merged.
> Remove caching of scopes

- bin/install_uninstall.ml
- src/build_system.ml
- src/file_tree.ml
- src/findlib.ml
- src/promotion.ml
- src/stdune/path.ml
- src/stdune/path.mli
- test/blackbox-tests/test-cases/unreadable-src/run.t
This allows us to accurately detect errors unlike Sys.readdir.
> Use Unix.opendir to list directories

- CHANGES.md
- doc/coq.rst
- src/coq_rules.ml
- src/coq_rules.mli
- src/dir_contents.ml
- src/dune_file.ml
- src/dune_file.mli
- src/gen_rules.ml
- src/stdune/path.ml
- test/blackbox-tests/test-cases/coq/ml_lib/src/dune
- test/blackbox-tests/test-cases/coq/ml_lib/src/gram.mlg
- test/blackbox-tests/test-cases/coq/ml_lib/src/gram.mli
- test/blackbox-tests/test-cases/coq/run.t
We add a
```
(coq.pp (modules foo bar))
````
stanza, that will look for a `foo.mlg` file and produce a
pre-processed `foo.ml`; similarly for `bar`.
This helps Coq plugin writers to avoid boilerplate and more
importantly, to get the right path on error messages.
> [coq] Add coqpp preprocessing stanza.

- CHANGES.md
- doc/coq.rst
- src/dune_file.ml
- test/blackbox-tests/test-cases/coq/base/dune
- test/blackbox-tests/test-cases/coq/ml_lib/theories/dune
- test/blackbox-tests/test-cases/coq/rec_module/dune
Support for the first form will be dropped in the 1.0 version of the
Coq language.
> [coq] Rename `(coqlib ...)` to `(coq.theory ...)`

- src/coq_rules.ml
- src/dune_file.ml
- src/dune_file.mli
As noted by @rgrinberg, this was a bug on our implementation as we
didn't really support `select` depends.
We also refactor the code a bit and produce correct error locations.
> [coq] Support only direct-style OCaml library dependencies.

- CHANGES.md
- src/coq_rules.boot.ml
- src/coq_rules.ml
- src/coq_rules.mli
- src/gen_rules.ml
- src/menhir.boot.ml
- src/menhir.ml
- src/menhir.mli
This is a common problem in a few Dune tools: if a menhir file is
inside a sub-directory, the tool will be invoked from the subdir,
however the Dune call was likely from the top-level directory and the
error/warning messages won't be correct.
I am not sure this is the right way to address this problem, in
particular what will happen if Dune is called from some parallel
sub-directory. Suggestions welcome.
> [menhir] Call menhir from root build directory to improve error reporting

- editor-integration/emacs/dune.el
These were omitted from the emacs file
> Add highlighting to source_tree and env_var deps

- bench/file_tree_cache.ml
These need to be updated to use the new Path.Source.t
These build errors can be caught `$ make check`
> Fix file tree cache benchmark building

- src/check_rules.ml
- src/lib_file_deps.ml
- src/lib_info.ml
- src/lib_rules.ml
- src/mode.ml
this makes it easier to experiment with alternative extensions such as for bucklescript
> do not hard code cmo/cmx/cmi extensions everywhere

- .travis-ci.sh
The two lists were different, which is probably a bug, and it seems to cause builds to fail in some cases.
> fix lists of test dependencies in travis

- src/dune_file.ml
- src/dune_file.mli
- test/blackbox-tests/test-cases/too-many-parens/b/dune
- test/blackbox-tests/test-cases/too-many-parens/run.t
This is another small feature required for #1930. The parser now captures the package name in executable stanzas.
> Capture the package name in Dune_file.Executables.t

- CHANGES.md
- src/dune_file.ml
- src/dune_file.mli
- src/dune_lang/dune_lang.mli
- src/dune_lang/template.ml
- src/dune_lang/template.mli
- src/merlin.ml
- src/preprocessing.ml
- src/string_with_vars.ml
- src/string_with_vars.mli
- test/blackbox-tests/test-cases/dune-ppx-driver-system/driver-tests/dune
- test/blackbox-tests/test-cases/dune-ppx-driver-system/driver-tests/dune-project
- test/blackbox-tests/test-cases/dune-ppx-driver-system/run.t
This PR propose to add support for variables in the flags of the "pps" (and "pps_staged") kind of preprocessing. 
The use-case I have in mind would be to pass "%{profile}" to the preprocessor which would allow it to generate a different code depending on the profile. This would be useful for preprocessors that implement code instrumentation (eg. [bisect](https://github.com/aantron/bisect_ppx), or [landmarks](https://github.com/LexiFi/landmarks)): they could implement the "identity preprocessor" when profile is "release" (also they could use the profile name as a scoping mechanism).  
Here is an example: 
```
(executable
(name test)
(preprocess (pps landmarks.ppx -- --profile "%{profile}"))
)
```
I made this PR to experiment with a profile-based workflow for landmarks and maybe to see if …
> Allow variables in pps flags

- CHANGES.md
- src/findlib.ml
> Do not fail when a findlib directory doesn't exist

- CHANGES.md
- src/lib.ml
Can we get @TheLortex as a reviewer on this?
@vsiles could you confirm this fixes your bug? #2085
> Remove all the shady Option.value_exn in lib.ml

- src/arg_spec.ml
- src/arg_spec.mli
- src/exe.ml
- src/link_time_code_gen.ml
- src/link_time_code_gen.mli
- src/mode.ml
- src/mode.mli
Refactoring to make #1930 easier.
- share more of the work between the various calls to `Link_time_code_gen.libraries_link`
- add a helper function for generating a module
I also removed the use of `lazy` since we are a bit careful about using lazy values now.
> Refactor Link_time_code_gen

- src/lib.ml
The previous code would load the entire findlib database. Now, this database is
loaded only when the variant map is necessary.
> Generate variant map more lazily

- src/exe.ml
- src/lib.ml
- src/lib.mli
- src/link_time_code_gen.ml
- src/link_time_code_gen.mli
- test/blackbox-tests/test-cases/findlib-dynload/run.t
By generating the same file in all modes and using `Dynlink.is_native` instead.
> Simplify Link_time_code_gen even more

- src/dune_project.ml
- src/install_rules.ml
- src/odoc.ml
- src/package.ml
- src/package.mli
Another small refactoring to make #1930 easier to review
> Refactor package version handling

- bin/import.ml
- bin/upgrade.ml
- bin/workspace_root.ml
- bin/workspace_root.mli
- src/dune_load.ml
- src/dune_load.mli
- src/file_tree.ml
- src/file_tree.mli
- src/main.ml
- src/main.mli
- src/vcs.ml
- src/vcs.mli
- test/unit-tests/dune
- test/unit-tests/vcs.mlt
In preparation for #1930. The module abstract and memoize `git describe ..` and a mercurial equivalent. This PR also add a test and attach vcs info to the file tree.
> Add a Vcs module to deal with git and hg

- CHANGES.md
- src/dune_file.ml
- src/dune_file.mli
- src/dune_package.ml
- src/dune_package.mli
- src/findlib.ml
- src/lib.ml
- src/lib.mli
- src/lib_info.ml
- src/lib_info.mli
- src/link_time_code_gen.ml
So that we can extend it to other libraries in the future without more hard-coding. After this patch, the matching on the name `findlib.dynload` is now done only when looking at the META file. So if someone was defining a `findlib.dynload` library via dune, it wouldn't get special treatment unless explicitly marked with `(special_builtin_support findlib_dynload)`, which is cleaner as well.
> Formalise special builtin support for findlib.dynload

- bin/exec.ml
- src/artifacts.ml
- src/artifacts.mli
- src/config.ml
- src/config.mli
- src/context.ml
- src/env_node.ml
- src/env_node.mli
- src/file_binding.ml
- src/file_binding.mli
- src/gen_rules.ml
- src/install_rules.ml
- src/local_package.ml
- src/local_package.mli
- src/opam_create.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/super_context.ml
- src/utils.ml
- src/utils.mli
All the installation directories live in the build directory, therefore this is
what we should return.
This is only the beginning as this type can be used in quite a few more places.
> Use Path.Build.t in some places

- CHANGES.md
- doc/opam.rst
- dune-project
- dune.opam
- dune.opam.template
- src/dune_project.ml
- src/dune_project.mli
- src/file_tree.ml
- src/file_tree.mli
- src/install_rules.ml
- src/local_package.ml
- src/local_package.mli
- src/opam_create.ml
- src/opam_file.ml
- src/opam_file.mli
- src/package.ml
- src/package.mli
- src/stdune/poly.ml
- src/stdune/poly.mli
- src/stdune/stdune.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/dune-project-meta/bad-opam-file/dune-project
- test/blackbox-tests/test-cases/dune-project-meta/run.t
- test/blackbox-tests/test-cases/dune-project-meta/test-fields/dune-project
- test/blackbox-tests/test-cases/dune-project-no-opam/dune
- test/blackbox-tests/test-cases/dune-project-no-opam/dune-project
- test/blackbox-tests/test-cases/dune-project-no-opam/run.t
> More progress on the opam generation

- src/ocaml-syntax-shims/pp.real.ml
On my machine, `make test` segfaults with master. Flushing the output when dumping the AST in `ocaml-syntax-shims` fixes the issue. Not sure why that makes dune segfault though, or why we didn't observe this before
> Flush the output in ocaml-syntax-shims

- CHANGES.md
- bin/common.ml
- bin/common.mli
- src/clflags.ml
- src/clflags.mli
- src/config.ml
- src/config.mli
- src/process.ml
In watch mode, the error messages from the full compilation commands are quite noisy. I think the correct default here is to omit them, at least by default. I'm not sure what's the best way to turn this into a user configurable option as it doesn't really fit into our display hierarchy.
> Trim error messages in watch mode

- src/build_system.ml
- src/rules.ml
- src/rules.mli
- Now directories can only pick up rules created in other directories by explicit call to `load_dir` and not by accident
- Build_system.prefix_rules is now done locally, without mutating a global ref
- Get rid of rule collector, replacing it with a simple flag for now (not stored in the table), but the plan is to get rid of that too when we replace the table with memoized function
> Pass rules between dirs without relying on side effect

- src/path_dune_lang.ml
- src/stdune/loc.ml
- src/stdune/loc0.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/path_intf.ml
- test/blackbox-tests/test-cases/custom-build-dir/run.t
* Path.of_string is for when we're sure the conversion cannot fail
* Path.parse_string_exn is for parsing user input
A parsing function that returns a Result.t wasn't necessary here as we don't really use this function in dune itself.
By the way, we still haven't decided about the convention for `Path.relative` and `Path.relative_exn`. We have the same situation, in some cases we are sure it's not going to fail and in others we are using user input and would like to return a `Result.t` to be handled by the caller.
> Adopt new parsing/string conversion convention for Path

- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/path_intf.ml
One could argue that for relative paths, the parent should never fail but give that we often use `parent` in conjunction with recursion, I think it's a bit safer to always have the user check.
> Consistent signature for Path.{parent,parent_exn}

- CHANGES.md
- src/dune_file.ml
- src/dune_file.mli
- src/expander.ml
- src/expander.mli
- src/lib_rules.ml
- src/merlin.ml
- src/preprocessing.ml
- src/preprocessing.mli
- src/super_context.ml
- src/super_context.mli
- test/blackbox-tests/test-cases/dune-ppx-driver-system/replaces/dune-project
- test/blackbox-tests/test-cases/external-lib-deps/dune-project
- test/blackbox-tests/test-cases/merlin-tests/dune
- test/blackbox-tests/test-cases/merlin-tests/exe/dune
- test/blackbox-tests/test-cases/merlin-tests/pp-with-expand/dune
- test/blackbox-tests/test-cases/merlin-tests/pp/dune
- test/blackbox-tests/test-cases/merlin-tests/run.t
- test/blackbox-tests/test-cases/meta-gen/dune-project
- test/blackbox-tests/test-cases/multi-dir/test4/dune-project
- test/blackbox-tests/test-cases/private-public-overlap/private-rewriter/dune-project
- test/blackbox-tests/test-cases/private-public-overlap/private-runtime-deps/dune-project
- test/blackbox-tests/test-cases/reason/dune-project
First of all, we are going to be more strict and error out if we can't expand
any variables for the .merlin. If this happens, then it's really a bug that we
should catch.
The functions that swallow expansion errors are removed because they're too easy
to misuse.
> Fix generation of -pp in .merlin

- CHANGES.md
- src/dune_project.ml
- src/dune_project.mli
- src/watermarks.ml
- test/blackbox-tests/test-cases/dune-project-meta/run.t
- test/blackbox-tests/test-cases/subst/run.t
As discussed in the opam file generation PR
> Make "dune subst" add a version field to dune-project

- src/stdune/path.ml
Previously, it would never return None.
Thanks for noticing @aalekseyev.
> Fix External.parent

- doc/opam.rst
- dune-project
- dune.opam
- src/dune_project.ml
- src/dune_project.mli
- src/opam_create.ml
This field is analogous to opam's doc field.
All this discussion about linting made me double check what the linter says about dune's opam file. Looks like it's useful after all :)
I'm undecided if we should call the field `doc` or `documentation`.
> Add documentation field to dune-project

- CHANGES.md
- src/action_exec.ml
If the directory that we're trying to create exists, then this is never an error.
We now forbid actions to create external or source dirs.
This should fix #2158
> Tweak mkdir_p uses

- src/preprocessing.mli
- src/super_context.ml
- src/super_context.mli
The returned paths are actually unused.
Also add to comments.
> Tighter type of Super_context.Deps.interpret.

- CHANGES.md
- doc/dune-files.rst
- src/blang.ml
- src/blang.mli
- src/context.ml
- src/dune_file.ml
- src/dune_file.mli
- src/lib.ml
- src/lib_config.ml
- src/lib_info.ml
- src/lib_info.mli
- src/pform.ml
- src/scope.ml
- src/string_with_vars.ml
- src/string_with_vars.mli
- test/blackbox-tests/test-cases/enabled_if/dune
- test/blackbox-tests/test-cases/enabled_if/dune-project
- test/blackbox-tests/test-cases/enabled_if/run.t
This replaces #1445 (I exchanged this PR for an OCaml PR with @dra27). It implements the same thing, except that the interpretation of the `enabled_if` field is done a bit, producing better error messages when the user tries to use a library that is disabled.
Additionally, only the newly added `os_type` variable is allowed in this field. This is to avoid making the set of library names too dynamic. While it doesn't matter too much right now, I have a feeling that making 
it too dynamic now might makes other things harder in the future.
> Allow the `enabled_if` field in `library` stanzas

- src/bootstrap.boot.ml
- src/bootstrap.mli
- src/file_tree.ml
Data only paths must only exist in the source
> Use source paths in bootstrap

- bin/print_rules.ml
- bin/target.ml
- src/build_system.ml
- src/build_system.mli
- src/file_tree.ml
- src/memo/memo.ml
- src/memo/memo.mli
- src/merlin.ml
- src/stdune/nothing.ml
- src/stdune/nothing.mli
- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/path_intf.ml
- test/blackbox-tests/test-cases/github2061/run.t
This converts more of the rule generation to purely functional style and memoizes the `load_dir` function.
The only remaining purpose of the `Build_system.files` field is stale directory deletion.
> Memoize load dir

- src/build.ml
- src/file_tree.ml
- src/file_tree.mli
The form `(source_tree <path>)` only makes sense for paths that exist in the source tree. Hence when we interpret this dependency, we can assume that all paths are going to come a directory belonging to a build context. This is because the corresponding source files have been copied.
This PR changes the evaluation of `source_tree` to make use of this fact and not consider directories that come from outside a context's build dir.
> Source_tree cannot be used for paths outside the context

- CHANGES.md
- doc/dune-files.rst
- src/context.ml
- src/context.mli
- src/dune_file.ml
- src/lib_config.ml
- src/lib_config.mli
- src/lib_info.ml
- src/pform.ml
Now these variables can be used along with os_type in the enabled_if
field of libraries
> Add model, architecture, system as enabled_if vars (#2164)kf

- src/build_system.ml
- src/rule.ml
- src/rule.mli
- src/stdune/bool.ml
- src/stdune/bool.mli
- src/stdune/path.ml
- src/stdune/path.mli
Never create directories outside the build dir, check for existence for all
other dirs.
I've tried to follow @diml's suggestion of just returning the build dirs in `Action.chdirs`, but I still don't see the point. We need to check for existence for the other dirs anyways. I think we could easily keep the old code where we return `Path.Set.t` and just call `Fs.mkdir_p_or_assert_exists` on everything.
There's still the issue of all the locs being absent. I'm not entirely sure this can be fixed but I will look into it.
> Fix chdir handling

- src/coq_rules.ml
- src/expander.ml
- src/scope.ml
- src/scope.mli
- src/super_context.ml
Scopes are not defined for directories outside the build dir. There's a still major scope related function that needs to change `Super_context.find_scope_by_dir`, but it will make this PR quite a bit bigger.
> Make scopes use the build dir

- src/stdune/ordering.ml
- src/stdune/ordering.mli
- src/stdune/path.ml
interened paths should not be compared like this.
> Fix use of polymorphic comparison

- src/dir_contents.ml
- src/dir_status.ml
- src/dir_status.mli
- src/stdune/path.ml
- src/stdune/path.mli
Dir_status is only kept for build directories and we use the correct
path type to reflect that.
This PR also addresses a faulty like looking check for the project root. The
project root is a source path, and the dir whose status we're getting is a build
path. There was no way those would be equal, the build dir's context has to be
stripped first.
> Patch Dir_status to use Path.Build.t where possible

- src/coq_rules.boot.ml
- src/coq_rules.ml
- src/coq_rules.mli
- src/gen_rules.ml
- src/install_rules.mli
- src/local_package.ml
- src/local_package.mli
- src/odoc.ml
- src/opam_create.ml
- src/opam_create.mli
- src/super_context.ml
- src/super_context.mli
- src/toplevel.ml
- src/utop.ml
Additionally, we port Opam_create's rule as well as it now becomes easy to do
so.
> Port Super_context.t to use Path.Build.t

- CHANGES.md
- src/c.ml
It's now quite easy to add support after introducing the C module.
Fixes #83
> Add support for the .cc extension for C++ sources

- src/dir_contents.ml
- src/dune_file.mli
- src/exe_rules.ml
- src/gen_rules.ml
- src/inline_tests.ml
- src/lib_info.ml
- src/lib_rules.ml
- src/module.ml
- src/module.mli
- src/obj_dir.ml
- src/obj_dir.mli
- src/odoc.ml
- src/toplevel.ml
- src/toplevel.mli
- src/utils.ml
- src/utils.mli
- src/utop.ml
- src/vimpl.mli
- src/virtual_rules.ml
- src/virtual_rules.mli
This is likely to have a small conflict with PR #2192. I'll clean it up once either one of the PR's is merged.
The list of public functions updated:
* Dune_file.obj_dir
* Module.odoc_file
* Obj_dir.make_lib
* Obj_dir.make_exe
* Toplevel.Source.make
* Utils.library_object_directory
* Utils.library_native_dir
* Utils.library_public_cmi_dir
* Utils.library_private_dir
* Vimpl.make
* Virtual_rules.impl
> Use Path.Build.t in Obj_dir and Utop

- CHANGES.md
- src/format_rules.ml
- test/blackbox-tests/test-cases/formatting/run.t
This will output errors relative to the correct directory.
@jordwalke Should a similar change be done to `refmt`?
> Run ocamlformat from build context root

- CHANGES.md
- src/local_package.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/odig-files-workspace/project/dune-project
- test/blackbox-tests/test-cases/odig-files-workspace/run.t
These files are relative to the project rather than the context. Otherwise, they
will not be included in the .install file in composed builds.
I will add a test if this is fix is indeed what we want.
> Fix detecting odig files for installation

- CHANGES.md
- src/dune_file.ml
- src/dune_file.mli
- src/merlin.ml
- test/blackbox-tests/test-cases/merlin-tests/run.t
Previously, if the pps were all ppx and equivalent, then they would
be dropped.
Fix #2206
> Fix generation of melrin with equal ppx pp

- doc/jsoo.rst
There is currently no value in Introducing the "jsoo" abbreviation.
The term "jsoo" is used exactly once (excluding the sentence where the abbreviation is introduced), while "js_of_ocaml" is used 11 times. Moreover, at most places in the doc, "js_of_ocaml" can't be easily replaced with "jsoo", as it refers to either the command line tool, or to the dune configuration, where it is named js_of_ocaml and not jsoo.
So it makes more sense to just remove "jsoo", which shortens the documentation by a whole sentence and expands the one occurrence.
> Remove unused abbreviation "jsoo"

- bench/dune_bench/file_tree_cache.ml
- bench/dune_bench/scheduler_bench.ml
- bin/common.ml
- bin/subst.ml
- src/main.ml
- src/stdune/path.ml
- src/stdune/path.mli
- test/unit-tests/action.mlt
- test/unit-tests/path.mlt
- test/unit-tests/tests.mlt
- test/unit-tests/vcs.mlt
Also move some build related functions to Path.Build
> Make Path.Build.to_string equivalent to Path.to_string

- CHANGES.md
- src/format_rules.ml
- src/preprocessing.ml
- src/refmt.ml
- src/refmt.mli
- src/stdune/bin.mli
- test/blackbox-tests/test-cases/formatting/run.t
This is consistent with how we convert reason sources to OCaml ast. To keep
formatting and compilation consistent, we introduce a Refmt module that handles
these details in one place.
> Run refmt from the context's root dir

- bin/install_uninstall.ml
- test/blackbox-tests/test-cases/install-dry-run/run.t
- test/blackbox-tests/test-cases/install-libdir/run.t
When uninstalling a package, the old code was checking every single directory that we deleted files in so far after delete every single file.
Now we just do it once at the end.
> Move directory deletion outside the inner loop in `dune uninstall`

- src/dep_graph.ml
- src/dep_graph.mli
- src/ocamldep.ml
- src/ocamldep.mli
- src/virtual_rules.ml
Use Path.Build.t in ocamldep/dep_graph wherever this makes sense. This changes
the following public changes:
* Dep_graph.make
* Ocamldep.graph_of_remote_lib
> Port Dep_graph to Path.Build.t

- bin/install_uninstall.ml
- src/fiber/fiber.ml
- src/fiber/fiber.mli
- src/upgrader.ml
- test/unit-tests/vcs.mlt
Some of the function names in the `Fiber` module were not great. This PR does the following renaming:
- `map_all` -> `sequential_map`
- `map_all_unit` -> `sequential_iter`
It also deletes the following unused functions:
- `all`
- `all_unit`
> Rename and delete a few fiber functions

- src/alias.ml
- src/alias.mli
- src/build_system.ml
- src/check_rules.ml
- src/dep.ml
- src/format_rules.ml
- src/gen_rules.ml
- src/inline_tests.ml
- src/install_rules.ml
- src/merlin.ml
- src/odoc.ml
- src/opam_create.ml
- src/preprocessing.ml
- src/rules.ml
- src/simple_rules.ml
- src/stdune/path.ml
- src/stdune/path.mli
Public functions modified:
* Alias.make
* Alias.dir
* Alias.fully_qualified_name
* Alias.{default,runtest,install,doc,private_doc,lint,all,check,fmt,default}
* Alias.stamp_file
* Alias.alias_dir (introduced to get rid of copying)
> Switch aliases module to use Path.Build.t

- src/build_system.ml
- src/build_system.mli
- src/gen_rules.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/path_intf.ml
This PR mostly touches upon internal code in Build_system.t but a few
public functions are touched:
* Build_system.set_rule_generators
* Build_system.set_packages
> Port more code to use to use Path.Build.t appropriately

- src/dir_contents.ml
- src/module.ml
- src/module.mli
- src/modules_field_evaluator.ml
Previously, they would just duplicate the fields name, intf, and impl.
> Make Module.Source.t a part of Module.t

- src/check_rules.ml
- src/check_rules.mli
- src/compilation_context.ml
- src/compilation_context.mli
- src/dir_contents.ml
- src/dune_file.ml
- src/dune_file.mli
- src/exe_rules.ml
- src/inline_tests.ml
- src/lib_info.ml
- src/lib_rules.ml
- src/link_time_code_gen.ml
- src/menhir.ml
- src/module_compilation.ml
- src/modules_field_evaluator.ml
- src/modules_field_evaluator.mli
- src/obj_dir.ml
- src/obj_dir.mli
- src/ocamldep.ml
- src/toplevel.ml
- src/toplevel.mli
- src/vimpl.ml
- src/virtual_rules.ml
This is a representation of the object directory where we know all the paths are
build paths. It allows us to remove a bunch of _exn calls to conver those paths
to build paths.
> Add Obj_dir.Local to public API

- src/build_system.ml
- src/build_system.mli
- src/gen_rules.ml
- src/install_rules.ml
- src/install_rules.mli
- src/scheme.ml
- src/scheme.mli
- test/blackbox-tests/test-cases/github2228/run.t
- test/unit-tests/scheme.mlt
This is a fix for #2228.
The problem is that stale artifact deletion doesn't know that the install directories should be kept.
This PR makes us correctly track that.
I'm working on a follow-up change that makes build system more robust to such problems.
As it stands, I have low confidence that the fix is complete.
> Correctly keep track of install subdirectories to keep

- src/module.ml
- src/module.mli
- src/virtual_rules.ml
The ?ext is only set for .o files. This isn't strong enough justification to
keep this argument around.
> Remove ?ext arg from the Module.cm_file family of functions

- src/action_to_sh.ml
- src/stdune/dyn0.ml
- src/stdune/pp.ml
- src/stdune/pp.mli
I originally thought it was a good idea, but as I'm converting error messages to the new API, I realise that it's not that great and it makes things more confusing than anything else. In particular, one could think that the element of the list are separated by cuts, which is not the case.
> Change the Pp.*box API to not take lists

- src/stdune/path.ml
- src/stdune/path_intf.ml
Remove Path.is_suffix because it's a strange funcion and it's unused.
> remove Path.is_suffix

- src/install_rules.ml
- src/lib.ml
- src/lib.mli
- src/local_package.ml
- src/local_package.mli
- src/obj_dir.ml
- src/obj_dir.mli
- src/odoc.ml
- src/super_context.ml
- src/super_context.mli
- src/virtual_rules.ml
This type allows us to access to local versions of some artifacts without _exn. Unfortunately, we need to push some of the _exn calls into `Lib.Local` itself, but this still seems like an improvement. `Lib.Local.of_lib_exn` can also be eliminated with a little more effort.
> Introduce Lib.Local.t

- src/check_rules.ml
- src/check_rules.mli
- src/compilation_context.ml
- src/compilation_context.mli
- src/dir_contents.ml
- src/dune_file.ml
- src/dune_file.mli
- src/dune_package.ml
- src/dune_package.mli
- src/exe_rules.ml
- src/inline_tests.ml
- src/install_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_info.ml
- src/lib_info.mli
- src/lib_modules.mli
- src/lib_rules.ml
- src/link_time_code_gen.ml
- src/module.ml
- src/module.mli
- src/module_compilation.ml
- src/modules_field_evaluator.mli
- src/obj_dir.ml
- src/obj_dir.mli
- src/ocamldep.ml
- src/toplevel.ml
- src/toplevel.mli
- src/vimpl.ml
- src/virtual_rules.ml
This PR parameterizes the `Obj_dir.t` by the type of paths that it returns. This allows us to use a single API for accessing Obj_dir.t values. But more importantly, it allows us to parameterize other code more easily - such as modules.
In particular, currently Module.t's contain two values that should be different between local modules and ones that were created by decoding dune-package files. To accommodate both kinds, we can do:
```
type 'path module =
{ name : Name.t
; source : 'path Source.t
; obj_dir : 'path Obj_dir.t
...
}
```
So now we'll have a single set of functions for module and they will all return the right paths.
The motivation for this is that I've tried introducing local modules to get rid of the last few _exn's and simplify virtual library copying rules (currently the …
> Add polymorphic Obj_dir.t operations

- src/dir_set.ml
- src/dir_set.mli
- src/scheme.ml
- src/scheme.mli
- src/stdune/path.ml
- src/stdune/path.mli
- src/stdune/path_intf.ml
We've previously thrown around an idea of making the type of paths polymorphic over a type variable that represents the root, so that the three types of paths (Local, Build, Source) are the same type and you can write code polymorphic over them.
This PR implements this idea and makes use of that to make the type of Dir_set more precise: the thing about Dir_set is that `descend` function returns a Dir_set that's no longer rooted where the original Dir_set was rooted, so it also benefits from the same type variable.
> Local path polymorphic over its root

- src/dir_contents.ml
- src/dune_package.ml
- src/exe.ml
- src/inline_tests.ml
- src/install_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_modules.ml
- src/lib_modules.mli
- src/lib_rules.ml
- src/link_time_code_gen.ml
- src/menhir.ml
- src/module.ml
- src/module.mli
- src/module_compilation.ml
- src/modules_field_evaluator.ml
- src/modules_field_evaluator.mli
- src/obj_dir.ml
- src/obj_dir.mli
- src/odoc.boot.ml
- src/odoc.ml
- src/odoc.mli
- src/toplevel.ml
- src/vimpl.ml
- src/virtual_rules.ml
All cm files are now fetched through Obj_dir.Module instead of Module.
This means that we don't need an obj_dir in Module.t anymore.
As discussed in the email. I will update this description with those details later.
> Make artifact access go through Obj_dir.t

- bin/common.ml
- bin/subst.ml
- bin/util.ml
- src/build_system.ml
- src/dep_path.ml
- src/main.ml
- src/path_dune_lang.ml
- src/process.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/super_context.ml
- src/utils.ml
- src/utils.mli
- test/unit-tests/action.mlt
- test/unit-tests/path.mlt
- test/unit-tests/tests.mlt
- test/unit-tests/vcs.mlt
Clean up various things that were matching on path kind.
Rewrite the two things that were actually using `Path.kind` or `Path.kind_raw` to match on path directly.
Rename Path.Kind -> Path.Build.Kind because it's only used to set the build directory root now.
And rename its constructor Local -> In_source_dir to remove the confusion between the Local module and this thing.
> Path.Kind cleanup

- src/artifacts.ml
- src/coq_rules.ml
- src/gen_meta.ml
- src/js_of_ocaml_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_info.ml
- src/lib_info.mli
- src/link_time_code_gen.ml
- src/local_package.ml
- src/merlin.ml
- src/odoc.ml
- src/preprocessing.ml
- src/sub_system.ml
- src/utop.ml
- src/virtual_rules.ml
We should have done this refactoring when Lib_info was introduced, but there were other things to do. Most of these fields aren't accessed so often. We might as well just use Lib_info.t directly.
> Lib info direct access

- src/module.ml
- src/module.mli
- src/obj_dir.ml
- src/obj_dir.mli
- src/ocamldep.ml
- src/virtual_rules.ml
This is consistent with the other artifacts. The virtual library rules
need to know where these files are, so they can no longer stay private
to ocamldep.
> Move ocamldep artifacts to Obj_dir

- src/build_system.ml
- src/memo/memo.ml
- src/memo/memo.mli
- src/stdune/dyn.mli
- src/stdune/dyn0.ml
- src/stdune/string.ml
- src/stdune/string.mli
- src/stdune/string_split.ml
- src/stdune/string_split.mli
Improve the reporting of `Code_error` errors that happen in memoized functions.
We make them additionally report the memo call stack and, where easy, show correct interleaving of Memo stack frames and OCaml stack frames.  (which doesn't seem easy for async call frames)
An example is below. The interesting new bits is the interleaving between:
- \"src/build_system.ml\", line 1120
- "load-dir", "default/enabled/no-source-code/.formatted"
- \"src/build_system.ml\", line 1197
- "load-dir", In_build_dir ".aliases/default/enabled/no-source-code/.formatted"
And then the entire `outer_call_stack` is newly-reported.
```
Error: exception {exn =
("Generated rules in a directory not allowed by the parent",
{dir = "default/enabled/no-source-code/.formatted";
rules = [Alias {name = "fmt"}]});
backtrace …
```
> Better Code_error reporting

- src/compilation_context.ml
- src/compilation_context.mli
- src/exe.ml
- src/exe.mli
- src/exe_rules.ml
- src/lib_rules.ml
- src/module_compilation.ml
- src/module_compilation.mli
Those were always passed manually along with the compilation context.
Doing it via the compilation context reduces the boilerplate.
> Move jsoo options to Compilation_context

- src/artifacts.ml
- src/coq_rules.ml
- src/gen_meta.ml
- src/install_rules.ml
- src/js_of_ocaml_rules.ml
- src/lib.ml
- src/lib.mli
- src/lib_info.ml
- src/lib_info.mli
- src/link_time_code_gen.ml
- src/local_package.ml
- src/merlin.ml
- src/odoc.ml
- src/preprocessing.ml
- src/sub_system.ml
- src/utop.ml
- src/virtual_rules.ml
This PR plans to accomplish:
```ocaml
val stubs : t -> dir:Path.Build.t -> Path.Build.t
val stubs_archive : t -> dir:Path.Build.t -> ext_lib:string -> Path.Build.t
val dll : t -> dir:Path.Build.t -> ext_dll:string -> Path.Build.t
val archive : t -> dir:Path.Build.t -> ext:string -> Path.Build.t
```
After this change, library artifacts will be consumed the same way everywhere.
> Library artifact refactoring (#2277

- src/colors.ml
- src/dune_lang/dune_lang.ml
- src/obj_dir.mli
- src/ocaml_flags.ml
- src/scheme.mli
- src/stdune/io.ml
- src/stdune/list.ml
- src/stdune/pp.ml
- src/stdune/result/result.ml
- src/stdune/result/result.mli
- src/stdune/sexp.ml
- src/stdune/stdune.ml
A few things that we use are deprecated in 4.08:
- `Pervasives`
- the `tag` functions of the `Format`  module
Since we are currently keeping compatibility with OCaml >= 4.02, i simply disabled warning 3 for these. I also disabled the new warning 66 in dev mode, since it is causing a lot of code in Dune, and I expect in many projects to break. This warning is for unused `open!`, which we often use to keep `open Stdune` or similar even when they are not used.
BTW, testing 4.08 in the CI is going to be annoying as a lot of compiler messages changed in 4.08. I.e. the captured output will be different between < 4.08 and >= 4.08 :(
> Fix compilation in --dev mode with 4.08

- src/compilation_context.ml
- src/compilation_context.mli
- src/lib_rules.ml
- src/module_compilation.ml
- src/module_compilation.mli
Passing `dynlink` & `sandbox` via the compilation context saves us passing around these variables. Also, since executables are going to have their own alias modules, we might as well handle it in a place shared between executables and libraries.
> Compilation context params

- src/compilation_context.ml
- src/compilation_context.mli
- src/exe_rules.ml
- src/inline_tests.ml
- src/link_time_code_gen.ml
- src/toplevel.ml
- src/utop.ml
- test/blackbox-tests/test-cases/trace-file/run.t
#2297 accidentally changed the `dynlink` status for executables to `false`, breaking the production of shared objects. This PR makes this parameter explicit to lower the chances of getting it wrong in the future. For executables, it sets it to `true` only if the user requested building a shared object.
> Make the "dynlink" argument of Compilation_context.create required

- CHANGES.md
- doc/dune-files.rst
- src/cinaps.boot.ml
- src/cinaps.ml
- src/cinaps.mli
- src/dune_file.mli
- src/gen_rules.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/cinaps/run.t
[Cinaps](https://github.com/janestreet/cinaps) is a small tool that allows to auto-generate parts of ml or other source files and keep them in sync. This PR adds integration into dune to make it easier to use it in dune projects.
I still need to write the doc, however this is ready for testing. /cc @ceastlund
> Add support for cinaps

- src/dep_graph.ml
- src/exe.ml
- src/lib_rules.ml
- src/module_compilation.ml
- src/module_compilation.mli
The previous behavior was to get all the modules in the compilation context, but then to filter out the alias module. That is quite confusing and we might as well just pass the modules that we want to compile explicitly.
> Refactor interaction between compilation context and module compilation

- src/dep_graph.ml
- src/dep_graph.mli
- src/lib_rules.ml
- src/ocamldep.ml
- src/virtual_rules.ml
Now the dependency graph can be reliably represented for entire libraries -- there's no longer a need for a separate graph compatibility modules and implementations of virtual libraries
It also future proofs us for when we introduce qualified subdirs. The dependency graph will be able to contain all dependencies for such libraries as well.
Also, this makes the merging of impl and vlib dep graphs quite trivial. See the 3rd commit for how simple it looks.
> Make Dep_graph keyed by obj_name

- doc/dune-files.rst
- doc/installation.rst
- doc/usage.rst
This PR adds a section "Installation" to the manual that regroups all the information about installing things with Dune.  That should make things clearer and more discoverable.
> Rework install doc

- bin/common.ml
- test/blackbox-tests/test-cases/github25/run.t
- test/blackbox-tests/test-cases/misc/run.t
This PR introduces a function `one_of` that makes use the of `Term.with_used_args` to easily implement incompatible options with cmdliner:
```ocaml
val one_of : 'a Term.t -> 'a Term.t -> 'a Term.t
```
We have several sets of options that are incompatible in the CLI and this PR simplify their definitions. In addition, the error message now reports the exact names of the incompatible options rather than always their long forms.
> Simplify handling of incompatible options

- CHANGES.md
- bin/common.ml
- bin/common.mli
- doc/usage.rst
- src/clflags.ml
- src/clflags.mli
- src/install_rules.ml
- src/wp/dune-impl/wp.ml
- src/wp/jbuilder-impl/wp.ml
- src/wp/wp.boot.ml
- src/wp/wp.mli
They are only useful for opam builds and they are annoying for development. This PR proposes to only promote them to the source tree when `--promote-install-files` is passed on the command line. `-p` implies `--promote-install-files`. This should go in Dune 2.0.0 only.
> Do not promote install files by default

- CHANGES.md
- src/dune_project.ml
The previous default was to allow such deps. From experience with this
feature in dune, it's ready for mass consumption.
cc @ocaml/dune-dev in case anyone has some last minute objections.
> Change implicit_transive_deps to be false for 2.0

- bin/install_uninstall.ml
- bin/print_rules.ml
- src/colors.ml
- src/colors.mli
- src/console.ml
- src/console.mli
- src/main.ml
- src/process.ml
- src/report_error.ml
- src/scheduler.ml
- src/stdune/ansi_color.ml
- src/stdune/ansi_color.mli
- src/stdune/dyn0.ml
- src/stdune/pp.ml
- src/stdune/pp.mli
- src/stdune/user_error.ml
- src/stdune/user_message.ml
- src/stdune/user_message.mli
- src/stdune/user_warning.ml
- src/stdune/user_warning.mli
- test/blackbox-tests/test-cases/install-partial-package/run.t
- test/unit-tests/pp.mlt
This PR converts a few more modules to the new error reporting API. `Process` was a bit more complicated since it embeds the output of sub-commands in error message. To deal with that, we now parse the ANSI escape sequence in the output of commands.
It also simplify the rendering API and restore coloring of error messages that use the new API.
> Convert `Process`, `Scheduler` and `Console` to the new error reporting API and restore coloring

- src/build.ml
- src/build.mli
- src/cm_files.ml
- src/cm_files.mli
- src/exe.ml
- src/exe_rules.ml
- test/blackbox-tests/test-cases/github660/run.t
The desired behavior for dune 2.0:
* Ask for all .cmx/.o files statically
* Only use topsorted .cmx files for linking
For < 2.0
* Topsort modules
* Ask for the topsorted subsets of .cmx/.o files dynamically
* Only use topsorted .cmx for linkig
> Fix building exe

- bin/common.ml
- bin/main.ml
- otherlibs/build-info/src/build_info.ml
- otherlibs/build-info/src/build_info.mli
- otherlibs/build-info/test/run.t
By not exposing naked values. This allows us to implement laziness or
some sort of transparent loading down the road.
Add a find primitive for statically linked libraries. We could easily
make this common look up faster down the road.
Some other things to consider:
* Implement comparison for versions
* Add a folding primitive for all statically linked libraries. This is useful if we ever change the representation of loaded libs to be a map for example.
> Future proof build info

- src/dep_graph.ml
- src/module.ml
- src/module.mli
Previously, we'd be using the module name to lookup the compilation
unit. However, the obj_map is keyed by the real units or "object names".
> Fix closure calculation for dep graphs

- src/exe.ml
- src/lib_rules.ml
- src/menhir.ml
- src/ocamldep.ml
- src/ocamldep.mli
These helpers aren't so useful and in an upcoming PR we'll be taking the dep graph for all modules at once.
> Remove the Ocamldep.generic functions

- src/module.ml
It should be the object name rather module name. In module.ml, name =
string, so the two types were confused.
@diml perhaps it makes sense to introduce `Moudle_name.t`? I could write an internal interface for `Module.Name` inside module.ml, but it would really be just copy pasted from the mli.
> Wrong key for for top closure

- src/compilation_context.ml
- src/context.ml
- src/exe.ml
- src/lib.ml
- src/lib.mli
- src/lib_config.ml
- src/lib_config.mli
- src/lib_rules.ml
- src/preprocessing.ml
- src/scope.ml
- src/super_context.ml
- src/toplevel.ml
It's eaier to pass this parameter like other lib config values through
the database. The client code is now simplified and doesn't need to
carry contexts around.
> Remove stdlib_dir for various flag functions

- src/dune_lang/dune_lang.ml
- src/dune_lang/dune_lang.mli
- src/dune_lang/lexer.ml
- src/dune_lang/lexer.mli
- src/dune_lang/lexer_shared.ml
- src/dune_lang/lexer_shared.mli
- src/format_dune_lang.ml
- src/lib_name.ml
- src/report_error.ml
- test/blackbox-tests/test-cases/format-dune-file/run.t
- test/unit-tests/sexp.mlt
- `Dune_lang.Parse_error`, it was only caught by `Report_error` so we can use `User_error.raise` instead
- `Lib_name.Invalid_lib_name`: it was never caught, turned into a `Code_error.raise` instead
> Remove a few more custom exceptions

- src/dune
It uses stdune which includes this dependency
> Remove dune_result from dune's deps

- otherlibs/build-info/src/dune
- src/dune_file.ml
- src/link_time_code_gen.ml
This allows us to wrap the build info library and maintain some encapsulation of the generated modules.
The way this is currently done is a bit hackish, let's wait for #2305 to be merged to fix this.
> Add support for wrapped code gen modules

- bin/installed_libraries.ml
- src/findlib.ml
- src/findlib.mli
- test/unit-tests/tests.mlt
@diml One thing I'm wondering about is how to make your `Pp` module usable with the toplevel. It seems like we'll still need to write `Format` printers for the toplevel, but it's quite tedious to have to do that. Is there a way to somehow have formatters be derived automatically for `Dyn.t` converters?
> Convert Fmt.t instances to Dyn

- src/check_rules.ml
- src/ml_kind.ml
- src/ml_kind.mli
- src/obj_dir.ml
Previously they were spread across Obj_dir and Check_rules
> Move .cmt & .cmti exts to Ml_kind

- src/exe_rules.ml
- src/lib_rules.ml
- src/merlin.ml
- src/merlin.mli
Since we introduced wrapped mode for executables, the same logic for flags is duplicated for libraries and executables. This PR moves this logic to `Merlin.make`. I also take the chance to clean up the object directory handling.
> Refactor creating Merlin.t

- src/obj_dir.ml
- src/obj_dir.mli
- src/ocamldep.ml
- src/virtual_rules.ml
When we get such deps from external modules, we don't really know the
original filename. This is a more consistent assumption if deps are
obtained from ocamlobjinfo or ocamldeps.
> Transitive no longer depend on module name

- src/module.ml
- src/module.mli
- src/obj_dir.ml
- src/obj_dir.mli
- src/odoc.ml
- src/utils.ml
- src/utils.mli
- test/blackbox-tests/test-cases/multiple-private-libs/run.t
- test/blackbox-tests/test-cases/odoc-unique-mlds/run.t
- test/blackbox-tests/test-cases/odoc/run.t
A parallel odoc directory structure isn't necessary anymore.
By the way, this also moves the .odoc files for private modules to the same directory as other modules. I believe this is consistent with @trefis suggestion that dune should not be hiding anything from odoc.
> Switch odoc dir to object directory

- .travis-ci.sh
- bin/compute.ml
- src/build_system.ml
- src/coq_rules.ml
- src/dep.ml
- src/dep.mli
- src/file_selector.ml
- src/file_selector.mli
- src/main.ml
- src/memo/memo.ml
- src/memo/memo.mli
- src/ocamlobjinfo.mli
- src/ocamlobjinfo.mll
- src/package.ml
- src/package.mli
- src/predicate.ml
- src/predicate.mli
- src/report_error.ml
- src/stdune/dyn.ml
- src/stdune/dyn.mli
- test/expect-tests/dune
- test/expect-tests/findlib_tests.ml
- test/unit-tests/dune
- test/unit-tests/dune_file.mlt
- test/unit-tests/ocamlobjinfo.mlt
This PR converts one of the unit test to ppx_expect.
PROS:
- we can use merlin in the test code \o/
- the dune file is much simpler
- we have more control over the structure of the code, i.e. we don't have to do everything at the toplevel
- we don't need to install printers and put `[%%ignore]` statements
CONS:
- we have to print things manually rather than rely on the toplevel
As a I needed a few Pp.t returning functions, I converted a few Format users to Pp. I also just deleted a bunch of `X.pp` functions that were unused
> Ppx expect

- src/print_diff.ml
use `git diff --no-index --color=always` over `diff` (no --color on macOS)
Somehow this still does not color the diff, whereas running the printed
command in a terminal does. Resolves ocaml/dune#2381.
> colored output for diff action

- src/compilation_context.ml
- src/compilation_context.mli
- src/dep_graph.ml
- src/dep_graph.mli
- src/dep_rules.ml
- src/dep_rules.mli
- src/exe.ml
- src/lib_rules.ml
- src/menhir.ml
- src/modules.ml
- src/modules.mli
- src/ocamldep.ml
- src/ocamldep.mli
- src/vimpl.ml
- src/vimpl.mli
- src/virtual_rules.ml
- src/virtual_rules.mli
Instead of taking vlib and impl dep graphs separately and then merging
them, we now have a higher level dependency procedure that is aware of
the special treatment implementations of virtual libraries need.
> Implement compound dependency rules for vlibs

- CHANGES.md
- src/compilation_context.ml
- src/env_node.ml
- src/ocaml_flags.ml
- src/ocaml_flags.mli
- src/toplevel.ml
- src/utop.ml
- test/blackbox-tests/test-cases/merlin-tests/run.t
- test/blackbox-tests/test-cases/trace-file/run.t
To get the default set of warnings, we must pass the syntax version.
I do not mention this specifically in the change list, as we can just pretend it was always like this and this is the first time we're changing things.
> Warning defaults now depend on version

- src/ocaml_flags.ml
- src/syntax.ml
- test/blackbox-tests/test-cases/merlin-tests/run.t
- test/blackbox-tests/test-cases/trace-file/run.t
This prevents new version of OCaml breaking the dev build. New warnings
should be introduced in a dune version aware way.
> Use stable set of warnings

- src/opam_create.ml
- src/package.mli
This PR removes `Local_package` from `Opam_create`. To replace it, all we need is a simple function that gives us all the packages defined in a directory.
> Do not use Local_package in Opam_create

- src/action.ml
- src/action.mli
- src/action_ast.ml
- src/action_dune_lang.ml
- src/action_dune_lang.mli
- src/action_exec.ml
- src/action_intf.ml
- src/action_mapper.ml
- src/action_mapper.mli
- src/action_unexpanded.ml
- src/action_unexpanded.mli
- src/build.ml
- src/build_system.ml
- src/command.ml
- src/dpath.ml
- src/dpath.mli
- src/expander.ml
- src/expander.mli
- src/inline_tests.ml
- src/module_compilation.ml
- src/preprocessing.ml
- src/simple_rules.ml
- src/stdune/path.ml
- src/stdune/path.mli
- src/super_context.ml
- test/blackbox-tests/test-cases/dune-jbuild-var-case/run.t
- test/blackbox-tests/test-cases/null-dep/run.t
- test/blackbox-tests/test-cases/rule-target-external/run.t
- test/unit-tests/action.mlt
Use `target = Path.Build.t` for the arguments of actions that modify things. Only allowing to modify build paths is allowed
Simplify sandboxing. Source paths and external paths are never sandboxed, so just make the sandboxing work on build paths.
> More precise action arguments

- src/lib.ml
Another instance of what is detailed in https://github.com/ocaml/dune/pull/2342 ; until https://github.com/ocaml/dune/issues/2298 is fixed I guess we'll have to live with commits like this.
> Fix build with OCaml trunk.

- CHANGES.md
- doc/advanced-topics.rst
- doc/dune-files.rst
- dune-project
- src/binary_kind.ml
- src/binary_kind.mli
- src/cinaps.ml
- src/compilation_context.ml
- src/compilation_context.mli
- src/dune_file.ml
- src/dune_file.mli
- src/dune_project.ml
- src/dune_project.mli
- src/exe.ml
- src/exe.mli
- src/exe_rules.ml
- src/gen_rules.ml
- src/inline_tests.ml
- src/lib_rules.ml
- src/link_time_code_gen.ml
- src/mode.ml
- src/mode.mli
- src/toplevel.ml
- src/utop.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/explicit_js_mode/dune
- test/blackbox-tests/test-cases/explicit_js_mode/dune-project
- test/blackbox-tests/test-cases/explicit_js_mode/run.t
- test/blackbox-tests/test-cases/explicit_js_mode/sub/dune
Fixes #1675 and #1940 
This is a first try at having a `(explicit_js_mode)` as discussed in #1675.
From a user perspective, it works as follows: when activated, `.bc.js` targets are only set up if the `(executable ...)` stanza contains `js` or `(byte js)` in its `(modes ...)` field.
Suggestions welcome!
> Explicit js mode

- dune-build-info.opam
- dune-build-info.opam.template
These tests aren't tied to any package, and hence cannot be run
separately from dune.
> Disable the build info tests

- src/gen_rules.ml
- src/lib_rules.ml
- src/lib_rules.mli
- src/odoc.boot.ml
- src/odoc.ml
- src/odoc.mli
The plan is to refactor the code so that the odoc rules aren't generated eagerly for the library anymore.
> Remove functor from lib_rules and make odoc use compilation_context

- bin/target.ml
- src/install.ml
- src/install_rules.ml
- src/stdune/path.ml
- src/stdune/path.mli
- test/expect-tests/stdune/path_tests.ml
This function only works when the second argument is in the source, so
we should just use that function.
> Remove Path.append

- src/install.mli
The fields are not used anywhere
> Make install paths abstract

- src/odoc.ml
Previously, the list of odocs per package and library was obtained by
globing the odocs target dir. That's a bit dodgy because it relied on
all the rules that generated such odocs to fire. The new code just
simply generates the list of odocs from the sources without making any
assumptions.
> Remove globs from odoc

- doc/foreign-code.rst
This stanza is deprecated and is replaced by data_only_dirs instead.
Fix #2446
> Do not use ignored_subdirs in documentation

- bin/common.ml
- bin/common.mli
- bin/import.ml
- bin/installed_libraries.ml
- bin/main.ml
- bin/target.ml
Previously, we would just ignore this value and hence `-p` would set to `@install` only because the default target was `@install`.
> Set default target from Common.t

- src/dune_project.ml
Previously, it would default to false when absent.
This doesn't need a CHANGES entry since the default is indeed `false` for all released versions.
> Fix default of explicit js mode

- src/virtual_rules.boot.ml
These aren't necessary as dune doesn't use virtual libraries anymore
> Remove virtual rules from bootstrap

- src/ocamlobjinfo.boot.ml
This module is not necessary for bootstrapping
> Remove ocamlobjinfo from bootstrap

- dune-project
The main benefit is that we get a slight boost when in parallelilsm when
building dune itself and get to remove some boilerplate in the
dune-project file.
> Switch dune to lang 2.0

- doc/dune-files.rst
- doc/faq.rst
- doc/project-layout-specification.rst
- doc/usage.rst
Instead, rephrase using "repository root".
Closes #308
> doc: only use "toplevel" in the OCaml sense

- src/build_system.ml
- test/blackbox-tests/test-cases/sandboxing/run.t
* The first commit ports the tests to OSX (hopefully)
* The second commit reproduces an assertion failure in the sandboxing code.
@aalekseyev let's try to avoid using bash in the tests as much as possible :)
> Sandboxing tests osx

- doc/dune-files.rst
- src/context.ml
- src/context.mli
- src/dune_env.ml
- src/dune_env.mli
- src/env_node.ml
- src/env_node.mli
- src/ocaml_flags.ml
- src/ocaml_flags.mli
- src/super_context.ml
- src/workspace.ml
- src/workspace.mli
Since it is already a list, it simplifies some part and remove one negligible optimization, which allowed to not create `env_node` of empty `env`.
The documentation for `env-vars` is updated.
> Remove the option in Dune_env.Stanza.t option

- src/cached_digest.ml
- src/stdune/float.ml
- src/stdune/float.mli
- src/stdune/hashtbl.ml
- src/stdune/hashtbl_intf.ml
- src/stdune/table.ml
- src/stdune/table.mli
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/incremental-rebuilds/run.t
Dune uses filesystem timestamps to detect file modifications. 
Not all filesystems record precise timestamps though. If two modifications happen at the same timestamp, dune gets confused.
In particular, if the following happens:
- file is written to (at time t0)
- dune reads file, records its digest and timestamp
- file is written to again (still at time t0)
then we end up with a stale digest associated with the current timestamp.
There are three scenarios to consider where this matters:
1. The file is in a build directory and is modified only by dune.
2. The file is in a source directory and is modified by a script that runs sequentially with dune.
3. The file is in a source directory and is modified by a user in parallel with dune.
We saw no obvious fix that'd be good for all (1,2,3) …
> Filesystem timestamp precision problem

- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/corrections/run.t
This PR adds a reproduction of some issues with `diff?` described in #2482.
> Add a test of weird behaviors of `diff?`

- doc/documentation.rst
This was still using jbuild syntax.
> doc: switch to dune syntax for (documentation)

- doc/opam.rst
Since ocaml/opam-repository#14266 it is a policy to not have dune marked as a build dependency but the dune documentation still has an example with dune marked as a build dependency.
> Remove the build tag from dune in the documentation

- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/github1541/run.t
This test shows the errors that we get when we try to expand a percent
form from a missing library or binary.
cc @ejgallego and @jorisio I will close #1541 as it seems it was fixed sometime.
> Add test to attempt to reproduce 1541

- test/blackbox-tests/test-cases/github1541/run.t
These macros should be expandable in the `deps` field as well.
> Add test cases for %{bin} and %{lib} in (deps ..)

- src/c_sources.ml
- src/context.ml
- src/coq_module.ml
- src/coq_module.mli
- src/dir_contents.ml
- src/expander.ml
- src/modules_field_evaluator.ml
- src/ordered_set_lang.ml
- src/ordered_set_lang.mli
I removed all the functors for the unordered case since it's just passing one function. For the unordered case, there's still a functor because maps aren't polymorphic. However, the resulting modules are at least polymorphic in the values. Lastly, there's a couple of minor unrelated changes. No_loc is now unified under the same functor and the is_standard optimization is done in only one place.
This is a pre-requesite for `per_file`.
> Simplify Ordered_set_language

- CHANGES.md
- src/dune/scheduler.ml
Print the following on every new build in watch mode:
```
********** NEW BUILD **********
```
> Make the beginning of a new build more explicit in watch mode

- bin/common.ml
- bin/compute.ml
- bin/exec.ml
- bin/external_lib_deps.ml
- bin/import.ml
- bin/install_uninstall.ml
- bin/installed_libraries.ml
- bin/main.ml
- bin/print_rules.ml
- bin/printenv.ml
- bin/subst.ml
- bin/target.ml
- bin/target.mli
- bin/utop.ml
- src/dune/main.ml
- src/dune/main.mli
- src/dune/process.ml
- src/dune/scheduler.ml
- src/dune/scheduler.mli
- src/stdune/log.ml
- src/stdune/log.mli
- test/expect-tests/common/dune_tests_common.ml
There is only one log file so there is no point allowing multiple `Log.t` values. Additionally, this change makes it easier to log things at random places.
> Make Log.t a global variable

- src/dune/build.ml
- src/dune/build.mli
- src/dune/expander.ml
- src/dune/ordered_set_lang.ml
- src/dune/ordered_set_lang.mli
Previously, we'd parse :include files based on the syntax. This is no
longer necessary.
> Remove support for jbuild style flags

- src/dune/ordered_set_lang.ml
- src/dune/ordered_set_lang.mli
- src/dune/preprocessing.ml
This is more consistent with how OSL works everywhere. The only field
that didn't satisfy this was as_ppx_flags
> Make OSL fields take standard as default

- src/dune/build_system.ml
Looks like a copy-paste error from the above mkdir_p function.
Signed-off-by: Jakub Staron <jstaron@janestreet.com>
> Do not reuse memo name for assert_exists.

- dune.opam
- dune.opam.template
It's no longer necessary as the build info library fills the information
in.
> Remove dune subst form bootstrap

- doc/dune-files.rst
Stage names are passed as is, so `with-test` should be used.
> Doc: fix typo in stage names

- CHANGES.md
- bin/upgrade.ml
- src/dune/upgrader.boot.ml
- src/dune/upgrader.ml
- src/dune/upgrader.mli
We make sure that a file is tracked by git before doing git operations to it.
This makes $ dune upgrade work better for vendored dirs.
@avsm does this sound like a good fix for #2232
> [upgrader] do not use git for untracked files

- bin/upgrade.ml
- src/dune/findlib/findlib.ml
- src/dune/upgrader.ml
Findlib defined libraries without an archive field will now have both `native` and `bytes` modes. On its own, it doesn't do anything but pave the way for reviving inheriting the modes is working correctly.
> Libraries without archives

- src/dune/action_exec.ml
- src/dune/action_exec.mli
- src/dune/build_system.ml
Given that I confused myself about this, I figured that we could use this opportunity to make things a little more bulletproof. Now we compute the action's context and use it to extract the env for the digest. We no longer need to construct the correct environment twice.
By the way, I just noticed that we aren't taking the digest of the un-sandboxed action. It's probably harmless but a bit confusing.
@staronj might want to take a look as well
> Use correct environment in one place

- doc/overview.rst
Since #2531, there is no longer a Coq section in the documentation, and since #2535 there is no longer a Coq sub-section in the "Other topics" section.  Coq's documentation is only available through its dedicated stanzas.  This means that it is much harder to discover that Dune supports not just OCaml and Reason, but also Coq.  This is an attempt to fix that, although it might be controversial, especially given that Coq's support is still very much a work-in-progress.
> Mention Coq in the overview.

- src/dune/compilation_context.ml
- src/dune/compilation_context.mli
- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/lib_rules.ml
- src/dune/mode.ml
- src/dune/mode.mli
This PR makes it so that `(modes ..)` settings are inherited in dependencies. This is important when depending on libraries such as `compiler-libs.toplevel`, which only provide a bytecode archive.
Some questions:
* The hack for libraries without archives is quite ugly. Shall we make it specific to compiler-libs perhaps?
* Do we need this for executables as well? If so, I would make that a separate PR.
> Inherit modes for libraries

- test/blackbox-tests/test-cases/dune-cache/run.t
It looks like dune memory does not update the digest cache when retrieving the artifact from cache.
Note that the obvious fix of calling `Cached_digest.refresh` on `file.in_the_build_directory` doesn't work because `file.in_the_build_directory` (incorrectly) counts as an external path.
We should probably change the promotion to no longer write absolute paths in there.
> add a test for the dune memory cache invalidation

- test/blackbox-tests/test-cases/dune-cache/run.t
- test/blackbox-tests/test-cases/dune-cache/stat.sh
This makes the tests pass on OSX.
Fix #2611
> Use gstat on Osx for the dune cache tests

- src/dune/lib.ml
The old code was a bit fishy to me because it was handling the default implementations only to throw them away later. The new implementation only handles the default implementations when it knows it will use them.
> Refactor variant closure

- src/dune/build_system.ml
- src/dune/build_system.mli
- src/dune/file_tree.ml
- src/dune/hooks.ml
- src/dune/hooks.mli
- src/dune/main.ml
- src/dune/scheduler.ml
- src/dune/scheduler.mli
- src/dune/stats.boot.ml
- src/dune/stats.ml
- src/dune/stats.mli
- src/stdune/console.ml
- src/stdune/console.mli
- test/blackbox-tests/test-cases/trace-file/run.t
This PR adds a a new option `--debug-rule-batches` that causes Dune to display the number of rules that become ready to fire at once. If this number is high, we can expect to be able to efficiently prefetch things for the shared artifact cache. So far it seems that this number is high right from the start, which is good.
> Record number of evaluated rules in the trace file

- doc/dune-files.rst
The documentation seems to lack a sentence stating how to generate the opam files with `(generate_opam_files true)`
> [Doc] Add some precisions about when opam files are generated

- src/memo/memo.ml
- src/memo/memo.mli
- test/expect-tests/memo/memoize_tests.ml
This argument can be used to create values that automatically expire at
the end of every run.
@diml @aalekseyev second attempt.
> [memo] Add ~lifetime argument to Memo.create

- src/dune/lib.ml
In the case when there are conditional dependencies, we should not be
dropping the normal dependencies.
This should fix the bug @avsm encountered on slack
> Fix dependencies incorrectly dropped when specified with select

- src/dune/file_tree.ml
- src/dune/file_tree.mli
- src/dune/upgrader.ml
- src/dune/vcs.ml
- src/dune/vcs.mli
This is a preliminary clean up PR before I add memoization. The function was getting out of hand, especially with ocamlformat's aggressive indentation. I also simplifies a couple of things (vcs check and nested conditionals) along the way.
> Refactor File_tree.load

- bin/dune
- boot/dune
- boot/libs.ml
- dune-project
- src/dune/bootstrap_info.ml
- src/dune/bootstrap_info.mli
- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/exe_rules.ml
- src/stdune/dyn.ml
- src/stdune/pp.ml
- src/stdune/pp.mli
- test/expect-tests/action_tests.ml
- test/expect-tests/catapult/catapult_tests.ml
- test/expect-tests/dune_file_tests.ml
- test/expect-tests/dune_lang/sexp_tests.ml
- test/expect-tests/fiber/fiber_tests.ml
- test/expect-tests/findlib_tests.ml
- test/expect-tests/memo/memoize_tests.ml
- test/expect-tests/ocamlobjinfo_tests.ml
- test/expect-tests/stdune/map_tests.ml
- test/expect-tests/stdune/path_tests.ml
This PR adds a rule to generate the list of libraries we put in the bootstrap file. This will be one less thing to maintain by hand while we work on dune.
At the moment the list is still duplicated in bootstrap.ml because putting `#use ...` makes ocamlformat unhappy. But we will use it for the new bootstrap procedure.
> Generate the list of libraries for the bootstrap

- doc/dune-libs.rst
It was pointing to the previous location.
> Update link to configurator API in docs

- src/dune/build_system.ml
- src/dune/dune_load.ml
- src/dune/file_tree.ml
- src/dune/file_tree.mli
- src/dune/upgrader.ml
This function is just as a helper function that is bloating the API. We have decided to move to a more spartan API by default.
> Remove File_tree.fold

- src/dune_manager/dune_manager.ml
- test/blackbox-tests/dune.inc
- test/blackbox-tests/test-cases/dune-cache-symlink/run.t
- test/blackbox-tests/test-cases/dune-cache-symlink/stat.sh
Although we refuse symlinks, keep caching. Improve resilience to the caching socket getting dropped.
> Cache: don't choke on symlinks.

- src/dune/dune_package.ml
Bootstrap was fixed to properly account for dependencies in the mli
I'm making this a PR mostly just to make sure it doesn't break in CI.
> Remove hack that was added just for bootstrap

- src/dune/dune_load.ml
- src/dune/file_tree.ml
- src/dune/file_tree.mli
- src/dune/upgrader.ml
I added a specialized folding function that will be the only one to report progress. This implementation is completely memoization agnostic and should work with the memoized code without modification.
This is slightly different from what we talked about but seems like an even simpler way of solving the problem. In this case, we'll be reporting the progress even in polling mode but if anything that is an improvement.
> Report progress only in dune_load or upgraded

- doc/concepts.rst
- src/dune/action.ml
- src/dune/action_ast.ml
- src/dune/action_dune_lang.ml
- src/dune/action_exec.ml
- src/dune/action_intf.ml
- src/dune/action_mapper.ml
- src/dune/action_to_sh.ml
- src/dune/action_unexpanded.ml
- test/blackbox-tests/test-cases/with-exit-codes/run.t
This PR follow a remark by @aalekseyev that the current semantics of `with-exit-codes` are not quite OK: in `(with-exit-codes 2 (progn (exit 2) do_thing)`, `do_thing` will run, which is not expected.
Some alternatives were discussed:
1) fix the behaviour: this means propagating the exit code of each `run` so that the enclosing action can decide whether to continue sequentially or simply return until the nearest `with-exit-codes` handler is found.
2) switch to a special action `(with-accepted-exit-codes <codes> <prog> <args>)`
3) add an optional argument to `run` to specify accepted exit codes.
I investigated 1), but the change seemed to complicate the code throughout simply to support this feature. It wasn't clear to me that the tradeoff was worth it. On the other hand, extending the …
> restrict with-exit-codes to "run", "bash" and "system"

- src/dune/case_lang.ml
- src/dune/case_lang.mli
This is the WIP after the discussion in #1682. The idea is to implement the example given in:
```
(flags -w 1 (per_file
(foo.ml -> -w 2)
(bar.ml -> -w 3)))
```
Except that it would look like:
```
(flags
-w 1
(per_file
(match
(foo.ml -> -w 2)
(bar.ml -> -w 3)))
```
The idea is that the generalized `match` will be useful in other contexts so I've made the element re-usable.
I'm trying to implement the above suggestion as being equivalent to:
```
(flags
(per_file
(match (* -> -w 1))
(per_file
(match
(foo.ml -> -w 2)
(bar.ml -> -w 3)))
```
> Add Match_lang.t

- src/dune/file_tree.ml
- test/blackbox-tests/test-cases/github764/run.t
Instead of generating a lazy file system tree, functions which read a
directory are memoized.
This PR is by no means done, and I realize that we need `Memo.Cell.t` before it's really usable but I'd like to push through anyway not to lose the progress I've made a couple of weeks ago.
There are three things left to do:
~Implement `Memo.Cell.t` will be done in a separate PR at first~ <- This one will be done separately.
The last two points I need some advice on. IIRC, there was a suggestion to have a memoized function `val dirs_visited : Path.t -> File.Set.t`, but I'm not entirely sure how that's going to work.
> Re-implement File_tree on top of memoization

- src/dune/compilation_context.ml
- src/dune/compilation_context.mli
- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/install_rules.ml
- src/dune/lib_archives.ml
- src/dune/lib_rules.ml
- src/dune/mode.ml
- src/dune/mode.mli
- src/dune/virtual_rules.ml
- test/blackbox-tests/test-cases/meta-gen/run.t
This is my attempt at fixing 2295 which unfortunately failed. The issue is that my validation against the closure is too eager and breaks existing builds (as shown in the tests).
Moving on, I think the right approach is to stick this validation when we calculate the closure itself. So the closure wouldn't just compute the list of libraries but also which modes its available for:
```
type status =
| Available
| Unavailable of Lib.t (* library that doesn't have the closure *)
type closure =
{ closure : Lib.t list Or_exn.t
; modes : status Mode.Dict.t
}
```
@diml does the above sound reasonable?
This PR isn't meant to be merged but I'll cherry pick some useful bits from it to master.
In any case, I don't think we should delay 2.0 for this.
> Attempt to address #2295

- src/dune/dune_file.ml
- src/dune/lib_file_deps.mli
- test/blackbox-tests/test-cases/foreign-library/run.t
- test/blackbox-tests/test-cases/foreign-stubs/run.t
This fixes #2765.
We now run all foreign archive tests with sandboxing.
The rest of the testsuite still has plenty of failures when run with `DUNE_SANDBOX=symlink`.
> Make foreign archives work with sandboxing

- doc/dune-files.rst
This fixes an omission in #2659.
> [docs] Add a missing section about the foreign_library stanza

- doc/usage.rst
> Doc: default alias is "all" in dune 2

- src/dune/opam_create.ml
- src/dune/package.ml
- src/dune/package.mli
- test/blackbox-tests/test-cases/dune-project-meta/run.t
- test/blackbox-tests/test-cases/dune-project-meta/test-fields-with-override/dune-project
See https://github.com/ocaml/dune/pull/2774#issuecomment-544378242
This makes it so that global `homepage` and `bug_reports` fields take precedence over the per-package ones, even when they are inferred from the `source` field.
> Fix the precedence of homepage, bug_reports per-package fields

- src/dune/lib.ml
- test/blackbox-tests/test-cases/byte-code-only/run.t
> Make build-info work in bytecode-only builds (fixes #2777)

- src/memo/memo.ml
- src/memo/memo.mli
- src/memo/store.ml
Custom stores allow a user of [Memo] to pick the data structure to store
the memoization table for a particular function.
@aalekseyev if this is the right way to implement this, I will add some tests as wel.
Fix #2753
> Add support for custom stores

- HACKING.md
- bin/common.ml
- bin/external_lib_deps.ml
- bin/upgrade.ml
- otherlibs/configurator/src/v1.mli
- plugin/jbuild_plugin.mli
- src/dune/action_intf.ml
- src/dune/context.mli
- src/dune/dune_file.ml
- src/dune/dune_file.mli
- src/dune/dune_project.ml
- src/dune/dune_project.mli
- src/dune/lib.mli
- src/dune/menhir.ml
- src/dune/modules_field_evaluator.ml
- src/dune/string_with_vars.mli
- src/dune/sub_system.mli
- src/dune/sub_system_info.mli
- src/jbuild_support/string_with_vars.mli
Just trying to tidy up comments/docs.
While doing this, I also found some leftover unused bits of code related to `jbuild` files, e.g. see changes to `dune_project.ml`.
> Rename jbuild to Dune/dune/[dune] as appropriate

- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/ppx-runtime-dependencies/ppx.ml
- test/blackbox-tests/test-cases/ppx-runtime-dependencies/run.t
This test exposes a bug in dependency cycle detection, where `ppx_runtime_libraries` are treated as build dependencies. Hope to find a fix soon.
> Add a test exposing a bug in dependency cycle detection

- src/memo/memo.ml
- src/memo/memo.mli
- src/memo/store.ml
- src/memo/store.mli
- src/memo/store_intf.ml
We only require [to_dyn]. Other requirements are passed through the
store itself.
> [memo] precise input for create_with_store

- src/dune/file_tree.ml
- src/dune/vcs.mli
- src/stdune/fdecl.ml
- src/stdune/fdecl.mli
Previously, watch mode was broken because File_tree.init was called more
than once. Now we allow multiple File_tree.init calls as long as they
are called with the same argument.
> Fix watch mode

- src/dune/exe_rules.ml
- src/dune/foreign.mli
- src/dune/foreign_rules.ml
- src/dune/foreign_rules.mli
- src/dune/lib_rules.ml
- test/blackbox-tests/test-cases/foreign-stubs/run.t
Apparently the initial implementation only supported these fields in `(foreign_library...)`.
> Make [include_dirs] and [extra_deps] work in (foreign_stubs ...)

- src/memo/memo.ml
- src/memo/memo.mli
- test/expect-tests/memo/memoize_tests.ml
A cell is just `Dep_node.t` that callers may use to avoid having to
lookup the input in the store.
----
Looks like my type hackery isn't enough to unify the `get_sync` and `get_async`
functions. I would appreciate a hand here.
> [memo] Introduce Memo.Cell.t

- src/dune/build_system.ml
- src/stdune/list.ml
- src/stdune/list.mli
The current `for_all2` is fragile because it makes it easy to catch things
thrown by `f`. This is almost always unintended. The fix is to make `for_all2`
return a result type.
The second commit just gets rid of this use of `for_all2` in favor `List.equal`
> [stdune] Improve for_all2

- doc/concepts.rst
- src/dune/foreign.ml
- src/dune/foreign.mli
- src/dune/foreign_rules.ml
- test/blackbox-tests/test-cases/foreign-library/run.t
This makes it possible to write `(include_dirs (lib foo))` in foreign stubs declarations, where `foo` is a library name.
Note that at the moment we do not support external dependencies in `include_dir`, which in particular means that `(include_dir (lib base))` fails with the following error:
```
File "expansions/dune", line 4, characters 33-37:
4 |  (include_dirs (lib answer) (lib base))
^^^^
Error: "/usr/local/home/amokhov/code/.opam/default/lib/base" is an external
directory; dependencies in external directories are currently not tracked.
Hint: You can specify "/usr/local/home/amokhov/code/.opam/default/lib/base" as an
untracked include directory like this:
(flags -I /usr/local/home/amokhov/code/.opam/default/lib/base)
```
I will add support for external directories in a separate PR.
> Add support for using library names in (include_dirs...)

- doc/dune-files.rst
I marked this feature as experimental, as @rgrinberg suggested, and added a link to ocamlfdo page, intentionally saying very little else about it. I will update ocamlfdo README with instruction for using it with dune as the other external dependencies are upstreamed.
> Documentation for fdo

- src/dune/foreign_rules.ml
- src/stdune/path.ml
- src/stdune/path.mli
- test/blackbox-tests/dune.inc
- test/blackbox-tests/gen_tests.ml
- test/blackbox-tests/test-cases/foreign-library/run.t
This allows using external directories in `(include_dir ...)` fields of foreign stub declarations.
Note that the current implementation tracks external directories non-recursively which is not ideal. The plan is to implement recursive tracking eventually -- there is a TODO with a couple of pointers.
> Add basic support for external directories in (include_dir ...)

- doc/concepts.rst
- src/dune/dune_file.ml
- src/dune/foreign.ml
- src/dune/foreign.mli
- src/dune/foreign_sources.ml
- src/dune/ordered_set_lang.ml
- src/dune/ordered_set_lang.mli
- test/blackbox-tests/test-cases/cxx-extension/run.t
- test/blackbox-tests/test-cases/duplicate-c-cxx-obj/run.t
- test/blackbox-tests/test-cases/duplicate-c-cxx-obj/same-stanza/dune
- test/blackbox-tests/test-cases/duplicate-c-cxx/run.t
- test/blackbox-tests/test-cases/foreign-stubs/run.t
In the initial implementation of foreign libraries, `standard` meant the empty list of `names`, but a more convenient and consistent (with library `modules`) meaning of `standard` is "all files with the relevant extension", as indicated by @aalekseyev's CR. This patch implements this new meaning of `standard`.
TODO:
> Make [:standard] names more useful in foreign stubs

- test/blackbox-tests/test-cases/foreign-stubs/run.t
The output is non-deterministic causing test failures on some platforms.
> Drop [--display] from C++ tests

- src/stdune/list.mli
Jenga complains about the following tricky dependency structure:
* `list.mli` depends on `result.mli` (due to the use of `Result.t`)
* `result.ml` depends on `list.ml` (due to the use of `List.rev`)
While this is not strictly speaking a cycle, it does confuse Jenga.
/cc @rgrinberg This tricky dependency structure was introduced in this commit: https://github.com/ocaml/dune/commit/1b7078ba69303526d8bfc0a1b4b33d4998f2e8b8
> Fix cyclic-ish dependencies between [list] and [result]
